bitwarden/android

- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/model/JwtTokenDataJson.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavViewModelTest.kt
[PM-11256](https://bitwarden.atlassian.net/browse/PM-11256)
This PR updates the `RootNavViewModel` to display the `RemovePasswordScreen` when appropriate. This completes the Remove Password flow.
<video src="https://github.com/user-attachments/assets/a346e009-7afe-4600-81fe-16328704112a" width="300" /> …
> PM-11256: Add RootNav logic to display Remove Password Screen

- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/util/UserStateJsonExtensions.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepositoryImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/util/UserStateJsonExtensionsTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepositoryTest.kt
[PM-11264](https://bitwarden.atlassian.net/browse/PM-11264)
This PR ensures that a user has a valid timeout action after removing the password.
- 🎨 …
> PM-11264: Ensure user has valid timeout action after migrating to Key Connector

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/util/VaultItemListingStateExtensions.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/util/VaultItemListingStateExtensionsTest.kt
[PM-10917](https://bitwarden.atlassian.net/browse/PM-10917)
This PR addresses a crash that occurs when creating a new cipher from the Empty Collections UI. …
> PM-10917: Fix crash caused when adding an item from a collection

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/auth/AuthNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/checkemail/CheckEmailNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/checkemail/CheckEmailScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/checkemail/CheckEmailViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/checkemail/handlers/CheckEmailHandler.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/startregistration/StartRegistrationScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/startregistration/StartRegistrationViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/checkemail/CheckEmailScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/checkemail/CheckEmailViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/startregistration/StartRegistrationScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/startregistration/StartRegistrationViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-11270
- Hide the new changes for the onboarding flow designs behind feature flags in the screens used for new email verification too 
- this is part one, the first two screens (start and check email)
https://github.com/user-attachments/assets/be8b2f23-bb74-4004-b0c9-d2a001ab910e
- ❓ …
> [PM-11270] Hide all new UI behind onboarding flow flag.

- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/api/AuthenticatedOrganizationApi.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/service/OrganizationService.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/service/OrganizationServiceImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/datasource/network/service/OrganizationServiceTest.kt
PM-11265
This PR deletes the `leaveOrganization` API from the app. The feature is not going to be used and is not needed. …
> PM-11265: Remove the leave organization API

- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/model/SyncResponseJson.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/datasource/network/service/SyncServiceTest.kt
[PM-11273](https://bitwarden.atlassian.net/browse/PM-11273)
This PR replaces the `useKeyConnector` key with the `keyConnectorEnabled` key. While the sync response does still get the `useKeyConnector` value, it is not accurate and resulted in bugs. …
> PM-11273: Update the 'useKeyConnector' with 'keyConnectorEnabled'

- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/model/Organization.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/util/SyncResponseJsonExtensions.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/util/UserStateJsonExtensions.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/util/AuthDiskSourceExtensionsTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/util/SyncResponseJsonExtensionsTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/util/UserStateJsonExtensionsTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/datasource/network/model/SyncResponseProfileUtil.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/removepassword/RemovePasswordViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/util/CipherViewExtensionsTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/movetoorganization/VaultMoveToOrganizationViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/movetoorganization/util/VaultMoveToOrganizationExtensionsTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/vault/util/UserStateExtensionsTest.kt
[PM-11299](https://bitwarden.atlassian.net/browse/PM-11299)
This PR addresses a bug where after password removal, the `SetPasswordScreen` would appear. This was caused because we relied on the `hasManageResetPasswordPermission` flag form the `TrustedDevuceOption` but we must derive this value ourselves. …
> PM-11299: Update the userState to properly parse the hasManageResetPasswordPermission flag

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/completeregistration/CompleteRegistrationScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/completeregistration/CompleteRegistrationViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/completeregistration/CompleteRegistrationScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/completeregistration/CompleteRegistrationViewModelTest.kt
Part 2 of https://bitwarden.atlassian.net/browse/PM-11270
- Hide new UI on complete registration screen behind feature flag.
https://github.com/user-attachments/assets/1f2195a8-b9f3-4ab0-ae41-55eb0c67d543 …
> [PM-11270] hide new UI in complete registration screen behind flag pt. 2

- app/src/main/java/com/x8bit/bitwarden/data/vault/manager/VaultLockManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/manager/VaultLockManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavViewModelTest.kt
[PM-10899](https://bitwarden.atlassian.net/browse/PM-10899)
This PR addresses a bug where after closing the app with a TDE user, the app would return to the `TrustedDevice` screen because the user was not being properly logged-out from their timeout action. …
> PM-10899: Fix user not being logged out properly on app restart

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/util/VaultUnlockTypeExtensions.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenPasswordField.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/util/VaultUnlockTypeExtensionsTest.kt
Support keyboard Done event as CTA Unlock on Pin\Master Password unlock screen
https://github.com/bitwarden/android/issues/3680
Better UX
| As is| Can be PWD | Can be PIN |
|--------|--------|--------|
| ![keyboard_actions_as_is](https://github.com/user-attachments/assets/c2154718-e865-4217-b5a7-1323521fc0b1) | ![keyboard_actions_pwd](https://github.com/user-attachments/assets/5a33144a-d46b-4abf-9f6e-488e620be9ce) | ![keyboard_actions_pin](https://github.com/user-attachments/assets/55712f39-5145-4564-b2d0-39183221eb0d) | …
> [PM-10685] Support keyboard Done event as CTA Unlock on Pin\Master Password unlock screen

- app/src/main/java/com/x8bit/bitwarden/ui/platform/manager/permissions/PermissionsManager.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/manager/permissions/PermissionsManagerImpl.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/manager/permissions/FakePermissionManager.kt
This PR addresses a typo in the codebase where the method `shouldShowRequestPermissionRationale` was incorrectly named as `shouldShouldRequestPermissionRationale`. 
- Renamed the method `shouldShouldRequestPermissionRationale` to the correct name `shouldShowRequestPermissionRationale`.
- Updated all instances where the incorrect method name was used.
This change should improve code readability and prevent any potential confusion or errors related to this method.
Thank you for your consideration!
> [PM-11307] Fix typo in method name: shouldShouldRequestPermissionRationale

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/button/BitwardenTextButton.kt
N/A
This PR updates the internal padding on the `BitwardenTextButton` to be consistent with all other Bitwarden buttons in the app. This should make the buttons slightly shorter.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/f3197d37-bf49-4964-b3e8-a862f346eff5" width="300" /> | <img src="https://github.com/user-attachments/assets/ade59b23-cdec-444e-9440-b0fb1a382f6f" width="300" /> | …
> Update internal BitwardenTextButton padding to be consistent with all Bitwarden Buttons

- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
[PM-11354](https://bitwarden.atlassian.net/browse/PM-11354)
This PR removes the logic to store the user key after completing a login with TDE. The `asymmetricalKey` that we have at that point is not the correct key to store and it causes errors when unlocking the vault with a password. The real `userKey` is already stored from the identity response and does allow the user to login via password.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/2a2d35a0-605f-4821-81f5-755dc2b85066" width="300" /> | <video src="https://github.com/user-attachments/assets/6a5f3661-aaaa-4d9d-b2fc-21b051bf1b9d" width="300" /> |
- Written new unit and / or integration tests where …
> PM-11354: TDE unlock since we already have the correct key from the identity service

- app/src/main/java/com/x8bit/bitwarden/MainViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/SpecialCircumstanceManager.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/SpecialCircumstanceManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/di/ActivityPlatformManagerModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/SpecialCircumstance.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/util/SpecialCircumstanceExtensions.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/completeregistration/CompleteRegistrationScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/completeregistration/CompleteRegistrationViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/login/LoginViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/MainViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/SpecialCircumstanceManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/completeregistration/CompleteRegistrationScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/completeregistration/CompleteRegistrationViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/base/BaseComposeTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/search/SearchViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/loginapproval/LoginApprovalScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-11310
Currently the special circumstance for the complete registration needs to be cleared since it interferes with AuthState related state navigation. The old way we were doing this via `onCleared` in the `CompleteRegistrationViewModel` was causing a conflict with the nav stack emitting a state based nav call after making the explicit call to go to the login screen.
- Categorize a `PreLogin` type of `SpecialCircumstance`
- Add function to manager to handle clearing a special circumstance after successful login.
- Observe user state change to update.
https://github.com/user-attachments/assets/9bd6333b-c424-4984-8ddf-3438e1420504
- Written new unit and / or …
> PM-11310 handle email registration special circumstance after successful login

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/auth/AuthNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/login/LoginScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/login/LoginViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/trusteddevice/TrustedDeviceEncryptionNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/login/LoginViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-10902
Base 64 encode password when passing it to the 2FA screen to prevent corruption when it includes characters that should be escaped for URL safety.
issue and …
> [PM-10902] Base64 encode sensitive 2FA nav args

- app/build.gradle.kts
- app/src/main/java/com/x8bit/bitwarden/MainActivity.kt
- app/src/main/java/com/x8bit/bitwarden/MainViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/FeatureFlagOverrideDiskSource.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/FeatureFlagOverrideDiskSourceImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/di/PlatformDiskModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/DebugMenuFeatureFlagManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/FeatureFlagManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/di/PlatformManagerModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/FlagKey.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/DebugMenuRepository.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/DebugMenuRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/di/PlatformRepositoryModule.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/components/FeatureFlagListItems.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/di/DebugMenuModule.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/manager/DebugLaunchManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/manager/DebugMenuLaunchManager.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavScreen.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/values/strings_non_localized.xml
- app/src/test/java/com/x8bit/bitwarden/MainViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/disk/FeatureFlagOverrideDiskSourceTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/DebugMenuFeatureFlagManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/repository/DebugMenuRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/manager/DebugLaunchManagerTest.kt
https://bitwarden.atlassian.net/browse/PM-11224
- Allow for a special UI to appear to let a dev/tester/qa have access to changing feature flags states in build marked with special flag in config
- Add build config flag to enable debug menu
- If this flag it true use a decorator version of the `FeatureFlagManager` which uses the saved overridden values
- Add basic UI to toggle existing feature flag Boolean values to `true` or `false`
https://github.com/user-attachments/assets/4453ec47-5ede-4e4d-a873-42cd3153781d
*New UI now looks like:*
- Communicated to DevOps any …
> PM-11224 Add menu to update feature flags with overridden values in real time

- app/src/debug/AndroidManifest.xml
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/x8bit/bitwarden/AccessibilityActivity.kt
- app/src/main/java/com/x8bit/bitwarden/BitwardenAppComponentFactory.kt
- app/src/main/java/com/x8bit/bitwarden/data/accessibility/di/AccessibilityModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/accessibility/manager/AccessibilityAutofillManager.kt
- app/src/main/java/com/x8bit/bitwarden/data/accessibility/manager/AccessibilityAutofillManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/tiles/BitwardenAutofillTileService.kt
- app/src/test/java/com/x8bit/bitwarden/data/accessibility/manager/AccessibilityAutofillManagerTest.kt
[PM-11483](https://bitwarden.atlassian.net/browse/PM-11483)
This PR adds the `BitwardenAutofillTileService` as a baseline for the Autofill fallback feature. …
> PM-11483: Create AutofillTileService

- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/model/VaultUnlockedNavBarTab.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-11214
- If the tab the user is already on is clicked again, popBack to the top of the graph, this unblocks interaction with the sub screens as mentioned in the defect. 
**NOTE** Key difference is on the settings tab where tapping settings again will take you back to the start of the graph**
I do have another fix locked and loaded where the VM keeps hold of a `SelectedBottomTab` enum and no interaction with the navController takes place if its the currently selected one, this matches what is seen today in the settings screen where the user would just stay on the submenu view.
https://github.com/user-attachments/assets/cecfe155-b13c-4f32-bf88-bbe938c9d74c
- …
> PM-11214 change navoptions to support single top without retaining VM

- app/src/main/java/com/x8bit/bitwarden/data/autofill/di/AutofillModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/manager/AutofillCompletionManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/manager/AutofillTotpManager.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/manager/AutofillTotpManagerImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/autofill/manager/AutofillCompletionManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/autofill/manager/AutofillTotpManagerTest.kt
[PM-11616](https://bitwarden.atlassian.net/browse/PM-11616)
This PR moves the logic for copying the TOTP code to the users clipboard into it's own class so it can be reused for accessibility-based autofill in the future. …
> PM-11616: Manage totp logic in AutofillTotpManager

- app/src/main/java/com/x8bit/bitwarden/data/auth/manager/UserLogoutManager.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/manager/UserLogoutManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/manager/UserLogoutManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt
[PM-11642](https://bitwarden.atlassian.net/browse/PM-11642)
This PR updates the logout process on invalid security stamp by performing a soft-logout instead of a full-logout. …
> PM-11642: Security stamp soft logout

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/di/AccessibilityModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/manager/LauncherPackageNameManager.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/manager/LauncherPackageNameManagerImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/autofill/accessibility/manager/LauncherPackageNameManagerTest.kt
[PM-11643](https://bitwarden.atlassian.net/browse/PM-11643)
This PR adds the `LauncherPackageNameManager` which queries the OS for the any launcher apps the user may be using. …
> PM-11643: Add LauncherPackageNameManager for tracking launcher apps

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
N/A
This PR removes the unused `shouldFinishOnComplete` property from the `VaultItemListingState` class. While this property was being set, it was never being referenced. …
> Remove unsued shouldFinishOnComplete property

- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/di/AccessibilityModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/model/Browser.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/model/FillableFields.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/parser/AccessibilityParser.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/parser/AccessibilityParserImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/util/BrowserUtil.kt
- app/src/main/res/xml/autofill_service_configuration.xml
- app/src/test/java/com/x8bit/bitwarden/data/autofill/accessibility/parser/AccessibilityParserTest.kt
[PM-11484](https://bitwarden.atlassian.net/browse/PM-11484)
This PR adds the logic for parsing a URI from the `AccessibilityNodeInfo` provided from the `AccessibilityService`. …
> PM-11484: Add logic to parse URI from AccessibilityNodeInfo

- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/FlagKey.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepository.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/components/FeatureFlagListItems.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityViewModel.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/FlagKeyTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityViewModelTest.kt
https://livefront.atlassian.net/browse/BITAU-107
Add UI and feature flag for authenticator syncing.
https://github.com/user-attachments/assets/059c0952-75e2-4c58-9b51-8dfa7ecd9d6e …
> BITAU-107 Add Feature Flag and UI for Authenticator Syncing

- app/src/main/java/com/x8bit/bitwarden/MainViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSource.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSourceImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepository.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepositoryImpl.kt
- app/src/test/java/com/x8bit/bitwarden/MainViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSourceTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/disk/util/FakeSettingsDiskSource.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepositoryTest.kt
https://bitwarden.atlassian.net/browse/PM-11714
- record each user id that has logged in on the device to keep track of this on per userId basis.
- 🎨 …
> PM-11714 record if a user has signed in on device before.

- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/model/ServerConfig.kt
N/A
This PR adds the missing `SerialName` annotations to the `ServerConfig` class. …
> Add missing SerialName annotations

- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/disk/AuthDiskSource.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/disk/AuthDiskSourceImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepositoryImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/datasource/disk/AuthDiskSourceTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/datasource/disk/util/FakeAuthDiskSource.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepositoryTest.kt
https://livefront.atlassian.net/browse/BITAU-108
The goal here is to generate and store a user specific encryption key whenever the user enables authenticator syncing. 
The presence of this key is how other services will know whether or not to share the user's TOTP URIs via `BridgeService`.
N/A
- 🤔 …
> BITAU-108 Store Authenticator Sync Key

- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreen.kt
N/A
This PR fixes the Slider in the generator screen. The slider looked weird because of the recent Compose BOM update to 2024.09.00.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/b7c938a0-9d22-4f62-9b78-b974c4bf7f84" width="300" /> | <img src="https://github.com/user-attachments/assets/1c67e0e7-c2be-40bc-aeb0-c05c2bc20cf8" width="300" /> |  …
> Update Slider UI after Compose BOM update

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupAutoFillNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupAutoFillViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupAutofillScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/handlers/SetupAutoFillHandler.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupAutoFillViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupAutofillScreenTest.kt
https://bitwarden.atlassian.net/browse/PM-10630
- Setup Auto-Fill screen UI set and ready to be integrated with the new Onboarding flow
- VM functions setup
- Dialogs in place …
> PM-10630 setup autofill UI and interactions set up

- app/src/main/java/com/x8bit/bitwarden/data/platform/processor/BridgeServiceProcessorImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/processor/BridgeServiceProcessorTest.kt
https://livefront.atlassian.net/browse/BITAU-102
Make sure we no-op all `BridgeService` calls under android API level 12.
N/A …
> BITAU-102 Return null BridgeService when API level is below 12

- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/FlagKey.kt
https://livefront.atlassian.net/browse/BITAU-160
I originally used the wrong flag name. This fixes that!
N/A …
> BITAU-160 Update feature flag name for authenticator sync

- app/src/debug/AndroidManifest.xml
- app/src/main/java/com/x8bit/bitwarden/BitwardenAppComponentFactory.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/BitwardenAccessibilityService.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/di/AccessibilityModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/processor/BitwardenAccessibilityProcessor.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/processor/BitwardenAccessibilityProcessorImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/util/AccessibilityNodeInfoExtensions.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/accessibility_service.xml
- app/src/test/java/com/x8bit/bitwarden/data/autofill/accessibility/processor/BitwardenAccessibilityProcessorTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/autofill/accessibility/util/AccessibilityNodeInfoExtensionsTest.kt
[PM-11487](https://bitwarden.atlassian.net/browse/PM-11487)
This PR adds the `BitwardenAccessibilityService` and `BitwardenAccessibilityProcessor` for handling autofill vial accessibility. …
> PM-11487: Initial accessibility service and processor for handling autofill

- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/model/OrganizationDomainSsoDetailsResponseJson.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/datasource/network/service/OrganizationServiceTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
https://bitwarden.atlassian.net/browse/PM-10905
- Automatically navigate to the SSO login page for users who are part of organization with a "claimed domain"
- The cause of this was the the field `ssoRequired` being "required" by our JSON serializer but not in the response for every account. Since we are not using it I removed it and other unused fields. Can also revert and just make optional `?`
https://github.com/user-attachments/assets/f17bccbd-ce5b-4acf-b0be-b46f66d2ad7a
- Updated any necessary documentation or …
> [PM-10905] Update JSON model to match API

- app/src/main/java/com/x8bit/bitwarden/MainActivity.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/di/AccessibilityModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/di/ActivityAccessibilityModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/manager/AccessibilityActivityManager.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/manager/AccessibilityActivityManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/manager/AccessibilityEnabledManager.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/manager/AccessibilityEnabledManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepository.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/di/PlatformRepositoryModule.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/manager/intent/IntentManager.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/manager/intent/IntentManagerImpl.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/data/autofill/accessibility/manager/AccessibilityActivityManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/autofill/accessibility/manager/AccessibilityEnabledManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillViewModelTest.kt
PM-11488
This PR adds a switch to the autofill settings UI for enabling the accessibility service.
<video src="https://github.com/user-attachments/assets/f03d5088-7ffb-44fe-b6e2-1833152a4306" width="350" /> …
> PM-11488: Add a switch to the autofill settings UI for enabling the accessibility service

- app/src/main/java/com/x8bit/bitwarden/BitwardenAppComponentFactory.kt
- app/src/main/java/com/x8bit/bitwarden/BitwardenLegacyAppComponents.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/manager/AccessibilityActivityManagerImpl.kt
N/A
This PR adds the `BitwardenLegacyAppComponents` for legacy app component names. …
> Add BitwardenLegacyAppComponents for legacy app component names

- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/model/SyncResponseJson.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/datasource/network/model/SyncResponseProfileUtil.kt
[PM-12240](https://bitwarden.atlassian.net/browse/PM-12240)
This PR removes all the unused fields from the Sync responses permissions block, this avoids a deserialization error that has occurred because some of the fields no longer exist. …
> PM-12240: Remove unused permissions from the sync response

- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/search/SearchViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/search/SearchViewModelTest.kt
PM-11485
This PR adds additional routing logic for accessibility-base autofill in the app. This new logic supports searching for a cipher when using accessibility autofill. …
> PM-11485: Add routing logic to handle searching during accessibility autofill

- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/DebugMenuRepository.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/DebugMenuRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/di/PlatformRepositoryModule.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuViewModel.kt
- app/src/main/res/values/strings_non_localized.xml
- app/src/test/java/com/x8bit/bitwarden/data/platform/repository/DebugMenuRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-12289
- allow for a way to re-enter the onboarding flow outside of creating a new account or logging in a new user.
https://github.com/user-attachments/assets/8534e615-a81e-4e58-8b84-4f7b5d509a2b …
> [PM-12289] add onboarding status override to debug menu

- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/manager/AccessibilityActivityManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/util/ContextExtensions.kt
- app/src/test/java/com/x8bit/bitwarden/data/autofill/accessibility/manager/AccessibilityActivityManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/autofill/accessibility/util/ContextExtensionsTest.kt
N/A
This PR creates a reusable extension for determining if the accessibility service is enabled. It is currently only used in one spot but will be used in other places soon. …
> Create reusable isAccessibilityServiceEnabled extension

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupAutoFillViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupCompleteNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupAutoFillViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupAutofillScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupCompleteViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-12076
- Add remaining areas for updating onboarding status to complete successful navigation of onboarding flow
builds on #3921  …
> PM-12076 remaining state based navigation linkup for onboarding

- app/src/main/java/com/x8bit/bitwarden/data/tiles/BitwardenAutofillTileService.kt
[PM-12297](https://bitwarden.atlassian.net/browse/PM-12297)
This PR adds a alert dialog to the `BitwardenAutofillTileService` whenever a user attempts to invoke the service but the `BitwardenAccessibilityService` is not enabled.
<video src="https://github.com/user-attachments/assets/0963f4e8-f5d3-4226-9328-647dc9225330" width="300" />
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general …
> PM-12297: Add accessibility service alert for autofill tile

- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/di/AccessibilityModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/manager/AccessibilityNodeInfoManager.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/manager/AccessibilityNodeInfoManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/model/FillableFields.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/model/KnownUsernameField.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/parser/AccessibilityParser.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/parser/AccessibilityParserImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/processor/BitwardenAccessibilityProcessorImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/util/AccessibilityNodeInfoExtensions.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/util/KnownUsernameFieldUtil.kt
- app/src/test/java/com/x8bit/bitwarden/data/autofill/accessibility/manager/AccessibilityNodeInfoManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/autofill/accessibility/parser/AccessibilityParserTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/autofill/accessibility/processor/BitwardenAccessibilityProcessorTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/autofill/accessibility/util/AccessibilityNodeInfoExtensionsTest.kt
[PM-11486](https://bitwarden.atlassian.net/browse/PM-11486)
This PR adds all the logic for parsing out the username and password fields that need to be populated. …
> PM-11486: Parse the Accessibility Nodes for username and password fields

- app/src/debug/AndroidManifest.xml
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillScreen.kt
[PM-12014](https://bitwarden.atlassian.net/browse/PM-12014)
This PR moves the manifest items for accessibility autofill from the debug manifest to the main manifest, allowing them to be used in all build variants. The UI switch for enabling accessibility autofill has also been enabled in non-debug builds. …
> PM-12014: Enable accessibility autofill outside of debug builds

- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/VaultRepository.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt
https://livefront.atlassian.net/browse/BITAU-108
I had previously missed this requirement for this ticket:
"A function is added to `VaultRepository` / `VaultLockManager` that allows for this per-user key to be used to unlock a particular user's vault."
N/A …
> BITAU-108 Add unlockWithAuthenticatorSyncKey to VaultRepository 

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupUnlockViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupUnlockViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-12319
- If the auto fill service is already enabled on the device a user is onboarding on, we should skip that step in the onboarding flow.
https://github.com/user-attachments/assets/b4a73be7-bf83-4dae-8f4c-89d79488be6a …
> [PM-12319] Skip Auto-fill setup if already enabled.

- app/src/main/java/com/x8bit/bitwarden/data/tiles/BitwardenAutofillTileService.kt
N/A
This PR addresses a crash I discovered in the autofill service when launching the `AccessibilityActivity`. …
> Add FLAG_ACTIVITY_NEW_TASK flag for autofill tile to avoid crash

- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSource.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSourceImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepository.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupAutoFillViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSourceTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/disk/util/FakeSettingsDiskSource.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupAutoFillViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-10631
- when a user clicks the "turn on later" option on the autofill setup screen, if they confirm we want to keep track of that to show the badge later.
issue …
> PM-10631 store when the user selects to turn auto fill on later

- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/processor/BitwardenAccessibilityProcessorImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/util/AccessibilityNodeInfoExtensions.kt
- app/src/test/java/com/x8bit/bitwarden/data/autofill/accessibility/processor/BitwardenAccessibilityProcessorTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/autofill/accessibility/util/AccessibilityNodeInfoExtensionsTest.kt
[PM-12397](https://bitwarden.atlassian.net/browse/PM-12397)
This PR clears the accessibility even when the user clicks the tile but is on the launcher or Bitwarden app. …
> PM-12397: Clear accessibility action when on launcher or Bitwarden App

- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSource.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSourceImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepository.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupUnlockViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSourceTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/disk/util/FakeSettingsDiskSource.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupUnlockViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-10622
- when the use selects to skip the onboarding step of setting up an unlock option, store that selection so we can show the badge on the settings later. …
> [PM-10622] Handle the skip unlock step in the onboarding, storing when the user selects to do so.

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenPasswordField.kt
[PM-9901](https://bitwarden.atlassian.net/browse/PM-9901)
All password fields in the app should use the sensitive info font in the app.
- 🎨 (`:art:`) …
> PM-9901: Use sensitive text font for passwords

- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-10118
- User selected generation type should be sync'd across all versions of generator screen.
https://github.com/user-attachments/assets/709a5d17-81ca-4057-ab41-2cad34337fa9 …
> [PM-10118]  update selected generator type when returning to main tab.

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/toggle/BitwardenWideSwitch.kt
N/A
This PR update the `BitwardenWideSwitch` to display the disabled state when needed.
This change is purely cosmetic, the rows were not clickable.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/cd9bb5ee-1b79-484f-b69c-91b4a9d3f99b" width="300" /> | <img src="https://github.com/user-attachments/assets/43a39f68-5834-4ef3-88e9-64c00aa6fdde" width="300" /> |
- 📝 …
> Update switch to represent disabled state

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/fab/BitwardenFloatingActionButton.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/blockautofill/BlockAutoFillScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/folders/FoldersScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/SendScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultScreen.kt
N/A
This PR creates a new `BitwardenFloatingActionButton` to be a base component for easier reusability.
No functional changes went into this PR.
- 🎨 …
> Create new reusable FAB component

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginNavigation.kt
https://bitwarden.atlassian.net/browse/PM-11535
- Prevent crypto error for a SSO user with a MP due to wrongly encoded password being passed to login attempt.
- The way the route was being set  w/o specifying nullable args in the destination: was causing "null" to be decoded and instead of passing `null` to the login function it was attempting to send the resulting string which was incorrect and also was "\<?><?>e" encoded characters.
- 👍 …
> PM-11535 Only add password to 2 factor login path if present

- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/blockautofill/BlockAutoFillScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/SendEmpty.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultNoItems.kt
N/A
This PR replaces the use of raw material buttons with our own `BitwardenFilledTonalButton`.
There should be no functional change in this PR.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/b3d4eab4-7151-42ef-9e83-7c76142d2de0" width="300" /> | <img src="https://github.com/user-attachments/assets/71a12fec-ac46-457a-aed5-0bce6941b6de" width="300" /> |
- 📝 …
> Replace usages of raw button with BitwardenFilledTonalButton

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
[PM-12631](https://bitwarden.atlassian.net/browse/PM-12631)
This PR adds support for processing the accessibility autofill selection after a master password re-prompt.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/eb6688e1-4c91-4c57-ac58-1c6197176d1f" width="300" /> | <video src="https://github.com/user-attachments/assets/546d1a7e-8513-4f7d-97be-3efb430d3d03" width="300" /> | …
> PM-12631: Handle password re-prompt for accessibility autofill

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/masterpasswordguidance/MasterPasswordGuidanceScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/preventaccountlockout/PreventAccountLockoutScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/account/BitwardenAccountSwitcher.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/divider/BitwardenHorizontalDivider.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/row/BitwardenTextRow.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/about/AboutScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/passwordhistory/PasswordHistoryScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultContent.kt
N/A
This PR adds a `BitwardenHorizontalDivider` for theming and reusability purposes. …
> Add Bitwarden Horizontal Divider

- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSource.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSourceImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepository.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepositoryImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSourceTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/disk/util/FakeSettingsDiskSource.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepositoryTest.kt
https://bitwarden.atlassian.net/browse/PM-12594
- Setup logic for showing badges on the main settings tabs and the nested settings menus
- Set up so the changes are observable and update when the values change. …
> PM-12594 Add observable flows to observe badge count changes when corresponding settings update

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/startregistration/StartRegistrationScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/appbar/BitwardenMediumTopAppBar.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/appbar/BitwardenSearchTopAppBar.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/appbar/BitwardenTopAppBar.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/appbar/action/BitwardenOverflowActionItem.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/appbar/action/BitwardenSearchActionItem.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/button/BitwardenFilledIconButton.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/button/BitwardenStandardIconButton.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dialog/BitwardenTimePickerDialog.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dropdown/BitwardenMultiSelectButton.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenPasswordField.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenPasswordFieldWithActions.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/listitem/BitwardenListItem.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/stepper/BitwardenStepper.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/toggle/BitwardenSwitchWithActions.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/passwordhistory/PasswordHistoryListItem.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditCardItems.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditCustomField.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditIdentityItems.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditLoginItems.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditSecureNotesItems.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditUriItem.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/attachments/AttachmentsContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemAttachmentContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemCardContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemCustomField.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemLoginContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultFilter.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/verificationcode/VerificationCodeItem.kt
N/A
This PR adds reusable icon button components.
No visual or functional changes were made in this PR.
- ❌ …
> Add reusable icon button components

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/loginwithdevice/LoginWithDeviceScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/content/BitwardenLoadingContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dialog/BitwardenLoadingDialog.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/indicator/BitwardenCircularProgressIndicator.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/passwordhistory/PasswordHistoryScreen.kt
N/A
This PR adds a customizable loading indicator to be used throughout the app.
Note, that at this time the wrapper does not do anything but it will!
- …
> Add a reusable bitwarden loading indicator

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/stepper/BitwardenStepper.kt
N/A
This PR disables the stepper buttons when the values are at the end of the specified range.
| --- | -- |
| <video src="https://github.com/user-attachments/assets/f95c7c1d-80ba-424f-874d-91bf536dc263" width="300" /> | <video src="https://github.com/user-attachments/assets/7bf125e9-b5ed-41e6-b478-7a8412f459b2" width="300" /> |
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes …
> Disable stepper buttons when they reach the end of range

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dialog/row/BitwardenSelectionRow.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/radio/BitwardenRadioButton.kt
N/A
This PR adds a reusable `BitwardenRadioButton` that can have custom theming applied to it.
There are no functional changes in this PR.
- 🎨 (`:art:`) …
> Add reusable radio button

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/badge/NotificationBadge.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/model/VaultUnlockedNavBarTab.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-12592
https://bitwarden.atlassian.net/browse/PM-12593
- show the count of "settings" notifications in a badge on the bottom nav bar.
https://github.com/user-attachments/assets/2494f010-b63a-4092-b850-88d76bf9e8e0 …
> [PM-12592] & [PM-12593] bottom nav notification dot

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/slider/BitwardenSlider.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreen.kt
N/A
This PR adds a reusable `BitwardenSlider` that can have custom theming applied to it.
There are no functional changes in this PR. …
> Add reusable slider component

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/segment/BitwardenSegmentedButton.kt
N/A
This PR makes some minor adjustments to simplify the `BitwardenSegmentedButton`.
No UI or functional changes were made here. …
> Simplify and clean up segmented button

- app/src/main/java/com/x8bit/bitwarden/data/autofill/util/AutofillIntentUtils.kt
https://bitwarden.atlassian.net/browse/PM-12711
- Restore functionality for regular autofill selection.
- ❌ …
> [PM-12711] Auto-Fill selection bug fix

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/navigation/BitwardenNavigationBarItem.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarScreen.kt
N/A
This PR adds a reusable `BitwardenNavigationBarItem` for custom styling and reusability.
No functional changes were made in this PR.
- 🎨 (`:art:`) …
> Add a reusable Navigation Bar Item

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/button/BitwardenFilledErrorButton.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/button/BitwardenOutlinedErrorButton.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/deleteaccount/DeleteAccountScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/deleteaccountconfirmation/DeleteAccountConfirmationScreen.kt
N/A
This PR renames the `BitwardenErrorButton` to `BitwardenFilledErrorButton` to be more inline with the naming conventions and adds a new `BitwardenOutlinedErrorButton` which will be used in the future.
No functional or visual changes were made in this PR. …
> Add BitwardenOutlinedErrorButton and rename BitwardenErrorButton

- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-12739
Updated maximum number and specials to match [other clients](https://github.com/bitwarden/clients/blob/main/libs/tools/generator/core/src/data/default-password-boundaries.ts) and server 
If minimum value is higher than maximum, set it as new maximum in order to avoid the app to crash in a scenario minimum is higher than maximum
Added tests
- 📝 (`:memo:`) …
> [PM-12739] Updated generator maximum number and specials

- .github/workflows/build.yml
https://bitwarden.atlassian.net/browse/PM-12322
The previous workflow only distributed artifacts when the branch was `main`. This change removes that restriction, allowing artifacts to be distributed from any branch. …
> [PM-12322] Remove branch restriction for distributing to Firebase

- app/src/main/java/com/x8bit/bitwarden/ui/platform/theme/color/BitwardenColorScheme.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/theme/color/ColorScheme.kt
PM-12322
This PR adds the new Bitwarden ColorScheme to the app but does not apply these new colors yet.
- ❌ …
> PM-12322: New color scheme

- app/src/main/java/com/x8bit/bitwarden/ui/platform/theme/BitwardenTheme.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/theme/type/BitwardenTypography.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/theme/type/Typography.kt
N/A
This PR consolidates all text styles in the app under BitwardenTypography and into the BitwardenTheme.
No functional changes were made in this PR and a followup PR will be made to update all references to `MaterialTheme.typography`. …
> Add singular BitwardenTypography to manage all text-styles

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/appbar/BitwardenSearchTopAppBar.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenHiddenPasswordField.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenTextField.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenTextFieldWithActions.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/slider/BitwardenSlider.kt
N/A
This PR updates the text field typography in the app for consistency.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/7259b2bd-941a-4d5c-b2e4-eb693fa0932c" width="300" /> | <img src="https://github.com/user-attachments/assets/e410e0ee-44a4-414d-8531-0220843aabf6" width="300" /> |
- ❓ …
> Clean up text field typography

- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/PinInputDialog.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupUnlockScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingScreenTest.kt
PM-10628
This PR updates the `PinInputDialog` to match designs.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/41411768-6a2d-47f4-9f8b-4ae670221cf7" width="300" /> | <img src="https://github.com/user-attachments/assets/d0589065-2dd2-4c8c-8de5-a4f157bddf58" width="300" /> |
- ❓ (`:question:`) …
> PM-10628: Update Pin Input Dialog UI

- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/sdk/model/Fido2CredentialStoreImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/VaultRepository.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/model/SyncVaultDataResult.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt
https://bitwarden.atlassian.net/browse/PM-13074
This commit introduces an explicit sync for FIDO2 credentials, ensuring they are up-to-date when accessed. It modifies the `Fido2CredentialStoreImpl` to call `syncFido2Credentials` instead of the  generic `sync` method.
Additionally, it adds a new `syncFido2Credentials` method to the `VaultRepository` interface and implements it in `VaultRepositoryImpl`,  allowing for targeted FIDO2 credential synchronization. A new sealed class, `SyncFido2CredentialsResult`, is introduced to represent the outcome of this sync operation. …
> [PM-13074] Explicitly sync FIDO2 credentials

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/toggle/BitwardenUnlockWithPinSwitch.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupUnlockScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityScreenTest.kt
[PM-10628](https://bitwarden.atlassian.net/browse/PM-10628)
This PR updates the title of the master password on restart dialog when enabling pin unlock.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/a8061b51-07f1-4178-982d-7c8e83f6c927" width="300" /> | <img src="https://github.com/user-attachments/assets/c6922406-b509-4131-a9c4-647566c36c11" width="300" /> |
- …
> PM-10628: Update pin dialog title

- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-12739
When the sum of minimum special, numbers, lowercase and uppercase exceeded the minimum length, the length was not being properly adjusted and was throwing an error on the SDK.
This should fix it by using the calculatedMinimumLength that takes variables that into consideration.
- ❓ …
> [PM-12739] adjusted generator length to not be lower than minimum length

- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/DebugMenuRepository.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/DebugMenuRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/di/PlatformRepositoryModule.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuViewModel.kt
- app/src/main/res/values/strings_non_localized.xml
- app/src/test/java/com/x8bit/bitwarden/data/platform/repository/DebugMenuRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-12760
- Allow users of debug menu the ability to revisit the Onboarding carousel flow after already logging in.
https://github.com/user-attachments/assets/e7aebd95-3fe8-4067-81e6-25c0863fc1ac …
> PM-12760 Add way to re-show the onboarding carousel via debug menu

- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/util/UserStateJsonExtensions.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/util/UserStateJsonExtensionsTest.kt
https://bitwarden.atlassian.net/browse/PM-12683
- For SSO users who are not using TDE or Key Connector and have not set their master password we want to ensure the user state gets set correctly that they need to create the password. …
> PM-12683 SSO user needed password set bug

- authenticatorbridge/src/main/java/com/bitwarden/authenticatorbridge/manager/AuthenticatorBridgeManagerImpl.kt
- authenticatorbridge/src/main/java/com/bitwarden/authenticatorbridge/manager/model/AccountSyncState.kt
- authenticatorbridge/src/main/java/com/bitwarden/authenticatorbridge/util/AndroidBuildUtils.kt
- authenticatorbridge/src/test/java/com/bitwarden/authenticatorbridge/manager/AuthenticatorBridgeManagerTest.kt
https://livefront.atlassian.net/browse/BITAU-69
The goal of this PR is to add a check for OS version to the bridge coroutines wrapper. 
N/A
- 🎨 …
> BITAU-69 Check for OS version in AuthenticatorBridgeManager

- app/src/beta/res/values/manifest.xml
- app/src/debug/res/values/manifest.xml
- app/src/main/AndroidManifest.xml
- app/src/release/res/values/manifest.xml
> [!NOTE]
> I tested these two cases:
[X] does this work for release <> release variant communication. 
I tested this with two one-off builds:
- [Main App Build](https://github.com/bitwarden/android/actions/runs/11151653148)
- [Authenticator App Build](https://github.com/bitwarden/authenticator-android/actions/runs/11148769402)
By clicking on the build links, you can see the commit that was build to see what changes are required by the authenticator app. 
[X] what happens under android version S?
- The coroutines wrapper returns an error in this case because we cannot connect to the bridge service. I'm going to add code to the wrapper to handle this expicitly and return a `OSVersionNotSupported` as part of BITAU-69.
https://livefront.atlassian.net/browse/BITAU-99
The goal of this PR is to …
> BITAU-99 Expose and protect `AuthenticatorBridgeService`

- app/src/main/java/com/x8bit/bitwarden/ui/vault/model/TotpData.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/util/TotpIntentUtils.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/util/TotpUriUtils.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/util/TotpIntentUtilsTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/util/TotpUriUtilsTest.kt
N/A
This PR adds logic for parsing a TOTP uri. This logic is not used yet but will be in a forthcoming PR. …
> Add logic for parting a TOTP code from a Uri or Intent

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/card/BitwardenActionCard.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-12773
- When boolean field is stored and true to show notification badges, we want to show the action card in the "Autofill" settings menu.
https://github.com/user-attachments/assets/aa491d8f-8483-437f-b232-f4aee438b8fa …
> PM-12773 show autofill card when user skipped this step in onboarding

- app/src/main/java/com/x8bit/bitwarden/MainViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/SpecialCircumstance.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/util/SpecialCircumstanceExtensions.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/MainViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/util/SpecialCircumstanceExtensionsTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/base/FakeNavHostController.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavViewModelTest.kt
[PM-13019](https://bitwarden.atlassian.net/browse/PM-13019)
This PR adds the special circumstance logic to route the user to the vault listing screen for a totp code intent.
Note that the Android Manifest has not bee updated to support this flow in this PR. That will occur in a future PR.
<video src="https://github.com/user-attachments/assets/d730dd8a-ac1b-4256-8288-7a08200ea47b" width="300" />
- 📝 …
> PM-13019: Add special circumstance to navigate to the vault listing UI for TOTP code

- app/src/test/java/com/x8bit/bitwarden/data/auth/datasource/disk/AuthDiskSourceTest.kt
N/A
Found a random test that I wrote that wasn't running due to missing `@Test` annotation. 
N/A
- ❌ …
> Fix unused test

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/appbar/BitwardenMediumTopAppBar.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dialog/BitwardenTimePickerDialog.kt
- docs/ARCHITECTURE.md
N/A
This PR removes the last references to the `MaterialTheme` in all spots of the app except internal to the `BitwardenTheme`. …
> Remove last references to MaterialTheme

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupAutoFillNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupAutoFillViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupAutofillScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupUnlockViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/SettingsNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlocked/VaultUnlockedNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarScreen.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupAutoFillViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupAutofillScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarScreenTest.kt
https://bitwarden.atlassian.net/browse/PM-13068
- Navigate from the autofill settings to the setup autofill screen if there is the action card.
- Show the setup autofill screen with "non root" UI and behavior.
- This is the final piece to the badging related to the onboarding setup.
https://github.com/user-attachments/assets/085a08e2-3f38-4829-88aa-5e9de7f36f85 …
> PM-13068 Navigate from settings to setup autofill screen.

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/resetpassword/ResetPasswordScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/setpassword/SetPasswordScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/card/BitwardenInfoCalloutCard.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/exportvault/ExportVaultScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/SendContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/SendEmpty.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditItemContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultNoItems.kt
N/A
This PR renames the `BitwardenPolicyWarning` to `BitwardenInfoCalloutCard` to match the name in Figma. Minor font and alignment changes have been made to adhere to the Figma designs as well.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/cedeee26-32e6-4858-812d-e10e3b83c0a0" width="300" /> | <img src="https://github.com/user-attachments/assets/61fe1d88-be70-4e0f-949e-303403be73dd" width="300" /> |
- …
> Rename BitwardenPolicyWarning to BitwardenInfoCalloutCard

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/util/VaultAddItemStateExtensions.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/vault/util/VaultAddItemStateExtensionsTest.kt
https://bitwarden.atlassian.net/browse/PM-12408
Password revision date should be updated when a cipher password is updated …
> [PM-12408] Updating password revision date on password change

- app/src/test/java/com/x8bit/bitwarden/data/vault/datasource/network/service/CiphersServiceTest.kt
N/A
This PR adds logic to log when a test is going to fail due to a boxed result coming from Retrofit.
- ❌ …
> Add logic to identify root cause of flakey test

- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepository.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/auth/AuthNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/enterprisesignon/EnterpriseSignOnNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/enterprisesignon/EnterpriseSignOnScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/enterprisesignon/EnterpriseSignOnViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/trusteddevice/TrustedDeviceEncryptionNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/enterprisesignon/EnterpriseSignOnScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/enterprisesignon/EnterpriseSignOnViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginViewModelTest.kt
[PM-13301](https://bitwarden.atlassian.net/browse/PM-13301)
This PR fixes the key-connector 2fa flow by passing the org identifier through for the proper login logic to be executed.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/4b28ebc4-a0b0-4bc4-b8a2-241555bf5c64" width="300" /> | <video src="https://github.com/user-attachments/assets/55709009-4995-4739-9b53-4592410bdaae" width="300" /> |
- 👍 …
> PM-13301: Fix 2fa with key connector bug

- app/src/main/java/com/x8bit/bitwarden/ui/platform/base/util/ModifierExtensions.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/base/util/TopAppBarScrollBehaviorExtensions.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/appbar/BitwardenMediumTopAppBar.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/appbar/BitwardenSearchTopAppBar.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/appbar/BitwardenTopAppBar.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/search/SearchScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultFilter.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultScreen.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/base/util/TopAppBarScrollBehaviorExtensionsTest.kt
[PM-12668](https://bitwarden.atlassian.net/browse/PM-12668)
This PR adds the divider to the bottom of the TopAppBar everywhere in the app.
<video src="https://github.com/user-attachments/assets/f4dc7024-68a4-41ab-8ece-b3b79032c800" width="300" /> …
> PM-12668: Update TopAppBar divider

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dialog/BitwardenDateSelectButton.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dialog/BitwardenTimeSelectButton.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dropdown/BitwardenMultiSelectButton.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenTextField.kt
N/A
This PR simplifies the styling of the Text Fields in the app and allows the underlying color scheme to handle it.
The main thing is fixing the placeholder text color.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/69e2fcbe-b286-4e1b-9df9-61b24114386b" width="300" /> | <img src="https://github.com/user-attachments/assets/bb0763c0-afa9-41eb-b31e-a81235265c71" width="300" /> | …
> Simplify text field color and textstyles

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/segment/BitwardenSegmentedButton.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/segment/color/BitwardenSegmentedButtonColors.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/theme/shape/BitwardenShapes.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/theme/shape/Shapes.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendContent.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendScreenTest.kt
[PM-13286](https://bitwarden.atlassian.net/browse/PM-13286)
This PR updates the Segmented Control to look like it is part of the TopAppBar.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/45c35730-4bb1-45d7-876c-e0f283438721" width="300" /> | <img src="https://github.com/user-attachments/assets/e70a2848-fdd2-4f54-88c3-e5614fefe54d" width="300" /> |
- 📝 (`:memo:`) …
> PM-13286: Update segmented control to match the TopAppBar

- app/src/main/java/com/x8bit/bitwarden/ui/platform/theme/color/ColorScheme.kt
N/A
This PR fixes the dark mode toggle color.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/884124ed-a820-4855-9f5d-3a88cf58d15d" width="300" /> | <img src="https://github.com/user-attachments/assets/d899b02a-78c4-43b7-8627-abf4d8c99293" width="300" /> |
- 🤔 …
> Fix dark mode toggle color

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/appbar/BitwardenSearchTopAppBar.kt
N/A
This PR fixes the search top app bar divider thickness.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/41010745-c4a9-45e5-853b-6a6434e81464" width="300" /> | <img src="https://github.com/user-attachments/assets/d9abccd2-1cda-468c-9ced-2ad446edcc85" width="300" /> | …
> Update the search top app bar divider thickness

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/appbar/BitwardenMediumTopAppBar.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/model/TopAppBarDividerStyle.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultScreen.kt
N/A
This PR adds a enum for better control of TopAppBar divider.
This PR has not functional changes.
- ❌ …
> Add enum for better control of TopAppBar divider

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/resetpassword/ResetPasswordScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/setpassword/SetPasswordScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/appbar/BitwardenMediumTopAppBar.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/appbar/BitwardenTopAppBar.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/SettingsScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/SendScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultScreen.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/send/SendScreenTest.kt
PM-12668
This PR updates `TopAppBar` size, font and scrolling affects to match the updated designs.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/8792a3c0-10c8-4627-88f9-d31577aeced4" width="300" /> | <img src="https://github.com/user-attachments/assets/88b536e2-3a69-4e49-9657-2e68deb6876f" width="300" /> |
| <img src="https://github.com/user-attachments/assets/b79cad02-76ef-418e-bf78-aefc2a9c893d" width="300" /> | <img src="https://github.com/user-attachments/assets/c073e4ef-7bd0-4523-9889-c2e6ad07959f" width="300" /> |
- …
> PM-12668: Update TopAppBars accross the app

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/checkemail/CheckEmailScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/startregistration/StartRegistrationScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/base/util/Text.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/checkemail/CheckEmailScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/base/util/ClickableAnnotatedStringTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/util/ComposeTestHelpers.kt
https://bitwarden.atlassian.net/browse/PM-13471
- `ClickableText` is deprecated, moving to using `LinkAnnotation` with the `Text` function.
- create a helper method to create clickable spans with default highlighting.
- Will be used further to implement design for https://bitwarden.atlassian.net/browse/PM-11182
Tested and verified with existing links. …
> PM-13471 Remove instances deprecated ClickableText

- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/AuthenticatorBridgeRepositoryImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/repository/AuthenticatorBridgeRepositoryTest.kt
https://livefront.atlassian.net/browse/BITAU-176
Make sure we don't show deleted ciphers when syncing with the authenticator app.
N/A …
> BITAU-176 Filter out deleted ciphers from syncAccounts call

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/segment/BitwardenSegmentedButton.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/segment/color/BitwardenSegmentedButtonColors.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorViewModelTest.kt
[PM-11176](https://bitwarden.atlassian.net/browse/PM-11176)
This PR updates the Generator Screen to use a Segmented Control for top level navigation.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/78f1bc2d-5e52-4b79-979b-7505073e058a" width="300" /> | <img src="https://github.com/user-attachments/assets/8321ebde-31be-4512-848b-77d8883a9973" width="300" /> |
- 📝 …
> PM-11176: Update generator to use segmented control

- app/src/main/java/com/x8bit/bitwarden/ui/platform/manager/biometrics/BiometricsManagerImpl.kt
I opened this discussion explaining the change a few weeks ago:
https://github.com/orgs/bitwarden/discussions/11286
Got no response so far so I decided to go ahead and submit the PR. Hope that's ok!
As explained in that discussion, by default the Biometrics API treats any authentication as if it were a high-risk operation (such as a purchase), and requires the user to press a "Confirm" button after successful authentication when using a passive biometric system (such as the secure face unlock present in newer Pixels).
But this doesn't really make sense for low-risk operations such as logging into an app, where you'd expect an iPhone-like authentication that seamlessly takes you to the app after success (I question whether it makes sense for the API to default to `true` here, but that's …
> [PM-13387] Skip unneeded confirmation button when using passive biometrics such as face unlock

- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/ciphermatching/CipherMatchingManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/util/StringExtensions.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/ciphermatching/CipherMatchingManagerTest.kt
[PM-12296](https://bitwarden.atlassian.net/browse/PM-12296)
This PR updates the `HOST` matching logic to only match on port when both the source and the target have a port present. …
> PM-12296: Only match port when present on both uris

- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/SettingsNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/vault/VaultSettingsNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/vault/VaultSettingsScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/vault/VaultSettingsViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarScreen.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/vault/VaultSettingsScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/vault/VaultSettingsViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-13609
- When the `ImportLoginsFlow` flag is enabled when the user clicks "Import Items" in the vault settings they should be taken to the new import login instruction flow
- The UI should also change from an external link to a plain text row
https://github.com/user-attachments/assets/2cfec3b2-beec-44d7-99a9-78f08160aaa6 …
> PM-13609 Navigate to new import flow from Vault settings when feature is enabled.

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/appbar/BitwardenTopAppBar.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendScreen.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendScreenTest.kt
N/A
This PR pins the segmented control to toolbar in AddSendScreen.
| Before | after |
| --- | --- |
| <video src="https://github.com/user-attachments/assets/a960f4be-eaf7-417b-b9eb-22034d088511" width="300" /> | <video src="https://github.com/user-attachments/assets/151a2c97-6cbb-44f9-9392-edfbbfce9209" width="300" /> |
- ❓ …
> Pin the segmented control to toolbar in AddSendScreen

- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/pendingrequests/PendingRequestsScreen.kt
N/A
This PR adjusts the `PendingRequestsScreen` empty state to have the illustration in the right size.
| --- | --- | 
| <img src="https://github.com/user-attachments/assets/2564c026-556a-4b88-8c29-834b0d311b1a" width="300" /> | <img src="https://github.com/user-attachments/assets/72fe4fdc-7f62-4826-9691-45ae6e4be16a" width="300" /> | …
> Update PendingRequestsScreen image size

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/x8bit/bitwarden/MainViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/SpecialCircumstance.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/SettingsScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/SettingsViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/util/ShortcutUtils.kt
- app/src/test/java/com/x8bit/bitwarden/MainViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/SettingsScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/SettingsViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarViewModelTest.kt
https://livefront.atlassian.net/browse/BITAU-105
The goal of this PR is to add a deep link to account security settings that will be used by the Authenticator app.
<video src="https://github.com/user-attachments/assets/660b6d3a-f9b1-4d62-b111-902919ff1804" width="300" /> …
> BITAU-105 Add support for deep link to account security

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupUnlockScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/toggle/BitwardenUnlockWithBiometricsSwitch.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/manager/biometrics/BiometricsManager.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/manager/biometrics/BiometricsManagerImpl.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupUnlockScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityScreenTest.kt
https://bitwarden.atlassian.net/browse/PM-13382
- Show a message under the biometric toggle with context to the biometrics available on the users device.
- A separate message for all devices with Class 3 (strong) and class 2 (weak) authentication. …
> PM-13382 show contextual message for the level of Biometrics available

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/auth/AuthNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/welcome/WelcomeNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/welcome/WelcomeScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/welcome/WelcomeViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/welcome/WelcomeScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/welcome/WelcomeViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-13648
- When the email verification flag is enabled we want to go to the new create account flow, this was not happening from the welcome carousel screen.
https://github.com/user-attachments/assets/3433a577-fd17-4191-af5d-68fcba769a95 …
> PM-13648 Nav to new create account when email verification is on

- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/network/di/PlatformNetworkModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/network/interceptor/AuthTokenInterceptor.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/NetworkConfigManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/PushManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/di/PlatformManagerModule.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/network/interceptor/AuthTokenInterceptorTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/NetworkConfigManagerTest.kt
[PM-13688](https://bitwarden.atlassian.net/browse/PM-13688)
This PR addresses a race condition that can occur when different parts of the app are directly checking disk source to determine the login state but the `AuthTokenInterceptor` is not being updated as quickly. To avoid race conditions like this, the interceptor will now query the disk source directly. …
> PM-13688: Remove race condition from AuthTokenInterceptor

- app/src/fdroid/java/com/x8bit/bitwarden/data/platform/manager/CrashLogsManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/CrashLogsManager.kt
- app/src/standard/java/com/x8bit/bitwarden/data/platform/manager/CrashLogsManagerImpl.kt
N/A
This PR allows the `CrashLogsManager` to handle generic `Throwable`s when logging non-fatal-errors.
- ❌ …
> Allow CrashLogsManager to handle generic Throwables

- app/src/main/assets/fido2_privileged_google.json
https://bitwarden.atlassian.net/browse/PM-13825
Closes #4120
Add passkey support for privileged apps; Talon, DuckDuckGo, Naver Whale, Fido Client, and Heytap. …
> [PM-13825] Update Google sourced FIDO 2 privileged app list

- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/sdk/model/Fido2CredentialStoreImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/VaultRepository.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/content/BitwardenFullScreenLoadingContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/content/BitwardenLoadingContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/content/ObscuredContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlocked/VaultUnlockedNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/importlogins/ImportLoginsNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/importlogins/ImportLoginsScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/importlogins/ImportLoginsViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/importlogins/handlers/ImportLoginHandler.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/importlogins/ImportLoginsScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/importlogins/ImportLoginsViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-11186
- Add reusable full screen loading screen with blur effect
- Show reusable loading screen when syncing vault from import logins
- Support two different states for the full screen loading for older Android versions.
| Android 10 & 11 | Android >= 12 |
| [pm11186a10.webm](https://github.com/user-attachments/assets/132ca3a6-d86c-4210-8e9f-c8461a0c9b2d) | https://github.com/user-attachments/assets/e23d0693-0915-4e22-a4ad-ff57f11d0920 | 
- Updated any …
> PM-11186 Sync in progress for import logins and full screen loading.

- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/model/GetTokenResponseJson.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/datasource/network/service/IdentityServiceTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
https://bitwarden.atlassian.net/browse/PM-13396
This commit adds support for the legacy error response model returned by the `getToken` endpoint.
The legacy model uses lowercase keys for error messages, while the current model uses uppercase keys. This change ensures that the app can handle both models correctly.
Additionally, the unit tests were updated to cover the scenario where the server returns a legacy error response. …
> [PM-13396] Add support for legacy error response model in getToken

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/util/VaultItemListingDataExtensions.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/util/VaultItemListingDataExtensionsTest.kt
[PM-13021](https://bitwarden.atlassian.net/browse/PM-13021)
This PR updates some incorrect TOTP copy.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/a9e1b85b-3ede-4e74-a6d4-850b234e205f" width="300" /> | <img src="https://github.com/user-attachments/assets/235ce174-e593-4f06-89a6-30df26213232" width="300" /> | …
> PM-13021: Update no item found copy for totp

- app/src/beta/res/values/manifest.xml
- app/src/debug/res/values/manifest.xml
- app/src/main/AndroidManifest.xml
- app/src/release/res/values/manifest.xml
N/A
The goal here is to make it so that the authenticator app can sync with the main password manager both when release via firebase app distribution and also the play store. 
N/A  …
> Use array to define knownCerts for authenticator bridge permission

- app/src/main/java/com/x8bit/bitwarden/MainViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/loginapproval/LoginApprovalScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/loginapproval/LoginApprovalViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/MainViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/loginapproval/LoginApprovalScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/loginapproval/LoginApprovalViewModelTest.kt
[PM-13690](https://bitwarden.atlassian.net/browse/PM-13690)
This PR adds a dialog that appears for users who are logged in when switching to a different account for passwordless login.
<video src="https://github.com/user-attachments/assets/2efb9f48-bf4f-42bc-b3d9-008724c151f5" width="300" />
- 🤔 …
> PM-13690: Add dialog before switching account during passwordless login

- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/search/SearchViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/search/SearchScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/search/SearchViewModelTest.kt
[PM-13847](https://bitwarden.atlassian.net/browse/PM-13847)
This PR updates the search screen to launch directly into the edit screen when an item is clicked during a totp flow.
<video src="https://github.com/user-attachments/assets/c165fba1-74b9-4439-bc11-1402ff3b5413" width="300" />
- 🤔 …
> PM-13847: Totp click on search should go directly to edit screen

- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/vault/VaultSettingsScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/vault/VaultSettingsViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/vault/VaultSettingsScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/vault/VaultSettingsViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-13627
- show the action card for the import logins on the VaultSettings screen as well, same logic applies to showing, feature flag must be enabled and vault must be empty.
https://github.com/user-attachments/assets/6096d2b6-90a2-4440-8baf-86f0d10b224b
- 🤔 …
> PM-13627 show action card on vault settings if applicable

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt
[PM-13024](https://bitwarden.atlassian.net/browse/PM-13024)
This PR updates the `VaultAddEditViewModel` to no close the app when you are done updating or creating a cipher via the totp flow.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/2a095a25-360d-4d10-b08c-3a117d93917c" width="300" /> | <video src="https://github.com/user-attachments/assets/1a0d6731-7b17-42dc-b24c-8f0c8a7c25f8" width="300" /> |
- …
> PM-13024: After saving cipher in totp flow, app should not close

- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/search/SearchContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/search/SearchViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/search/util/SearchTypeDataExtensions.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/util/VaultItemListingDataExtensions.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/search/SearchScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/search/SearchViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/search/util/SearchTypeDataExtensionsTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/search/util/SearchUtil.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/util/VaultItemListingDataUtil.kt
[PM-13020](https://bitwarden.atlassian.net/browse/PM-13020)
This PR updates the totp flow inside the search and listing screen to ensure that the master password reprompt is honored.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/dd946795-33f0-435a-b854-de3e212b2198" width="300" /> | <video src="https://github.com/user-attachments/assets/58caebdb-32e6-4191-be7b-40fe8f7349b8" width="300" /> |
- 👍 …
> PM-13020: During totp flow master password reprompt should be honored

- app/src/main/java/com/x8bit/bitwarden/data/autofill/di/AutofillModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/processor/AutofillProcessorImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/autofill/processor/AutofillProcessorTest.kt
N/A
This PR updates the error handling in the `AutofillProcessorImpl` to use `Timber` instead of the `LogsManager` directly. …
> User TImber instead of LogsManager directly

- app/src/test/java/com/x8bit/bitwarden/data/platform/repository/AuthenticatorBridgeRepositoryTest.kt
N/A
This PR ensures that `unmockkStatic` is called for `toEncryptedSdkCipher` in the `AuthenticatorBridgeRepositoryTest`. …
> Ensure unmockk static is called in test teardown

- .github/workflows/build.yml
- .github/workflows/test.yml
This commit adds a step to upload test reports as artifacts when the `test` or `build` workflows fail.
This will help with debugging by providing access to the test reports for failed builds. …
> Upload test reports on test and build workflow failures

- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/FlagKey.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/components/FeatureFlagListItems.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/FlagKeyTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-13980
This commit introduces a new feature flag which can be used to enable or disable the SSH Key Cipher Item Types feature. …
> [PM-13980] Add SSH Key Cipher Item Types feature flag

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/pendingrequests/PendingRequestsScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/blockautofill/BlockAutoFillScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/exportvault/ExportVaultScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/other/OtherScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditCustomFieldsButton.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditLoginItems.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/attachments/AttachmentsContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/manualcodeentry/ManualCodeEntryScreen.kt
[PM-13937](https://bitwarden.atlassian.net/browse/PM-13937)
This PR replaces all the tonal buttons in the app with outlined buttons.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/9e15bfb4-2d9c-4efd-98d7-23f174abd647" width="300" /> | <img src="https://github.com/user-attachments/assets/85a80c9b-228a-4b06-ab14-ca92623a5be1" width="300" /> | …
> PM-13937: Replace tonal buttons with outline buttons

- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarScreen.kt
> QA-950: Adding testTag for VaultUnlockedNavBar component

- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/model/SyncVaultDataResult.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/importlogins/ImportLoginsScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/importlogins/ImportLoginsViewModel.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/importlogins/ImportLoginsScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/importlogins/ImportLoginsViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-13886
- when the import logins flow attempts to sync, and it's successful but no items are returned we want to display this to the user in the form of the error dialog as if the sync failed. Allowing them to try again or exit.
https://github.com/user-attachments/assets/beffd0b9-06a5-4b23-bcdf-d0a095db7e41
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes …
> PM-13886 show dialog when no logins were imported

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/attachments/AttachmentsContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemAttachmentContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemLoginContent.kt
> QA-951: Adding missing IDs for Attachment rows

- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/network/core/ResultCall.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/network/util/CallExtensionsTest.kt
N/A
This PR removes the query params from the network logs. …
> Remove query params from network logging

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/toggle/BitwardenWideSwitch.kt
> QA-952: Adding test tags for Toggle items

- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/about/AboutScreen.kt
> QA-955: Adding testTag to About screen rows

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/slider/BitwardenSlider.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreen.kt
[PM-14036](https://bitwarden.atlassian.net/browse/PM-14036)
This PR updates the `BitwardenSlider` to match the v3 designs.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/ab49dbf7-4c2d-4f24-9650-6f714dec5fb4" width="300" /> | <img src="https://github.com/user-attachments/assets/06b094ab-288d-480b-a505-5c849b4925f2" width="300" /> | …
> PM-14036: Update the slider UI

- app/src/test/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/completeregistration/CompleteRegistrationViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/createaccount/CreateAccountViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/enterprisesignon/EnterpriseSignOnViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/startregistration/StartRegistrationViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/importlogins/ImportLoginsViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModelTest.kt
N/A
This PR updates usages of `turbinScope` in test to make them a bit cleaner. …
> Simplify usages of turbineScope

- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityViewModel.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityViewModelTest.kt
- authenticatorbridge/src/main/java/com/bitwarden/authenticatorbridge/util/AndroidBuildUtils.kt
https://livefront.atlassian.net/browse/BITAU-182
https://livefront.atlassian.net/browse/BITAU-107
The goal of this PR is to not show authenticator sync UI when API level is below 31. Also, I made a small copy update that Lukus found while I was in there.
Note: the design file is still using v2 design, so we can ignore that difference.
| Design | Implementation |
| --- | --- |
| <img src="https://github.com/user-attachments/assets/5ae01fe0-7abc-4cf0-a3c8-6c22359394e5" width="300" /> | <img src="https://github.com/user-attachments/assets/b4f0e5a3-8706-46a7-a6a4-0da0d6ad2ccb" width="300" /> |
- Used internationalization (i18n) for all UI …
> BITAU-182 BITAU-107 Don't show authetnicator sync toggle below API 31

- app/build.gradle.kts
https://bitwarden.atlassian.net/browse/PM-13908
This commit disables the `ExtraTranslation` lint warning.
- …
> [PM-13908] Disable ExtraTranslation lint warning

- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSource.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSourceImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/FirstTimeActionManager.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/FirstTimeActionManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/FirstTimeState.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/vault/VaultSettingsViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/importlogins/ImportLoginsViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSourceTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/disk/util/FakeSettingsDiskSource.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/FirstTimeActionManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/vault/VaultSettingsViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/importlogins/ImportLoginsViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-14009
- Only show "Vault settings/Import logins" badge and action card if the user dismisses the card in their vault/chooses the "import later" option.
https://github.com/user-attachments/assets/496d6f1a-8211-4d46-9d0d-90a253165e82 …
> PM-14009 complete fix importlogins card show logic

- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/disk/AuthDiskSource.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/disk/AuthDiskSourceImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepository.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/datasource/disk/AuthDiskSourceTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/datasource/disk/util/FakeAuthDiskSource.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-13988
- Fix issue where the account lock values were not updating when changed through the "Setup unlock" screen after clicking the action card.
Before: 
https://github.com/user-attachments/assets/0c500fb7-f305-4ab1-97b6-40db505e1078
After: 
https://github.com/user-attachments/assets/5e5cfb4b-39e2-4e4d-bfb5-f311046b5600 …
> PM-13988 observe changes to unlock status on settings screen

- app/src/main/java/com/x8bit/bitwarden/ui/platform/base/util/ModifierExtensions.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/appbar/BitwardenMediumTopAppBar.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/appbar/BitwardenSearchTopAppBar.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/appbar/BitwardenTopAppBar.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/divider/BitwardenHorizontalDivider.kt
[PM-14201](https://bitwarden.atlassian.net/browse/PM-14201)
This PR updates the default divider thickness across the app.
There should be no functional changes in this PR. …
> PM-14201: Update the default divider thickness

- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/SettingsNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/vault/VaultSettingsNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/vault/VaultSettingsScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/vault/VaultSettingsViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlocked/VaultUnlockedNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/manager/di/PlatformUiManagerModule.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/manager/snackbar/SnackbarRelay.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/manager/snackbar/SnackbarRelayManager.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/manager/snackbar/SnackbarRelayManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/importlogins/ImportLoginsNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/importlogins/ImportLoginsScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/importlogins/ImportLoginsViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultGraphNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModel.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/vault/VaultSettingsScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/vault/VaultSettingsViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/manager/snackbar/SnackbarRelayManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/importlogins/ImportLoginsScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/importlogins/ImportLoginsViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-11188
&
Pt2 of https://bitwarden.atlassian.net/browse/PM-13943
- Allow one "screen" to trigger a snackbar on another
- Show success snackbar on vault and vault settings screen after import login flow
https://github.com/user-attachments/assets/dad6e938-6611-4c98-b376-be9d495d1ab9
- ❓ …
> PM-11188 show snackbar after import success. PM-13943 add relay for snackbar events across screen contexts.

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenTextField.kt
[PM-14044](https://bitwarden.atlassian.net/browse/PM-14044)
This PR updates the line-break logic to account for padding on both sides of the text field.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/56cacb7a-41ab-4791-b54a-c5ba55482dea" width="300" /> | <video src="https://github.com/user-attachments/assets/73d5a951-c06e-47b4-9f0f-c8b9f1165775" width="300" /> | …
> PM-14044: Update generator line breaks to account for padding on both sides

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/stepper/BitwardenStepper.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendContent.kt
> QA-954: Add testtags to Send screen elements

- app/src/standard/java/com/x8bit/bitwarden/data/platform/manager/LogsManagerImpl.kt
https://bitwarden.atlassian.net/browse/PM-14241
Trying to uproot the `nonfatalErrorTree` when it has not been planted is causing the application to crash. This will add a check to verify it exists on the Timber array before trying to remove it. …
> [PM-14241] Checking if Timber tree has been added before trying to remove it

- app/proguard-rules.pro
https://bitwarden.atlassian.net/browse/PM-14254
The Android Verifier component is incorrectly flagged as dead code by Proguard, as it's unable to detect JNI usage.
This change manually keeps the `org.rustls.platformverifier` classes to resolve the issue. …
> [PM-14254] Keep Android verifier for JNI usage

- app/schemas/com.x8bit.bitwarden.data.vault.datasource.disk.database.VaultDatabase/4.json
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/disk/VaultDiskSourceImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/disk/database/VaultDatabase.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/disk/entity/CollectionEntity.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/model/SyncResponseJson.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/util/VaultSdkCollectionExtensions.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/datasource/disk/VaultDiskSourceTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/datasource/network/model/SyncResponseCollectionUtil.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/datasource/network/service/SyncServiceTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/datasource/sdk/model/CollectionViewUtil.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/datasource/sdk/model/VaultSdkCollectionUtil.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/repository/util/VaultSdkCollectionExtensionsTest.kt
- gradle/libs.versions.toml
https://bitwarden.atlassian.net/browse/PM-13900
https://bitwarden.atlassian.net/browse/PM-13933
https://bitwarden.atlassian.net/browse/PM-14062
Closes #4171
This commit updates the Bitwarden SDK to the latest version and references the temporary internal group name. The group name will be reverted back when internal SDK infrastructure changes are completed.
This commit also adds the `canManage` property to the `CollectionEntity` and `SyncResponseJson` classes to support the management of collections. It also includes necessary test updates and updates to the database schema to reflect these changes.
Depends on #4158
- Used …
> [PM-13900] Update Bitwarden SDK to add `canManage` to Collection objects

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditCardItems.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditIdentityItems.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditLoginItems.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditSecureNotesItems.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/util/CipherViewExtensions.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/util/CipherViewExtensionsTest.kt
[PM-13842](https://bitwarden.atlassian.net/browse/PM-13842)
This PR removes the ownership section for the create cipher UI when there are no organizations to select from. …
> PM-13842: Hide ownership when the user has no organizations

- .github/ISSUE_TEMPLATE/bug.yml
- README.md
- scripts/download-artifacts.sh
https://bitwarden.atlassian.net/browse/PM-14261
1. Update README and bugs template to remove Beta references
2. Adds Server questions to bug template
3. Adds github artifacts download script
issue and …
> [PM-14261] Update README and bugs template to remove Beta references

- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/BitwardenAccessibilityService.kt
- app/src/main/res/xml/accessibility_service.xml
PM-14255
This PR makes two major performance improvements for the accessibility service.
* Remove the `typeWindowContentChanged` event type which occurs much more frequently than needed.
* Remove the usage of the `RootInActiveWindow` which can take a long time to access.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/67a2f221-e2aa-46c1-a9aa-7b8e74e9d5ed" width="300" /> | <video src="https://github.com/user-attachments/assets/0fa0afa5-b633-47ed-b164-0dcfaad66fe4" width="300" /> | …
> PM-14255: Remove accessibility logic to improve overall performance

- app/src/main/java/com/x8bit/bitwarden/data/tools/generator/repository/GeneratorRepositoryImpl.kt
https://bitwarden.atlassian.net/browse/PM-14346
This commit modifies `generateForwardedServiceUsername` to run on the IO dispatcher by using `withContext`. This change ensures that any network calls made by the SDK are not executed on the main thread.
https://github.com/user-attachments/assets/c21c060b-596c-47ba-9a35-bcd8dda87dc3
- …
> [PM-14346] Run alias generation on the IO dispatcher

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditSshKeyItems.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/handlers/VaultAddEditSshKeyTypeHandlers.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-14271
The commit disables editing of public key, private key, and fingerprint fields for SSH keys in edit mode. This is achieved by:
- Making the corresponding text fields read-only.
- Removing the handlers that were previously updating the ViewModel with text changes for these fields.
https://github.com/user-attachments/assets/0acf00bc-a0fe-453a-b510-804c927efbd4 …
> [PM-14271] Disable editing SSH key fields in edit mode

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemSshKeyContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/handlers/VaultSshKeyItemTypeHandlers.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-14273
This commit adds the ability to copy the public key and fingerprint of an SSH key within the vault item view.
It introduces new buttons to trigger the copy actions and updates the view model and item handlers to handle the copy functionality.
https://github.com/user-attachments/assets/49f25156-f3be-4f6b-b4d6-c1950bcc64b3 …
> [PM-14273] Add copy functionality for SSH key fields

- app/src/main/java/com/x8bit/bitwarden/ui/platform/base/util/StringExtensions.kt
[PM-14044](https://bitwarden.atlassian.net/browse/PM-14044)
This PR adjusts the line break logic to measure the entire string instead of an individual character.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/30cd4915-6a8a-4479-b643-7fda0ce3df97" width="300" /> | <video src="https://github.com/user-attachments/assets/9be271eb-b9d8-4af4-8f5c-2644fe566ec7" width="300" /> | …
> PM-14044: Fix line-breaking logic

- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorViewModel.kt
[PM-14379](https://bitwarden.atlassian.net/browse/PM-14379)
This PR fixes a bug where we were storing the word `null` as the word separator which caused the value to default to the first char, `n`.
issue …
> PM-14379: Stop storing 'null' in as the word separator

- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreen.kt
[PM-14036](https://bitwarden.atlassian.net/browse/PM-14036)
This PR adds addition end padding to the slider on the Generator Screen. This is an attempt to lower the odds that grabbing the slider thumb when it is at the end of the screen will trigger a navigate-back gesture.
Design approved of this extra padding.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/97fce7fb-d84b-4bd4-9f61-ff48433f3737" width="300" /> | <img src="https://github.com/user-attachments/assets/d836e862-ba60-4b54-b5d3-49484e0584fd" width="300" /> |
- …
> PM-14036: Add extra slider padding

- app/src/main/java/com/x8bit/bitwarden/data/platform/util/StringExtensions.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/util/URIExtensions.kt
- app/src/test/java/com/x8bit/bitwarden/data/util/StringExtensionsTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/util/UriExtensionsTest.kt
https://bitwarden.atlassian.net/browse/PM-13948
- If a port was specified with no scheme, the `URI` was not parsing the string correctly and was using the `host` as the `scheme`
before: 
https://github.com/user-attachments/assets/a0248aeb-e46f-49ac-8ae1-54b5306a7828
After: 
https://github.com/user-attachments/assets/927c4711-0a73-4d4f-beee-35331533a65a …
> PM-13848 Handle URIs with ports and host matching

- app/schemas/com.x8bit.bitwarden.data.vault.datasource.disk.database.VaultDatabase/4.json
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/disk/VaultDiskSource.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/disk/VaultDiskSourceImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/disk/database/VaultDatabase.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/disk/entity/DomainsEntity.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/model/SyncResponseJson.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/util/DomainsExtensions.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/datasource/disk/VaultDiskSourceTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/datasource/disk/dao/FakeDomainsDao.kt
[PM-14433](https://bitwarden.atlassian.net/browse/PM-14433)
This PR allows for the domains data to be nullable in the sync response JSON and handles all the downstream affects that change has.
issue and …
> PM-14433: Null domain data

- app/src/main/java/com/x8bit/bitwarden/ui/platform/manager/snackbar/SnackbarRelayManager.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/manager/snackbar/SnackbarRelayManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/manager/snackbar/SnackbarRelayManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-14353
- Snackbar was briefly showing while the account was switched, due to the navigation being user state based the next instance of the VaultViewModel was collecting from the shared flow before it was removed from the internal map on completion of the previous instance. 
- Added a function to explicitly clear the replay cache.
| before | after |
| [example](https://github.com/user-attachments/assets/532028a8-4d41-4ab9-9cd1-43167ba4f94e) | [pm14353after.webm](https://github.com/user-attachments/assets/4fecf845-a430-416b-84ac-8ee1b1144abe) | 
- Used internationalization (i18n) …
> PM-14353 : Clean up consumed snackbar on quick resubmission due to state based nav.

- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/model/SyncResponseJson.kt
https://bitwarden.atlassian.net/browse/PM-14526
Adds the `@JsonNames` annotation to the `profile` and `domains` properties in the `SyncResponseJson` data class.
This ensures that the properties are correctly deserialized even if the server response uses different casing for the property names.
- 🤔 …
> [PM-14526] Add JsonNames annotation to SyncResponseJson 

- app/schemas/com.x8bit.bitwarden.data.vault.datasource.disk.database.VaultDatabase/5.json
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/disk/database/VaultDatabase.kt
https://bitwarden.atlassian.net/browse/PM-14596
This commit updates the VaultDatabase schema to version 5. …
> Bump VaultDatabase to version 5

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/util/CipherViewExtensions.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/model/VaultItemStateData.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/util/CipherViewExtensions.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/datasource/sdk/model/CollectionViewUtil.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/util/CipherViewExtensionsTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/item/util/CipherViewExtensionsTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/item/util/VaultItemTestUtil.kt
https://bitwarden.atlassian.net/browse/PM-13360
This commit prevents users from assigning items to collections if the item is already in a read-only collection where the user does not have "manage" permission.
This change ensures that users with limited permissions cannot modify items in a way that violates the collection's access controls.
Coming soon! …
> [PM-13360] Respect manage permission to assign collections

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/segment/BitwardenSegmentedButton.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorViewModel.kt
[PM-14644](https://bitwarden.atlassian.net/browse/PM-14644)
This PR updates the logic for displaying the segmented control and its options on the generator screen based on the `GeneratorMode`.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/72b9ee5b-3380-463d-a996-0c47c43a52a2" width="300" /> | <img src="https://github.com/user-attachments/assets/767e679d-2a9e-4321-b1b7-ee5a3b2ca4da" width="300" /> |
- 👍 …
> PM-14644: Segmented control should be conditionally displayed for modal generator screen

- app/src/main/java/com/x8bit/bitwarden/ui/platform/manager/intent/IntentManagerImpl.kt
[PM-14480](https://bitwarden.atlassian.net/browse/PM-14480)
This PR is already in main, this is a cherry-pick for a hotfix.
This PR updates the `IntentManager` to check for the `androidapp` scheme and attempt to launch the app if possible.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/0973c77f-1d88-4159-a884-776a23447921" width="300" /> | <video src="https://github.com/user-attachments/assets/77daec24-41bb-4274-9c0f-5870ac3a989b" width="300" /> | …
> PM-14480: Update IntentManager to be able to launch apps

- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/disk/VaultDiskSourceImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/disk/dao/DomainsDao.kt
https://bitwarden.atlassian.net/browse/PM-14433
Cherry-picked from #4231 (5a4b8d64) on branch `release/hotfix-v2024.11.0`.
- Avoid call on a null object when a query is made against an empty table returning a Flow. 
- According to the [documentation](https://developer.android.com/reference/androidx/room/Query), this should have thrown a NPE, but it seems that there is an open [issue](https://issuetracker.google.com/issues/213175894) where it actually is returning Flow<T?> and emitting `null`. Updating the contract to return a `Flow<DomainEntity>` so it matches the result we get from Room, then we filter out the null emissions where we are mapping back to the JSON.
- FWIW: I checked other areas in the codebase where we are returning `Flow`s from Room and they are all `Flow<List<T>>` so …
> PM-14433 update flow type to nullable so we can handle gracefully and avoid crash

- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/util/StateFlowExtensions.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/repository/util/StateFlowExtensionsTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt
https://bitwarden.atlassian.net/browse/PM-11753
In some instances the vault gets stuck on an infinite loading. 
This is caused by some scenarios when the app is on background and the vault gets locked the requirements to emit on `observeWhenSubscribedAndLoggedIn` are not met causing the observer to not be called anymore.
This tries to fix it by creating a new flow that also listens to the `vaultUnlockFlow`.
mutableStateFlow on the VaultRepository will listen to the `observeWhenSubscribedAndUnlocked` and call the observer on unlock
- Communicated to DevOps any …
> [PM-11753] Listening to vaultUnlock state on mutableCiphers, folders, collections and send state flow

- app/src/main/java/com/x8bit/bitwarden/MainViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/manager/AccessibilityCompletionManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/util/AutofillIntentUtils.kt
- app/src/main/java/com/x8bit/bitwarden/data/tiles/BitwardenAutofillTileService.kt
- app/src/test/java/com/x8bit/bitwarden/data/autofill/accessibility/manager/AccessibilityCompletionManagerTest.kt
[PM-14411](https://bitwarden.atlassian.net/browse/PM-14411)
This PR allows the accessibility autofill functionality to work when the app is already open.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/fbda7ad5-fd10-43e2-acdc-f21cf9eb8574" width="300" /> | <video src="https://github.com/user-attachments/assets/238813ab-7186-4914-9be3-5583501e3de0" width="300" /> | …
> PM-14411: Allow accessibility autofill to run when app is already in background

- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/network/serializer/BaseEnumeratedIntSerializer.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/model/PolicyTypeJson.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/network/serializer/BaseEnumeratedIntSerializerTest.kt
https://bitwarden.atlassian.net/browse/PM-14656
Adds a default value to the BaseEnumeratedIntSerializer to handle unknown values during deserialization. This ensures that unknown values will be deserialized to the specified default value instead of throwing an exception. …
> [PM-14656] Add default value to `BaseEnumeratedIntSerializer`

- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/network/serializer/BaseEnumeratedIntSerializer.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/model/PolicyTypeJson.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/network/serializer/BaseEnumeratedIntSerializerTest.kt
https://bitwarden.atlassian.net/browse/PM-14656
Adds a default value to the BaseEnumeratedIntSerializer to handle unknown values during deserialization. This ensures that unknown values will be deserialized to the specified default value instead of throwing an exception. …
> [PM-14656] Add default value to BaseEnumeratedIntSerializer

- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/pendingrequests/PendingRequestsScreen.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/pendingrequests/PendingRequestsScreenTest.kt
[PM-14458](https://bitwarden.atlassian.net/browse/PM-14458)
This PR fixes a big in the notifications prompt where it would be displayed is the user has not denied the permission first. …
> PM-14458: Fix notifications prompt on first use

- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/handlers/CatchAllEmailHandlers.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/handlers/ForwardedEmailAliasHandlers.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/handlers/PassphraseHandlers.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/handlers/PasswordHandlers.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/handlers/PlusAddressedEmailHandlers.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/handlers/RandomWordHandlers.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/handlers/UsernameTypeHandlers.kt
N/A
This PR moves all of the handler classes from the `GeneratorScreen` and into their own files.
Some other small changes were made to the `GeneratorScreen` but none affect the app functionality.
There is one minor UI update, the divider line is no longer displayed when in the generator modal and the segmented control is present.
- …
> Clean up the generator screen and handlers

- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlocked/VaultUnlockedNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/util/CipherViewExtensions.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/util/VaultItemListingStateExtensions.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultGraphNavigation.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/util/VaultItemListingStateExtensionsTest.kt
https://bitwarden.atlassian.net/browse/PM-11303
- Added the missing "Add Cipher" floating button to the folder view.
- Updated the "Add" functionality to preselect the current folder when adding from a folder view. To achieve this, a new navigation parameter was introduced and passed to the Add/Edit screen.
https://github.com/user-attachments/assets/25db2b95-38ec-4d0d-9440-f13866956830
- 📝 (`:memo:`) or …
> [PM-11303] Add button missing for folders

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-14589
Removed the SSH key feature flag and disabled the SSH key item type option in `VaultAddEdit` screen.
The SSH key item type option is currently hidden until the SDK supports it.
| <img width="381" alt="image" src="https://github.com/user-attachments/assets/6afc7fa4-ab5d-4f06-8530-18f2b3f8a75b"> | <img width="380" alt="image" src="https://github.com/user-attachments/assets/e5c72d3f-7cdd-4bb7-9b81-0220f5acb33d"> | 
- Updated any …
> [PM-14589] Prevent SSH key item creation

- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/disk/VaultDiskSourceImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/model/SyncResponseJson.kt
https://bitwarden.atlassian.net/browse/PM-14526
Cherry-picked from #4247 (816b9769) from branch `release/hotfix-v2024.11.1`.
Adds the `@JsonNames` annotation to the `profile` and `domains` properties in the `SyncResponseJson` data class.
This ensures that the properties are correctly deserialized even if the server response uses different casing for the property names. …
> [PM-14526] Add JsonNames annotation to SyncResponseJson

- app/src/main/java/com/x8bit/bitwarden/data/platform/util/ResultExtensions.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/util/ResultTest.kt
[PM-14805](https://bitwarden.atlassian.net/browse/PM-14805)
This PR ensures that you cannot double wrap a `Result` in a `Result` when using the `asSuccess` helper method. …
> PM-14805: Ensure results cannot be double wrapped from 'asSuccess'

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/loginwithdevice/LoginWithDeviceViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/loginwithdevice/LoginWithDeviceViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-14597
- Remove notification dialog if device approval is declined …
> PM-14597 remove notification if device login is declined

- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/BitwardenAccessibilityService.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/processor/BitwardenAccessibilityProcessor.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/processor/BitwardenAccessibilityProcessorImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/autofill/accessibility/processor/BitwardenAccessibilityProcessorTest.kt
N/A
This PR adds some additional performance improvements to the accessibility autofill by deferring the call to the `rootAccessibilityNodeInfo` until after all other checks have passed. …
> Improve accessibility autofill performance

- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/network/model/NetworkResult.kt
[PM-14854](https://bitwarden.atlassian.net/browse/PM-14854)
This PR fixes a crash on app startup in release caused by the `NetworkResult` being obfuscated. …
> PM-14854: Keep NetworkResult to avoid obfuscation crash in release

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/snackbar/BitwardenSnackbar.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/vault/VaultSettingsScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultScreenTest.kt
https://bitwarden.atlassian.net/browse/PM-14352
- dismiss on click of snackbar 
https://github.com/user-attachments/assets/66e6ecb5-8173-4946-9c72-9eba3ff105b0 …
> PM-14352 Dismiss Snackbar when user clicks it as a default unless the specific dismiss action is present.

- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
[PM-14851](https://bitwarden.atlassian.net/browse/PM-14851)
This PR updates the `SendVerificationEmailRequestJson` to use a `null` name instead of an empty string. …
> PM-14851: Blank names should be considered null

- .github/workflows/build.yml
https://bitwarden.atlassian.net/browse/PM-14897
https://bitwarden.atlassian.net/browse/PM-14898
Outputs version name and number to action run summary, removing the need to go into job step logs. 
While at it, fixed f-droid internal firebase distribution. Thanks @vgrassia for pointing it out! 
- 🤔 …
> [PM-14897] Enhance build.yml run summary and fix f-droid distribution

- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/FirstTimeActionManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/di/PlatformManagerModule.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/FirstTimeActionManagerTest.kt
https://bitwarden.atlassian.net/browse/PM-14414
- Once any user has enabled the autofill service any showing action cards for any user should be hidden.
https://github.com/user-attachments/assets/66c89879-c688-486b-8e02-ce4b27196440 …
> PM-14414 hides autofill card for all users if autofill service is enabled.

- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/model/FillableFields.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/processor/BitwardenAccessibilityProcessorImpl.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/manager/exit/ExitManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/data/autofill/accessibility/processor/BitwardenAccessibilityProcessorTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
[PM-14411](https://bitwarden.atlassian.net/browse/PM-14411)
This PR addresses multiple issues concerning the QuickTile and Accessibility Autofill.
* After parsing a Url, if there are no fields available to fill, we should toast and return.
* Do not clear the `AccessibilityAction` just because the event is for a launcher or skipped package, the missing fields logic will handle it.
* The `VaultItemListingScreen` should dismiss the activity when navigating back from attempting autofill.
* Closing the app via the `ExitManager` should kill the task as well, this is needed specifically because the `AccessibilityService` runs in the background and we want to clear the state.
- Written new unit and / or …
> PM-14411: Autofill logic to work better with QuickTile

- .github/workflows/release-branch.yml
https://bitwarden.atlassian.net/browse/PM-14879
Adds workflow to create release branches, supports RC and Hotfix:
1. RC branches are created with the following naming pattern: `release/{YYY.MM}-rc{build_number}`, e.g. `release/2024.11-rc5`. Date prefix can be removed by a workflow input, in that case it would create a `release/rc5`.
2. Hotfix branches are created using the last release tag, e.g. `hotfix-v2024.11.4`
Running this workflow with `Hotfix` multiple times won't fail, although logs are slightly different - we don't receive remote logs  
- Communicated to …
> [PM-14879] Release Branch creation workflow

- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSource.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSourceImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/DatabaseSchemeManager.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/DatabaseSchemeManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/di/PlatformManagerModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/disk/util/FakeSettingsDiskSource.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/DatabaseSchemeManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt
PM-14596
cherry picked from #4257 (3c77933b) on `release/hotfix-v2024.11.3`
Trigger a sync when the database schema changes. This ensures that the client and server are in sync after a schema update. …
> [PM-14596] Sync on database scheme change

- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreen.kt
https://bitwarden.atlassian.net/browse/PM-14429
- When decreasing the  min numbers or special characters the value continues to change because the length of the pw does not change and the minimum range is changing.
Before: See story
After: 
https://github.com/user-attachments/assets/56807212-d0f7-4ae4-a9dc-a5d8afc1cb1d
- ❓ …
> PM-14429 Set the min and max range of the slider to match the restrictions not update the min with the computed min.

- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/sdk/VaultSdkSource.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/sdk/VaultSdkSourceImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/datasource/sdk/VaultSdkSourceTest.kt
[PM-12259](https://bitwarden.atlassian.net/browse/PM-12259)
This PR update the `validatePin` function in the `AuthRepository` to use the purpose-made SDK function to validate the pin. This fixes some bugs that can occur from calling the `initializeCrypto` function in unexpected places, which is how the previous logic worked.
- ❓ …
> PM-12259: Use validatePin SDK to validate the users pin

- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/model/FillableFields.kt
[PM-14934](https://bitwarden.atlassian.net/browse/PM-14934)
This PR adjusts the `hasFields` property to allow the accessibility autofill to fill usernames or passwords in a stand-alone manner. Meaning that it could be a site with just a password or just a username. …
> PM-14934: Allow accessibility autofill to fill just a username or just a password

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/manualcodeentry/ManualCodeEntryViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/manualcodeentry/ManualCodeEntryViewModelTests.kt
[PM-12733](https://bitwarden.atlassian.net/browse/PM-12733)
This PR trims the totp before saving it.
- ❌ …
> PM-12733: Trim totp codes before saving them

- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/SendContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultContent.kt
[PM-14200](https://bitwarden.atlassian.net/browse/PM-14200)
This PR updates the Send Screen's types header to contain a count.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/7c321db9-9825-4a8f-bea8-26c4322c1c0c" width="300" /> | <img src="https://github.com/user-attachments/assets/5a4af936-935d-4652-9ac7-ad88b52b0223" width="300" /> | …
> PM-14200: Add count to sends type header

- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/util/JwtTokenUtils.kt
N/A
This PR adds logging to track when a JWT Token fails to be parsed. …
> Log JWT parsing errors

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/button/BitwardenFilledIconButton.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/button/color/BitwardenIconButtonColors.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/stepper/BitwardenStepper.kt
[PM-15041](https://bitwarden.atlassian.net/browse/PM-15041)
This PR adds the `BitwardenFilledIconButton` to the app and applies it to all steppers.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/5d12eb51-1b68-4b1b-b6d0-f6400b0bd2bc" width="300" /> | <img src="https://github.com/user-attachments/assets/e75dcafa-e86c-4d83-a736-b919b833f989" width="300" /> |
- 📝 …
> PM-15041: Update stepper buttons

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/completeregistration/PasswordStrengthIndicator.kt
https://bitwarden.atlassian.net/browse/PM-15049
- Strength indicator shouldn't show till min chars is met.
- Min chars info color should no longer change once met.
| <img width="325" alt="image" src="https://github.com/user-attachments/assets/44e2ab96-5469-4531-94c2-9505a5ef87f1"> | ![image](https://github.com/user-attachments/assets/0c847d1b-fadb-4b09-8a5d-99cc12a4bcde) |
| <img width="339" alt="image" src="https://github.com/user-attachments/assets/455a0efc-728f-4c28-a41b-bdbf37687f09"> | ![image](https://github.com/user-attachments/assets/43d9a86f-4427-410b-aaef-56e4aa84eef7) | 
- Used …
> PM-15049 PW strength indicator design audit

- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/service/IdentityService.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/service/IdentityServiceImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/datasource/network/service/IdentityServiceTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
[PM-15025](https://bitwarden.atlassian.net/browse/PM-15025)
This PR updates the `sendVerificationEmail` API to properly parse error messages from the server so they can be displayed to the user.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/19293c07-9918-4587-8262-a54de42a6184" width="300" /> | <img src="https://github.com/user-attachments/assets/90c71081-64ac-4ab0-b65b-77c5f7063c11" width="300" /> |
- …
> PM-15025: Update sendVerificationEmail to handle error responses

- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/disk/model/AccountJson.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/model/KeyConnectorUserDecryptionOptionsJson.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/model/TrustedDeviceUserDecryptionOptionsJson.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/model/UserDecryptionOptionsJson.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockViewModel.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/data/auth/datasource/disk/AuthDiskSourceTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-15062
- Prevent users from being in limbo state if they no longer have a way to unlock account after migration from MAUI app. …
> PM-15062 prevent account lockout when biometrics is only unlock method and no longer supported class.

- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/disk/model/AccountJson.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/model/KeyConnectorUserDecryptionOptionsJson.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/model/TrustedDeviceUserDecryptionOptionsJson.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/model/UserDecryptionOptionsJson.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockViewModel.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/data/auth/datasource/disk/AuthDiskSourceTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-15062
- If a user has a no longer supported biometric set up as their only way to unlock their account (particularly after migration from MAUI -> native) we want to inform them of that and then log them out.
- Should support single and multi-account.
https://github.com/user-attachments/assets/2e4258ed-a499-4b06-815f-9ad04695dfa6 …
> PM-15062 Checking if the user has a no longer supported biometric as their only way of unlocking their account.

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dialog/BitwardenBasicDialog.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/manualcodeentry/ManualCodeEntryScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/manualcodeentry/ManualCodeEntryViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/manualcodeentry/ManualCodeEntryScreenTests.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/manualcodeentry/ManualCodeEntryViewModelTests.kt
[PM-12733](https://bitwarden.atlassian.net/browse/PM-12733)
This PR adds an error dialog to be displayed if the user attempts to enter a blank totp code. …
> PM-12733: Add error dialog to be displayed if TOTP code is blank

- .github/workflows/github-release.yml
[PM-11598](https://bitwarden.atlassian.net/browse/PM-11598)
1. Prefix tagnames with "v", following our usual pattern
2. Refactor inputs casing to kebab-case (thanks @vgrassia! ) …
> [PM-11598] GitHub Release - Improve tag name and refactor inputs casing

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/loginwithdevice/LoginWithDeviceScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/loginwithdevice/LoginWithDeviceViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/loginwithdevice/LoginWithDeviceViewModelTest.kt
PM-14963
This PR adds a toast when you successfully login with device. …
> PM-14963: Add toast when login via device succeeds

- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/network/interceptor/BaseUrlInterceptor.kt
N/A
This PR remove the nonnull requirement for the `HttpUrl` inside the `BaseUrlInterceptor`. This should avoid an error that can cause a crash in the app. …
> Simplify url check in BaseUrlInterceptor

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/completeregistration/CompleteRegistrationScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/completeregistration/CompleteRegistrationViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/createaccount/CreateAccountScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/createaccount/CreateAccountViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/startregistration/StartRegistrationScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/startregistration/StartRegistrationViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dialog/BitwardenBasicDialog.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/appearance/AppearanceScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingScreen.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/completeregistration/CompleteRegistrationScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/completeregistration/CompleteRegistrationViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/createaccount/CreateAccountScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/createaccount/CreateAccountViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/startregistration/StartRegistrationScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/startregistration/StartRegistrationViewModelTest.kt
N/A
This PR simplifies the `BitwardenBasicDialog` by removing the `BasicDialogState` class.
- ❌ (`:x:`) or …
> Remove the BasicDialogState

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/toggle/BitwardenUnlockWithPinSwitch.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/PinInputDialog.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingScreenTest.kt
https://bitwarden.atlassian.net/browse/PM-15109
- prevent users from entering or pasting non numeric values in for the text field.
https://github.com/user-attachments/assets/2c168289-c382-407c-a668-e159f6b134bc …
> PM-15109 only accept numeric values for account pin lock value

- app/src/main/java/com/x8bit/bitwarden/MainViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/manager/Fido2CredentialManager.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/manager/Fido2CredentialManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/model/Fido2CreateCredentialRequest.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/util/Fido2IntentUtils.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/SpecialCircumstance.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/util/SpecialCircumstanceExtensions.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/util/Fido2CreateCredentialRequestExtensions.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/util/VaultItemListingDataExtensions.kt
- app/src/test/java/com/x8bit/bitwarden/MainViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/autofill/fido2/manager/Fido2CredentialManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/autofill/fido2/model/Fido2CredentialRequestUtil.kt
- app/src/test/java/com/x8bit/bitwarden/data/autofill/fido2/util/Fido2IntentUtilsTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/util/SpecialCircumstanceExtensionsTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/util/Fido2CredentialRequestExtensionsTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/util/VaultItemListingDataExtensionsTest.kt
PM-15057
Rename `Fido2CredentialRequest` to `Fido2CreateCredentialRequest` for clarity and consistency. This change reflects the specific purpose of the request, which is to create a new FIDO2 credential. …
> [PM-15057] Rename Fido2CredentialRequest to Fido2CreateCredentialRequest

- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/api/CiphersApi.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/model/ImportCiphersJsonRequest.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/model/ImportCiphersResponseJson.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/service/CiphersService.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/service/CiphersServiceImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/datasource/network/service/CiphersServiceTest.kt
PM-15054
Add an API for importing ciphers, including folders and folder relationships. …
> [PM-15054] Add API for importing ciphers

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/util/VaultItemListingDataExtensions.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/util/VaultItemListingDataExtensionsTest.kt
PM-15113
Disable the add button in the SSH Keys screen. This fixes a bug that allowed creation of SSH keys after selecting the SSH key filter.
- 🎨 …
> [PM-15113] Disable add button in SSH Keys screen

- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/VaultRepository.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/other/OtherViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/SendViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/verificationcode/VerificationCodeViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/search/SearchViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/other/OtherViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/send/SendViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/verificationcode/VerificationCodeViewModelTest.kt
[PM-15177](https://bitwarden.atlassian.net/browse/PM-15177) Part 1
This PR adds the ability to force a sync and bypass the normal checks that occur before syncing. This is meant to be used in the case where a user has specifically requested a sync immeditely. …
> M-15177: All user input syncs should be forced

- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/VaultRepository.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/other/OtherViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/SendViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/verificationcode/VerificationCodeViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/search/SearchViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/other/OtherViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/send/SendViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/verificationcode/VerificationCodeViewModelTest.kt
[PM-15177](https://bitwarden.atlassian.net/browse/PM-15177) Part 1
This PR adds the ability to force a sync and bypass the normal checks that occur before syncing. This is meant to be used in the case where a user has specifically requested a sync immediately.
This was cherry-picked from main.
- 🤔 …
> All user input syncs should be forced

- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/di/PlatformDiskModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/DatabaseSchemeManager.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/DatabaseSchemeManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/di/PlatformManagerModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/tools/generator/datasource/disk/di/GeneratorDiskModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/disk/callback/DatabaseSchemeCallback.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/disk/di/VaultDiskModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/DatabaseSchemeManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/datasource/disk/callback/DatabaseSchemeCallbackTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt
[PM-15177](https://bitwarden.atlassian.net/browse/PM-15177)
This PR update the logic for managing a destructive fallback. The big difference is that we clear the `lasSyncTime` for all users to ensure that vault gets re-synced. …
> PM-15177: Improve destructive fallback logic

- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryImpl.kt
N/A
This PR ensures that the `lastSyncTime` is updated before re-syncing the vault. This is to make sure the vault does not re-emit while the `lastSyncTime` is null as that can cause an incorrect loading state. …
> Ensure lastSyncTime is updated before resyncing the vault

- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSource.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSourceImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSourceTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/disk/util/FakeSettingsDiskSource.kt
N/A
This PR removes the `lastDatabaseSchemeChangeInstant ` and `lastDatabaseSchemeChangeInstantFlow` from the `SettingDiskSource` as it is not used anymore. …
> Remove unused lastDatabaseSchemeChangeInstant from settings disk source

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemSshKeyContent.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemScreenTest.kt
PM-15116
Add common vault item content (notes, custom fields, and attachments) to the SSH key content screen.
Coming soon! …
> [PM-15116] Add common vault item content to SSH keys

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/masterpasswordguidance/MasterPasswordGuidanceScreen.kt
[PM-15147](https://bitwarden.atlassian.net/browse/PM-15147)
- Address PR comments from previous [PR](https://github.com/bitwarden/android/pull/4383)
- Remembering viewModel to prevent unnecessary recompositions and fix order of function parameters …
> PM-15147 - `MasterPasswordGuidanceScreen` PR Cleanup

- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/clipboard/BitwardenClipboardManagerImpl.kt
- app/src/main/res/values/strings.xml
[PM-15599](https://bitwarden.atlassian.net/browse/PM-15599)
This PR updates the toast when copying a password to no longer display the value being copied. …
> PM-15599: Update copy toast to not display copied value

- .github/CODEOWNERS
https://bitwarden.atlassian.net/browse/PM-9328
Updates CODEOWNERS to assign everything inside `.github` folder to the mobile team. This was previously done in the ios repo but android was missing it. …
> [PM-9328] Mobile team owns changes to the .github folder

- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/util/SpecialCircumstanceExtensions.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/util/SpecialCircumstanceExtensionsTest.kt
PM-15057
Renamed `toFido2RequestOrNull` to `toFido2CreateRequestOrNull` to better reflect its purpose of retrieving a Fido2CreateCredentialRequest from a SpecialCircumstance. …
> [PM-15057] Rename toFido2RequestOrNull to toFido2CreateRequestOrNull

- app/src/main/java/com/x8bit/bitwarden/data/autofill/util/AutofillRequestExtensions.kt
- app/src/test/java/com/x8bit/bitwarden/data/autofill/util/AutofillRequestExtensionsTest.kt
https://bitwarden.atlassian.net/browse/PM-13513
Closes #4082 
Android apps can't recognize autofill URI's properly without the "androidapp" prefix scheme. 
Keeping it when saving a new login from and Android app …
> [PM-13513] Keeping "androidapp" scheme on uri when saving from Android Apps

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditSshKeyItems.kt
PM-15116
Add the common cipher fields to the add/edit screen so they can be modified when editing an existing SSH key. …
> [PM-15116] Add common fields to SSH Key add/edit screen

- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/other/OtherScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/other/OtherViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/SendViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/other/OtherViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/send/SendViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-15624
When the following actions occur the response should be:
- Pull to Refresh | Loading wheel appears briefly, no error shown
- "Sync now" in other settings | "Internet connection required" error shown
- Attempting to add/edit Cipher | "Internet connection required" error shown
- Attempting to add/edit Send | "Internet connection required" error shown
- Unlocking vault when sync has been >30 mins | Able to log in, no error shown
- Updated any necessary documentation or …
> PM-15624 Align handling of no network states with iOS app.

- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/FlagKey.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/FlagKeyTest.kt
[PM-15831](https://bitwarden.atlassian.net/browse/PM-15831)
- Enabled `enable-authenticator-sync-android` to be remotely configurable  …
> PM-15831 - Enable remote configuration of `enable-authenticator-sync-android` feature flag

- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/FlagKey.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/FlagKeyTest.kt
[PM-15831](https://bitwarden.atlassian.net/browse/PM-15831)
- Cherry pick the commit from the previous [PR](https://github.com/bitwarden/android/pull/4441) …
> PM-15831 - 🍒 Enable remote configuration of `enable-authenticator-sync-android` feature flag

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenHiddenPasswordField.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenPasswordField.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenPasswordFieldWithActions.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenTextField.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenTextFieldWithActions.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/toolbar/BitwardenCutCopyTextToolbar.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/toolbar/BitwardenEmptyTextToolbar.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/model/TextToolbarType.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreen.kt
[PM-15599](https://bitwarden.atlassian.net/browse/PM-15599)
This PR overrides the default `TextToolbar` in order to ensure that all text that is cut or copied, is always treated as sensitive data.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/b32eae33-a2ad-4d01-931a-d5c7f8e5c2aa" width="300" /> | <video src="https://github.com/user-attachments/assets/670a4a3e-710f-4db4-b3f6-56941bdf7009" width="300" /> |
- Updated any necessary documentation or informed the documentation …
> PM-15599: Allow for custom TextToolbars

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/importlogins/ImportLoginsViewModel.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/importlogins/ImportLoginsViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-15037
- Add title "Import error" to the dialog shown when a sync after the import logins flow is empty.
- 🎨 …
> PM-15037 Add missing title to empty sync import logins error dialog

- .github/workflows/build.yml
- app/build.gradle.kts
PM-15176
This change updates the build output filenames to align with established conventions and expectations. 
The new expected output filenames are:
```
standardRelease -> com.x8bit.bitwarden.apk
standardBeta    -> com.x8bit.bitwarden.beta.apk
standardDebug   -> com.x8bit.bitwarden.dev.apk
fdroidRelease   -> com.x8bit.bitwarden-fdroid.apk
fdroidBeta      -> com.x8bit.bitwarden.beta-fdroid.apk
fdroidDebug     -> com.x8bit.bitwarden.dev-fdroid.apk
```
- Updated any necessary documentation or informed the …
> [PM-15176] Update build output filenames

- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSource.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSourceImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/ReviewPromptManager.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/ReviewPromptManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/di/PlatformManagerModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/tools/generator/repository/GeneratorRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/tools/generator/repository/di/GeneratorRepositoryModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/manager/CipherManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/manager/di/VaultManagerModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/di/VaultRepositoryModule.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/util/IntExtensions.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSourceTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/disk/util/FakeSettingsDiskSource.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/ReviewPromptManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/tools/generator/repository/GeneratorRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/manager/CipherManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/util/IntExtensionsTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-15380
- Track when a user adds a new cipher item.
- Track when a user creates a new send.
- Track when a user uses a generated value on an existing item.
- If any of these is down 3 or more times that is considered qualifying for the action portion of showing the app review card.
- ❓ …
> PM-15380 Track user interactions which would trigger a potential showing of the app review prompt.

- app/src/standard/java/com/x8bit/bitwarden/data/platform/manager/LogsManagerImpl.kt
N/A
This PR fixes a bug where we would plant duplicate DebugTrees for Timber every time the user toggles the logging flag. This change will ensure we only plant the tree once at start up. …
> Ensure DebugTree is only planted once

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditSshKeyItems.kt
PM-15862
Hide the Linked Fields option from the custom field selection dialog for SSH key item types.
- ❌ …
> [PM-15862] Remove Linked Fields option from SSH keys

- app/src/main/assets/fido2_privileged_community.json
Fixes #4352
Make Firefox Nightly work with Bitwarden passkeys …
> [PM-15911] Add Firefox Nightly to FIDO2 community list

- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/FeatureFlagManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/FlagKey.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/components/FeatureFlagListItems.kt
- app/src/main/res/values/strings_non_localized.xml
https://bitwarden.atlassian.net/browse/PM-15553
Pass down to the SDK a remote flag value to control the cipher key encryption feature state.
- 🎨 …
> [PM-15553] Add remote flag to control cipher key encryption.

- gradle/libs.versions.toml
N/A
This PR updates hilt to the latest version (v2.53.1).
This update removes the warnings in the build logs:
```
w: [ksp] No dependencies reported for generated source com.x8bit.bitwarden.ui.auth.feature.accountsetup.SetupAutoFillViewModel_HiltModules_BindsModule_Binds_LazyMapKey.java which willprevent incremental compilation.
```
[Release Notes!](https://github.com/google/dagger/releases/tag/dagger-2.53.1) …
> Update to Hilt 2.53.1

- app/build.gradle.kts
PM-15176
This commit introduces a new task, `renameAabFiles`, that is executed after the `bundle` task. This task renames the output aab files match the APK naming conventions, such as `com.x8bit.bitwarden.dev.aab` for the standard debug build and `com.x8bit.bitwarden.aab` for the standard release build. …
> [PM-15176] Rename AAB outputs to match APK naming convention

- app/build.gradle.kts
PM-16052
This change adds a `CI_INFO` build config field that is populated from the `ci.properties` file if it exists. If the file does not exist, the value defaults to "local". …
> [PM-16052] Add CI_INFO build config field

- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/appearance/AppearanceScreen.kt
[PM-16053](https://bitwarden.atlassian.net/browse/PM-16053)
- Previously, the dialog used the Text value directly within the string resource. This update leverages the `invoke` function to correctly resolve and display the actual string of the language correctly.
https://github.com/user-attachments/assets/a9b4a601-ca1a-4ebc-900a-919d1addf4ed
https://github.com/user-attachments/assets/a2f30bd6-cc9b-47ad-ade5-d77f94e3975f …
> PM-16053 - Text in Prompt to Restart App After Changing Language in Settings 

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/environment/EnvironmentScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenTextField.kt
[PM-16058](https://bitwarden.atlassian.net/browse/PM-16058)
This PR adds an auto-complete style dropdown to the environments UI for a few default URLs. These are only available in the debug configuration for ease of testing. …
> PM-16058 - Add default environments via autocomplete dropdown

- app/src/main/java/com/x8bit/bitwarden/ui/platform/base/util/Text.kt
[PM-15976](https://bitwarden.atlassian.net/browse/PM-15976)
- prevent crash caused by not being able to apply span to non translated string.
- 🎨 …
> PM-15976 🍒  prevent app crash for non english language

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/completeregistration/CompleteRegistrationScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/createaccount/CreateAccountScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/enterprisesignon/EnterpriseSignOnScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/environment/EnvironmentScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/landing/LandingScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/resetpassword/ResetPasswordScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/setpassword/SetPasswordScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/startregistration/StartRegistrationScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dialog/BitwardenTextEntryDialog.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenTextField.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenTextFieldWithActions.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/PinInputDialog.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditCardItems.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditIdentityItems.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditLoginItems.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditSecureNotesItems.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditSshKeyItems.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemCardContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemIdentityContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemLoginContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemSecureNoteContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemSshKeyContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/manualcodeentry/ManualCodeEntryScreen.kt
https://bitwarden.atlassian.net/browse/PM-16058
- Adding the autocomplete menu changed the structure of the of the `BitwardendTextField` composbale. Adding in an explicit parameter for the test tag that should be applied to the actual editable field. …
> PM-16058 add test tag parameter to be applied to the text field

- .github/workflows/test.yml
PM-16207
1. Codecov v5 workflow deprecated the `file` input, changed it to `files`. This has been silently failing. 
2. Remove secrets used in test.yml …
> [PM-16207] chore(ci): Fix codecov usage and remove secrets from test.yml

- .github/workflows/scan-ci.yml
- .github/workflows/scan.yml
PM-16208
1. Adds a new scan workflow triggered on push to protected branches, splitting this responsibility from the pull request scan. Kept the filename of the existing file the same given the multiple changes required but we should rename it to `scan-pr.yml` or similar in a future isolated PR. 
2. Migrates to new sonarqube action as instructed in https://github.com/SonarSource/sonarcloud-github-action …
> [PM-16208] chore(ci): Split scan workflow for protected branches and migrate to new sonarqube action

- gradle/libs.versions.toml
PM-15057
This commit updates the AndroidX Credentials dependency to version 1.5.0-alpha04, which includes new features and API changes to improve security for FIDO2 credential creation and retrieval. This introduces biometrics for both request types using the `BiometricPrompt` API. It also adds support for a new `DigitalCredential` type, as well as `RestoreCredential`, used to transfer the credential from the previous device to a new one.
Note: Versions `>= 1.5.0-alpha05` introduce breaking changes and bugs that are not yet suitable for production. This update targets `1.5.0-alpha04` while we wait for those issues to be resolved.
- Used …
> [PM-15057] Update AndroidX Credentials to 1.5.0-alpha04

- .github/workflows/release-branch.yml
PM-16211
The previous method to retrieve the last release git tag only worked when all tags are in the main branch. We'll now get the last tag across all branches. 
While at it removed the rc prefix input which won't be used in this repo. …
> [PM-16211] chore(ci): Fix hotfix branch creation workflow by retrieving the last tag across all branches 

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/util/CollectionViewExtensions.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/util/model/CollectionPermission.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/datasource/sdk/model/CollectionViewUtil.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/util/CollectionViewExtensionsTest.kt
[PM-15970](https://bitwarden.atlassian.net/browse/PM-15970)
[PM-15969](https://bitwarden.atlassian.net/browse/PM-15969)
Allows assigning items to collections if the user has manage permissions and is not restricted from viewing or editing password in the collection. This fixes an issue where collection assignment would be blocked if the user could view the item and its passwords.
Coming soon!
- 📝 …
> [PM-15970] Allow assigning collections if user has correct permissions

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModelTest.kt
PM-15863
Add a master password prompt before revealing the private SSH key if the content requires reprompt. …
> [PM-15863] Request master password before revealing private SSH key

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt
PM-12391
Check the `isUnlockWithPinEnabled` setting instead of checking the `vaultUnlockType` of the active account to determine if a PIN prompt should be shown. …
> [PM-12391] Respect PIN unlock setting during FIDO user verification

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemSshKeyContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/handlers/VaultSshKeyItemTypeHandlers.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModelTest.kt
PM-15864
Adds a copy button to the private key field in SSH key entries, allowing users to easily copy the private key to the clipboard.
- 🎨 (`:art:`) …
> [PM-15864] Add copy private key action for SSH keys

- app/src/main/java/com/x8bit/bitwarden/data/autofill/util/AutofillIntentUtils.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/AppStateManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/AppCreationState.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/manager/VaultLockManagerImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/AppStateManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/util/FakeAppStateManager.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/manager/VaultLockManagerTest.kt
[PM-16062](https://bitwarden.atlassian.net/browse/PM-16062)
- When the app was being opened by the AutoFill/Accessibility services from a cold start, the user would need to unlock the vault, and once completing the AutoFill request the vault was being locked based on the state being send to the `VaultLockManager`. 
- This was especially called out for logins that have a (2 page) flow, where the user was being asked to unlock the vault again to grab the password on the second page.
- This change changes the `VaultLockManager` to check the timeout action instead on events of the activity being created for the first time with the added context of if was created for Autofill purposes.
https://github.com/user-attachments/assets/982edd38-2aea-4e76-94c9-1f73d70f1277
- Contributor guidelines …
> PM-16062 Prevent account locks for ongoing autofill requests

- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/disk/model/AccountJson.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/util/GetTokenResponseExtensions.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/util/UserStateJsonExtensions.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/model/SyncResponseJson.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/datasource/disk/AuthDiskSourceTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/manager/AuthRequestManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/manager/TrustedDeviceManagerTests.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/manager/UserLogoutManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/manager/util/TrustDeviceResponseExtensionsTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/util/AuthDiskSourceExtensionsTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/util/GetTokenResponseExtensionsTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/util/UserStateJsonExtensionsTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/FirstTimeActionManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/tools/generator/repository/GeneratorRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/datasource/network/model/SyncResponseProfileUtil.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/datasource/network/service/SyncServiceTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/manager/CipherManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/manager/VaultLockManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt
https://bitwarden.atlassian.net/browse/PM-8217
Add creationDate and isTwoFactorEnable properties to user account. Values were already being passed down from api response but were previously ignored.
issue …
> [PM-8217] Add creationDate and isTwoFactorEnable properties

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenTextField.kt
- applying the padding twice with passed in Modifier, it should only be applied to the outer `Box`
- Fix double padding. …
> Update the text field to not use passed in modifier.

- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/FlagKey.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/components/FeatureFlagListItems.kt
- app/src/main/res/values/strings_non_localized.xml
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/FlagKeyTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-8217
In order for QA to fully test the new device two factor notice feature, we need to bypass the requirement of only showing the notice to Bitwarden Cloud environments.  …
> [PM-8217] Add local feature flag to ignore environment validation

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/util/CollectionViewExtensions.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/util/CollectionViewExtensionsTest.kt
https://bitwarden.atlassian.net/browse/PM-15969
Fix bug where users with Can Edit permission in one collection could not use "assign to collection".
https://github.com/user-attachments/assets/9c9b98de-f5f3-4fdc-a294-f16d27de27ec …
> [PM-15969] Users with `Can Edit` access cannot assign collections

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/util/CollectionViewExtensions.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/util/CollectionViewExtensionsTest.kt
`Backport:`https://github.com/bitwarden/android/pull/4512
https://bitwarden.atlassian.net/browse/PM-15969
Fix bug where users with Can Edit permission in one collection could not use "assign to collection".
https://github.com/user-attachments/assets/9c9b98de-f5f3-4fdc-a294-f16d27de27ec
- 🤔 …
> [PM-15969] Users with Can Edit access cannot assign collections

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/newdevicenotice/NewDeviceNoticeEmailAccessScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/newdevicenotice/NewDeviceNoticeEmailAccessViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/newdevicenotice/NewDeviceNoticeEmailAccessScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/newdevicenotice/NewDeviceNoticeEmailAccessViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-16695
Added a "learn more" button that redirects the user into https://bitwarden.com/help/new-device-verification/ …
> [PM-16695] Added "learn more" link to NewDeviceNoticeEmailAccess

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultContent.kt
[PM-16821](https://bitwarden.atlassian.net/browse/PM-16821)
This PR removes the extra padding on the right side of the dividers on the Vault Screen.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/cf586fd1-0942-45f3-9d41-4f3778a32b4a" width="300" /> | <img src="https://github.com/user-attachments/assets/4c8a3c58-04a5-4212-a854-fac15e446842" width="300" /> |
- 📝 …
> PM-16821: remove padding on right side of the vault screen dividers

- app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/processor/Fido2ProviderProcessorImpl.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/data/autofill/fido2/processor/Fido2ProviderProcessorTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
PM-16120
This commit refactors the FIDO2 Get Credentials request handling in `Fido2ProviderProcessorImpl` to use `takeUntilLoaded` and `fold` to collect `CipherView` data. This ensures querying for matching items is not performed until vault data for the active user is loaded.
We also defer the handling of FIDO2 assertion requests until the vault data is loaded. This ensures the selected item data is available before attempting authentication.
These changes prevent unexpected failures when a passkey authentication request is received while the application is not actively running.
| <video src="https://github.com/user-attachments/assets/98e99c7a-070e-47d0-b38b-2341cfdbb2a5"/> | <video src="https://github.com/user-attachments/assets/1fafee2f-7850-4333-a …
> [PM-16120] Defer passkey authentication until vault data is loaded

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/newdevicenotice/NewDeviceNoticeEmailAccessViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/newdevicenotice/NewDeviceNoticeTwoFactorViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/newdevicenotice/NewDeviceNoticeEmailAccessViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/newdevicenotice/NewDeviceNoticeTwoFactorViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-16809
Fix bug introduced during PR when the remind me later date wasn't being set properly. …
> [PM-16809] Fix remind me later date

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenTextField.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenTextFieldWithActions.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreen.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreenTest.kt
[PM-14179](https://bitwarden.atlassian.net/browse/PM-14179)
This PR moves the password copy button down and make it more pronounces as well as updates the `BitwardenTextField` to allow for nullable labels.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/6c22b024-00a9-4d46-9c07-4bcd732ec438" width="300" /> | <img src="https://github.com/user-attachments/assets/d103905c-a41d-4f1d-af5b-ad0449de934a" width="300" /> |
- Updated any necessary documentation or informed the …
> PM-14179: Update generator screen copy button

- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/newdevicenotice/NewDeviceNoticeTwoFactorViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/newdevicenotice/NewDeviceNoticeTwoFactorViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-16670
We need the app to sync when the user leaves the app to setup a two factor method and comes back. This will void the grace period of 30 mins between vault syncs.  …
> [PM-16670] Force app to sync after 2FA notice

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/newdevicenotice/NewDeviceNoticeEmailAccessViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/newdevicenotice/NewDeviceNoticeTwoFactorViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/newdevicenotice/NewDeviceNoticeEmailAccessViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/newdevicenotice/NewDeviceNoticeTwoFactorViewModelTest.kt
`Backport:` https://github.com/bitwarden/android/pull/4526 …
> [PM-16809] Fix remind me later date (#4526)

- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/newdevicenotice/NewDeviceNoticeTwoFactorViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/newdevicenotice/NewDeviceNoticeTwoFactorViewModelTest.kt
`Backport:` https://github.com/bitwarden/android/pull/4525 …
> [PM-16670] Force app to sync after 2FA notice (#4525)

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/util/CipherViewExtensions.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/util/CipherViewExtensionsTest.kt
https://bitwarden.atlassian.net/browse/PM-13349
Hide Edit option in cipher list item overflow when editing not permitted (accompanies #4430)
- 🎨 …
> [PM-13349] Hide Edit option in cipher list item overflow when editing not permitted

- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/disk/AuthDiskSource.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/disk/AuthDiskSourceImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/BiometricsEncryptionManager.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/BiometricsEncryptionManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/di/PlatformManagerModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepository.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/di/PlatformRepositoryModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/VaultRepository.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupUnlockScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupUnlockViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/handlers/SetupUnlockHandler.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/manager/biometrics/BiometricsManager.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/manager/biometrics/BiometricsManagerImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/datasource/disk/AuthDiskSourceTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/datasource/disk/util/FakeAuthDiskSource.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupUnlockScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupUnlockViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityViewModelTest.kt
[PM-15356](https://bitwarden.atlassian.net/browse/PM-15356)
This PR adds an extra layer of security to the biometrics prompt by signing the user key before storing it, meaning that only a real cipher from the Biometric Prompt can decrypt the data and unlock the vault. …
> PM-15356: Resolve biometrics bypass

- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/search/util/SearchTypeDataExtensions.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/search/util/SearchTypeDataExtensionsTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/search/util/SearchUtil.kt
PM-9439
Display the passkey icon for search results that contain FIDO2 credentials when the web icon is unavailable.
| <img width="378" alt="image" src="https://github.com/user-attachments/assets/c6982651-bbad-4ff1-a754-af84524393f6" /> | <img width="378" alt="image" src="https://github.com/user-attachments/assets/c9b434f0-f50f-4843-bfff-94d434cbcf62" /> |
- 📝 …
> [PM-9439] Use passkey icon for items with FIDO2 credentials in search results

- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/newdevicenotice/NewDeviceNoticeEmailAccessViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/newdevicenotice/NewDeviceNoticeTwoFactorViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/newdevicenotice/NewDeviceNoticeEmailAccessViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/newdevicenotice/NewDeviceNoticeTwoFactorViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-16670
When the user configures a two factor method, we need to dismiss the new device notice if it is showing.
https://github.com/user-attachments/assets/b448ae64-19a1-492a-b181-e8cdb239287a …
> [PM-16670] Add check for 2fa status

- app/src/main/res/values/strings.xml
https://bitwarden.atlassian.net/browse/PM-16808
Add missing question mark to label: "_Do you have reliable access to your email, **...** ?_"
- 🎨 …
> [PM-16808] Add question mark to copy

- app/src/main/assets/fido2_privileged_community.json
- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/util/BrowserUtil.kt
- app/src/main/res/xml/autofill_service_configuration.xml
This issue was brought to our attention via a user from our Discord Server.
IronFox is a new privacy and security-oriented web browser for Android, based on Firefox. It's forked from the recently discontinued [Mull Browser](https://divestos.org/pages/our_apps#mull).
Autofilling log-in info from Bitwarden in IronFox is currently broken; this fixes it by adding our app ID.
Please let me know if there's any questions or concerns :)
> [PM-16870] Add support for IronFox

- .github/workflows/test.yml
[PM-16827](https://bitwarden.atlassian.net/browse/PM-16827)
We won't have coverage reports when tests fail.  …
> [PM-16827] Only report coverage when tests pass

- app/src/main/java/com/x8bit/bitwarden/BitwardenApplication.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/disk/AuthDiskSourceImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/di/PlatformManagerModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/network/NetworkConfigManager.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/network/NetworkConfigManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/network/NetworkConnectionManager.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/network/NetworkConnectionManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/enterprisesignon/EnterpriseSignOnViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/masterpasswordhint/MasterPasswordHintViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/other/OtherViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/network/NetworkConfigManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/network/NetworkConnectionManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/util/FakeNetworkConnectionManager.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/masterpasswordhint/MasterPasswordHintViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/other/OtherViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt
PM-17011
Moves `NetworkConfigManager` and `NetworkConnectionManager` to the `network` subpackage.
This change is for better organization of the project. There are no functional changes. …
> [PM-17011] Move network managers to `network` package

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/indicator/BitwardenCircularProgressIndicator.kt
[PM-16830](https://bitwarden.atlassian.net/browse/PM-16830)
- Update the loading indicator to match the new reskin.  Originally I had read this story wrong and was implementing this app-wide for the full screen loading but after a sync with Dave I realized this ticket is much smaller in size. 
- Using the existing `CircularProgressIndicator` and updated the `trackColor` property to match the new reskin color.  Confirmed with Emily this looks good for this particular ticket. 
https://github.com/user-attachments/assets/e450a79f-818d-4978-951b-1f0f093d6809
- Communicated …
> PM-16830 - Update global loading screen component to new reskinned version

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/masterpasswordhint/MasterPasswordHintScreen.kt
> [QA-968] Adding missing testTag for MP hint email field

- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/folders/addedit/FolderAddEditScreen.kt
> [QA-969] Adding missing testTag for Folder Name textfield

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/newdevicenotice/NewDeviceNoticeTwoFactorNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/newdevicenotice/NewDeviceNoticeTwoFactorScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/newdevicenotice/NewDeviceNoticeTwoFactorViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlocked/VaultUnlockedNavigation.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/newdevicenotice/NewDeviceNoticeTwoFactorScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/newdevicenotice/NewDeviceNoticeTwoFactorViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-16905
The second screen of new device notice was missing a back button in its UI. This PR address that issue. …
> [PM-16905] Add back button to new device notice

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenHiddenPasswordField.kt
N/A
The `BitwardenHiddenPasswordField` was missing card padding. This PR addresses that issue.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/deae238e-8c10-4375-9f5f-8e30f57b499a" width="300" /> | <img src="https://github.com/user-attachments/assets/bfe2dd49-d275-4d89-aba4-08783d9fff7c" width="300" /> | …
> Add correct card padding to BitwardenHiddenPasswordField

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditLoginItems.kt
N/A
This PR addresses a bug when creating a new login cipher where the type card and the name card are too close together.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/20167c99-7d78-44d1-a94a-b8d36fc7a086" width="300" /> | <img src="https://github.com/user-attachments/assets/ace2ced9-5957-4d91-91f2-f27d1ec6340f" width="300" /> | …
> Add spacer between type and name when creating a login cipher

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dropdown/EnvironmentSelector.kt
N/A
This PR removes an unnecessary outer box from the `EnvironmentSelector` composable. There should be no visible UI changes as part of this update.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/2212866a-df41-45df-946c-bbda4e9555ca" width="300" /> |<img src="https://github.com/user-attachments/assets/bf3e486f-d418-45b9-af67-dc1a895d5399" width="300" /> |
- 📝 …
> Remove outer box on EnvironmentSelector

- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/FlagKey.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/components/FeatureFlagListItems.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-17405
Adds a new feature flag for mutual TLS.
This commit introduces a new feature flag named `mutual-tls` that can be used to enable or disable mutual TLS authentication. It also includes necessary UI elements to interact with the flag in the debug menu.
- 🤔 …
> [PM-17405] Add mutual TLS feature flag

- app/src/main/java/com/x8bit/bitwarden/MainActivity.kt
- app/src/main/java/com/x8bit/bitwarden/MainViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSource.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSourceImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepository.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/appearance/AppearanceViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/appearance/model/AppTheme.kt
- app/src/test/java/com/x8bit/bitwarden/MainViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSourceTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/disk/util/FakeSettingsDiskSource.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/appearance/AppearanceViewModelTest.kt
[PM-17404](https://bitwarden.atlassian.net/browse/PM-17404)
This PR sets the theme on the `AppCompatDelegate` whenever the user changes the theme in app. This ensure that all image resources are updated properly. …
> PM-17404: Set app delegate on theme change

- app/src/main/java/com/x8bit/bitwarden/MainViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/di/Fido2ProviderModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/model/Fido2CreateCredentialRequest.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/model/Fido2CredentialAssertionRequest.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/processor/Fido2ProviderProcessorImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/util/Fido2IntentUtils.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/FlagKey.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/components/FeatureFlagListItems.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/MainViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/autofill/fido2/manager/Fido2CredentialManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/autofill/fido2/model/Fido2CredentialAssertionRequestUtil.kt
- app/src/test/java/com/x8bit/bitwarden/data/autofill/fido2/model/Fido2CredentialRequestUtil.kt
- app/src/test/java/com/x8bit/bitwarden/data/autofill/fido2/processor/Fido2ProviderProcessorTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/autofill/fido2/util/Fido2IntentUtilsTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/util/SpecialCircumstanceExtensionsTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/util/Fido2CredentialRequestExtensionsTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/util/VaultItemListingDataExtensionsTest.kt
PM-15906
PM-12511
Resolves https://github.com/bitwarden/android/issues/3953
Add a biometric prompt to the passkey registration and authentication flows.
The biometric prompt will be shown when creating or authenticating with a passkey if the user has supported device biometrics enabled.
This change also adds an `isUserVerified` flag to the Fido2 requests to determine if the user has verified their identity using the single tap flow.
> [!NOTE]
> When vault timeout is set to immediate, users must unlock multiple times. This is intentional since the application is set to lock immediately after backgrounding and the passkey flow requires backgrounding the application after initial unlock and credential discovery.
| Case   | Before | After  |
|--------|--------|--------|
| Create | <video …
> [PM-15906] Implement single tap passkey flows

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/login/LoginScreen.kt
[PM-17410](https://bitwarden.atlassian.net/browse/PM-17410)
This PR updates the font on the `Get master password hint` button.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/f17709c9-8270-49b6-8f48-250fce8bec58" width="300" /> | <img src="https://github.com/user-attachments/assets/50c535b6-b746-4c3f-af07-d7bfb8d47321" width="300" /> | …
> PM-17410: Update password hint font

- app/src/main/java/com/x8bit/bitwarden/data/vault/manager/VaultLockManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/manager/di/VaultManagerModule.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/manager/VaultLockManagerTest.kt
[PM-17130](https://bitwarden.atlassian.net/browse/PM-17130)
[PM-15804](https://bitwarden.atlassian.net/browse/PM-15804)
This PR adds a broadcast receiver to the `VaultLockManager` in order to ensure that we lock the vault at the soonest possible moment.
There seems to be an issue in the way `delay` works inside a coroutine scope when the screen is off. The `delay` will take significantly longer to complete and cause the vault to not lock when it is supposed to. This new solution restarts the delay with an appropriate remaining time when the screen is turned back on to ensure we lock the vault correctly.
- Used internationalization (i18n) …
> PM-15804, PM-17130: Add logic to monitor when the screen on state to ensure the vault locks properly

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenTextField.kt
[PM-14179](https://bitwarden.atlassian.net/browse/PM-14179)
This PR moves the test tag on the `BitwardenTextField` to the actual `TextField` instead of the wrapping component. THis should fix some issue with automation. …
> PM-14179: Update internal placement of test tags for the BitwardenTextField

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/masterpasswordgenerator/MasterPasswordGeneratorScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenHiddenPasswordField.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenPasswordField.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenPasswordFieldWithActions.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/stepper/BitwardenStepper.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreen.kt
PM-17409
This PR allows the various text fields to have a null label. When the label is null, the content will be centered more appropriately that when the label is present but empty.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/8ecd86b0-5de2-4604-a337-d4b12b1e503a" width="300" /> | <img src="https://github.com/user-attachments/assets/fe3a1b9a-ab87-43c8-9012-d7e885d3dcf7" width="300" /> |
- 👍 (`:+1:`) …
> PM-17409: Allow nullable labels text fields

- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSource.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSourceImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/FirstTimeActionManager.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/FirstTimeActionManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/CoachMarkTourType.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/handlers/PasswordHandlers.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditItemContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/handlers/VaultAddEditLoginTypeHandlers.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSourceTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/disk/util/FakeSettingsDiskSource.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/FirstTimeActionManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt
[PM-16621](https://bitwarden.atlassian.net/browse/PM-16621)
[PM-16630](https://bitwarden.atlassian.net/browse/PM-16630)
- Show action cards if they have not been shown to user before and the native onboarding feature flag is enabled.
- Once interacting with the card, should be removed from screens and not show again.
https://github.com/user-attachments/assets/11af3d96-ad39-43b3-ac03-748fc65fe831
- 📝 …
> PM-16630 PM-16621 Add logins action card and add explore generator card to be able to trigger coach marks

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/completeregistration/CompleteRegistrationScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/createaccount/CreateAccountScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/removepassword/RemovePasswordScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/resetpassword/ResetPasswordScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/setpassword/SetPasswordScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dialog/BitwardenMasterPasswordDialog.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dialog/BitwardenPinDialog.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenHiddenPasswordField.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenPasswordField.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenPasswordFieldWithActions.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenTextField.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/exportvault/ExportVaultScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditCardItems.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditLoginItems.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditSshKeyItems.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemLoginContent.kt
N/A
This PR fixes an issue occurring in the UI automation tests where the test tags need to be applied to the actual `TextField` instead of the outer element. …
> Update BitwardenPasswordField TestTags

- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/model/ImportPrivateKeyResult.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/model/MutualTlsCertificate.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/model/MutualTlsKeyHost.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/KeyManager.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/KeyManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/di/PlatformManagerModule.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/KeyManagerTest.kt
PM-17424
Relates to #4606, #4486
Implement a new manager, `KeyManager`, for managing key-related data.
This includes:
- Importing a mutual TLS certificate into the AndroidKeyStore.
- Removing a mutual TLS certificate from the AndroidKeyStore.
- Retrieving a mutual TLS certificate from the AndroidKeyStore or system KeyChain.
- ❓ …
> [PM-17424] Implement KeyManager for handling private keys

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dialog/BitwardenClientCertificateInfoDialog.kt
- app/src/main/res/values/strings.xml
PM-17531
Relates to #4486 
This commit introduces a new dialog for importing client certificates. The dialog prompts the user to enter the certificate password and alias. …
> [PM-17531] Add dialog for client certificate import

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/landing/LandingScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/startregistration/StartRegistrationScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dropdown/EnvironmentSelector.kt
- app/src/main/res/values/strings.xml
[PM-17377](https://bitwarden.atlassian.net/browse/PM-17377)
This PR makes small tweaks to the Environment selector UI.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/00d5e32c-3ec9-4adf-8859-6255d0fbe717" width="300" /> | <img src="https://github.com/user-attachments/assets/2e6a8415-24fb-4f8f-81f8-068abe4e3b8b" width="300" /> | …
> PM-17377: Update text, formatting, and style for the environment selector

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/landing/LandingScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/landing/LandingViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginViewModel.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/landing/LandingScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/landing/LandingViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginViewModelTest.kt
[PM-17378](https://bitwarden.atlassian.net/browse/PM-17378)
This PR updates the remember text to match the latest designs.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/507b256b-6ceb-4457-8d57-c76679cd1092" width="300" /> | <img src="https://github.com/user-attachments/assets/5165f101-bf3e-42a4-8f76-b7e5ba558190" width="300" /> | …
> PM-17378: Update remember me text

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/manualcodeentry/ManualCodeEntryScreen.kt
[PM-17638](https://bitwarden.atlassian.net/browse/PM-17638)
This PR updated the `ManualCodeEntryScreen` to use the appropriate card backgrounds.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/92eec488-8608-4c41-b1c1-15bec68b100e" width="300" /> | <img src="https://github.com/user-attachments/assets/9caf675e-2e71-4bea-883c-a69fe80cb69a" width="300" /> |
- 📝 …
> PM-17638: Add card background for the manual totp screen

- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/DebugMenuRepository.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/DebugMenuRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/coachmark/CoachMarkContainer.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/coachmark/CoachMarkScopeInstance.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/coachmark/CoachMarkState.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/coachmark/LazyListCoachMarkState.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/coachmark/model/CoachMarkHighlightState.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/tooltip/BitwardenToolTipState.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/tooltip/BitwardenToolTipStateImpl.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuViewModel.kt
- app/src/main/res/values/strings_non_localized.xml
- app/src/test/java/com/x8bit/bitwarden/data/platform/repository/DebugMenuRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuViewModelTest.kt
[PM-17650](https://bitwarden.atlassian.net/browse/PM-17650)
- Prevent the tool tip from being dismissed at all when user clicks outside.
- Previous behavior it disappears and returns. 
- Overrides the default `dismiss` function of the tool tip state which is what the Google api calls under the hood to dismiss the tooltip when there is a click outside.
- Added way to reset coach mark related card show values to be able to test the tours easier.
https://github.com/user-attachments/assets/79268afa-5ea0-41a7-9d10-89e414ecdb5d …
> PM-17650 Implement custom tool tip state to prevent tool tips from dismissing.

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/login/LoginScreen.kt
[PM-17382](https://bitwarden.atlassian.net/browse/PM-17382)
- Update the style/color on text on the `LoginScreen` …
> PM-17382 - Update “Logging in as…” text and link style on log in screen

- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/FlagKey.kt
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 …
> Update SingleTapPasskeyAuthentication and SingleTapPassskeyCreation to be remote flags

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/color/BitwardenTextFieldColors.kt
[PM-17684](https://bitwarden.atlassian.net/browse/PM-17684)
This PR updates the cursor color throughout the app.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/d4e5b983-2687-4d79-93f1-4e373e0627f5" width="300" /> | <img src="https://github.com/user-attachments/assets/7d2910b3-80e9-43e2-83a6-59779196c038" width="300" /> …
> PM-17684: Update the cursor color throughout the app

- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/util/AddSendStateExtensions.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/util/AddSendStateExtensionsTest.kt
[PM-17680](https://bitwarden.atlassian.net/browse/PM-17680)
This PR will set the expiration date on sends to the deletion date whenever you update a send that already have an expiration date set.
issue …
> PM-17680: Overwrite the expiration date to the deletion date

- app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/manager/AccessibilityEnabledManagerImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/autofill/accessibility/manager/AccessibilityEnabledManagerTest.kt
[PM-17205](https://bitwarden.atlassian.net/browse/PM-17205)
This PR updates the `AccessibilityEnabledManager` to check the status of the accessibility service on start up to avoid default values of false. …
> PM-17205: Check accessibility service status on start up

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dropdown/BitwardenMultiSelectButton.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/appearance/AppearanceScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/other/OtherScreen.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/appearance/AppearanceScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/other/OtherScreenTest.kt
[PM-17721](https://bitwarden.atlassian.net/browse/PM-17721)
This PR updates the dropdown menus in the app.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/4c3a404d-cbfb-4050-b39f-fea843b015c2" width="300" /> | <img src="https://github.com/user-attachments/assets/e19600e5-178e-4172-bcec-70c168d4b8ee" width="300" /> |
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) …
> PM-17721: Update app dropdown menus

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/auth/AuthNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/checkemail/CheckEmailNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/checkemail/CheckEmailScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/checkemail/CheckEmailViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/checkemail/handlers/CheckEmailHandler.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/checkemail/CheckEmailScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/checkemail/CheckEmailViewModelTest.kt
[PM-17388](https://bitwarden.atlassian.net/browse/PM-17388)
- In the existing version of the email screen replace the bottom copy/links with the CTA button matching v3 design.
- In v3 version update from text button to outlined button per design.
https://github.com/user-attachments/assets/0a2e2369-5a62-4fd8-89d0-8d0d231f809c
s
- ❓ …
> PM-17388 Update existing and v3 email verification screen to match design audit

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/landing/LandingScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/startregistration/StartRegistrationScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/startregistration/StartRegistrationViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/startregistration/handlers/StartRegistrationHandler.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenPasswordField.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/startregistration/StartRegistrationScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/startregistration/StartRegistrationViewModelTest.kt
[PM-17384](https://bitwarden.atlassian.net/browse/PM-17384)
[PM-17386](https://bitwarden.atlassian.net/browse/PM-17386)
- Change color of non-link text to Text-Secondary
- Remove Vault illustration in favor of the Bitwarden logo and align spacing
- Reverse order of the name and email fields
- Update back button icon to be a “X” close button
- Update the email address placeholder to `Email address (required)` …
> PM-17384 PM-17386 - Create Account Design Audit

- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorViewModelTest.kt
[PM-16861](https://bitwarden.atlassian.net/browse/PM-16861)
-  When tapping on the same segmented button selection (Password / Passphrase / Username) a new password/passphrase/username is not generated again.  User can tap the same tab over and over and nothing should change.
[untitled.webm](https://github.com/user-attachments/assets/7c724933-8612-4bf3-892f-909f409e6795) …
> PM-16861 - Update Behavior When Tapping Same Generator Tab Already Viewing

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/account/BitwardenAccountSwitcher.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultContent.kt
[PM-17765](https://bitwarden.atlassian.net/browse/PM-17765)
[PM-17767](https://bitwarden.atlassian.net/browse/PM-17767)
- Fix the spacing in the vault screen between the start of the content and the items, move the 16.dp padding between items to the end of "each" section so for conditional content it will only be applied if needed.
- Change icon size in account switcher drop down and set a minimum row height for each option per the desing.
OLD | NEW
- Updated any necessary documentation or informed the documentation …
> PM-17765 & PM-17767 Adjust spacing in vault screen and adjust account switcher icon size and minimum row height

- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/FlagKey.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/repository/DebugMenuRepositoryTest.kt
[PM-17797](https://bitwarden.atlassian.net/browse/PM-17797)
[PM-17798](https://bitwarden.atlassian.net/browse/PM-17798)
- set both onboarding flags to be remotely configurable. …
> PM-17797 and PM-17798 set onboarding features to be remotely configurable

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditLoginItems.kt
N/A
This PR updates the TOTP row for ciphers to use the `coachMarkHighlightItem` helper. There should be no visual changes to the UI. …
> Update TOTP coachmark layout

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultContent.kt
N/A
This PR fixes a spacing issue between card items in the vault screen favorites.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/2273b1b4-86d0-4fa1-bad9-3d069ba1be4b" width="300" /> | <img src="https://github.com/user-attachments/assets/6359dd30-3865-45a1-8b7b-24ae2f72ba90" width="300" /> | …
> Fix vault favorites spacing

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/coachmark/CoachMarkContainer.kt
[PM-17910](https://bitwarden.atlassian.net/browse/PM-17910)
- Prevent going back while coach marks are showing.
https://github.com/user-attachments/assets/b50e0420-8df0-46bf-8ddf-6a04d605be55
issue and …
> PM-17910 Prevent back events from system when coach mark tour is in progress.

- app/src/main/java/com/x8bit/bitwarden/data/autofill/manager/AutofillTotpManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/clipboard/BitwardenClipboardManager.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/clipboard/BitwardenClipboardManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/search/SearchViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/passwordhistory/PasswordHistoryViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/SendViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/verificationcode/VerificationCodeViewModel.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/data/autofill/manager/AutofillTotpManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/search/SearchViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/about/AboutViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/generator/passwordhistory/PasswordHistoryViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/send/SendViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/verificationcode/VerificationCodeViewModelTest.kt
[PM-9535](https://bitwarden.atlassian.net/browse/PM-9535)
The clipboard manager now has additional arguments to set custom text. When text is copied to the clipboard a toast is shown to the user with the custom message regardless of the Android version. This way it's clear what was copied.
Notes
Password
Username
URI
Custom fields
- …
> [PM-9535] Show toast when copying values prior to Android 13

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/manualcodeentry/ManualCodeEntryScreen.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/manualcodeentry/ManualCodeEntryScreenTests.kt
[PM-17851](https://bitwarden.atlassian.net/browse/PM-17851)
This PR updates the UI for the `ManualCodeEntryScreen` to match the v3 designs.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/7101500c-cf17-488c-a3ca-24033d450499" width="300" /> | <img src="https://github.com/user-attachments/assets/55a1254d-f4e4-4cc1-a9f3-2db4332c9e78" width="300" /> |
- 📝 (`:memo:`) …
> PM-17851: Update manual code entry screen

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/coachmark/CoachMarkContainer.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/coachmark/CoachMarkScope.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditLoginItems.kt
https://bitwarden.atlassian.net/browse/PM-17930
Removing the default parameters from CoachMarkHighlight.
Composable functions in an interface do not support default parameters.
Source:
https://issuetracker.google.com/issues/165812010 …
> [PM-17930] Remove default arguments from CoachMarkHighlight

- .github/workflows/test.yml
https://bitwarden.atlassian.net/browse/PM-17939
While troubleshooting Codecov issues I noticed the default branch wasn't correctly set and that Pull Requests are being compared with Merge Queue branches, due to Codecov not supporting the same commit existing in multiple branches ([ref](https://github.com/codecov/feedback/issues/216#issuecomment-1883055575)). By restricting coverage upload to On Push and Pull Request triggers I'm expecting Codecov to start comparing Pull Requests to `main`, improving how incremental changes are handled.
- Communicated to DevOps any …
> [PM-17939] Restrict test.yml coverage upload to On Push and Pull Request triggers

- scripts/update_app_ci_build_info.sh
PM-10515
https://github.com/bitwarden/android/pull/4456 enhanced the info obtained from the About screen copy, but it was missing build related info. This was due to the `ci.properties` file being created one folder above the repo root folder, because the script is running from the repo root instead of inside the scripts folder.  
- …
> [PM-10515] fix: Missing build information in About screen version copy

- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/appearance/AppearanceScreen.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/appearance/AppearanceScreenTest.kt
[PM-17958](https://bitwarden.atlassian.net/browse/PM-17958)
This PR removes the supporting text from the language selector to match the updated V3 designs.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/b58e28d0-217f-4ca8-8b14-0cd3d957ae56" width="300" /> | <img src="https://github.com/user-attachments/assets/a7fb3bbe-8a0c-44ef-9e57-07ff05c204c6" width="300" /> | …
> PM-17958: Remove language supporting text

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/header/BitwardenExpandingHeader.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditAdditionalOptions.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditCardItems.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditCustomFieldsButton.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditIdentityItems.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditItemContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditLoginItems.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditSecureNotesItems.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditSshKeyItems.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditScreenTest.kt
[PM-17841](https://bitwarden.atlassian.net/browse/PM-17841)
This PR moves all the miscellaneous items into an expandable `Additional options` section in the add/edt cipher UI.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/b508cf4c-ece7-4d96-ae12-f91bde467a02" width="300" /> | <img src="https://github.com/user-attachments/assets/cb9886e0-02d5-4dbc-ba74-6e1335188e24" width="300" /> | …
> PM-17841: Hide additional options behind expandable section

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/stepper/BitwardenStepper.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreen.kt
> QA-1056: Adding testTag to Stepper value text

- app/src/main/java/com/x8bit/bitwarden/MainViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/model/Fido2CredentialAssertionRequest.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/util/Fido2IntentUtils.kt
- app/src/test/java/com/x8bit/bitwarden/data/autofill/fido2/util/Fido2IntentUtilsTest.kt
https://bitwarden.atlassian.net/browse/PM-17694
Update the FIDO2 authentication flow to ignore user verification results when single-tap sign-on is not used. This prevents redundant user verification from being performed if the user unlocked their vault to retrieve matching credentials.
https://github.com/user-attachments/assets/eb1792c9-b1be-449c-a782-a31cc5f42c0f
https://github.com/user-attachments/assets/79ebafc9-2827-42c6-8bd4-c7a179fa4f6a …
> [PM-17694] Only update FIDO2 user verification status during single-tap sign-in

- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/model/LoginResultExtensions.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/BiometricsEncryptionManager.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/BiometricsEncryptionManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/AuthenticatorBridgeRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepository.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/model/VaultUnlockResult.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupUnlockViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityViewModel.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/model/LoginResultExtensionsTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupUnlockViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityViewModelTest.kt
[PM-17968](https://bitwarden.atlassian.net/browse/PM-17968)
[GitHub Issue](https://github.com/bitwarden/android/issues/4683)
This PR updates the `BiometricsEncryptionManager` to migrate secret keys to be unique per user.
Primary Changes:
- We are going to use user scoped secret keys for all new biometrics
- If a user is already setup with a non-user scoped secret key, then we let them use it
- If it fails to decrypt, then we clear their data and they need to re-setup biometrics (with a user scoped key)
Unfortunately, a user who is already in the failure state is not recoverable and they need to re-setup biometrics.
- Used …
> PM-17968: Create unique secret keys per user and handle decoding error

- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/FlagKey.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/FlagKeyTest.kt
https://bitwarden.atlassian.net/browse/PM-17405
The `mutual-tls` flag key is now remotely configured.
- ❌ …
> [PM-17405] Configure `mutual-tls` FlagKey as remotely configured

- .github/workflows/scan.yml
- .github/workflows/test.yml
PM-18193
While troubleshooting why Merge Queue runs were hanging, we concluded we only need scan.yml to run for pull requests. 
The SAST job has been failing occasionally which may have not been properly reported to the merge queue, this change will also serve as a test. Additionally, we're moving the test.yml job restrictions to each individual step, so the report job is marked as Success instead of Skipped, as a test for the merge queue issue.
- Updated any necessary documentation or informed the documentation …
> [PM-18193] Remove scan.yml from Merge Queue status check and update test.yml report job skip

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenPasswordField.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenTextField.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/toolbar/BitwardenCutCopyTextToolbar.kt
[PM-17368](https://bitwarden.atlassian.net/browse/PM-17368)
Fix bug where when a user used cut on a TextField it would clear it.
Update text without the selection and clear selection afterwards
https://github.com/user-attachments/assets/fcea2b94-418f-4237-a600-3668796db345 …
> [PM-17368] After cut, update text and clear selection.

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/environment/EnvironmentViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/base/util/StringExtensions.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/base/util/StringExtensionsTest.kt
[PM-3553](https://bitwarden.atlassian.net/browse/PM-3553)
[PM-3503](https://bitwarden.atlassian.net/browse/PM-3503)
[PM-14936](https://bitwarden.atlassian.net/browse/PM-14936)
[PM-7430](https://bitwarden.atlassian.net/browse/PM-7430)
Relates to https://github.com/bitwarden/server/pull/5387
Relates to #3152
Relates to #4708
Relates to #4308
Move `prefixHttpsIfNecessaryOrNull` to `StringExtensions`.
- 📝 …
> [PM-14936] Move `prefixHttpsIfNecessaryOrNull` to `StringExtensions`

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/segment/BitwardenSegmentedButton.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreen.kt
[PM-18083](https://bitwarden.atlassian.net/browse/PM-18083)
- Fix issue where the segmented buttons were not filling out the full length of the segmented row.
- This is due to the buttons being wrapped in the `CoachMarkHighlights` and confirmed if they are wrapped in any other container it does not respect the `1f` weights applied internally. Instead we are calculating the total width of the row and then splitting it evenly and applying that width to each button.
**BEFORE**
https://github.com/user-attachments/assets/a9bbf879-548e-4a95-b99f-943460aa045b
**AFTER**
https://github.com/user-attachments/assets/c3d0b5b4-19bd-4b06-b05f-0c10d7247f6c
- Written new unit and / or integration tests where …
> PM-18083 Ensure segmented buttons on generator fill entire width evenly.

- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/FlagKey.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/components/FeatureFlagListItems.kt
- app/src/main/res/values/strings_non_localized.xml
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/FlagKeyTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-3553
Introduce a new feature flag, `SimpleLoginSelfHostAlias`, to enable the generation of aliases using self-hosted SimpleLogin instances. …
> [PM-3553] Add SimpleLogin self-hosted alias feature flag

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/util/VaultItemListingDataExtensions.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/util/VaultItemListingDataExtensionsTest.kt
https://bitwarden.atlassian.net/browse/PM-17766
- Update empty strings for SSH keys …
> PM-17766 add new strings for ssh keys empty item

- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/model/AuthRequestTypeJson.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/model/KdfTypeJson.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/model/TwoFactorAuthMethod.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/network/serializer/BaseEnumeratedIntSerializer.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/NotificationType.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/OrganizationEventType.kt
- app/src/main/java/com/x8bit/bitwarden/data/tools/generator/repository/model/PasscodeGenerationOptions.kt
- app/src/main/java/com/x8bit/bitwarden/data/tools/generator/repository/model/UsernameGenerationOptions.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/model/CipherRepromptTypeJson.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/model/CipherTypeJson.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/model/FieldTypeJson.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/model/FileUploadType.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/model/LinkedIdTypeJson.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/model/OrganizationStatusType.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/model/OrganizationType.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/model/PolicyTypeJson.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/model/SecureNoteTypeJson.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/model/SendTypeJson.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/model/UriMatchTypeJson.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/network/serializer/BaseEnumeratedIntSerializerTest.kt
N/A
This PR update failure logging for the `BaseEnumeratedIntSerializer` to indicate the enum it was trying to parse.
This will give us more context about the specific enum being decoded instead of errors like this:
```
Caused by java.lang.IllegalArgumentException: Unknown value 60
```
- 🤔 …
> Improve the error messaging when an enum is not parsed correctly

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenTextField.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemLoginContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/handlers/VaultLoginItemTypeHandlers.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModelTest.kt
[PM-18275](https://bitwarden.atlassian.net/browse/PM-18275)
This PR adds the totp tooltip that links out to the integrated authenticator website.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/8bbc7223-c3d7-48f1-b782-c0b75eb283ae" width="300" /> | <img src="https://github.com/user-attachments/assets/acac4083-6a1d-41a5-93fd-43b699a617ed" width="300" /> |
- 📝 …
> PM-18275: Add totp tooltip on view item screen

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-17882
Fix bug:
When the user created a new cipher using the autofill selection, it would clear the special circumstance and immediately close the `VaultItemListingScreen`, showing the vault instead. 
Added condition to not clear the special circumstance on cipher create if it is a `AutofillSelectionData`.
https://github.com/user-attachments/assets/878a10d5-1a83-4d3e-83c0-42e05c41f678 …
> [PM-17882] Cannot select autofill after creating new login

- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/FlagKey.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/FeatureFlagManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/FlagKeyTest.kt
https://bitwarden.atlassian.net/browse/PM-18281
Change cipher key encryption flag default value to false
- …
> [PM-18281] Change cipher key encryption flag default value to false

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditItemContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt
[PM-18410](https://bitwarden.atlassian.net/browse/PM-18410)
This PR removes the cipher type selector from from the add item UI. …
> PM-18410: Remove cipher type dropdown from add item screen

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenTextField.kt
[PM-18370](https://bitwarden.atlassian.net/browse/PM-18275)
This PR updates the space between the label and the tooltip to be consistent with the latest designs.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/fa48d367-8250-43c8-80c4-8e051e49c2f2" width="300" /> | <img src="https://github.com/user-attachments/assets/2a4501d6-09a6-4252-9394-6696adf643b6" width="300" /> | …
> PM-18370: Update space between label and tooltip

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/bottomsheet/BitwardenModalBottomSheet.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/button/BitwardenTextSelectionButton.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dropdown/BitwardenMultiSelectButton.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditItemContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/handlers/VaultAddEditCommonHandlers.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/util/CipherViewExtensions.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/util/CipherViewExtensionsTest.kt
[PM-18032](https://bitwarden.atlassian.net/browse/PM-18032)
- Effects both Add/Edit screens for items that can be added to folders
- Update design of folder selection to use a bottom sheet where the users select the option and then save to confirm selection
- In the bottom sheet allow users to add a new folder by name. 
https://github.com/user-attachments/assets/c736b0f4-305b-4a18-8ffa-234dd17ede34
- 📝 …
> PM-18032 Adding a new folder while adding or editing an item.

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemCardContent.kt
[PM-18292](https://bitwarden.atlassian.net/browse/PM-18292)
- The "Notes" section header needed to actually be swapped with "Additional Options".  
- 🎨 …
> PM-18292 - Swap "Notes" title with "Additional Options"

- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityScreen.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityScreenTest.kt
https://bitwarden.atlassian.net/browse/PM-18454
Hide `Unlock options` section in `AcountSecurity` page when there aren't methods available.
- 🎨 …
> [PM-18545] Hide section when no unlock option are available

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/button/BitwardenTextSelectionButton.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dropdown/BitwardenMultiSelectButton.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityScreen.kt
[PM-18452](https://bitwarden.atlassian.net/browse/PM-18452)
This PR updates the `BitwardenMultiSelectionButton` and `BitwardenTextSelectionButton` to handle the disabled state in a better way.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/9b69bac1-e685-434c-bf85-a1f8f6efcd9c" width="300" /> | <img src="https://github.com/user-attachments/assets/f6ce4eed-badb-4b31-84d8-125616fd0e11" width="300" /> |
- 👍 …
> PM-18452: Update BitwardenMultiSelectionButton

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-15873
Add delay to `PullToRefresh` to remove the spinning wheel icon when there is not internet connection. This is a workaround for a know issue: https://issuetracker.google.com/issues/248274004
Check internet connection on sync click and show dialog instead of performing the sync.
https://github.com/user-attachments/assets/3375d2ee-c9b7-49cd-99be-16781d414080 …
> [PM-15873] Add delay to PTR to remove the spinning wheel

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModelTest.kt
[PM-18121](https://bitwarden.atlassian.net/browse/PM-18121)
This PR updates the cipherType passed to the edit cipher screen from the cipher details screen.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/9be53a49-4ecf-4f73-886b-88920728d140" width="300" /> | <img src="https://github.com/user-attachments/assets/213828cb-dde7-4752-9755-0a5db57e02e9" width="300" /> | …
> PM-18121: Use correct cipher type for edit screen

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/toggle/BitwardenSwitch.kt
[PM-18480](https://bitwarden.atlassian.net/browse/PM-18480)
This PR updates the internal padding of the `BitwardenSwitch` to be 12dp and the height of the internal switch component to be 32dp (normally 48dp). This should keep the size of the switch the same under normal circumstances but increase the size when the text exceeds the size of the internal switch (usually when text is two lines).
| --- | --- |
| <img src="https://github.com/user-attachments/assets/24c06c45-bd87-46fd-b44f-989be517f9bf" width="300" /> | <img src="https://github.com/user-attachments/assets/49875290-a505-4272-b266-a0324c80a783" width="300" /> |
- …
> PM-18480 Update BitwardenSwitch padding

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/x8bit/bitwarden/data/autofill/di/ActivityAutofillModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/di/AutofillModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/manager/AutofillActivityManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/manager/chrome/ChromeThirdPartyAutofillEnabledManager.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/manager/chrome/ChromeThirdPartyAutofillEnabledManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/manager/chrome/ChromeThirdPartyAutofillManager.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/manager/chrome/ChromeThirdPartyAutofillManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/model/chrome/ChromeReleaseChannel.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/model/chrome/ChromeThirdPartyAutoFillData.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/FlagKey.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/components/FeatureFlagListItems.kt
- app/src/main/res/values/strings_non_localized.xml
- app/src/test/java/com/x8bit/bitwarden/data/autofill/manager/AutofillActivityManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/autofill/manager/chrome/ChromeThirdPartyAutofillEnabledManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/FlagKeyTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuViewModelTest.kt
[PM-18314](https://bitwarden.atlassian.net/browse/PM-18314)
[PM-18450](https://bitwarden.atlassian.net/browse/PM-18450)
- Add manager classes to query content provider for chrome autofill information per updated blog post.
- Add feature flag that when enabled will read the values from that manager otherwise will provide default vaults.
- See https://android-developers.googleblog.com/2025/02/chrome-3p-autofill-services-update.html
- 👍 (`:+1:`) …
> PM-18314 & PM-18450 Check for Chrome browser 3rd party autofill.

- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/api/UnauthenticatedIdentityApi.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/model/PrevalidateSsoResponseJson.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/service/IdentityServiceImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/model/PrevalidateSsoResult.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/enterprisesignon/EnterpriseSignOnScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/enterprisesignon/EnterpriseSignOnViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/datasource/network/service/IdentityServiceTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/enterprisesignon/EnterpriseSignOnScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/enterprisesignon/EnterpriseSignOnViewModelTest.kt
[PM-18496](https://bitwarden.atlassian.net/browse/PM-18496)
This PR propagates the the API error from the `prevalidateSso` API to the UI layer.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/29c802a4-bbbc-4348-a820-aa8a57703fa4" width="300" /> | <img src="https://github.com/user-attachments/assets/23e2436b-124f-4775-86a3-7a55f07d1fb7" width="300" /> |
- 📝 …
> PM-18496: Propagate prevalidateSso API error message

- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/service/AccountsServiceImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/service/IdentityServiceImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/network/util/ExceptionExtensions.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/network/util/NetworkErrorCode.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/service/CiphersServiceImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/service/FolderServiceImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/service/SendsServiceImpl.kt
N/A
This PR creates an enum for parsable error codes so we can more easily interpret what each code means and remove magic number suppressions.
No changes in functionality were made in this PR.
issue and …
> Add NetworkErrorCode enum to make error parsing more readable

- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/model/GetTokenResponseJson.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/datasource/network/service/IdentityServiceTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
N/A
This PR simplifies the error response models by using the `JsonNames` annotation instead of creating a separate model with different keys.
- 🎨 …
> Simplify error response models

- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/SendViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/send/SendViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-15873
Cherrypick from `main` of remaining PTR fixes into `rc` branch.
https://github.com/bitwarden/android/pull/4784
https://github.com/bitwarden/android/pull/4778 …
> [PM-15873] Cherrypick: PTR remaining changes

- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/FirstTimeActionManagerImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/FirstTimeActionManagerTest.kt
[PM-18636](https://bitwarden.atlassian.net/browse/PM-18636)
This is a cherry pick from this [PR](https://github.com/bitwarden/android/pull/4787) to the release branch
Notes from PR:
- To avoid showing the coach mark cards to users who have been using the app and are familiar we are adding a business rule to avoid showing the card if there is any LOGIN type ciphers in the user's vault.
- 
- Updated any necessary documentation (Confluence, contributing …
> 🍒 PM-18636 Hide coach mark card if any login ciphers exist

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/segment/BitwardenSegmentedButton.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreen.kt
[PM-18388](https://bitwarden.atlassian.net/browse/PM-18388)
- Provide a better experience visually when the options in the generated segmented control wrap to second line by adding a hyphen.
- Adjust some spacing to better match the design. 
- Vertical spacing on buttons determined by font scale.
- Button heights will now fill the row height like in design and button heights will be uniform to match the largest (intrinsic min).
**Font scale x1**
| before | after |
| ![scale_1_before](https://github.com/user-attachments/assets/c28d4898-e548-48f1-885c-75b7abf1668b) | ![scale_1_after](https://github.com/user-attachments/assets/77be5f17-f330-45fe-994f-e5d737f35a44) | 
**Font scale x1.3**
| before | after |
| …
> PM-18388 add hyphens on segmented button labels

- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/PolicyManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/SendEmpty.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/PolicyManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/datasource/network/model/SyncResponseProfileUtil.kt
[PM-18677](https://bitwarden.atlassian.net/browse/PM-18677)
This PR updates the policy manager to allow policies for disabled organizations to still apply.
Also updated a minor margin issue with the policy card.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/e831c08c-41af-4453-9ae4-1a9918a7b6c8" width="300" /> | <img src="https://github.com/user-attachments/assets/c3016d37-a9f4-4486-b551-944d77eccb25" width="300" /> | …
> PM-18677: Policies for disabled organizations apply

- app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/manager/Fido2OriginManagerImpl.kt
https://bitwarden.atlassian.net/browse/PM-17215
Resolves https://github.com/bitwarden/android/issues/4733
Resolves https://github.com/bitwarden/android/issues/4582
Remove `get_login_creds` as only `handle_all_urls` is necessary on `Fido2OriginManagerImpl.filterMatchingAppStatementsOrNull`, relaxing passkey requirements …
> [PM-17215] Remove get_login_creds from Fido2OriginManagerImpl.filterMatchingAppStatementsOrNull

- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/FlagKey.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/FlagKeyTest.kt
[PM-18773](https://bitwarden.atlassian.net/browse/PM-18773)
- Update the string name for the key to match the LD remote configuration. …
> PM-18773 update the keyName for the ChromeAutofill flag

- gradle/libs.versions.toml
N/A
Update testng from 7.10.2 to 7.11.0
<details>
<summary>testng-team/testng (org.testng:testng)</summary>
[Compare Source](https://redirect.github.com/testng-team/testng/compare/7.10.2...7.11.0)
-   Report deadlocks when running in sharedthreadpool by [@&#8203;krmahadevan](https://redirect.github.com/krmahadevan) in [https://github.com/testng-team/testng/pull/3119](https://redirect.github.com/testng-team/testng/pull/3119)
-   Update JCommander to 1.83 by [@&#8203;adessaigne](https://redirect.github.com/adessaigne) in [https://github.com/testng-team/testng/pull/3123](https://redirect.github.com/testng-team/testng/pull/3123)
-   Update Gradle Wrapper from 8.7 to 8.8 by [@&#8203;github-actions](https://redirect.github.com/github-actions) in …
> [deps] Update testng to 7.11.0

- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/FirstTimeActionManagerImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/FirstTimeActionManagerTest.kt
[PM-18681](https://bitwarden.atlassian.net/browse/PM-18681)
- Update logic to determine CTA card visibility based only on the user’s personal vault. Previously, CTA cards were hidden if a user had login ciphers in either their personal or organization vault. With this change, only personal vault login items will prevent the CTA cards from appearing, ensuring that users with access to organization collections still see relevant coach mark tours.
https://github.com/user-attachments/assets/650fd200-ce88-4353-b3c3-5e2cd8c15bf7 …
> PM-18681 - Update Showing Coach Mark Tour Logic To Only Consider User's Personal Vault

- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/NotificationPayload.kt
[PM-17087](https://bitwarden.atlassian.net/browse/PM-17087)
- Support servers which are pushing the notification payload with `camelCase` key names. (ex: `qa-team.sh.bitwarden.pw`).
- Interestingly it does look like the server code is pushing the response using `camelCase` but we have been using `PascalCase` and are not seeing these issues reported on production builds. [NotificationHubPushService](https://github.com/bitwarden/server/blob/main/src/Core/NotificationHub/NotificationHubPushRegistrationService.cs#L50)
- CI …
> PM-17087 update notification payloads to support camelCase JSON keys.

- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendViewModelTest.kt
[PM-10725](https://bitwarden.atlassian.net/browse/PM-10725)
This PR updates the the Create Send flow to always display the Share Sheet regardless of whether the Send was created internally or externally.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/7041f021-200e-4566-a17e-e0c69d4b7aa8" width="300" /> | <video src="https://github.com/user-attachments/assets/5c7ffeed-657f-4c84-8491-980cbb773293" width="300" /> | …
> PM-10725: Always show share sheet after creating send regardless of how it was made

- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/appearance/AppearanceScreen.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/appearance/AppearanceScreenTest.kt
N/A
This PR removes the language change dialog that informs users that they need to restart the app. This is not true, the app does not need to restart. …
> Remove the language change dialog

- app/src/main/java/com/x8bit/bitwarden/data/platform/util/BuildConfigUtils.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/about/AboutViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/about/AboutScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/about/AboutViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/util/BuildConfigTest.kt
[PM-19099](https://bitwarden.atlassian.net/browse/PM-19099)
This PR moves a lot of the BuildConfig data into the `BuildConfigUtils`, this makes it easier to reuse in the future and makes it mockable.
- 🤔 …
> PM-19099: Centralize app metadata

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockScreen.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockScreenTest.kt
[PM-11356](https://bitwarden.atlassian.net/browse/PM-11356)
- When the user account and unlocked status change we trigger the garbage collection which causes the screen to completely compose twice, which causes the focus request on the text field to happen twice which is the cause of the "extra" keyboard showing. 
- Adding a small delay means the first attempt to draw the screen that will ultimately get garbage collected will not show the keyboard as the text field will not autofocus.
https://github.com/user-attachments/assets/0f099687-3232-46e0-98ee-bf5afc6970cc
https://github.com/user-attachments/assets/e109d8f6-d9e9-42ec-9a99-fdcf3f1043e5
- Written new unit and / or integration tests where …
> PM-11356 prevent extra soft-keyboard showing.

- app/src/main/java/com/x8bit/bitwarden/MainActivity.kt
- app/src/main/java/com/x8bit/bitwarden/MainViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/appearance/AppearanceViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/util/LocaleExtensions.kt
- app/src/test/java/com/x8bit/bitwarden/MainViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/appearance/AppearanceViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/util/LocaleExtensionsTest.kt
[PM-18877](https://bitwarden.atlassian.net/browse/PM-18877)
- When a user makes a selection for an app specific language through the device settings (Android 13+), we want to respect that setting and update the internal storage to reflect those changes.
- If the user sets an app specific language from the device settings currently, that selection will not be persisted across app restart as it was not being saved. 
- There was also a case where, if the user had set a language in the app's appearance settings and then made a new selection in the device settings it would not be reflected.
- For devices where App specific language APIs are available we will check the API when the app resumes and if one is selected we will save to the storage to keep in sync. …
> PM-18877 Respect system app specific language selection on Android 13 and up.

- app/src/main/java/com/x8bit/bitwarden/MainActivity.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavScreen.kt
[PM-19199](https://bitwarden.atlassian.net/browse/PM-19199)
This PR moves the debug menu screen up into the top-most level of the app in order to remove it from the state-based navigation graph.
Having an event-driven screen in the state-driven root nav host was various bugs whenever the state changed which would remove the debug menu from the stack. The most obvious issue was visible during rotation.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/90457f49-9199-4611-9df6-68d0bf41a2d4" width="300" /> | <video src="https://github.com/user-attachments/assets/c2fb190f-ca18-4469-8d89-3618f006ca8c" width="300" /> |
- Written new unit and / or integration tests …
> PM-19199: hoist debug menu up to top level of the app

- app/src/main/java/com/x8bit/bitwarden/MainViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockScreen.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockScreenTest.kt
https://bitwarden.atlassian.net/browse/PM-11356
- Missed the delays in the MainViewModel flows which trigger the screen refresh. Adjusting the time to be greater than that and added comment for added context.
- The result of this can be seen on a release build, seems like in debug the timing was not as exact which is why the smaller time slice seemingly worked originally. …
> PM-11356 Adjust autofocus delay to be greater than screen refresh delay.

- app/src/main/java/com/x8bit/bitwarden/data/auth/manager/AuthRequestManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/manager/model/AuthRequestResult.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/manager/model/AuthRequestUpdatesResult.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/manager/model/AuthRequestsResult.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/manager/model/AuthRequestsUpdatesResult.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/error/NoActiveUserException.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/loginapproval/LoginApprovalScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/loginapproval/LoginApprovalViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/pendingrequests/PendingRequestsViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/manager/AuthRequestManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/loginapproval/LoginApprovalViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/pendingrequests/PendingRequestsViewModelTest.kt
[PM-19233](https://bitwarden.atlassian.net/browse/PM-19233)
This PR propagates the errors from the Auth Request flows to the UI. …
> PM-19233: Propagate auth request errors to the UI

- app/src/main/java/com/x8bit/bitwarden/data/vault/manager/CipherManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/model/CreateAttachmentResult.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/model/DeleteAttachmentResult.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/attachments/AttachmentsScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/attachments/AttachmentsViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/manager/CipherManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/attachments/AttachmentsScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/attachments/AttachmentsViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-19234
- Propagate the errors from creating and deleting attachments to the UI. …
> PM-19234 propagates attachment result errors to UI

- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/model/DeleteAccountResponseJson.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/model/DeleteAccountResult.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/deleteaccount/DeleteAccountScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/deleteaccount/DeleteAccountViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/deleteaccountconfirmation/DeleteAccountConfirmationScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/deleteaccountconfirmation/DeleteAccountConfirmationViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/deleteaccount/DeleteAccountViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/deleteaccountconfirmation/DeleteAccountConfirmationViewModelTest.kt
[PM-19239](https://bitwarden.atlassian.net/browse/PM-19239)
This PR propagates the errors for deleting an account to the apps UI. …
> PM-19239: Propagate delete account errors to the UI

- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/model/CreateFolderResult.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/model/DeleteFolderResult.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/model/UpdateFolderResult.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/folders/addedit/FolderAddEditScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/folders/addedit/FolderAddEditViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/folders/addedit/FolderAddEditViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-19241
- Propagate the thrown errors to the UI for folder CRUD results. …
> PM-19241 folder result errors propagated to UI

- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/model/ValidatePasswordResult.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/error/MissingPropertyException.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/resetpassword/ResetPasswordViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/search/SearchViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/exportvault/ExportVaultScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/exportvault/ExportVaultViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/resetPassword/ResetPasswordViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/search/SearchViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/exportvault/ExportVaultViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModelTest.kt
[PM-19245](https://bitwarden.atlassian.net/browse/PM-19245)
This PR propagates the error from the password validation flows to the UI. …
> PM-19245: Propagate error from password validation to UI

- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/model/EmailTokenResult.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/model/KnownDeviceResult.kt
- app/src/test/java/com/x8bit/bitwarden/MainViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/login/LoginViewModelTest.kt
[PM-19283](https://bitwarden.atlassian.net/browse/PM-19283)
This PR propagates the errors from the email token and known device flows.
These errors are notably not displayed in the UI today because we purposely do not display dialogs here but I am still updating these flows for completeness.
- 📝 (`:memo:`) or …
> PM-19283: Propagate error from email token and known device flows

- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/model/NewSsoUserResult.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/model/OrganizationDomainSsoDetailsResult.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/model/PrevalidateSsoResult.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/enterprisesignon/EnterpriseSignOnScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/enterprisesignon/EnterpriseSignOnViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/trusteddevice/TrustedDeviceScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/trusteddevice/TrustedDeviceViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/enterprisesignon/EnterpriseSignOnViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/trusteddevice/TrustedDeviceScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/trusteddevice/TrustedDeviceViewModelTest.kt
[PM-19284](https://bitwarden.atlassian.net/browse/PM-19284)
This PR propagates all the SSO errors up to the UI. …
> PM-19284: Propagate SSO flow errors to the UI

- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/model/LoginResultExtensions.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/AuthenticatorBridgeRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/sdk/VaultSdkSourceImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/sdk/model/InitializeCryptoResult.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/manager/VaultLockManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/model/NoKeyFoundForUserException.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/model/VaultUnlockResult.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/util/VaultUnlockResultExtensions.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/model/LoginResultExtensionsTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/repository/AuthenticatorBridgeRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/datasource/sdk/VaultSdkSourceTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/manager/VaultLockManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-19275
- Propagate throw errors from vault unlock results.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue …
> PM-19275 propagate the errors for the vault unlock error result types

- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/model/RegisterResult.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/completeregistration/CompleteRegistrationScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/completeregistration/CompleteRegistrationViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/createaccount/CreateAccountScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/createaccount/CreateAccountViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/completeregistration/CompleteRegistrationViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/createaccount/CreateAccountViewModelTest.kt
[PM-19294](https://bitwarden.atlassian.net/browse/PM-19294)
This PR propagates the errors from the Register flow to the UI. …
> PM-19294: Propagate the Register errors to the UI

- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/model/LoginResult.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/model/LoginResultExtensions.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/enterprisesignon/EnterpriseSignOnViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/login/LoginScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/login/LoginViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/loginwithdevice/LoginWithDeviceViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/model/LoginResultExtensionsTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/enterprisesignon/EnterpriseSignOnViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/login/LoginViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/loginwithdevice/LoginWithDeviceViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginViewModelTest.kt
[PM-19296](https://bitwarden.atlassian.net/browse/PM-19296)
This PR propagates the login flow errors up to the UI. …
> PM-19296: Propagate login errors to the UI

- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/model/PasswordHintResult.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/model/PasswordStrengthResult.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/model/RemovePasswordResult.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/model/ResetPasswordResult.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/model/SetPasswordResult.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/completeregistration/CompleteRegistrationViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/createaccount/CreateAccountViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/masterpasswordhint/MasterPasswordHintScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/masterpasswordhint/MasterPasswordHintViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/removepassword/RemovePasswordViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/resetpassword/ResetPasswordViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/setpassword/SetPasswordScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/setpassword/SetPasswordViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/exportvault/ExportVaultViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/completeregistration/CompleteRegistrationViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/createaccount/CreateAccountViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/removepassword/RemovePasswordViewModelTest.kt
[PM-19295](https://bitwarden.atlassian.net/browse/PM-19295)
This PR propagates the password errors to the UI. …
> PM-19295: Propagate password errors to the UI

- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/model/RequestOtpResult.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/model/ResendEmailResult.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/model/SendVerificationEmailResult.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/model/UserFingerprintResult.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/model/ValidatePinResult.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/model/VerifiedOrganizationDomainSsoDetailsResult.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/model/VerifyOtpResult.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/startregistration/StartRegistrationScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/startregistration/StartRegistrationViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/deleteaccountconfirmation/DeleteAccountConfirmationViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/exportvault/ExportVaultViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/enterprisesignon/EnterpriseSignOnViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/startregistration/StartRegistrationViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/deleteaccountconfirmation/DeleteAccountConfirmationViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/exportvault/ExportVaultViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
[PM-19314](https://bitwarden.atlassian.net/browse/PM-19314)
This PR propagates the errors from the remaining auth flows to the UI. …
> PM-19314: Propagate remaining auth errors to the UI

- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/ItemListingScreen.kt
- authenticator/src/test/java/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/ItemListingScreenTest.kt
[BWA-119](https://bitwarden.atlassian.net/browse/BWA-119)
- The issue was that the manual entry screen was not being displayed when attempting to add a new code. Instead, a dialog prompted the user to open Settings, but upon dismissing the dialog, they remained on the same tab.
- After discussing with Luke, we determined that the expected behavior should match iOS, which does not display a dialog. Instead, if permissions are not granted, the manual entry screen should be shown directly.  This also follows the flow of the Password Manager android app.
- Fixed typo in `onScanQrCodeClick`
https://github.com/user-attachments/assets/6094c1c8-626f-4140-b270-3ee7e23479ee
https://github.com/user-attachments/assets/142ae99e-ad14-4c4b-b9ef-23758bc03faa
- All …
> BWA-119 - Unable to Access Manual Code Entry After Denying Camera Permissions on

- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/AuthenticatorBridgeRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/manager/VaultLockManager.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/manager/VaultLockManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/landing/LandingViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/login/LoginViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/SendViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/verificationcode/VerificationCodeViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/repository/AuthenticatorBridgeRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/manager/VaultLockManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/landing/LandingViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/login/LoginViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/send/SendViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/verificationcode/VerificationCodeViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-13257
User should not be automatically prompted for biometrics when naviting from vault to lock screen. On all other scenarios user should be automatically prompted. …
> [PM-13257] Checking if user is navigating from vault before showing prompt for biometrics

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/scaffold/BitwardenScaffold.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarScreen.kt
[PM-18862](https://bitwarden.atlassian.net/browse/PM-18862)
This PR updates the IME handling for the `BitwardenScaffold` and `VaultUnlockedNavBarScreen` in order to better accommodate ime when the bottom navigation is present. This realistically only occurs on the generator screen but this fix is generic enough to work everywhere.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/53a3524f-bf50-416e-9263-dc1fe7a036dd" width="300" /> | <video src="https://github.com/user-attachments/assets/6c7625f2-1504-4b51-897d-167d2ad2fa6d" width="300" /> |
- Protected functional changes with optionality (feature …
> PM-18862: Update IME handling for BitwardenScaffold and VaultUnlockedNavBarScreen

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockViewModelTest.kt
[PM-19399](https://bitwarden.atlassian.net/browse/PM-19399)
This PR suppresses the `Share error details` button when the user enters the incorrect password. …
> PM-19399: Do not show 'Share error details' button when user enter incorrect password

- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/platform/feature/settings/SettingsScreen.kt
[BWA-154](https://bitwarden.atlassian.net/browse/BWA-154)
This PR fixes the padding on the privacy policy button.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/dab98a79-f180-40e1-ae13-c950eade1dbf" width="300" /> | <img src="https://github.com/user-attachments/assets/1c52fcf6-8a06-4694-85a9-ba0069c73210" width="300" /> |
- Updated any necessary documentation (Confluence, contributing docs) or informed the …
> BWA-154: Fix privacy policy padding

- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/util/ServiceTypeExtensions.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/generator/util/ServiceTypeExtensionsTest.kt
[PM-19403](https://bitwarden.atlassian.net/browse/PM-19403)
This PR adds error messaging to the username generation to better indicate that you missed a required field.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/ba2c84a8-4360-4a9f-a1f9-41a9e3463ebd" width="300" /> | <video src="https://github.com/user-attachments/assets/4d3a1a86-1540-4987-a057-aef87a480845" width="300" /> | …
> PM-19403: Add better error messages for username generation

- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/PinInputDialog.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupUnlockScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityScreenTest.kt
[PM-8953](https://bitwarden.atlassian.net/browse/PM-8953)
This PR updates the Pin Entry dialog to require 4 digits minimum when creating a new pin.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/bccd915e-1ce5-41be-80a5-5eff1b00da76" width="300" /> | <img src="https://github.com/user-attachments/assets/83dbd2c9-686c-4e5f-a7f6-9f1863aeeeba" width="300" /> | …
> PM-8953: Require 4 digits for pin entry

- app/src/main/java/com/x8bit/bitwarden/data/vault/manager/CipherManagerImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/manager/CipherManagerTest.kt
[PM-19498](https://bitwarden.atlassian.net/browse/PM-19498)
[This is a cherry-pick from main.](https://github.com/bitwarden/android/pull/4920)
This PR updates migration logic to ensure the migration only occurs when the SDK actually generate a key for the cipher. If the SDK feature for generating a key is disabled, the cipher update API seems to fail; this failure does not occur when the key is present. …
> PM-19498: Update cipher migration logic

- app/src/main/java/com/x8bit/bitwarden/MainActivity.kt
[PM-19550](https://bitwarden.atlassian.net/browse/PM-19550)
- Accept default to DEFAULT AppLanguage if no app specific language is set. …
> PM-19550:  Accept app language settings "System default"

- app/src/main/assets/fido2_privileged_community.json
Relates to #4910
Remove `net.quetta.browser` from `fido2_privileged_community.json`. It is added to `fido2_privileged_google.json` in #4910. …
> Update passkey privileged app community list

- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/deleteaccount/DeleteAccountViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/deleteaccount/DeleteAccountViewModelTest.kt
PM-19547
This PR adds a small delay to the success dialog when deleting an account. This is needed because the activity restarts when the account is deleted and causes a small flicker in the UI.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/d23beadb-3d63-441f-917e-778f4fff91f1" width="300" /> | <video src="https://github.com/user-attachments/assets/cbce28b3-9725-408d-93a8-be45a3086e6c" width="300" /> |
- …
> PM-19547: Delay the delete account success dialog to avoid flicker

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/scaffold/BitwardenScaffold.kt
[PM-19466](https://bitwarden.atlassian.net/browse/PM-19466)
This PR adds IME padding to the snackbar to ensure it is always visible.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/f473eb18-db39-4c44-bc72-c2f8595451d0" width="300" /> | <video src="https://github.com/user-attachments/assets/c83b7335-ba83-4d1a-a4df-9592842d7736" width="300" /> |
- Updated any necessary documentation (Confluence, contributing docs) …
> PM-19466: Fix snackbar ime padding

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/toggle/BitwardenSwitch.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditAdditionalOptions.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditCustomField.kt
[PM-19653](https://bitwarden.atlassian.net/browse/PM-19653)
This PR adds support for the `BitwardenSwitch` to display a tooltip, actions, and subtext internally. …
> PM-19653: Add tooltip and subtext tupport for the switch

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/util/VaultDataExtensions.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/vault/util/VaultDataExtensionsTest.kt
[PM-19723](https://bitwarden.atlassian.net/browse/PM-19723)
- Add a check to see if any collection view exists.
- If a collection view exists or the vault items with no folder amount is greater than 100 then group all those items in a "No Folder" folder.
**BEFORE**
https://github.com/user-attachments/assets/c2babfed-0414-468b-8767-467cf8727308
**AFTER**
https://github.com/user-attachments/assets/e7281ad6-36ff-44f5-98d5-a5e01231e325
- Updated any …
> PM-19723 Group "no folder" items when there is a collection present.

- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/model/SendVerificationEmailResponseJson.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/base/util/StringExtensions.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/base/util/StringExtensionsTest.kt
[PM-19404](https://bitwarden.atlassian.net/browse/PM-19404)
This PR updates 2 things in order to improve email validation.
* The logic for validating an email address has been updated to actually check that the string is an email address.
* The error message displayed to the user is checking the validation errors from the API. …
> PM-19404: Improve email validation and validation error parsing

- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/service/AccountsServiceImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/service/IdentityServiceImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/service/CiphersServiceImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/service/FolderServiceImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/service/SendsServiceImpl.kt
- network/build.gradle.kts
- network/src/main/kotlin/com/bitwarden/network/model/BitwardenError.kt
- network/src/main/kotlin/com/bitwarden/network/util/ExceptionExtensions.kt
- network/src/main/kotlin/com/bitwarden/network/util/NetworkErrorCode.kt
PM-19782
Move `BitwardenError`, `NetworkErrorCode` enum, and `ExceptionExtensions` utility functions from the `app` module to the `network` module.
The build configuration for the `network` module was updated with new dependencies for `kotlinx.serialization`. …
> [PM-19782] Migrate network error handling to `network` module

- .github/workflows/scan-ci.yml
- .github/workflows/scan.yml
https://bitwarden.atlassian.net/browse/VULN-226
GitHub Security tab is failing to associate the status os the scan.yml, this change may address that by setting the GitHub merge branch ref and sha instead but we'll need to merge it to confirm.
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general …
> Set SARIF upload branch to the merge commit ref/sha retrieved from GH CLI

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/row/BitwardenPushRow.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/toggle/BitwardenSwitch.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/SettingsNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/SettingsScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/about/AboutNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/about/AboutScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/about/AboutViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/FlightRecorderNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/FlightRecorderScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/FlightRecorderViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/recordedLogs/RecordedLogsNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/recordedLogs/RecordedLogsScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/recordedLogs/RecordedLogsViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlocked/VaultUnlockedNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarScreen.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/about/AboutScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/about/AboutViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/FlightRecorderScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/FlightRecorderViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/recordedlogs/RecordedLogsScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/recordedlogs/RecordedLogsViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarScreenTest.kt
[PM-19591](https://bitwarden.atlassian.net/browse/PM-19591)
This PR adds the basic flight recorder UI to the about screen.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/340ff460-5791-471c-8732-362200d8cd84" width="300" /> | <img src="https://github.com/user-attachments/assets/1a9bea82-c9f4-41ce-b897-cc6980d0a2d4" width="300" /> | …
> PM-19591: Initial flight recorder UI

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/navigation/BitwardenNavigationRail.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/scaffold/BitwardenScaffold.kt
[PM-19812](https://bitwarden.atlassian.net/browse/PM-19812)
This PR addresses a bit of minor design feedback where the screen transitions were looking a bit weird since the animation were occurring on top of the navigation rail.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/000e858f-e9ca-464c-9aa6-b763a2b1b5d5" width="450" /> | <video src="https://github.com/user-attachments/assets/bc508179-4fcc-447f-8b34-6203af14dd0d" width="450" /> |
- Communicated to DevOps …
> PM-19812: Navigation Rail design feedback

- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/EventDiskSource.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/EventDiskSourceImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/network/service/EventService.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/network/service/EventServiceImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/event/OrganizationEventManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/OrganizationEvent.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/disk/EventDiskSourceTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/network/service/EventServiceTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/event/OrganizationEventManagerTest.kt
- network/src/main/kotlin/com/bitwarden/network/api/EventApi.kt
- network/src/main/kotlin/com/bitwarden/network/model/OrganizationEventJson.kt
- network/src/main/kotlin/com/bitwarden/network/model/OrganizationEventType.kt
PM-19841
Move `EventApi`, `OrganizationEventJson`, and `OrganizationEventType` to the `network` module. …
> [PM-19841] Migrate Event API and models to network module

- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/api/UnauthenticatedAuthRequestsApi.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/service/AuthRequestsService.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/service/AuthRequestsServiceImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/service/NewAuthRequestService.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/service/NewAuthRequestServiceImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/manager/AuthRequestManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/manager/util/AuthRequestTypeExtensions.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/datasource/network/service/AuthRequestsServiceTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/datasource/network/service/NewAuthRequestServiceTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/manager/AuthRequestManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/manager/util/AuthRequestTypeExtensionsTest.kt
- network/src/main/kotlin/com/bitwarden/network/api/AuthenticatedAuthRequestsApi.kt
- network/src/main/kotlin/com/bitwarden/network/model/AuthRequestRequestJson.kt
- network/src/main/kotlin/com/bitwarden/network/model/AuthRequestTypeJson.kt
- network/src/main/kotlin/com/bitwarden/network/model/AuthRequestUpdateRequestJson.kt
- network/src/main/kotlin/com/bitwarden/network/model/AuthRequestsResponseJson.kt
PM-19854
Move AuthenticatedAuthRequestsApi and related models to the `network` module. Update imports in `:app` to use the new location. …
> [PM-19854] Migrate AuthenticatedAuthRequestsApi to network module

- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/api/UnauthenticatedKeyConnectorApi.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/service/AccountsServiceImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/datasource/network/service/AccountsServiceTest.kt
- network/src/main/kotlin/com/bitwarden/network/api/AuthenticatedKeyConnectorApi.kt
- network/src/main/kotlin/com/bitwarden/network/model/KeyConnectorMasterKeyRequestJson.kt
PM-19856
The `AuthenticatedKeyConnectorApi` and `KeyConnectorMasterKeyRequestJson` have been moved from the `app` module to the `network` module.
Additionally in `app` module replace old imported classes with new imported ones from `network` module. …
> [PM-19856] Migrate KeyConnectorApi and models to network module

- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/service/NewAuthRequestServiceImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/datasource/network/service/NewAuthRequestServiceTest.kt
- network/src/main/kotlin/com/bitwarden/network/api/UnauthenticatedAuthRequestsApi.kt
PM-19860
Move `AuthRequestTypeJson`, `AuthRequestsResponseJson`, `UnauthenticatedAuthRequestsApi`, and `AuthRequestRequestJson` to the `network` module. …
> [PM-19860] Migrate UnauthenticateAuthRequestsApi and models to `network` module

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/navigation/BitwardenNavigationRail.kt
[PM-19937](https://bitwarden.atlassian.net/browse/PM-19937)
This PR makes the navigation rail scrollable for small devices.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/a6ef7f28-43e4-48e9-8c7b-055b8b4b26a5" width="400" /> | <video src="https://github.com/user-attachments/assets/2129439b-d6a8-4ea8-bbc7-da31fea6f8f5" width="400" /> | …
> PM-19937: Make navigation rail scrollable

- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/di/PlatformManagerModule.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/data/platform/manager/di/PlatformManagerModule.kt
- core/src/main/kotlin/com/bitwarden/core/di/CoreModule.kt
- data/src/test/kotlin/com/bitwarden/data/manager/DispatcherManagerTest.kt
PM-19947
The system `Clock` provider has been moved to the `core` module.
This change removes redundant `Clock` providers from `authenticator` and `app` modules. …
> [PM-19947] Provide system clock in the `core` module

- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/di/PlatformDiskModule.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/data/platform/datasource/disk/di/PlatformDiskModule.kt
- data/src/main/kotlin/com/bitwarden/data/datasource/disk/ConfigDiskSourceImpl.kt
- data/src/main/kotlin/com/bitwarden/data/datasource/disk/di/DiskModule.kt
PM-19949
Make the `ConfigDiskSourceImpl` internal and provide `ConfigDiskSource` from the `data` module. …
> [PM-19949] Provide ConfigDiskSource from `data` module

- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/service/DevicesServiceImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/datasource/network/service/DevicesServiceTest.kt
- network/src/main/kotlin/com/bitwarden/network/api/UnauthenticatedDevicesApi.kt
PM-19861
Move `UnauthenticatedDevicesApi` from the `app` module to the `network` module. Updated its usages in the `app` module. …
> [PM-19861] Migrate UnauthenticatedDevicesApi to network module

- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/service/CiphersServiceImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/service/SendsServiceImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/datasource/network/service/CiphersServiceTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/datasource/network/service/SendsServiceTest.kt
- network/src/main/kotlin/com/bitwarden/network/api/AzureApi.kt
PM-20068
Move `AzureApi` from the `app` module to the `network` module. Removed the duplicate implementation from the `app` module. Updated all usages of `AzureApi` to use the new implementation in `network`. …
> [PM-20068] Migrate AzureApi to `network` module

- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/service/DownloadServiceImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/datasource/network/service/DownloadServiceTest.kt
- network/src/main/kotlin/com/bitwarden/network/api/DownloadApi.kt
PM-20070
Moved `DownloadApi` from the `app` module to the `network` module. Removed the previous implementation from the `app` module and updated its usages to use the new `network` module implementation. …
> [PM-20070] Migrate DownloadApi to `network` module

- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSource.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSourceImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/model/FlightRecorderDataSet.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSourceTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/disk/util/FakeSettingsDiskSource.kt
[PM-20123](https://bitwarden.atlassian.net/browse/PM-20123)
This PR adds persisted metadata for the flight recorder logs to the settings disk source. …
> PM-20123: Add flight recorder metadata

- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/service/FolderService.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/service/FolderServiceImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/util/VaultSdkFolderExtensions.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/datasource/network/service/FoldersServiceTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/repository/util/VaultSdkFolderExtensionsTest.kt
- network/src/main/kotlin/com/bitwarden/network/api/FoldersApi.kt
- network/src/main/kotlin/com/bitwarden/network/model/FolderJsonRequest.kt
PM-20071
Migrated `FoldersApi` and `FolderJsonRequest` from the `app` module to the `network` module. Removed redundant implementations and model from the `app` module. Updated all usages of `FoldersApi` and `FolderJsonRequest` to use the new implementation in `network`. …
> [PM-20071] Migrate FoldersApi to `network` module

- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/service/SendsServiceImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/datasource/network/service/SendsServiceTest.kt
- network/src/main/kotlin/com/bitwarden/network/api/SendsApi.kt
PM-20072
The `SendsApi` interface has been moved from the `app` module to the `network` module. …
> [PM-20072] Migrate SendsApi to `network` module

- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/service/SyncServiceImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/datasource/network/service/SyncServiceTest.kt
- network/src/main/kotlin/com/bitwarden/network/api/SyncApi.kt
PM-20073
Moved `SyncApi` from the `app` module to the `network` module.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit …
> [PM-20073] Migrate SyncApi to the network module

- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/util/WebAuthUtils.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/util/WebAuthUtilsTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginViewModelTest.kt
[PM-20172](https://bitwarden.atlassian.net/browse/PM-20172)
This PR displays the error message from webAuthN responses to the user.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/eb685098-2fb0-4674-b366-c08a99bc9b36" width="300" /> | <img src="https://github.com/user-attachments/assets/e43c0290-4b28-41ec-9a28-97beb63cb7b9" width="300" /> | …
> PM-20172: Display errors from WebAuthN results

- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/di/AuthNetworkModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/manager/KeyConnectorManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/manager/di/AuthManagerModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/di/AuthRepositoryModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/network/authenticator/RefreshAuthenticator.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/network/interceptor/AuthTokenInterceptor.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/network/util/HeaderUtils.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/manager/KeyConnectorManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/data/platform/datasource/network/util/HeaderUtils.kt
- network/src/main/kotlin/com/bitwarden/network/model/DeleteAccountResponseJson.kt
- network/src/main/kotlin/com/bitwarden/network/model/PasswordHintResponseJson.kt
- network/src/main/kotlin/com/bitwarden/network/service/AccountsService.kt
- network/src/main/kotlin/com/bitwarden/network/service/AccountsServiceImpl.kt
- network/src/main/kotlin/com/bitwarden/network/util/HeaderUtils.kt
- network/src/test/kotlin/com/bitwarden/network/service/AccountsServiceTest.kt
PM-20185
Migrated `AccountsService` and related classes to the `network` module. …
> [PM-20185] Migrate AccountService to network module

- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/network/retrofit/RetrofitsImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/util/BuildConfigUtils.kt
[PM-20260](https://bitwarden.atlassian.net/browse/PM-20260)
This PR limits the network logs in production to just the urls being hit and the response codes. …
> Limit network logs in production

- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/model/FlightRecorderDataSet.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/flightrecorder/FlightRecorderManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/util/FileExtensions.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/recordedLogs/RecordedLogsScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/recordedLogs/RecordedLogsViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/recordedLogs/util/FlightRecorderDataSetExtensions.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/util/LongExtensions.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/flightrecorder/FlightRecorderManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/recordedlogs/RecordedLogsScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/recordedlogs/RecordedLogsViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/recordedlogs/util/FlightRecorderDataSetExtensionsTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/util/FlightRecorderDurationTests.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/util/LongExtensionsTest.kt
[PM-19593](https://bitwarden.atlassian.net/browse/PM-19593)
This PR updates the `FlightRecorderManager` to store the expiration date when a log becomes inactive and adds the recorded logs UI.
- 🤔 …
> PM-19593: Display all flight recorder logs

- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/about/AboutViewModelTest.kt
N/A
This is addresses a minor bug in the `AboutViewModelTests` where the test was using the system default timezone. This can cause discrepancies between output of a time based on the timezone of the dev machine and the CI machine. Currently it is not an issue because this class has no tests like that but this will avoid a future headache if someone were to add more featues/tests. …
> Use explicit timezone in tests

- .github/workflows/scan-ci.yml
- .github/workflows/scan.yml
https://bitwarden.atlassian.net/browse/PM-19821
Re-introducing the scan / scan-ci split to fix `main`. 
Reverts bitwarden/android#4969
Reverts bitwarden/android#4958 (just scan.yml) …
> Revert "[PM-19821] Consolidate scan.yml and scan-ci.yml"

- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/FlagKey.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/FlagKeyTest.kt
PM-19740
Update MobileErrorReporting flag configuration
The `MobileErrorReporting` flag is now remotely configured. Updated `FlagKeyTest` accordingly. …
> Make MobileErrorReporting flag remotely configured

- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/di/AuthNetworkModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/manager/AuthRequestManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/manager/di/AuthManagerModule.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/manager/AuthRequestManagerTest.kt
- network/src/main/kotlin/com/bitwarden/network/service/NewAuthRequestService.kt
- network/src/main/kotlin/com/bitwarden/network/service/NewAuthRequestServiceImpl.kt
- network/src/test/kotlin/com/bitwarden/network/service/NewAuthRequestServiceTest.kt
PM-20190
Moved `NewAuthRequestService` and its implementation `NewAuthRequestServiceImpl` to the `network` module. This change removes redundant code from the `app` module, and updates the dependencies in `app` to use the `network` module's implementation.
The `NewAuthRequestServiceTest` was also moved to `network` module. …
> [PM-20190] Migrate `NewAuthRequestService` to `network` module

- app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/di/AuthNetworkModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/di/AuthRepositoryModule.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
- network/src/main/kotlin/com/bitwarden/network/service/OrganizationService.kt
- network/src/main/kotlin/com/bitwarden/network/service/OrganizationServiceImpl.kt
- network/src/test/kotlin/com/bitwarden/network/service/OrganizationServiceTest.kt
PM-20191
Moved `OrganizationService` and `OrganizationServiceImpl` from the `app` module to the `network` module. This centralizes organization-related network operations within the `network` module. Removed the old files from the `app` module. Updated all usages of `OrganizationService` and `OrganizationServiceImpl` to use the new implementation in `network`.
- Updated any necessary documentation (Confluence, contributing docs) or informed the …
> [PM-20191] Migrate OrganizationService to `network` module

- app/src/main/java/com/x8bit/bitwarden/MainViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/manager/Fido2CredentialManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/model/Fido2CreateCredentialRequest.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/model/Fido2CredentialAssertionRequest.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/util/Fido2IntentUtils.kt
- app/src/test/java/com/x8bit/bitwarden/MainViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/autofill/fido2/model/Fido2CredentialAssertionRequestUtil.kt
- app/src/test/java/com/x8bit/bitwarden/data/autofill/fido2/model/Fido2CredentialRequestUtil.kt
- app/src/test/java/com/x8bit/bitwarden/data/autofill/fido2/util/Fido2IntentUtilsTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/util/SpecialCircumstanceExtensionsTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/util/Fido2CredentialRequestExtensionsTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/util/VaultItemListingDataExtensionsTest.kt
PM-20127
Prevent user verification from prompting twice when single-tap passkey processing is enabled.
- Added `isUserPreVerified` property to `Fido2CreateCredentialRequest` and `Fido2CredentialAssertionRequest` to indicate if the user has been verified by the OS biometric prompt.
- Updated `Fido2IntentUtils` to extract the OS biometric prompt result from request data and include it in `isUserPreVerified`.
- Updated `MainViewModel` to set the user's verification status based on `isUserPreVerified` when a new FIDO 2 request is received.
- Updated FIDO2 logic in `VaultItemListingViewModel` and `VaultAddEditViewModel` to support new `Fido2GetCredentialsRequest`.
- Removed some redundant methods from `Fido2CredentialManagerImpl`.
- Added tests for `Fido2GetCredentialsRequest` handling in …
> [PM-20127] Only prompt passkey user verification once

- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/flightrecorder/FlightRecorderManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/manager/FileManager.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/manager/FileManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/manager/model/ZipFileResult.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/recordedLogs/RecordedLogsScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/recordedLogs/RecordedLogsViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/manager/intent/IntentManager.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/manager/intent/IntentManagerImpl.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/flightrecorder/FlightRecorderManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/recordedlogs/RecordedLogsScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/recordedlogs/RecordedLogsViewModelTest.kt
[PM-19622](https://bitwarden.atlassian.net/browse/PM-19622)
This PR adds the ability to share flight recorder logs.
<video src="https://github.com/user-attachments/assets/499b212c-c0dc-4390-9180-73f65169ddc1" width="350" />
- ❓ …
> PM-19622: Add ability to share flight recorder logs

- app/src/main/java/com/x8bit/bitwarden/data/auth/manager/AuthTokenManager.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/manager/AuthTokenManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/auth/manager/di/AuthManagerModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/network/di/PlatformNetworkModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/network/retrofit/RetrofitsImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/manager/AuthTokenManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/network/retrofit/RetrofitsTest.kt
- network/build.gradle.kts
- network/src/main/kotlin/com/bitwarden/network/interceptor/AuthTokenInterceptor.kt
- network/src/main/kotlin/com/bitwarden/network/interceptor/AuthTokenProvider.kt
- network/src/test/kotlin/com/bitwarden/network/interceptor/AuthTokenInterceptorTest.kt
PM-20306
The `AuthTokenInterceptor` has been moved from the `app` module to the `network` module. This change centralizes network-related components and improves code organization.
The changes include:
-   **AuthTokenInterceptor Relocation:** The `AuthTokenInterceptor` class was removed from `app` and added to `network`.
- **AuthTokenProvider** An interface with `getActiveAccessTokenOrNull()` has been created in `network` module.
-   **AuthTokenManager** A new `AuthTokenManager` interface and its implementation `AuthTokenManagerImpl` were created to handle authentication tokens.
-   **Dependency Updates:** The `PlatformNetworkModule` has been updated to use the new `AuthTokenInterceptor` from `network`.
- **Test Update:** Updated tests after changes.
- **FakeInterceptorChain Update:** …
> [PM-20306] Migrate Auth Token Interceptor

- authenticator/src/main/kotlin/com/bitwarden/authenticator/data/platform/datasource/network/util/HeaderUtils.kt
Updated the user-agent header value in the `authenticator` module to include "Bitwarden_Authenticator_Mobile" instead of "Bitwarden_Mobile". …
> Update user-agent header in Authenticator app

- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/recordedLogs/util/FlightRecorderDataSetExtensions.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/recordedlogs/RecordedLogsScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/recordedlogs/util/FlightRecorderDataSetExtensionsTest.kt
[PM-19593](https://bitwarden.atlassian.net/browse/PM-19593)
This PR updates the expiration string to specify the date instead of the number of days for extra clarity.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/4506f728-bfd4-4781-a21d-f0b489c3a89e" width="300" /> | <img src="https://github.com/user-attachments/assets/899c8fbd-b513-4b1a-a0e5-d448c1bb44f3" width="300" /> | …
> PM-19593: Update expiration string to be 'Expires on <date>'

- app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/di/VaultNetworkModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/repository/di/VaultRepositoryModule.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt
- network/src/main/kotlin/com/bitwarden/network/service/SyncService.kt
- network/src/main/kotlin/com/bitwarden/network/service/SyncServiceImpl.kt
- network/src/test/kotlin/com/bitwarden/network/service/SyncServiceTest.kt
PM-20196
Moved `SyncService` and `SyncServiceImpl` from the `app` module to the `network` module. Removed duplicate implementations and interfaces from the `app` module. Updated all usages of `SyncService` to use the new implementation in `network`. Also moved `SyncServiceTest` into the network module.
- 📝 …
> [PM-20196] Migrate SyncService to the network module

- app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/datasource/network/di/Fido2NetworkModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/di/Fido2ProviderModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/manager/Fido2OriginManagerImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/autofill/fido2/manager/Fido2OriginManagerTest.kt
- network/src/main/kotlin/com/bitwarden/network/api/DigitalAssetLinkApi.kt
- network/src/main/kotlin/com/bitwarden/network/model/DigitalAssetLinkResponseJson.kt
- network/src/main/kotlin/com/bitwarden/network/service/DigitalAssetLinkService.kt
- network/src/main/kotlin/com/bitwarden/network/service/DigitalAssetLinkServiceImpl.kt
- network/src/test/kotlin/com/bitwarden/network/service/DigitalAssetLinkServiceTest.kt
PM-20373
Moved the Digital Asset Link API components from the `app` module to the `network` module. This includes:
-   `DigitalAssetLinkApi` interface.
-   `DigitalAssetLinkResponseJson` data model.
-   `DigitalAssetLinkService` interface.
-   `DigitalAssetLinkServiceImpl` implementation.
-   Related unit tests.
Updated all usages to reference the new `network` module location.
Removed the redundant implementations from `app` module.
- Updated any …
> [PM-20373] Migrate Digital Asset Link API to `network` module

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/environment/EnvironmentScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/welcome/WelcomeScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/base/util/EventsEffect.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/snackbar/BitwardenSnackbarHostState.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditScreen.kt
[PM-20375](https://bitwarden.atlassian.net/browse/PM-20375)
This PR updates the way `EventsEffect` works to force users to provide their own scope so that nothing blocks other events.
- 🤔 (`:thinking:`) or …
> PM-20375: Events to use their own scope

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/model/NavigationItem.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/SettingsNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/model/VaultUnlockedNavBarTab.kt
[PM-20422](https://bitwarden.atlassian.net/browse/PM-20422)
This PR updates the way we manage tab navigation to avoid a reload of the page when clicking the same tab multiple times.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/a72ae811-0c4a-4e37-a665-4a0d079b6eca" width="300" /> | <video src="https://github.com/user-attachments/assets/0689e01f-c475-450a-93e7-b9bf125c7f79" width="300" /> |
- Updated any …
> PM-20422: Update tab navigation

- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/recordedLogs/RecordedLogsScreen.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/recordedlogs/RecordedLogsScreenTest.kt
[PM-20385](https://bitwarden.atlassian.net/browse/PM-20385)
This PR ensures that the delete log confirmation dialog is removed after the user clicks "yes". …
> PM-20385: Delete confirmation dialog should dismiss on confirmation

- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/model/FlightRecorderDataSet.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/flightrecorder/FlightRecorderManager.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/flightrecorder/FlightRecorderManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/animation/AnimateNullableContentVisibility.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/fab/BitwardenFloatingActionButton.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/snackbar/BitwardenSnackbar.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/snackbar/BitwardenSnackbarHost.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/snackbar/BitwardenSnackbarHostState.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/SettingsNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultGraphNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/handlers/VaultHandlers.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/util/FlightRecorderDataSetExtensions.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/flightrecorder/FlightRecorderManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/vault/util/FlightRecorderDataSetExtensionsTest.kt
[PM-19594](https://bitwarden.atlassian.net/browse/PM-19594)
This PR adds the flight recorder Snackbar (sorta) to the Vault Screen.
| Dismiss | Go To Settings |
| --- | --- |
| <video src="https://github.com/user-attachments/assets/0f436f00-1f66-45cb-a52d-c75f210f88f6" width="300" /> | <video src="https://github.com/user-attachments/assets/e8d24cd8-089f-4bf1-ba5a-e137588a0fc2" width="300" /> | …
> PM-19594: Add flight recorder banner

- app/src/main/java/com/x8bit/bitwarden/BitwardenApplication.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/di/PlatformManagerModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/NetworkConnection.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/NetworkSignalStrength.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/network/NetworkConnectionManager.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/network/NetworkConnectionManagerImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/network/NetworkConnectionManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/util/FakeNetworkConnectionManager.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/enterprisesignon/EnterpriseSignOnViewModelTest.kt
[PM-20516](https://bitwarden.atlassian.net/browse/PM-20516)
This PR updates the `NetworkConnectionManager` to allow us to better track the internet connection state including extra specific data such at the type of connection.
- ❓ …
> PM-20516: Update NetworkConnectionManager

- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/recordedLogs/RecordedLogsScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/recordedLogs/RecordedLogsViewModel.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/recordedlogs/RecordedLogsScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/recordedlogs/RecordedLogsViewModelTest.kt
[PM-20400](https://bitwarden.atlassian.net/browse/PM-20400)
This PR adds a confirmation Snackbar after deleting flight recorder logs.
| Single Log Deleted | All Logs Deleted |
| --- | --- |
| <img src="https://github.com/user-attachments/assets/5d94963d-7c2d-4402-af82-551ba7c23980" width="300" /> | <img src="https://github.com/user-attachments/assets/aac5344f-9471-4490-85b1-c4ff506eaa73" width="300" /> | …
> PM-20400: Display snackbar confirming log deletion

- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
https://bitwarden.atlassian.net/browse/PM-18942
There was a bug where revoke/restore notification would not update the vault if sync was done recently. In order to fix the problem we need to force sync for this type of notification.
https://github.com/user-attachments/assets/b3ae696d-b3d6-4284-86fd-5b52ae8b1124 …
> [PM-18942] Force sync for revoke/restore notification.

- authenticator/src/main/kotlin/com/bitwarden/authenticator/data/authenticator/datasource/disk/di/AuthenticatorDiskModule.kt
N/A
Updated the `AuthenticatorDatabase` setup to use `fallbackToDestructiveMigration(dropAllTables = true)` instead of the deprecated `fallbackToDestructiveMigration()`. This ensures that all tables are dropped and recreated during a destructive migration. …
> Drop all tables when performing destructive migration in Authenticator

- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/CertificateManager.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/CertificateManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/ImportPrivateKeyResult.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/environment/EnvironmentScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/environment/EnvironmentViewModel.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/network/ssl/CertificateManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/environment/EnvironmentScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/environment/EnvironmentViewModelTest.kt
PM-17686
When a certificate alias already exists, the app now displays a confirmation dialog to allow the user to overwrite the existing certificate. …
> [PM-17686] Allow overwriting TLS certificates

- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/manager/VaultLockManager.kt
- app/src/main/java/com/x8bit/bitwarden/data/vault/manager/VaultLockManagerImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/manager/VaultLockManagerTest.kt
[PM-20552](https://bitwarden.atlassian.net/browse/PM-20966)
This PR Fixes a TDE bug caused by a race condition that occurs when logging in.
When logging in with TDE and trusting the device, 3 distinct flags will be set that can cause the `userState` to emit and the `RootNavScreen` to change it's target destination:
* `shouldTrustDevice`
* `isTdeLoginComplete`
* `isVaultUnlocked`
We want these 3 properties to all update together as a single transaction in order to ensure the app does not navigate prematurely. This premature navigation can cause the user to be logged-out or cancel the trusted device process. To fix this, I am ensuring that the userState does not emit while the active user is unlocking their vault and as soon as the entire process is complete, it updates at that time. The …
> PM-20552: Ensure userState does not emit while the active user is unlocking

- app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/di/Fido2ProviderModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/manager/Fido2CredentialManager.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/manager/Fido2CredentialManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/processor/Fido2ProviderProcessorImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/util/Fido2IntentUtils.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/autofill/fido2/manager/Fido2CompletionManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/ui/autofill/fido2/manager/model/GetFido2CredentialsResult.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/composition/LocalManagerProvider.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/manager/intent/IntentManager.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/manager/intent/IntentManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/data/autofill/fido2/manager/Fido2CredentialManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/autofill/fido2/processor/Fido2ProviderProcessorTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/autofill/fido2/util/Fido2IntentUtilsTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/datasource/sdk/model/CipherViewUtil.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/autofill/fido2/manager/Fido2CompletionManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
Resolves PM-20176
Resolves PM-20127
Move the responsibility of building credential entries from `Fido2ProviderProcessor` to `Fido2CredentialManager`. This change centralizes the credential handling and simplifies the code in `Fido2ProviderProcessor` by delegating this task.
Key changes:
- **Fido2CredentialManager:**
- Implemented `getCredentialEntries()` to handle the retrieval and creation of `CredentialEntry` objects.
- Now uses the `VaultRepository` to fetch and decrypt credential data.
- Uses `EnvironmentRepository` to get base icon url.
- Now uses Glide for network image loading (currently disabled).
- Includes logic to handle biometric prompts.
- **Fido2ProviderProcessor:**
- Removed the logic for building `CredentialEntry`.
- Now relies on `Fido2CredentialManager` to provide the …
> [PM-20508] Centralize passkey credential entry creation

- app/src/main/java/com/x8bit/bitwarden/data/platform/util/StringExtensions.kt
- app/src/test/java/com/x8bit/bitwarden/data/util/StringExtensionsTest.kt
PM-14846
PM-20513
Relates to #5084 
Correct parsing of IP addresses with and without scheme and port. `URI` cannot parse an IP address with a port when it does not also include the scheme (http, https), so autofill matching triggered from the Quick Tile was not working properly.
-   **New Function:** Added `isIpAddress()` to check if a string is a valid IPv4 address, optionally with a port and scheme.
-   **Regex Update:** Added the `IP_ADDRESS_WITH_OPTIONAL_PORT` regex. It validates IPv4 addresses with or without ports (0-65535 range), with an optional `http://` or `https://` prefix.
-   **URI Parsing:** Modified `toUriOrNull()` to handle IP addresses without schemes by adding a default "https://" scheme before parsing.
- **Tests update**: Added new tests for `isIpAddress` function.
- …
> [PM-14846] Improve IP Address and Port Handling in StringExtensions

- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/FlagKey.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/components/FeatureFlagListItems.kt
- app/src/main/res/values/strings_non_localized.xml
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/FlagKeyTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/repository/DebugMenuRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-20037
Remove the Onboarding Carousel flag, keeping the DebugMenu button to restart the Onboarding Carousel …
> [PM-20037] Remove native-carousel-flow feature flag

- app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/manager/Fido2CredentialManagerImpl.kt
PM-20127
The logic for single tap passkey authentication has been updated to prevent user verification when user is already verified.
https://github.com/user-attachments/assets/ce534184-7752-479b-b53a-ffa07584612b …
> [PM-20127] Prevent double UV prompt during FIDO 2 operations

- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillViewModelTest.kt
- network/src/main/kotlin/com/bitwarden/network/BitwardenServiceClientImpl.kt
- network/src/main/kotlin/com/bitwarden/network/service/ConfigServiceImpl.kt
[PM-21156](https://bitwarden.atlassian.net/browse/PM-21156)
This PR fixes the retrofit instance used by the `ConfigService` to ensure configurations are pulled from the correct environment.
- 🤔 …
> PM-21156: Fix ConfigService retrofit instance

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/x8bit/bitwarden/data/platform/contentprovider/UncaughtErrorLoggingContentProvider.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuViewModel.kt
- app/src/main/res/values/strings_non_localized.xml
- app/src/test/java/com/x8bit/bitwarden/data/util/TestHelpers.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuViewModelTest.kt
[PM-21110](https://bitwarden.atlassian.net/browse/PM-21110)
This PR adds a button to generate a crash from the debug menu. Additionally, it also adds logging for fatal crashes to ensure that the Flight Recorder will capture these events. …
> PM-21110: Add a generate crash button to the debug menu

- app/src/main/java/com/x8bit/bitwarden/ui/platform/base/util/StringExtensions.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/base/util/StringExtensionsTest.kt
[PM-19771](https://bitwarden.atlassian.net/browse/PM-19771)
This PR allows emails to contain a forward slash. …
> PM-19771: Allow forward slashes in emails

- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/loginwithdevice/model/LoginWithDeviceType.kt
[PM-21285](https://bitwarden.atlassian.net/browse/PM-21285)
This PR fixes a crash at app start up dues to an unserializable enum in the navigation graph. …
> PM-21285: Ensure route data is serializable

- app/src/main/java/com/x8bit/bitwarden/ui/platform/base/util/NavGraphBuilderExtensions.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/model/VaultUnlockedNavBarTab.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/util/SavedStateHandleExtensions.kt
- ui/build.gradle.kts
- ui/src/main/java/com/bitwarden/ui/platform/theme/Transition.kt
- ui/src/main/java/com/bitwarden/ui/platform/util/RouteUtil.kt
[PM-21324](https://bitwarden.atlassian.net/browse/PM-21324)
This PR moves the main UI transitions to the common UI module. …
> PM-21324: Move common UI transitions to UI module

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dialog/BitwardenSelectionDialog.kt
N/A
This PR fixes a duplicated launched effect key, it makes no functional change but it is now technically correct. …
> Fix duplicated launched effect key

- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/SendEmpty.kt
[PM-21351](https://bitwarden.atlassian.net/browse/PM-21351)
This PR hides the "new send" button from accessibility when on the empty sends screen to avoid duplicated TalkBack announcements for the same functionality.
- ❓ (`:question:`) …
> PM-21351: Hide new send button from accessibility when on the empty sends screen

- app/src/main/java/com/x8bit/bitwarden/ui/autofill/BitwardenRemoteViews.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/theme/BitwardenTheme.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/theme/color/ColorScheme.kt
- ui/src/main/java/com/bitwarden/ui/platform/theme/color/BitwardenColorScheme.kt
PM-21365
Move the `BitwardenColorScheme` data class from the `app` module to the `ui` module. This change is part of a larger refactor to improve code organization and reusability. …
> [PM-21365] Migrate BitwardenColorScheme to ui module

- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/model/SendItemType.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/viewsend/ViewSendNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/viewsend/ViewSendScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/viewsend/ViewSendViewModel.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/send/viewsend/ViewSendScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/send/viewsend/ViewSendViewModelTest.kt
[PM-21397](https://bitwarden.atlassian.net/browse/PM-21397)
This PR creates the basic UI scaffold for the new View Send screen. Notably, none of this UI is currently accessible within the app.
- 🤔 …
> PM-21397: Create initial View Send scaffold

- app/src/main/java/com/x8bit/bitwarden/data/credentials/manager/BitwardenCredentialManager.kt
- app/src/main/java/com/x8bit/bitwarden/data/credentials/manager/BitwardenCredentialManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/credentials/model/GetCredentialsRequest.kt
- app/src/main/java/com/x8bit/bitwarden/data/credentials/processor/CredentialProviderProcessorImpl.kt
- app/src/main/java/com/x8bit/bitwarden/ui/credentials/manager/model/GetCredentialsResult.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/data/credentials/manager/BitwardenCredentialManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/credentials/processor/CredentialProviderProcessorTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/credentials/manager/CredentialProviderCompletionManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
PM-21367
Refactor the logic for retrieving credential entries and improve the handling of multiple credential options. …
> [PM-21367] Support passkey requests with multiple options

- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/SendEmpty.kt
[PM-21351](https://bitwarden.atlassian.net/browse/PM-21351)
This PR clears the semantics on the empty sate new send button ion conjunction with the `hideFromAccessibility()` to ensure it is completely removed. …
> PM-21351: Clear scemantics on new send button

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenPasswordField.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenTextField.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/disk/util/FakeSettingsDiskSource.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/autofill/util/InlinePresentationSpecExtensionsTest.kt
N/A
This PR cleans up a few minor lint warnings and deprecation's where possible. …
> Clean up lint warnings

- app/src/main/java/com/x8bit/bitwarden/ui/platform/theme/BitwardenTheme.kt
- ui/src/main/java/com/bitwarden/ui/platform/components/field/interceptor/NoPersonalizedLearningInterceptor.kt
PM-21572
Move the `NoPersonalizedLearningInterceptor` class from the `app` module to the `ui` module.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue …
> [PM-21572] Migrate NoPersonalizedLearningInterceptor to ui module

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/component/ItemHeader.kt
PM-21585
Closes #5183 
Display an item's folder location in the item header when the item is only assigned to a single folder and not any collections.
A new preview has also been added to demonstrate this change.
| <img width="455" alt="image" src="https://github.com/user-attachments/assets/5241a90b-534f-43b6-a35e-fbe2ec496fb6" /> |<img width="460" alt="image" src="https://github.com/user-attachments/assets/54cd34d1-61f0-493e-8c60-837190b76d04" /> | 
- Communicated …
> [PM-21585] Display item folder location when only in a single folder

- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/search/SearchNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/search/SearchScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/search/SearchViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlocked/VaultUnlockedNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/SendGraphNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/SendNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/SendScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/SendViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/handlers/SendHandlers.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/search/SearchScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/send/SendScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/send/SendViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
[PM-21591](https://bitwarden.atlassian.net/browse/PM-21591)
This PR adds all the routing to navigate to the `ViewSendScreen`. While the routes now exist allowing the `SearchScreen`, `VaultItemListingScreen`, and `SendScreen` to navigate there, none of those screen actually do this yet. That final change will come in a later PR when we are ready to enable this feature.
- Updated any necessary documentation (Confluence, contributing docs) or informed the …
> PM-21591: Add navigation routing for the ViewSendScreen

- app/src/main/java/com/x8bit/bitwarden/data/credentials/builder/CredentialEntryBuilder.kt
- app/src/main/java/com/x8bit/bitwarden/data/credentials/builder/CredentialEntryBuilderImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/credentials/di/CredentialProviderModule.kt
- app/src/main/java/com/x8bit/bitwarden/data/credentials/manager/BitwardenCredentialManager.kt
- app/src/main/java/com/x8bit/bitwarden/data/credentials/manager/BitwardenCredentialManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/credentials/model/GetCredentialsRequest.kt
- app/src/main/java/com/x8bit/bitwarden/data/credentials/model/ProviderGetPasswordCredentialRequest.kt
- app/src/main/java/com/x8bit/bitwarden/data/credentials/processor/CredentialProviderProcessorImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/credentials/util/BiometricPromptDataUtils.kt
- app/src/main/java/com/x8bit/bitwarden/data/credentials/util/PublicKeyCredentialEntryBuilderExtensions.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/data/credentials/builder/CredentialEntryBuilderTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/credentials/manager/BitwardenCredentialManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/credentials/processor/CredentialProviderProcessorTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/vault/datasource/sdk/model/CipherViewUtil.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
PM-21567
Extract logic responsible for building CredentialEntry objects to a dedicated CredentialEntryBuilder class. This reduces the responsibilities of `BitwardenCredentialManager` and improves testability of the process and its components.
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general …
> [PM-21567] Implement `CredentialEntryBuilder` interface

- app/src/main/java/com/x8bit/bitwarden/MainActivity.kt
- app/src/main/java/com/x8bit/bitwarden/MainViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSource.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSourceImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepository.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepositoryImpl.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/toggle/BitwardenSwitch.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/appearance/AppearanceScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/appearance/AppearanceViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/theme/color/ColorScheme.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/x8bit/bitwarden/MainViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSourceTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/disk/util/FakeSettingsDiskSource.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepositoryTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/appearance/AppearanceScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/appearance/AppearanceViewModelTest.kt
PM-10660
PM-20285
Introduce support for dynamic colors in the application.
-   A new setting `isDynamicColorsEnabled` is added to `SettingsDiskSource` and `SettingsRepository` to persist and retrieve the dynamic colors preference.
-   A new flow `isDynamicColorsEnabledFlow` is added to track the changes of `isDynamicColorsEnabled`.
-   A new switch "Dynamic colors" is added in the Appearance Screen.
- The `MainState` is updated with the `isDynamicColorsEnabled` attribute.
- `BitwardenTheme` is updated to set the dynamic color.
- The `AppearanceViewModel` is updated to set the `isDynamicColorsEnabled`.
Coming soon!
- Protected functional …
> [DynamicColors] Add support for dynamic colors

- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/search/SearchContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/search/SearchViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/search/handlers/SearchHandlers.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/search/util/SearchTypeDataExtensions.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/handlers/VaultItemListingHandlers.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/util/VaultItemListingDataExtensions.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/search/SearchScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/search/SearchViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/search/util/SearchUtil.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/util/VaultItemListingDataUtil.kt
[PM-21610](https://bitwarden.atlassian.net/browse/PM-21610)
This PR updates the `SearchScreen` and `VaultItemListingScreen` to better support the sends types. …
> PM-21610: Update SearchScreen and VaultItemListingScreen for better Sends support

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/toggle/BitwardenSwitch.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/theme/color/ColorScheme.kt
PM-10660
PM-20285
Correct the material color token used for BitwardenSwitch's backgroundOff and switch properties.  …
> [DynamicColors] Update toggle button switch dynamic color scheme

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dialog/BitwardenLoadingDialog.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupUnlockScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/enterprisesignon/EnterpriseSignOnScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/loginwithdevice/LoginWithDeviceScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/removepassword/RemovePasswordScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/trusteddevice/TrustedDeviceScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/search/SearchScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/deleteaccount/DeleteAccountScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/deleteaccountconfirmation/DeleteAccountConfirmationScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/exportvault/ExportVaultScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/folders/addedit/FolderAddEditScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/other/OtherScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/send/SendScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/send/viewsend/ViewSendScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/attachments/AttachmentsScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/importlogins/ImportLoginsScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/movetoorganization/VaultMoveToOrganizationScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/verificationcode/VerificationCodeScreenTest.kt
[PM-21634](https://bitwarden.atlassian.net/browse/PM-21634)
This PR updates the `BitwardenLoadingDialog` to be an actual `Dialog` instead of a `PopUp`. It was made as a `PopUp` originally because the `Dialog` could not go edge-to-edge but this issue was resolved in the 1.8.0 version of the material 3 library.
[Original Bug](https://issuetracker.google.com/issues/246909281)
| --- | --- |
| <img src="https://github.com/user-attachments/assets/81dc6682-b775-4237-b136-4dc2be5c127e" width="300" /> | <img src="https://github.com/user-attachments/assets/79112541-3c2f-477b-94e6-d3ff034ad518" width="300" /> |
- Protected …
> PM-21634: Update loading Dialog to be a real dialog

- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlocked/VaultUnlockedNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendViewModelTest.kt
[PM-21631](https://bitwarden.atlassian.net/browse/PM-21631)
This PR updates the `AddSendScreen` to navigate to the Vault Unlocked root after deleting the send. This is to ensure we do not land the user on the `ViewSendScreen` for the send they just deleted.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/c92297b4-8753-4db9-9969-45cb8d84d649" width="300" /> | <video src="https://github.com/user-attachments/assets/41249216-04d1-4b86-8ef2-29ef5a416ca5" width="300" /> |
- CI builds …
> PM-21631: Update Edit Send Screen to navigate to Vault Unlocked root

- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/FlagKey.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/FlagKeyTest.kt
[PM-21641](https://bitwarden.atlassian.net/browse/PM-21641)
This PR allows the `pm-15493-restrict-item-deletion-to-can-manage-permission` flag to be remotely configured. …
> PM-21641: Allow delete and restore logic to be remotely configured

- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/handlers/AddSendHandlers.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/viewsend/ViewSendScreen.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendScreenTest.kt
- app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/send/viewsend/ViewSendScreenTest.kt
[PM-21445](https://bitwarden.atlassian.net/browse/PM-21445)
This PR updates the Send delete buttons in the `ViewSendScreen` and `AddSendScreen`.
* The `ViewSendScreen` is getting a confirmation dialog added.
* The `AddSendScreen` is having the button moved to the bottom of the content instead of the overflow menu.
| Edit | View |
| --- | --- |
| <video src="https://github.com/user-attachments/assets/dc701d08-9638-4598-8e50-13a5e9a7c093" width="300" /> | <video src="https://github.com/user-attachments/assets/817c08fd-708a-4d2a-bacd-f2a7380b0ef9" width="300" /> |
- Used …
> PM-21445: Update the Send delete buttons

- authenticator/src/main/kotlin/com/bitwarden/authenticator/MainActivity.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/auth/unlock/UnlockScreen.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/ItemListingScreen.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/manualcodeentry/ManualCodeEntryScreen.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/platform/composition/LocalManagerProvider.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/platform/feature/settings/SettingsScreen.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/platform/feature/settings/export/ExportScreen.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/platform/feature/settings/importing/ImportingScreen.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/platform/theme/AuthenticatorTheme.kt
PM-21676
Move the `CompositionLocal` providers for various managers (PermissionsManager, IntentManager, ExitManager, BiometricsManager) from `AuthenticatorTheme.kt` to a new dedicated composable `LocalManagerProvider.kt`.
This change improves code organization by centralizing the provision of these managers. Screen composables have been updated to import these local providers from the new `composition` package. …
> [PM-21676] Relocate Authenticator local manager providers

- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
- app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
[PM-21696](https://bitwarden.atlassian.net/browse/PM-21696)
This PR fixes a bug where a user could change their environment in the app by starting to add a new account but if they switch back to the original account before finalizing the new account, the environment was not reverting back to the active users account. …
> PM-21696: Make sure environment is up-to-date

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/coachmark/CoachMarkScopeInstance.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/search/SearchContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/SettingsScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/pendingrequests/PendingRequestsScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/recordedLogs/RecordedLogsScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/folders/FoldersScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/passwordhistory/PasswordHistoryScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/SendContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/components/CollectionItemSelector.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/attachments/AttachmentsContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemCardContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemIdentityContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemLoginContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemSecureNoteContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemSshKeyContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/util/CipherViewExtensions.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultContent.kt
- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/verificationcode/VerificationCodeScreen.kt
- ui/src/main/java/com/bitwarden/ui/platform/base/util/ListExtensions.kt
- ui/src/test/kotlin/com/bitwarden/ui/platform/base/util/ListExtensionsTest.kt
PM-21356
Move UI ListExtension functions from the app module to the ui module. …
> [PM-21356] Migrate ui ListExtensions to `ui` module

- app/src/main/AndroidManifest.xml
[PM-19770](https://bitwarden.atlassian.net/browse/PM-19770)
This PR changes the domains from used to intercept the verify email link from `vault.bitwarden.com` and `vault.bitwarden.eu` to `*.bitwarden.com` and `*.bitwarden.eu` respectively. This expected value and allows the link to navigate users to the Android app.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/bb734f6b-43b4-4aff-84c6-171a56396c81" width="300" /> | <video src="https://github.com/user-attachments/assets/6e43076a-bcda-499f-ae2d-ebc91099a2f3" width="300" /> |
- Used …
> PM-19770: Fix the verify email domains

- app/src/main/java/com/x8bit/bitwarden/data/auth/repository/model/RegisterResult.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/createaccount/CreateAccountNavigation.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/createaccount/CreateAccountScreen.kt
- app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/createaccount/CreateAccountViewModel.kt
- network/src/main/kotlin/com/bitwarden/network/model/RegisterResponseJson.kt
[PM-21707](https://bitwarden.atlassian.net/browse/PM-21707)
This PR updates the `RegisterResponseJson` response to allow for a nullable `captchaBypassToken`. This should have always been the case but it is now necessary since the cloud will be removing the field entirely in the future. …
> PM-21707: Allow nullable captcha token

- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/FeatureFlagManagerImpl.kt
- app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/FlagKey.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/disk/FeatureFlagOverrideDiskSourceTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/FeatureFlagManagerTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/manager/FlagKeyTest.kt
- app/src/test/java/com/x8bit/bitwarden/data/platform/repository/DebugMenuRepositoryTest.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/data/platform/manager/FeatureFlagManagerImpl.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/data/platform/manager/model/FlagKey.kt
- authenticator/src/test/java/com/bitwarden/authenticator/data/platform/datasource/disk/FeatureFlagOverrideDiskSourceTest.kt
- authenticator/src/test/java/com/bitwarden/authenticator/data/platform/manager/FeatureFlagManagerTest.kt
- authenticator/src/test/java/com/bitwarden/authenticator/data/platform/manager/FlagKeyTest.kt
- authenticator/src/test/java/com/bitwarden/authenticator/data/platform/repository/DebugMenuRepositoryTest.kt
[PM-21080](https://bitwarden.atlassian.net/browse/PM-21080)
This PR removes the `isRemotelyConfigured` flag from the app, since we are moving to a version based system for this functionality.
- 🤔 …
> PM-21080: Remove the isRemotelyConfigured flag

- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/account/BitwardenAccountActionItem.kt
- app/src/main/java/com/x8bit/bitwarden/ui/platform/components/account/BitwardenAccountSwitcher.kt
- ui/build.gradle.kts
- ui/src/main/java/com/bitwarden/ui/platform/base/util/ColorExtensions.kt
- ui/src/test/kotlin/com/bitwarden/ui/platform/base/util/ColorExtensionsTest.kt
PM-21354
This commit moves the `ColorExtensions.kt` file and its corresponding test file `ColorExtensionsTest.kt` from the `app` module to the `ui` module. …
> [PM-21354] Migrate ColorExtensions and its tests to ui module 

- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/platform/composition/LocalManagerProvider.kt
- authenticator/src/test/java/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/ItemListingScreenTest.kt
- authenticator/src/test/java/com/bitwarden/authenticator/ui/authenticator/feature/manualcodeentry/ManualCodeEntryScreenTest.kt
- authenticator/src/test/java/com/bitwarden/authenticator/ui/platform/base/AuthenticatorComposeTest.kt
- authenticator/src/test/java/com/bitwarden/authenticator/ui/platform/feature/settings/SettingsScreenTest.kt
N/A
This PR updates the `AuthenticatorComposeTest` to mirror the `BitwardenComposeTest` by allowing the tests to more easily override custom local compositions. …
> Update authenticator compose tests to allow for easier use of local compositions

- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/ItemListingScreen.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/ItemListingViewModel.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/platform/components/card/BitwardenActionCard.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/platform/components/row/BitwardenTextRow.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/platform/feature/settings/SettingsScreen.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/platform/feature/settings/SettingsViewModel.kt
- authenticator/src/main/res/values/strings.xml
- authenticator/src/test/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/ItemListingScreenTest.kt
- authenticator/src/test/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/ItemListingViewModelTest.kt
- authenticator/src/test/kotlin/com/bitwarden/authenticator/ui/platform/feature/settings/SettingsScreenTest.kt
- authenticator/src/test/kotlin/com/bitwarden/authenticator/ui/platform/feature/settings/SettingsViewModelTest.kt
[PM-17660](https://bitwarden.atlassian.net/browse/PM-17660)
This PR updates the action card and `Sync with Authenticator` button in the Authenticator to better inform the user about how Authenticator Sync works.
| Befoire | After |
| --- | --- |
| <img src="https://github.com/user-attachments/assets/1b5df6c6-0129-4a88-bebb-6e4b6ed565ca" width="300" /> | <img src="https://github.com/user-attachments/assets/946d7518-2286-4b36-b9a8-6081610ba260" width="300" /> |
| <img src="https://github.com/user-attachments/assets/c1fb09fe-2854-458e-ad54-55b69c65f011" width="300" /> | <img src="https://github.com/user-attachments/assets/94746e32-6e76-4edd-91ac-be0a19d2ce23" width="300" /> |
- Written new unit and / or …
> PM-17660: Add additional context for the sync feature

- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/ItemListingScreen.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/ItemListingViewModel.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/platform/components/card/BitwardenActionCard.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/platform/components/row/BitwardenTextRow.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/platform/feature/settings/SettingsScreen.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/platform/feature/settings/SettingsViewModel.kt
- authenticator/src/main/res/values/strings.xml
- authenticator/src/test/java/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/ItemListingScreenTest.kt
- authenticator/src/test/java/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/ItemListingViewModelTest.kt
- authenticator/src/test/java/com/bitwarden/authenticator/ui/platform/feature/settings/SettingsScreenTest.kt
- authenticator/src/test/java/com/bitwarden/authenticator/ui/platform/feature/settings/SettingsViewModelTest.kt
[PM-17660](https://bitwarden.atlassian.net/browse/PM-17660)
This PR updates the action card and `Sync with Authenticator` button in the Authenticator to better inform the user about how Authenticator Sync works.
Note that the `toAnnotatedString` and `spanStyleOf` extensions were pulled into the common library and do not exist in the Authentoicator yet. Those functions have been directly copied into the `SettingsScreen` for this RC, it it better in main 😄.
| Befoire | After |
| --- | --- |
| <img src="https://github.com/user-attachments/assets/1b5df6c6-0129-4a88-bebb-6e4b6ed565ca" width="300" /> | <img src="https://github.com/user-attachments/assets/946d7518-2286-4b36-b9a8-6081610ba260" width="300" /> |
| <img src="https://github.com/user-attachments/assets/c1fb09fe-2854-458e-ad54-55b69c65f …
> 🍒PM-17660: Sync learn more cherry pick

- app/src/main/kotlin/com/x8bit/bitwarden/data/auth/repository/model/Organization.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/auth/repository/util/SyncResponseJsonExtensions.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModel.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/util/CollectionViewExtensions.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/util/CollectionViewExtensionsTest.kt
- network/src/main/kotlin/com/bitwarden/network/model/SyncResponseJson.kt
- network/src/testFixtures/kotlin/com/bitwarden/network/model/SyncResponseProfileUtil.kt
https://bitwarden.atlassian.net/browse/PM-21577
When organization `Limit item deletion to Members with Manage permission` is off, users with `Can Edit` permission or `Can edit, hide password` permission should be able to see the delete button in the menu.
Soon™
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) …
> [PM-21577] Handle organization limitItemDeletion from sync response.

- app/src/main/kotlin/com/x8bit/bitwarden/data/autofill/accessibility/processor/BitwardenAccessibilityProcessorImpl.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/autofill/accessibility/processor/BitwardenAccessibilityProcessorTest.kt
[PM-16705](https://bitwarden.atlassian.net/browse/PM-16705)
This PR updates the accessibility event node logic to utilize the `RootNode` instead of the source node if the source node is null. This helps us combat issues where the the node is null when the event comes through but we do not receive another event.
This does cause performance to suffer a little bit but a recent change that checks for the accessibility action first mitigates the worst aspects of this performance issue.
- Communicated to DevOps …
> PM-16705: Improve the node validation logic

- app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt
- app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-21537
When RemoveIndividualVault is active, `selectedOwner` is returning data but `selectedOwnerId` is not set. This updated the`selectedOwnerId` to match `selectedOwner` …
> 🍒 [PM-21537] Fix remove individual vault collection selection cherrypick

- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-21537
When RemoveIndividualVault is active, `selectedOwner` is returning data but `selectedOwnerId` is not set. This updated the`selectedOwnerId` to match `selectedOwner` …
> [PM-21537] Fix remove individual vault collection selection

- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/blockautofill/BlockAutoFillScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/folders/FoldersScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/tools/feature/send/SendScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/tools/feature/send/viewsend/ViewSendScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/vault/VaultScreen.kt
- ui/src/main/kotlin/com/bitwarden/ui/platform/components/fab/BitwardenFloatingActionButton.kt
[PM-21916](https://bitwarden.atlassian.net/browse/PM-21916)
This PR moves the `BitwardenFloatingActionButton` to the `ui` module. …
> PM-21916: Move the FAB to the UI module

- app/src/main/kotlin/com/x8bit/bitwarden/ui/tools/feature/send/viewsend/ViewSendScreen.kt
[PM-21135](https://bitwarden.atlassian.net/browse/PM-21135)
This PR updates the field order for the View Send Screen to match the latest designs.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/0f18b5c2-ee0c-431a-bd85-9473ebd73f19" width="300" /> | <img src="https://github.com/user-attachments/assets/68004212-16f2-41bb-9805-de271f50f327" width="300" /> | …
> PM-21135: Fix view send field order

- app/src/main/AndroidManifest.xml
- app/src/main/kotlin/com/x8bit/bitwarden/MainActivity.kt
- app/src/main/res/values/styles.xml
- authenticator/src/main/AndroidManifest.xml
- authenticator/src/main/kotlin/com/bitwarden/authenticator/MainActivity.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/platform/theme/AuthenticatorTheme.kt
- authenticator/src/main/res/values/styles.xml
- ui/src/main/kotlin/com/bitwarden/ui/platform/theme/BitwardenTheme.kt
- ui/src/main/kotlin/com/bitwarden/ui/platform/util/AppThemeExtensions.kt
- ui/src/main/kotlin/com/bitwarden/ui/platform/util/ComponentActivityExtensions.kt
- ui/src/main/kotlin/com/bitwarden/ui/platform/util/ConfigurationExtensions.kt
- ui/src/test/kotlin/com/bitwarden/ui/platform/util/AppThemeExtensionsTest.kt
[PM-15229](https://bitwarden.atlassian.net/browse/PM-15229)
This PR updates the way we handle edge-to-edge in the main activity and theme. This new mechanism follows the patterns seen in the Now-In-Android app, it should be more performant and hopefully help with some system bar issues seen on certain devices (these issues have not been reproduced and I am unsure if this actually solves the issue). …
> PM-15229: Update logic for handling edge-to-edge

- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/vaultunlocked/VaultUnlockedNavigation.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/tools/feature/send/addedit/AddEditSendNavigation.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/tools/feature/send/addedit/AddEditSendScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/tools/feature/send/addedit/AddEditSendViewModel.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/tools/feature/send/addedit/AddEditSendScreenTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/tools/feature/send/addedit/AddEditSendViewModelTest.kt
[PM-21631](https://bitwarden.atlassian.net/browse/PM-21631)
When deleting a Send from the `AddEditSendScreen`, we need to check if the user came from the `SearchScreen` in order to navigate to the correct location. If they came from Search then we should go there, otherwise the Root is the correct destination.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/60e1791f-b79e-4150-a348-a1eb3e34d5f8" width="300" /> | <video src="https://github.com/user-attachments/assets/383967d8-1302-420c-bafe-6117a88ea7e5" width="300" /> |
- Used …
> PM-21631: Check for Search Screen when navigating after deleting a Send

- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/manualcodeentry/ManualCodeEntryScreen.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/manualcodeentry/SaveManualCodeButtons.kt
- authenticator/src/main/res/values/strings.xml
- authenticator/src/test/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/manualcodeentry/ManualCodeEntryScreenTest.kt
[BWA-159](https://bitwarden.atlassian.net/browse/BWA-159)
This PR updates the `ManualCodeEntryScreen` in the Authenticator to allow scrolling, remove deprecated code, and added UI tests.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/608e677b-f5d4-42af-99b7-3a3dca2d66a5" width="300" /> | <video src="https://github.com/user-attachments/assets/b100e89e-bd13-42c5-8951-a331e56ce94f" width="300" /> |
- Updated any …
> BWA-159: Update the ManualCodeEntryScreen to allow scrolling

- app/src/main/kotlin/com/x8bit/bitwarden/ui/tools/feature/send/viewsend/ViewSendScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/tools/feature/send/viewsend/ViewSendViewModel.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/tools/feature/send/viewsend/ViewSendScreenTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/tools/feature/send/viewsend/ViewSendViewModelTest.kt
[PM-22265](https://bitwarden.atlassian.net/browse/PM-22265)
This PR adds a Copy button for the private notes field on the `ViewSendScreen`.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/ce854698-ea8d-4fc2-99a6-903b91c5d2ce" width="300" /> | <img src="https://github.com/user-attachments/assets/85a4800a-8e29-42c6-89b1-e254b86b03db" width="300" /> |
- Updated any necessary documentation (Confluence, contributing …
> PM-22265: Add Copy Notes button to ViewSendScreen

- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModel.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModelTest.kt
[PM-22345](https://bitwarden.atlassian.net/browse/PM-22345)
This PR updates the Flight Recorder banner to not dismiss after clicking on the `Go to settings` button. …
> PM-22345: Flight recorder banner should not dismiss when navigating to settings

- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/verificationcode/VerificationCodeViewModel.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/verificationcode/VerificationCodeScreenTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/verificationcode/VerificationCodeViewModelTest.kt
[PM-10286](https://bitwarden.atlassian.net/browse/PM-10286)
This PR updates the `VerificationCodeViewModel` to verify that the user has a master password before prompting the user for one. If no password exists, we ignore the reprompt behavior. …
> PM-10286: VerificationCodeScreen should not show MP reprompt if there is no master password

- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/components/dialog/BitwardenTimePickerDialog.kt
- app/src/main/res/values/strings.xml
- app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityScreenTest.kt
[PM-22522](https://bitwarden.atlassian.net/browse/PM-22522)
This PR updates the language used on the time picker to match the designs.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/e019d11f-028f-444f-8f0f-820ffce16c32" width="300" /> | <img src="https://github.com/user-attachments/assets/57e28e7f-45bd-4482-8887-bbcbbf90d046" width="300" /> |
- Updated any necessary documentation (Confluence, contributing docs) …
> PM-22522: Update time picker language

- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/components/snackbar/BitwardenSnackbarHostState.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/search/SearchScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/search/SearchViewModel.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/manager/snackbar/SnackbarRelay.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/manager/snackbar/SnackbarRelayManager.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/manager/snackbar/SnackbarRelayManagerImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/tools/feature/send/SendScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/tools/feature/send/SendViewModel.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/tools/feature/send/addedit/AddEditSendScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/tools/feature/send/addedit/AddEditSendViewModel.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/tools/feature/send/viewsend/ViewSendScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/tools/feature/send/viewsend/ViewSendViewModel.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
- app/src/main/res/values/strings.xml
- app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/search/SearchScreenTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/search/SearchViewModelTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/tools/feature/send/SendScreenTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/tools/feature/send/SendViewModelTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/tools/feature/send/addedit/AddEditSendScreenTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/tools/feature/send/addedit/AddEditSendViewModelTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/tools/feature/send/viewsend/ViewSendScreenTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/tools/feature/send/viewsend/ViewSendViewModelTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingScreenTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
[PM-22551](https://bitwarden.atlassian.net/browse/PM-22551)
This PR updates Send Toasts to be Snackbars instead. This includes adding a Snackbar when updating a Send (it's behind the Share Sheet).
| --- | --- |
| <video src="https://github.com/user-attachments/assets/027c78a6-8c8d-4c28-95a0-25cb540d32a7" width="300" /> | <video src="https://github.com/user-attachments/assets/c42c17dd-0ce8-4f80-92c6-6ecd3d69e015" width="300" /> |
- …
> PM-22551: Update toasts to snackbars for Sends

- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/components/content/BitwardenContentBlock.kt
Update the `BitwardenContentBlock` divider to span the entire width unless an icon is present. …
> Update BitwardenContentBlock divider padding logic

- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/itemlisting/model/ListingItemOverflowAction.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/util/CipherViewExtensions.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/search/SearchViewModelTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/search/util/SearchUtil.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/itemlisting/util/VaultItemListingDataUtil.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/util/CipherViewExtensionsTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModelTest.kt
[PM-22642](https://bitwarden.atlassian.net/browse/PM-22642)
[PM-22644](https://bitwarden.atlassian.net/browse/PM-22644)
This PR adds the master password re-prompt to the `Copy totp` and `Copy note` overflow options.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/e03d10dd-1359-4710-aca7-f959c9204d62" width="300" /> | <video src="https://github.com/user-attachments/assets/6d0599c6-ad17-4fe6-b148-25d0e78a01eb" width="300" /> | …
> PM-22642, PM-22644: Add MP reprompt for TOTP code and secure note

- data/src/main/kotlin/com/bitwarden/data/manager/BitwardenPackageManager.kt
- data/src/main/kotlin/com/bitwarden/data/manager/BitwardenPackageManagerImpl.kt
- data/src/main/kotlin/com/bitwarden/data/manager/di/DataManagerModule.kt
- data/src/test/kotlin/com/bitwarden/data/manager/BitwardenPackageManagerTest.kt
PM-22665
Introduce a manager for interacting with Android's package manager. …
> [PM-22665] Add BitwardenPackageManager abstraction

- app/src/main/kotlin/com/x8bit/bitwarden/data/credentials/di/CredentialProviderModule.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/credentials/manager/OriginManager.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/credentials/manager/OriginManagerImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/credentials/parser/RelyingPartyParser.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/credentials/parser/RelyingPartyParserImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/credentials/manager/OriginManagerTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/credentials/parser/RelyingPartyParserTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
- network/src/main/kotlin/com/bitwarden/network/api/DigitalAssetLinkApi.kt
- network/src/main/kotlin/com/bitwarden/network/service/DigitalAssetLinkService.kt
- network/src/main/kotlin/com/bitwarden/network/service/DigitalAssetLinkServiceImpl.kt
- network/src/test/kotlin/com/bitwarden/network/service/DigitalAssetLinkServiceTest.kt
PM-22441
Closes #5321
Closes #5322
The `DigitalAssetLinkService` and its implementation now take a `sourceWebSite` parameter instead of relying on the target application's package name and certificate fingerprint for the source. This aligns better with how Digital Asset Links work, where the website declares trust in the app.
The `OriginManager` now passes the `relyingPartyId` (which is the source website) to the `DigitalAssetLinkService`.
A `RelyingPartyParser` interface and its implementation `RelyingPartyParserImpl` have been introduced to centralize the logic for parsing relying party IDs from various Credential Manager request objects.
- Written new unit and / or integration tests where …
> [PM-22441] Refactor DigitalAssetLinkService to use source website

- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/verificationcode/VerificationCodeViewModel.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/verificationcode/VerificationCodeViewModelTest.kt
[PM-22643](https://bitwarden.atlassian.net/browse/PM-22643)
This PR ensures that the error dialogs are not cleared when new TOTP data arrives.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/23f3b412-4845-4272-9950-248a0f68da9b" width="300" /> | <video src="https://github.com/user-attachments/assets/f52688bc-e8bf-48d4-9081-773b7072be65" width="300" /> | …
> PM-22643: Do not clear error dialogs when updating TOTP data

- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/manager/CipherManagerImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/repository/model/CreateCipherResult.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/vault/manager/CipherManagerTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt
- network/src/main/kotlin/com/bitwarden/network/model/CreateCipherResponseJson.kt
- network/src/main/kotlin/com/bitwarden/network/service/CiphersService.kt
- network/src/main/kotlin/com/bitwarden/network/service/CiphersServiceImpl.kt
- network/src/test/kotlin/com/bitwarden/network/service/CiphersServiceTest.kt
PM-21782
This commit introduces a new `CreateCipherResponseJson` sealed class to better handle responses from the create cipher API endpoint. This allows for more specific error messages to be displayed to the user when a cipher creation fails due to invalid data.
The `CreateCipherResult.Error` class has been updated to include an optional `errorMessage` string, which can be directly displayed in the UI.
The `CipherManagerImpl` and `VaultAddEditViewModel` have been updated to utilize this new error handling, providing more informative feedback to the user.
- Used …
> [PM-21782] Improve create cipher error handling

- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingScreen.kt
- app/src/main/res/values/strings.xml
PM-19108
The dialog title for the trust privileged add prompt is changed from "An error has occurred" to "Unrecognized browser".
The message for the passkey operation failure due to an untrusted browser is updated to state that the browser is "not recognized" instead of "not trusted", and specifies that trusting will add it to the list of "locally trusted applications".
A new string resource "unrecognized_browser" is added. …
> [PM-19108] Update passkey prompt for unrecognized browser

- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/vault/VaultScreen.kt
- ui/src/main/kotlin/com/bitwarden/ui/platform/components/animation/AnimateNullableContentVisibility.kt
PM-22777
The composable `AnimateNullableContentVisibility` was moved from the `app` module to the `ui` module.
Package and import statements were updated to reflect this change. …
> [PM-22777] Migrate AnimateNullableContentVisibility to ui module

- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/addedit/util/CipherViewExtensions.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/item/util/CipherViewExtensions.kt
- app/src/main/res/values/strings.xml
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/addedit/util/CipherViewExtensionsTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemScreenTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/item/util/VaultItemTestUtil.kt
[PM-22835](https://bitwarden.atlassian.net/browse/PM-22835)
This PR updates the passkey creation date format style.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/ada52515-8954-4e46-aa2a-b8e0c928a11a" width="300" /> | <img src="https://github.com/user-attachments/assets/c04b1066-89ec-41e7-9075-7a3881daa57e" width="300" /> |
| <img src="https://github.com/user-attachments/assets/5acde551-f468-4796-83ab-94f2c534190a" width="300" /> | <img src="https://github.com/user-attachments/assets/540afdb5-d184-4953-9657-5124a7009ada" width="300" /> |
- Protected functional changes with optionality (feature …
> PM-22835: Update the passkey creation date format style

- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/components/dialog/BitwardenMasterPasswordDialog.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/components/field/BitwardenTextField.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/PinInputDialog.kt
[PM-22875](https://bitwarden.atlassian.net/browse/PM-22875)
This PR updates the `BitwardenMasterPasswordDialog` and `PinInputDialog` to submit their values when the `Done` button on the keyboard is clicked.
Note: this still honors the minimum 4 character rule for pins. …
> PM-22875: Done button on keyboard should submit pin or password from dialog

- app/src/main/AndroidManifest.xml
- app/src/main/kotlin/com/x8bit/bitwarden/data/autofill/manager/AutofillActivityManagerImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/autofill/manager/browser/BrowserThirdPartyAutofillEnabledManagerImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/autofill/manager/browser/BrowserThirdPartyAutofillManager.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/autofill/manager/browser/BrowserThirdPartyAutofillManagerImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/autofill/model/browser/BrowserPackage.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/autofill/model/browser/BrowserThirdPartyAutoFillData.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillViewModel.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/browser/BrowserAutofillSettingsCard.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/browser/model/BrowserAutofillSettingsOption.kt
- app/src/main/res/values/strings.xml
- app/src/test/kotlin/com/x8bit/bitwarden/data/autofill/manager/AutofillActivityManagerTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/autofill/manager/browser/BrowserThirdPartyAutofillEnabledManagerTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillScreenTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillViewModelTest.kt
N/A
This PR adds support for Brave as a browser that requires opt-in for 3rd part Autofill support.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/e2e09df2-b17e-45d0-bed2-093a35c709b7" width="300" /> | <img src="https://github.com/user-attachments/assets/a1b7be97-6ee1-4fb6-ac0e-e716bbca6c3f" width="300" /> |
- …
> Add Brave integration toggle

- app/src/main/kotlin/com/x8bit/bitwarden/ui/tools/feature/send/SendListItem.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/tools/feature/send/util/SendViewExtensions.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/util/CipherViewExtensions.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/search/util/SearchUtil.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/tools/feature/send/util/SendViewExtensionsTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingScreenTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/itemlisting/util/VaultItemListingDataUtil.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/util/CipherViewExtensionsTest.kt
[PM-22213](https://bitwarden.atlassian.net/browse/PM-22213)
This PR rearranges the options in the Cipher and Send overflow menus.
The general order is:
1. Copy/Share
2. View
3. Edit
4. Destructive
| --- | --- |
| <img src="https://github.com/user-attachments/assets/4f7ebf4f-0a59-40a1-8214-04da7adfb9b5" width="300" /> | <img src="https://github.com/user-attachments/assets/14ef112e-1aa6-4816-9d53-f064a50f9440" width="300" /> |
| <img src="https://github.com/user-attachments/assets/c7c8d3f8-cf31-4b2b-be75-787a3239f312" width="300" /> | <img src="https://github.com/user-attachments/assets/6dedda9b-ffce-4320-815f-f14846e6dd38" width="300" /> |
- Written new unit and / or integration …
> PM-22213: Update the order of items in the Send and Cipher overflows

- data/src/main/kotlin/com/bitwarden/data/manager/BitwardenPackageManager.kt
- data/src/main/kotlin/com/bitwarden/data/manager/BitwardenPackageManagerImpl.kt
- data/src/test/kotlin/com/bitwarden/data/manager/BitwardenPackageManagerTest.kt
BWA-162
This commit introduces a new method, `getPackageInstallationSourceOrNull`, to the `BitwardenPackageManager` interface and its implementation, `BitwardenPackageManagerImpl`.
This method allows retrieval of the installation source of a given package. It returns the package name of the installer application or null if the information is unavailable (e.g., system app, app not installed, or installer uninstalled).
Unit tests have been added to verify the functionality of `getPackageInstallationSourceOrNull`.
- CI builds …
> [BWA-162] Add `getPackageInstallationSourceOrNull` to `BitwardenPackageManager`

- app/src/main/res/values/strings.xml
- app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/privilegedapps/about/AboutPrivilegedAppsScreenTest.kt
PM-23121
The string resource `trusted_by_you_learn_more` is updated to capitalize the word "You".
| <img width="377" alt="image" src="https://github.com/user-attachments/assets/455682bd-1ee2-42c8-8385-f8a6632019fd" /> | <img width="365" alt="image" src="https://github.com/user-attachments/assets/de7c312f-be10-4f51-b0b3-00c2abd55495" /> |  …
> [PM-23121] Capitalize "You" in passkey trust string

- app/src/main/kotlin/com/x8bit/bitwarden/MainActivity.kt
- app/src/main/kotlin/com/x8bit/bitwarden/MainViewModel.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSourceImpl.kt
- app/src/test/kotlin/com/x8bit/bitwarden/MainViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-22640
When the screen capture setting was updated it only applied the effect after app restart. This solution updates the flags on MainActivity when the setting is updated …
> [PM-22640] Updating screen capture flag when the setting is changed

- app/src/main/res/values-v30/values.xml
- app/src/main/res/values/styles.xml
- app/src/main/res/values/values.xml
[PM-23136](https://bitwarden.atlassian.net/browse/PM-23136)
This PR fixes a crash on Android 10 caused by using the `always` `windowLayoutInDisplayCutoutMode`. …
> PM-23136: Only apply 'always' display cutout mode on API 30 and up

- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/privilegedapps/about/AboutPrivilegedAppsScreen.kt
PM-23131
The "About privileged apps" screen content is made vertically scrollable.
| Header | After |
| <video src="https://github.com/user-attachments/assets/3bc7ec4f-8bb8-40c3-9006-397398da1ba8" /> | <video src="https://github.com/user-attachments/assets/260e92cf-69ad-42c1-912a-b6b462da38d0" /> |  …
> [PM-23131] Make "About privileged apps" screen scrollable

- app/src/main/res/values/strings.xml
- app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/privilegedapps/about/AboutPrivilegedAppsScreenTest.kt
PM-23132
- Capitalization of "You" in `trusted_by_you_learn_more` is changed to "you".
- The `privileged_apps_description` string is updated to include "applications or" before "web browsers".
| Header | Header |
| <img width="482" alt="image" src="https://github.com/user-attachments/assets/06da1714-e7e9-4f31-9f91-b378546b957a" /> | <img width="489" alt="image" src="https://github.com/user-attachments/assets/eb6e811e-aff6-41b6-b781-3786a9ae62ad" /> | 
- Communicated to DevOps any …
> [PM-23132] Update capitalization and wording in privileged apps strings

- app/src/main/kotlin/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupAutofillScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/auth/feature/completeregistration/CompleteRegistrationScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/auth/feature/createaccount/CreateAccountScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/auth/feature/landing/LandingScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/auth/feature/startregistration/StartRegistrationScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/auth/feature/trusteddevice/TrustedDeviceScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/components/toggle/BitwardenUnlockWithBiometricsSwitch.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/components/toggle/BitwardenUnlockWithPinSwitch.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/debugmenu/components/FeatureFlagListItems.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/about/AboutScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/appearance/AppearanceScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/browser/BrowserAutofillSettingsCard.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/other/OtherScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/tools/feature/send/addedit/AddEditSendContent.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/components/CollectionItemSelector.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditAdditionalOptions.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditCustomField.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/item/component/VaultItemCustomField.kt
- ui/src/main/kotlin/com/bitwarden/ui/platform/components/toggle/BitwardenSwitch.kt
- ui/src/main/kotlin/com/bitwarden/ui/platform/components/toggle/color/BitwardenSwitchColors.kt
[PM-23186](https://bitwarden.atlassian.net/browse/PM-23186)
This PR moves the 'BitwardenSwitch' to the 'ui' module. …
> PM-23186: Move 'BitwardenSwitch' to the 'ui' module

- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/ItemListingScreen.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/search/ItemSearchContent.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/search/ItemSearchViewModel.kt
- authenticator/src/test/kotlin/com/bitwarden/authenticator/data/authenticator/manager/util/VerificationCodeItemUtil.kt
- authenticator/src/test/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/search/ItemSearchViewModelTest.kt
- authenticator/src/test/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/util/VerificationCodeItemExtensionsTest.kt
[PM-19780](https://bitwarden.atlassian.net/browse/PM-19780)
This PR adds headers to the Authenticator search screen indicating where the totp codes came from.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/e9b312d0-3e1b-476a-bb18-e82289b037fc" width="300" /> | <img src="https://github.com/user-attachments/assets/3a2e3dbc-3cfc-4098-a8ae-b03e507b1c90" width="300" /> | …
> PM-19780: Authenticator source headers

- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/attachments/AttachmentsScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/attachments/AttachmentsViewModel.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/attachments/AttachmentsViewModelTest.kt
[PM-23308](https://bitwarden.atlassian.net/browse/PM-23308)
This PR replaces the Toasts in the Attachment screen with Snackbars.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/c6c0f359-9be1-4cf0-bcfd-cdf2490646c4" width="300" /> | <img src="https://github.com/user-attachments/assets/3aa99ac4-eee9-48ed-8b50-789746c70ae9" width="300" /> |
| <img src="https://github.com/user-attachments/assets/a2cb7c0f-9dd9-48e5-b061-0e9a9582948d" width="300" /> | <img src="https://github.com/user-attachments/assets/9059a2f7-a6fc-4f5a-90ff-64884575908b" width="300" /> |
- Protected functional changes with optionality …
> PM-23308: Replace Toasts with Snackbar in AttachmentsScreen

- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/search/SearchViewModel.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/manager/snackbar/SnackbarRelay.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModel.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModel.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModelTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModelTest.kt
[PM-23322](https://bitwarden.atlassian.net/browse/PM-23322)
This PR replaces all the Toasts on the `VaultItemScreen` with a Snackbar.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/013c1b46-d585-4ee4-9248-9ee758f1e639" width="300" /> | <img src="https://github.com/user-attachments/assets/e976aff7-c224-4ea3-884f-eba223691b76" width="300" /> | …
> PM-23322: Replace VaultItemScreen toasts with snackbars

- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/other/OtherScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/other/OtherViewModel.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/other/OtherScreenTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/other/OtherViewModelTest.kt
[PM-23318](https://bitwarden.atlassian.net/browse/PM-23318)
This PR replaces the Toast on the `OtherScreen` with a Snackbar.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/c1ed4b5f-18f5-4c7a-8ee5-671f374fe13d" width="300" /> | <img src="https://github.com/user-attachments/assets/ad4ad15c-ccbf-44c6-8bf0-be41903cd7dc" width="300" /> | …
> PM-23318: Replace OtherScreen toast with snackbar

- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/exportvault/ExportVaultScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/exportvault/ExportVaultViewModel.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/exportvault/ExportVaultScreenTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/exportvault/ExportVaultViewModelTest.kt
[PM-23320](https://bitwarden.atlassian.net/browse/PM-23320)
This PR replaces the `ExportVaultScreen` toasts with Snackbars.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/cbd94627-afe7-47cf-b6f9-468921098068" width="300" /> | <img src="https://github.com/user-attachments/assets/c73c3fcb-c90a-4f73-9db2-5be05568cab6" width="300" /> | …
> PM-23320: Replace Export Vault screen toasts with snackbars

- app/src/main/kotlin/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginViewModel.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginScreenTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginViewModelTest.kt
[PM-23321](https://bitwarden.atlassian.net/browse/PM-23321)
This PR replaces all the Toasts on the `TwoFactorLoginScreen` with a Snackbar.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/71b0895c-f36b-438e-9e92-90d9f79cab93" width="300" /> | <img src="https://github.com/user-attachments/assets/a3c0f434-a01a-4709-8f9b-690b121e65f7" width="300" /> |
- Updated any necessary documentation (Confluence, contributing …
> PM-23321: Replace two-factor screen toasts with snackbars

- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/loginapproval/LoginApprovalViewModel.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/pendingrequests/PendingRequestsScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/pendingrequests/PendingRequestsViewModel.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/manager/snackbar/SnackbarRelay.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/loginapproval/LoginApprovalViewModelTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/pendingrequests/PendingRequestsScreenTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/pendingrequests/PendingRequestsViewModelTest.kt
[PM-23354](https://bitwarden.atlassian.net/browse/PM-23354)
This PR adds replaces the Pending Approval Toasts with Snackbars when possible.
Note that when approving a login via notification, the app closes after approving or denying the request. Because the app is closed, we still use a Toast in this scenario.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/27928a7f-7bc7-4fc4-a026-1d5353842b5d" width="300" /> | <img src="https://github.com/user-attachments/assets/89598fb2-6a9c-4ead-a162-d6be60951787" width="300" /> |
- Used …
> PM-23354: Replace Login Approval toasts with snackbar

- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/manager/snackbar/SnackbarRelay.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModel.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/movetoorganization/VaultMoveToOrganizationScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/movetoorganization/VaultMoveToOrganizationViewModel.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditScreenTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemScreenTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModelTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/movetoorganization/VaultMoveToOrganizationViewModelTest.kt
[PM-23503](https://bitwarden.atlassian.net/browse/PM-23503)
This PR converts the Move to Organization Toasts to the Snackbars. …
> PM-23503: Update Move to Organization toasts to be snackbars

- app/src/main/kotlin/com/x8bit/bitwarden/data/platform/manager/FirstTimeActionManagerImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/platform/manager/SdkClientManagerImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/platform/manager/di/PlatformManagerModule.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/platform/manager/sdk/SdkRepositoryFactory.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/platform/manager/sdk/SdkRepositoryFactoryImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/platform/manager/sdk/repository/SdkCipherRepository.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/platform/repository/AuthenticatorBridgeRepositoryImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/datasource/disk/VaultDiskSource.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/datasource/disk/VaultDiskSourceImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/datasource/disk/dao/CiphersDao.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryImpl.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/platform/manager/FirstTimeActionManagerTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/platform/manager/SdkClientManagerTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/platform/manager/sdk/SdkRepositoryFactoryTests.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/platform/manager/sdk/repository/SdkCipherRepositoryTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/platform/repository/AuthenticatorBridgeRepositoryTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/vault/datasource/disk/VaultDiskSourceTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/vault/datasource/disk/dao/FakeCiphersDao.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt
[PM-14063](https://bitwarden.atlassian.net/browse/PM-14063)
This PR adds the persistence state for the SDK Ciphers Repository. …
> PM-14063: SDK persistance state

- app/src/main/kotlin/com/x8bit/bitwarden/AutofillTotpCopyViewModel.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/manager/CipherManager.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/manager/CipherManagerImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/manager/model/GetCipherResult.kt
- app/src/test/kotlin/com/x8bit/bitwarden/AutofillTotpCopyViewModelTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/vault/manager/CipherManagerTest.kt
PM-23604
This PR adds a `getCipher` helper method for retrieving a cipher by ID. …
> [PM-23604] Add 'getCipher' helper method

- app/schemas/com.x8bit.bitwarden.data.vault.datasource.disk.database.VaultDatabase/7.json
- app/src/main/kotlin/com/x8bit/bitwarden/data/platform/repository/AuthenticatorBridgeRepositoryImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/datasource/disk/VaultDiskSource.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/datasource/disk/VaultDiskSourceImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/datasource/disk/dao/CiphersDao.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/datasource/disk/database/VaultDatabase.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/datasource/disk/entity/CipherEntity.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/platform/repository/AuthenticatorBridgeRepositoryTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/vault/datasource/disk/VaultDiskSourceTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/vault/datasource/disk/dao/FakeCiphersDao.kt
[PM-23667](https://bitwarden.atlassian.net/browse/PM-23667)
This PR adds a database query to specifically fetch login ciphers that contain totps codes. …
> PM-23667: Optimize authenticator sync with totp database query

- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/appearance/AppearanceScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/appearance/AppearanceViewModel.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/appearance/AppearanceScreenTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/appearance/AppearanceViewModelTest.kt
PM-21750
The dynamic colors option in Appearance settings will now only be displayed on devices running Android 12 (API 31) or higher, as this feature is not supported on older versions.
This change includes:
- Updating `AppearanceViewModel` to check the Android build version and set an `isDynamicColorsSupported` flag in the state.
- Conditionally rendering the "Dynamic colors" switch in `AppearanceScreen` based on the `isDynamicColorsSupported` flag.
- Updating tests to reflect this new behavior.
| <img width="365" alt="image" src="https://github.com/user-attachments/assets/c46c5303-f4f1-44d1-aad2-9da5f49145be" /> | <img width="365" alt="image" src="https://github.com/user-attachments/assets/226280dd-379f-49c0-93a6-bc57b21bb2e5" /> | 
- Contributor …
> [PM-21750] Only show dynamic colors option on Android 12+

- app/src/main/kotlin/com/x8bit/bitwarden/data/platform/manager/di/PlatformManagerModule.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/platform/manager/model/FlagKey.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/platform/processor/AuthenticatorBridgeProcessorImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/debugmenu/components/FeatureFlagListItems.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityViewModel.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/platform/manager/FlagKeyTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/platform/processor/AuthenticatorBridgeProcessorTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuViewModelTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityViewModelTest.kt
[PM-23692](https://bitwarden.atlassian.net/browse/PM-23692)
This PR removes the Authenticator Sync feature flag from the Password Manager app. …
> PM-23692: Remove auth sync feature flag from password manager

- authenticator/src/main/kotlin/com/bitwarden/authenticator/data/authenticator/repository/AuthenticatorRepositoryImpl.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/data/authenticator/repository/di/AuthenticatorBridgeModule.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/data/authenticator/repository/di/AuthenticatorRepositoryModule.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/data/platform/manager/model/FlagKey.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/platform/feature/debugmenu/DebugMenuScreen.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/platform/feature/debugmenu/components/FeatureFlagListItems.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/platform/feature/settings/SettingsScreen.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/platform/feature/settings/SettingsViewModel.kt
- authenticator/src/main/res/values/strings.xml
- authenticator/src/main/res/values/strings_non_localized.xml
- authenticator/src/test/kotlin/com/bitwarden/authenticator/data/authenticator/repository/AuthenticatorRepositoryTest.kt
- authenticator/src/test/kotlin/com/bitwarden/authenticator/data/platform/manager/FeatureFlagManagerTest.kt
- authenticator/src/test/kotlin/com/bitwarden/authenticator/data/platform/manager/FlagKeyTest.kt
- authenticator/src/test/kotlin/com/bitwarden/authenticator/data/platform/repository/DebugMenuRepositoryTest.kt
- authenticator/src/test/kotlin/com/bitwarden/authenticator/ui/platform/feature/debugmenu/DebugMenuScreenTest.kt
- authenticator/src/test/kotlin/com/bitwarden/authenticator/ui/platform/feature/debugmenu/DebugMenuViewModelTest.kt
- authenticator/src/test/kotlin/com/bitwarden/authenticator/ui/platform/feature/settings/SettingsViewModelTest.kt
[PM-23693](https://bitwarden.atlassian.net/browse/PM-23693)
This PR removes the Authenticator Sync feature flag from the Authenticator app. …
> PM-23693: Remove Authenticator Sync flag from Authenticator app

- app/src/main/kotlin/com/x8bit/bitwarden/data/platform/repository/AuthenticatorBridgeRepositoryImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/platform/repository/di/PlatformRepositoryModule.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/datasource/sdk/ScopedVaultSdkSource.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/datasource/sdk/ScopedVaultSdkSourceImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/datasource/sdk/di/VaultSdkModule.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/platform/repository/AuthenticatorBridgeRepositoryTest.kt
[PM-23666](https://bitwarden.atlassian.net/browse/PM-23666)
This PR creates a scoped version of the `VaultSdkSource` in order to allow background processes like the Authenticator Sync to unlock and access the vault without interacting with the rest of the app. …
> PM-23666: Construct unique SDK client for Authenticator Sync feature

- app/src/main/kotlin/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginViewModel.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-22399
Previously, the server was configured to send the 2FA email as part of login if email was the user's only 2FA option. This has since changed, and now the app needs to request this email be sent when the view appears. This only applies to 2FA, the device verification code email is still sent by the server.
https://github.com/user-attachments/assets/3d365b8f-9c3a-4058-b624-23cb7e31de07
- Updated any …
> [PM-22399] Send 2FA email when view appears

- app/src/test/kotlin/com/x8bit/bitwarden/data/platform/manager/sdk/repository/SdkCipherRepositoryTest.kt
N/A
The `tearDown` method in `SdkCipherRepositoryTest` was incorrectly calling `mockkStatic` instead of `unmockkStatic` when cleaning up mocks. This commit corrects the method call to ensure proper test teardown. …
> Fix `unmockkStatic` usage in `SdkCipherRepositoryTest`

- app/src/main/kotlin/com/x8bit/bitwarden/ui/tools/feature/send/addedit/AddEditSendViewModel.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/tools/feature/send/addedit/AddEditSendScreenTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/tools/feature/send/addedit/AddEditSendViewModelTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
[PM-23910](https://bitwarden.atlassian.net/browse/PM-23910)
This PR ensures that Files Sends cannot be created without a premium account. …
> PM-23910: Disallow file sends for non-premium users

- app/src/main/kotlin/com/x8bit/bitwarden/MainActivity.kt
[PM-23878](https://bitwarden.atlassian.net/browse/PM-23878)
This PR moves the call to `filterTouchesWhenObscured` to after `super.onCreate()` in order to avoid having the OS add an ActionaBar.
- 🤔 …
> PM-23878: Move filterTouchesWhenObscured to avoid actionbar issues

- ui/src/main/kotlin/com/bitwarden/ui/platform/base/util/StringExtensions.kt
- ui/src/test/kotlin/com/bitwarden/ui/platform/base/util/StringExtensionsTest.kt
PM-23844
Resolves #5535
The email validation regex in `StringExtensions.kt` is updated to allow the asterisk character (*) in the local part of an email address.
The `isValidEmail` function's KDoc is also updated to reflect this change.
https://github.com/user-attachments/assets/7f53c1f5-cd58-4252-b8d9-2bd947ce0dec …
> Allow asterisk in email validation

- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryImpl.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt
[PM-24004](https://bitwarden.atlassian.net/browse/PM-24004)
This PR changes the full sync notification to call `sync(force = false)` instead of `syncIfNecessary()`, this small changes bypasses the 30 minute interval check to ensure we sync if something has changed. …
> PM-24004: Push notification for sync should bypass 30 minute interval

- app/src/main/kotlin/com/x8bit/bitwarden/data/auth/manager/UserLogoutManagerImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityScreen.kt
- app/src/main/res/values/strings.xml
- app/src/test/kotlin/com/x8bit/bitwarden/data/auth/manager/UserLogoutManagerTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupUnlockScreenTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityScreenTest.kt
[PM-19185](https://bitwarden.atlassian.net/browse/PM-19185?focusedCommentId=103980&sourceType=mention)
This PR retains the PIN after a soft logout, allowing the user to re-login with a pin instead of a password. The UI has also had some copy updated in order to explain the functionality better.
- 📝 (`:memo:`) …
> PM-19185: Persist pin after a soft-logout

- ui/build.gradle.kts
N/A
This commit updates the `lint` configuration in the `ui/build.gradle.kts` file to disable the `MissingTranslation` and `ExtraTranslation` checks. …
> Disable MissingTranslation and ExtraTranslation lint checks in UI module

- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/appearance/AppearanceScreen.kt
- app/src/main/res/values/strings.xml
- app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/appearance/AppearanceScreenTest.kt
[PM-24075](https://bitwarden.atlassian.net/browse/PM-24075)
This PR updates the copy used for the Dynamic Colors toggle and confirmation dialog based on latest designs. …
> PM-24075: Update Dynamic colors copy

- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModel.kt
- app/src/main/res/values/strings.xml
[PM-24087](https://bitwarden.atlassian.net/browse/PM-24087)
This PR updates the top app bar title for the SSH keys. …
> PM-24087: Update the add/edit ssh key title

- ui/src/main/kotlin/com/bitwarden/ui/platform/util/ParcelableRouteSerializer.kt
N/A
This PR fixes a crash that only occurs on API 33 (Upside Down Cake).
Using ParcelCompat handles the checks internally and does not use the newer `readParcelable` API until API 34 when this bug was fixed. …
> Fix crash in Android 13

- app/src/main/kotlin/com/x8bit/bitwarden/data/autofill/manager/AutofillTotpManagerImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/datasource/sdk/VaultSdkSource.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/datasource/sdk/VaultSdkSourceImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/repository/VaultRepository.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/search/SearchViewModel.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/itemlisting/model/ListingItemOverflowAction.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/util/CipherListViewExtensions.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModel.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/autofill/manager/AutofillTotpManagerTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/vault/datasource/sdk/VaultSdkSourceTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/vault/manager/TotpCodeManagerTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/search/SearchViewModelTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/search/util/SearchUtil.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/itemlisting/util/VaultItemListingDataUtil.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/util/CipherListViewExtensionsTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModelTest.kt
PM-24204
PM-24206
This commit modifies the TOTP generation logic across the application to utilize `cipherId` instead of the raw `totpCode`. This change enhances security and aligns with best practices by avoiding the direct handling of TOTP codes where possible.
Key changes include:
- Updated `VaultRepository` and `VaultSdkSource` to accept `cipherId` for TOTP generation. The `generateTotp` method in `VaultSdkSource` that accepted a `totp` string has been removed.
- `VaultRepositoryImpl` now retrieves the `CipherListView` using the provided `cipherId` to pass to `VaultSdkSource.generateTotpForCipherListView`.
- ViewModels (`SearchViewModel`, `VaultViewModel`, `VaultItemListingViewModel`) and `AutofillTotpManagerImpl` now pass `cipherId` to `VaultRepository.generateTotp`.
- …
> [PM-24204] Correct TOTP generation to use cipherId instead of totpCode

- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/datasource/sdk/di/VaultSdkModule.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/datasource/sdk/model/Fido2CredentialStoreImpl.kt
PM-24205
Fixes a bug that failed to create a new login cipher for passkey registration. The patch refactors how `Fido2CredentialStoreImpl` save credentials to utilize `VaultSdkSource` for decrypting the `Cipher` before saving it. This change ensures that new ciphers are saved correctly.
Key changes:
- `Fido2CredentialStoreImpl` now depends on `AuthRepository` and `VaultSdkSource`.
- The `saveCredential` method in `Fido2CredentialStoreImpl` now uses `vaultSdkSource.decryptCipher` to decrypt the `EncryptionContext.cipher` before updating or creating the cipher in `VaultRepository`.
- `NoActiveUserException` is thrown if there is no active user when attempting to decrypt.
- The `VaultSdkModule` has been updated to provide the new dependencies to `Fido2CredentialStoreImpl`. …
> [PM-24205] Fix Fido2CredentialStore to save new credentials correctly

- app/src/main/kotlin/com/x8bit/bitwarden/data/autofill/manager/AutofillTotpManagerImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/datasource/sdk/VaultSdkSource.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/datasource/sdk/VaultSdkSourceImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/repository/VaultRepository.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/search/SearchViewModel.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/itemlisting/model/ListingItemOverflowAction.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/util/CipherListViewExtensions.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModel.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/autofill/manager/AutofillTotpManagerTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/vault/datasource/sdk/VaultSdkSourceTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/vault/manager/TotpCodeManagerTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/search/SearchViewModelTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/search/util/SearchUtil.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/itemlisting/util/VaultItemListingDataUtil.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/util/CipherListViewExtensionsTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModelTest.kt
PM-24204
Cherry-pick #5599
This commit modifies the TOTP generation logic across the application to utilize `cipherId` instead of the raw `totpCode`. This change enhances security and aligns with best practices by avoiding the direct handling of TOTP codes where possible.
Key changes include:
- Updated `VaultRepository` and `VaultSdkSource` to accept `cipherId` for TOTP generation. The `generateTotp` method in `VaultSdkSource` that accepted a `totp` string has been removed.
- `VaultRepositoryImpl` now retrieves the `CipherListView` using the provided `cipherId` to pass to `VaultSdkSource.generateTotpForCipherListView`.
- ViewModels (`SearchViewModel`, `VaultViewModel`, `VaultItemListingViewModel`) and `AutofillTotpManagerImpl` now pass `cipherId` to `VaultRepository.generateTotp`.
- …
> 🍒 [PM-24204] Correct TOTP generation to use cipherId instead of totpCode

- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/search/util/SearchTypeDataExtensions.kt
Resolves PM-24206
This commit updates the filtering logic for `SearchTypeData.Vault.VerificationCodes`. Instead of checking `organizationUseTotp`, it now verifies if `login?.totp` is not null to determine if a cipher has a verification code. This makes the check more direct and accurate. …
> [PM-24206] Fix filtered verification code search

- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/search/SearchContent.kt
[PM-24303](https://bitwarden.atlassian.net/browse/PM-24303)
This PR ensures that the MP reprompt is observed during Autofill searches. …
> PM-24303: Master password reprompt fix

- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/search/util/SearchTypeDataExtensions.kt
PM-24206
Cherry-picked from #5619
This commit updates the filtering logic for `SearchTypeData.Vault.VerificationCodes`. Instead of checking `organizationUseTotp`, it now verifies if `login?.totp` is not null to determine if a cipher has a verification code. This makes the check more direct and accurate.
- 📝 …
> 🍒[PM-24206] Fix filtered verification code search 

- app/src/main/kotlin/com/x8bit/bitwarden/data/platform/manager/flightrecorder/FlightRecorderWriterImpl.kt
N/A
This PR adds the device fingerprint to the Flight Recorder. This information is extremely helpful when determining if bugs are tied to a specific Android revision. …
> Add fingerprint to flight recorder

- app/src/main/kotlin/com/x8bit/bitwarden/data/tiles/BitwardenGeneratorTileService.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/tiles/BitwardenVaultTileService.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/manager/intent/IntentManager.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/manager/intent/IntentManagerImpl.kt
N/A
This PR removes the logic for tile intents from the `IntentMnager` to make things just a little simpler. …
> Handle tile intents without IntentManager

- app/src/main/kotlin/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/auth/repository/model/LogoutReason.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
- network/src/main/kotlin/com/bitwarden/network/api/UnauthenticatedIdentityApi.kt
- network/src/main/kotlin/com/bitwarden/network/authenticator/RefreshAuthenticator.kt
- network/src/main/kotlin/com/bitwarden/network/model/RefreshTokenResponseJson.kt
- network/src/main/kotlin/com/bitwarden/network/provider/RefreshTokenProvider.kt
- network/src/main/kotlin/com/bitwarden/network/service/IdentityServiceImpl.kt
- network/src/test/kotlin/com/bitwarden/network/authenticator/RefreshAuthenticatorTests.kt
- network/src/test/kotlin/com/bitwarden/network/service/IdentityServiceTest.kt
[PM-24440](https://bitwarden.atlassian.net/browse/PM-24440)
Add logic to log a user out when an `invalid_grant` is returned from the refresh access token API. …
> PM-24440: Log user out for 'invalid_grant'

- app/src/main/kotlin/com/x8bit/bitwarden/data/credentials/builder/CredentialEntryBuilderImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/credentials/di/CredentialProviderModule.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/credentials/manager/CredentialManagerPendingIntentManager.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/credentials/manager/CredentialManagerPendingIntentManagerImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/credentials/processor/CredentialProviderProcessorImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/credentials/util/CredentialProviderIntentUtils.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/manager/intent/IntentManager.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/manager/intent/IntentManagerImpl.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/credentials/builder/CredentialEntryBuilderTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/credentials/processor/CredentialProviderProcessorTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/credentials/util/CredentialManagerIntentUtilsTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/credentials/manager/CredentialProviderCompletionManagerTest.kt
PM-24411
This commit introduces `CredentialManagerPendingIntentManager` to handle the creation of `PendingIntent`s used by the CredentialManager.
Key changes:
- Created `CredentialManagerPendingIntentManager` interface and its implementation `CredentialManagerPendingIntentManagerImpl`.
- `CredentialProviderProcessorImpl` and `CredentialEntryBuilderImpl` now use `CredentialManagerPendingIntentManager` for creating `PendingIntent`s.
- Removed `PendingIntent` creation methods from `IntentManager` and `IntentManagerImpl`.
- Updated constants for Intent actions and extra keys to reside in `CredentialManagerPendingIntentManager.kt`.
- Adjusted tests in `CredentialProviderProcessorTest`, `CredentialProviderCompletionManagerTest`, `CredentialManagerIntentUtilsTest`, and …
> [PM-24411] Extract pending intent management for Credential Manager requests

- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/composition/LocalManagerProvider.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/manager/di/PlatformUiManagerModule.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/manager/intent/IntentManager.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/manager/intent/IntentManagerImpl.kt
PM-24411
This commit introduces a new `shareErrorReport` function to the `IntentManager` interface. This function is intended to launch the system's share sheet with an error report generated from a provided `Throwable`.
- ❓ …
> [PM-24411] Add shareErrorReport to IntentManager

- app/src/main/kotlin/com/x8bit/bitwarden/data/autofill/builder/FilledDataBuilderImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/autofill/model/AutofillHint.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/autofill/model/AutofillView.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/autofill/util/HtmlInfoExtensions.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/autofill/util/StringExtensions.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/autofill/util/ViewNodeExtensions.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/autofill/util/ViewStructureUtils.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/autofill/builder/FilledDataBuilderTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/autofill/util/HtmlInfoExtensionsTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/autofill/util/ViewNodeExtensionsTest.kt
- ui/src/main/res/values/strings.xml
TBD
This commit refactors the autofill hint detection logic in `ViewNodeExtensions.kt` and introduces support for new autofill hints related to credit card information.
Key changes include:
- Introduced a new `AutofillHint` enum to represent various autofill field types.
- Added regular expressions to detect hints for cardholder name, card number, expiration month, expiration year, expiration date, and security code from HTML attributes.
- Updated `ViewNode.supportedAutofillHint` to use the new `AutofillHint` enum and prioritize explicit hints over inferred ones.
- Modified `ViewNode.isPasswordField` and `ViewNode.isUsernameField` to be properties and utilize the new hint logic.
- Added new `AutofillView.Card` subtypes: `ExpirationDate` and `CardholderName`.
- Updated …
> Refactor Autofill Hint Logic and Add Card Autofill Support

- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/manager/intent/IntentManager.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/manager/intent/IntentManagerImpl.kt
PM-24411
This commit modifies the `createFileChooserIntent` method in `IntentManager` and its implementation `IntentManagerImpl` to accept an optional `mimeType` parameter.
Key changes:
- `IntentManager.createFileChooserIntent` now has a `mimeType` parameter, which defaults to `"*/*"` to allow all file types.
- `IntentManagerImpl.createFileChooserIntent` now uses the provided `mimeType` when creating the `ACTION_OPEN_DOCUMENT` intent.
- KDoc for `createFileChooserIntent` has been updated to reflect the new `mimeType` parameter.
- Used internationalization (i18n) for all UI …
> [PM-24411] Add MIME type parameter to file chooser intent

- .github/workflows/build-authenticator.yml
- .github/workflows/build.yml
- .github/workflows/release-branch.yml
PM-24589
Trigger CI builds when release branches are created or updated. 
Test execution runs:
* Cut Release Branch - https://github.com/bitwarden/android/actions/runs/16828616993
* Build - https://github.com/bitwarden/android/actions/runs/16828621611
* Build Authenticator - https://github.com/bitwarden/android/actions/runs/16828621731
- 👍 (`:+1:`) …
> [PM-24589] Trigger CI builds for release branches

- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/components/dropdown/BitwardenMultiSelectButton.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/components/dropdown/model/MultiSelectOption.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/appearance/AppearanceScreenTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillScreenTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/FlightRecorderScreenTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/other/OtherScreenTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreenTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/movetoorganization/VaultMoveToOrganizationScreenTest.kt
- ui/src/main/kotlin/com/bitwarden/ui/platform/components/button/BitwardenTextSelectionButton.kt
N/A
This PR adds support for headers and Supporting Content in the `BitwardenMultiSelectButton`. …
> Add header and custom supportContent functionality to BitwardenMultiSelectButton

- network/src/main/kotlin/com/bitwarden/network/model/SyncResponseJson.kt
- network/src/test/kotlin/com/bitwarden/network/service/SyncServiceTest.kt
- network/src/testFixtures/kotlin/com/bitwarden/network/model/SyncResponseProfileUtil.kt
PM-24568
Introduce the `accountKeys` field to the `SyncResponseJson.Profile` data class. This new field will hold the user's signature key pair, public key encryption key pair, and security state.
The `privateKey` field has been deprecated in favor of `accountKeys`.
Additionally, new test fixture utilities (`createMockPrivateKeys`, `createMockSecurityState`, `createMockPublicKeyEncryptionKeyPair`, `createMockSignatureKeyPair`) have been added to facilitate testing of this new structure. The existing `SyncServiceTest` has been updated to include `accountKeys` in its mock response.
- Protected functional changes with optionality (feature …
> [PM-24568] Add `accountKeys` to `SyncResponseJson.Profile`

- .github/workflows/release-branch.yml
PM-24590
Support creating hotfix branches for Password Manager or Authenticator.
Test runs:
* BWPM -  https://github.com/bitwarden/android/actions/runs/16828964830
* BWA - https://github.com/bitwarden/android/actions/runs/16829006054
- ❓ …
> [PM-24590] Add support to hotfix specific apps in Cut Release Branch workflow

- app/src/main/kotlin/com/x8bit/bitwarden/data/auth/datasource/disk/AuthDiskSource.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/auth/datasource/disk/AuthDiskSourceImpl.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/auth/datasource/disk/AuthDiskSourceTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/auth/datasource/disk/util/FakeAuthDiskSource.kt
PM-24569
This adds functions to `AuthDiskSource` to store and retrieve `accountKeys`. Additionally, functions to store and retrieve the private key have been marked deprecated in favor of the account keys.
This includes:
- Adding `getAccountKeys` and `storeAccountKeys` methods to `AuthDiskSource` and its implementations.
- Deprecating the old `getPrivateKey` and `storePrivateKey` methods.
- Updating tests to use the new methods and verify their functionality.
- Ensuring that `clearAccountData` also clears the new `accountKeys`.
- Used internationalization (i18n) for all UI …
> [PM-24569] Save accountKeys to AuthDiskSource

- app/src/main/kotlin/com/x8bit/bitwarden/MainActivity.kt
- app/src/main/kotlin/com/x8bit/bitwarden/MainViewModel.kt
- app/src/test/kotlin/com/x8bit/bitwarden/MainViewModelTest.kt
[PM-24690](https://bitwarden.atlassian.net/browse/PM-24690)
This PR updates the way we display toasts in the MainActivity so we use the `ToastManager` directly in the ViewModel. …
> PM-24690: Use ToastManager in MainViewModel

- app/src/main/kotlin/com/x8bit/bitwarden/data/auth/datasource/disk/AuthDiskSource.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/auth/datasource/disk/AuthDiskSourceImpl.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/auth/datasource/disk/AuthDiskSourceTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/auth/datasource/disk/util/FakeAuthDiskSource.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/auth/repository/util/GetTokenResponseExtensionsTest.kt
- network/src/main/kotlin/com/bitwarden/network/model/AccountKeysJson.kt
- network/src/main/kotlin/com/bitwarden/network/model/GetTokenResponseJson.kt
- network/src/main/kotlin/com/bitwarden/network/model/SyncResponseJson.kt
- network/src/test/kotlin/com/bitwarden/network/service/IdentityServiceTest.kt
- network/src/testFixtures/kotlin/com/bitwarden/network/model/AccountKeysJsonUtil.kt
- network/src/testFixtures/kotlin/com/bitwarden/network/model/SyncResponseProfileUtil.kt
Completes PM-24721
Relates to https://github.com/bitwarden/server/pull/5982
Refactored `AccountKeys` to be a top-level model `AccountKeysJson` in the network module.
This change allows `AccountKeysJson` to be used in `GetTokenResponseJson` and `SyncResponseJson.Profile`.
The corresponding test fixtures for creating mock `AccountKeysJson` instances were also moved to a new file `AccountKeysJsonUtil.kt` in the network testFixtures.
`AuthDiskSource` and its implementation `AuthDiskSourceImpl`, along with the test fake `FakeAuthDiskSource`, were updated to use the new `AccountKeysJson` model.
- Protected functional changes with optionality …
> [PM-24721] Refactor AccountKeys to top-level common model

- app/src/main/kotlin/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreen.kt
- ui/src/main/kotlin/com/bitwarden/ui/platform/components/slider/BitwardenSlider.kt
- ui/src/main/kotlin/com/bitwarden/ui/platform/components/slider/color/BitwardenSliderColors.kt
[PM-24771](https://bitwarden.atlassian.net/browse/PM-24771)
This PR moves the `BitwardenSlider` in the `ui` module. …
> PM-24771: Move the slider to the UI module

- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/manager/utils/IntentManagerUtils.kt
N/A
The `startSystemAutofillSettingsActivity` function was incorrectly negating the result of `startActivity`. This commit removes the negation to correctly reflect the activity launch status.
https://github.com/user-attachments/assets/ead381da-c003-4028-ae69-8a10e657827f …
> Fix Autofill settings deeplink

- app/src/main/kotlin/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupAutofillScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/manager/intent/IntentManager.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/manager/intent/IntentManagerImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/manager/utils/IntentManagerUtils.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupAutofillScreenTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityScreenTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillScreenTest.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/ItemListingScreen.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/platform/manager/intent/IntentManager.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/platform/manager/intent/IntentManagerImpl.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/platform/util/IntentManagerUtils.kt
N/A
This PR updates the `IntentManager` and its extensions to simplify things where possible.
* Expose `packageName` from the IntentManager.
* Removes the context param from `ntentManager extensions.
* Minor bug fixes.
- ❓ (`:question:`) …
> Remove context param from IntentManager extensions

- network/src/main/kotlin/com/bitwarden/network/model/AccountKeysJson.kt
Relates to https://github.com/bitwarden/server/commit/8a39481fec87848e19cdd92d620d3e23b97901cb
The commit refactors the `AccountKeysJson` data class and its nested classes.
It removes the `@OptIn(ExperimentalSerializationApi::class)` annotation and updates the `@SerialName` annotations to use camelCase for consistency.
The `@JsonNames` annotations, which provided alternative names for deserialization, have been removed. This implies that the API now strictly expects camelCase keys.
- Communicated to …
> Refactor AccountKeysJson property names

- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/pendingrequests/PendingRequestsScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/importlogins/ImportLoginsScreen.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/util/ComposeTextHelper.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditScreenTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/importlogins/ImportLoginsScreenTest.kt
- ui/src/main/kotlin/com/bitwarden/ui/platform/components/bottomsheet/BitwardenModalBottomSheet.kt
- ui/src/testFixtures/kotlin/com/bitwarden/ui/util/ComposeTestHelpers.kt
[PM-25003](https://bitwarden.atlassian.net/browse/PM-25003)
This PR migrates the `BitwardenBottomSheet` to the `ui` module. …
> PM-25003: Migrate bottom sheet to the UI module

- app/src/main/kotlin/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreen.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreenTest.kt
- ui/src/main/res/values/strings.xml
[PM-20198](https://bitwarden.atlassian.net/browse/PM-20198)
This PR updates the Generator modal `Save` button to be `Apply`.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/d5bd26dd-f1d2-4cae-9764-77f6942b8ab2" width="300" /> | <img src="https://github.com/user-attachments/assets/2e722186-49a3-4269-988b-749ffa9cb32c" width="300" /> | …
> PM-20198: Update generator modal 'Save' button to 'Apply'

- core/src/main/kotlin/com/bitwarden/core/data/repository/util/SpecialCharWithPrecedenceComparator.kt
- core/src/test/kotlin/com/bitwarden/core/data/repository/util/SpecialCharWithPrecedenceComparatorTest.kt
[PM-17755](https://bitwarden.atlassian.net/browse/PM-17755)
This PR fixes a `Comparator` bug cause by inconsistent comparison logic based on the users locale. …
> PM-17755: Fix comparator inconsistency based on Locale

- app/src/main/kotlin/com/x8bit/bitwarden/data/autofill/di/AutofillModule.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/autofill/provider/AutofillCipherProviderImpl.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/autofill/processor/AutofillCipherProviderTest.kt
PM-25057
This commit filters the list of card autofill ciphers based on active policies that restrict item types for organizations. …
> [PM-25057] Filter Card Autofill Ciphers by Policy

- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/search/SearchViewModel.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/manager/snackbar/SnackbarRelay.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModel.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModel.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt
[PM-25069](https://bitwarden.atlassian.net/browse/PM-25069)
This PR updates toasts (where possible) in the `VaultAddEditViewModel` o use Snackbars instead. …
> PM-25069: Update VaultAddEditViewModel toasts to snackbars

- app/src/main/kotlin/com/x8bit/bitwarden/MainActivity.kt
[PM-25143](https://bitwarden.atlassian.net/browse/PM-25143)
🍒 This PR updates the mechanism used to restart the main activity on old revisions of Android 15.
The issue was that the intent was generated using the `makeMainActivity` function, this was causing intent data loss on recreation. This change uses the existing intent to prevent intent data loss and manually applies all the same properties as `makeMainActivity` to maintain the correct other functionality. …
> 🍒 PM-25143: Retain intent data on recreate

- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/datasource/sdk/model/Fido2CredentialStoreImpl.kt
PM-25239
Resolves #5218 
Do not attempt sync when performing passkey operations so that vault connectivity is not required.
Legacy passkeys that require counters may fail if they have not been synced recently. Users must manually trigger sync in order to use the legacy passkey. …
> [PM-25239] Remove unnecessary vault sync from `Fido2CredentialStoreImpl`

- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/repository/util/VaultSdkCollectionExtensions.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/vault/repository/util/VaultSdkCollectionExtensionsTest.kt
PM-25327
Collections are now sorted primarily by `CollectionType`, with `DEFAULT_USER_COLLECTION` appearing first, and then alphabetically by name within each type group.
Additionally, the `toCollectionType()` function has been renamed to `toSdkCollectionType()` for clarity.
Corresponding test cases have been updated to reflect these changes.
- 👍 …
> [PM-25327] Display default user collections first

- .github/workflows/build.yml
PM-25396
While handling the release process our team noticed builds in Firebase that weren't published to PlayStore, this PR addresses that. 
Our QA team noted something similar previously happened when distribution inputs were missed while triggering manual builds, changing the input defaults too while at it.  …
> [PM-25396] Publish store builds when release branches are updated

- app/src/main/kotlin/com/x8bit/bitwarden/data/platform/manager/PushManagerImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/platform/manager/model/SyncFolderDeleteData.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryImpl.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/platform/manager/PushManagerTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt
[PM-25462](https://bitwarden.atlassian.net/browse/PM-25462)
This PR update the `SYNC_FOLDER_DELETE` push notification processing to allow us to delete Folders when the user is not currently the active user. …
> PM-25462: Allow SYNC_FOLDER_DELETE notification to delete Folders for inactive user

- app/src/main/kotlin/com/x8bit/bitwarden/data/platform/manager/PushManagerImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/platform/manager/model/SyncCipherDeleteData.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryImpl.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/platform/manager/PushManagerTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt
[PM-25474](https://bitwarden.atlassian.net/browse/PM-25474)
This PR update the `SYNC_CIPHER_DELETE` push notification processing to allow us to delete Ciphers when the user is not currently the active user. …
> PM-25474: Allow SYNC_CIPHER_DELETE notification to delete Cipher for inactive user

- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryImpl.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt
[PM-25478](https://bitwarden.atlassian.net/browse/PM-25478)
This PR allows the upsert events from push notifications to update a vault Folder or Send without requiring the vault to be unlocked.
- 🤔 …
> PM-25478: Update sends and folders while vault is locked

- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/model/VaultUnlockedNavBarTab.kt
- ui/src/main/kotlin/com/bitwarden/ui/platform/components/navigation/model/NavigationItem.kt
[PM-25162](https://bitwarden.atlassian.net/browse/PM-25162)
This PR addresses a bug in the Bottom Nav navigation that was causing the Settings tab to not navigate up when clicked.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/6f8563e9-381e-4df0-abfb-4f776a7d168e" width="300" /> | <video src="https://github.com/user-attachments/assets/bbfb39cc-871d-4b65-80d7-8dc5298dc473" width="300" /> |
- Updated any …
> PM-25162: Fix a navigation bug in bottom navigation

- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/datasource/sdk/VaultSdkSource.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/datasource/sdk/VaultSdkSourceImpl.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/vault/datasource/sdk/VaultSdkSourceTest.kt
PM-25522
Add a new function `importCxf` to the `VaultSdkSource` interface and its implementation `VaultSdkSourceImpl`. This function allows importing data in CXF format into the user's vault.
The `importCxf` function takes a user ID and a CXF payload as input and returns a `Result` containing a list of `Cipher` objects if the import is successful.
Unit tests have been added to verify the functionality of the new function. …
> [PM-25522] Add `importCxf` function to `VaultSdkSource`

- app/src/main/AndroidManifest.xml
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/search/SearchContent.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/SettingsViewModel.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillScreen.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/importlogins/ImportLoginsScreenTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemScreenTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/vault/VaultScreenTest.kt
- ui/src/main/res/values/strings.xml
N/A
Cleanup lint warnings in string resources.
- 🎨 …
> Cleanup minor lint warnings in string resources

- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/datasource/disk/VaultDiskSource.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/datasource/disk/VaultDiskSourceImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/datasource/disk/dao/CiphersDao.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/repository/VaultRepository.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/repository/util/AccountJsonExtensions.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/vault/datasource/disk/VaultDiskSourceTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/vault/datasource/disk/dao/FakeCiphersDao.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/vault/datasource/sdk/model/AccountUtil.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/vault/repository/model/AccountJsonUtil.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/vault/repository/util/AccountJsonExtensionsTest.kt
PM-15056
Introduce the `exportVaultDataToCxf` function to the `VaultRepository` and its implementation. This function allows exporting selected ciphers to a CXF file.
The following changes were made:
- Added `getSelectedCiphers` to `CiphersDao` and `VaultDiskSource` to retrieve specific ciphers by their IDs.
- Created an `AccountJson.toSdkAccount()` extension function to convert `AccountJson` to the SDK's `Account` model.
- Implemented `exportVaultDataToCxf` in `VaultRepositoryImpl` to utilize the new data source methods and the SDK for CXF export.
- Added corresponding tests for the new functionalities.
- Protected functional changes with …
> [PM-15056] Add `exportVaultDataToCxf` function to `VaultRepository`

- authenticator/src/main/kotlin/com/bitwarden/authenticator/data/platform/manager/imports/parsers/TwoFasExportParser.kt
https://bitwarden.atlassian.net/browse/PM-22320
On some scenarios the 2fas export is missing the algorithm. Defaulting to SHA1 solves the issue and makes it consistent with iOS authenticator
- 🤔 …
> [PM-22320] Default to SHA1 on 2fas importer if algorithm is missing

- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/edititem/EditItemScreen.kt
- ui/src/main/res/values/strings.xml
[PM-24234](https://bitwarden.atlassian.net/browse/PM-24234)
This PR adds one last missing plurals translation to the app. …
> PM-24234: Add missing plurals

- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/appearance/AppearanceScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/exportvault/ExportVaultScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/FlightRecorderScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/other/OtherScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditCardItems.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditIdentityItems.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditUriItem.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/platform/feature/settings/SettingsScreen.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/platform/feature/settings/export/ExportScreen.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/platform/feature/settings/importing/ImportingScreen.kt
- ui/src/main/kotlin/com/bitwarden/ui/platform/base/util/StringResExtensions.kt
- ui/src/main/kotlin/com/bitwarden/ui/platform/base/util/StringUtil.kt
- ui/src/main/kotlin/com/bitwarden/ui/util/Text.kt
N/A
Clean up some minor lint warnings by replacing `LocalContext.current.resources` with `LocalResources.current`. …
> Update resources to use LocalResources

- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/importitems/ImportItemsViewModel.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/importitems/ImportItemsViewModelTest.kt
- ui/src/main/res/values/strings.xml
PM-25822
This change introduces the `ImportItemsViewModel` responsible for handling the logic of importing items from other credential managers.
It also adds new string resources used in the import items feature.
Additionally, unit tests for `ImportItemsViewModel` are included. …
> [PM-25822] Add `ImportItemsViewModel` and related strings 

- app/src/main/kotlin/com/x8bit/bitwarden/data/platform/manager/SdkClientManagerImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/platform/manager/di/PlatformManagerModule.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/datasource/sdk/ScopedVaultSdkSourceImpl.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/platform/manager/SdkClientManagerTest.kt
- data/build.gradle.kts
- data/src/main/kotlin/com/bitwarden/data/manager/NativeLibraryManager.kt
- data/src/main/kotlin/com/bitwarden/data/manager/NativeLibraryManagerImpl.kt
- data/src/main/kotlin/com/bitwarden/data/manager/di/DataManagerModule.kt
N/A
Move `NativeLibraryManager` and its implementation `NativeLibraryManagerImpl` from the `app` module to the `data` module.
This change also involves updating import statements and dependency injection configurations.
The `data` module now includes `timber` as a new dependency. …
> Move NativeLibraryManager to data module

- cxf/src/main/kotlin/androidx/credentials/providerevents/ProviderEventsManager.kt
- cxf/src/main/kotlin/androidx/credentials/providerevents/transfer/RegisterExportResponse.kt
- cxf/src/main/kotlin/com/bitwarden/cxf/registry/CredentialExchangeRegistry.kt
- cxf/src/main/kotlin/com/bitwarden/cxf/registry/CredentialExchangeRegistryImpl.kt
The `registerExport` function in `ProviderEventsManager` and `CredentialExchangeRegistry` now returns a `RegisterExportResponse` instead of a `Boolean`.
A placeholder `RegisterExportResponse` class has been added.
The `StubProviderEventsManager` has been updated to return a `RegisterExportResponse` and provide canned data for `importCredentials` for testing purposes.
- Updated any necessary documentation (Confluence, contributing docs) …
> Update `registerExport` to return `RegisterExportResponse`

- app/src/main/kotlin/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/auth/repository/model/ResendEmailResult.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginViewModel.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
- network/src/main/kotlin/com/bitwarden/network/model/InvalidJsonResponse.kt
- network/src/main/kotlin/com/bitwarden/network/model/VerificationCodeResponseJson.kt
- network/src/main/kotlin/com/bitwarden/network/model/VerificationOtpResponseJson.kt
- network/src/main/kotlin/com/bitwarden/network/service/AccountsService.kt
- network/src/main/kotlin/com/bitwarden/network/service/AccountsServiceImpl.kt
- network/src/test/kotlin/com/bitwarden/network/service/AccountsServiceTest.kt
[PM-25908](https://bitwarden.atlassian.net/browse/PM-25908)
This PR processes the error responses with a 400 code from the `end-email-login` and `resend-new-device-otp` APIs. …
> PM-25908: Process 400 responses from verification code APIs

- app/src/main/kotlin/com/x8bit/bitwarden/data/autofill/di/AutofillModule.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/autofill/manager/browser/BrowserAutofillDialogManager.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/autofill/manager/browser/BrowserAutofillDialogManagerImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/autofill/model/browser/BrowserThirdPartyAutoFillData.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSource.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSourceImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillViewModel.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/vault/VaultGraphNavigation.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/vault/VaultNavigation.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/vault/VaultScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModel.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/vault/handlers/VaultHandlers.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/autofill/manager/browser/BrowserAutofillDialogManagerTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/platform/datasource/disk/SettingsDiskSourceTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/platform/datasource/disk/util/FakeSettingsDiskSource.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillViewModelTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/vault/VaultScreenTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModelTest.kt
- ui/src/main/kotlin/com/bitwarden/ui/platform/components/dialog/BitwardenTwoButtonDialog.kt
- ui/src/main/res/values/strings.xml
[PM-25258](https://bitwarden.atlassian.net/browse/PM-25908)
This PR adds a dialog to the VaultScreen that lets the user know that Autofill is currently not configured properly for their browser and that they can fix it in Autofill settings. The takes them there.
<video src="https://github.com/user-attachments/assets/6662ee32-c075-496a-ae70-22acfda367b4" width="300" />
- Updated any necessary documentation (Confluence, contributing docs) or informed the …
> Pm 25258 browser autofill dialog

- app/src/main/kotlin/com/x8bit/bitwarden/data/credentials/di/CredentialProviderModule.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/credentials/manager/OriginManagerImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/debugmenu/components/FeatureFlagListItems.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillViewModel.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/credentials/manager/OriginManagerTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuViewModelTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillScreenTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillViewModelTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
- authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/platform/feature/debugmenu/components/FeatureFlagListItems.kt
- core/src/main/kotlin/com/bitwarden/core/data/manager/model/FlagKey.kt
- core/src/test/kotlin/com/bitwarden/core/data/manager/model/FlagKeyTest.kt
- ui/src/main/res/values/strings_non_localized.xml
[PM-26027](https://bitwarden.atlassian.net/browse/PM-26027)
This PR removes the `UserManagedPrivilegedApps` feature flag. …
> PM-26027: Remove the UserManagedPrivilegedApps feature flag

- app/src/main/kotlin/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupAutofillScreen.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupAutofillScreenTest.kt
PM-26151
This PR updates the onboarding screen for Autofill to disable the `Continu`e button until the user enabled Autofill. They can still select the `Turn on later` option. …
> PM-26151: Disable continue button for Autofill onboarding flow when autofill is disabled

- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/manager/CredentialExchangeImportManagerImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/manager/VaultSyncManager.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/manager/VaultSyncManagerImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/manager/di/VaultManagerModule.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/manager/model/ImportCxfPayloadResult.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/repository/VaultRepository.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/repository/di/VaultRepositoryModule.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/vault/manager/CredentialExchangeImportManagerTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/vault/manager/VaultSyncManagerTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt
N/A
This PR extracts the remaining Sync logic into the `VaultSyncManager`. …
> Fully extract more sync logic into the VaultSyncManager

- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/vault/VaultScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModel.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/vault/handlers/VaultHandlers.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/vault/VaultScreenTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModelTest.kt
- ui/src/main/res/values/strings.xml
[PM-26303](https://bitwarden.atlassian.net/browse/PM-26303)
This PR removes the `Exit` button from the overflow menu of the `VaultScreen`. …
> PM-26303: Remoe the 'Exit' button from the VaultScreen overflow menu

- app/src/main/kotlin/com/x8bit/bitwarden/data/platform/manager/PushManager.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/platform/manager/PushManagerImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/platform/manager/model/NotificationPayload.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/manager/VaultSyncManagerImpl.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/importlogins/ImportLoginsViewModel.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/platform/manager/PushManagerTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/vault/manager/VaultSyncManagerTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/importlogins/ImportLoginsViewModelTest.kt
[PM-25642](https://bitwarden.atlassian.net/browse/PM-25642)
This PR updates the background sync and import logins sync to be a forced sync. …
> PM-25642: Force sync or clear last sync time on sync notification

- app/src/main/kotlin/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupBrowserAutofillScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupBrowserAutofillViewModel.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupBrowserAutofillScreenTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupBrowserAutofillViewModelTest.kt
- ui/src/main/res/values/strings.xml
[PM-26312](https://bitwarden.atlassian.net/browse/PM-26312)
This PR adds the browser integration help link to to the browser integration onboarding screen.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/5c1ed77d-e298-4be3-ab64-676d52f560e5" width="300" /> | <img src="https://github.com/user-attachments/assets/43aa1628-d6e6-4b98-ae6c-0e4f554ccf96" width="300" /> | …
> PM-26312: Add browser integration help link

- app/src/main/kotlin/com/x8bit/bitwarden/data/credentials/model/Fido2AttestationResponse.kt
- app/src/main/kotlin/com/x8bit/bitwarden/data/vault/datasource/sdk/util/PublicKeyCredentialAuthenticatorAttestationResponseExtensions.kt
- app/src/test/kotlin/com/x8bit/bitwarden/data/vault/datasource/sdk/util/PublicKeyCredentialAuthenticatorAttestationResponseExtensionsTest.kt
https://bitwarden.atlassian.net/browse/PM-17870
When the SDK did not return information about the resident key (rk), we omitted the `clientExtensionResults` field from the jsonResponse. This caused Chromium to fail parsing the credential response
This PR updates the implementation to always include `clientExtensionResults`, defaulting to an empty object.
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation …
> [PM-17870] Always include clientExtensionResults in Fido2AttestationResponse

- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/addedit/util/CipherViewExtensions.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/addedit/util/CipherViewExtensionsTest.kt
PM-26330
This commit fixes an issue where the owner data was not correctly set when the individual vault was disabled. The `appendFolderAndOwnerData` function in `CipherViewExtensions.kt` has been updated to correctly determine the default owner and collection when the individual vault is disabled.
Additionally, new tests have been added to `CipherViewExtensionsTest.kt` to cover this scenario.
Coming soon! …
> [PM-26330] Correct owner data when individual vault is disabled

- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/exportitems/selectaccount/SelectAccountScreen.kt
- app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/exportitems/selectaccount/SelectAccountViewModel.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/exportitems/SelectAccountScreenTest.kt
- app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/exportitems/SelectAccountViewModelTest.kt
- ui/src/main/kotlin/com/bitwarden/ui/platform/components/content/BitwardenEmptyContent.kt
- ui/src/main/kotlin/com/bitwarden/ui/platform/components/content/BitwardenLoadingContent.kt
- ui/src/main/res/values/strings.xml
PM-26355
This commit refactors the `SelectAccountScreen` to better handle different states (Loading, Content, NoItems) by introducing a sealed `ViewState` class within `SelectAccountState`.
This change also includes:
- Updating `SelectAccountViewModel` to emit the new `ViewState`.
- Modifying `SelectAccountScreen` to display UI based on the `ViewState`.
- Adding new string resources for the "No accounts available" state.
- Updating unit tests to reflect these state handling improvements.
- Using `ImportCredentialsCancellationException` when the user cancels the import flow.
- …
> [PM-26355] Improve SelectAccountScreen state handling
