bitwarden/android

src/App/Resources/AppResources.fr.resx

Various grammar and spelling corrections.
Replace all «sites» mentions with «logins» (identifiants) mentions.
Add and translate lines 760 to 819.
I don't have a Xamarin development environment setup, so I couldn't test the translations.

Corrections + new french translations

---

src/App/Services/TokenService.cs

To avoid errors in Task<ApiResult<TokenResponse>> when logging in on
UWP apps ensure that we check that they key exists before we delete the
2FA key token.

TokenService.cs: Check if key exists before deleting it

---

src/App/Pages/LoginPage.cs

This series provides a lot of fixes for Windows 10 and Windows Phone 10 UWP platforms.
This sets the toolbar options to have images (otherwise they look blank on the default view). See https://github.com/bitwarden/mobile/pull/188 for what the difference is.
This also fixes up the layout to correctly separate the login boxes (they used to be touching) and ensures that the reset password link can be seen by the user.
It fixes up some missing images.
Finally it allows the back button to appear when running on Windows 10. Previously it would not appear and there would be no obvious way to progress backwards. This allows us to remove the cancel button.
I'm getting the hang of this now, so if this is merged I can keep working on the other pages.
This is what it looks like now:
Phone
Desktop

Login page fixes

---

src/App/Pages/EnvironmentPage.cs
src/App/Pages/Lock/LockPasswordPage.cs
src/App/Pages/LoginPage.cs
src/App/Pages/LoginTwoFactorPage.cs
src/App/Pages/PasswordHintPage.cs
src/App/Pages/RegisterPage.cs
src/App/Pages/Settings/SettingsAddFolderPage.cs
src/App/Pages/Settings/SettingsEditFolderPage.cs
src/App/Pages/Tools/ToolsPasswordGeneratorPage.cs
src/App/Pages/Vault/VaultAddCipherPage.cs
src/App/Pages/Vault/VaultAttachmentsPage.cs
src/App/Pages/Vault/VaultCustomFieldsPage.cs
src/App/Pages/Vault/VaultEditCipherPage.cs
src/App/Pages/Vault/VaultViewCipherPage.cs
src/App/Utilities/Helpers.cs

This adds a helper function which we can use to set logos for Windows
platforms to ensure the user can see the UWP toolbar actions. This won't
have an effect on non-Windows platforms.

App: LoginPage.cs: Use a logo for the login button

---

src/App/Pages/Lock/LockFingerprintPage.cs
src/App/Pages/Settings/SettingsPage.cs
src/App/Resources/AppResources.Designer.cs
src/App/Resources/AppResources.resx
src/UWP.Images/UWP.Images.projitems

Windows Hello is currently supported in the UWP app, but all of the
strings just point to using fingerprint. Windows Hello instead will
adjust based on what the user has avaliable and registered with the
Windows OS. To reflect that it isn't just fingerprints update the
strings when on UWP.

Add support for Windows Hello

---

src/App/Pages/Vault/VaultAutofillListCiphersPage.cs
src/App/Pages/Vault/VaultListCiphersPage.cs
src/App/Pages/Vault/VaultListGroupingsPage.cs

When specifying page options the loader doesn't appear properly on UWP
applications. I also couldn't see the options documented here:
https://developer.xamarin.com/api/type/Xamarin.Forms.ActivityIndicator/

Vault: Don't specify page options for ActivityLoading

---

src/UWP/App.xaml.cs

Following the instructions here:
https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-API#windows-uwp---compile-with-net-native-tool-chain-note
fix the UWP App.xaml.cs to ensure images are loaded when building UWP
apps for release.

UWP: Fix images when compiling with .NET Native Toolchain

---

src/App/Pages/Vault/VaultListGroupingsPage.cs

To avoid accessing a null poiter add a null check in OnSelectTemplate().

App: Pages: Add a null check in OnSelectTemplate()

---

src/UWP/App.xaml.cs
src/UWP/Controls/ExtendedTableViewRenderer.cs
src/UWP/UWP.csproj

Add a base ExtendedTableViewRenderer we can use.
This is part of the work to fix the vertical layout issues, not there yet, but I think this is moving in the right direction.

UWP: Add a ExtendedTableViewRenderer

---

src/App/Models/Page/VaultViewCipherPageModel.cs

This is a pretty simple PR. I'm migrating from 1Password to Bitwarden, and I noticed that while 1Password has a constant-length password mask, Bitwarden's leaks the length of the password even when it's masked. This commit simply changes to a constant-length mask.

Don't leak password length through mask

---

src/App/Models/Page/VaultViewCipherPageModel.cs
src/App/Pages/Vault/VaultAddCipherPage.cs
src/App/Pages/Vault/VaultEditCipherPage.cs
src/App/Pages/Vault/VaultViewCipherPage.cs

By default shows Card Security Code masked in the same way as Passwords. (bitwarden/desktop issue 78)
Only tested on Android (not iOS devices available) but when setting input field to password, the keyboard type of "Numeric" isn't honoured and it shows standard keyboard with numbers at the top.  Tested this is new project and the same thing happens.

Card Security Code masked (bitwarden/desktop issue 78)

---

src/App/Pages/Tools/ToolsPage.cs

In the tab tools when you have a self hosted bitwarden environment and click on the web vault.
The application open the link "https://vault.bitwarden.com" instead of the defined BaseUrl.
This commit fix the link if a BaseUrl is defined.

Use BaseUrl when opening web vault if defined

---

src/Android/Android.csproj
src/Android/Properties/AndroidManifest.xml
src/Android/Resources/Resource.Designer.cs
src/Android/Resources/xml/network_security_config.xml

See: https://android-developers.googleblog.com/2016/07/changes-to-trusted-certificate.html
Fixes: #346

Honor user CA store when targeting Android Nougat SDK and later

---

src/Android/MainActivity.cs

Bitwarden crashes when trying to add a file that does not exist on the filesystem as an attachment.
The Android 'Documents' app seems to keep a cache of downloaded files despite those files having been deleted off the file system. This cases Bitwarden to crash when the user selects them.
I figure that presenting some error to the user when this happens makes sense, but beyond the generic "An error has occurred" message, I couldn't find a suitable resource.

Handle exception when adding attachment that does not exist on file system.

---

src/Android/Controls/ExtendedEntryRenderer.cs
src/App/Controls/ExtendedEntry.cs
src/App/Controls/PinControl.cs

Set Android InputType directly for the pin lock screen to force numeric-only keyboard layout.

---

src/Android/Autofill/AutofillHelpers.cs
src/Android/AutofillService.cs
src/Android/Resources/xml/autofillservice.xml

The F-Droid build of Firefox (Fennec) has a different package name.
This name needs to be explicitly listed in order for autofill support to
work correctly.

Android: Support autofill in Fennec F-Droid

---

src/App/Pages/Generator/GeneratorHistoryPage.xaml
src/App/Pages/Generator/GeneratorPage.xaml
src/App/Pages/Generator/GeneratorPageViewModel.cs
src/App/Pages/Vault/PasswordHistoryPage.xaml
src/App/Pages/Vault/ViewPage.xaml
src/App/Utilities/ColoredPasswordConverter.cs
src/App/Utilities/PasswordFormatter.cs

Passwords displayed in the password generator are not colour coded like they are on other platforms. This pull request changes the password generator password to be colour coded.
https://community.bitwarden.com/t/color-coded-password-not-working-on-android/9594

Change password generator to use ColoredPassword

---

src/Android/Accessibility/AccessibilityHelpers.cs
src/Android/Accessibility/AccessibilityService.cs

* AccessibilityHelpers.cs:  If AccessibilityNodeInfo.FindAccessibilityNodeInfosByViewId(..) returns null when the source package is a supported browser, return a null uri to prevent overwriting the existing notification's pendingIntent uri extra with the brower's packageName.
* AccessibilityService.cs: Added null uri checks as it is now possible for AccessibilityHelpers.getUri(..) to return a null uri when the Accessibility Service is misbehaving.

Fix for notification pendingIntent uri being set to browser package name

---

src/Android/Accessibility/AccessibilityService.cs

Removal of double-event block for known browsers since it's no longer necessary and was preventing the overlay from working with some browsers

Removal of double-event block for known browsers

---

src/App/Services/MobileStorageService.cs
src/App/Services/PreferencesStorageService.cs

Currently, we store environment URLs in our LiteDB JSON database. Enterprise customers have expressed a desire to pre-configure the environment URL of the app for their employees using app installation tools like https://www.appconfig.org/. These tools can generally only pre-configure app values that are stored in `NSUserDefaults` (iOS) or `SharedPreferences` (Android). See https://www.appconfig.org/www/appconfig-content/uploads/2015/08/ImplementingAppConfigwithXamarin.pdf
To support this, we need to move environment URLs to be stored in our `PreferencesStorageService`. Existing users with configured environment URLs need to have their values migrated from `LiteDbStorage` to `PreferencesStorageService`.

Migrate EnvironmentUrls to pref storage

---

src/App/Pages/Accounts/TwoFactorPageViewModel.cs

In the callback the processing does not go in the main UI thread, so we
need to switch there. Otherwise on Android this throws
Android.Util.AndroidRuntimeException with detail “Only the original thread
that created a view hierarchy can touch its views”.
Discovered by trying to login with Duo as a two-factor login type.

Fix runtime exception.

---

src/App/Pages/Accounts/TwoFactorPageViewModel.cs

The code expects to be called form UI thread, but it looks like JavaScript
callbacks are not. Switch to UI thread when invoking a callback.
This is a better fix than #738, because this fixes the whole callback thread issue.

Make callbacks from UI thread.

---

src/App/Pages/Generator/GeneratorPage.xaml
src/App/Utilities/PasswordFormatter.cs

Some key takeaways:
- One character of the alpha hex code was still in the hex color.  Android ignored the invalid char and was able to establish the intended hex color, whereas iOS threw the whole thing out as invalid, hence the color-less passwords.  Also had to add another span for the "normal" color so it respects what "normal" is based on the selected app theme.  I actually can't figure out how Android is doing this automatically.
- Changing the label to `HorizontalOptions="CenterAndExpand"` mimics the behavior of `wrap_content` in Android, so the label itself is only as wide as the text within.  This "fixes" the issue of iOS ignoring `HorizontalTextAlignment="Center"` when `TextType="Html"` is used, but only if the password is on a single line.  Once the password starts wrapping, …

Fixed password color and alignment on iOS password generator

---

src/App/Utilities/PasswordFormatter.cs

- Added a (hacky) fix to get per-char wrapping working properly with special chars by adding a zero-width space char after every char (these are then treated as a "safe" place to wrap by the system, restoring the smoother wrapping experience we had pre-colorized passwords)
- Wrapped the spans in a div on iOS.  Without it, iOS was visibly displaying the zero-width space char.  Android refuses to keep divs on a single line (ignoring the inline* attr) which is why we restrict this to iOS.
- Added `HttpUtility.HtmlEncode()` on special chars so < > etc. are displayed properly

Fixes for html wrapping and encoding

---

src/Android/Services/DeviceActionService.cs
src/App/Pages/Vault/ViewPage.xaml.cs
src/App/Pages/Vault/ViewPageViewModel.cs
src/App/Resources/AppResources.Designer.cs
src/App/Resources/AppResources.resx

Introduced new attachment handling flow for Android:  Click download icon -> perform download -> If the file can be opened by the system, present user with "open or save" prompt -> If the file can't be opened by the system, go directly into the save flow.  This effectively means we can save any type of attachment + optionally open/view directly if supported.

New Android attachment handling to support saving or opening attachments

---

src/Core/Abstractions/IPasswordGenerationService.cs
src/Core/Services/PasswordGenerationService.cs

This PR brings the codebase in alignment with some jslib changes. See https://github.com/bitwarden/jslib/pull/83
> Allows us to pass in some options to have policies enforced upon. need this for upcoming CLI PR where options are derived instead of pulled from storage.

Allows us to pass in some options to have policies enforced upon.

---

src/App/Pages/Settings/ExportVaultPage.xaml.cs
src/Core/Services/PasswordGenerationService.cs

- Added missing call to Unsubscribe broadcaster service in ExportVaultPage (and fixed copy pasta on Subscribe call)
- Rewrote policy parser to properly check for existence of key before value retrieval

Fixed potential broadcast leak & policy value parsing

---

src/App/App.xaml.cs
src/App/Pages/Accounts/TwoFactorPageViewModel.cs

Workaround for older bug in Xamarin.Forms by waiting for app to resume before attempting to set Application.Current.MainPage.  Fixed in latest Xamarin.Forms 4.4.0.x but it's too dangerous to swap that out so close to a release.
This fixes the issue with Duo that only occurs when you leave the Bitwarden app completely to acknowledge the push (in recent versions of Android you can ack the push directly from the Duo notification, never leaving the Bitwarden app)

Wait for app to resume before attempting to set Application.Current.MainPage

---

src/App/Pages/Vault/CiphersPage.xaml.cs
src/App/Pages/Vault/CiphersPageViewModel.cs

- Perform search result list update on main thread to force thread safety on the underlying ObservableCollection.  This fixes the occasional `ArgumentOutOfRangeException` as well as the strange behavior where hitting the IME "enter" key after entering text would clear the results and state none were found even though they exist.
- Changed existing search execution delay for keystrokes to 200ms to match web
- Fixed race condition where non-delayed search (keyboard "enter") jumped the queue and the prior delayed search (text change) would still modify the search results, contributing to the "no results found" problem (we're now returning when `OperationCanceledException` is thrown)

Fixed issue where multiple threads were attempting to modify search result list

---

src/App/Pages/TabsPage.cs
src/App/Styles/Base.xaml
src/iOS/Renderers/CustomTabbedRenderer.cs

Looks like the platform-specific property for tab colors was deprecated in Xamarin.Forms 4, so moved this to proper styling (new way) and removed the custom renderer hack on iOS.
Also changed Icon to IconImageSource since apparently that was deprecated now too.

Move tab bar colors to styles

---

src/Core/Services/SyncService.cs

Fixes sync issue introduced with policies combined with org-less accounts

Null check policies from SyncResponse before parsing

---

src/App/Pages/Settings/ExportVaultPageViewModel.cs
src/Core/Core.csproj

- Bumped CsvHelper to 15.0.1
- Added missing error dialog in export failure catch block

Bumped csvHelper to 15.0.1 and added missing error dialog in export failure flow

---

src/App/Pages/Generator/GeneratorPage.xaml
src/App/Pages/Generator/GeneratorPageViewModel.cs
src/Core/Models/Domain/PasswordGeneratorPolicyOptions.cs
src/Core/Services/PasswordGenerationService.cs

> Add missing components for passphrase policy. Use existing data structures/patterns to implement a shared password generator (password/passphrase) for both Android and iOS.
- **GeneratorPage.xaml**: Added `IsEnabled` values for `Capitalize` and `IncludeNumber` switches depending on the `EnforcedPolicyOptions` returned
- **GeneratorPageViewModel.cs**: Updated boolean property to use newly added `InEffect()` function
- **PasswordGeneratorPolicyOptions.cs**: Added new fields for tracking the passphrase policy. Created helper method to clear up a long conditional in the view model.
- **PasswordGenerationService.cs**: Passphrase options are now enforced during `PasswordGeneratorPolicyOptions` objection creation.  User options are now updated with passphrase options during retrieval. …

Enforce Passphrase Policy

---

src/Core/Models/Domain/PasswordGeneratorPolicyOptions.cs

> Policy In Effect banner is showing up for users not in an organization [Reddit](https://www.reddit.com/r/Bitwarden/comments/fjfies/one_or_more_organization_policies_are_affecting/)
- Downstream code was expecting the `PasswordGeneratorPolicyOptions` object to have a default `DefaultType` of an empty string. This was not being set, causing the conditional `DefaultType != ""` to return true.
- **PasswordGeneratorPolicyOptions.cs**: Added default value for `DefaultType` property. This now mimics the js codebase.

Fix bug with policy banner visibility

---

src/Core/Services/PasswordGenerationService.cs

> Rearrange the current password generation code in order to update the UI if password length varies based on the selected options.  Relates to [Web Bug #497](https://github.com/bitwarden/web/issues/497)
- **PasswordGenerationService.cs**: Created `SanitizePasswordLength` method that can be called with UI changes or for password generation only.  Maintains existing workflows but will now properly update the UI if a minimum length condition is met.

Sanitize Password Length

---

src/App/Pages/Vault/ScanPage.xaml.cs

The QR code in the attached issue is inverted.  Adding `TryInverted` to the scan options makes ZXing aware of it.

Add support for inverse data matrix QR codes

---

src/Android/Accessibility/AccessibilityActivity.cs
src/Android/Accessibility/AccessibilityHelpers.cs
src/Android/Accessibility/AccessibilityService.cs
src/Android/Android.csproj
src/Android/Resources/values/strings.xml
src/Android/Tiles/AutofillTileService.cs
src/App/Resources/AppResources.Designer.cs
src/App/Resources/AppResources.resx
src/Core/Constants.cs

The user can now add a "scan & fill" quick setting tile on Android 7.0+ via the Android's tile edit/config mechanism.  It uses accessibility to perform the autofill and can be used in addition to, or in lieu of, the accessibility overlay (by leaving the overlay permission disabled they can safely use the tile only - the missing-overlay-permission toast only appears if the tile isn't enabled).
Fun stuff:
- You can only collapse the quick settings dropdown by launching an activity or opening a dialog.  Once I accepted defeat here I resorted to using a dialog for the "you need to enable accessibility" error, and an activity to trigger the broadcast message to the accessibility service to perform a field search.
- Without waiting 250ms after receiving the trigger message, the window parser …

Added Quick Settings tile for triggering accessibility autofill

---

src/Android/Resources/values/strings.xml
src/Android/Tiles/AutofillTileService.cs
src/App/Pages/Vault/AutofillCiphersPage.xaml
src/App/Resources/AppResources.resx

- Changed wording of autofill tile from "Scan & Fill" to "Auto-fill" for consistency throughout the app
- Fixed missing "+" icon in FAB when attempting to autofill something that doesn't exist in your vault
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1169444489336079/1169794380212370) by [Unito](https://www.unito.io/learn-more)

Tweaks to autofill tile naming & fixed missing plus icon

---

src/Android/Accessibility/AccessibilityHelpers.cs
src/Android/Autofill/AutofillHelpers.cs

Add autofill (accessibility) support for Vivaldi snapshot browser
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1169444489336079/1170066913744691) by [Unito](https://www.unito.io/learn-more)

Add support for Vivaldi snapshot browser

---

src/Android/Accessibility/AccessibilityHelpers.cs
src/Android/Accessibility/AccessibilityService.cs

- Removed dependency on MainActivity for acquiring resource context from the `GetSystemResourceDimenPx` helper method as the "current" activity may not be ours (confirmed via invalid cast exceptions in crash logs).  Now using the resource context from our own service.
- Added some smarts to detect the presence of the autofill service prompt and back off if it's visible (we want the autofill service to take priority over accessibility - in most cases this happens automatically but in situations where it doesn't, this should help).
- Moved time-based overload protection (as well as new autofill detection) in front of overlay permission warning toast.  I believe the false positives (negatives?) returned by `Settings.CanDrawOverlays(...)` may be caused by excessive pounding on the method by …

Additional accessibility tweaks

---

src/App/App.csproj
src/App/Pages/Generator/GeneratorPage.xaml

Updated to Xamarin.Forms `4.5.0.617` which fixes slider binding when operating via TalkBack on Android.  Also added `AutomationProperties.HelpText` to read length aloud while adjusting.

Fix for talkback slider control

---

src/App/App.csproj
src/App/App.xaml.cs
src/App/Pages/Accounts/HomePage.xaml.cs
src/App/Pages/Accounts/LockPage.xaml.cs
src/App/Pages/Accounts/LoginPage.xaml.cs
src/App/Pages/Accounts/LoginPageViewModel.cs
src/App/Pages/Accounts/TwoFactorPage.xaml.cs
src/App/Pages/Accounts/TwoFactorPageViewModel.cs
src/App/Pages/Generator/GeneratorPage.xaml

> Allow logged out applications to be aware of auto-fill flow. This closes a gap between being locked vs logged out from timeout/restart.
- **App.xaml.cs**: Passed `appOptions` into `HomePage` constructor
- **HomePage.xaml.cs**: Updated constructor to accept `appOptions`. Passed `appOptions` into `LoginPage`
- **LoginPage.xaml.cs**: Updated constructor to accept `appOptions`. Passed `appOptions` into `TwoFactorPage` and added two helpers for moving to next page.
- **LoginPageViewModel.cs**: Added `StartTwoFactorAction` and `LoggedInAction` properties and invoked during page change.
- **TwoFactorPage.xaml.cs**: Updated constructor to accept `appOptions` and init `storageService`. Added helper for moving to next page.
- **TwoFactorPageViewModel.cs**: Added `TwoFactorAction` property and …

[Autofill] Apply locked autofill flow to logged out state

---

src/Core/Services/CipherService.cs

Consider default URI match type selected on settings when filtering the entries to show on autofill.

[FIX] Consider default URI match type on filtering

---

src/Android/Receivers/LockAlarmReceiver.cs
src/App/App.xaml.cs
src/App/Pages/Settings/SettingsPage/SettingsPageViewModel.cs
src/App/Services/MobileStorageService.cs
src/App/Utilities/AppHelpers.cs
src/Core/Abstractions/ITokenService.cs
src/Core/Abstractions/IVaultTimeoutService.cs
src/Core/Constants.cs
src/Core/Services/CryptoService.cs
src/Core/Services/TokenService.cs
src/Core/Services/VaultTimeoutService.cs
src/Core/Utilities/ServiceContainer.cs
src/iOS/AppDelegate.cs

> Prepare the service/dependent application layers for using new `VaultTimeout` logic to include logging out during timeout.
- **LockAlarmReceiver.cs**: Updated call to use refactored name `CheckVaultTimeoutAsync`
- **App.xaml.cs**: Updated Constants key reference to `VaultTimeoutKey`
- **SettingsPageViewModel.cs**: Updated Constants key reference to `VaultTimeoutKey`.  Added placeholder for new `SetVaultTimeoutOptionsAsync` method.
- **MobileStorageService.cs**: Added new action key to `preferenceStorageKeys`.
- **AppHelper.cs**: Updated Constants key reference to `VaultTimeoutKey`.  Added default value for `VaultTimeoutActionKey` and set it to `lock`
- **ITokenService.cs**: Added `ToggleTokensAsync` method reference
- **IVaultTimeoutService.cs**: Name refactors `CheckVaultTimeoutAsync` …

[Auto-Logout] Update Service layer logic

---

src/Android/Accessibility/AccessibilityHelpers.cs
src/Android/Autofill/AutofillHelpers.cs
src/Android/Resources/xml/autofillservice.xml

This adds compatibility for Vivaldi Sopranos browser (following user request).
This one being pre-snapshot build for translators and Vivaldi team members.
Closes #673

Add support for Vivaldi Sopranos browser. Closes #673

---

store/google/Publisher/Program.cs

Per Google's recommendation, pad the HTTP request timeout when uploading APK/bundles to Play Store.  (Previous attempt to publish was met with `TaskCanceledException` - apparently the client defaults to 20 seconds)

Set Google publisher upload timeout to 3 minutes

---

src/Android/Services/DeviceActionService.cs

Previously a call to BiometricPrompt.AuthenticationCallback#OnAuthenticationFailed()
was treated as though an unrecoverable failure had occurred. However this is called on
each failed fingerprint match, for example, and is not a terminal failure. Now these
intermittent failures are ignored and a call to #OnAuthenticationError() is recognised
as an unrecoverable failure instead.
Fixes #791

Allow a BiometricPrompt to succeed after an initial failure

---

src/App/Utilities/AppHelpers.cs

Actionsheets cannot be programmatically dismissed, so instead we're checking the lock state before executing the selected action.  If the vault is locked, a simple "Vault is Locked" toast is shown, and the sheet is dismissed to make way for the unlock screen that is already visible.

Prevent actionsheet command execution if vault is locked

---

src/App/Pages/Vault/AddEditPage.xaml
src/App/Pages/Vault/AddEditPage.xaml.cs
src/App/Pages/Vault/AddEditPageViewModel.cs
src/App/Pages/Vault/CiphersPage.xaml.cs
src/App/Pages/Vault/CiphersPageViewModel.cs
src/App/Pages/Vault/GroupingsPage/GroupingsPage.xaml.cs
src/App/Pages/Vault/GroupingsPage/GroupingsPageListItem.cs
src/App/Pages/Vault/GroupingsPage/GroupingsPageViewModel.cs
src/App/Pages/Vault/ViewPage.xaml
src/App/Pages/Vault/ViewPage.xaml.cs
src/App/Pages/Vault/ViewPageViewModel.cs
src/App/Resources/AppResources.Designer.cs
src/App/Resources/AppResources.resx
src/App/Utilities/AppHelpers.cs
src/Core/Abstractions/IApiService.cs
src/Core/Abstractions/ICipherService.cs
src/Core/Abstractions/ISearchService.cs
src/Core/Enums/EventType.cs
src/Core/Models/Data/CipherData.cs
src/Core/Models/Domain/Cipher.cs
src/Core/Models/Response/CipherResponse.cs
src/Core/Models/View/CipherView.cs
src/Core/Services/ApiService.cs
src/Core/Services/CipherService.cs
src/Core/Services/SearchService.cs
src/iOS.Core/Views/ExtensionTableSource.cs
src/iOS/AppDelegate.cs

> Similar changes as the other clients, added Trash bin support, soft-delete and restore functions to the mobile app. Tested in iOS and Android emulators.
Sorry for the size of this one. PR from `soft-delete-init` to `soft-delete`.
- **/App/Pages/Vault/AddEditPage.xaml**:  When editing an item, only provide "soft-delete", relabeled as "Send to trash"
- **/App/Pages/Vault/AddEditPage.xaml.cs**:  See "AddEditPage.xaml" above
- **/App/Pages/Vault/AddEditPageViewModel.cs**:  Text changes for the prompt, "Send to trash" vs. "Delete"
- **/App/Pages/Vault/CiphersPage.xaml.cs**:  Treatment for handling the display of the trash bin vs. other normal folders/views including messaging
- **/App/Pages/Vault/CiphersPageViewModel.cs**:  See "CiphersPage.xaml.cs" above
- …

[Soft Delete] Added trash folder to mobile

---

src/Android/Accessibility/AccessibilityHelpers.cs
src/Core/Utilities/CoreHelpers.cs

Ran across an issue introduced by recent modifications where an expected failure did in fact, not fail, resulting in a 'no matches found' condition (calling `Uri.TryCreate` on a URL without a scheme worked, and passed along a scheme-less URI until it was rejected by subsequent code).
The solution (which lines up better with previous code) is to perform the http(s) scheme check / prefix creation _first_, and if not necessary _then_ fall back to attempting to create the URI with the string as-is.  This results in the scheme-less URI being properly prefixed with `http://`.  Also tested with the URLs fixed by our recent changes, and they still work properly.
I'm unsure why we didn't see this while testing the recent changes.  For reference, the uriString that exposed this was …

Additional URI parsing fix

---

src/Android/Accessibility/AccessibilityHelpers.cs

This adds **[Tor Browser](https://play.google.com/store/apps/details?id=org.torproject.torbrowser)**, **[Firefox Lite](https://play.google.com/store/apps/details?id=org.mozilla.rocket)** ¹ and **[Opera Mini Beta](https://play.google.com/store/apps/details?id=com.opera.mini.native.beta)** browsers to `AccessibilityHelpers.SupportedBrowsers`.
The resource-id value of these has been checked.
These three browser entries were missing there, see screenshot below:
_(**left:** `AutofillHelpers.{TrustedBrowsers+CompatBrowsers}` combined and sorted alphabetically **/** 
**right:** `AccessibilityHelpers.SupportedBrowsers` sorted alphabetically)_
___
¹ Formerly known as _Firefox Rocket_, this browser launched a few years ago, is the lite version of Firefox (approx. 6 MB), based on the Android WebView …

[Autofill - Browser lists] Accessibility Service: add Tor Browser, Firefox Lite and Opera Mini Beta

---

src/Android/Accessibility/AccessibilityHelpers.cs
src/Android/Autofill/AutofillHelpers.cs
src/Android/Resources/xml/autofillservice.xml

___
This adds compatibility for **[Avast Secure Browser](https://play.google.com/store/apps/details?id=com.avast.android.secure.browser)** (`com.avast.android.secure.browser`).
More info about it on [its Wikipedia page](https://en.wikipedia.org/wiki/Avast_Secure_Browser).
:heavy_check_mark: The resource-id value (`editor`) has been checked.
<details>
<summary>Read more ...</summary>
:arrow_right: `com.avast.android.secure.browser:id/` **`editor`**
</details>

Add support for Avast Secure Browser

---

src/Android/Accessibility/AccessibilityHelpers.cs
src/Android/Autofill/AutofillHelpers.cs
src/Android/Resources/xml/autofillservice.xml

___
This adds compatibility for **[GNU IceCat](https://f-droid.org/en/packages/org.gnu.icecat/)** (`org.gnu.icecat`), the [GNU version of the Firefox ESR browser](https://en.wikipedia.org/wiki/GNU_IceCat).
:heavy_check_mark: The resource-id value (`url_bar_title`) has been checked.
<details>
<summary>Read more ...</summary>
:arrow_right: `org.gnu.icecat:id/` **`url_bar_title`**
</details>

Add support for GNU IceCat

---

src/Android/Accessibility/AccessibilityHelpers.cs
src/Android/Autofill/AutofillHelpers.cs
src/Android/Resources/xml/autofillservice.xml

___
This adds compatibility for **[Tor Browser (Alpha)](https://play.google.com/store/apps/details?id=org.torproject.torbrowser_alpha)** (`org.torproject.torbrowser_alpha`).
:heavy_check_mark: The resource-id value (`url_bar_title`) has been checked.

Add support for Tor Browser (Alpha)

---

src/Android/Properties/AndroidManifest.xml

_... including "Pen Window" support, too._ :relaxed:
Long before Android natively supported multi-window management with Android 7.0, Samsung had launched its system. This PR allows Bitwarden to be compatible with this system, which can be used on some tablets but also on some large screen smartphones from the Samsung brand.
<details>
<summary>Read me ...</summary>
:arrow_right: This PR adds Bitwarden to this list (of compatible apps), allowing it to be used in split-screen mode. That is, typically, _left or right_ for **tablet**, _top or bottom_ for **smartphone**. But the very large tablets, typically 12" and more, allow the use of 4 simultaneous apps in the form of a 2x2 grid!
:arrow_right: **See these two official videos for use:** :clapper:
- [Samsung Galaxy Tab 4 | How To: …

Add support for Samsung "Multi Window" mode (Android < 7.0 users)

---

src/Android/Properties/AndroidManifest.xml

In the same vein as the support for [Samsung "Multi Window" mode](https://github.com/bitwarden/mobile/pull/877), this adds support for **LG "Dual Window" mode** (for Android < 7.0 users).
<details>
<summary>Read more ...</summary>
Long before Android natively supported multi-window management with Android 7.0, LG had launched its system. This PR allows Bitwarden to be compatible with this system, which can be used on some tablets but also on some large screen smartphones from the LG brand.
This PR adds Bitwarden to the list of compatible apps, allowing it to be used in split-screen mode. That is, typically, _left or right_ for **tablet**, _top or bottom_ for **smartphone**. Just press and hold the Bitwarden icon (located in the dedicated area) and drag and drop it to the desired side of …

Add support for LG "Dual Window" mode (Android < 7.0 users)

---

src/Android/Accessibility/AccessibilityHelpers.cs
src/Android/Accessibility/AccessibilityService.cs
src/Android/Accessibility/KnownUsernameField.cs
src/Android/Android.csproj

Accessibility:  Added support for establishing a username field without the presence of a password field, or for overriding a username field with a different one (think github homepage user/email/pass form).  As there doesn't appear to be a reliable way to make this work automagically, this takes the manual route where we simply maintain a list of sites and their corresponding username field IDs.
I opted not to use the entire URI as some of the variations were endless depending on locale, continuation path args, etc.  So we're keying off the authority and the end of the path to establish a site & page match, then on the view ID for a username field match.
Additional data was needed earlier in the process to establish the username field, so some operations were shuffled around to prevent …

Support for establishing a username field without a password field

---

src/Android/Accessibility/AccessibilityHelpers.cs
src/Android/Autofill/AutofillHelpers.cs
src/Android/Resources/xml/autofillservice.xml

___
This adds compatibility for **[AVG Browser](https://play.google.com/store/apps/details?id=com.avg.android.secure.browser)** (`com.avg.android.secure.browser`).
:heavy_check_mark: The resource-id value (`editor`) has been checked.
<details>
<summary>Read more ...</summary>
:arrow_right: `com.avg.android.secure.browser:id/` **`editor`**
Very similar to [Avast Secure Browser](https://play.google.com/store/apps/details?id=com.avast.android.secure.browser) (recently committed from [this PR](https://github.com/bitwarden/mobile/pull/874)).
This is because **AVG** has been a subsidiary of **Avast** since [its acquisition](https://press.avast.com/avast-closes-acquisition-of-avg-technologies) by the latter in 2016. For information, the two browsers were released the same day on the Play Store …

Add support for AVG Browser

---

src/App/Pages/Settings/AccessibilityServicePage.xaml

Adjusted layout and logic of accessibility settings to better match the cleaner autofill service settings.  Screenshots from Nexus 5X to demonstrate with space restrictions:
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

Usability improvements to accessibility settings

---

src/App/Resources/AppResources.af.resx
src/App/Resources/AppResources.de.resx
src/App/Resources/AppResources.es.resx
src/App/Resources/AppResources.et.resx
src/App/Resources/AppResources.fa.resx
src/App/Resources/AppResources.fi.resx
src/App/Resources/AppResources.hu.resx
src/App/Resources/AppResources.id.resx
src/App/Resources/AppResources.it.resx
src/App/Resources/AppResources.ko.resx
src/App/Resources/AppResources.nb.resx
src/App/Resources/AppResources.ro.resx
src/App/Resources/AppResources.sk.resx
src/App/Resources/AppResources.th.resx
src/App/Resources/AppResources.vi.resx
src/App/Resources/AppResources.zh-Hans.resx

I fixed a typo in the `PINRequireMasterPasswordRestart` popup message. It was present in all languages.

fix typo in PINRequireMasterPasswordRestart

---

src/App/App.xaml.cs
src/App/Pages/Accounts/TwoFactorPage.xaml.cs

**TwoFactorPage.xaml.cs** - The focus request would only ever happen once since it was behind the `!_inited` condition.  Changed this to always perform the focus request in `OnAppearing()` while only restricting `_vm.Init()` to the `!_inited` condition.  Fixes #905 
**App.xaml.cs** - removed the workaround added mid-December.  The Xamarin.Forms issue linked was closed on Feb 11, and the Forms updates since then were no longer reacting well to the workaround, resulting in what appeared to be an empty instance of the lockPage instead of the one already available.  Fixes #906

lock screen drawing & 2FA entry bugfixes

---

src/App/App.xaml.cs
src/App/Pages/Accounts/TwoFactorPageViewModel.cs

Confirmed this is no longer necessary with the version of Forms we're using.  (Flow is also snappier without the hack, making for an improved experience)

Removal of lifecycle hack for 2FA resume flow

---

src/Android/Renderers/CustomEditorRenderer.cs

Workaround provided by Xamarin team for allowing long-press-in-editor-within-scrollview system prompts to appear (copy/paste/etc).  Fixes #747

Workaround for pasting into editor within scrollview

---

src/Android/Accessibility/AccessibilityHelpers.cs
src/Android/Autofill/AutofillHelpers.cs
src/Android/Resources/xml/autofillservice.xml

___
- adds compatibility for **[Privacy Browser (Free)](https://play.google.com/store/apps/details?id=com.stoutner.privacybrowser.free)** (`com.stoutner.privacybrowser.free`) and
- adds compatibility for **[Privacy Browser (Standard)](https://play.google.com/store/apps/details?id=com.stoutner.privacybrowser.standard)** (`com.stoutner.privacybrowser.standard`).
&nbsp;
:heavy_check_mark: The resource-id value (`url_edittext`) has been checked.
:arrow_right: Only on the **Free** version though.
:arrow_right_hook: But is more than certainly the same on the **Standard** version, the latter being mainly a paid ad-free version. See the `Privacy Browser Free Advertisements` section of their [Privacy Policy](https://www.stoutner.com/privacy-browser/privacy-policy/) page.
&nbsp;
<details> …

Add support for Privacy Browser (Free/Standard). Closes #407

---

src/Android/Accessibility/AccessibilityHelpers.cs

This adds a comment clarifying that the second entry of the resource-id value for "Adblock Browser" is not another current possibility, but an entry kept for reasons of compatibility with the previous versions (those before version 2 — _which were based on Firefox for Android_).
:arrow_right: This entry can therefore be safely withdrawn in the future. :heavy_check_mark:

Adblock Browser: clarification

---

src/Android/Accessibility/AccessibilityHelpers.cs

This fixes support for (new versions of) **Firefox Nightly for Developers** (see [here](https://play.google.com/store/apps/details?id=org.mozilla.fennec_aurora&hl=en) and [here](https://f-droid.org/en/packages/org.mozilla.fennec_fdroid/)). :heavy_check_mark:
<details>
<summary>View me ...</summary>
&nbsp;
</details>
<details>
<summary>View me ...</summary>
</details>

Fix support for "Firefox Nightly for Developers"

---

src/Android/Accessibility/AccessibilityHelpers.cs

My mistake: `org.mozilla.fennec_fdroid` is not an "F-Droid version of Firefox Nightly for Developers". This corrects my error.

Partial revert of "Fix support for Firefox Nightly for Developers"

---

src/Android/Accessibility/AccessibilityHelpers.cs

This fixes support for (new versions of) [Firefox Beta](https://play.google.com/store/apps/details?id=org.mozilla.firefox_beta). :heavy_check_mark:
<details>
<summary>View me ...</summary>
&nbsp;
</details>
<details>
<summary>View me ...</summary>
</details>

Fix support for Firefox Beta

---

src/Android/Accessibility/AccessibilityHelpers.cs

The resource-id value progressively goes from `url_bar_title` to `mozac_browser_toolbar_url_view` in Firefox browsers.
In the order of their appearance, it seems to be: `org.mozilla.fenix.nightly` **->** `org.mozilla.fenix` and then `org.mozilla.fennec_aurora` **->** `org.mozilla.firefox_beta`.
:arrow_right_hook: We can therefore easily deduce that the next on the list will be `org.mozilla.firefox` very soon<sup>*</sup>.
This PR adds this new resource-id value:
- for `org.mozilla.firefox` _in anticipation_ (this is specified) and
- for some Firefox forks<sup>*</sup> _in anticipation_ (also specified).
Ideally, a swapping of the two entries of these resource-id values will be done when the time comes; `url_bar_title` becoming Legacy.

Early support for future versions of Firefox (+ some forks)

---

src/App/Services/MobileStorageService.cs
src/Core/Services/LiteDbStorageService.cs
src/Core/Utilities/ServiceContainer.cs

LiteDB broke something in latest update. We now need to properly dispose of the database object or we get exceptions on file locking when trying to re-construct.

Dispose of LiteDatabase instance

---

src/App/App.xaml.cs
src/App/Pages/Settings/SettingsPage/SettingsPageViewModel.cs
src/Core/Services/VaultTimeoutService.cs

> Make sure that the `lock` option is the default value even if the setting has not been explicitly set and/or the app is updated instead of cleanly installed.
- **App.xaml.cs**: Changed conditional logic to make lock option the default action
- **SettingsPageViewModel.cs**: Added default for `lock` if saved action was null
- **VaultTimeoutService.cs**: Changed conditional logic to make lock option the default action

[Auto Logout] Update lock option to be default value

---

src/App/Pages/Settings/ExportVaultPageViewModel.cs

Avoid Task.Result usage in application in apps with the UI thread, this can cause deadlocks, await a task instead.

Avoid Task.Result usage

---

src/App/App.xaml.cs
src/App/Models/AppOptions.cs
src/iOS.Autofill/CredentialProviderViewController.cs
src/iOS.Core/Services/DeviceActionService.cs
src/iOS.Extension/LoadingViewController.cs

- Rename EmptyApp option to IosExtension since that's what it's really for
- Add IosExtension check to SupportsNfc checks

check app options ios extension on nfc check

---

src/Core/Utilities/CoreHelpers.cs

When parsing a URL string that meets the proper format to construct a URL, but the hostname/host is malformed, you end up with an empty string for the hostname/host rather than `null`. We handle the `null` condition when comparing URLs for autofill, but not an empty string. This leads to two malformed hostnames/hosts being able to match `('' === '') == true`. This PR ensures that hostname/host parsing always treats an empty string the same as `null`.

check for empty string on malformed URL

---

src/App/Pages/Settings/SettingsPage/SettingsPageViewModel.cs
src/iOS.Core/Utilities/ASHelpers.cs
src/iOS/AppDelegate.cs

If users are using the vault timeout feature to log out of the app, the autofill index may not be cleared when they are logged out (ex, the app just terminates). This is because the traditional loggedout message event may never occur. I would consider this a security issue since it would lead to a logged out user still receiving hints in their keyboard about items that were in their vault. If a user is using the vault timeout == "logOut" feature, we cannot maintain the autofill index for keyboard hints.

Don't build the keyboard index for autofill if using logout action

---

src/Core/Core.csproj
src/Core/Services/LiteDbStorageService.cs

Use a static singleton instance of LiteDatabase instead of trying to manually dispose. This should get around the Lite Database file locking issue we have been experiencing and allow us to upgrade to the latest LiteDB version that we need to resolve other bugs.

Singleton LiteDatabase

---

src/Android/Accessibility/AccessibilityHelpers.cs
src/Android/Autofill/AutofillHelpers.cs
src/Android/Resources/xml/autofillservice.xml

There is a Chromium build with package name `org.bromite.chromium` with minimal patches which is used mostly to test whether issues come from upstream (Chromium) or are only in Bromite; see also https://www.bromite.org/chromium
This could be useful to test the Bitwarden integration as well.

Add support for Bromite's vanilla build of Chromium

---

src/iOS.Autofill/CredentialProviderViewController.cs
src/iOS.Autofill/SetupViewController.cs
src/iOS.Extension/LoadingViewController.cs

Replaced use of `GetAwaiter().GetResult()` within autofill and sharing extension view controllers, fixes frozen and/or partially drawn autofill windows when setting up and using autofill.
Before:
After:
Also fixed the dark-text-on-dark-background issue for the autofill setup completion header (now matches "success" color used in share extension)
Autofill:
Share:

Fix for deadlock in iOS autofill & share extensions

---

src/Android/Services/DeviceActionService.cs
src/App/Abstractions/IDeviceActionService.cs
src/App/App.xaml.cs
src/App/Pages/Accounts/LockPage.xaml
src/App/Pages/Accounts/LockPage.xaml.cs
src/App/Pages/Accounts/LockPageViewModel.cs
src/App/Pages/Settings/SettingsPage/SettingsPage.xaml.cs
src/App/Pages/Settings/SettingsPage/SettingsPageViewModel.cs
src/App/Resources/AppResources.Designer.cs
src/App/Resources/AppResources.resx
src/App/Services/MobilePlatformUtilsService.cs
src/Core/Abstractions/IVaultTimeoutService.cs
src/Core/Constants.cs
src/Core/Services/AuthService.cs
src/Core/Services/CryptoService.cs
src/Core/Services/VaultTimeoutService.cs
src/iOS.Core/Controllers/LockPasswordViewController.cs
src/iOS.Core/Services/DeviceActionService.cs

- Refactored code to use "biometric" terminology so it doesn't conflict with "fingerprint" (phrase)
- Removed native biometric code for Android 10 as the plugin handles it now
- Changed phrasing on Android to "Biometric Verification" as it's the system's responsibility to identify the method used.  Even though the Biometric API was added in Android 10, the BiometricPrompt API was added in 9 to cover for vendors introducing other methods (face, iris).  The system can do a better job of prompting the user than we can (see screenshots)
- iOS code remains mostly untouched
I'm hoping by removing any custom code we'll fix the fingerprint oddities we're seeing right now, as well as some labeling oddities for users running Anrdoid 9.

Biometrics cleanup

---

src/Android/Accessibility/AccessibilityHelpers.cs

Turns out that while `AccessibilityWindowInfo` was added in Android 5, `AccessibilityWindowInfo.Title` didn't show up until Android 7.  We recently added the `Title` check to prevent any drawing conflicts with autofill windows.  Changed to just skip the check outright until Android 8 (when autofill was introduced).

Fix for accessibility overlay on Android 5 & 6

---

src/Core/Models/Data/CipherData.cs

Resolves #973.
When a vault is synced, the content is stored using the `Data` models, since the fallback path relied on `CipherResponse` defaulting the value, this did not happen for content already synced. By adding a default value to `ViewPassword` in `CipherData` de-serialized objects will now default with `ViewPassword` enabled.
We need to keep the other fallback as well, since otherwise the `CipherData` will copy the `ViewPassword=False` from `CipherResponse`.

Resolve passwords being hidden in upgrade path

---

src/Core/Models/View/CipherView.cs

Resolve new ciphers defaulting to ViewPassword = false, causing passwords to be non editable.

Resolve passwords in new ciphers being disabled

---

.github/workflows/build.yml

Re-enabled `Decrypt secrets`, `Set up keychain`, and `Set up provisioning profiles` steps to allow iOS builds to succeed from non-master branches

Fix for non-master branch iOS builds

---

.github/workflows/build.yml
src/Android/Renderers/CustomEntryRenderer.cs

A workaround for disabling predictive text while editing visible password fields on Android (see code comments for details/links on what and why).  This should suffice until the Xamarin.Forms bug has been fixed:
https://github.com/xamarin/Xamarin.Forms/issues/10857

Workaround for disabling predictive text in visible password fields

---

src/Android/Accessibility/AccessibilityHelpers.cs

Currently, the [new system](https://github.com/bitwarden/mobile/pull/880) allowing "email/username" field detection without "password" field, which uses the accessibility service, only works well with some browsers like Chrome.
Indeed, if the subdomain is specific like `signin.`example.com: no problem!
But if it's `www.`example.com, Bitwarden (with current entries) will assume that the browser will hide this part for comparison. _(This is a new trend in browsers.)_
This is only the case in some browsers (currently: [Chrome](https://user-images.githubusercontent.com/4764956/86173097-bbf50a00-bb1f-11ea-8ee0-aa776e0c7b0c.png), [Firefox beta](https://user-images.githubusercontent.com/4764956/86173122-c6170880-bb1f-11ea-8fb1-cc9575e1a38b.png), etc.).
<details>
<summary>View me ...</summary> …

[KnownUsernameField] Compatibility with more browsers

---

src/Android/MainActivity.cs
src/App/Pages/Vault/AddEditPage.xaml.cs
src/App/Utilities/PermissionManager.cs

Permissions flow for Android was causing the white screen on initial permission grant on occasion. Moved permission grant to pre-TOTP page load. This resvoles #975 
**src/Android/MainActivity.cs** - ZXing.Net.Mobile.Forms.Android.PermissionsHandler.OnRequestPermissionsResult was deprecated, and with new flow, was hanging. I've modified this to point to the new method.
**src/App/Pages/Vault/AddEditPage.xaml.cs** - Added permissions check on click to confirm access to camera. If access is denied, return to add page.
**src/App/Utilities/PermissionManager.cs** - Added static method for checking/requesting permissions using Xamarin Essentials, for this use case and potential future consumption. 
* None known. Requesting a test on a physical device before merging with master to confirm. …

Modified Permissions Flow

---

src/App/Pages/Vault/ViewPage.xaml
src/Core/Models/View/LoginUriView.cs

Modify listing of URI to include port where applicable. Aligns with changes in jslib.
**src/Core/Models/View/LoginUriView.cs** View model changes. Hostname was no longer being used with this change, so replace Hostname with Host. 
**src/App/Pages/Vault/ViewPage.xaml** Presentation modification. Point to new property.

Modified listing of website from Hostname to Host

---

src/iOS.Core/Utilities/ASHelpers.cs

Prevent trashed credentials from being made available in iOS autofill. Didn't appear to be an issue on Android.
**src/iOS.Core/Utilities/ASHelpers.cs** - Was going to create a new service method that returned untrashed/undeleted credentials, but this seemed like the path of least resistance.
This will close #1014

Allow only non-deleted creds to be added to autofill

---

src/Android/Properties/AndroidManifest.xml

Fixes https://github.com/bitwarden/mobile/issues/1018 by forcing `installLocation` to `internalOnly` per [@mportune-bw 's comments](https://github.com/bitwarden/mobile/issues/1018#issuecomment-662485499)

Added android:installLocation=internalOnly to manifest

---

src/App/Pages/Generator/GeneratorHistoryPage.xaml
src/App/Pages/Vault/PasswordHistoryPage.xaml
src/App/Pages/Vault/ViewPage.xaml

According to: bitwarden/desktop#490
Replace the "copy value" icon with fa-clone.

Consistent: Replaced the clipboard icon with a clone icon to improve UX 

---

src/Android/Renderers/CustomEntryRenderer.cs

Fixes #1025 
Xamarin Forms handles the scenario where a Numeric keyboard type + IsPassword setting properly sets the native Android Input Type between Numeric vs. NumericPassword. This is overridden by BW's custom entry renderer's implementation which maps custom fonts and behavior for Android.
This change adds the scenario to handle a PIN style (numeric keyboard) which should be masked/password and can be toggled accordingly.

Fix Pin cannot be hidden after showing it #1025

---

src/Android/Accessibility/AccessibilityHelpers.cs
src/Android/Accessibility/KnownUsernameField.cs

**CONTEXT:** This is an update of [this new system](https://github.com/bitwarden/mobile/pull/880) _(system allowing "user ID" field detection — i.e. email/username/phone/whatever — without "password" field using the accessibility service)_.
**UPDATED:** Engine.
:arrow_right_hook: _Prerequisite for my next PR which concerns the **entries**._
___
&nbsp;
**This:**
- allows to have multiple pairs "path / username view ID" per domain;
- adds more advanced path support:
- in its case-sensitive version: `startswith:string`, `contains:string`, `endswith:string` and
- in its case-insensitive version: `istartswith:string`, `icontains:string`, `iendswith:string`.
&nbsp;
:bulb: About using `StringComparison.Ordinal` and `StringComparison.OrdinalIgnoreCase`, this is recommended for a variety of …

[KnownUsernameField] Engine update (make the system more flexible)

---

src/Android/Accessibility/AccessibilityHelpers.cs

**CONTEXT:** This is an update of [this new system](https://github.com/bitwarden/mobile/pull/880) _(system allowing "user ID" field detection — i.e. email/username/phone/whatever — without "password" field using the accessibility service)_.
**UPDATED:** Entries.
**RELATED:** https://github.com/bitwarden/mobile/pull/880#issuecomment-646830516
___
&nbsp;
&nbsp;
**This fixes support for:**
- [see post n°1 below] **Google**
**This adds missing OAuth support for:**
- [see post n°2 below] **PayPal**
**This adds support for:**
- [see post n°3 below] national + desktop **Amazon** — the latter uses a different value.
- [see post n°4 below] national **eBay**
- [see post n°5 below] **Atlassian**
- [see post n°6 below] **Bitly** — enterprise users.
- [see post n°7 below] **Tumblr**
- [see post n°8 …

[KnownUsernameField] Entries update (main ones)

---

src/Android/Services/BiometricService.cs

During testing I accidentally reversed the expected result from `ValidateIntegrityAsync`. (Emulator has issues with detecting biometric changes, so to verify the message I inverted the check)
Should solve https://github.com/bitwarden/mobile/pull/1026#issuecomment-672996129

Biometric integrity check always fails

---

src/Android/Accessibility/AccessibilityHelpers.cs

&nbsp;
As a reminder, `www.ebay.in` is the only one in the list — available in the footer of `www.ebay.com` — with `www.ebay.se` to have their domain name redirecting to `ebay.com`.
**But** unlike the `.se` where the `signin.ebay.se` does not exist or no longer exists, the `.in` still has it: `signin.ebay.in`. With a message indicating this **transition period**, though.
:arrow_right_hook: _Although inaccessible from the home page because now redirected to `in.ebay.com` (which uses `signin.ebay.com`)._
&nbsp;
&nbsp;
**Main URL:**
**Alternative URL:**
> To buy and sell on www.ebay.com or other eBay sites internationally, existing users can login using their credentials or new users can register an eBay account on ebay.in. **Kindly note you can no longer buy or sell on eBay.in.**
&nbsp; …

[KnownUsernameField] Fix for the special case "eBay India"

---

src/Android/Accessibility/AccessibilityHelpers.cs

- adds all missing entries for `Yandex`.
:arrow_right_hook: _(Exhaustive list of Yandex domain names obtained by contacting their support.)_
&nbsp;
&nbsp;
<details>
<summary>Part of mail 1 (list of Yandex TLDs) ...</summary>
&nbsp;
> Here is a list of all domain zones used by Yandex:
> az, co.il, com, com.am, com.ge, com.tr, ee, fi, fr, pl, ru, ua, by, kg, kz, lt, lv, md, tj, tm, uz
>
> If you have any questions, please contact us and we will try to help!
</details>
&nbsp;
<details>
<summary>Part of mail 2 (intercompatibility) ...</summary>
&nbsp;
> The user can log in to an account in any domain zone. In fact, the authorization requires only username, so you can enter with any email alias.
</details>
&nbsp;
<details>
<summary>Part of mail 3 (various) ...</summary>
&nbsp;
> **1) Just for …

[KnownUsernameField] Entries update (Yandex)

---

.github/scripts/android/deploy-play.ps1

Publish directly to internal test track to skip play store approval process for internal testers (artifact can then be manually promoted to alpha > beta > prod like before).  This should bring the testing experience up to speed with TestFlight for iOS (i.e. push code > ci build > immediate availability).
Edit: For clarification the signup process requires maintaining a list of the testers' email addresses, combined with each tester clicking a "join the program" from a page that only renders for them if they're on the list.  Nothing goes public until we push it.

publish to google play internal test track

---

src/iOS.Core/Services/BiometricService.cs

Fixed comparison of stored state string to use value instead of instance (manifested itself as a "biometrics changed, login with master password" error on lock screen)

Fix iOS biometric unlock

---

src/App/Pages/Generator/GeneratorPageViewModel.cs

Upon page creation, `SliderInputAsync()` was firing before `InitAsync()` which would overwrite any existing settings with defaults before the previously saved values could be loaded.  Simply blocking this by checking `_doneIniting` allows the saved values to be loaded first.  Fixes #1059 
Edit: Clarification - I should say `InitAsync()` is actually called first, but it calls `LoadFromOptions()` which sets `Length` which in turn calls `SliderInputAsync()` before `InitAsync()` is truly finished.  At the moment this happens there are two values which have not yet been loaded from options.  Which values?  You guessed it - `Capitalize` and `IncludeNumber` from the passphrase generator page.

fix for passphrase generator persistent settings

---

src/Core/Services/UserService.cs

Any checks to canAccessPremium will throw an exception when not authed since there is no token to reference. This stops it from even trying to access the token.
This is the same as https://github.com/bitwarden/jslib/pull/170

check authed before checking if token has premium

---

src/Android/Services/BiometricService.cs

Key generation seems to be failing on some devices (possibly those which were originally setup when only the fingerprint API was supported and were later upgraded to a version of Android that supported the biometric API).  We're allowing those to silently fail in order for biometrics to continue to function.

fix issue with biometric validation

---

src/iOS.Core/Services/BiometricService.cs

The EvaluatedPolicyDomainState can be null.
"This property returns a value only when the canEvaluatePolicy(_:error:) method succeeds for a biometric policy or the evaluatePolicy(_:localizedReason:reply:) method is called and a successful biometric authentication is performed. Otherwise, nil is returned."
https://developer.apple.com/documentation/localauthentication/lacontext/1514150-evaluatedpolicydomainstate
Might solve #1078 and #1055

Biometric Integrity crash fix on iOS

---

src/App/Pages/Accounts/LockPageViewModel.cs
src/Core/Services/CryptoService.cs

Fix for missing key issue when logging in with SSO with biometric unlock already enabled from previous login.
`LockPageViewModel`: Added check for existence of key before allowing biometric unlock.  This will force password unlock when logging in with SSO as a key has not yet been established.
`CryptoService`: Null check key before attempting Base64 conversion to prevent NPE when logging in with SSO if biometric unlock is already enabled

fix for sso login when bio unlock already enabled

---

src/App/Pages/Accounts/LockPage.xaml
src/App/Pages/Accounts/LockPageViewModel.cs
src/iOS.Core/Controllers/LockPasswordViewController.cs
src/iOS.Core/Utilities/ThemeHelpers.cs

- Added check for biometric integrity when unlocking vault within iOS extensions
- Removed `Unlock with [touchId/faceId/biometric]` button and added alert text to extension if integrity check fails
- Also removed same bio unlock button from unlock screen in app if integrity check fails, for consistency across platforms
- Added check for crypto key in iOS extension to verify if bio unlock is possible (for SSO login)

biometric integrity check in iOS extensions

---

src/App/Controls/ExtendedSearchBar.cs

Search bar text color was not taking app theme into account (only system theme) so a light system with dark app theme resulted in dark text on a dark background.  By using themehelper here we take both the app and system theme into account.

fix issue with search bar color on iOS

---

src/App/Pages/Vault/AddEditPage.xaml

Removed Keyboard="Numeric" property from CardNumberEntry. European debit card numbers are alphanumeric. See also https://en.wikipedia.org/wiki/International_Bank_Account_Number.

Allow alphanumeric card numbers

---

src/Android/Android.csproj
src/Android/Renderers/CustomTabbedRenderer.cs

Added support for tab button re-selection in Android to match behavior from iOS, enabling the user to return to the vault root `GroupingsPage` from within a Type page (Login, Card, etc.) simply by tapping `My Vault` again.  Since we're using bottom-nav a little extra song and dance was required to get ahold of the view and set the listener.

re-select support for android tabbed page buttons

---

src/Android/Accessibility/AccessibilityHelpers.cs
src/Android/Autofill/AutofillHelpers.cs
src/Android/Resources/xml/autofillservice.xml

Closes #1105  (issue I recently created). [Iceraven ](https://github.com/fork-maintainers/iceraven-browser)is a Firefox Android fork

Add support for Iceraven browser

---

src/Android/Services/BiometricService.cs
src/Core/Abstractions/IBiometricService.cs
src/iOS.Autofill/LockPasswordViewController.cs
src/iOS.Core/Controllers/LockPasswordViewController.cs
src/iOS.Core/Services/BiometricService.cs
src/iOS.Extension/LockPasswordViewController.cs

iOS extensions are returning a different biometric state from the main app (derived from bundle ID):
https://developer.apple.com/forums/thread/70570
This PR adds support for performing integrity validation based on the source of the query (extension vs app).  Unfortunately this means both the extension(s) and the main app will have to re-enter the password for verification after a change in biometric integrity, independent of each other.  Not an ideal experience, but since an integrity change shouldn't happen frequently I believe this is our best course of action.

Support for storing multiple biometric integrity states for iOS

---

src/App/Pages/Accounts/LoginSsoPage.xaml.cs
src/App/Pages/Accounts/SetPasswordPage.xaml.cs
src/App/Pages/Accounts/SetPasswordPageViewModel.cs
src/App/Pages/Accounts/TwoFactorPage.xaml.cs
src/Core/Models/Request/SetPasswordRequest.cs

> Currently, when a new bitwarden/org user is created, they are given a status of `accepted`.  This can create issues for organizations trying to `confirm` the same user (which can't happen until they've set their master password). To alleviate the issue, change new user's `orgUser` status to `invited` until after they've set a master password. Pass through the necessary information for the `2fa` and `set-password` components.
- **LoginSsoPage.xaml.cs**: Passed already existing `_vm.orgIdentifier` into the constructor for both the `2fa` and `SetPassword` pages.
- **SetPasswordPage.xaml.cs**: Added `orgIdentifier` to the constructor. Saved parameter value to the underlying view model.
- **SetPasswordPageViewModel.cs**: Created `OrgIdentifier` property and assigned value to the …

[SSO] New user provision flow

---

src/Android/Accessibility/AccessibilityHelpers.cs

- switches the order of priority "Fennec,Fenix" to "Fenix,Fennec" for `org.mozilla.firefox` (+ for some Firefox forks which have already switched to a Fenix base).
&nbsp;
<details>
<summary>Read more …</summary>
```bash
$ strings -f *.apk | egrep "url_bar_title|mozac_browser_toolbar_url_view"
com.qwant.liberty_40000271_apps.evozi.com.apk: mozac_browser_toolbar_url_view
org.mozilla.fennec_fdroid_811320.apk: mozac_browser_toolbar_url_view
org.mozilla.firefox_81.1.4-2015768387_minAPI21(arm64-v8a)(nodpi)_apkmirror.com.apk: mozac_browser_toolbar_url_view
org.torproject.torbrowser_alpha_10.0a8_(81.1.2-Beta)-2015713931_minAPI21(arm64-v8a)(nodpi)_apkmirror.com.apk: mozac_browser_toolbar_url_view
```
New resource-id used since v79 ([1](https://user-images.githubusercontent.com/4764956/96039124-778c …

Firefox (+ some forks): switch resource-id priority order

---

src/Android/Accessibility/AccessibilityHelpers.cs
src/Android/Autofill/AutofillHelpers.cs
src/Android/Resources/xml/autofillservice.xml

- updates support for **Ungoogled Chromium** browser.
- keeps (for a few months)  `org.ungoogled.chromium` with the comment `// [DEPRECATED]`;
- adds `org.ungoogled.chromium.stable`, but also `org.ungoogled.chromium.extensions.stable` (see [their CHANGELOG](https://git.droidware.info/wchen342/ungoogled-chromium-android/src/commit/1812d0258510535da8406ea0e39cdd0c26a21342/CHANGELOG.md) regarding this).
&nbsp;
Fixes #1118

Update support for Ungoogled Chromium browser. Fixes #1118

---

src/Android/Accessibility/AccessibilityHelpers.cs

- adds support for alternative access for **NTT DOCOMO** _(KnownUsernameField > Top 20 Japan)_.
&nbsp;
<details>
<summary>View me ...</summary>
</details>

[KnownUsernameField] Entries update (Top 20 JP enhancement)

---

src/iOS.Autofill/CredentialProviderViewController.cs
src/iOS.Autofill/LockPasswordViewController.cs
src/iOS.Autofill/LoginAddViewController.cs
src/iOS.Autofill/LoginListViewController.cs
src/iOS.Autofill/LoginSearchViewController.cs
src/iOS.Autofill/PasswordGeneratorViewController.cs
src/iOS.Autofill/SetupViewController.cs
src/iOS.Core/Controllers/ExtendedUITableViewController.cs
src/iOS.Core/Controllers/ExtendedUIViewController.cs
src/iOS.Core/Views/CustomPresentationControllerDelegate.cs
src/iOS.Core/iOS.Core.csproj
src/iOS.Extension/LoadingViewController.cs
src/iOS.Extension/LockPasswordViewController.cs
src/iOS.Extension/LoginAddViewController.cs
src/iOS.Extension/LoginListViewController.cs
src/iOS.Extension/PasswordGeneratorViewController.cs
src/iOS.Extension/SetupViewController.cs

On iOS 13+ the extension modals are displayed as sheets which enables the user to swipe them away as a method of cancelation.  We have varying levels of logic attached to our cancel buttons that was not firing when the user swiped the sheet(s) away, resulting in an un-dismiss-able sheet that requires the app that triggered it to be killed.  This PR attaches a delegate to each view controller to capture a dismiss-by-swipe event and fire off the same code used by the cancel buttons.  Viola, no more frozen treats!  According to Apple this callback only fires on dismiss-by-swipe, so using the cancel button won't result in code being executed twice.

fix for stuck extension sheets when dismissed by swipe

---

src/iOS/Info.plist

Apparently this key was deprecated and is no longer necessary (confirmed via simulator test on all versions back to iOS 10).  The presence of the key is preventing publishing, so away it goes.

Remove deprecated info.plist key

---

src/App/Pages/Accounts/RegisterPage.xaml
src/App/Pages/Accounts/RegisterPageViewModel.cs
src/App/Resources/AppResources.Designer.cs
src/App/Resources/AppResources.resx

> In order to complete GDPR compliance, moving forward with new user creation, we need to have explicit user interaction for Terms of Service and Privacy Policy acknowledgement.
- **RegisterPage.xaml**: Added UI for terms/privacy acknowledgement. Created formatted label text with spannable selectors for each of the policies. Use specialized margin based on platform.
- **RegisterPageViewModel.cs**: Added variables for `ShowTerms`, `AcceptPolicies`, and created `PoliciesClickCommand` for opening URIs. Added `Submit` logic. Added getter property to handle switch margin based on platform.
- **AppResources.resx**: Added strings. Note: formatting for the `AcceptPolicies` string looks weird, but is necessary because of the intentional line break (xml:preserve takes the string as is).

[GDPR] Adjusted TOS/Privacy acceptance

---

src/App/Pages/Accounts/RegisterPage.xaml
src/App/Styles/Black.xaml
src/App/Styles/Dark.xaml
src/App/Styles/Light.xaml
src/App/Styles/Nord.xaml

> Hyperlinks needs to be updated with proper theming
- **RegisterPage.xaml**: Adjusted `TextColor` to use static resource colors established in all themes
- **Styles**: Added `HyperlinkColor` that mimics existing color schemes
Shoutout to @vachan-maker for the heads up 👍

[GDPR] Updated privacy policy links for theming

---

src/Core/Models/Request/CipherRequest.cs
src/Core/Services/CipherService.cs

This is a companion PR to API changes found in bitwarden/server#994
* **CipherRequest.cs**: Add revision date to request model for validation.
* **CipherService.cs**: Include revision date in encryption of ciphers so it can be included in the request model.

Include revision date in cipher requests

---

src/App/Resources/AppResources.Designer.cs
src/App/Resources/AppResources.resx
src/App/Services/MobileStorageService.cs
src/Core/Constants.cs
src/iOS.Autofill/LockPasswordViewController.cs
src/iOS.Core/Controllers/LockPasswordViewController.cs
src/iOS.Core/Services/BiometricService.cs
src/iOS.Extension/LockPasswordViewController.cs

A path was discovered where a user could modify biometric credentials on an iOS device then bypass the Bitwarden integrity check by using the autofill extension.
Reason: While the extensions do properly perform the integrity check per #1110 , the check would fail to catch the change **only if the extension had yet to be triggered once biometric unlock was enabled within the app**  (because the very first check results in a null value, then updates to the current integrity key value and returns true to indicate success - see [BiometricService line 39](https://github.com/bitwarden/mobile/blob/e27370cf32ece73ba44d7eadd6aebf519d82fdce/src/iOS.Core/Services/BiometricService.cs#L39)).
_Solution Part 1_: By performing the check regardless of the biometric unlock setting in the app, the null …

Fix for missing biometric integrity check in iOS extensions under certain conditions

---

src/Core/Abstractions/IUserService.cs
src/Core/Models/Response/IdentityTokenResponse.cs
src/Core/Services/UserService.cs

This fixes the issue where the app would throw if the value was missing as it was stored as zero instead of null.  The result is now an invalid password prompt on unlock instead of crashing (bringing mobile to parity with other clients).

Make KdfIterations nullable

---

src/Android/Receivers/ClearClipboardAlarmReceiver.cs

Per #1165, on Android 11 the Google Keyboard will suggest passwords copied to the clipboard even after they have been cleared by Bitwarden.
This is because the latest suggestion is not updated after the primary text on the clipboard is set to an empty string. The suggestion is removed correctly if the clipboard clear text is a space instead. Using a space to clear the clipboard matches the behavior of the Chromium browser extension.
This is what the suggestion looks like after Bitwarden has set the text in the clipboard to a space.

Change text for clearing a clipboard to a space instead of an empty string on Android

---

src/Android/Autofill/AutofillService.cs
src/App/Pages/Vault/AddEditPageViewModel.cs
src/App/Resources/AppResources.Designer.cs
src/App/Resources/AppResources.resx
src/Core/Enums/PolicyType.cs
src/Core/Models/Data/OrganizationData.cs
src/Core/Models/Domain/Organization.cs
src/Core/Models/Response/ProfileOrganizationResponse.cs

> Allow organizations to restrict user's from saving added/cloned items to their personal vaults. Remove the personal ownership option when this policy is enabled and the user is not an Admin/Owner of the organization.
- **Android/AutofillService**: Added checks to prevent user's from being able to auto-fill/save new logins (defaults to personal ownership, otherwise)
- **AddEditPageViewModel**: Added `PolicyService` to constructor. Added logic during construction of personal ownership list to remove the personal ownership option if necessary. **Note**: ran into a special use case where the list of collections was not being updated when defaulting to an organization because of the personal ownership policy. If the `OwnershipOrgIndex` remained at position 0, the change detection would not …

[Policy] Personal Ownership

---

src/Android/MainActivity.cs
src/Android/Services/DeviceActionService.cs
src/App/Abstractions/IDeviceActionService.cs
src/App/App.xaml.cs
src/App/Pages/BaseContentPage.cs
src/App/Services/MobilePlatformUtilsService.cs
src/Core/Abstractions/IPlatformUtilsService.cs
src/Core/Services/VaultTimeoutService.cs
src/iOS.Core/Services/DeviceActionService.cs
src/iOS.Core/Utilities/iOSHelpers.cs
src/iOS/AppDelegate.cs

Protects the vault-timeout from clock changes by using a monotonic clock, validated on app resume. *
Android made this super easy.  iOS required a hack is required to get trustworthy values - instead of a timestamp in seconds we get a difference in seconds between now and the boot time, resulting in a duration that includes sleep time.  As both of those values are susceptible to clock changes in the same manner, the difference between them will be fixed, resulting in an anchored and forward-moving value that can be used as a monotonic clock.
* Unless I'm missing something @kspearrin this can replace the timers on both platforms.  I can remove them outright if you agree.

Use monotonic clock for vault timeout

---

src/Android/MainApplication.cs
src/Core/Services/LiteDbStorageService.cs
src/iOS.Core/Utilities/iOSCoreHelpers.cs

Our DB library currently does not support shared connections across processes on Xamarin.iOS.  This limitation manifests itself in our app as new or modified ciphers missing from autofill.  We didn't discover this until after we enhanced our cipher caching mechanism **[here](https://github.com/bitwarden/mobile/pull/1112),** when it became apparent the DB was keeping it's own cache and not recognizing modifications made by another process.
This workaround, while heavy-handed, allows our enhanced caching to function as originally intended by spinning up and disposing a DB connection for every R/W operation, giving the access layer the latest data to work with regardless of which process wrote it.  Initial tests show no noticeable reduction in performance using test vaults of 1000+ ciphers. …

Workaround for lack of shared DB support

---

src/Core/Services/ExportService.cs

I missed the top-level `encrypted: true` hint on my first pass. Thanks to @kspearrin for pointing this out. Test encrypted exports now import correctly through web vault.
* **ExportService.cs**: Add Encrypted properties to jsonDoc objects. Note, these are lowercased by the `CamelCasePropertyNamesContractResolver` call.

Add encrypted hint json property

---

src/App/Pages/Settings/ExportVaultPage.xaml
src/App/Pages/Settings/ExportVaultPageViewModel.cs
src/App/Resources/AppResources.Designer.cs
src/App/Resources/AppResources.resx

We decided with the subtle change between export warnings to use a confirmation popup to warn about the failings of each export type. 
This PR removes the view's warning message and renders it as a popup after the master password has been confirmed.  Ialso inverted the password `if/else` to minimize nesting.

Show vault export warning as popup

---

src/Android/Accessibility/AccessibilityHelpers.cs

Related to #1021. 
Browsers are moving away from displaying URI scheme in a way accessibility can easily grab. This causes this URI healing to be relied upon more frequently. It should attempt https prior to http due to prevelence of https and security concerns with passwords over http.
* **AccessibilityHelpers.cs**: This helper is responsible for grabbing the Uri out of  a browser's address node. If a URI scheme isn't present, it heals the URI with `https://`.  It seems unlikely that any URI that isn't healed by `https://` would be by prepending `http://`, but the attempt isn't very expensive.

Attempt URI healing with https prior to http

---

src/App/App.xaml.cs

A condition force to not show the auto biometric prompt (https://github.com/bitwarden/mobile/issues/1045).
This condition don't change the case about when you lock manually the vault from settings page or app bar, because the value of the function parameter is false in those cases, and the prompt is not shown, as expected.
However, in the case that the vault is not locked and you hit the home button or when you lock the phone screen, the value of the function parameter is true, and the condition set it on false, then the prompt will not be shown when you'll access back to the app. Whatever vault timeout selected, it's happen when the vault timed out. When it sets to "Immediatly" this behavior is annoying when you want to switch to another app and go back to it.
<details>
<summary>GIF …

Fix auto biometric prompt on vault timeout

---

src/Android/Accessibility/AccessibilityHelpers.cs
src/Android/Autofill/AutofillHelpers.cs
src/Android/Resources/xml/autofillservice.xml

- switches the order of priority "Fennec,Fenix" to "Fenix,Fennec" for `org.torproject.torbrowser` (see their [blog post](https://blog.torproject.org/new-release-tor-browser-1003) and annex 1 below).
- adds a precision about the non-presence in this list of `com.android.htmlviewer` (entry added by @stevenlele in [this PR](https://github.com/bitwarden/mobile/pull/1121)).
- removes the deprecated `org.ungoogled.chromium` as planned [here](https://github.com/bitwarden/mobile/pull/1119);
- removes unnecessary precision about the version regarding some entries added by @stevenlele (for the sake of clarity, let's only add this information in the source code itself when more than one resource-id is present — typical case: current and legacy value).
&nbsp;
&nbsp;
___
<details>
<summary>Annex 1 …

[SupportedBrowsers] Small update

---

src/Core/Services/ExportService.cs

Do not export items that have been trashed. Related to [this community request](https://community.bitwarden.com/t/deleted-password-shows-up-in-vault-export/13246/14).
It seems like in the future we will want to optionally export trashed items with a flag showing they are trashed. However, this aligns closer to expected behavior for now.
* **ExportService.ce**: Filter all ciphers to include only those without `DeletedDate`s

Do not export items that have been deleted

---

src/App/Pages/Vault/AddEditPageViewModel.cs

> Cloning a cipher when personal ownership is not allowed would result in an unexpected experience with the ownership list (nothing would be selected, but the personal option would be removed).  Fix by adjusting logic for downstream changes in clone mode when personal ownership is not allowed.
- **AddEditPageViewModel**: Added explicit check for `null` Organization ID on the cipher being edited and if allowing personal ownership was disabled - if so, the cipher's Organization ID will be updated to the (first) organization enforcing this policy forcing the necessary downstream UI updates for ownership/collection(s)

[Bug] Clone personal ownership

---

src/App/Pages/Settings/ExportVaultPageViewModel.cs

Match jslib behavior to use `.json` as file extension for encrypted json export.
* **ExportVaultPageViewModel.cs**: detect encrypted fileFormat and set extension to just `.json`

Use .json extension for encrypted json export

---

src/Core/Abstractions/IApiService.cs
src/Core/Services/ApiService.cs
src/Core/Services/CipherService.cs

Related to https://app.asana.com/0/1169444489336079/1199337616674667/f
Related to bitwarden/web/issues/748
Related to bitwarden/server#1072
Allows edit of restored cipher without forced resync.
* **ApiService.cs**: Api now responds with updated Ciphers upon restore (bitwarden/server#1072)
* **CipherService.cs**: Update revision date to match the server's response.

Update revision date from server on restore

---

src/Android/Autofill/AutofillService.cs
src/App/Pages/Vault/AddEditPageViewModel.cs
src/Core/Enums/OrganizationUserType.cs
src/Core/Models/Data/OrganizationData.cs
src/Core/Models/Data/Permissions.cs
src/Core/Models/Domain/Organization.cs
src/Core/Models/Response/ProfileOrganizationResponse.cs

https://app.asana.com/0/1195018406457675/1153292148278664
As a user, I would like to be able to configure another user with access to manage user/group/collection assignment without being able to see organization passwords that are not directly assigned to them.
1. Implemented the Permissions object and Custom role type as seen in the server PR
2. Converted any existing role checks in the app to Permission checks that verify a `ValidRole || ValidPermission`

Implemented Custom role and permissions

---

src/Android/MainActivity.cs
src/Android/Services/DeviceActionService.cs
src/App/App.xaml.cs
src/App/Pages/BaseContentPage.cs
src/App/Services/MobileStorageService.cs
src/Core/Constants.cs
src/Core/Services/VaultTimeoutService.cs
src/iOS.Core/Services/DeviceActionService.cs
src/iOS.Core/Utilities/iOSHelpers.cs
src/iOS/AppDelegate.cs

This PR restores the vault timeout timer in Android in a way that coexists with the new locking mechanism, since we're unable to reproduce the failure of the new mechanism reported elsewhere.  It is my hope that we can remove the timer (again) once we're able to establish what is behind the failure on some devices.
Note that the restored timer is only utilized as a trigger (like before) but the actual time comparison is still using the new monotonic clock value.  If for some reason this still doesn't work, we can be reasonably sure that the problem lies with the returned value and not the way the lock trigger is fired.
Also changed:
- Normalized elapsed time to milliseconds instead of seconds so we can perform time checks with multiplication instead of division (Desperation Level 1)
- …

Restore vault timeout timer for Android

---

src/Core/Models/Data/OrganizationData.cs
src/Core/Models/Domain/Organization.cs
src/Core/Models/Response/ProfileOrganizationResponse.cs

Just as no boolean value should ever be nullable, so too should a collection of boolean values never be nullable
This fixes a bug in the Testflight release that was causing editing organization ciphers to crash the app.

null checked all the permissions

---

store/google/Publisher/Program.cs

F-Droid publishing was still unsuccessful, so testing google again this morning; will try other stuff if it continues to fail

revert "temporarily disable throwing on failure"

---

src/iOS.Core/Controllers/PasswordGeneratorViewController.cs
src/iOS.Core/Views/FormEntryTableViewCell.cs
src/iOS.Core/Views/PickerTableViewCell.cs

Fix #620: the iOS autofill and extension password generator does not give the user the options to generate a passphrase.
Edit: I also noticed that the "Avoid ambiguous characters" switch was missing when generating a password, so I added that control as well.
- add required controls and logic to `iOS.Core/Controllers/PasswordGeneratorViewController.cs`.
- add some event handlers to `FormEntryTableViewCell` and `PickerTableViewCell` so that we can regenerate the password when their value changes
- let developer specify a custom indentation for `FormEntryTableViewCell` objects - this is required to line it up with the other controls (not sure if there is a better way of doing this)
New passphrase controls:
Added "Avoid ambiguous characters" control (note that this now pushes the "Option …

Add passphrase generator to iOS Extensions

---

src/Android/MainActivity.cs
src/App/Pages/Accounts/TwoFactorPage.xaml.cs

Fix #769 and #350. Inserting a Yubikey via USB on the 2FA page will close the 2FA page and revert the user back to the initial welcome page. See example here: https://youtu.be/bKYIPMlMJVU
This actually happens on any of the pre-login pages, but obviously the 2FA page is the biggest concern.
Android apps use "Activity" objects to manage views and entry points into the app. Xamarin.Forms implements this by creating a single `MainActivity` to manage the app.
When certain configuration changes occur, Android rapidly destroys and recreates Activities to help them gracefully handle the configuration change. It is the app developer's responsibility to make sure that their Activities handle this lifecycle without loss of data or interruption to the user.
The problem is that plugging in a Yubikey …

Fix crash when using Yubikey via usb on Android

---

src/App/Pages/Accounts/TwoFactorPage.xaml
src/App/Pages/Generator/GeneratorPage.xaml
src/App/Pages/Send/SendAddEditPage.xaml
src/App/Pages/Send/SendAddEditPage.xaml.cs
src/App/Pages/Send/SendAddEditPageViewModel.cs
src/App/Pages/Settings/AutofillServicesPage.xaml
src/App/Pages/Settings/OptionsPage.xaml
src/App/Pages/Settings/SyncPage.xaml
src/App/Pages/Vault/AddEditPage.xaml
src/App/Pages/Vault/CollectionsPage.xaml
src/App/Pages/Vault/SharePage.xaml
src/App/Resources/AppResources.Designer.cs
src/App/Resources/AppResources.resx
src/App/Styles/Base.xaml

Additional adjustments based on [web PR 822](https://github.com/bitwarden/web/pull/822):
- Additional help text
- Replace Send type picker with segmented control (radio buttons can be iffy on mobile)
("copy on send" was already implemented as "share on send")

UX tweaks for Send

---

src/App/Controls/SendViewCell/SendViewCell.xaml
src/App/Pages/Send/SendAddEditPage.xaml
src/App/Pages/Send/SendAddEditPageViewModel.cs

- Added "disabled" state icon `fa-warning` in lieu of banner to save space in Sends list
- Swapped `File` and `Text` type buttons for new Sends
- Made `File` the default new Send type for premium users

Added disabled icon and make File default type for new Sends if premium

---

src/iOS.Core/Constants.cs
src/iOS.Extension/LoadingViewController.cs
src/iOS.Extension/LoginListViewController.cs

Fix #1035 - when using Chrome, the iOS Share Extension would not find any matching sites and would not autofill.
As discussed, Chrome does not support our `extension.js` script required for autofill operations. This also meant that the URL was being passed to the extension using an unexpected data type.
We discussed allowing the user to copy/paste their login info instead of autofilling. There is actually already code there to do that! However, my guess is that Chrome changed the `UTType` it was using to send the URL information to the extension, which meant the app wasn't catching the URL info and wasn't activating the copy/paste options.
With that in mind, the changes are actually very minor to get this to work properly:
* `Constants.cs` - add the identifier for the [URL …

Fix autofill on Chrome from the iOS Share Extension

---

src/App/Pages/Send/SendAddEditPage.xaml
src/App/Pages/Send/SendAddEditPage.xaml.cs
src/App/Pages/Send/SendAddEditPageViewModel.cs

- Fixed improper file field validation when editing a file Send
- Fixed "no file chosen" label after selecting file
- Fixed blank deletion date/time picker when current date is today or time is midnight
- Fixed all `Now` references to have minute-precision (strip seconds & milliseconds)
- Fixed `Name` field focus issue when switching between file and text types
- Moved `Name` field above Send type picker per discussion

Send bugfixes & tweaks

---

src/Android/Properties/AndroidManifest.xml

Added package visibility entries in the manifest so `Xamarin.Essentials.Browser` can open URLs on Android 11.
https://docs.microsoft.com/en-us/xamarin/essentials/open-browser?tabs=android

Fixed launch url on Android 11

---

src/App/Pages/Send/SendAddEditPage.xaml
src/App/Pages/Send/SendAddEditPage.xaml.cs
src/App/Pages/Send/SendAddEditPageViewModel.cs

Options section is collapsed by default when adding or editing Sends for simplification.
**Considerations:**
- `Share this Send upon save` switch is the last element before the Options panel (instead of the very end of the form) since the `Save` button on mobile is at the top.
- It's amazing how inconsistently apps us the "down" vs. "up" chevron to represent "expanded" vs. "collapsed".  I chose the "action to be performed when pressing this button" approach, so "down" is "collapsed".  I'm not super attached to it though if anybody has strong feelings otherwise.  (Some UIs show a right-facing chevron to indicate collapsed, but on mobile that can drive an expectation that we'll be taken to the "next screen", which isn't what we're doing here.  I'm probably overthinking it.)
**Screenshots:**

Expandable options for Add/Edit Send

---

src/App/Pages/Send/SendAddEditPage.xaml

Use primary color for Send Options "button" so it stands out in dark themes the same way as light themes.
**Screenshots:**

Use primary color for options label & chevron

---

src/Android/Renderers/SendViewCellRenderer.cs
src/Android/Resources/layout/SendViewCell.axml
src/App/Controls/SendViewCell/SendViewCell.xaml
src/App/Controls/SendViewCell/SendViewCell.xaml.cs
src/App/Controls/SendViewCell/SendViewCellViewModel.cs
src/App/Pages/Send/SendAddEditPage.xaml
src/App/Pages/Send/SendAddEditPage.xaml.cs
src/App/Pages/Send/SendAddEditPageViewModel.cs
src/App/Pages/Send/SendGroupingsPage/SendGroupingsPage.xaml
src/App/Pages/Send/SendGroupingsPage/SendGroupingsPage.xaml.cs
src/App/Pages/Send/SendGroupingsPage/SendGroupingsPageListItem.cs
src/App/Pages/Send/SendGroupingsPage/SendGroupingsPageViewModel.cs
src/App/Pages/Send/SendsPage.xaml
src/App/Pages/Send/SendsPageViewModel.cs
src/App/Resources/AppResources.Designer.cs
src/App/Resources/AppResources.resx
src/App/Utilities/AppHelpers.cs
src/Core/Enums/PolicyType.cs

**Overview**
Added support for disabling Send via enterprise policy.  Functionality is reduced to read and delete only.
_(Note that references to "options button" below is referring to the 3-dot overflow for each item in listviews, not the new expandable options button on the Send Add/Edit page)_
**Files Changes/Added**
Android:
- **SendviewCellRenderer.cs**: Support for toggling options button visibility, added missing disabled send icon
- **SendViewCell.axml**: Added missing disabled send icon
App:
- **SendviewCell.xaml**: Support for toggling options button visibility
- **SendViewCell.xaml.cs**: Support for toggling options button visibility
- **SendViewCellViewModel.cs**: Support for toggling options button visibility
- **SendGroupingsPage.xaml**: Support for toggling options button …

Support for Disable Send policy

---

src/App/Pages/Send/SendAddEditPageViewModel.cs
src/App/Pages/Send/SendGroupingsPage/SendGroupingsPage.xaml.cs

An Android-specific bug in Xamarin.Forms results in calling `OnAppearing` on a page when you exit and return to the app while a modal is showing, and it doesn't get called again when the modal is dismissed.  This results in new file Sends not showing up in the list since the file picker pushes the app to the background.  I'm using a simple broadcast message to refresh the list after saving is complete.

fix for send list refresh on android

---

src/Core/Models/Api/SendFileApi.cs
src/Core/Models/Data/SendFileData.cs
src/Core/Models/Domain/SendFile.cs
src/Core/Models/Request/SendRequest.cs
src/Core/Models/View/SendFileView.cs
src/Core/Services/SendService.cs
test/Core.Test/Models/Request/SendRequestTests.cs
test/Core.Test/Services/SendServiceTests.cs

Related to bitwarden/server#1175. Updates models to match new expected lack of URL in SendFile and file length hint in SendRequest.
* **SendFileApi.cs/SendFileData.cs/SendFile.cs/SendFileView.cs**: Remove Url
* **SendRequest.cs/SendService.csc** Add and populate FileLength hint on initial Send Request
* **Tests**: Populate File Length. Verifies SendRequest file length is correctly populated.

Send file model changes

---

src/Android/Android.csproj

Xamarin.Android 11.2 has finally been promoted to stable so this workaround is no longer necessary.  It also means:
- Debugging in Android 11 emulator is back to full speed
- No more 'removal of workaround' to debug on emulated Android versions < 11
Today is a good day - been waiting for this since October 👍

Removed fast deployment hack for Android 11 emulation

---

src/App/Pages/Send/SendGroupingsPage/SendGroupingsPage.xaml

There was a small but visible (on iOS) gap at the top of the Sends list when Send is _not_ disabled by org policy (so, when it's enabled normally).  `IsVisible` on the org policy warning banner was never moved to the wrapping `StackLayout` when it was added later.  Fixed.

fix for small gap at the top of send list when not disabled by policy

---

src/App/Pages/Vault/AddEditPageViewModel.cs

Fixed issue where users were unable to edit existing personal vault items while joined to an organization where personal vaults are prohibited.  Thanks to @vincentsalucci for key info.

Fix for editing existing personal vault items when non-personal org policy is active

---

src/App/Pages/Send/SendAddEditPage.xaml

- Added filesize to Send edit screen
- Removed "The file you want to send" text underneath filename on edit screen since you can't edit the file anyway (requires creating a new Send)

Added missing filesize on Send edit screen

---

src/App/Utilities/AppHelpers.cs

Fix for establishing Send url in cloud vs on-prem

fix for establishing Send url in cloud vs on-prem

---

src/App/Pages/Send/SendAddEditPageViewModel.cs
src/App/Resources/AppResources.resx

When creating a new Send, the DateTimes created from the "simple" picker were being set to midnight instead of the current time.  Not really a showstopper until "one hour" is selected, resulting in a DateTime from the past ([today] at midnight).  Some investigation revealed that modifying the 'DeletionDate' property bound to `ExtendedDatePicker` was triggering property changes multiple times within the picker and resetting the time to midnight.  Those custom pickers are no fun, so for safety/sanity during this release I've given the "simple" pickers their own "simple" DateTimes to modify, isolating them from the values bound to the custom pickers.  I will revisit this later to come up with something more elegant.
Edit: Forgot to mention also fixed a missing "Send" capitalization

Fix for incorrect deletion/expiration times during Send creation

---

src/Core/Services/SendService.cs

This should fix the issue where password protected Sends generated on mobile are failing to open.

use hardcoded kdfiterations for send passwords

---

src/Android/Accessibility/AccessibilityHelpers.cs

&nbsp;
- adds the freshly launched `amazon.pl` — see [the press release](https://www.aboutamazon.eu/press-release/amazon-pl-launches-in-poland). :bulb:
- adds the recently launched `amazon.se` — see [the press release](https://www.aboutamazon.eu/press-release/amazon-se-launches-in-sweden). :bulb:
&nbsp;
**Related:** https://github.com/bitwarden/server/pull/1219
&nbsp;
&nbsp;
<details>
<summary>Read me …</summary>
&nbsp;
**amazon.pl (desktop):**
```html
<input type="email" maxlength="128" id="ap_email" name="email" tabindex="1" class="a-input-text a-span12 auth-autofocus auth-required-field">
```
**amazon.pl (mobile):**
```html
<input type="email" maxlength="128" id="ap_email_login" placeholder="Adres e-mail (numer telefonu w przypadku kont mobilnych)" name="email" autocorrect="off" …
```

[KnownUsernameField] Entries update (Amazon)

---

src/App/Pages/Send/SendAddEditPage.xaml
src/App/Pages/Send/SendAddEditPageViewModel.cs
src/App/Resources/AppResources.Designer.cs
src/App/Resources/AppResources.resx
src/App/Utilities/AppHelpers.cs
src/Core/Enums/PolicyType.cs
src/Core/Models/Data/SendData.cs
src/Core/Models/Domain/Send.cs
src/Core/Models/Request/SendRequest.cs
src/Core/Models/Response/SendResponse.cs
src/Core/Models/View/SendView.cs
src/Core/Services/SendService.cs

Allow the creator of a Send to hide their email address from the recipient.
See the [web PR](https://github.com/bitwarden/web/pull/895) and [server PR](https://github.com/bitwarden/server/pull/1234) for more info and discussion.
* add "Hide my email address from recipients" toggle slider to the Send AddEdit page
* check and enforce new Send Options Policy > which can disable this new feature (`disableHideEmail`)
* add banner at the top of the Send AddEdit page if Send Options policy is in effect

Hide email address in Sends

---

src/App/Pages/Send/SendAddEditPage.xaml
src/App/Pages/Vault/AttachmentsPageViewModel.cs
src/App/Pages/Vault/ViewPageViewModel.cs
src/App/Resources/AppResources.resx
src/Core/Abstractions/IApiService.cs
src/Core/Abstractions/ICipherService.cs
src/Core/Abstractions/IFileUploadService.cs
src/Core/Models/Request/AttachmentRequest.cs
src/Core/Models/Response/AttachmentUploadDataReponse.cs
src/Core/Services/ApiService.cs
src/Core/Services/CipherService.cs
src/Core/Services/FileUploadService.cs
src/Core/Utilities/ServiceContainer.cs
test/Core.Test/AutoFixture/Cipher/CipherCustomizations.cs
test/Core.Test/Services/CipherServiceTests.cs

Commensurate PR with bitwarden/jslib#312.
Add the ability to direct upload to Azure or Bitwarden for cipher attachments. Increases size limit to 500MB.
* **SendAddEditPage/AttachmentPageView/AppResources**: Update max upload size to 500MB for both Send and Attachments.
* **ViewPageViewModel**: Cipher ID is needed for new download url request.
* **ApiService**: Direct upload endpoints for attachments. Similar to those for Send
* PostCipherAttachmentLegacy: The old attachment upload method
* PostCipherAttachmentAsync: New cipher attachment endpoint. Responds with instructions on how to upload the attachment file.
* PostCipherAttachment/RenewAttachmentUploadUrl: The same path. returns a new upload URL and information on how to upload
* PostAttachmentFileAsync: Direct upload to Bitwarden for …

Attachment azure upload blobs

---

src/App/Pages/Send/SendAddEditPageViewModel.cs
src/App/Pages/Vault/AttachmentsPageViewModel.cs
src/App/Resources/AppResources.resx

Both iOS and Android are having trouble with the current method of loading the entire file to memory, encrypting it, and sending to azure in one go.
We will need to come up with a chunking scheme to support larger files in the future
* **SendAddEditPageViewModel**: Validate file is not longer that 100MB
* **AttachmentsPageViewModel**: Validate file is not longer than 100MB
* **AppResources**: Revert size limit text to 100 MB

Limit file upload sizes to 100MB

---

src/App/Pages/Send/SendAddEditPageViewModel.cs

Delay share sheet trigger until after exiting add/edit Send screen/modal.  Previously we were seeing the exit action taking the sheet with it on some devices, but this appears to work across the board.

Fix for disappearing Send share sheet

---

src/App/Pages/Send/SendAddEditPageViewModel.cs
src/App/Resources/AppResources.resx

Users are required to verify their email before creating a file Send, however the current message doesn't provide any explanation about how to do this. This is especially a problem because you can't verify your email in the mobile app, so it's not obvious that you have to go somewhere else to do it.
I've used the same UX flow as settings that can only be changed in the web vault:
* explain to the user that this can only be done on the "bitwarden.com web vault" (may be inaccurate for self hosted, but I've stuck to the current pattern)
* offer to take the user there now, which takes the user to the relevant help documentation
I'll replicate these changes for desktop and browser tomorrow.
Bonus: deleted unused private var I left there from the 'hide email' feature.

Explain how to verify email for file Sends

---

src/Android/Properties/AndroidManifest.xml

The previous fix to open URIs in Android 11+ did not take into account app (i.e. non-web) URIs.  In order for `PackageManager.GetLaunchIntentForPackage(..)` to function in Android 11+, the package has to be visible to us.  Visibility can be specified by exact package name or types of actions with filters.  Since neither is practical when the user can specify any and all current and future apps, we've gone the wildcard route with the `name` and removed the optional `scheme`.  This gives us enough app visibility to build launch intents using known package names without requiring the `QUERY_ALL_PACKAGES` permission.
Additional reading:  https://developer.android.com/training/package-visibility

Expand package visibility for Android 11+

---

src/App/Pages/Settings/ExportVaultPageViewModel.cs

Fixes #1401. Exports should be saved as UTF-8, not ASCII-encoded strings.

Encode exports as UTF8

---

src/Core/Utilities/CoreHelpers.cs

This fixes bitwarden/mobile#967.
The issue is that [during comparison](https://github.com/bitwarden/mobile/blob/ce965ba5e1b71ac9e3ea98bdf7568d7f8830365a/src/Core/Services/CipherService.cs#L378-L379), if the URIs don't match `http://` or `https://`, `http://` is prepended to the URI, and subsequent calls to `uri.Host` always return `androidapp`.
This change simply avoids prepending `http://` in the case where a protocol is defined. It might make sense to use a regular expression to avoid the edge case of [matching that pattern later in the URL](https://stackoverflow.com/a/43283492/434343).

Fix Host matching of androidapp:// URIs

---

src/Android/MainActivity.cs
src/Android/WebAuthCallbackActivity.cs

- Android: make sure `WebAuthCallbackActivity` isn't exported
- Android: make TaskAffinity for `MainActivity` empty to address strandhogg v1 & v2 vulnerability
**Things to consider:**
These changes have the potential to affect established app behavior, and as such will require regression with a focus on autofill, accessibility, and the SSO authentication flow.

fix for activity exporting and workaround for task affinity

---

src/Android/MainActivity.cs
src/Android/WebAuthCallbackActivity.cs

[These changes](https://github.com/bitwarden/mobile/commit/e61bcd278548b7d8bb3925d8dc89f616c17b1c7d) broke the SSO auth flow (`Xamarin.Essentials.WebAuthenticatorCallbackActivity` can't deliver a callback to an activity with a different TaskAffinity).  Using `SingleTask` launch mode in our main activity still fixes the issue reported to us while maintaining TaskAffinity with other activities.  In addition `WebAuthCallbackActivity` must remain exported for this to work.

replaced blank taskaffinity with singletask launchmode

---

src/Core/Models/Request/TokenRequest.cs
src/Core/Services/ApiService.cs

Adds a new request header, `auth-email`, to auth requests that includes the same value as the `username` post parameter. This will enable us to rate limit auth requested based on username to prevent things like 2FA brute forcing.

add `auth-email` header to auth request

---

src/Core/Services/ExportService.cs
src/Core/Utilities/ServiceContainer.cs

In https://github.com/bitwarden/jslib/pull/369, I added an arbitrary `encString` at the top of encrypted exports. When the data is imported, this `encString` is decrypted first as a check to make sure that the encKey has not changed.
This PR replicates the change for mobile, by adding the `encString` to the top of encrypted exports.
Not implemented:
* dealing with organizations, as it looks like organization exports are not implemented in mobile
* importing data, as this can only be done via the web vault.

Add encKeyValidation string to encrypted exports

---

src/Core/Abstractions/IFileUploadService.cs
src/Core/Services/CipherService.cs
src/Core/Services/FileUploadService.cs
test/Core.Test/Services/CipherServiceTests.cs

See bitwarden/jslib#403. The issue wasn't present here, but the type change still is a good idea to protect against that kind of typo

Use type to ensure transmitted data is encrypted

---

src/App/Pages/Accounts/LockPageViewModel.cs
src/App/Pages/Accounts/LoginPageViewModel.cs
src/App/Pages/Accounts/LoginSsoPageViewModel.cs
src/App/Services/MobileStorageService.cs
src/App/Utilities/AppHelpers.cs
src/Core/Constants.cs
src/iOS.Core/Controllers/LockPasswordViewController.cs

Track failed unlock attempts in device storage instead of memory to prevent brute-force attacks for PIN or master password on unlock screen.  (HackerOne report # 1217914)

Track failed unlock attempts in storage

---

src/App/Pages/Send/SendsPage.xaml.cs
src/App/Pages/Vault/CiphersPage.xaml.cs

It seems https://github.com/bitwarden/mobile/pull/1374 broke selecting ciphers and sends when searching. When looking at the other pages which implements the same logic I noticed we forgot to add `FirstOrDefault()`.

Fix selecting ciphers in search not working

---

test/Core.Test/Models/Domain/SendTests.cs

Temporarily disable Send test until the race condition can be found, or Github Actions is capable of re-running jobs on a per-platform basis.  This is becoming problematic when the test fails on a single platform when merging to master and re-publishing the successful build only results in more errors.

Temporarily disable send tests

---

src/App/Pages/Settings/ExportVaultPageViewModel.cs

Fix for password handling in vault export:
- Don't clear `MasterPassword` property until after sending the backing var to `CompareAndUpdateKeyHashAsync`
- Negate `passwordValid` for proper error flow

Fix for export password handling

---

src/App/Pages/Vault/AddEditPage.xaml
src/App/Pages/Vault/AddEditPage.xaml.cs
src/App/Pages/Vault/AddEditPageViewModel.cs

An issue where a BindableLayout that is modified off-screen isn't re-drawn to reflect the modification (Xamarin Forms 4.5+) broke the way we render organization & collection selection when adding new vault items.  This PR works around that in an _interesting_ way.
- `HasCollections` is set to `true` in order to make the layout visible before modifying the content
- After `Collections` is updated with the new content, it is set to a new instance of `ExtendedObservableCollection` containing the values already established in `ResetWithRange` (which must still occur or this has no effect)
- Upon scrolling the screen, the collections `RepeaterView.ItemsSource` is repeatedly set to `Collections` (limited by a timer to prevent scroll events from max'ing out the thread pool)
Things to consider:
- …

Workaround for off-screen draw bug in XF4.5+

---

src/Core/Core.csproj
src/iOS/iOS.csproj

- Prevent linking of CsvHelper in release builds (fixes export failure)
- Update to latest CsvHelper for bugfixes
- Added missing `--linkskip=BitwardeniOSAutofill` where missing for consistency

Update csv lib and skip linking in release builds

---

src/App/Resources/AppResources.resx

Hey, I noticed that the string doesn't have a capitalized "Send" word.
It a bit messes up with the Crowdin comparing system, as both browser and desktop versions have "Send" capitalized correctly - while mobile and web don't.
I also made a PR on the web version.

MaximumAccessCountInfo locale string update

---

src/App/Pages/Vault/AutofillCiphersPage.xaml.cs

The autofill cipher list screen would re-appear when resuming the app after exiting via the back button (I believe this could be due to the change to SingleTask LaunchMode).  By clearing the autofill `Uri` when using the back button, resuming the app behaves as expected by opening to the main tabbed screen.

Fix for resuming autofill when back button was previously used to exit

---

src/Android/Autofill/AutofillService.cs
src/App/Pages/Send/SendAddEditPage.xaml.cs
src/App/Pages/Send/SendAddEditPageViewModel.cs
src/App/Pages/Vault/AddEditPage.xaml.cs
src/App/Pages/Vault/AutofillCiphersPage.xaml.cs

Recent changes to the order of operations for vault timeout created a bug specific to activities that are launched by an intent other than the system app launcher and when the user isn't using biometrics (race condition between showing the lock screen and clearing data needed to unlock).  This PR fixes that as well as a few other bugs discovered along the way.
- **AutofillService.cs**: calls `CheckVaultTimeoutAsync` before checking the lock status to make sure the timeout is taken into account before providing creds to the autofill service
- **SendAddEditPage.xaml.cs** and **SendAddEditPageViewModel.cs**: calls `CheckVaultTimeoutAsync` and checks lock status when appearing to prevent attempts to load anything before unlock can occur, and handle back button to close activity properly …

Fix for password unlock for autofill and share-to-send on Android

---

src/App/Pages/Send/SendAddEditPage.xaml

The same issue we had to work around in #1447 also occurred in the collapsible `Options` panel when adding/editing a Send.  Thankfully this one was easier to work around simply by locking the panel open so it's drawn initially and never needs to be re-drawn.  (This should also be reverted once the Forms bug is fixed)

Workaround for off-screen draw bug in XF4.5+ part 2 (Send)

---

src/Android/MainActivity.cs
src/App/Pages/Send/SendAddEditPage.xaml.cs
src/App/Pages/Send/SendAddEditPageViewModel.cs
src/App/Pages/Vault/AddEditPage.xaml.cs
src/App/Pages/Vault/AutofillCiphersPage.xaml.cs
src/App/Utilities/AppHelpers.cs

Recent changes caused the app to lock instantly when adding a new cipher or Send from within the app when the vault timeout is set to immediate.  As locking is handled on sleep instead of on resume when the timeout is set to immediate, some additional intelligence was needed to make sure activities that support launching via intent (autofill and Send) don't perform lock checks on launch if the timeout is set to immediate (as the app will already be locked when the user exited previously).
While working on this, a previous fix regarding back button handling in Send stopped working.  Further investigation revealed the launch intent was being re-delivered when resuming from the app switcher.  A simple check for the intent's `ActivityFlags.LaunchedFromHistory` allows us to skip delivery if …

Bugfixes for lock block when setting timeout to immediate

---

src/Android/MainActivity.cs

From a hackerone report, it's relatively easy to crash the Android app via the intent mechanism, so we're catching any exceptions to prevent this kind of denial of service attack.

handle intent exceptions to prevent denial of service

---

src/Core/Models/Data/OrganizationData.cs
src/Core/Models/Domain/Organization.cs
src/Core/Models/Response/ProfileOrganizationResponse.cs

Two fixes to Organization vars that were preventing sync from working with a particular set of data:
- `Seats`: made nullable to match server
- `MaxCollections`: made nullable `short` to match server

Bugfix for incorrect type and nullable for some org vars

---

src/Android/Android.csproj
src/Android/Properties/AndroidManifest.xml
src/App/App.csproj
src/iOS.Autofill/Info.plist
src/iOS.Autofill/iOS.Autofill.csproj
src/iOS.Extension/Info.plist
src/iOS.Extension/iOS.Extension.csproj
src/iOS/Info.plist
src/iOS/iOS.csproj
store/google/Publisher/Publisher.csproj
test/Common/Common.csproj
test/Core.Test/Core.Test.csproj

- App version bump to 2.11.2
- Bumped to latest Xamarin libs to squash Android fragment view crash
- Updated other libs since this release will be regression tested
- Keep `Xamarin.Google.Android.Material` at `1.3.0.1` due to [this issue](https://github.com/xamarin/AndroidX/issues/335)
- Added explicit `Xamarin.AndroidX.Core` dependency due to [this issue](https://github.com/xamarin/Xamarin.Forms/issues/14417) (will create Asana ticket for future removal)

lib updates and app version bump

---

src/Android/Android.csproj
src/Android/Properties/AndroidManifest.xml
src/App/App.csproj
src/iOS.Autofill/Info.plist
src/iOS.Autofill/iOS.Autofill.csproj
src/iOS.Extension/Info.plist
src/iOS.Extension/iOS.Extension.csproj
src/iOS/Info.plist
src/iOS/iOS.csproj
store/google/Publisher/Publisher.csproj
test/Common/Common.csproj
test/Core.Test/Core.Test.csproj

Reverts bitwarden/mobile#1468.  App is crashing on login when built in release mode, because of course it is.

Revert "lib updates and app version bump"

---

src/Android/Android.csproj
src/App/App.csproj
src/iOS.Autofill/iOS.Autofill.csproj
src/iOS.Extension/iOS.Extension.csproj
src/iOS/iOS.csproj
store/google/Publisher/Publisher.csproj
test/Common/Common.csproj
test/Core.Test/Core.Test.csproj

- Bumped to latest Xamarin Forms to fix Android crash when toggling light/dark mode
- Keep `Xamarin.Google.Android.Material` at `1.3.0.1` due to [this issue](https://github.com/xamarin/AndroidX/issues/335)
- Added explicit `Xamarin.AndroidX.Core` dependency due to [this issue](https://github.com/xamarin/Xamarin.Forms/issues/14417) (will create Asana ticket for future removal)
- Restricted `Xamarin.AndroidX.Core` to `1.5.0` and added `Xamarin.AndroidX.AppCompat.AppCompatResources` due to [this issue](https://github.com/xamarin/Xamarin.Forms/issues/14424)
- Removed `<AndroidLinkMode>` from debug builds to fallback to default (same as release, which is `SdkOnly` instead of `None`) to catch library issues sneaking past developers.  This will add a few seconds to the build time, but …

Fix for Android crash when toggling system light/dark theme

---

src/App/Pages/Accounts/LoginSsoPage.xaml
src/App/Pages/Accounts/TwoFactorPageViewModel.cs

Some work to finish off #1427.
On the 2FA page:
* Fix QA feedback that the "Continue" button was not properly showing/hiding based on the selected 2FA method. This was because we weren't using `setProperty` in the `ShowContinue` getter, so the bindings weren't being updated.
* Fix an unrelated bug where clicking off the "Use another method" modal (without selecting an option or clicking cancel) would act as if the user had selected an unsupported 2FA method.
On the SSO page:
* Move Log In button to be consistent with the other login pages.

Move remaining primary buttons in login flow

---

src/Android/Accessibility/AccessibilityHelpers.cs
src/Android/Autofill/AutofillHelpers.cs
src/Android/Resources/xml/autofillservice.xml

This adds support for Mull browser, a privacy oriented and deblobbed web browser based on Mozilla's Firefox for Android. 
Also adds support for legacy version of Mull based on the Fennec architecture.
Resolves #1288

Add support for Mull browser

---

test/Core.Test/Services/SendServiceTests.cs

Temporarily disable Send test until the race condition can be found, or Github Actions is capable of re-running jobs on a per-platform basis (missed this one back when #1443 was merged, and it failed today with the same `System.Exception : Service cryptoService is not registered` message)

Temporarily disable send test

---

.github/workflows/release.yml

Adds a Release workflow so that we can test on another branch while developing a proper Release workflow.

Add Release workflow stub

---

src/Android/MainActivity.cs
src/App/Utilities/AppHelpers.cs

There have been some reports of the EMM / MDM configuration for centrally mobile deployments where the custom, self-hosted URL for Bitwarden needs to be pre-set in corporate distributions. This capability is supported in Xamarin and this capability was added a while back, but it would appear it isn't working (just nobody told us this or truly needed it until now).
* **MainActivity.cs** - `SetPreconfiguredRestrictionSettingsAsync` is an `async` method and was being called synchronously, assigning the delegate task (unexecuted) to `var setRestrictions` only to be lost in the aether. Added the `.GetAwaiter().GetResult()` call to force synchronous execution in the synchronous context it's needed
* **AppHelpers.cs** - It would seem that from the calling methods to …

Fix for EMM system configuration for mobile

---

src/App/Pages/CaptchaProtectedViewModel.cs
src/Core/Models/Response/ErrorResponse.cs
src/iOS.Core/Services/DeviceActionService.cs

Fixes: https://app.asana.com/0/0/1200771124135716/f
Two iphone crashes were found due to captcha. The first is a null exception dismissing progress view if it doesn't exist. The second with grabbing validation errors on a message that has none.
* **CaptchaProtectedModel.cs**: Use helper method to ensure we have the right webvault url
* **ErrorResponse**: Handle the case when no validationErrors are returned
* **DeviceActionService**: Return if _progress is null. This seems to just be an oversight of the null check.

Fix iphone captcha throws

---

.github/workflows/crowdin-sync.yml

In order to test the new Crowdin Sync workflow, the workflow needs to first exist in `master`

Adding stub for crowdin sync testing

---

src/App/Pages/Accounts/SetPasswordPage.xaml
src/App/Pages/Accounts/SetPasswordPageViewModel.cs
src/App/Resources/AppResources.Designer.cs
src/App/Resources/AppResources.resx
src/Core/Abstractions/IApiService.cs
src/Core/Abstractions/IPolicyService.cs
src/Core/Abstractions/IUserService.cs
src/Core/Enums/PolicyType.cs
src/Core/Models/Data/OrganizationData.cs
src/Core/Models/Domain/Organization.cs
src/Core/Models/Domain/ResetPasswordPolicyOptions.cs
src/Core/Models/Request/OrganizationUserResetPasswordEnrollmentRequest.cs
src/Core/Models/Response/OrganizationKeysResponse.cs
src/Core/Models/Response/ProfileOrganizationResponse.cs
src/Core/Services/ApiService.cs
src/Core/Services/PolicyService.cs
src/Core/Services/UserService.cs

> Expand the `Set Password` flow to handle Password Reset Auto Enrollment for the organization joined.
- **SetPasswordPage.xaml**: Add new banner explaining auto enrollment
- **SetPasswordPageViewModel.cs**: Add new properties/methods/conditionals for handling auto enrollment once a successful password is set
- **AppResources.resx**: Added banner string
- **ApiService**: Added two new API methods to be used during the auto enrollment flow
- **PolicyService**: Added new getter method retrieving reset password policy options
- **UserService**: Added new method to retrieve an organization by `identifier`
- **PolicyType**: Added `ResetPassword` enumeration
- **OrganizationData**: Added `Identifier` property
- **Organization**: Added `Identifier` property
- **ResetPasswordPolicyOptions**: …

[SSO] Auto enroll during set password

---

src/App/Pages/Accounts/TwoFactorPageViewModel.cs
src/App/Resources/AppResources.Designer.cs
src/App/Resources/AppResources.resx

_Edited with final screenshots_
Prepend WebAuthn error messages with a friendly/helpful message to hopefully cut down on support requests.
Key points conveyed:
1. User's browser must support WebAuthn, and 
2. It has to be set as the default browser (per WebAuthenticator requirements) 
New message:
Old message:

friendly message for webauthn errors

---

src/App/Pages/Accounts/SetPasswordPageViewModel.cs
src/Core/Abstractions/IApiService.cs
src/Core/Models/Response/OrganizationAutoEnrollStatusResponse.cs
src/Core/Services/ApiService.cs

> Add the latest `Auto Enroll` status `API` and updated the flow for information retrieval in regards to the `Organization ID` and `AutoEnrollEnabled` boolean.
- **SetPasswordPageViewModel**: Update the flow to use the newly available `API`
- **api.service**: Added new `GetOrganizationAutoEnrollStatus` method
- **OrganizationAutoEnrollStatusResponse**: Added response object for newly created `API`
- [Server - Add Auto Enroll status API](https://github.com/bitwarden/server/pull/1583)

[SSO Auto Enroll] Auto Enroll status retrieval

---

src/Android/Android.csproj
src/Android/Renderers/CustomTabbedRenderer.cs
src/App/App.csproj
src/Core/Core.csproj
src/iOS.Autofill/iOS.Autofill.csproj
src/iOS.Extension/iOS.Extension.csproj
test/Common/Common.csproj
test/Core.Test/Core.Test.csproj

The SR5 release of Xamarin Forms (5.0.0.2125) fixed the broken AndroidX & Material dependencies of the previous release, allowing us to remove the extra dependencies added in #1471 and update others to the latest without breaking the build.  This will close [this Asana task](https://app.asana.com/0/1169444489336079/1200632790235501/f).
(Note this does not yet fix [this Asana task](https://app.asana.com/0/1169444489336079/1200531933783245/f) which we worked around in #1447 and #1454)
Also updated LiteDB, AppCenter, and .NET Test SDK to the latest.

Update XF to remove AndroidX dependency hack

---

src/App/Pages/Vault/GroupingsPage/GroupingsPageViewModel.cs

Prevents grouped pages from counting deleted items in the folder/collection counts. We were including these deleted items when doing type, folder, and collection counts on grouped pages (except the main page which had code to prevent it).

Exclude deleted items from folder counts

---

src/Android/Accessibility/AccessibilityHelpers.cs
src/Android/Autofill/AutofillHelpers.cs
src/Android/Resources/xml/autofillservice.xml

Some android systems show captive login activity (`com.google.android.captiveportallogin`) when connecting to wireless network. This activity shows URL in its ActionBar subtitle, so there is no view ID.
See: https://cs.android.com/android/platform/superproject/+/master:packages/modules/CaptivePortalLogin/src/com/android/captiveportallogin/CaptivePortalLoginActivity.java;l=600
This browser was added in https://github.com/bitwarden/mobile/pull/1281, but the developer seems to be unwilling to add auto-fill compatibility. Auto-fill was partially functioning before adding the support, but afterwards it was completely broken (or it might be subject to browser version). Dropping the support might be a good choice.

[SupportedBrowsers] Add Captive Login and drop Alook

---

src/iOS.Extension/LoadingViewController.cs

iOS extension is not loading.
This was an unintentional feature of our appearance tweaks in #1556. We used the ThemeManager to call colors for appearance adjustments before we had a ResourceDictionary loaded.
Asana Task: https://app.asana.com/0/1169444489336079/1201291162165972/f
Closes #1624
* **src/iOS.Extension/LoadingViewController.cs:** Load app resources before making appearance adjustments
- Test app extension can be turned on and loads correctly in different scenarios
- Test extension appearance and theme is correct

iOS Extension is not loading (#1624)

---

src/iOS.Core/Controllers/LockPasswordViewController.cs

Use SSO if using key connector without bio or pin on autofill
Asana Task: https://app.asana.com/0/1201363553288890/1201363818962345/f
https://app.asana.com/0/1201363553288890/1201363818962343/f
* **src/iOS.Core/Controllers/LockPasswordViewController.cs:** Add call to SSO login page if using key connector
- Autofill authentication with key connector
- Extension authentication with key connector

Show SSO login if using key-connector without bio or pin

---

src/App/Pages/Settings/SettingsPage/SettingsPageViewModel.cs

If the user is using Key Connector and sets an unlock pin, do not ask them whether they want to "require unlocking with master password when the application is restarted". Instead, default this to false because they do not have a master password.

[Key Connector] Hide "Master Pass On Restart" prompt when setting pin

---

src/Android/Android.csproj
src/Android/MainApplication.cs

Favicons were missed on the vault because of an SSL issue due to not setting AndroidClientHandler on the image library, FFImageLoading.
Discussion of the issue: https://github.com/xamarin/xamarin-android/issues/6351
**MainApplication.cs:** Set AndroidClientHandler as the handler for the HttpClient to be used in the FFImageLoading service.
Specially on Android API < 7.1.1 we should test that the vault icons are being loaded correctly.

Fixed missing FavIcons on Android #1640

---

src/iOS.Core/Controllers/LockPasswordViewController.cs

Implements https://github.com/bitwarden/mobile/pull/1654 for the iOS extension & autofill projects:
> If a key connector user has biometrics set up on the lock screen, we want to hide the master password prompt. [...]
>
> If the user is using a PIN with biometrics, the screen should remain the same and prompt for PIN input.
* **src/iOS.Core/Controllers/LockPasswordViewController.cs**:
* hide the Submit button if using biometric unlock only (this is done by setting text to `null` and disabling it)
* change the title text to "Unlock Vault" if using biometric unlock only
* skip setup for the `MasterPasswordCell` if using biometric unlock only
* if using biometric unlock only, move the "biometric cell" up to the first row, and adjust the length of the grid accordingly. To assist this, I've …

[Key Connector] Hide MP input in iOS extensions

---

src/Android/Renderers/CustomEntryRenderer.cs

Android has a known bug preventing the copy/paste functionality on a TextView inside a scrollable RecyclerView: https://issuetracker.google.com/issues/37095917
While running on Android 11, Bitwarden entry fields are encountering the same problem. After loading a page with entry fields, you can't long-press to show copy/paste menu unless you first input text. 
This workaround re-enables the entry after displaying, and allows users to utilize the clipboard without putting in text first.
Asana Task: https://app.asana.com/0/1169444489336079/1199543494650934/f
Closes #1215
* **src/Android/Renderers/CustomEntryRenderer.cs:** Workaround for Android clipboard bug
- Regression testing of clipboard functionality for entry fields throughout the application on Android 11

Add workaround to Android entry renderer

---

src/Android/Accessibility/AccessibilityHelpers.cs
src/Android/Autofill/AutofillHelpers.cs

In future versions of Focus/Klar, we will be using the same view ID as other Mozilla browsers.

Update Focus/Klar accessibility IDs

---

src/Android/Accessibility/AccessibilityHelpers.cs
src/Android/Autofill/AutofillHelpers.cs
src/Android/Resources/xml/autofillservice.xml

Add support for Bitwarden auto-fill in Pluma: [Play Store link](https://play.google.com/store/apps/details?id=com.qflair.browserq).
Add the corresponding package name in the expected places. Followed other PRs that achieve the same for other browsers, such as https://github.com/bitwarden/mobile/pull/846.
Ensure that Bitwarden auto-fill suggestions target the site that Pluma is currently displaying (as opposed to the package name for Pluma).

Add support for Pluma Browser for Android

---

src/App/Pages/Vault/AddEditPageViewModel.cs

Fix crash produced when adding a custom field on a Secure Note, because it tries to load Linked field picker even if the type of the custom field is not Linked. This happens because the Linked picker is on the same view.
* **AddEditPageViewModel.cs:** Added null check to avoid crash when loading LInkedFieldOptions on SecureNote on other type of custom fields.
Try to add each type of custom field on Secure Notes; and also a Linked custom field on some other Cypher.

Fix Crash produced when adding a custom field on a Secure Note

---

src/iOS.Core/Controllers/LockPasswordViewController.cs

Key Connector changes for autofill on iOS were showing the SSO login flow even when a user wasn't a SSO user. This was a logic error, we weren't checking for key connector use while seeing if the user was using biometric without being validated. 
Needs to be cherry picked to `rc`
Asana Task: https://app.asana.com/0/1201363553288890/1201432735007902/f
* **src/iOS.Core/Controllers/LockPasswordViewController.cs:** Add check for key connector before sso login flow to autofill
- iOS autofill with/without key connector & biometric authentication

only prompt for sso if using key connector

---

src/iOS/AppDelegate.cs

iOS will occasionally crash while backgrounding or killing the application. This was due to us referencing a `KeyWindow` object that becomes null during backgrounding. If the timing was off we would get a null pointer exception. 
This fix moves all the logic for backgrounding to OnResignActivation, which is called right before we move to the background. `KeyWindow` shouldn't be null yet and we can handle the splash screen without timing issues.
This opens up an old task: https://app.asana.com/0/1169444489336079/1201190971681077/f
We might eventually need to refactor how we accomplish this, as `KeyWindow` is deprecated in iOS 15.
* **src/iOS/AppDelegate.cs:** Move splash screen logic to OnResignActivation
- Testing around backgrounding and killing of app. Splash screen should show when …

move splash screen logic to OnResignActivation

---

src/iOS.Extension/iOS.Extension.csproj

the iOS extension project didn't have the entitlements selected for simulator debug builds, causing it to crash on initialization.

include entitlements in ios.extension simulator builds

---

src/Android/Android.csproj
src/Android/MainActivity.cs
src/Android/MainApplication.cs
src/Android/Services/ClipboardService.cs
src/App/Pages/Generator/GeneratorHistoryPageViewModel.cs
src/App/Pages/Generator/GeneratorPageViewModel.cs
src/App/Pages/Settings/SettingsPage/SettingsPageViewModel.cs
src/App/Pages/Vault/PasswordHistoryPageViewModel.cs
src/App/Pages/Vault/ViewPageViewModel.cs
src/App/Services/MobilePlatformUtilsService.cs
src/App/Utilities/AppHelpers.cs
src/Core/Abstractions/IClipboardService.cs
src/Core/Abstractions/IPlatformUtilsService.cs
src/iOS.Core/Services/ClipboardService.cs
src/iOS.Core/Utilities/iOSCoreHelpers.cs
src/iOS.Core/iOS.Core.csproj
src/iOS/AppDelegate.cs

This PR fixes the Clipboard clear after time set by the user on Options on iOS
* **ClipboardService.cs:** Added this service to centralize the clipboard logic
* **MainActivity.cs/AppDelegate.cs:** Removed clipboard and messenger related logic and moved it to the service
* **OtherFiles:** Changed the old calls to point to the new `ClipboardService`
Given that the copy feature has been refactored a bit in order to fix this issue, we should check that values are being copied correctly in the next places of the app (both Android and iOS):
- Cyphers all values that can be copied (Username, Password, TOTP, Card Number, Security Code, Notes, Send URL)
- Password generator password
- Password history password
- Settings → About

Fix Clipboard clear after time on iOS

---

src/Android/Accessibility/AccessibilityActivity.cs
src/Android/Android.csproj
src/Android/MainActivity.cs
src/Android/Utilities/IntentExtensions.cs
src/Android/WebAuthCallbackActivity.cs

Fix crash produced by unsafe deserialization of parcel data intent attack.
The problem lies in that when creating the activity this is called and if there are any extras then a bundle is requested in [FcmLifecycleCallbacks](https://github.com/firebase/firebase-android-sdk/blob/21a9f912862bfbd801690a9f88dce22366bec8ac/firebase-messaging/src/main/java/com/google/firebase/messaging/FcmLifecycleCallbacks.java#L40) that will cause to call the [Bundle.getBundle(...)](https://cs.android.com/android/platform/superproject/+/nougat-cts-release:frameworks/base/core/java/android/os/Bundle.java;l=817) which calls `unparcel()` and if the attacker planted a parcelable class that can't be found in the app then it will make the app crash.
* **MainActivity.cs:** Call ValidateIntent to check whether the …

Fix Unsafe deserialization of Parcel data Intent

---

src/App/Utilities/ThemeManager.cs
src/iOS.Core/Renderers/CustomLabelRenderer.cs

Fix crash on iOS LabelRenderer when changing themes on password generator screen and password generator history. These are **workarounds** only
I think this may need to be further tested and check what happens on certain scenarios before going to PRD. I saw that when the app is supposed to crash, but now it doesn't because of the try...catch, there are certain elements that don't update the style, so maybe I could spend more time in it trying to make everything work correctly
* **CustomLabelRenderer.cs:** Added try...catch when calling base so that we can ignore the exception if it happens, it's the only workardound I could find so far (already submitted PR on Xamarin Forms to fix this https://github.com/xamarin/Xamarin.Forms/pull/14982)
* **ThemeManager.cs:** Sometimes the app crashes …

Fix by workaround crash on LabelRenderer and when changing themes #1689

---

src/iOS/AppDelegate.cs

Fix crash produced on iOS after long time in the background
* **AppDelegate.cs:** Added null checks on some services that were being called on the app lifecycle and may have been disposed before.
I'm not sure yet what is the root cause of the problem, so this'd be a baindaid for the problem, if it keeps appearing we'd need to dig in more to check which is the flow or root cause that leads to the blink crash.
Steps to reproduce:
- Open the Bitwarden app on iOS
- Stop using the phone for a while leaving it on background (no idea yet how long, to make sure of my testing I left it on the background until the next day)
- Open the Bitwarden app again. On the first try, the app will just blink (opening then closed suddenly).
- It will open successfully on the second try.
The app shouldn't crash …

Possible fix for iOS crash after long time idling

---

src/Android/Autofill/AutofillHelpers.cs
src/Android/Autofill/AutofillService.cs

closes #1017 
Asana: https://app.asana.com/0/1169444489336079/1185097609703843/f
We're having reports of some applications and browsers repeatedly asking if the user would like to save login information. While this is most likely an issue with the Autofill service or the application itself, our option to "Disable Save Prompts" isn't working correctly to stop all prompts.
This change moves the check for "Disable Save Prompts" to before sending the fill package. That way, we can determine if the we need to include Save Information in the `FillResponse` before the prompt shows.
* **src/Android/Autofill/AutofillHelpers.cs:** Change `BuildFillResponse` to `CreateFillResponse` as we are only returning the `FillResponse.Builder` now in …

Check for disable save prompt option before sending fill request in Android Autofill

---

src/App/Pages/Settings/SettingsPage/SettingsPage.xaml
src/App/Pages/Settings/SettingsPage/SettingsPage.xaml.cs
src/App/Pages/Settings/SettingsPage/SettingsPageListItemSelector.cs

Every option in settings allows you to tap anywhere within the row to enable the action. Every option except "Custom" timeouts. This fix pulls the option into its own data template and adds a tap recognizer on the entire row for the TimePicker.
Asana: https://app.asana.com/0/1169444489336079/1201172188894451/f
* **src/App/Pages/Settings/SettingsPage/SettingsPage.xaml:** Create new DataTemplate for Custom option in Settings. Include DataTemplate in the DataTemplateSelector
* **src/App/Pages/Settings/SettingsPage/SettingsPage.xaml.cs:** If TapGestureRecognizer is triggered, find the TimePicker from the StackLayout and trigger.
* **src/App/Pages/Settings/SettingsPage/SettingsPageListItemSelector.cs:** Return new DataTemplate for Custom …

Expand Settings TimePicker tap recognition to entire row

---

src/App/Pages/Settings/SettingsPage/SettingsPageViewModel.cs
src/App/Services/PushNotificationListenerService.cs
src/Core/Constants.cs
src/iOS/AppDelegate.cs
src/iOS/Services/iOSPushNotificationHandler.cs
src/iOS/Services/iOSPushNotificationService.cs

Add logs and information to help figure out what's wrong on iOS push notifications. **This PR should be reverted after we fix the iOS push notifications on TestFlight** But we need this PR to trigger a new TestFlight version with additional logs
* Added logs and info on Settings about regarding PN registration
This is merely for Dev logs.

Add logs to help solve iOS PN problem

---

src/Core/Abstractions/ITokenService.cs
src/Core/Services/AuthService.cs
src/Core/Services/TokenService.cs

Fix NPE on login with account that has never logged in before (recent change in the way skipping token storage is handled combined with a fresh install)
* **TokenService.cs:** Added `forDecodeOnly` bool to `SetAccessTokenAsync` method to allow token decoding without saving to the account state (which doesn't exist until the next step in the auth process, which requires values from the decoded token)
* **AuthService.cs:** Utilize the new bool
Login with a fresh install and boom.  Apparently it's been awhile since I cleared app data.

Fix for initial login token storage paradox

---

src/App/Controls/ExtendedToolbarItem.cs
src/iOS.Core/Renderers/CustomNavigationRenderer.cs

Fix crash when having two or more users and one of them logs out on Account Switching.
* **CustomNavigationRenderer.cs:** Added try....catch of the `ObjectDisposedException` given that we don't have a clearer way to check whether the Toolbar item has been disposed or change the approach on (un)subscription for the `PropertyChanged`
The app shouldn't crash when logging out a user

Fix Account Switching crash on log out

---

src/Android/MainApplication.cs
src/App/Pages/Accounts/LockPage.xaml.cs
src/App/Pages/BaseContentPage.cs
src/App/Pages/Vault/GroupingsPage/GroupingsPage.xaml.cs
src/App/Services/MobileStorageService.cs
src/Core/Abstractions/IAppIdService.cs
src/Core/Abstractions/IStateMigrationService.cs
src/Core/Abstractions/IStateService.cs
src/Core/Constants.cs
src/Core/Services/AppIdService.cs
src/Core/Services/StateMigrationService.cs
src/Core/Services/StateService.cs
src/Core/Utilities/ServiceContainer.cs
src/iOS.Core/Utilities/iOSCoreHelpers.cs

Migrate existing user data to the new multi-account storage pattern upon app update.
* **MainApplication.cs:** Init `StateMigrationService` with the required storage services
* **LockPage.xaml.cs:** Remove avatar appearance condition since it will always been shown here
* **GroupingsPage.xaml.xs:** Remove old v1-to-v2 migration code (some of which was moved to `StateMigrationService`)
* **BaseContentPage.cs:** Change avatar appearance condition to the presence of any active account, which should only ever be false before the very first login
* **MobileStorageService.cs:** Remove old migration keys & logic, add key for state version
* **AppIdService.cs:** Reverted to pre-multi-account state due to infinite loop during migration when it was using the state service (this particular value …

Account switching migration service

---

src/App/Pages/Accounts/HomePage.xaml
src/App/Pages/Accounts/HomePage.xaml.cs
src/App/Pages/Accounts/LockPage.xaml
src/App/Pages/Accounts/LockPage.xaml.cs
src/App/Pages/Accounts/LoginPage.xaml
src/App/Pages/Accounts/LoginPage.xaml.cs
src/App/Pages/BaseContentPage.cs
src/App/Pages/Vault/GroupingsPage/GroupingsPage.xaml
src/App/Pages/Vault/GroupingsPage/GroupingsPage.xaml.cs

Add tap to dismiss on the Account Switching list when tapping outside the list on the overlay.
* **BaseContentPage.cs:** Renamed `ShowAccountListAsync` to `ToggleAccountListAsync` handling the `IsVisible` inside from the overlay reference thus reducing the boilerplate from the callers. Added two new methods `ShowAccountListAsync` and `HideAccountListAsync` to be used directly where they are needed.
* **...Page.xaml:** Added `BoxView` to add the tap gesture and dismiss the overlay
* **...Page.xaml.cs:** Added behavior to dismiss the overlay on tapping and improved the code to reduce boilerplate
When the Account Switching overlay list is opened, tapping on the bottom part should close it.

Account Switching Tap to dismiss

---

src/App/Resources/AppResources.resx

Remove final punctuation on some strings for the Send view.
* **AppResources.resx:** Removed punctuation
The final period should not be there on the strings that relate to the toggles on the Send screen
Bitwarden Send via the share icon menu
- Open a file such as PDF or photo
- select the share button in iOS then select Bitwarden
- scroll to the bottom of the send and there are two toggle titles that should not have periods anymore

Removed punctuation on some string resources regarding Send

---

src/App/Effects/ScrollViewContentInsetAdjustmentBehaviorEffect.cs
src/App/Pages/Accounts/HomePage.xaml
src/App/Pages/Accounts/LockPage.xaml
src/App/Pages/Accounts/LoginPage.xaml
src/App/Pages/Vault/GroupingsPage/GroupingsPage.xaml
src/iOS.Core/Effects/ScrollViewContentInsetAdjustmentBehaviorEffect.cs
src/iOS.Core/iOS.Core.csproj

Fix top space shown on iOS on the Account Switching overlay after opening and closing a modal on the Vault and then opening the Account Switching list.
* **GroupingsPage.xaml:** Added effect to change the behavior of content inset adjustment on the list view of account switching overlay so that it never takes into account the Safe Area which was causing the issue.
In the Vault, after opening and closing a modal like adding a cypher, and opening the account switching overlay shouldn't present any weird spaces at the top.

Fix iOS top space on Account switching list overlay after modal

---

src/App/Pages/Accounts/HomePage.xaml.cs
src/App/Pages/Accounts/LockPage.xaml
src/App/Pages/Accounts/LockPage.xaml.cs
src/App/Pages/Accounts/LoginPage.xaml.cs
src/App/Pages/BaseContentPage.cs
src/App/Pages/Vault/GroupingsPage/GroupingsPage.xaml.cs

Dismiss the account list on certain events, like selecting toolbar options that are still accessible when the menu is showing, the Android back button, etc.
* **HomePage.xaml.cs:** Hide account list when opening environment controls, and Android back button support
* **LockPage.xaml:** Cleanup formatting to be identical to other pages with account switching overlay
* **LockPage.xaml.cs:** Hide account list when selecting Log Out (Android) or when More is clicked (iOS), and Android back button support
* **LoginPage.xaml.cs:** Hide account list in CloseAction, when More is clicked, and Android back button support
* **GroupingsPage.xaml.cs:** Hide account list on Search, Sync, Lock, Exit, Add, and ShowPreviousPage.  Added missing _fab arg in `AccountSwitch_Clicked` and …

Usability: dismiss account list on certain events

---

src/Android/MainApplication.cs
src/App/Pages/Accounts/DeleteAccountViewModel.cs
src/App/Pages/Accounts/VerificationCodeViewModel.cs
src/App/Utilities/VerificationActionsFlowHelper.cs
src/Core/Models/Request/DeleteAccountRequest.cs
src/Core/Services/UserVerificationService.cs
src/iOS.Core/Utilities/iOSCoreHelpers.cs

Fix OTP parameter sent on account deletion of SSO with CME.
* **DeleteAccountRequest.cs:** Added OTP parameter
* **VerificationActionsFlowHelper:** Added more logic to set the verification type on the parameters and also hash the password directly here
* **VerificationCodeViewModel:** Set the verification type on the parameters
* **DeleteAccountViewModel.cs -> DeleteAccountActionFlowExecutioner:** Updated it to consider passing the master password hash or the OTP parameter to the request.
A user should be able to delete an account with master password and also with OTP (SSO with CME)

Fix Account Deletion SSO with CME OTP parameter 

---

src/App/App.csproj
src/App/Controls/AccountSwitchingOverlay/AccountSwitchingOverlayView.xaml
src/App/Controls/AccountSwitchingOverlay/AccountSwitchingOverlayView.xaml.cs
src/App/Controls/AccountSwitchingOverlay/AccountSwitchingOverlayViewModel.cs
src/App/Pages/Accounts/HomePage.xaml
src/App/Pages/Accounts/HomePage.xaml.cs
src/App/Pages/Accounts/HomePageViewModel.cs
src/App/Pages/Accounts/LockPage.xaml
src/App/Pages/Accounts/LockPage.xaml.cs
src/App/Pages/Accounts/LockPageViewModel.cs
src/App/Pages/Accounts/LoginPage.xaml
src/App/Pages/Accounts/LoginPage.xaml.cs
src/App/Pages/Accounts/LoginPageViewModel.cs
src/App/Pages/BaseContentPage.cs
src/App/Pages/Vault/GroupingsPage/GroupingsPage.xaml
src/App/Pages/Vault/GroupingsPage/GroupingsPage.xaml.cs
src/App/Pages/Vault/GroupingsPage/GroupingsPageViewModel.cs
src/Core/Abstractions/IStateService.cs
src/Core/Services/StateService.cs

Add an account switching overlay control to be reused on all the views. Also add its own ViewModel to handle the logic and configuration.
* **AccountSwitchingOverlayView:** This is the new control for the overlay
* **AccountSwitchingOverlayViewModel:** This is the overlay's viewmodel to handle logic and configuration
* **...Page.xaml:** Changed to use the new overlay control
* **...Page.xaml.cs:** Changed to use the new overlay control and removed old code
* **...PageViewModel.cs:** Added and created new `AccountSwitchingOverlayViewModel` on each to offer the binding context for the new overlay control and configuration 
* **BaseContentPage.cs:** Moved Account switching overlay logic to the new control
* **StateService:** Change the `AccountViews` to be a `List` instead of an …

Create and use Account Switching overlay control

---

src/Android/Renderers/CustomTabbedRenderer.cs
src/App/Pages/TabsPage.cs
src/App/Pages/Vault/GroupingsPage/GroupingsPage.xaml.cs
src/iOS.Core/Renderers/CustomTabbedRenderer.cs

Dismiss the Account Switching Overlay when tapping on the tabs. 
**Merge #1753 before merging this so the call to hide the overlay gets updated in the new way the other PR has.**
* **TabsPage:** Implemented call to hide the overlay on the `GroupingsPage` on tab re-selection and when changing tabs
* **Android/Renderers/CustomTabbedRenderer.cs:** Called hide the overlay on tab re-selection and updated the deprecated listener.
* **/iOS.Core/Renderers/CustomTabbedRenderer.cs:** Called hide the overlay on tab re-selection
* **GroupigsPage.xaml.cs:** Made pubic method to hide the overlay (this needs to change when #1753 gets merged)
When the overlay is open and you tap on a tab, the overlay should hide.

Dismiss Account Switching overlay when tapping on the tabs

---

src/App/Controls/AvatarImageSource.cs

Fix Avatar blinking when changing tabs and going back to Groupings tab.
* **AvatarImageSource:** Overriden Equals and GetHashCode so the instance is properly compared based on the `_data` thus disallowing to set an instance with the same `_data` multiple times when using `SetProperty(...)` on the ViewModels.
The Avatar shouldn't blink when changing tabs and returning to the first one (where the avatar is shown)

Account Switching fix avatar blinking

---

src/iOS.Core/Renderers/ExtendedDatePickerRenderer.cs

We had a workaround for `DatePicker` styling that targeted iOS 13.2 and above. This workaround was actually supposed to be targeting 14.0 and above, so was throwing an error on anything between 13.2 and 14.0.  
Since we have upgraded to Xamarin 5.0.0.2125, we can remove this as Xamarin has [fixed the issue](https://github.com/xamarin/Xamarin.Forms/pull/13344)
* **src/iOS.Core/Renderers/ExtendedDatePickerRenderer.cs:** Remove styling workaround
`DatePicker` should continue working correctly. There are examples on the Settings and EditSend screens.

remove datepicker style workaround

---

.github/workflows/build.yml

This PR adds the `iOS AppCenter` secret to the `build` workflow.
* **.github/workflows/build.yml:** Added login/key-vault steps to `iOS` job and used new secret in `Upload dSYMs to App Center` step.

Add AppCenter secret to build workflow

---

src/App/Pages/Vault/GroupingsPage/GroupingsPageListItem.cs

> Fix the groupings icon for collections: `bwi-globe` --> `bwi-collection`
- **GroupingsPageListItem**: Changed icon for collections to `BitwardenIcons.Collection`
- Reference for correct icon
- Make sure that the icon for collections within the groupings page is using the correct icon

[Icons] - BUG - Update groupings icon for collections

---

src/App/App.xaml.cs

Fix for vault timeout not firing on app resume in most recent release.  Closes #1772
* **App.xaml.cs:** The [recent change](https://github.com/bitwarden/mobile/pull/1707) to make `UpdateTheme` async resulted in a race condition which allowed `BaseContentPage.SaveActivity()` to execute prior to `VaultTimeoutService.CheckVaultTimeoutAsync()`.  This resulted in the `LastActiveTime` value being reset before it could be compared to the current time, making the app think only a few milliseconds had passed regardless of how long it was in the background.  By checking vault timeout before executing the improved theme update process, we're able to establish the correct elapsed time again.  @fedemkr Let me know if you see any issues with this interfering with the theme updater.
Vault timeout should …

Fix for vault timeout not firing on resume

---

src/App/Pages/Accounts/LoginPageViewModel.cs
src/App/Pages/Accounts/LoginSsoPageViewModel.cs
src/App/Pages/Settings/ExtensionPageViewModel.cs
src/App/Resources/AppResources.Designer.cs
src/App/Resources/AppResources.resx
src/App/Services/MobileStorageService.cs
src/App/Utilities/AppHelpers.cs
src/Core/Abstractions/IStateService.cs
src/Core/Constants.cs
src/Core/Services/StateMigrationService.cs
src/Core/Services/StateService.cs
src/Core/Services/SyncService.cs
src/Core/Services/VaultTimeoutService.cs

Improvements to the handling and presentation of logging out on vault timeout.  Some high-level details:
- Being "logged out" on timeout is presented to the user the same way as being "locked" (i.e. the account is still displayed in the account switcher and can be selected as the active account)
- User settings are maintained so when the user logs back in the app behaves like they're picking up where they left off.  Vault data however (pretty much everything encrypted for that matter) is removed, otherwise it would defeat the purpose of logging out on timeout.  Logging back in will sync and reconstruct that data.
- When the user logs out via the settings menu (known internally as "user initiated"), then we clean house of all settings and data, making subsequent logins by the same user a …

Usability improvements to handling logout on vault timeout

---

src/App/Pages/Generator/GeneratorPage.xaml
src/App/Styles/Base.xaml

On Android, when Large Font Size settings is set, the password generator view gets truncated at the bottom; so this PR fix this and also that the `Length` number width is correct to be displayed in one line.
Also **we should keep track** of Xamarin Forms PR: [Make sure ScrollViewRenderer on Android is resolving layout changes](https://github.com/xamarin/Xamarin.Forms/pull/15076). That should be released shortly, that should fix this without the workaround.
* **GeneratorPage.xaml:** Wrapped the `ScrollView` in a `ContentView` (_workaround_) so that the layout measurements get updated with Large font size. And also increased `WidthRequest` on the `Length` to be displayed correctly in one line.
Go to Android Accessibility settings and increase the font size and the bottom of the password …

Fix Password Generator view bottom truncated Large Font Size

---

src/App/App.xaml.cs
src/App/Models/AppOptions.cs
src/App/Pages/Accounts/HomePage.xaml
src/App/Pages/Accounts/HomePage.xaml.cs
src/App/Pages/Accounts/HomePageViewModel.cs
src/App/Pages/Accounts/LoginPage.xaml
src/App/Pages/Accounts/LoginPage.xaml.cs
src/App/Pages/Accounts/LoginPageViewModel.cs
src/App/Pages/Settings/SettingsPage/SettingsPageViewModel.cs
src/App/Utilities/AppHelpers.cs
src/Core/Abstractions/IPolicyService.cs
src/Core/Abstractions/IStateService.cs
src/Core/Abstractions/IVaultTimeoutService.cs
src/Core/Enums/VaultTimeoutAction.cs
src/Core/Models/Domain/Account.cs
src/Core/Services/PolicyService.cs
src/Core/Services/StateMigrationService.cs
src/Core/Services/StateService.cs
src/Core/Services/TokenService.cs
src/Core/Services/VaultTimeoutService.cs
src/iOS.Core/Utilities/ASHelpers.cs
src/iOS/AppDelegate.cs

A multitude of fixes, things I missed, etc.  See code changes for details.
* **AppOptions.cs:** Added `HideAccountSwitcher` bool to control this asynchronously when constructing a page
* **HomePage.*:** Replaced "Close" ToolbarItem with a "Cancel" button since there doesn't appear to be a way to alternate with the avatar (only shown when running as iOS extension), hide account switcher based on AppOptions in constructor (so it works in iOS now)
* **LoginPage.*:** Replaced "Close" ToolbarItem with a "Cancel" button since there doesn't appear to be a way to alternate with the avatar (only shown during normal (not vault-timeout) login flow), added disabled Entry visual state for text color when disabling email field (when logging back in after logout via vault timeout), hide account switcher …

Account switching fixes

---

src/Android/Services/DeviceActionService.cs
src/App/Abstractions/IDeviceActionService.cs
src/App/Controls/CipherViewCell/CipherViewCell.xaml
src/App/Controls/CipherViewCell/CipherViewCell.xaml.cs
src/App/Controls/IconLabel.cs
src/App/Controls/SendViewCell/SendViewCell.xaml
src/App/Controls/SendViewCell/SendViewCell.xaml.cs
src/App/Pages/Send/SendGroupingsPage/SendGroupingsPage.xaml
src/App/Pages/Vault/GroupingsPage/GroupingsPage.xaml
src/App/Styles/Base.xaml
src/iOS.Core/Renderers/CustomLabelRenderer.cs
src/iOS.Core/Services/DeviceActionService.cs
src/iOS.Core/Utilities/FontElementExtensions.cs
src/iOS.Core/iOS.Core.csproj

This PR fixes the Large Font Accessibility issues on the Vault and Send views, that were displaying the icons partially when the system font was too big.
* **DeviceActionService.cs:** Added `GetSystemFontSizeScale()` to calculate sizes that are not directly related to fonts like grid columns.
* **CypherViewCell / SendViewCell:** Changed so that icons are columns are adapted to Accessibility Large Fonts
* **IconLabel:** Added `ShouldUpdateFontSizeDynamicallyForAccesibility` to be specific on when we want to update the font size for accesibility. This was added just in case to not affect the whole app thus introducing this change little by little. Then when we address the Accessibillity Large Font issues across the whole app we can make the logic more generic and remove this property.
* …

Fix Large Font Accessibility issues on icons on Vault and Send

---

src/App/Pages/Accounts/LockPageViewModel.cs
src/App/Pages/Settings/SettingsPage/SettingsPageViewModel.cs
src/Core/Abstractions/IStateService.cs
src/Core/Models/Domain/Account.cs
src/Core/Services/StateMigrationService.cs
src/Core/Services/StateService.cs
src/Core/Services/VaultTimeoutService.cs
src/iOS.Core/Controllers/LockPasswordViewController.cs

Fixes to data handling for PIN lock flow caused by my misinterpretation of a specific "key" used for crypto purposes vs a "key" used for storage purposes.
* **Account.cs:** Moved `PinProtected` from `AccountSettings` to `PinProtectedKey` in `AccountKeys` as it represents a value held in memory only (`AccountKeys` is never written to state storage)
* **Everything else:** Updated references to changes made in `Account.cs`, and added `await` to a calls to `_stateService.GetPinProtectedKeyAsync(..)` so null check actually works as expected
https://app.asana.com/0/1166330464508357/1201846609152550

Fix for invalid PIN lock state when switching accounts

---

src/App/Pages/Accounts/LoginPage.xaml
src/App/Pages/Accounts/LoginPage.xaml.cs
src/App/Pages/Accounts/LoginPageViewModel.cs
src/App/Pages/Settings/OptionsPageViewModel.cs
src/App/Resources/AppResources.Designer.cs
src/App/Resources/AppResources.resx
src/Core/Abstractions/IStateService.cs
src/Core/Services/StateService.cs

- Apply theme selections globally (took this approach so we can restore per-account themes in the future by removing a contained block of code)
- Support for account removal from login page (via logout on vault timeout)
- Check for existing account on add-account and prompt to switch if available
* **LoginPage.*:** Added "Remove Account" menu option and supporting code, also added checking for already-added account when logging in a new account
* **OptionsPageViewModel.cs:** Apply theme globally when applied in Settings
* **StateService.cs:** Added `GetUserIdAsync` and `ApplyThemeGloballyAsync` methods
- Change theme then switch users - theme will remain consistent
- Switch to an active logged-out account and expand the overflow menu to use the "Remove Account" option
- Add an account …

Global theme and account removal

---

src/App/Controls/CipherViewCell/CipherViewCell.xaml
src/App/Controls/CipherViewCell/CipherViewCell.xaml.cs

Fix icon image size to be adaptive on Large Font Size Accessibility which also fixes the row height being really high on large vault items.
* **CipherViewCell:** Change the Width/HeightrRequest of the CachedImage icon to be calculated with the font scale.
Test that the icons have the correct size and check this on large vault as well.

Fix vault item icon image size to be adaptive on Large Font Size Accessibility

---

src/App/Pages/Send/SendAddEditPage.xaml.cs

Fix Options to be displayed in one line on add edit Send. The issue was in German (Optionen)
* **SendAddEditPage.xaml.cs:** Removed `WidthRequest` on button options given that now only the first one is being displayed due to #1454 
The `Options` should be displayed correctly in one line, particularly test in German.

Fix Options being seen in two lines on Add/edit Send

---

src/App/Pages/Vault/AddEditPage.xaml
src/App/Styles/Base.xaml

Improve UX on Identity fields, to have phone keyboard and capitalize names and city/state/country. Based on [https://github.com/bitwarden/web/pull/1384](https://github.com/bitwarden/web/pull/1384)
* **Base.xaml:** Added styles for capitalize word/sentence
* **AddEditPage.xaml:** Changed styles for better keyboard UX
On First name, Middle Name and Last Name the keyboard should appear capitalizing each word.
On Phone should open the telephone keyboard
On City, State and Country the keyboard should appear capitalizing the sentence.

Improved keyboard UX on Identity fields

---

src/App/Pages/Accounts/LoginPageViewModel.cs

When checking for an already logged-in account, take the environment into account (otherwise identical emails can't be used across different servers)
* **LoginPageViewModel.cs:** Added `BaseUrl` comparison to existing account check, and moved switch prompt dialog to dedicated method
https://app.asana.com/0/1201803072708593/1201873026592841

Take environment into account when checking for existing account

---

src/App/Pages/Accounts/LockPageViewModel.cs
src/App/Pages/CaptchaProtectedViewModel.cs
src/App/Pages/Settings/SettingsPage/SettingsPageViewModel.cs
src/App/Utilities/AppHelpers.cs
src/Core/Abstractions/IEnvironmentService.cs
src/Core/Services/EnvironmentService.cs

Change link on Settings "Change Master Password" and "Two-Step Login" to go to Web Vault Settings.
* **EnvironmentService.cs:** Added constants for default Web Vault and Snd url and refactored a bit the code to use them and also added a new method to get the web url for Send.
* **SettingsPageViewModel.cs:** Changed the url on "Change Master Password" and "Two-Step Login" to go to the Web Vault Settings
* **Others:** Adapted to the new `EnvironmentService`
For any of the testing, take into consideration that the web url is different depending on what is configured, the precedence is as follows: 
- Web Vault Server URL
- Self-hosted Environment -> Server URL
- Default (https://vault.bitwarden.com)
Test that when clicking on **Settings > Change Master Password** and **Settings > Two-Step …

Changed links on Settings "Change Master Password" and "Two Step Login"

---

src/Core/Services/StateService.cs

App went directly to unlocked vault, skipping bio unlock prompt on cold start when bio unlock was enabled.  Turned out the in-memory bio lock state bool should default to true for the flow to work correctly (overlooked as part of account switching transition)
* **StateService.cs:** Make `BiometricLocked` true by default for cold-start bio unlock flow to function correctly
1. Set vault timeout to something long-ish (15 minute default is fine)
2. Set vault timeout action to Lock
3. Enable biometric unlock support (face, finger, DNA sample, etc.)
4. Swipe away (kill) app
5. Launch app.  With fix: Biometric unlock prompt will be shown.  Without fix: Waltz right into unlocked vault (unless vault timeout period elapsed)

Fix for missing bio unlock on app restart

---

src/App/Pages/Settings/OptionsPageViewModel.cs
src/Core/Abstractions/IStateService.cs
src/Core/Services/StateService.cs

Make the "Disable Website Icons" option global to match desktop.  I'm continuing to follow the `Apply*Globally` pattern established with the Theme change so a single block of code can be removed to restore per-account functionality in the future.
* **StateService.cs:** Created `SetValueGloballyAsync` method to support key/value based settings (values not in the `Account` object)
* **OptionsPageViewModel.cs:** Removed previous `Apply*Global` calls since everything is contained within `StateService` now
https://app.asana.com/0/1201803072708593/1201880420113232

Apply Disable Favicon setting globally to match desktop

---

src/App/Pages/Vault/ViewPage.xaml
src/App/Pages/Vault/ViewPageViewModel.cs

The standard password field displays number and special characters in a different color for better readability. A hidden custom-field currently does not colorize it's value when shown.
Asana task: https://app.asana.com/0/1200804338582616/1201884248598927/f
* **src/App/Pages/Vault/ViewPageViewModel.cs:** Add new public property ColoredHiddenValue which formats the hidden custom field value
* **src/App/Pages/Vault/ViewPage.xaml:** Adjust hidden fieldvalue binding to new property and add text-html to StyleClass
**BEFORE:**
**AFTER:**
When the value of a hidden custom field is shown, it should be colorized as the standard password field

BEEEP: Colorize hidden custom field when value visible

---

src/App/Pages/Accounts/LockPageViewModel.cs
src/App/Pages/Settings/SettingsPage/SettingsPageViewModel.cs
src/App/Utilities/AppHelpers.cs
src/Core/Abstractions/IStateService.cs
src/Core/Models/Domain/Account.cs
src/Core/Services/AuthService.cs
src/Core/Services/StateService.cs
src/Core/Services/VaultTimeoutService.cs
src/iOS.Core/Controllers/LockPasswordViewController.cs

While working on [this](https://github.com/bitwarden/mobile/pull/1818) I discovered I could confuse the app into changing the biometric lock state for non-active accounts. The bio-lock state is now tracked per-account.
* **Account.cs:** Added `BiometricLocked` bool to `AccountKeys` and renamed it to `AccountVolatileData` since it's no longer just keys (this object is never written to storage)
* **StateService.cs:** Replaced `BiometricLocked` property with dedicated methods to use the `Account` object
* **AppHelpers.cs:** Removed the call to set `BiometricLocked` as it's now handled within the call to `LogoutAccountAsync` above it
* **Everything else:** Update syntax to support new async Get/Set BiometricLocked methods in `StateService`
Configure multiple accounts with biometric unlock …

Fix for biometric lock state overlap

---

src/App/Utilities/AppHelpers.cs

URL encode base64 in url parameters. B64 include the `+` character, which is converted to a ` `, which is _not_ a valid base 64 character.
This was causing errors while loading our captcha connectors, and likely our 2fa connectors, for certain languages.
Test captcha functionality with czech locale.

Add url encoding to data parameter

---

src/App/Pages/Accounts/TwoFactorPageViewModel.cs
src/Core/Abstractions/IAuthService.cs
src/Core/Services/AuthService.cs

> Implement `captcha` functionality for the `2fa` page
- **TwoFactorPageViewModel.cs:** Added captcha functionality by using the existing `CaptchaProtectedViewModel`
- **AuthService**: Expanded `LogInTwoFactorAsync` method to take in potentially passed in `captchaToken`. Will only overwrite the existing property if the passed in value is not null.
- Make sure captcha can be triggered/collected from the 2fa component and complete a successful login

[Captcha] Implement for 2fa

---

src/App/App.xaml.cs
src/App/Utilities/AppHelpers.cs
src/Core/Abstractions/IStateService.cs
src/Core/Services/StateService.cs
src/Core/Services/VaultTimeoutService.cs
src/Core/Utilities/ServiceContainer.cs

- Fixed an issue where logging out the active account from the switcher menu removed the data but left the current screen in place (instead of switching to another user or showing the home screen if there was only one user)
- Also made some changes requested in #1826 (will add comments inline on that PR shortly)
* **AppHelpers.cs:** Added logout message for handling logging out of active account
* **StateService.cs:** Added `Async` suffix to `IsActiveAccount` method name
* **App.xaml.cs/VaultTimeoutService.cs/ServiceContainer.cs:** cleanup (see other PR linked above)
Perform a logout on the active (current) account via long-press in the account switching menu and observe behavior

fix for logging out active account from switcher and cleanup

---

.github/workflows/build.yml

Remove the dependency on Microsoft.AppCenter.Crashes from Core on F-Droid build
* **build.yml:** Remove the package node oof Microsoft.AppCenter.Crashes from Core.csproj on F-Droid build
Use some static analysis tool to check that no tracker is found on F-Droid apk. On the linked issue they used "Aurora Warden"

[Build] Remove Microsoft.AppCenter.Crashes from Core on F-Droid

---

src/App/App.xaml.cs
src/Core/Services/VaultTimeoutService.cs

An attempt to streamline the implementation of passing values with "lock" and "logout" messages resulted in missing data, resulting in both messages acting on the active account regardless of context.  This reverts that change so we can rethink later.
* **App.xaml.cs & VaultTimeoutService.cs:** Revert to previous use of Tuple
https://app.asana.com/0/1201803072708593/1201936151872719/f
https://app.asana.com/0/1201803072708593/1201929380000890/f

Fix for lock & logout message parsing issue

---

src/Android/MainActivity.cs

Prevent tap actions from being redirected/missed when another view is obscuring the Bitwarden app.
Right now I've enabled it app wide but I do have stashed code to apply it for specific controls if we need to apply in a more granular way.
* **MainActivity.cs:** Enabled `FilterTouchesWhenObscured` on the root view so nothing on the app is tappable if it's obscured by another toast, dialog, or window (other app)
Use an app that has a transparent or semi-transparent background to interact with Bitwarden app and check whether the controls are tapped like buttons, fields, etc.
If you don't have an app to test this let me know and I'll build a apk with the one I crerated and been using.
Also test to interact with the app when popups/dialogs and toasts are shown to see that I haven't broken …

Prevent tapping on app area if its obscured by another window

---

src/App/Pages/Settings/SettingsPage/ISettingsPageListItem.cs
src/App/Pages/Settings/SettingsPage/SettingsPage.xaml
src/App/Pages/Settings/SettingsPage/SettingsPageHeaderListItem.cs
src/App/Pages/Settings/SettingsPage/SettingsPageListItem.cs
src/App/Pages/Settings/SettingsPage/SettingsPageListItemSelector.cs
src/App/Pages/Settings/SettingsPage/SettingsPageViewModel.cs

Fix Settings crash on iOS 15.4
* **ISettingsPageListItem:** Interface that all items share
* **ISettingsPageHeaderListItem:** Item for the header
* **SettingsPageViewModel** Changed the approach so that group is not used and there is a plain list of items
* **SettingsPageView** Removed the `GroupHeaderTemplate` and added a new template for the header list item
* **SettingsPageListItemSelector** Added the `HeaderTemplate`
Settings page should behave as expected without crashing even if you change tabs rapidly

Fix Settings crash by removing grouped items

---

src/Android/Services/DeviceActionService.cs
src/App/Abstractions/IDeviceActionService.cs
src/App/App.xaml.cs
src/App/Services/MobileStorageService.cs
src/App/Utilities/AppHelpers.cs
src/Core/Constants.cs
src/iOS.Core/Services/DeviceActionService.cs
src/iOS.Core/Utilities/ASHelpers.cs
src/iOS.ShareExtension/LoadingViewController.cs
src/iOS.ShareExtension/LockPasswordViewController.cs
src/iOS/AppDelegate.cs

Fixes account switching issues:
- Update iOS QuickType Bar credentials list when switching accounts without re-syncing
- Don't auto-prompt biometrics when user initiates lock
- Add unique cache and bio integrity keys to ShareExtension to make sure it's working from the most recent data
* **DeviceActionService.cs:** Added `OnAccountSwitchCompleteAsync` for any platform-specific cleanup required after switching accounts (used to refresh or remove iOS QuickType bar credentials)
* **AppHelpers.cs:** Added call to `deviceActionService.OnAccountSwitchCompleteAsync()` upon account switch completion
* **ASHelpers.cs:** Added calls to `RemoveAllCredentialIdentitiesAsync()` to remove stale credentials from the iOS QuickType bar if the active account isn't authed or unlocked, or contains no matches …

Misc fixes for account switching

---

src/App/Resources/AppResources.resx

The option in the ios menu to get to autofill settings is called "Passwords" instead of "Passwords & Accounts"

Update ios Autofill page to match setting's name

---

src/iOS/AppDelegate.cs

Fix crash happened on `AppDelegate -> OnActivated`
* **AppDelegate:** Added null check on `OnActivated` for the `KeyWindow` and also made a const for the `tag` of the splash view.
The flow for the crash to happen is unknown but at least we should check that the splash shown when "minimizing" the app should be displayed correctly and hide correctly when going back to the application.

Fix crash iOS AppDelegate OnActivated

---

src/Core/Services/TokenService.cs

Crash data from both platforms show a common thread where `TokenService.DecodeToken` is throwing `Access token not found` when called from `KeyConnectorService.UserNeedsMigration` > `TokenService.GetIsExternal`.  Based on the 1:1 ratio of users to crashes, this seems like a race condition that occurs once before an active account token is written to storage.  An additional null check of `_accessTokenForDecoding` before calling `DecodeToken` from `GetIsExternal` (following the same logic of the `decoded?["amr"]` null check immediately below it) should prevent this.
* **TokenService.cs:** Return `false` if `_accessTokenForDecoding` if still null after `GetTokenAsync` and before `DecodeToken`

Fix for missing token when checking for key connector migration

---

src/App/App.xaml.cs
src/App/Pages/Vault/AutofillCiphersPage.xaml
src/App/Pages/Vault/AutofillCiphersPage.xaml.cs
src/App/Pages/Vault/AutofillCiphersPageViewModel.cs

Added support for account switching within the autofill UI on Android
* **AutofillCiphersPage.xaml:** Added `AvatarImageSource` to toolbar, additional `ShowNoData` property (explained below), and `AccountSwitchingOverlayView` control to layout
* **AutofillCiphersPage.xaml.cs/AutofillCiphersPageViewModel.cs:** Added avatar & overlay support, plus separate loading & "NoData" states to smooth out UX when switching accounts (previously "NoData" was simply the negated "HasData" resulting in "No Matches" being shown momentarily before showing the matches)
* **App.xaml.cs:** Added additional condition for clearing `Options.Uri` upon exiting the autofill flow (required to prevent main app from falling back into "autofill matches" view when switching accounts, as that triggers the …

Account switching in autofill UI (Android)

---

src/App/Resources/AppResources.resx

- [X ] Other
Change the value for 'copy notes' to 'copy note' since it is applying a single action on 1 item. This source string is already 'copy note' in the browser extension.

Change source string 'copy notes' to 'copy note'

---

src/App/Pages/CaptchaProtectedViewModel.cs

hCaptcha has an option to bypass captcha requests for accessibility purposes, but the flow requires access to existing cookies when using `WebAuthenticator`, which we previously disabled to prevent any unforeseen issues.  This PR enables cookie access within the captcha flow to allow the accessibility bypass to function.  (Note this was only an issue on iOS since `PrefersEphemeralWebBrowserSession` has no effect on Android)
* **CaptchaProtectedViewModel.cs:** Set `PrefersEphemeralWebBrowserSession` to false to allow access to existing cookies during captcha flow
See PS-330 for details

PS-330 Fix a11y issue with hCaptcha on iOS

---

src/App/Pages/Generator/GeneratorPage.xaml
src/App/Pages/Generator/GeneratorPageViewModel.cs
src/Core/Models/Domain/PasswordGenerationOptions.cs
src/Core/Services/PasswordGenerationService.cs
src/iOS.Core/Controllers/PasswordGeneratorViewController.cs

Fix **avoid ambiguous characters** option. On mobile the value was being stored locally inverted of what the user had selected. Wasn't noticed during the session due to caching.
Refactor the name of the property `Ambiguous` to `AvoidAmbiguous`, this naming was misleading.
Fixed bug where the boolean value for the `AvoidAmbiguous` property was being stored inverted.
* **GeneratorPageViewModel.cs:140:** value was being stored inverted of what UI was showing

PS-591 Fix avoid ambiguous characters #1664

---

src/Core/Services/SearchService.cs

When search for ciphers or sends give priority to matches with the `Name` property, show them first in the results list.
* **SearchService.cs:** While running the search methods, created two list, one for matches and another for matches with lower priority. After the search, merged the two lists and retuned the results. This ensures that we only iterate through the list once and give it the order we desire.

PS-592 Name field is not prioritised in search results #1687

---

src/iOS.Extension/LoginListViewController.cs

Master password reprompts were not being checked on the share sheet extension for iOS. This adds that functionality.
* **src/iOS.Extension/LoginListViewController.cs:** add passwordRepromptService and use on `RowSelected`

[PS-673] Add check for master password reprompt to share sheet extension

---

src/App/Pages/Generator/GeneratorPage.xaml
src/App/Resources/AppResources.Designer.cs
src/App/Resources/AppResources.resx

Fix accessibility text for password generator toggles.
The toggles should have a clear announcement that is understandable for assistive technology users.
* **GeneratorPage.xaml:** Added new accessibility text.
* **AppResources.resx:** iOS VoiceOver does not pronounce "a to z" correctly, had to use "A to Z" on lowercase to have the expect result.

[PS-674] Mobile: Accessibility - expand label/name for password generator toggles

---

src/App/Pages/Send/SendAddEditPage.xaml
src/App/Pages/Send/SendAddEditPage.xaml.cs
src/App/Pages/Send/SendAddEditPageViewModel.cs
src/App/Resources/AppResources.Designer.cs
src/App/Resources/AppResources.resx

Make options button and chevron button work as a single button. Add accessibility text to describe the state of the layout.
* **src/App/Pages/Send/SendAddEditPage.xaml**: Moved the click event to the parent `StackLayout`. Added accessibility text to `StackLayout`. Removed accessibility on views inside `StackLayout`.
*  **src/App/Pages/Send/SendAddEditPageViewModel.cs**: Added property for the accessibility text. Raise prop change on `ShowOptions` set.

[PS-676] Accessibility - "Options" expand/collapse control does not announce state

---

src/App/Pages/Vault/GroupingsPage/GroupingsPageViewModel.cs

Fix vault blank after unlocking and closing the modal when the user had locked the vault when viewing a cipher. It may fix #1274 as well.
* **GroupingsPageViewModel.cs:** Added `Clear` call to the `GroupedItems` collection before replacing in order to invalidate the internal `UICollectionView` layout and the Replace to work as expected. This issue was introduce by the update to XF v5.0.0.2401. This workarounds the issue but we should keep checking this for a better solution or hope the next version fixes it.

[PS-536] Fix vault blank after unlocking and back navigation

---

src/App/Controls/CipherViewCell/CipherViewCell.xaml
src/App/Controls/SendViewCell/SendViewCell.xaml
src/App/Pages/TabsPage.cs
src/App/Pages/Vault/GroupingsPage/GroupingsPage.xaml
src/App/Pages/Vault/GroupingsPage/GroupingsPage.xaml.cs
src/App/Pages/Vault/GroupingsPage/GroupingsPageViewModel.cs
src/App/Resources/AppResources.Designer.cs
src/App/Resources/AppResources.resx
src/App/Utilities/AppHelpers.cs
src/Core/Abstractions/IFolderService.cs
src/Core/Abstractions/IPolicyService.cs
src/Core/BitwardenIcons.cs
src/Core/Services/FolderService.cs
src/Core/Services/PolicyService.cs

Added the ability to filter vault ciphers/folders/collections by all/personal/organization when specific conditions are met (account is part of an organization(s) & the Personal Ownership Policy does _not_ apply)
* **GroupingsPage.xaml/xaml.cs/ViewModel.cs:** Added UI & logic for displaying & handling vault filter options & selection
* **TabsPage.cs:** Added `UpdateVaultButtonTitleAsync()` method to change vault button title to `Vaults` or `My Vault` based on filter availability.  Triggered on page appearing as well as sync completion via `BroadcasterService`
* **AppHelpers.cs:** Added `IsShowingVaultFilterAsync()` convenience method
* **FolderService.cs:** Added support for passing in existing `FolderView` list to `GetAllNestedAsync` method to support required flexibility during filter …

[SG-79] Mobile Vault Filter

---

src/App/Pages/Accounts/BaseChangePasswordViewModel.cs
src/App/Pages/Accounts/LockPage.xaml
src/App/Pages/Accounts/LockPageViewModel.cs
src/App/Pages/Accounts/LoginPage.xaml
src/App/Pages/Accounts/LoginPageViewModel.cs
src/App/Pages/Accounts/RegisterPage.xaml
src/App/Pages/Accounts/RegisterPageViewModel.cs
src/App/Pages/Accounts/SetPasswordPage.xaml
src/App/Pages/Accounts/SetPasswordPageViewModel.cs
src/App/Pages/Accounts/UpdateTempPasswordPage.xaml
src/App/Pages/Send/SendAddEditPage.xaml
src/App/Pages/Send/SendAddEditPageViewModel.cs
src/App/Pages/Settings/ExportVaultPage.xaml
src/App/Pages/Settings/ExportVaultPageViewModel.cs
src/App/Pages/Vault/AddEditPage.xaml
src/App/Pages/Vault/AddEditPageViewModel.cs
src/App/Pages/Vault/ViewPage.xaml
src/App/Pages/Vault/ViewPageViewModel.cs
src/App/Resources/AppResources.Designer.cs
src/App/Resources/AppResources.resx

Password show/hide toggles show indicate the state to the user. 
Added text resource to represent the visibility of the password. Used this resource on all password toggles.

PS-675 Added accessibility text to password show/hide toggles

---

src/Android/Android.csproj
src/Android/Renderers/CustomPageRenderer.cs
src/App/Pages/Vault/CiphersPage.xaml
src/App/Resources/AppResources.Designer.cs
src/App/Resources/AppResources.resx

Android back buttons throughout the app don't have accessibility text. Add text to be read by the VoiceOver\TalkBack on the back button.
* **src/Android/Renderers/CustomPageRenderer.cs:** Toolbar back button was only accessible through a custom renderer.

PS-689 Android: Accessibility - back buttons in search and vault > bin lack appropriate accessible name

---

src/App/Pages/Vault/ViewPageViewModel.cs

Update to icons used for Boolean and Linked to use real icons
Icons on Mobile devices aren't displaying properly for Linked and Boolean type
ViewPageViewModel.cs 
Updated to use Bitwarden defined icons for Boolean and linked types

Updating icons for Linked and Boolean fields

---

src/Android/Resources/mipmap-anydpi-v26/ic_launcher.xml
src/Android/Resources/mipmap-anydpi-v26/ic_launcher_round.xml

Adds support for launcher icon themes in Android 13.  (Turns out this doesn't require SDK/target updates that were holding us back in Xamarin)  Reference: https://developer.android.com/about/versions/13/features
* **ic_launcher/round.xml:** Added monochrome element to logo vectordrawable for theme support in Android 13

Adaptive icon theme support in Android 13

---

src/iOS.Autofill/LoginSearchViewController.cs
src/iOS.Core/Utilities/UISearchBarExtensions.cs
src/iOS.Core/iOS.Core.csproj

With these changes, autofill iOS extension searchbar's search text and icon should appear as white for non light themes.
* **LoginSearchViewController.cs**: Invoked new method extension ApplyDarkThemesColors from UISearchBarExtensions.cs
* **UISearchBarExtensions.cs**: Applied white color to search text and icon only for iOS versions greater or equal than 13 because this solution isn't supported for prior versions.
Without the fix:
With the fix:
Dark theme
Black theme
Nord theme

PS-587 - Fix searchbar search textfield and icon colors for dark themes

---

src/App/Controls/ExtendedCollectionView.cs
src/App/Pages/Generator/GeneratorHistoryPage.xaml
src/App/Pages/Send/SendGroupingsPage/SendGroupingsPage.xaml
src/App/Pages/Send/SendsPage.xaml
src/App/Pages/Settings/FoldersPage.xaml
src/App/Pages/Settings/SettingsPage/SettingsPage.xaml
src/App/Pages/Vault/AutofillCiphersPage.xaml
src/App/Pages/Vault/CiphersPage.xaml
src/App/Pages/Vault/GroupingsPage/GroupingsPage.xaml
src/App/Pages/Vault/PasswordHistoryPage.xaml
src/iOS.Core/Renderers/CollectionView/ExtendedCollectionViewRenderer.cs
src/iOS.Core/Renderers/CollectionView/ExtendedGroupableItemsViewController.cs
src/iOS.Core/iOS.Core.csproj

- [] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
Add extended logs for `CollectionView` on iOS when doing `UpdateTemplatedCell` to have more context on the AppCenter crashes.
* **ExtendedCollectionView.cs:** Added `ExtraDataForLogging` property to add any extra information we want from the usage of the collection view.
* **ExtendedCollectionViewRenderer.cs:** Added this renderer in order to override the controller used in the collection view renderer.
* **ExtendedGroupableItemsViewController.cs:** Added this to override the `UpdateTemplatedCell` method and add a try...catch to extend the logging information with the one provided by `ExtraDataForLogging` to have more context on AppCenter crashes.

[PS-785] Added logs for exceptions on UpdateTemplatedCell

---

src/App/Pages/Vault/AddEditPage.xaml.cs
src/App/Pages/Vault/CiphersPage.xaml
src/App/Pages/Vault/CiphersPage.xaml.cs
src/App/Pages/Vault/CiphersPageViewModel.cs
src/App/Pages/Vault/GroupingsPage/GroupingsPage.xaml
src/App/Pages/Vault/GroupingsPage/GroupingsPage.xaml.cs
src/App/Pages/Vault/GroupingsPage/GroupingsPageViewModel.cs
src/App/Styles/Base.xaml

- [SG-362] Added vault org filter support to cipher search page
- [SG-356] Pre-select org when creating new cipher from org-filtered list
* **GroupingsPage.xaml:** Updated button style
* **GroupingsPage.xaml.cs:** Pass selected org ID to `AddEditPage`
* **GroupingsPageViewModel.cs:** Make `GetVaultFilterOrgId()` public
* **AddEditPage.xaml.cs:** Add support for `organizationId` in constructor
* **CiphersPage.xaml/xaml.cs/ViewModel.cs:** Added UI & logic for displaying & handling vault filter options & selection
* **Base.xaml:** Added new `list-row-button-text` style to fix color of vault filter button to match mocks
[SG-362]: https://bitwarden.atlassian.net/browse/SG-362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SG-356]: …

[SG-79] Add filter to search and preselect org in new cipher

---

src/Android/MainApplication.cs
src/Android/Services/ClipboardService.cs
src/Android/Services/DeviceActionService.cs
src/App/Pages/Generator/GeneratorHistoryPageViewModel.cs
src/App/Pages/Generator/GeneratorPageViewModel.cs
src/App/Pages/Vault/PasswordHistoryPageViewModel.cs
src/App/Pages/Vault/ViewPageViewModel.cs
src/App/Services/MobilePlatformUtilsService.cs
src/App/Utilities/AppHelpers.cs
src/Core/Abstractions/IClipboardService.cs
src/Core/Abstractions/IPlatformUtilsService.cs
src/iOS.Core/Services/ClipboardService.cs
src/iOS.Core/Utilities/iOSCoreHelpers.cs

Android 13 introduces some changes to clipboard behavior when copying text:
https://developer.android.com/about/versions/13/features/copy-paste
This PR does the following:
* Prevent toasts when copying text on Android 13+ so as to not conflict with the new indicator
* Pass the `IS_SENSITIVE` flag to the `ClipboardManager` to prevent showing copied text in the new popup in Android 13+
_**Note 1: Currently this can't be tested in the emulator as the latest image (at least for ARM64) is still internally returning `32` for the API version (should be `33`).  I installed the June 8 beta on a Pixel 4a for testing.**_
_**Note 2: As of the latest beta released yesterday (June 8) the OS behavior doesn't line up with the documented behavior (Instead of obfuscated dots in the popup it shows "Tap to …

Clipboard handling adjustments for Android 13

---

src/Core/Services/PolicyService.cs

Fixes issue where the vault filter wouldn't appear if any org a user is a member of has the Personal Ownership policy enabled
* **PolicyService.cs:** Removed personal ownership policy check from `ShouldShowVaultFilterAsync` method (originally added due to a misinterpretation of the original task on my part)

[SG-79] [SG-376] Fixed vault filter display issue when personal ownership policy enabled

---

src/App/Pages/Vault/CiphersPageViewModel.cs
src/App/Pages/Vault/GroupingsPage/GroupingsPageViewModel.cs
src/App/Pages/VaultFilterViewModel.cs
src/Core/Services/PolicyService.cs

- Hide the "My Vault" option if the Personal Ownership Policy is enabled in an organization
- Hide the vault filters altogether if the Personal Ownership & Single Org policies are both enabled in an organization
* **GroupingsPageViewModel/CiphersPageViewModel.cs:** Added `_hideMyVaultFilterOption` bool based on `_policyService.PolicyAppliesToUser(PolicyType.PersonalOwnership)`
* **PolicyService.cs:** Added additional policy checks in `ShouldShowVaultFilterAsync()` method

[SG-79] [SG-389] Additional logic around vault filter display

---

src/App/Pages/VaultFilterViewModel.cs

This fixes an issue where org items were not appearing when the vault filter control was hidden due to the single org and personal ownership policies both being enabled.
* **VaultFilterViewModel.cs:** Update logic to handle mixed policy variations/changes better on initial load and refresh.  A delay is required before setting `ShowVaultFilter` to properly draw the org name in the vault filter if the filter was previously hidden but now shown after a refresh.

[SG-390] Fix for missing org items with single org & personal ownership enabled

---

src/Android/MainApplication.cs
src/App/App.xaml.cs
src/App/Controls/AccountSwitchingOverlay/AccountSwitchingOverlayViewModel.cs
src/App/Services/MobileStorageService.cs
src/App/Utilities/AccountManagement/AccountsManager.cs
src/Core/Abstractions/IStateService.cs
src/Core/Constants.cs
src/Core/Services/StateService.cs
src/Core/Utilities/AccountsManagerMessageCommands.cs
src/iOS.Core/Utilities/AccountSwitchingOverlayHelper.cs
src/iOS.Core/Utilities/iOSCoreHelpers.cs

On iOS, when coming from background to the app we should check if any extension has switched users, and if so, change the user as well on the app.
* **MainApplication.cs:** Updated `StateService` to include the messenger
* **App.xaml.cs:** Calls check for extension user id change when resuming the app (background to foreground)
* **AccountSwitchingOverlayViewModel.cs:** Added `FromIOSExtension` and if that's the case save the user id if the account has been switched. Also, refactored a bit the if to have less branches and applied the constants.
* **AccountsManager.cs:** Changed invoking on main thread to be awaited, thus the exception can bubble up
* **Constants.cs:** Added `iOSExtensionActiveUserIdKey` to be used to store the active user id on the extension if it has changed so that it …

[SG-386] iOS Update user state when coming from background

---

src/App/Pages/Vault/CiphersPageViewModel.cs
src/App/Pages/Vault/GroupingsPage/GroupingsPageViewModel.cs
src/App/Pages/VaultFilterViewModel.cs

`InitVaultFilterAsync` wasn't being called on the secondary view page, resulting in missing data.  In order to do that from `GroupingsPage` the logic for setting the `ShowVaultFilter` property was broken out into its own method, and only called from the MainPage.  Both methods are called back to back on `CiphersPage` to maintain previous behavior.
* **GroupingsPageViewModel.cs:** Call `InitVaultFilterAsync` regardless of page, and `ShowVaultFilterIfNeededAsync` on MainPage only
* **CiphersPageViewModel.cs:** Call `InitVaultFilterAsync` and `ShowVaultFilterIfNeededAsync` back to back to maintain previous behavior
* **VaultFilterViewModel.cs:** Separate setting of `ShowVaultFilter` property to its own method `ShowVaultFilterIfNeededAsync`

[SG-392] Fix for vault filter selection carryover to secondary page

---

src/App/Pages/VaultFilterViewModel.cs

This fixes the issue where personal items added prior to joining an org with the personal ownership policy enabled were not being shown if the single org policy was also enabled.
* **VaultFilterViewModel.cs:** Removed the forced filter set to org when both policies are enabled, instead forced to "All Vaults".

[SG-393] Fix for missing personal items added prior to joining org with personal ownership policy

---

src/App/Controls/AccountSwitchingOverlay/AccountSwitchingOverlayView.xaml.cs
src/iOS.Core/Utilities/AccountSwitchingOverlayHelper.cs

On Autofill, after hiding the account switching overlay the user can't select any items. So this fixes the tap area.
* **AccountSwitchingOverlayView.xaml.cs:** Added `AfterHide` action to invoke after hiding the account switching overlay
* **AccountSwitchingOverlayHelper.cs:** Hide the container of the account switching overlay after the overlay hidden animation finishes. Fix one tiny animation issue when displaying the overlay

[SG-396] Fix tappable area after hiding account switching on Autofill

---

src/App/Pages/Accounts/LockPage.xaml.cs
src/App/Pages/Accounts/LockPageViewModel.cs

Fix crash produced when focussing the pin/master password entry on the lock page after choosing the fallback method on a failed biometric scan.
I couldn't reproduced this but there are a lot of crashes reported on AppCenter so just fixed it where it's appearing to crash.
Also improved the code so that the ViewModel have fewer direct accesses to the View/Page.
* **LockPage.xaml.cs:** Improved the code making the `SecretEntry` centralizing the logic with the `PinLock` to get the correct entry. Also perform the logic of Focusing on the `Page` invoking it on the main thread to avoid the crash.
* **LockPageViewModel.cs:** Moved the focus action to the page, given that the VM should not do this directly on MVVM. Also added `WeakEventManager` so we don't have to worry about memory leaks.
I …

EC-149 Fix crash when trying to Focus on Lock page

---

src/Android/Services/ClipboardService.cs
src/App/Pages/Vault/ViewPageViewModel.cs

Fix possible crash when copying password on cipher item view
* **ClipboardService.cs:** Added try catch ignore for the specific exception on the issue reported
* **ViewPageViewModel.cs:** Improved the copying commands

[EC-297] Fix possible crash when copying password on cipher item view

---

src/App/Pages/Accounts/SetPasswordPageViewModel.cs
src/Core/Models/Request/OrganizationUserResetPasswordEnrollmentRequest.cs

Add user verification to reset password request We only need master password hash because this is currently only used for sso password setting after auto-provisioning. Key Connector is not involved in these accounts

[PS-1051] Add user verification to reset password request

---

src/iOS.Core/Utilities/AccountSwitchingOverlayHelper.cs
src/iOS.Core/Utilities/ImageSourceExtensions.cs

Fixes crash produced when creating the avatar image on iOS Autofill
* **AccountSwitchingOverlayHelper.cs:** Added exception handling, default image to return and some logging
* **ImageSourceExtensions.cs:** Added proper logging
When an error occurs on creating the avatar image then the default one will be displayed

[EC-308] Fix crash on avatar image creation on iOS Autofill

---

src/App/Pages/Vault/ViewPageViewModel.cs

Closes https://github.com/bitwarden/mobile/issues/1985
Fixes the problem of boolean custom fields showing the opposite of their value at the moment
* **src/App/Pages/Vault/ViewPageViewModel.cs:** Swap around the icons used

[PS-1074] Use correct icon for checked/unchecked boolean

---

src/Android/Accessibility/AccessibilityHelpers.cs
src/Android/Autofill/AutofillHelpers.cs
src/Android/Resources/xml/autofillservice.xml

This adds support for iodé Browser (https://gitlab.com/iode/os/apps/iodebrowser), a Firefox fork developed for the iodéOS privacy-oriented rom (but can be used independently of the rom).

[EC-326] Add support for iodé Browser

---

src/App/Controls/AvatarImageSource.cs

Fix getting the first letters on avatar image creation. There are some cases when more spaces are added, at the beginning, at the end or in the middle that causes the method to fail.
* **AvatarImageSource.cs:** Sanitized data on getting first letters so that it doesn't fail when more spaces are added

[EC-323] Fix error when getting the first letters on avatar image creation

---

src/App/Pages/Settings/SettingsPage/SettingsPage.xaml.cs
src/App/Pages/Settings/SettingsPage/SettingsPageListItem.cs
src/App/Pages/Settings/SettingsPage/SettingsPageViewModel.cs

Fix crash happening on phones with Vietnamese language when trying to enter to Password Autofill on iOS.
The action was being taken after comparing the title of the setting item, and on Vietnamese there are two strings translated the same thus it was misleading on the action to take.
* **SettingsPage.xaml.cs:** Refactored so that we avoid the string comparison and now it just calls for the ViewModel command for the execution.
* **SettingsPageListItem.cs:** Added `ExecuteAsync` func to add the action to perform on each item
* **SettingsPageViewModel.cs:** Moved all the actions to each item and added command to execute the item's action. I think this is better because it avoids the comparison and it's easier and more direct to set up.

[EC-306] Fix crash on Vietnamese language when trying to enter Password Autofill on iOS

---

src/App/Abstractions/IAccountsManager.cs
src/App/App.xaml.cs
src/App/Utilities/AccountManagement/AccountsManager.cs
src/Core/Services/AuthService.cs
src/iOS.Autofill/CredentialProviderViewController.cs
src/iOS.Core/Controllers/BaseLockPasswordViewController.cs

When the user enters invalid credentials on lock screen on iOS Autofill five times it crashes.
* **App.xaml.cs:** Added exception handling on navigation call
* **AccountsManager.cs:** Made public the logout method and refactor a bit
* **AuthService.cs:** Uses the constant for loggedOut now
* **CredentialProviderViewController.cs:** Added a bunch of try...catch and fix some async work 
* **BaseLockPasswordViewController.cs:** Now it calls the proper log out method of the account manager and refactor a bit to reuse code

[EC-312] Fix crash on entering invalid credentials five times on iOS Autofill

---

.github/workflows/release.yml

At times, we find that we need to re-run a workflow to publish to an app store. We need the ability to have more selection over the specific stores. This adds a boolean input for the f-droid step, which defaults to true.
* **.github/workflows/release.yml:** Add input option for f-droid release.

Add publish options to release workflow

---

src/App/Pages/Accounts/EnvironmentPageViewModel.cs

Fixed the validation of environment urls in Environment Settings page to also validate URLs without http:// or https://  allowing the successful saving of URLs with and without http:// or https:// .
**src/App/Pages/Accounts/EnvironmentPageViewModel.cs**: Fixed validation from checking if URL is UriKind.Absolute to check if URL is UriKind.RelativeOrAbsolute.

[SG-467] Fix environment url validations

---

src/App/Pages/Vault/ViewPage.xaml
src/App/Pages/Vault/ViewPageViewModel.cs
src/Core/Models/View/FieldView.cs

Screen Reader should be able to read if the Boolean icon value on custom fields is Enabled or Disabled
* **ViewPage.xaml**: Added `AutomationProperties.Name` accessibility property to the CustomField boolean IconLabel.
* **ViewPageViewModel**: Added a new property named `ValueAccessibilityText` that has the value to use on the xaml accessibility property.

[PS-1080] Added text alternative to Boolean custom field icon

---

src/App/Pages/Accounts/TwoFactorPage.xaml
src/App/Pages/Accounts/TwoFactorPage.xaml.cs
src/App/Pages/Accounts/TwoFactorPageViewModel.cs
src/iOS.Autofill/CredentialProviderViewController.cs
src/iOS.Autofill/iOS.Autofill.csproj
src/iOS.Core/Services/DeviceActionService.cs
src/iOS.Core/iOS.Core.csproj
src/iOS.Extension/iOS.Extension.csproj
src/iOS.ShareExtension/iOS.ShareExtension.csproj

On iOS Extensions when 2FA view is presented, it should allow to change between different 2FA if setup.
* **TwoFactorPage.xaml:** Changed Toolbar item More Clicked event to Command
* **TwoFactorPage.xaml.cs:** Removed More_Clicked event and moved logic to VM command
* **TwoFactorPageViewModel.cs:** Added MoreCommand with the logic of the More_Clicked and changed it to use `DeviceActionService` instead of directly `Page` to show the action sheet in order for it to work on the extensions.
* **iOS.Autofill.csproj:** Added reference to the "more"/"three dots" images to get in the bundle
* **DeviceActionService.cs:** Improved null check of the ViewController, if that one was null on some cases the Task was not finishing given that it was not setting the result.
* **iOS.Extension.csproj:** …

[EC-341] Fix show alternative 2FA on iOS extensions

---

src/Android/Properties/AndroidManifest.xml
src/App/Pages/Vault/GroupingsPage/GroupingsPage.xaml
src/App/Pages/Vault/GroupingsPage/GroupingsPage.xaml.cs
src/App/Pages/Vault/GroupingsPage/GroupingsPageListItem.cs
src/App/Pages/Vault/GroupingsPage/GroupingsPageViewModel.cs
src/App/Resources/AppResources.Designer.cs
src/App/Resources/AppResources.resx

After demo the authenticator feature, it was decided that the way we were showing the TOTP codes needed a rework. If the user is premium, It now has a vault entry that navigates to a new page only for TOTP codes.
* **src/App/Pages/Vault/GroupingsPage/GroupingsPageViewModel.cs:306:**
When the user only has one Cipher with TOTP and removes the configuration in the edit page, when he comes back from edit, it will be redirected to the main vault page.

[SG-416] Authenticator toggle remake 

---

src/Android/Services/AndroidPushNotificationService.cs
src/Android/Services/DeviceActionService.cs
src/App/Abstractions/IDeviceActionService.cs
src/App/Abstractions/IPushNotificationService.cs
src/App/Pages/Settings/SettingsPage/SettingsPageViewModel.cs
src/App/Resources/AppResources.Designer.cs
src/App/Resources/AppResources.resx
src/App/Services/NoopPushNotificationService.cs
src/Core/Abstractions/IStateService.cs
src/Core/Constants.cs
src/Core/Services/StateService.cs
src/iOS.Core/Services/DeviceActionService.cs
src/iOS/Services/iOSPushNotificationService.cs

Add a setting to the Bitwarden mobile app under the “Security” section: “Approve login requests”
Default state is Disabled.
When user Enables the option, check to see if the Bitwarden app has notification permissions. If not, request them. Even if the user does not enable notifications, the Approve login requests feature is enabled.
* **src/iOS/Services/iOSPushNotificationService.cs:** Added new method because iOS has different approach on notifications status. I needed a way to tell if the user had blocked the "alert notifications" in order to redirect to the settings.
New entry in the security section of settings tab:
Dialog to provide additional information and enable/disable the feature:
If the user doesn't have notification "Alert" enable, show this dialog to open settings directly:

[SG-381] Passwordless - Add setting to Mobile

---

.github/workflows/build.yml

Add workaround for broken windows 2022 runner.

Add workaround for broken windows 2022 runner

---

src/App/Pages/Accounts/RegisterPage.xaml
src/App/Pages/Accounts/RegisterPageViewModel.cs

This PR fixes the #2009 issue. It adds a margin between the switch and the privacy policy text in the sign-up screen.
* **RegisterPage.xaml:** Removed the binding property for the margin and changed to a fixed value. Since I haven't found any style for the switch, I kept the definition here.
* **RegisterPageViewModel.xaml:** Since now the value is the same for iOS and Android, the property is no longer necessary.

[PS-1228] Android: Label of terms of service and privacy policy switch is too close to the actual switch in the sign-up screen

---

src/Android/Android.csproj
src/Android/Effects/NoEmojiKeyboardEffect.cs
src/App/Effects/NoEmojiKeyboardEffect.cs
src/App/Pages/Generator/GeneratorPage.xaml
src/iOS.Core/Effects/NoEmojiKeyboardEffect.cs
src/iOS.Core/iOS.Core.csproj

Remove the possibility of adding emojis on the word separator at Generator when passphrase is selected
* **NoEmojiKeyboardEffect.cs:** Created effect with settings to not show emojis on the keyboard, both on iOS and Android.
* **GeneratorPage.cs:** Added NoEmojiKeyboardEffect to the passphrase generator Entry

[PS-1009] Changed keyboard on Passphrase generator to not allow emojis

---

src/App/Pages/Vault/GroupingsPage/GroupingsPageTOTPListItem.cs

Fix Bug: 
When copying the TOTP code from the “Verification Codes” page, the code is copied in the format “### ###”. In order to fix this problem, removing the space is necessary.
Replaced the space dividing the two parts of the code from the copied string.

[SG-598] Copying TOTP Code from Verification Codes page copies space between sets of numbers

---

src/App/Pages/Vault/ScanPage.xaml.cs

User needs to be able to add TOTP authentication key manually without the need to include the full URI. 
Removed unnecessary verification for manually adding TOTP Secret Key

[SG-599] "Cannot read authenticator key" if URI is not included before TOTP Secret

---

src/Core/Services/BitwardenFileUploadService.cs

Fixes https://github.com/bitwarden/mobile/issues/2018
* **BitwardenFileUploadService.cs ** Sets the content-type of the data/file upload to application/octet-stream to be consistent with other bitwarden client.

[PS-1252] Fix Content Type for file upload

---

src/Android/MainActivity.cs

The fonts on Android are too big on some devices. Removed Android native scaling as xamarin `NamedSize` is already scaling the fonts.
* **MainActivity.cs:** Set the native Android font scaling to 1. So that it doesn't scale as the Xamarin `NamedSize` is already scaling the text
Max font size with Android scaling:
Max font size without Android scaling:

[PS-191] Improve support for larger fonts Android

---

src/Android/MainActivity.cs
src/Android/Push/FirebaseMessagingService.cs
src/Android/Services/AndroidPushNotificationService.cs
src/App/Abstractions/IPushNotificationService.cs
src/App/App.xaml.cs
src/App/Pages/Accounts/LoginPasswordlessPage.xaml
src/App/Pages/Accounts/LoginPasswordlessViewModel.cs
src/App/Resources/AppResources.Designer.cs
src/App/Resources/AppResources.resx
src/App/Services/NoopPushNotificationService.cs
src/App/Services/PushNotificationListenerService.cs
src/Core/Abstractions/IStateService.cs
src/Core/Constants.cs
src/Core/Enums/NotificationType.cs
src/Core/Models/Response/NotificationResponse.cs
src/Core/Models/Response/PasswordlessLoginResponse.cs
src/Core/Services/StateService.cs
src/iOS/AppDelegate.cs
src/iOS/Services/iOSPushNotificationHandler.cs
src/iOS/Services/iOSPushNotificationService.cs

Configure the mobile app to be able to receive and process a new notification type associated with passwordless login. 
Added configuration to be able to show local notifications to the user and dismiss them. 
* **src/App/App.xaml.cs:**
Added subscription in the broadcast service for `unlock` and `passwordlessLoginRequest`. Every time the user unlocks its vault, if there is any pending request, then the app should show the accept/decline modal. If the user in within the app and a new passwordless login notification arrives, it will broadcast a `passwordlessLoginRequest` message, showing the  the accept/decline modal.
* **src/Android/Services/IPushNotificationService.cs:**  
`SendLocalNotification` `DismissLocalNotification` added methods to the interface and following platform …

[SG-472] Add configuration for new notification type

---

.github/workflows/build.yml
.github/workflows/crowdin-pull.yml

The GitHub action Azure Key Vault is being deprecated and will no longer be maintained. The outcome of the related spike offers a solution to implement as a drop-in replacement using bash and the Az CLI. All references for the `Azure/get-keyvault-secrets` action will need to be replaced with this bash step in all our workflows.

Update deprecated Azure Key Vault in workflows

---

src/Android/MainApplication.cs
src/App/App.xaml.cs
src/App/Utilities/AccountManagement/AccountsManager.cs
src/Core/Utilities/AccountsManagerMessageCommands.cs
src/iOS.Core/Utilities/iOSCoreHelpers.cs

… to trigger a check for login requests.
When the user have more than one account logged in and sends a login request for the not active (still unlocked) account , The user sees the push notification but when switches to the account that received the request the user is not being redirected to the login request screen.
Passwordless request check was not being triggered because there was no "unlock" message being broadcasted. Added new broadcast message when account is switched to trigger passwordless login requests check.
- If this …

[SG-691] Login request is not displayed after changing accounts

---

src/Android/MainActivity.cs
src/Android/Services/AndroidPushNotificationService.cs
src/App/Abstractions/IPushNotificationListenerService.cs
src/App/Abstractions/IPushNotificationService.cs
src/App/Models/NotificationData.cs
src/App/Pages/Accounts/LoginPasswordlessViewModel.cs
src/App/Services/NoopPushNotificationListenerService.cs
src/App/Services/NoopPushNotificationService.cs
src/App/Services/PushNotificationListenerService.cs
src/Core/Constants.cs
src/iOS/Services/iOSPushNotificationHandler.cs
src/iOS/Services/iOSPushNotificationService.cs

Tapping Push Notification does not take you to account the request is for.
Added new method in `src/App/Services/PushNotificationListenerService.cs` to handle notification tap logic.

[SG-702] Tapping Push Notification does not open the account the request is for

---

src/Android/Android.csproj
src/Android/Receivers/NotificationDismissReceiver.cs
src/Android/Services/AndroidPushNotificationService.cs
src/App/Abstractions/IPushNotificationListenerService.cs
src/App/Services/NoopPushNotificationListenerService.cs
src/App/Services/PushNotificationListenerService.cs
src/Core/Constants.cs
src/iOS/Services/iOSPushNotificationHandler.cs

Fixe bug when the user dismissed the passwordless login notification by swiping, the data related to the login request was not erased. 
**src/App/Services/PushNotificationListenerService.cs:** added new method to handle notification dismiss events from platforms. This removes from preferences the data stored for that request.
**src/iOS/Services/iOSPushNotificationHandler.cs:** code to handle the event of dismissing notification on iOS
**src/Android/Receivers/NotificationDismissReceiver.cs:** new broadcast receiver to handle the dismiss event on Android.
**src/Core/Constants.cs:** fixed a bug on android where the constant wasn't matching with the property name.
- Please add **unit tests** where it makes …

[SG-703] Login request is not removed after dismissing push notification

---

src/App/Controls/AvatarImageSource.cs

The order of avatars (not accounts) would invert each time the account switching list was opened on iOS.  Missed it the first time through due to the subtle earth-tones all my test accounts ended up with.
* **AvatarImageSource.cs:** Added missing `_id` check to `Equals` fixed the object comparison (thanks @fedemkr )

Fix for avatar sequence issue on iOS account switching modal

---

src/Core/Services/ApiService.cs

Be more precise to force log out when receiving 400 error code by ensuring that the response error is invalid grant.
This is related to the clients PR [400s only log out on invalid grant error #3924](https://github.com/bitwarden/clients/pull/3924)
* **ApiService.cs:** After parsing the json, log out the user if the response error is "invalid_grant".

SG-786 - Fix 400 error code log outs without invalid_grant

---

src/App/Pages/Generator/GeneratorPageViewModel.cs
src/Core/Abstractions/ITokenService.cs
src/Core/Services/TokenService.cs

Added a call to refresh the token used for decoding before getting the user's email in order to fix a crash.
* **ITokenService.cs**
* **TokenService.cs :**  Added new method to refresh token without returning it.
* **GeneratorPageViewModel.cs :**  Made sure token is refreshed before using it to get user's email.

[SG-769] Fix crash by ensuring that token for decoding is refreshed before use

---

src/App/App.xaml.cs

Fix bug where If the user never answers the switch accounts pop up, the lock is never released. This was problematic because when tapping a notification while pop-up was showing, the user navigates to the other account automatically and the pop-up is never dismissed.
Removed await to allow the execution flow and lock to be released.

[SG-800] Selecting notification for inactive account on iOS while app is open does not display the request

---

src/App/Services/PushNotificationListenerService.cs

Fix bug when tapping a login request at the same time the modal is appearing.
On notification tap check if there is a pending login request.

[SG-802] iOS clicking push notification after login request has appeared makes it disappear

---

src/App/Pages/Accounts/LoginPageViewModel.cs

Only show 'remove account' if the account already exists in the accounts list
* **src/App/Pages/Accounts/LoginPageViewModel.cs:** Add `SavedEmail` property that checks if the email belongs to an account in the accounts list and only show `remove account` if they are there.

[SG-808] Only show 'remove account' option if user is in Accounts list

---

src/App/App.xaml.cs

Temporary fix for issue where multiple accounts are not getting login with device requests. 
* **src/App/App.xaml.cs:** Add `syncCompleted` to commands that will trigger a check to get passwordless requests

[SG-816] Add syncCompleted to check to get passwordless requests

---

.github/workflows/release.yml

The Github deployment was getting created (and sent to Jira) for Dry Run triggers.
* **release.yml:** Added check to only run Deployment-related jobs when it is not a Dry Run

Changed Github deployments not to trigger on Dry Run

---

src/App/App.xaml.cs
src/App/Pages/Accounts/LoginPasswordlessRequestViewModel.cs
src/App/Pages/Accounts/LoginPasswordlessViewModel.cs
src/App/Resources/AppResources.Designer.cs
src/App/Resources/AppResources.resx
src/Core/Models/Response/PasswordlessLoginResponse.cs

Depends on  #https://github.com/bitwarden/server/pull/2412
When responding to a previously answered passwordless device, show a message saying the request is not longer valid.

[SG-778] Adjust mobile client to handle previously-responded-to passwordless request

---

src/App/App.xaml.cs
src/App/Pages/Accounts/LoginPasswordlessRequestViewModel.cs
src/App/Pages/Accounts/LoginPasswordlessViewModel.cs
src/Core/Abstractions/IApiService.cs
src/Core/Abstractions/IAuthService.cs
src/Core/Models/Response/PasswordlessLoginResponse.cs
src/Core/Services/ApiService.cs
src/Core/Services/AuthService.cs
src/Core/Services/SyncService.cs
src/Core/Utilities/ServiceContainer.cs

If the user for some reason did not receive the notification to login with the device, sync the vault will fetch all login requests and pick the most recent and valid one.
* **SyncService.cs:** when vault sync is triggered, get all login requests and set in the stateService the most recent. After that triggers a normal passwordless login request flow.

[SG-816] Get all login requests and pick the most recent

---

src/App/Pages/Settings/SyncPageViewModel.cs
src/App/Pages/Vault/GroupingsPage/GroupingsPageViewModel.cs
src/Core/Abstractions/ISyncService.cs
src/Core/Services/SyncService.cs

Adding the possibility to manually get pending login requests. This will be always fetched even though the sync is not forced.
Exposed the Sync Login Requests method to be called separately from the **FullSync**. This is a temporary solution. A tech dept ticket was created to move all Passwordless code to an independent service.

[SG-831] Pull Down Sync does not retrieve pending AuthRequests

---

build.cake

This fixes Android's QA apk crashing while trying to attach a file. A recently added file (`FileService.cs`) with a reference to the package name was missing from the script.
* **build.cake:** Script will now change the package name in Android's `FileService.cs`

[SG-837] QA build crashing while attaching a file

---

src/App/Services/PushNotificationListenerService.cs

Tapping the login request notification before the modal showed up, was launching a new window and the modal would never appear

[SG-860] Add condition to execute notification tap code

---

src/watchOS/bitwarden/bitwarden WatchKit Extension/Controls/AvatarView.swift
src/watchOS/bitwarden/bitwarden WatchKit Extension/Utilities/ColorUtils.swift
src/watchOS/bitwarden/bitwarden WatchKit Extension/Utilities/StringExtensions.swift
src/watchOS/bitwarden/bitwarden WatchKit Extension/ViewModels/CipherListViewModel.swift
src/watchOS/bitwarden/bitwarden WatchKit Extension/Views/CipherListView.swift
src/watchOS/bitwarden/bitwarden.xcodeproj/project.pbxproj

Add avatar header on Apple Watch
* **AvatarView:** Custom view to display the avatar icon (Circle with the letters inside)
* **ColorUtils:** Some utils to init a `Color` from a `hex` string and also to get its RGBA components
* **StringExtensions:** Added extension to add left padding on a string
* **CipherListViewModel:** Fix issue on the state check
* **CipherListView:** Removed outer `VStack` and added section for the user avatar header
`AvatarView` is an adaptation from `AvatarImageSource` of the iPhone application. One caveat to take into consideration was when dealing with bitwise operations and overflow c# handles it internally by going to an `unchecked` context while in swift you need to mark the operation explicitly.
So what in C# is:
```c#
(hash << 5) - hash
```
In swift we need …

[EC-759] Add avatar header Apple Watch MVP

---

src/App/Services/BaseWatchDeviceService.cs
src/Core/Enums/WatchState.cs
src/Core/Models/View/WatchDTO.cs
src/iOS.Core/Services/WatchDeviceService.cs
src/watchOS/bitwarden/bitwarden WatchKit Extension/Models/VaultTimeoutAction.swift
src/watchOS/bitwarden/bitwarden WatchKit Extension/Models/WatchDTO.swift
src/watchOS/bitwarden/bitwarden WatchKit Extension/Services/StateService.swift
src/watchOS/bitwarden/bitwarden WatchKit Extension/Utilities/BWState.swift
src/watchOS/bitwarden/bitwarden WatchKit Extension/ViewModels/BWStateViewModel.swift
src/watchOS/bitwarden/bitwarden WatchKit Extension/WatchConnectivityManager.swift

Removed (commented) things that are not going to be included on the MVP:
- Vault timeout sync
- Unlock state sync
Also fix issue on the `applicationContext` sent to have a key based on time to ensure faster delivery.
* **WatchDeviceService:** Added time based suffix to key sent in `applicationContext` to have faster delivery of the message to the watch. If the same key is used on different syncs then the OS may defer the delivery of the message until a better time.
* **WatchConnectivityManager:** Now it needs to get the first key of the `applicationContext` dictionary that starts with the actual name of the key. We need to do this given that we don't know the full string of the key due to the added time-based-suffix
* **Other:** Commented out things not included on the MVP
- Please check …

[EC-786] Apple Watch MVP Sync fixes

---

src/Android/Services/DeviceActionService.cs
src/Android/Services/WatchDeviceService.cs
src/App/Abstractions/IDeviceActionService.cs
src/App/Pages/Settings/SettingsPage/SettingsPageViewModel.cs
src/App/Services/BaseWatchDeviceService.cs
src/Core/Abstractions/IStateService.cs
src/Core/Abstractions/IWatchDeviceService.cs
src/Core/Constants.cs
src/Core/Enums/WatchState.cs
src/Core/Services/StateService.cs
src/iOS.Core/Services/DeviceActionService.cs
src/iOS.Core/Services/WatchDeviceService.cs
src/iOS.Core/Utilities/WCSessionManager.cs
src/iOS/AppDelegate.cs
src/watchOS/bitwarden/bitwarden WatchKit Extension/Utilities/BWState.swift

Implement iOS setting for "Connect to Watch" and also added logic to handle activation of the watch communication session accordingly.
* **SettingsPageViewModel:** Moved "Connect to Watch" to the proper place, implemented toggle Watch connection
* **StateService:** Added `ShouldConnectToWatch` flag to be used alongside with the watch sync and to see if the watch communication session should be activated or not.
* **BaseWatchDeviceService:** Implemented logic to check the aforementioned flag to know whether to sync data or not and whether the connection should be activated. Also to signal the watch to wipe the data when the connection is turned off from iOS app settings.
* **AppDelegate:** Check the flag to see if the watch connection should be activated depending on the current account
* …

[EC-579] Apple Watch MVP iOS settings and activation

---

src/App/Pages/Vault/CipherAddEditPage.xaml.cs
src/App/Pages/Vault/ScanPage.xaml
src/App/Pages/Vault/ScanPage.xaml.cs
src/App/Pages/Vault/ScanPageViewModel.cs
src/App/Resources/AppResources.Designer.cs
src/App/Resources/AppResources.resx

When a user denies camera access for the QR code scan, they are neither prompted again nor are they given a modal that says ‘You must enable camera access…’ etc. when they tap the icon to add an authenticator code to an item that does not yet have one. This occurs in Prod as well; the camera icon/Set up TOTP buttons do not respond when selected if you have previously denied the setting.This poses an issue in the Authenticator UI because there is no way to manually add a new TOTP without accessing those screens, however, you can edit an existing one.
Expected behavior: When the user has camera permissions turned off, clicking the “add new TOTP” button launches the “Enter Key Manually” mode. If the user then clicks the “scan QR Code” link (attempting to switch to camera mode) we show the …

[SG-601] Enhance experience when user denies camera access in Authenticator

---

src/watchOS/bitwarden/bitwarden WatchKit Extension/Controls/TrackableWithHeaderListView.swift
src/watchOS/bitwarden/bitwarden WatchKit Extension/Localization/en.lproj/Localizable.strings
src/watchOS/bitwarden/bitwarden WatchKit Extension/Utilities/ColorUtils.swift
src/watchOS/bitwarden/bitwarden WatchKit Extension/Utilities/ViewExtensions.swift
src/watchOS/bitwarden/bitwarden WatchKit Extension/ViewModels/CipherListViewModel.swift
src/watchOS/bitwarden/bitwarden WatchKit Extension/Views/CipherItemView.swift
src/watchOS/bitwarden/bitwarden WatchKit Extension/Views/CipherListView.swift
src/watchOS/bitwarden/bitwarden WatchKit Extension/WatchConnectivityManager.swift
src/watchOS/bitwarden/bitwarden.xcodeproj/project.pbxproj

Add search header to cipher list on watch
* **CipherListViewModel:** Added search logic combining publishers of all the ciphers and the search term. A little hack here to add a row when no ciphers are found after a search has been done.
* **CipherListView:** Changed `List` to be a `TrackableWithHeaderListView` now, added the search header view. Also added interaction with the scroll to make the search header appear/disappear. Also update the scroll initial position when loading the ciphers to be in the avatar instead of the header. Furthermore, polished the code splitting the whole tree into different views on computed properties are also extracted the list item view into its own file `CipherItemView`
* **TrackableWithHeaderListView:** List wrapper that has a header (I'll use it for the …

[EC-616] Apple Watch MVP Cipher Search

---

src/iOS.Autofill/CredentialProviderViewController.cs
src/iOS.Core/Utilities/iOSCoreHelpers.cs
src/iOS.Extension/LoadingViewController.cs
src/iOS/AppDelegate.cs

Fix regression where the iOS autofill extension was not working due to services incorrectly registration.
* **iOSCoreHelpers:** Moved the `IWatchDeviceService` registration here on the new method `RegisterFinallyBeforeBootstrap` intended to be used for stuff that need to be setup before bootstrap and after all the other registrations have been done.
* **AppDelegate:** Calls the new `RegisterFinallyBeforeBootstrap` to setup extra stuff before bootstrap. Moved the watch device  service registration there.
* **CredentialProviderViewController:** Calls the new `RegisterFinallyBeforeBootstrap` to setup extra stuff before bootstrap.
* **LoadingViewController:** Calls the new `RegisterFinallyBeforeBootstrap` to setup extra stuff before bootstrap.
- Please check for formatting errors (`dotnet …

[EC-833] Fix WatchDeviceService registration to be called appropiately

---

src/iOS.Core/Services/WatchDeviceService.cs
src/iOS.Core/Utilities/DictionaryExtensions.cs
src/iOS.Core/Utilities/WCSessionManager.cs
src/watchOS/bitwarden/bitwarden WatchKit Extension/Helpers/KeychainHelper.swift
src/watchOS/bitwarden/bitwarden WatchKit Extension/Localization/en.lproj/Localizable.strings
src/watchOS/bitwarden/bitwarden WatchKit Extension/Services/StateService.swift
src/watchOS/bitwarden/bitwarden WatchKit Extension/Utilities/BWState.swift
src/watchOS/bitwarden/bitwarden WatchKit Extension/Utilities/Queue.swift
src/watchOS/bitwarden/bitwarden WatchKit Extension/ViewModels/BWStateViewModel.swift
src/watchOS/bitwarden/bitwarden WatchKit Extension/ViewModels/CipherListViewModel.swift
src/watchOS/bitwarden/bitwarden WatchKit Extension/WatchConnectivityManager.swift
src/watchOS/bitwarden/bitwarden.xcodeproj/project.pbxproj
src/watchOS/bitwarden/bitwarden/WatchConnectivityManager.swift

Add `kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly` to the accessible on Keychain items.
Also, added state to show to the user when the Apple Watch Passcode is not set and also a check to see if that situation changed and if a passcode is set afterwards to signal the iPhone to trigger a sync.
* **WatchDeviceService:** Subscribed to `OnMessagedReceived` to trigger the sync when the action is the one intended
* **WCSessionManager:** Improved naming, changed `Console.WriteLine` to `Debug.WriteLine`, removed sending application context on main thread, added exception logging, and added method to get message with reply.
* **KeychainHelper:** Added `kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly` accessible on save items and added `hasDeviceOwnerAuth` to check whether the user has a Passcode …

[EC-835] Add kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly on Watch Keychain

---

README.md

Fixes #2263
Fixes the broken link in the README to our contributing guidelines mobile section.
* **README.md:** Fix links to point to https://contributing.bitwarden.com/getting-started/clients/mobile/

[PS-2119] Fix link to contributing docs

---

.github/workflows/enforce-labels.yml

I realized via https://github.com/bitwarden/mobile/pull/2044 that we do not block merging when the `needs-qa`-label was added.
The enforcement on the `needs-qa` label was added with https://github.com/bitwarden/clients/pull/3450 for the clients and with https://github.com/bitwarden/server/pull/2248 for the server, but we must have missed the mobile repo.
* **.github/workflows/enforce-labels.yml:** Add `needs-qa` to the BANNED_LABELS and mentioned it in the description.
- If this change has particular **deployment requirements** - …

[PS-2162] Add `needs-qa` label to enforce-labels workflow

---

store/fdroid/config.py

Recent changes to F-Droid have reduced tolerance for incorrect repo URLs.  I can confirm that the latest 1.15 client no longer experiences the reported issue, the upcoming 1.16 build maintains the strict requirement.  This will require re-publishing our F-Droid repo to get things moving again.  More info:
https://gitlab.com/fdroid/fdroidclient/-/issues/2390
https://gitlab.com/rfc2822/fdroid-firefox/-/merge_requests/54
* **config.py:** Added `/repo` to the end of the `repo_url`
- If this change has particular **deployment …

[PS-2172] Fix repo url for F-Droid 1.15+

---

src/Android/Properties/AndroidManifest.xml

Fix bug where browser urls are not launching.
Steps:
Launch App
Navigate to Settings
Tap on “Import Items” or “Change Master Password” or “Help and feedback”
Actual Results:
Settings page links are not launching browser
After confirming in the documentation, when target API 30 or above, one needs to add extra info to the manifest.
https://learn.microsoft.com/en-us/xamarin/essentials/open-browser?tabs=android

[SG-978] Mobile - Settings page links are not launching browser

---

.github/workflows/build.yml

Utilizes a popular Action to process .NET test results and upload them as a report artifact. Much easier to parse 
results than working through the commandline output.
* **.github/workflows/build.yml:** Additional step for report processing

Upload and process test results as an artifact and report

---

src/App/Pages/Accounts/RegisterPageViewModel.cs
src/App/Pages/Accounts/SetPasswordPageViewModel.cs
src/Core/Constants.cs

Updating the KDF iterations to the same value as clients https://github.com/bitwarden/clients/pull/4482
Getting KdfIterations value from a global constant to be used by all the VMs that need it.
* **Constants.cs:** Added `KdfIterations` constant value with 600k
* **RegisterPageViewModel.cs, SetPasswordPageViewModel.cs:** Using the `KdfIterations` value from `Constants.cs`

[PS-2275] Update the default kdf iterations to 600k.

---

src/App/Pages/Generator/GeneratorPage.xaml
src/App/Pages/Generator/GeneratorPageViewModel.cs
src/App/Resources/AppResources.Designer.cs
src/App/Resources/AppResources.resx
src/App/Utilities/IconGlyphExtensions.cs
src/Core/Enums/ForwardedEmailServiceType.cs
src/Core/Models/Domain/UsernameGenerationOptions.cs
src/Core/Models/Domain/UsernameGeneratorConfig.cs
src/Core/Services/ApiService.cs
src/Core/Services/UsernameGenerationService.cs

Add option to select Fastmail and Duck Duck Go as options in the forwarded email alias providers.
Default to none-selected if this is the first use of the screen. Otherwise default to the last selected.
[src/App/Pages/Generator/GeneratorPage.xaml](https://github.com/bitwarden/mobile/pull/2304/files#diff-6646362e986f583f0da02c8c01fad244607c0d4dd38e211dd22f7d7ac64664dd): 
New UI views to hold api keys for new services added. (This can be refactored in the future to avoid having multiple views)
[src/App/Pages/Generator/GeneratorPageViewModel.cs](https://github.com/bitwarden/mobile/pull/2304/files#diff-06d6f35a0e203bdae8fe03dade2ef549a73850f02dde233ac921a0fd7214dbc5):
Add new entries for Fastmail and Duck Duck Go to `ForwardedEmailServiceTypeOptions`.
Added properties to bind to the UI for …

[SG-516] Additional forwarded email providers for username generator - mobile

---

.github/workflows/build.yml

Don't fall out when a test run fails. The reporter will still be able to capture results.
* **.github/workflows/build.yml:** Fallout removal

Remove fallout from test run

---

src/App/Pages/Accounts/LockPageViewModel.cs
src/App/Pages/Accounts/RegisterPageViewModel.cs
src/App/Pages/Accounts/SetPasswordPageViewModel.cs
src/App/Pages/Accounts/UpdateTempPasswordPageViewModel.cs
src/App/Pages/Settings/SettingsPage/SettingsPageViewModel.cs
src/Core/Abstractions/ICryptoService.cs
src/Core/Abstractions/IStateService.cs
src/Core/Constants.cs
src/Core/Models/Domain/Account.cs
src/Core/Models/Domain/KdfConfiguration.cs
src/Core/Models/Request/RegisterRequest.cs
src/Core/Models/Request/SetKeyConnectorKeyRequest.cs
src/Core/Models/Request/SetPasswordRequest.cs
src/Core/Models/Response/IdentityTokenResponse.cs
src/Core/Models/Response/PreloginResponse.cs
src/Core/Services/AuthService.cs
src/Core/Services/CryptoService.cs
src/Core/Services/PclCryptoFunctionService.cs
src/Core/Services/StateMigrationService.cs
src/Core/Services/StateService.cs
src/iOS.Core/Controllers/BaseLockPasswordViewController.cs
src/iOS.Core/Controllers/LockPasswordViewController.cs

This PR adds configuration option support for the argon2 kdf.
For all files: Basically anywhere where kdfIterations / kdfType is used (in requests, stateservice) we simply add the optional variables kdfMemory and kdfParalleism. The defaults are: 64 (MiB) for memory and 4 parallelism.
This reopens mistakenly closed: https://github.com/bitwarden/mobile/pull/2322
I just applied the commit as a patch on the latest master, though there were 2 errors, which I can check in ~2 hours.

[PS-2358] Add kdf configuration options

---

src/Android/Autofill/FieldCollection.cs

Improving the way we recognize fields as Username and Password at the login autofill to avoid filling username fields with passwords or not detecting username fields as valid username fields
* **FieldCollection.cs:** Added common username terms 
On fields that identify as password we check if they don't have "Username terms" on hints to avoid filling passwords on usernames.
In cases we haven't found any Username Field, we will check if there is any Field with any hint or IdEntry that matches our "Username Terms"
- If this change has …

[PS-2330][PS-2329][PS-2332][PS-2333] Checking for username terms on Android Autofill

---

src/Core/Services/AuthService.cs

ref: https://bitwarden.atlassian.net/browse/PS-2413
With the introduction of Argon2, KdfMemory and KdfParallelism need to be set to the account profile in state service. This spot was missed in the original work, resulting in null values for these fields.
* **AuthService.cs:** Add KdfMemory and KdfParallelism to the `AccountProfile` object saved after login.

[PS-2413] set all kdf params on account profile

---

src/App/Resources/AppResources.resx

For consistency with other clients, the button option for the login with device request should be changed to read,
“Log in with device”
Currently, it reads,
“Log In with another device”

[SG-1035] Fix label for log in with device

---

src/App/Controls/PasswordStrengthProgressBar/PasswordStrengthProgressBar.xaml.cs

MP strength bar color is Blue for weakest password and should be red.
https://user-images.githubusercontent.com/4648522/217921416-140c6035-3298-4814-936c-adce1e138927.mov

[SG-1055] MP strength bar color is Blue for weakest password and should be red

---

src/App/Pages/Accounts/HomePageViewModel.cs

Fix ‘Account already added Would you like to switch to it now?’ prompt loop when performing login with an account already added.
* **src/App/Pages/Accounts/HomePageViewModel.cs:** Added new condition to only prompt the user if the chosen account is authenticated.

[SG-1056] Fix login prompt loop for added accounts

---

src/Android/Services/DeviceActionService.cs
src/App/Pages/Settings/SettingsPage/SettingsPageViewModel.cs
src/Core/Abstractions/IStateService.cs
src/Core/Constants.cs
src/Core/Models/Domain/Account.cs
src/Core/Services/StateMigrationService.cs
src/Core/Services/StateService.cs
src/Core/Utilities/CoreHelpers.cs

These changes allow the app to retain account-specific settings after a hard logout (previous would only retain on soft logout).  In order to accomplish this without re-architecting the way soft logout works with multiple users, some stored settings (`VaultTimeout`, `VaultTimeoutAction`, and `ScreenCaptureAllowed`) had to be relocated from the state object to normal local storage with an account-specific pref name (follows existing pattern).  This requires a new state migration, which resulted in a conflict with a previous migration with 3 values that were originally account-specific (`DisableFavicon`, `Theme`, and `AutoDarkTheme` but used trickery to apply globally to match other clients) requiring migrating those to true global values (remove the trickery).
* **StateService.cs:** 
* …

[PS-2280] Retain app settings on logout

---

src/Android/Services/ClipboardService.cs
src/App/Services/MobilePlatformUtilsService.cs
src/Core/Abstractions/IClipboardService.cs
src/iOS.Core/Services/ClipboardService.cs

Copy confirmation toasts were originally removed on Android 13+ devices since the system provides its own notification now. However we’re seeing that functionality removed by some device makers, giving users the impression that copy isn’t working at all.  As there’s no official way to know if this is happening, we're restoring the toast across the board.  Better to have some overlap than no notification at all.
* **ClipboardService.cs:** Removed `IsCopyNotificationHandledByPlatform` method
* **MobilePlatformUtilsService.cs:** Removed `_clipboardService.IsCopyNotificationHandledByPlatform` check before showing toast
- …

[PS-2520] Restore copy confirmation toast on Android 13+

---

src/App/Pages/Vault/AutofillCiphersPageViewModel.cs
src/App/Pages/Vault/CipherSelectionPage.xaml
src/App/Pages/Vault/CipherSelectionPage.xaml.cs
src/App/Pages/Vault/CipherSelectionPageViewModel.cs
src/App/Pages/Vault/OTPCipherSelectionPageViewModel.cs

On the OTP handler flow, add the possibility to create a new login cipher with the OTP key already filled in.
* **CipherSelectionPage.xaml / ...xaml.cs:** Added "Add" toolbar item on iOS and changed click event handlers with commands on adding
* **CIpherSelectionPageViewModel:** Added `AddCommand` and template method to implement it
* **AutofillCiphersPageViewModel:** Moved add cipher implementation to this VM on the add command action
* **OTPCipherSelectionPageViewModel:** Implemented add cipher with the otp data
- If this change has …

[PM-1131] OTP Handling - Create cipher with OTP filled

---

src/Core/Utilities/OtpData.cs

The Issuer and Account name should be set correctly on the `OtpData` from the OTP uri
* **OTPData:** Fix set Issuer and Account name from the label. The correct order is first the `Issuer` and then the `AccountName`

[PM-1386] Fix OTP Data Issuer and Account name being set correctly

---

src/App/App.xaml.cs
src/App/Pages/Accounts/LoginPasswordlessRequestViewModel.cs
src/App/Pages/Settings/LoginPasswordlessRequestsListPage.xaml
src/App/Pages/Settings/LoginPasswordlessRequestsListViewModel.cs
src/Core/Models/Response/PasswordlessLoginResponse.cs
src/Core/Services/AuthService.cs

- Modify mobile client to generate the fingerprint phrase themselves, ignoring the one retrieved from the API
- Remove fingerprintPhrase from the AuthRequestResponse
* **src/Core/Models/Response/PasswordlessLoginResponse.cs:**
Renamed property containing the `FingerprintPhrase`, ignoring api value.
* **src/Core/Services/AuthService.cs:**
After fetching the data from the `ApiService`, `AuthService` will populate the values for the `FingerprintPhrase`.

[PM-1078] Login with Device - Change mobile to not get fingerprint from API

---

src/App/Pages/Accounts/LoginPageViewModel.cs

Ignore Know Device api endpoint error on mobile.
- Check for api 401 error and silently log the exception instead of showing an error dialog
- Moved the hide loading to finally block.

[PM-1497] Known device api error

---

src/Core/Services/StateMigrationService.cs

Fixed incorrect type during migration
* **StateMigrationService.cs:** Changed `int?` to `string` because strings aren't ints 🤦 

[PM-1571] Fix migration crash

---

src/Core/Abstractions/IStateMigrationService.cs
src/Core/Services/StateMigrationService.cs
src/Core/Services/StateService.cs

This makes the storage migration process thread safe to cover for cases where migration is inadvertently called more than once during app initialization.
* **StateMigrationService.cs:** Combine checking for and performing migration into a single step behind a `SemaphoreSlim` to make sure migration will complete before executing a subsequent check.
* **StateService.cs:** Replace `NeedsMigration()` and `Migrate()` with `MigrateIfNeeded()`

[PM-1646] Add thread safety to migration process

---

src/App/Controls/CipherViewCell/CipherViewCell.xaml.cs
src/App/Pages/Vault/GroupingsPage/GroupingsPageViewModel.cs

Fix cipher options not working on lists due to binding failing.
* **CipherViewCell:** Changed type of the `ButtonCommand` from `Command<CipherView>` to `ICommand` to make it more generic and easy to bind to any type of command in the ViewModel. This was causing the issue due to the change on the ViewModel to an `AsyncCommand<...>`
* **GroupingsPageViewModel:** Updated to use the `AsyncCommand<...>` as in the other places.

[PM-1615] Fix cipher options not working in lists due to binding failing

---

src/App/Controls/CipherViewCell/CipherViewCell.xaml.cs
src/App/Pages/Vault/GroupingsPage/GroupingsPageViewModel.cs

Reverts bitwarden/mobile#2456 so QA can test before merging.

Revert "[PM-1615] Fix cipher options not working in lists due to binding failing"

---

src/Android/MainApplication.cs
src/App/Utilities/AccountManagement/AccountsManager.cs
src/Core/Abstractions/IConditionedAwaiterManager.cs
src/Core/Services/ConditionedAwaiterManager.cs
src/Core/Services/EnvironmentService.cs
src/Core/Utilities/ServiceContainer.cs
src/iOS.Core/Utilities/iOSCoreHelpers.cs

There are some cases where a race-condition happens on `AccountsManager` registration and it ends up crashing the iOS app.
* **ConditionedAwaiterManager:** Added this class as a helper to have a condition task that can be awaited and can be completed/faulted from other services without needing any dependencies. This uses the `AwaiterPrecondition` to handle the proper task depending on the condition.
* **AccountsManager:** It now awaits for the precondition `EnvironmentUrlsInited` in order to perform any calls which is why before was being registered too late and now it can be registered before the App.App constructor is called.
* **EnvironmentService:** Change to update the `ConditionedAwaiterManager` -> `EnvironmentUrlsInited` precondition accordingly depending if it succeeds or fails.
* …

[PM-1576] Fix Race condition AccountsManager registration

---

src/iOS.Core/Services/FileService.cs

Some users are experiencing difficulties when trying to download attachments or exports. After selecting "Save in files" it should show the file system so that the user could select where to save it. Although sometimes it doesn't appear.
* **FileService.cs:** Changed `UIDocumentInteractionController` with `UIDocumentPickerViewController`. This way it opens immediately the "file system" and works consistently.

[PM-1731] Using UIDocumentPickerViewController when saving files on iOS

---

src/Core/Services/PolicyService.cs

We are now updating the vault timeout information from new policies that come in from a sync. During this, I checked the existence of a `MaximumVaultTimeout` policy using `.Equals(default)`, but this didn't seem to actually check the values for null. 
I have now changed it to check the Value of the `KeyValuePair` for null instead.
Will need to be cherry-picked to `rc`

[PM-1906] Fix syncing issue with new policies method to update Vault Timeout

---

src/Android/MainApplication.cs
src/Android/Services/BiometricService.cs
src/App/Pages/Accounts/LockPage.xaml
src/App/Pages/Accounts/LockPageViewModel.cs
src/App/Resources/AppResources.Designer.cs
src/App/Resources/AppResources.resx
src/App/Services/MobilePlatformUtilsService.cs
src/App/Services/MobileStorageService.cs
src/Core/Abstractions/IBiometricService.cs
src/Core/Abstractions/IPlatformUtilsService.cs
src/Core/Abstractions/IStateService.cs
src/Core/Constants.cs
src/Core/Services/StateMigrationService.cs
src/Core/Services/StateService.cs
src/iOS.Autofill/LockPasswordViewController.cs
src/iOS.Core/Controllers/BaseLockPasswordViewController.cs
src/iOS.Core/Controllers/LockPasswordViewController.cs
src/iOS.Core/Services/BiometricService.cs
src/iOS.Core/Utilities/AccountSwitchingOverlayHelper.cs
src/iOS.Core/Utilities/iOSCoreHelpers.cs
src/iOS.Extension/LockPasswordViewController.cs
src/iOS.ShareExtension/LockPasswordViewController.cs

This modification tracks system-level biometric invalidation (new fingerprint/face added, etc.) at the account level by storing 'approval flags' with the user ID & representations of the current 'state' of biometrics in the following format:
accountBiometricIntegrityValid_{userId}_{systemBioIntegrityState}
The presence of this key indicates to the app that this particular user is clear to use biometrics in the state provided.  Once the state changes and the key is no longer valid, the user must re-enter their password to save a new key with the updated state for their user ID.
_Android notes:_
Our Android implementation never stored any kind of system biometric state because validation relies on key functions throwing specific exceptions.  For this to work a state was added in the form of …

[PM-1817] Expand biometric integrity checks to the account level

---

src/App/Pages/Vault/CipherSelectionPage.xaml
src/App/Pages/Vault/CipherSelectionPage.xaml.cs

🐛 Fix the toolbar icon for the avatar switch on OTP cipher selection that wasn't being loaded.
* **CipherSelectionPage.xaml:** Changed toolbar item priority to "-1" which seems to fix the bug and not the icon loads and updates in the UI correctly
* **CipherSelectionPage.xaml.cs:** Enabled back the account toolbar icon loading and surrounded it in a try...catch so that the app doesn't crash if the icon can't be loaded somehow.

[PM-1352] Fix Avatar toolbar icon on OTP cipher selection

---

.github/labeler.yml
src/watchOS/bitwarden/bitwarden WatchKit Extension/Models/Mocks/CipherMock.swift
src/watchOS/bitwarden/bitwarden WatchKit Extension/ViewModels/CipherDetailsViewModel.swift
src/watchOS/bitwarden/bitwarden WatchKit Extension/Views/CipherDetailsView.swift
src/watchOS/bitwarden/bitwarden WatchKit Extension/Views/CipherItemView.swift
src/watchOS/bitwarden/bitwarden WatchKit Extension/Views/CipherListView.swift

Fix TOTP code regeneration after Always On Display. Also, blur username, TOTP code and timer when entering in Always On Display.
* **CipherDetailsViewModel:** Extracted the generation of the code to a specific method so that it can be reused.
* **CipherDetailsView:** Regenerates the code when the view becomes active (after coming from background/always on display) and also marked the username, TOTP code and timer value as sensitive so they are blurred when entering into Always On Display.
* **CipherListView:** Blur username on Always On Display
* **CipherItemView:** Blur username on Always On Display
- If this change …

[PM-1748] Fix Watch TOTP details on Always On Display

---

src/Android/Android.csproj
src/App/App.csproj
src/Core/Core.csproj
src/iOS.Autofill/iOS.Autofill.csproj
src/iOS.Extension/Info.plist
src/iOS.Extension/iOS.Extension.csproj
src/iOS.ShareExtension/Info.plist
src/iOS.ShareExtension/iOS.ShareExtension.csproj
src/iOS/Info.plist
src/iOS/iOS.csproj
test/Common/Common.csproj
test/Core.Test/Core.Test.csproj
test/Core.Test/Models/Request/SendRequestTests.cs

Dependency updates galore.
**_Note 1:_** Some Android libs (`AndroidX.AppCompat`, `AndroidX.MediaRouter`, and `Google.Material.Android`) could not be updated to their latest versions due to being compiled at a higher build target than the current public `Xamarin.Forms` (fixed in an upcoming XF release - I tested against `5.0.0.8491` and everything seemed happy).
**_Note 2:_** Updating `MessagePack*` breaks the Android build with the following error:
```
Xamarin.Android.Legacy.targets(317, 5): [XA2002] Can not resolve reference: `Microsoft.NET.StringTools`, referenced by `MessagePack`. Please add a NuGet package or assembly reference for `Microsoft.NET.StringTools`, or remove the reference to `MessagePack`.
```
I'm not sure of the correct path forward here so I'll need input from @fedemkr …

[PM-2219] Dependency Updates

---

src/App/Pages/Accounts/HomePageViewModel.cs

When environments change we need to fetch the feature flags for that environment.
Added force refresh on picker selection and environment update.
https://github.com/bitwarden/mobile/assets/4648522/30b8c41a-f6a1-429f-8a23-edba1d50e6f0

[PM-2347] Refresh feature flags when environment urls change

---

src/App/Lists/ItemLayouts/CustomFields/HiddenCustomFieldItemLayout.xaml
src/App/Lists/ItemLayouts/CustomFields/TextCustomFieldItemLayout.xaml
src/App/Pages/Vault/CipherAddEditPage.xaml
src/App/Resources/AppResources.Designer.cs
src/App/Resources/AppResources.resx

The entries when adding a cipher should have a name assigned for screen reader.
* **All files:** Added the entires to the accessible tree and set their accessible name. I couldn't use `LabeledBy` feature of Xamarin Forms because it doesn't work on iOS as stated in the [docs](https://learn.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/accessibility/automation-properties#automationpropertieslabeledby).

[PM-1798] Improve ScreenReader when adding a cipher

---

src/Android/Autofill/FieldCollection.cs

This PR allows user/pass field detection to utilize fallback code on both fields if hints are only available for one (previously a single hint would prevent fallback detection from executing resulting in only the username or password field being filled).
* **FieldCollection.cs:** Only return if matching hint found, otherwise execute fallback detection in `PasswordFields` & `UsernameFields`

[PM-2392] Enhancement to login field detection for Android autofill

---

src/App/Resources/AppResources.Designer.cs
src/App/Resources/AppResources.resx
src/iOS.Autofill/LockPasswordViewController.cs
src/iOS.Core/Controllers/BaseLockPasswordViewController.cs

Fix extension freeze when tapping the "Go" (return button) on the keyboard when unlocking.
* **BaseLockPasswordViewController:** `GetAwaiter().GetResult()` was causing a deadlock, so changed that to `FireAndForget()` which also logs exceptions, if any. And added the flag so that we avoid multiple executions. Just in case, there seems to be a lot of line changes but it's mainly adding a `try...finally`
* **LockPasswordViewController:** Added `FireAndForget` so that we log the exceptions, if any.
* **AppResources:** Added period in the warning for the argon2id.
- If this change requires a **documentation update** - …

[PM-2575] Fix extension freeze when using the return button on the keyboard when unlocking

---

src/App/Lists/ItemLayouts/CustomFields/BooleanCustomFieldItemLayout.xaml
src/App/Lists/ItemLayouts/CustomFields/HiddenCustomFieldItemLayout.xaml
src/App/Lists/ItemLayouts/CustomFields/LinkedCustomFieldItemLayout.xaml
src/App/Lists/ItemLayouts/CustomFields/TextCustomFieldItemLayout.xaml
src/App/Pages/Vault/CipherAddEditPage.xaml

* **CipherAddEditPage.xaml:**  Adding locators for all the Login/Card/SecureNote/Identity item fields
* **TextCustomFieldItemLayout.xaml:** Adding locators for title/value fields
* **BooleanCustomFieldItemLayout.xaml:** Adding locators for title/value fields
* **HiddenCustomFieldItemLayout.xaml:** Adding locators for title/value fields
* **LinkedCustomFieldItemLayout.xaml:** Adding locators for title/value fields
- If this change …

[PM-2544] Adding AutomationIDs for CipherAddEditViewPage elements

---

src/App/Pages/Generator/GeneratorHistoryPage.xaml
src/App/Pages/Generator/GeneratorPage.xaml

* **GeneratorPage.xaml:** Adding IDs for all the interactable elements displayed for passwords/usernames
* **GeneratorPageHistory.xaml:** Adding IDs for each cell, apart from the locators for each nested element

Adding AutomationIDs on Generator page elements

---

src/App/Controls/CipherViewCell/CipherViewCell.xaml
src/App/Controls/SendViewCell/SendViewCell.xaml
src/App/Pages/Send/SendsPage.xaml
src/App/Pages/Vault/CiphersPage.xaml

* **CipherViewCell.xaml:** Adding locators for Cipher cell elements
* **SendViewCell.xaml:** Adding locators for Send cell elements
* **CiphersPage.xaml:** Adding locators for cipher list, empty list label and Search bar
* **SendsPage.xaml:** Adding ids for each send cell

[PM-2611] Adding IDs for Cipher/Send search results

---

src/App/Pages/Vault/CipherAddEditPage.xaml
src/App/Pages/Vault/CipherDetailsPage.xaml

* **CipherDetailsPage.xaml:** Adding AutomationIDs cipher elements and sections

[PM-2545] Adding Automation IDs for CipherDetailsPage elements

---

src/App/Pages/Vault/AttachmentsPage.xaml

* **AttachmentsPage.xaml:** Adding AutomationIDs for Attachment cells, labels, and buttons

[PM-2690] Adding IDs for AttachmentPage elements

---

src/App/Pages/Settings/SettingsPage/SettingsPage.xaml
src/App/Pages/Settings/SettingsPage/SettingsPageListItem.cs

* **SettingsPage.xaml:** Adding IDs for all the setting options + statuses
* **SettingsPageListItem.cs:** Adding new `AutomationId` variable

[PM-2678] Adding IDs for Settings Page elements

---

src/App/Pages/Settings/FolderAddEditPage.xaml
src/App/Pages/Settings/FoldersPage.xaml
src/App/Pages/Settings/OptionsPage.xaml

* **FolderAddEditPage.xaml:**  Adding AutomationIDs
* **FoldersPage.xaml:** Adding IDs for cells and setting statuses
* **OptionsPage.xaml:** Adduig IDs to elements

[PM-2688] Adding IDs for Options and Folders pages

---

src/App/Pages/Send/SendAddEditPage.xaml
src/App/Pages/Send/SendGroupingsPage/SendGroupingsPage.xaml
src/App/Pages/Send/SendGroupingsPage/SendGroupingsPageListItem.cs
src/App/Pages/Send/SendsPage.xaml
src/App/Pages/Vault/AttachmentsPage.xaml

* **SendAddEditPage.xaml:** Adding IDs for each Send element
* **SendGroupingsPage.xaml:** Adding IDs for Send lists
* **SendGroupingsPageListItem.xaml:** Adding a new variable to make AutomationIDs dynamic
* **SendsPage.xaml:** Adding IDs for label displayed when send list is empty

[PM-2737] Adding AutomationIDs for Send page elements

---

src/Android/MainActivity.cs
src/App/App.xaml.cs
src/App/Pages/Vault/AttachmentsPageViewModel.cs
src/Core/Abstractions/IVaultTimeoutService.cs
src/Core/Services/VaultTimeoutService.cs

This reverts commit 0288a6659c9841379e2727cd44d6033fbb467497.
Still presenting problems in QA, reverting for `rc` cut

Revert "reset lock delay when returning from activity result (#2539)"

---

src/App/Pages/Settings/SettingsPage/SettingsPageViewModel.cs
src/App/Resources/AppResources.Designer.cs
src/App/Resources/AppResources.resx

For users without a master password, the unlock settings need to be different:
- Vault timeout action defaults to “log out”
- Vault timeout action “lock” is only available as an option if the user has enabled PIN unlock or biometrics unlock.
- If user disables PIN/Biometric unlock methods, then the vault timeout action defaults back to “log out”
- Get DecryptionOptions to check if the user has master password set. 
if the user doesn't have a master password set up:
- Change PIN and Biometric disable logic to reset timeout action to Logout
- Change default timeout action to logout if there is no saved action.
https://github.com/bitwarden/mobile/assets/4648522/972cd706-61a7-4c35-bab6-9368848dc6d2
- Please …

[PM-1201] Change timeout actions available based on hasMasterPassword

---

src/App/Pages/Vault/CipherDetailsPage.xaml

We added a different ID to the View Password button on CipherDetailsPage (for Login items), causing issues in our tests. This PR aims to replace the ID with the right one. 
* ** CipherDetailsPage.xaml:** Updating AutomationID for View Password button

[PM-3030] Fixing wrong ID on CipherDetailsPage for Login items

---

src/App/Pages/Vault/GroupingsPage/GroupingsPageViewModel.cs

This PR attempts to fix an issue happening from time to time, where the vault view's list doesn't load
Even though I couldn't reproduce the issue, I forced in the code the properties not to propagate changes to the view which end in this state, and based on these assumptions this fix is presented.
* **GroupingPageViewModel:** Added a bunch of main thread invocations for the properties expected to change from the view, so in case there is another thread executing the load, the property changed will be invoked in the main thread.
- If …

[AC-1425] Fix iOS blank vault load

---

src/Android/Android.csproj
src/Android/Renderers/CustomLabelRenderer.cs
src/Android/Resources/drawable/empty_uris_placeholder.xml
src/Android/Resources/drawable/empty_uris_placeholder_dark.xml
src/Android/Resources/layout/validatable_input_dialog_layout.xml
src/Android/Resources/values/dimens.xml
src/Android/Services/DeviceActionService.cs
src/App/Abstractions/IDeviceActionService.cs
src/App/App.csproj
src/App/Controls/CustomLabel.cs
src/App/Pages/Settings/BlockAutofillUrisPage.xaml
src/App/Pages/Settings/BlockAutofillUrisPage.xaml.cs
src/App/Pages/Settings/BlockAutofillUrisPageViewModel.cs
src/App/Pages/Settings/OptionsPage.xaml
src/App/Pages/Settings/OptionsPage.xaml.cs
src/App/Pages/Settings/OptionsPageViewModel.cs
src/App/Resources/AppResources.Designer.cs
src/App/Resources/AppResources.resx
src/App/Styles/Base.xaml
src/App/Utilities/Prompts/ValidatablePromptConfig.cs
src/iOS.Core/Services/DeviceActionService.cs

Improve current way to block Auto-fill URIs. This is an Android feature.
* **BlockAutofillUrisPage.xaml:** New view to display blocked autofill URIs.
* * **BlockAutofillUrisPage.xaml.cs:** New view to display blocked autofill URIs. Added this as theme dirtable to change the placeholder corresponding to the current app theme.
* **BlockAutofillUrisPageViewModel.cs:** New view model to handle the logic for blocked autofill URIs and also validation on input.
* **OptionsPage.xaml:** Changed UI to be simpler and just navigate to the new view
* **OptionsPage.xaml.cs:** Removed old blocked Uris logic
* **OptionsPageViewModel.cs:** Removed old blocked Uris logic and added navigation to new view
* **DeviceActionService.cs:** Added new `DisplayValidatablePromptAsync(...)` method that shows a custom …

[PM-2320] Improve Android block Auto-fill URIs

---

src/Core/Models/Domain/Fido2Key.cs
src/Core/Services/CipherService.cs

Fix when moving to org the non-discoverable passkey shouldn't be removed.
* **Fido2Key:** Added `EncryptableProperties` to improve code reuse.
* **CipherService:** Replaced hashSet of properties with the new one in the `Fido2Key` and also added the non-discoverable passkey (`cipher.Login.Fido2Key`) to be taken into account when encrypting a cipher.

[PM-3096] Fix non discoverable passkey removal on moving to org

---

src/App/Pages/Vault/SharePageViewModel.cs
src/App/Resources/AppResources.Designer.cs
src/App/Resources/AppResources.resx
src/Core/Abstractions/ICipherService.cs
src/Core/Models/Domain/Fido2Key.cs
src/Core/Models/View/Fido2KeyView.cs
src/Core/Services/CipherService.cs

Display error toast on duplicate passkey when moving item to an organization.
* **SharePageViewModel:** Added check of duplicate passkey error and show the toast to the user in that case
* **ICipherService:** Added `ShareWithServerError` to return the appropriate response to the caller when sharing cipher to an org. I cannot throw an `ApiException` with the error inside given that `AppResources` is not available in the `Core` project. Also another way would be to create and throw a specific exception for this and handle it on the caller but I thought this was better and the caller can handle the different paths more directly.
* **CipherService:** Added the validation to check whether the cipher has a FIdo2Key and if so, check if the organization already has any ciphers with the same …

[PM-2378] Display error toast on duplicate Passkey when moving cipher to an organization

---

src/App/Pages/Accounts/LoginPasswordlessRequestViewModel.cs
src/App/Pages/Accounts/TwoFactorPage.xaml.cs
src/App/Pages/Accounts/TwoFactorPageViewModel.cs
src/iOS.Autofill/CredentialProviderViewController.cs
src/iOS.Extension/LoadingViewController.cs
src/iOS.ShareExtension/LoadingViewController.cs

Merge after https://github.com/bitwarden/mobile/pull/2643
Navigate to device approval options after a successful 2FA authentication.
* **src/App/Pages/Accounts/TwoFactorPageViewModel.cs:** Add logic for TDE flow and action to call when device approval options is needed.
* **iOS Extension:** Add missing action to navigate to device approval options screen.
https://github.com/bitwarden/mobile/assets/4648522/bb722b65-cb78-4d66-81d4-bd633ca4b46d

[PM-1280] TDE 2FA - approval options navigation

---

src/App/Pages/Accounts/LockPageViewModel.cs
src/App/Pages/Accounts/LoginPasswordlessRequestViewModel.cs
src/App/Pages/Accounts/TwoFactorPage.xaml.cs
src/App/Pages/Accounts/TwoFactorPageViewModel.cs
src/Core/Abstractions/IAuthService.cs
src/Core/Abstractions/IStateService.cs
src/Core/Constants.cs
src/Core/Models/Domain/PendingAdminAuthRequest.cs
src/Core/Services/AuthService.cs
src/Core/Services/StateService.cs
src/iOS.Autofill/CredentialProviderViewController.cs
src/iOS.Extension/LoadingViewController.cs
src/iOS.ShareExtension/LoadingViewController.cs

Merge after https://github.com/bitwarden/mobile/pull/2642
Reuse created admin requests when trying to approve a login with TDE Admin approval request.
Store admin request id and private key to secure storage.
When opening the screen check for pending admin requests.
If there is a pending admin request populate the vm data with the saved request. 
https://github.com/bitwarden/mobile/assets/4648522/36ed5b21-d56a-4378-9cfe-111d466b6c33

[PM-2408] Pending admin approval requests

---

src/Android/Services/DeviceActionService.cs

Fix custom block URI dialog cancellation to finish its internal task and not block the button.
* **DeviceActionService:** Added `BasicDialogWithResultCancelListener` to handle dialog cancellation and set the return task value to `null` so that the task gets finished when the user taps in the background to cancel the opened dialog.

[PM-3165] Fix custom block URI dialog cancellation

---

src/App/Pages/Vault/CipherDetailsPage.xaml.cs
src/App/Pages/Vault/CipherDetailsPageViewModel.cs
src/Core/Models/View/CipherView.cs

Avoid ability to clone on discoverable passkeys.
* **CipherDetailsPage.xaml.cs:** Remove "Clone" ability on the iOS menu when cipher is a discoverable passkey. Also, refactor a bit the code to be more clean and readable.
* **CipherDetailsPageViewModel:** Added `CanClone` to improve readability and have a centralized point for its logic. Also, added a safe check on the clone execution not to allow cloning a discoverable passkey in case something on the UI fails.
* **CipherView:** Added `IsClonable` to know whether the cipher can be cloned or not.
- If this change requires a **documentation update** - notify the …

[PM-3227] Avoid clone on discoverable passkeys.

---

src/App/Pages/Accounts/LoginSsoPageViewModel.cs
src/App/Pages/Accounts/TwoFactorPageViewModel.cs
src/Core/Abstractions/IDeviceTrustCryptoService.cs
src/Core/Services/AuthService.cs
src/Core/Services/DeviceTrustCryptoService.cs
src/Core/Services/StateService.cs

After key rotation the user wasn't able to login using SSO.
When key rotation happens, decryption options come with null keys to the mobile client. If this happens we need to clear the trust device locally and redirect the user to the device approval options screen before entering the vault.
https://github.com/bitwarden/mobile/assets/4648522/90232a21-ea2b-49ab-a339-a0bf14935f0c

[PM-3379] Following key rotation, Mobile unable to log in with non-MP approval flow 

---

src/App/Abstractions/IPasswordRepromptService.cs
src/App/Pages/Vault/AutofillCiphersPageViewModel.cs
src/App/Pages/Vault/CipherDetailsPageViewModel.cs
src/App/Pages/Vault/CiphersPageViewModel.cs
src/App/Pages/Vault/OTPCipherSelectionPageViewModel.cs
src/App/Services/MobilePasswordRepromptService.cs
src/App/Utilities/AppHelpers.cs
src/iOS.Autofill/CredentialProviderViewController.cs
src/iOS.Autofill/Utilities/AutofillHelpers.cs
src/iOS.Extension/LoginListViewController.cs

Fix MP reprompt to be bypassed when no master hash is stored, like with TDE.
* **MobilePasswordRepromptService.cs:** Added check of master password hash to bypass MP reprompt and also added the Cipher reprompt type check inside to be more maintainable.
* **Others:** Adapted code to new method

[PM-3385] Fix Master Password reprompt item level (TDE)

---

src/App/Pages/Accounts/LoginApproveDevicePage.xaml.cs
src/App/Pages/Accounts/LoginPasswordlessRequestPage.xaml.cs
src/App/Pages/Accounts/LoginPasswordlessRequestViewModel.cs
src/App/Pages/Accounts/LoginSsoPageViewModel.cs
src/App/Utilities/AccountManagement/AccountsManager.cs
src/Core/Abstractions/IAuthService.cs
src/Core/Services/AuthService.cs
src/Core/Services/CryptoService.cs
src/Core/Services/VaultTimeoutService.cs
src/iOS.Autofill/CredentialProviderViewController.cs
src/iOS.Extension/LoadingViewController.cs
src/iOS.ShareExtension/LoadingViewController.cs

If the approving device doesn't have a master key, users should still be able to use Login with Device. This adds a token request in that instance, and sets the user key after.
While investigating this, I discovered that we're not clearing the active user id when adding a new account. This is problematic because `isAuthenticated` simply checks if the user id is `null`.
**Edit:** I originally fixed this by setting the active user Id to `null` but we can't do that for autofill purposes. Instead I am passing the `AuthRequestType` to any auth request logic so we know whether to use the Admin Approval logic or Unlock and Authenticate.
I also discovered that our background script to log out inactive accounts was attempting to set the user key if the vault timeout was set to 'never'. This change …

[PM-3394] Fix login with device for passwordless approvals

---

src/Android/Android.csproj
src/App/App.csproj
src/Core/Core.csproj
src/iOS.Autofill/iOS.Autofill.csproj
src/iOS.Extension/iOS.Extension.csproj
src/iOS.ShareExtension/iOS.ShareExtension.csproj
src/iOS/iOS.csproj
test/Common/Common.csproj
test/Core.Test/Core.Test.csproj

Another round of dependency updates made possible by the recent release of [Xamarin.Forms 5.0.0 SR-15](https://github.com/xamarin/Xamarin.Forms/releases/tag/release-5.0.0-sr15).
**_Note 1:_** `MessagePack*` will remain on its current version since it still breaks the Android build with the following error:
```
Xamarin.Android.Legacy.targets(317, 5): [XA2002] Can not resolve reference: `Microsoft.NET.StringTools`, referenced by `MessagePack`. Please add a NuGet package or assembly reference for `Microsoft.NET.StringTools`, or remove the reference to `MessagePack`.
```
The author states a [workaround](https://github.com/MessagePack-CSharp/MessagePack-CSharp/issues/1509#issuecomment-1554925920) was added in `2.5.94+` but we're still seeing this error with `2.5.124`.
**_Note 2:_** Continuing …

[PM-3497] Dependency Updates

---

src/Core/Services/AuthService.cs

If a user had 2fa enabled on their account and requested device approval from a passwordless device, the user key wasn't being set on the account. This change stores the user key on the auth service so that a second auth request can set it if they are successfully authenticated

[PM 3513] Fix passwordless 2fa login with device on mobile

---

src/Android/MainActivity.cs
src/App/App.xaml.cs
src/App/Controls/Settings/SwitchItemView.xaml
src/App/Pages/Accounts/HomePage.xaml.cs
src/App/Pages/Generator/GeneratorPage.xaml.cs
src/App/Pages/PickerViewModel.cs
src/App/Pages/Settings/AboutSettingsPage.xaml
src/App/Pages/Settings/AboutSettingsPage.xaml.cs
src/App/Pages/Settings/AppearanceSettingsPage.xaml
src/App/Pages/Settings/AppearanceSettingsPage.xaml.cs
src/App/Pages/Settings/AppearanceSettingsPageViewModel.cs
src/App/Pages/Settings/AutofillSettingsPage.xaml
src/App/Pages/Settings/AutofillSettingsPage.xaml.cs
src/App/Pages/Settings/OptionsPageViewModel.cs
src/App/Pages/Settings/OtherSettingsPage.xaml
src/App/Pages/Settings/OtherSettingsPage.xaml.cs
src/App/Pages/Settings/OtherSettingsPageViewModel.cs
src/App/Pages/Settings/SecuritySettingsPage.xaml
src/App/Pages/Settings/SecuritySettingsPage.xaml.cs
src/App/Pages/Settings/SettingsPage/SettingsPageViewModel.cs
src/App/Pages/Settings/VaultSettingsPage.xaml
src/App/Pages/Settings/VaultSettingsPage.xaml.cs
src/App/Pages/TabsPage.cs
src/App/Styles/ControlTemplates.xaml
src/App/Utilities/ThemeManager.cs
src/iOS.Core/Renderers/CustomTabbedRenderer.cs
src/iOS/AppDelegate.cs

Implemented new view for settings: Appearance.
* **PickerViewModel:** Improved it to reuse code and also added `afterSelectionChangedAsync` to be able to perform actions after the picker selected value has been set.
* **AppearanceSettingsPage/ViewModel:** Implemented new Appearance view with new `PickerViewModel` approach.
* **Other settings views:** Made the navigation to not be modal, removed the toolbar item for the back button given that the default is being used and changed the base class to be `BaseContentPage` instead the modal one.
* **Other:** Moved `updatedTheme` to a constant and updated everywhere to used that constant
- Please add **unit tests** where it makes sense to do so (encouraged but …

[PM-3512] Settings Appearance

---

src/App/Pages/Accounts/LoginPasswordlessRequestViewModel.cs

Show the api error when a user tries to Login with device but there is an SSO only policy enforced.
Catch Api exception and show internal error message.

[PM-3513] Show error SSO policy

---

src/Core/Constants.cs

`UserKeyBiometricUnlockKey` was defined as `biometricUnlock_{userId}` which was already used for `BiometricUnlockKey`.  It has been changed to `userKeyBiometricUnlock_{userId}`.  For sanity `UserKeyAutoUnlockKey` was also changed to `userKeyAutoUnlock_{userId}`.
**Note:** I did not add migration as this feature has not shipped yet.  QA should clear app data before resuming testing.
* **Constants.cs:** Fixed values described above

fix for TDE pref naming collision

---

src/Core/Services/CryptoService.cs

When migrating the pin, we were clearing the old encryption key. Unfortunately, this key is needed for the bio/auto migration that could still happen later.
This fix checks for the existence of an old encrypted master key inside the pin migration, indicating that the bio/auto migration is still needed, and doesn't clear the old encryption key if so. I have also added a null check to the bio/auto migration.
This will need to be picked to `rc`
- If this change has particular …

[PM-3640] don't clear key needed for bio/auto migration in pin migration

---

src/App/Pages/BaseContentPage.cs
src/App/Services/MobileStorageService.cs
src/Core/Abstractions/IAppIdService.cs
src/Core/Abstractions/ICipherService.cs
src/Core/Abstractions/IStateService.cs
src/Core/Constants.cs
src/Core/Services/AppIdService.cs
src/Core/Services/CipherService.cs
src/Core/Services/StateMigrationService.cs
src/Core/Services/StateService.cs

This change performs data migration out of LiteDB and into shared preferences.  It also changes the mobile storage service to default to saving anything new to shared pref storage, and requires specifying keys for LiteDB storage.
* **StateMigrationService:** Added a 5to6 migration block for global and account-specific state values
* **MobileStorageService.cs:** Added a set of LiteDB storage keys to check against when accessing storage.  Also added an inline litedb-to-pref migration on the getter to cover for values that can't be handled cleanly via StateMigration (`accountBiometricIntegrityValid_{userId}_{systemBioIntegrityState}`) and as a catch-all to prevent anything sneaking into liteDB during the transition.
* **BaseContentPage.cs:** Prevent saving last active time without a userId …

[PM-3222] Migration of data from LiteDB to shared pref storage

---

src/App/Pages/Accounts/SetPasswordPage.xaml
src/App/Pages/Accounts/UpdateTempPasswordPage.xaml

Adding more AutomationIDs to continue improving our mobile automation test suite
Some missing AutomationIDs were added to Set/UpdatePassword XAML files
* **SetPasswordPage.xaml:** Adding missing IDs for entry fields
* **UpdateTempPasswordPage.xaml:** Adding missing IDs for entry fields

[PM-3803] Adding AutomationIDs for Set/Update password pages

---

src/iOS.Core/Controllers/BaseLockPasswordViewController.cs

When a user with no MP and biometrics enabled attempts to autofill, the user is prompted to log in via SSO instead of biometrics.
Start the enable biometrics on iOS extension when biometric is the only login method besides SSO.

[PM-3593] Autofill: user with no MP not able to biometrics

---

src/App/Pages/Accounts/LoginSsoPageViewModel.cs

Fix bug where an expired sso token is cached by the mobile browser and the user cannot continue the sso login flow.
When a user cancels the modal, we will start a cached cleared browser session to login.

[PM-3551] Expired SSO token cached

---

src/Core/Services/ApiService.cs
src/Core/Utilities/VersionHelpers.cs

Remove the suffix on the client version when sending it to the server on the `ApiService`.
* **ApiService:** Remove suffix on client version default HttpClient header.
* **VersionHelpers:** Added helper to remove and return the string version without the suffix.

[PM-3737] Remove client version suffix sent to server

---

src/Core/Services/StateService.cs

`Approve Login Request` setting value is reset when the user logs out. 
Value should be kept saved. 
Remove line that was clearing the `Approve Login Request` setting.

[PM-3522] Approve Login Request setting is not remembered if user logs out of mobile

---

src/App/Pages/Settings/ExportVaultPage.xaml

Adding more AutomationIDs to continue improving our mobile automation test suite
Some missing AutomationIDs were added to the ExportVault XAML file
* **ExportVaultPage.xaml:** Adding missing AutomationIDs

[PM-4046] Adding AutomationIDs for ExportVault page

---

src/App/Services/MobilePasswordRepromptService.cs
src/Core/Abstractions/ICryptoService.cs
src/Core/Services/CryptoService.cs
src/Core/Services/UserVerificationService.cs

Application is crashing to users that have biometrics active, updated to the most recent version without and try to export. 
This is caused by a missing `MasterKey`, this fix creates the missing `MasterKey` if necessary at export.
* **UserVerificationService.cs:** Calling method `GetOrDeriveMasterKeyAsync` to ensure that the `MasterKey` if doesn't exist is created. In case of success, use the same logic from `MasterPasswordRepromptService` to update the `MasterKey` and the `UserKey`
* **CryptoService.cs:** Created a method that updates the `MasterKey` and the `UserKey` based on the code from `MasterPasswordRepromptService` so that it can be reused by `UserVerificationService`
* **MasterPasswordRepromptService:** Replacing the code by the new created method from `CryptoService`
- Please …

[PM-4081] Fix crash on export page

---

src/App/Pages/Vault/GroupingsPage/GroupingsPage.xaml.cs
src/iOS.Core/Renderers/CollectionView/ExtendedGroupableItemsViewController.cs

Try fix the most reoccurring crash. If the app goes to background and there was an item open, when it comes to the foreground and tries to load the item again it could crash.
https://github.com/bitwarden/mobile/issues/2794
https://github.com/bitwarden/mobile/issues/2478
Check for previous opened item before trying to load the vault list.

[PM-868] Re-open app to item could crash the app

---

src/App/Pages/Vault/CipherAddEditPage.xaml
src/App/Pages/Vault/CipherDetailsPage.xaml
src/App/Utilities/DateTimeConverter.cs
src/Core/Models/Api/Fido2CredentialApi.cs
src/Core/Models/Data/Fido2CredentialData.cs
src/Core/Models/Domain/Fido2Credential.cs
src/Core/Models/View/Fido2CredentialView.cs
src/Core/Services/CipherService.cs

Add `CreationDate` to `Fido2Credential` objects and update the UI accordingly also fixing an issue where the date time was not being presented in local time.
* **Fido2Credential...:** Added `CreationDate` and updated mappings.
* **...Page.xaml:** Updated bindings to the new creation date and use `DateTimeConverter` with the specific format to avoid creating a new property on the VMs.
* **DateTimeConverter:** Added `Format` property with a default value so we can customize it in specific occasions like this one.
- If this change has …

[PM-4404] Add CreationDate to Fido2Credential objects

---

.github/CODEOWNERS

Adding all files that get synced with the Crowdin PRs besides en/ into ownership of team-tools-dev
* **.github/CODEOWNERS:** 
- Set ownership of locales to team-tools-dev
- Set ownership of locales for the stores to team-tools-dev
- Remove ownership for en on the stores

Update CODEOWNERS for Crowdin PRs

---

src/App/Controls/Settings/BaseSettingControlView.cs
src/App/Controls/Settings/SettingChooserItemView.xaml.cs
src/App/Pages/Settings/SecuritySettingsPage.xaml
src/App/Pages/Settings/SecuritySettingsPageViewModel.cs
src/App/Resources/AppResources.Designer.cs
src/App/Resources/AppResources.resx
src/App/Styles/ControlTemplates.xaml
src/App/Utilities/BoolToColorConverter.cs

Update settings screen vault timeout action cell UI to match designs.
Add disable and description properties to SettingsPageListItem.
Add new UI cell to data template.
https://github.com/bitwarden/mobile/assets/4648522/e98284c8-4b9d-426f-b81b-58b7a979af65

[PM-3340] Update timeout action for users without master password.

---

src/Core/Services/VaultTimeoutService.cs

Fix bug where if Unlock with Biometrics is Enabled, the app would still lock the vault even if the Vault Timeout is set to Never.
Remove old check for biometric state on vault timeout `IsLocked`

[PM-891] Biometrics enabled ignores vault timeout set to Never

---

src/Core/Models/Domain/UsernameGenerationOptions.cs
src/Core/Services/EmailForwarders/FastmailForwarder.cs
src/Core/Services/UsernameGenerationService.cs

Added a metadata field (forDomain:) to the Fastmail Forwarder API request that's set to the domain name of the item being added to the vault, or to "" if the username generator is being used in standalone mode. This allows the user's Fastmail account to display the domain name for the username that was generated.
- **src/Core/Models/Domain/UsernameGenerationOptions.cs:** `GetForwarderOptions()` will now return a `FastmailForwarderOptions` object with the new `Website` member set to the `EmailWebsite` of `UsernameGenerationOptions` for the fastmail case
- **src/Core/Services/EmailForwarders/FastmailForwarder.cs:** Added the `FastmailForwarderOptions` class that extends `ForwarderOptions` and updated declarations accordingly. Added the `forDomain:` field to the API request
- …

[PM-4800] Send item domain name to fastmail

---

.github/workflows/build.yml

This PR fixes the `build` workflow by installing Microsoft OpenJDK 11.  Other various improvements have also been applied.
* **.github/workflows/build.yml:** Update actions. Update runner versions. Add step for installing Microsoft OpenJDK 11. Remove unnecessary shell keys. Remove old retrieve-secrets step and use our action. 

Fix Build workflow - Install OpenJDK 11

---

src/App/Pages/Settings/VaultSettingsPageViewModel.cs

When tapping on the Import items button, the user gets asked if they want to get redirected to the web vault to import the items.
Clicking yes, opens the web-vault in the browser, but after logging in, they are on the vault page instead of the tools/import page.
* **src/App/Pages/Settings/VaultSettingsPageViewModel.cs:** Extend the existing url with "/#/tools/import" to route to the import page

[PM-5715] Route to import page when clicking on import items button

---

src/App/Pages/Settings/VaultSettingsPageViewModel.cs
src/Core/ExternalLinksConstants.cs

Follow-up from https://github.com/bitwarden/mobile/pull/2937
When tapping on the Import items button, the user gets asked if they want to get redirected to the web vault to import the items.
Clicking yes, opens the web-vault in the browser, but after logging in, they are on the vault page instead of the tools/import page.
* **src/App/Pages/Settings/VaultSettingsPageViewModel.cs:** Extend the existing url with "/#/tools/import" to route to the import page
- If this change has particular **deployment requirements** - notify the DevOps …

[PM-5715] Route to import page when clicking on import items button Pt2

---

src/Core/Constants.cs

```
```
Set the minimum server version that will support vault item encryption to `2024.1.3`, as the final pieces of this will be released with the release on 2/6, which will be server `2023.1.3`.
Server PR: https://github.com/bitwarden/server/pull/3711
Clients PR: https://github.com/bitwarden/clients/pull/7705
- **Constants.cs:** Updated minimum server version.

[PM-5638] Bump minimum server version for vault item encryption

---

src/Core/Pages/Accounts/TwoFactorPage.xaml
src/Core/Pages/Accounts/TwoFactorPageViewModel.cs

To stop the sliding bottom layout on the Duo 2FA page we're now setting a fixed height for the webview based on a simple measurement.  The gap at the bottom can vary depending on the device height (screenshots below), but thankfully Duo's new [frameless implementation](https://github.com/bitwarden/mobile/pull/2956) will demote this flow to an edge case.
* **TwoFactorPage/Viewmodel:** Added height property and calculation using `DeviceDisplay.MainDisplayInfo` height & density
In the rare case we aren't able to obtain the available height for measuring, we default to 400dp as a safe minimum as seen here:
- If this …

[PM-5910] Workaround for for sliding elements in Duo 2FA flow

---

src/Core/Constants.cs

```
```
Set the minimum server version that will support vault item encryption to `2024.2.0`, as the final pieces of this will be released with the release on 2/6, which will be server `2023.2.0`.
(Note that https://github.com/bitwarden/mobile/pull/2959 incremented to `2024.1.3`, but the upcoming release version will be `2024.2.0`.)
Server PR: https://github.com/bitwarden/server/pull/3718
Clients PR: https://github.com/bitwarden/clients/pull/7705
- **Constants.cs:** Updated minimum server version.
- If this change has particular …

[PM-5638] Update minimum version for vault item encryption to 2024.2.0

---

src/Core/Controls/AccountSwitchingOverlay/AccountSwitchingOverlayView.xaml

Account Switcher can't be dismissed by tapping in the empty space below it like we could with the Xamarin Forms app.
This is caused because `FillAndExpand` works differently in MAUI and will not "expand to fill" the entire screen space with the BoxView that we had before for detecting and dismissing the Account Switcher.
* **AccountSwitchingOverlayView.xaml:** Replace `StackLayout` with a Grid and set `RowDefinitions`. Setting "*" for the `BoxView `will ensure it "fills" the entire screen and therefore will detect the tap event that triggers the dismiss of the Account Switcher.
- If this change requires a …

[PM-5902] Fix Account Switcher can't be dismissed when tapping outside of it

---

src/App/Platforms/Android/MainActivity.cs
src/Core/App.xaml.cs

Fix Account Switcher visible on Android when no Accounts are logged in.
This is happening because on Android `App.xaml.cs.SetOptions()` can get called after `App.xaml.cs` already has Options set. In this scenario it would get replaced and specifically the property `HideAccountSwitcher` will have an incorrect value of `false`.
* **App.xaml.cs:** Update the `SetOptions()` method to only update the properties that we need from Android instead of replacing the entire object. Also added some comments and changed the method name to `SetAndroidOptions()` to make it more clear.
- If this change requires a **documentation …

[PM-5903] Fix Account Switcher visible on Android when no Accounts are logged in

---

src/App/Platforms/iOS/AppDelegate.cs
src/Core/Controls/AuthenticatorViewCell/AuthenticatorViewCell.xaml
src/Core/Controls/AuthenticatorViewCell/AuthenticatorViewCell.xaml.cs
src/Core/Controls/CipherViewCell/BaseCipherViewCell.cs
src/Core/Controls/CipherViewCell/CipherViewCell.xaml
src/Core/Controls/CipherViewCell/CipherViewCell.xaml.cs
src/Core/MauiProgram.cs
src/Core/Pages/Vault/CipherItemViewModel.cs

Fix background crash happening on iOS due to having a lock file (login.png) when the app got to suspended state.
This is due to the `CachedImage` loading and error placeholders which try to load the _login.png_ file and at the same time the user sends the app to background, and when it reaches the suspended state, sometimes the file is still locked which causes the app to crash afterwards with this reason on the crashlog `RUNNINGBOARD 0xdead10cc` and this message can be seen on the Console output `suspended with locked system files` referencing afterwards the _login.png_ file.
* **BaseCipherViewCell.cs:** Added this class to hold the new logic for the cached image source and visibility changes between the cached image and the placeholder icon. This is shared between `CipherViewCell` and …

[PM-5896] Fix MAUI iOS Background crash due to lock files on suspension

---

src/Core/Pages/Vault/CipherAddEditPage.xaml.cs

Fix for incorrect TOTP white text color on label when using light theme on iOS.
This fix is a workaround for the MAUI Issue https://github.com/dotnet/maui/pull/20100
* **CipherAddEditPage.xaml.cs:** Set the TextColor to null and back to the correct color whenever we try to programatically change the entry text. Doing this avoids the bug.

[PM-5907] Fix for incorrect TOTP white text color on label when using light theme on iOS

---

src/Core/Pages/Send/SendAddEditPage.xaml.cs

Fix for incorrect Send MaxAccess white text color on label when using light theme on iOS.
This fix is a workaround for the MAUI Issue https://github.com/dotnet/maui/pull/20100
* **SendAddEditPage.xaml.cs:** Set the TextColor to null and back to the correct color whenever we try to programatically change the entry text. Doing this avoids the bug.

[PM-5906] Fix for incorrect Send MaxAccess white text color on label when using light theme on iOS

---

src/Core/Utilities/ThemeManager.cs

We want to implement a fix/workaround for MAUI not reporting the correct Theme when resuming an iOS App.
* **ThemeManager.cs:** Added iOS/Android specific implementations for OsDarkModeEnabled() so that we can directly fetch the Theme on the iOS API for the iOS implementation.

[PM-5913] Fix for MAUI not reporting the correct Theme when resuming an iOS App

---

.github/workflows/version-bump.yml

This PR fixes the version check step by using the proper location of `AndroidManifest.xml`.
* **.github/workflows/version-bump.yml:** Update path to `AndroidManifest.xml`. Fix `while` loop logic.

Version Bump workflow - Fix location of AndroidManifest.xml file

---

src/Core/Pages/Send/SendGroupingsPage/SendGroupingsPage.xaml
src/Core/Resources/Styles/Android.xaml
src/Core/Resources/Styles/iOS.xaml

Font Size on some controls in the MAUI app is different from Xamarin Forms. Ideally it should be the same.
As far as I could tell MAUI no longer uses the same Font Size default that we had in Xamarin Forms.
The most obvious issues seemed to be on `Entry`, `Editor`, `Picker` and `SearchBar`.
In code I set these base controls to always have a default of `FontSize="18"` which seems to be the same as the Xamarin Forms app.
Also added a spacing on `SendGroupingsPage.xaml` between icon and text. (this wasn't an issue in Xamarin Forms because XF has a default Spacing of 6)
* **Android.xaml:** Set the default FontSize to 18 on `Entry`, `Editor`, `Picker` and `SearchBar`. (for Android)
* **iOS.xaml:** Set the default FontSize to 18 on `Entry`, `Editor`, `Picker` and `SearchBar`. (for iOS)
* …

[PM-5909] Fix Font MAUI Sizes

---

.github/workflows/build.yml

This PR adds the .NET 3.1 runtime so that the Google Publisher project can sign correctly.
* **.github/workflows/build.yml:** Add line for .NET 3.1 runtime

Add .NET 3.1 to fix Google Publisher project signing

---

src/Core/Controls/CipherViewCell/BaseCipherViewCell.cs

… 
'Show website icons' option is not being respected.
The issue seems to be caused by the `Icon_Success` setting Icon to visible after loading it without taking into account the current WebsiteIcons setting.
* **BaseCipherViewCell.cs:** Updated `Icon_Success` method to take into account the current WebsiteIcons setting.

[PM-6309] Fix for 'Show website icons' option not being respected

---

src/Core/Pages/Settings/LoginPasswordlessRequestsListViewModel.cs

Currently on iOS there are still Layout issues related with the RefreshView.
These seem to be caused by the IsRefreshing being set to true on RefreshAsync which the RefreshView seems to use to trigger the RefreshCommand again. This duplicate execution causes layout issues on iOS.
Removing `IsRefreshing=true` fixes the issue. The only worry is that the busy indicator would not appear, but this doesn't seem to be a problem because when doing PullToRefresh the RefreshView changes IsRefreshing and shows the indicator.
For the other situations where we execute RefreshAsync the `LoginPasswordlessRequestsListPage.xaml.cs` takes care of the busy indicator.
* **LoginPasswordlessRequestsListViewModel.cs:** Removed `IsRefreshing=true`
- Please check for formatting errors (`dotnet format …

[PM-6301] Fix for pending login view breaks after closing one request

---

src/Core/Abstractions/IConditionedAwaiterManager.cs
src/Core/Pages/Accounts/HomePage.xaml.cs
src/Core/Pages/AndroidNavigationRedirectPage.xaml.cs
src/Core/Services/ConditionedAwaiterManager.cs
src/Core/Utilities/AccountManagement/AccountsManager.cs

Try to ensure the main navigation always runs after the homepage navigation.
Using the ConditionedAwaiterManager I initially tried using SetCompleted in the Window ctor but that was apparently to early still.
Moved it to HomePage after it "fires" it's own Navigation and that does seem to work.

Added ConditionedAwaiter to avoid race condition issue where HomePage navigation would run after the main navigation

---

src/Core/Pages/Accounts/LoginPasswordlessPage.xaml
src/Core/Resources/Styles/iOS.xaml

Some buttons on iOS don't have the correct Height and Corner Radius
Xamarin Forms doesn't seem to have the same defaults for Buttons than MAUI on iOS.
To fix these issues I added default min height and corner radius for iOS buttons.
Also removed incorrect style class from one button.
* **iOS.xaml:** Added default CornerRadius and MinHeightRequest for iOS Buttons and removed redundant properties from other Button styles that are based from default one.
* **LoginPasswordlessPage.xaml:** Removed incorrect class
Before             |  After
:-------------------------:|:-------------------------:
- If this change requires a …

[PM-5912] Fix for some iOS buttons not having the correct height and corner radius

---

src/Core/Abstractions/IConditionedAwaiterManager.cs
src/Core/Pages/Accounts/HomePage.xaml.cs
src/Core/Pages/AndroidNavigationRedirectPage.xaml.cs
src/Core/Services/ConditionedAwaiterManager.cs
src/Core/Services/LegacySecureStorage/AndroidKeyStore.cs
src/Core/Services/LegacySecureStorage/KeyChain.cs
src/Core/Services/LegacySecureStorage/LegacySecureStorage.cs
src/Core/Services/SecureStorageService.cs
src/Core/Utilities/AccountManagement/AccountsManager.cs

Implement Legacy Secure Storage.
MAUI has changed how Secure Storage work vs Xamarin.Forms, so to avoid having to do a migration now, we are implementing the former way of Secure Storage so the update to MAUI version of the app is as seamless as possible.
* **AndroidKeyStore:** Component to get/store keys securely on Android
* **KeyChain:** Component to get/store keys securely on iOS
* **SecureStorageService:** Updated it to use the Xamarin Essentials (Xamarin Forms)'s components for both platforms.
- If this change has particular …

[PM-6428] Implement Legacy Secure Storage

---

src/Core/Pages/Send/SendAddEditPage.xaml

Touching the arrow icon itself doesn't trigger the expand/collapse command likely because the icon button is handling/ignoring the even and it doesn't propagate to the TapGestureRecognizer.
Set the icon buttons to be InputTransparent.
Also took the chance to add the Min Width to ensure the arrow isn't right next to the label on iOS. (so it's looking like the Xamarin Forms app)
* **SendAddEditPage.xaml:** Added `InputTransparent="True"` and `MinimumWidthRequest="25"`
Before             |  After
:-------------------------:|:-------------------------:
- If this change requires a **documentation update** - notify the …

[PM-5917] Fix for send arrow now being touch sensitive to expand collapse

---

src/Core/Pages/Accounts/LoginPasswordlessPage.xaml
src/Core/Pages/Accounts/LoginPasswordlessRequestPage.xaml
src/Core/Pages/Settings/LoginPasswordlessRequestsListPage.xaml

Fingerprint phrases are being shown with the incorrect font
The correct font is set for MonoLabel but apparently they are not set when using FormattedText.
Changing to Text instead fixes the issue. (FormattedText doesn't really seem to be needed in this scenario)
I applied this to other MonoLabel in the app that had the same issue.
* **LoginPasswordlessPage.xaml:** Changed `FormattedText` to `Text`
* **LoginPasswordlessRequestPage.xaml:** Changed `FormattedText` to `Text`
* **LoginPasswordlessRequestsListPage.xaml:** Changed `FormattedText` to `Text`
Before             |  After
:-------------------------:|:-------------------------:
- Please add **unit tests** where it makes sense to do so (encouraged …

[PM-5916] Fix for incorrect fonts in fingerprint phrases

---

src/iOS.Core/Utilities/ASHelpers.cs

Omit creating CredentialIdentity if it throws an exception. E.g. if a Passkey doesn't have a UserName it will throw and it shouldn't break replacing all the other identities.
* **ASHelpers:** Added a try...catch when creating the `CredentialIdentity` which returns `null` if an exception happens so it's ignored when registering all identities and it doesn't break it.

[PM-6513] Omit creating CredentialIdentity if it throws an exception

---

src/Core/App.xaml.cs
src/Core/Pages/Settings/AutofillSettingsPageViewModel.android.cs

The app is showing the Home Login page when we open the Accessibility Settings on Android from the App and then close the bitwarden app.
This is due to the Accessibility Service being kept alive (and therefore `App.xaml.cs`). When we open the app again it doesn't try to Navigate to the proper page because of that.
We need to have the app navigate normally even in these scenarios.
A workaround similar to the existing one for Autofill can be implemented. It's done separately with a different variable so that the app can handle edge cases where both are needed simultaneously. 
* **App.xaml.cs:** Added a workaround block similar to the existing one for Autofill. This will basically allow executing Navigations if `HasNavigatedToAccessibilitySettings` is set to true.
* …

[PM-6552] Fix for App only showing Home (Login) Page after closed after opening Accessibility Settings

---

src/Core/Pages/AndroidNavigationRedirectPage.xaml.cs

Added missing using in previous PR
* **AndroidNavigationRedirectPage.xaml.cs:** Add using for LoggerHelper

[PM-6552] Added missing using in previous PR

---

src/Core/Core.csproj
src/Core/Pages/Accounts/LoginSsoPage.xaml.cs
src/Core/Pages/Accounts/LoginSsoPageViewModel.cs
src/Core/Services/Logging/DebugLogger.cs
src/Core/Services/StateMigrationService.cs
src/Core/Utilities/AccountManagement/AccountsManager.cs
src/Core/Utilities/WebAuthenticatorMAUI/WebAuthenticator.ios.cs
src/Core/Utilities/WebAuthenticatorMAUI/WebAuthenticator.shared.cs
src/Core/Utilities/WebAuthenticatorMAUI/WebAuthenticatorResult.cs
src/Core/Utilities/WebAuthenticatorMAUI/WebUtils.cs
src/iOS.Autofill/CredentialProviderViewController.cs
src/iOS.Autofill/LockPasswordViewController.cs
src/iOS.Core/Controllers/BaseLockPasswordViewController.cs
src/iOS.Core/Controllers/LoginAddViewController.cs
src/iOS.Extension/LoadingViewController.cs
src/iOS.ShareExtension/LoadingViewController.cs

Fix Autofill iOS Extension when using TDE without MP flow.
_Note: I also fixed one NRE on the state migration from 6 to 7, also same happening on Generator view on iOS extension. Additionally, `WebAuthenticator` was copied and adapted from MAUI Essentials to get the current `UIWindow` as in Xamarin Essentials._
* **BaseLockPasswordViewController:** Updating PromptSSO view controller creation to be like in MAUI.
* **LoginAddViewController:** Fixed generator view controller creation to be like in MAUI.
* **StateMigrationService:** Fix NRE if `state` is `null`
* **LoginSSOViewModel:** Fix to use workaround for iOS Extension on the `WebAuthenticator`
* **WebAuthenticator:** MAUI Essentials copy of `WebAuthenticator` adapted to get the current `UIWIndow` as it was being done in Xamarin …

[PM-6539] Fix Autofill Extension TDE without MP flow

---

.github/workflows/release.yml

This PR fixes the path to `AndroidManifest.xml` in the `Release` workflow.
* **.github/workflows/release.yml:** Update path to `AndroidManifest.xml` in the `Check Release Version` step, remove `github.event.` from inputs as it's not necessary.

DEVOPS-1861 - Update release workflow with proper paths

---

src/App/Platforms/Android/Autofill/AutofillHelpers.cs
src/App/Platforms/Android/Tiles/AutofillTileService.cs
src/App/Platforms/Android/Tiles/GeneratorTileService.cs
src/App/Platforms/Android/Tiles/MyVaultTileService.cs
src/App/Platforms/Android/Utilities/AndroidHelpers.cs

When using Android Tiles on Android 14+ the TileService crashes.
Android now requires that TileServices using `PendingIntent` instead of Intent for `StartActivityAndCollapse()`
Doing this change avoids the crash. We still keep the "old" Intent code for older versions of Android.
There was also a background crash on AccessibilityService due to a PendingIntent being mutable which also seems to no longer being allowed in Android14 for that specific scenario.
* **AutofillTileService.cs:** Added if scenario for Android 14 to use `PendingIntent` instead of `Intent`.
* **MyVaultTileService.cs:** Added if scenario for Android 14 to use `PendingIntent` instead of `Intent`
* **GeneratorTileService.cs:** Added if scenario for Android 14 to use `PendingIntent` instead of `Intent`
* …

[PM-6726] Fix for Android 14 devices crashing when using the Tiles

---

src/App/Platforms/Android/AndroidManifest.xml

There's a `NullPointerException` ocurring in `WebAuthenticatorIntermediateActivity`.
This is likely related with `WebAuthenticatorCallbackActivity` in Android.
As explained in the [Microsoft Docs](https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/communication/authentication?view=net-maui-8.0&tabs=android) when   using this WebAuthenticator on Android we need to add the appropriate query.
This might be the cause of the bug.
```
<queries>
<intent>
<action android:name="android.support.customtabs.action.CustomTabsService" />
</intent>
</queries>
```
Added the query intent for CustomTabs as it might fix the exception that is occurring in Android WebAuthenticator.
* **AndroidManifest.xml:** Added the query
- Please check for formatting errors (`dotnet format …

[PM-6751]Added missing query intent for CustomTabs that might be responsible for the Exception in WebAuthenticator

---

src/Core/Resources/Localization/AppResources.Designer.cs
src/Core/Resources/Localization/AppResources.resx
src/Core/Services/Fido2AuthenticatorService.cs
src/iOS.Autofill/CredentialProviderViewController.Passkeys.cs
src/iOS.Autofill/CredentialProviderViewController.cs
src/iOS.Autofill/ILoginListViewController.cs
src/iOS.Autofill/LoginListViewController.cs
src/iOS.Autofill/LoginListViewController.designer.cs
src/iOS.Autofill/LoginSearchViewController.cs
src/iOS.Autofill/MainInterface.storyboard
src/iOS.Autofill/Models/Context.cs
src/iOS.Autofill/Utilities/AutofillHelpers.cs
src/iOS.Autofill/Utilities/BaseLoginListTableSource.cs
src/iOS.Autofill/Utilities/Fido2GetAssertionFromListUserInterface.cs
src/iOS.Autofill/iOS.Autofill.csproj
src/iOS.Core/Models/CipherViewModel.cs
src/iOS.Core/Views/CipherLoginTableViewCell.cs
src/iOS.Core/Views/ExtensionTableSource.cs

Implement combined view for passwords and passkeys on iOS Autofill extension with in-view search feature.
* **CredentialProviderViewController[Passkeys]:** Moved `PrepareCredentialList` to Passkeys file and reuse the one without passkeys request parameters from this one saving the parameters in the context.
* **LoginListViewController:**
* Added Loading indicator
* Implemented different names for the title depending on the context
* Added Search feature inside this list, the toolbar search button toggles the visibility of the search bar
* Implemented Fido2 `GetAssertion` for the logic for the combined passwords and passkeys
* Improved empty state
* Improved loading and reloading items
* **BaseLoginListTableSource:** Main point for implementing the logic of cipher loading, taking into …

[PM-5154] Implement combined view for passwords and passkeys on iOS Autofill extension

---

src/Core/Abstractions/IConditionedAwaiterManager.cs
src/Core/Resources/Localization/AppResources.Designer.cs
src/Core/Resources/Localization/AppResources.resx
src/Core/Services/ConditionedAwaiterManager.cs
src/Core/Services/UserVerification/Fido2UserVerificationPreferredServiceStrategy.cs
src/Core/Services/UserVerification/Fido2UserVerificationRequiredServiceStrategy.cs
src/Core/Services/UserVerification/UserVerificationMediatorService.cs
src/Core/Utilities/Fido2/Fido2UserVerificationOptions.cs
src/iOS.Autofill/CredentialProviderViewController.Passkeys.cs
src/iOS.Autofill/CredentialProviderViewController.cs

Fix fingerprint verification on unlocked accounts because of race condition
* **CredentialProviderViewController.Passkeys:** Added a hack here to wait until `ViewDidAppear` happens using the `ConditionedAwaiterManager` for `OnNeedUITask` callback of user verification in order to have the UI displayed before trying to perform the biometrics check. In order for this to happen I've added a toast to be shown which forces the UI to be presented, was the easiest way I could come up to actually show the UI and trigger `ViewDidAppear`.
* **Fido2UserVerificationOptions:** Changed `OnNeedUITask` to be async.
https://github.com/bitwarden/mobile/assets/15682323/7df9dd22-98d0-4c90-833b-7c9ec11e497d
- Please add …

[PM-6685] Fix fingerprint verification on unlocked accounts because of race condition

---

src/Core/Abstractions/IPlatformUtilsService.cs
src/Core/Abstractions/IUserVerificationMediatorService.cs
src/Core/Pages/Accounts/LockPageViewModel.cs
src/Core/Pages/Settings/SecuritySettingsPageViewModel.cs
src/Core/Services/Fido2AuthenticatorService.cs
src/Core/Services/MobilePlatformUtilsService.cs
src/Core/Services/UserVerification/Fido2UserVerificationPreferredServiceStrategy.cs
src/Core/Services/UserVerification/Fido2UserVerificationRequiredServiceStrategy.cs
src/Core/Services/UserVerification/IUserVerificationServiceStrategy.cs
src/Core/Services/UserVerification/UserVerificationMediatorService.cs
src/Core/Utilities/CancellableResult.cs
src/iOS.Autofill/CredentialProviderViewController.Passkeys.cs
src/iOS.Autofill/LoginAddViewController.cs
src/iOS.Autofill/LoginListViewController.cs
src/iOS.Core/Controllers/BaseLockPasswordViewController.cs

Improved user verification on passkeys creation to better take into account User verification cancellation and also enforcement at the moment of creation.
* **MobilePlatformUtilsService:** Now `AuthenticateBiometricAsync` returns `null` when cancelled by the user.
* **UserVerificationMediatorService:** Changed to use `CancellableResult<T>` to tackle cancellation flows.
* Same applies to its strategies
* **LoginListViewController/LoginAddViewController:** Added cancellation flow so the user can try again and also implemented user verification enforcement at this stage as well to prevent the cipher to be created if the verification fails and is required.
- Please add **unit tests** where it makes sense to …

[PM-6848] Improved User verification on passkeys creation

---

src/Core/App.xaml.cs

When exceptions occur inside the lambda for the BroadcastService Callback in `App.xaml.cs` they can be difficult to read or incomplete.
The idea is to try to make them a bit more clear when looking at AppCenter diagnostics.
One potential way to improve them was to change the callback to be a named method instead off a lambda.
Also all the `MainThread` Invoke inside this callback were changed to have local functions instead of lambdas.
As an example a stacktrace that looked like this:
`at Bit.App.App.<>c__DisplayClass28_0.<<-ctor>b__2>d.MoveNext(`
Now looks like this:
`at Bit.App.App.<>c__DisplayClass29_0.<<BroadcastServiceMessageCallbackAsync>g__ExecuteNavigationAction|0>d.MoveNext(`
* **App.xaml.cs:**  …

[PM-7009] Improved exception messages for the Broadcast Service message callback function

---

src/App/Platforms/Android/Services/DeviceActionService.cs

Android App is currently crashing when launching a package name that is not found on the device.
Added specific Exception Try Catch to avoid crashing when the package name is not found.
`IntentSender.SendIntentException` is the Exception we get in Debug when trying to launch an invalid package name.
`Android.Util.AndroidException` is an Exception that seems to be reported on AppCenter for the same issue.
* **DeviceActionService:** Added the specific TryCatch
- If this change has particular **deployment requirements** - notify the …

[PM-7010] Fix for Android App crashing when launching app with invalid package name

---

src/iOS.Autofill/MainInterface.storyboard

Fix passkey cipher list empty view label on small devices

[PM-6844] Fix passkey cipher list empty view label small device

---

src/Core/Abstractions/IStateService.cs
src/Core/Services/StateService.cs
src/iOS.Autofill/CredentialProviderViewController.Passkeys.cs
src/iOS.Autofill/CredentialProviderViewController.cs

Fix account switching to work correctly on autofill, loading the latest state of the accounts.
* **StateService:** Added way to force reloading the state
* **CredentialProviderViewController:** Made `InitAppIfNeededAsync` async to be able to force reloading the state when loading the extension and also on the several callbacks for actions on the extension.
* **Others:** Also, ignored `Fido2AuthenticatorException` from logging them into AppCenter given they don't add any valuable logging if an exception is raised, and if that happens we log the problem in a different part of the code.
- If this change requires a …

[PM-6798] Fix account switch on autofill

---

src/iOS.Autofill/Utilities/BaseLoginListTableSource.cs

Remove duplicate master password reprompt when selecting a cipher for Passkey creation.
* **BaseLoginListTableSource:** Remove duplicate master password reprompt when selecting a cipher for Passkey creation.

[PM-6850] Remove duplicate MP-reprompt on passkey selection

---

src/iOS.Core/Utilities/ASHelpers.cs

Remove Non-Discoverable filter for passkeys when setting the credentials on the ASStore to see if that fixes some sites not displaying the passkey for quick OS bottom sheet selection.

[PM-6538] Remove Non-Discoverable filter for passkeys when setting the credentials on the ASStore

---

src/Core/Models/View/CipherView.cs
src/Core/Models/View/LoginView.cs
src/iOS.Autofill/Utilities/BaseLoginListTableSource.cs
src/iOS.Core/Utilities/ASHelpers.cs
src/iOS.Core/Views/ExtensionTableSource.cs

If all usernames are null on a cipher item that has passkeys, then `Cipher.Name` should be displayed for username.
* **CipherView:** Moved method to get the Username and take into account `Cipher.Name` as a possible fallback.
* **BaseLoginListTableSource:** Take into account username fallbacks for passkey items.

[PM-6655] Add null fallback cipher name on passkeys

---

src/Core/Services/Fido2AuthenticatorService.cs
src/Core/Services/Logging/ClipLogger.cs
src/Core/Utilities/Fido2/Fido2AuthenticatorException.cs
src/iOS.Autofill/CredentialProviderViewController.Passkeys.cs
src/iOS.Autofill/CredentialProviderViewController.cs
src/iOS.Autofill/Fido2MakeCredentialUserInterface.cs
src/iOS.Autofill/Utilities/BaseLoginListTableSource.cs
src/iOS.Autofill/Utilities/Fido2GetAssertionFromListUserInterface.cs

Fix account switch on iOS Autofill extension
* **Fido2AuthenticatorService:** Added a do...while for the first part of the flows so if the account is changed an exception is raised and the flow starts over. This was the fastest thing I could come up with to fix this situation.
* **CredentialProviderViewController:** Subscribed to account switched completed to reset and set the `AccountSwitchedException` on the TaskCompletionSources necessary for passkeys. Also improved the code and refactored a bit to be able to reuse some of it in another place.
* **CredentialProviderViewController.Passkeys:** Changed how we ensure vault is unlocked to consider more account states and reuse the navigation on the `CredentialProviderViewController`
* **Ohers:** Some fixes to use `Try...` way for setting …

[PM-6798] Fix account switch on iOS Autofill extension

---

src/iOS.Autofill/LoginListViewController.cs
src/iOS.Autofill/Models/Context.cs

When the user tries to autofill a webpage and there’s a passkey related error, they’ll see our iOS extension open with an error message. After pressing ok, the activity indicator / loading spinner isn’t removed and search won’t work, preventing users from autofilling other credentials.
We should fallback to passwords in this scenario.
* **LoginListViewController.cs:** Added fallback reload scenario
* **Context.cs:** Added new boolean Flag to distinguish the fallback scenario
Fallback Password List if exception occurs.
- If this change …

[PM-7186] Fallback to password list on exception

---

src/iOS.Autofill/LoginListViewController.cs

Remove error message when showing passwords as fallback
Message commented and added some comments to code also.
* **LoginListViewController.cs:**

[PM-7186] Remove error message when showing password list as a fallback

---

build.cake

Updates the iOS Encryption Export Compliance Code to match our Beta AppStoreConnect app.

[PM-7309] iOS Beta variants now have their own Encryption Export Compliance Code

---

src/Core/Controls/CipherViewCell/CipherViewCell.xaml
src/Core/Models/View/CipherView.cs
src/Core/Pages/Vault/AutofillCiphersPageViewModel.cs
src/Core/Pages/Vault/CipherItemViewModel.cs
src/Core/Utilities/IconGlyphConverter.cs
src/Core/Utilities/IconGlyphExtensions.cs

Android is not showing passkey icon when "show website icons" is disabled
Changed IconGlyphExtensions to take into account if the cipher has Fido2Credential and return passkey icon in that scenario.
* **IconGlyphExtensions.cs:** 
Before             |  After
:-------------------------:|:-------------------------:

[PM-7369] Show passkey icon on android when the item has a Fido2 credential

---

src/App/Platforms/Android/Autofill/Fido2MakeCredentialUserInterface.cs
src/Core/Abstractions/IFido2MakeCredentialConfirmationUserInterface.cs
src/Core/Utilities/AccountManagement/AccountsManager.cs
src/Core/Utilities/AppHelpers.cs

Fix updating flag of having unlocked in the current transaction on passkey creation in order for the User Verification to perform correctly on unlocked vaults.
* **Fido2MakeCredentialUserInterface:** Added function setter that gets the current state of if the vault has been unlocked in the current transaction and used that inside the flow.
* **AppHelpers:** Set the aforementioned function with the `AppOptions` property.
* **AccountsManager:** Clear has been unlocked in the current transaction flag when switching accounts.
- If this …

[PM-7365] Fix User Verification to be done correctly on passkey creation on Never timeout vault

---

src/App/Platforms/Android/Autofill/Fido2MakeCredentialUserInterface.cs
src/App/Platforms/Android/MainApplication.cs
src/Core/Abstractions/IFido2MakeCredentialConfirmationUserInterface.cs
src/Core/Pages/Vault/AutofillCiphersPageViewModel.cs
src/Core/Pages/Vault/CiphersPageViewModel.cs

Implemented cipher selection on search on Fido2 creation
* **Fido2MakeCredentialUserInterface:** Moved logic of cipher selection check to create a Fido2 credential here in order to be reused between cipher list and search.
* **CiphersPageViewModel:** Added call to the aforementioned UserInterface to select a cipher for Fido2 creation

[PM-7366] Select cipher on search on Fido2 creation

---

src/Core/App.xaml.cs
src/Core/Pages/Vault/CipherAddEditPage.xaml.cs
src/Core/Pages/Vault/CipherAddEditPageViewModel.cs
src/Core/Pages/Vault/CiphersPageViewModel.cs
src/Core/Utilities/AccountManagement/AccountsManager.cs
src/Core/Utilities/AppHelpers.cs

Fix Android only interfaces to be constrained to Android on Fido2 flows.
* **Everything:** Constrained to Android the resolve and usage of `IFido2MakeCredentialConfirmationUserInterface`

[PM-7385] Fix IFido2MakeCredentialConfirmationUserInterface usages

---

src/iOS.Core/Views/CipherLoginTableViewCell.cs

Update favicons placeholder color on autofill iOS to be alike main app
* **CipherLoginListTableViewCell:** Updated icon color

[PM-7518] Update favicons placeholder color autofill iOS

---

src/App/Platforms/Android/MainActivity.cs

Fix UserVerification on Fido2 credential creation on Android
* **MainActivity:** Reset `HasUnlockedInThisTransaction` when a new transaction starts on Fido2 credential creation on Android so User verification is done correctly

[PM-7365] Fix UserVerification on Fido2 credential creation on Android

---

src/App/App.csproj
src/App/Platforms/iOS/PrivacyInfo.xcprivacy
src/iOS.Autofill/iOS.Autofill.csproj
src/iOS.Extension/iOS.Extension.csproj
src/iOS.ShareExtension/iOS.ShareExtension.csproj
src/watchOS/bitwarden/PrivacyInfo.xcprivacy
src/watchOS/bitwarden/bitwarden.xcodeproj/project.pbxproj

Add privacy manifest file to iOS, its extensions and the watchOS app.
* **PrivacyInfo.xcprivacy:** Add this privacy manifest that includes use of required reasons API

[PM-6971] Add privacy manifest file to iOS

---

src/App/Platforms/Android/Autofill/CredentialHelpers.cs
src/App/Platforms/Android/Autofill/CredentialProviderSelectionActivity.cs
src/Core/Abstractions/IFido2ClientService.cs
src/Core/Abstractions/IFido2MediatorService.cs
src/Core/Services/Fido2AuthenticatorService.cs
src/Core/Services/Fido2ClientService.cs
src/Core/Services/Fido2MediatorService.cs
src/Core/Utilities/Fido2/Fido2AuthenticatorGetAssertionResult.cs
src/Core/Utilities/Fido2/Fido2ClientAssertCredentialResult.cs
src/Core/Utilities/Fido2/Fido2SelectedCredential.cs
test/Core.Test/Services/Fido2ClientAssertCredentialTests.cs
test/Core.Test/Services/Fido2ClientCreateCredentialTests.cs

This redirects all android fido2 calls to the `Fido2Client`, and correctly maps to/from extension objects

[PM-7257] android add support for web authn resident key credential property in our net mobile app 2

---

src/App/Platforms/Android/Autofill/CredentialHelpers.cs
src/App/Platforms/Android/Autofill/CredentialProviderSelectionActivity.cs
src/Core/Resources/Localization/AppResources.Designer.cs
src/Core/Resources/Localization/AppResources.resx

Show error message when trying to use/create a fido2 credential on Android from a native app, i.e. origin is `null`

[PM-7585] Show error message when Origin is null on Fido2 Android

---

src/App/Platforms/Android/Autofill/CredentialProviderSelectionActivity.cs
src/App/Platforms/Android/Autofill/Fido2GetAssertionUserInterface.cs
src/App/Platforms/Android/MainApplication.cs
src/Core/Utilities/Fido2/Fido2GetAssertionUserInterface.cs

Fix proper implementation of IFido2GetAssertionUserInterface Android
* **Fido2GetAssertionUserInterface:** Implemented this interface correctly, adding an `Init(...)` method to initialize the things in this singleton for every fido2 request. Moved ensure vault unlocked and user verification here as well instead of on the activity.
* **Others:** Updated to use the new interface correctly

[PM-7623] Fix proper implementation of IFido2GetAssertionUserInterface Android

---

src/App/Platforms/Android/Push/FirebaseMessagingService.cs

Google is deprecating their legacy FCM endpoints (GCM), so migrate to FCMv1 as outlined by Microsoft:
https://learn.microsoft.com/en-us/azure/notification-hubs/notification-hubs-gcm-to-fcm
ref: https://github.com/bitwarden/server/pull/3917
(old) GCM format: 
```
{
"data": {
"data": {
"type": 1,
"payload": "JSON_Data"
}
}
}
```
(new) FCM format:
```
{
"message": {
"data": {
"type": "1",
"payload": "JSON_Data"
}
}
}
```
* **FirebaseMessagingService.cs:** Update remote message parsing to account for GCM and FCM message formats. GCM is detected and kept as-is. FCM is detected and re-constructed into a JObject to match the existing GCM format.
- Please add **unit tests** where it makes sense to do so …

[PM-7631] Handle new FCMv1 format

---

src/App/Platforms/Android/Autofill/CredentialHelpers.cs
src/App/Platforms/Android/Autofill/CredentialProviderSelectionActivity.cs
src/App/Platforms/Android/Utilities/CallingAppInfoExtensions.cs
src/Core/Abstractions/IFido2ClientService.cs
src/Core/Abstractions/IFido2MediatorService.cs
src/Core/Services/Fido2ClientService.cs
src/Core/Services/Fido2MediatorService.cs
src/Core/Utilities/Fido2/Fido2ExtraAssertCredentialParams.cs
src/Core/Utilities/Fido2/Fido2ExtraCreateCredentialParams.cs

Implement Fido2 credentials autofill and creation from native Android apps.
* **Fido2ClientService:** Added extra parameters objects to pass additional data like the client data hash and the android package name that is needed for the client data json. Also, added additional logic for the origin validations so they're not performed when the request comes from a native app.
* **CallingAppInfoExtensions:** Extracted the `CallingAppInfo` to Android origin here so it can be reused.
* **CredentialHelpers:** Updated the code with the new needed parameters and improved the code when the flows fails. Also updated `origin` accordingly depending on whether the `Origin` from the RP is `null` or not.
* **CredentialProviderSelectionActivity:** Updated the code with the new needed parameters and …

[PM-7553] Implement native app Fido2 credentials

---

src/Core/Utilities/TaskExtensions.cs

Fix crash produced for non-catched exception on iOS Autofill when opening the combined Password + Passkeys view with no Passkeys to load.
* **TaskExtensions:** Moved `shouldLogException` to an internal `if` so all exceptions are catched and then the specific ones logged which was the original intent.

[PM-7698] Fix crash produced for non-catched exception on iOS Autofill

---

.github/labeler.yml
.github/workflows/pr-labeler.yml

#2895 updated our PR Labeler to V5 which changed the structure of `labeler.yml`, reason why this build step has been failing. This PR fixes that.
While at it, added "Xamarin.AndroidX.Credentials" folder path to the Android label.

[PM-7922] Updating labeler.yml to the new format required by V5

---

src/iOS.Autofill/CredentialProviderViewController.Passkeys.cs
src/iOS.Autofill/CredentialProviderViewController.cs

Fix autofill cancelling the request producing inconsistent behavior on passwords because of Fido2 check safeguard.
* **CredentialProviderViewController:** Changed the safeguard for iOS < 17 to only check if the context is for passkeys/fido2 which previously was wrongly checking the condition.

[PM-7255] Fix autofill cancelling the request producing inconsistent behavior

---

src/Core/Pages/Accounts/LoginPage.xaml.cs
src/Core/Pages/Accounts/LoginPasswordlessRequestPage.xaml.cs
src/Core/Pages/Accounts/RegisterPage.xaml.cs
src/Core/Pages/Accounts/TwoFactorPage.xaml.cs
src/Core/Pages/Accounts/TwoFactorPageViewModel.cs
src/Core/Pages/CaptchaProtectedViewModel.cs
src/iOS.Autofill/CredentialProviderViewController.cs

Fix for WebAuthn 2FA not working on iOS Autofill extension given that the `UIWindow` was not getting properly gotten. This fixes it by using our custom workaround for it.
This affects WebAuthn as well as could affect Captcha views.
* **All:** Applied workaround to use `ShouldUseSharedApplicationKeyWindow` when coming from iOS extension and updated callers to properly pass `FromIosExtension` flag to it gets applied correctly.

[PM-8051] Fix WebAuthenticator getting the Window properly on iOS Autofill extension 2FA WebAuthn

---

src/iOS.Autofill/CredentialProviderViewController.cs

Fix 2FA launch crash from iOS autofill
* **CredentialProviderViewController:** It was missing the `appOptions` to be passed to the `App` and therefore crashing afterwards.

[PM-8051] Fix 2FA launch crash from iOS autofill

---

src/iOS.Autofill/CredentialProviderViewController.cs

Fix Password Autofill from Quick Type on iOS < 17
* **CredentialProviderViewController:** Uncommented old deprecated methods to autofill using the Quick type bar so it works on iOS < 17.

[PM-8666] Fix Password Autofill from Quick Type on iOS < 17

---

app/src/main/java/com/x8bit/bitwarden/BitwardenApplication.kt
app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepository.kt
app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
app/src/main/java/com/x8bit/bitwarden/data/platform/manager/di/PlatformManagerModule.kt
app/src/main/java/com/x8bit/bitwarden/data/platform/manager/event/OrganizationEventManager.kt
app/src/main/java/com/x8bit/bitwarden/data/platform/manager/event/OrganizationEventManagerImpl.kt
app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
app/src/test/java/com/x8bit/bitwarden/data/platform/manager/event/OrganizationEventManagerTest.kt

[BIT-2418](https://livefront.atlassian.net/browse/BIT-2418)
This PR adds the `OrganizationEventManager` class to store and upload organization events.
- …

BIT-2418: Add the OrganizationEventManager

---

app/src/main/java/com/x8bit/bitwarden/data/platform/manager/event/OrganizationEventManager.kt
app/src/main/java/com/x8bit/bitwarden/data/platform/manager/event/OrganizationEventManagerImpl.kt
app/src/test/java/com/x8bit/bitwarden/data/platform/manager/event/OrganizationEventManagerTest.kt

N/A
This PR removes the `suspend` keyword for the trackEvent function of the `OrganizationEventManager`. this simplifies the interface and allows us to manage the process within out own scope.
issue and …

trackEvent should not suspend

---

app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/EventDiskSource.kt
app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/EventDiskSourceImpl.kt
app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/network/api/EventApi.kt
app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/network/model/OrganizationEventJson.kt
app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/network/service/EventService.kt
app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/network/service/EventServiceImpl.kt
app/src/main/java/com/x8bit/bitwarden/data/platform/manager/event/OrganizationEventManagerImpl.kt
app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/disk/EventDiskSourceTest.kt
app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/network/service/EventServiceTest.kt
app/src/test/java/com/x8bit/bitwarden/data/platform/manager/event/OrganizationEventManagerTest.kt

N/A
This PR renames a network model to include the `Json` suffix. …

Append 'Json' suffix to network model name

---

app/src/main/java/com/x8bit/bitwarden/data/autofill/builder/FillResponseBuilderImpl.kt
app/src/main/java/com/x8bit/bitwarden/data/autofill/di/AutofillModule.kt
app/src/main/java/com/x8bit/bitwarden/data/autofill/manager/AutofillCompletionManagerImpl.kt
app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/search/SearchViewModel.kt
app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt
app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModel.kt
app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/model/ListingItemOverflowAction.kt
app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/util/CipherViewExtensions.kt
app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModel.kt
app/src/test/java/com/x8bit/bitwarden/data/autofill/builder/FillResponseBuilderTest.kt
app/src/test/java/com/x8bit/bitwarden/data/autofill/manager/AutofillCompletionManagerTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/search/SearchScreenTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/search/SearchViewModelTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/search/util/SearchUtil.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModelTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/util/VaultItemListingDataUtil.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/util/CipherViewExtensionsTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModelTest.kt

[BIT-2419](https://livefront.atlassian.net/browse/BIT-2419)
This PR adds most of the organization events to the app, a second PR will be coming shortly to get the last of them. …

Add organization event tracking

---

app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemCardContent.kt
app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModel.kt
app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/handlers/VaultCardItemTypeHandlers.kt
app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/util/CipherViewExtensions.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemScreenTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModelTest.kt

[PM-7607](https://bitwarden.atlassian.net/browse/PM-7607)
This PR adds the master password re-prompt for the card cipher code and number.
| Before | After
| --- | --- |
| <video src="https://github.com/bitwarden/android/assets/125928928/a0793022-19bf-4276-b5af-4fe8164dd7ad" width="300" /> | <video src="https://github.com/bitwarden/android/assets/125928928/edfe4bce-be78-43d0-a094-ea050d4a2fcd" width="300" /> | …

Add password reprompt for card number and code

---

.github/workflows/crowdin-push.yml
crowdin.yml

https://bitwarden.atlassian.net/browse/PM-8016
Upload source strings to Crowdin on push events to `main`. 
When uploading, directory hierarchy is preserved to decouple Android source files from other platforms.
Target destination for Android string source files is `res/values/strings.xml`
- 🤔 …

[PM-8016] Push string resources to Crowdin

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/x8bit/bitwarden/BitwardenApplication.kt
app/src/main/java/com/x8bit/bitwarden/data/platform/manager/di/PlatformManagerModule.kt
app/src/main/java/com/x8bit/bitwarden/data/platform/manager/restriction/RestrictionManager.kt
app/src/main/java/com/x8bit/bitwarden/data/platform/manager/restriction/RestrictionManagerImpl.kt
app/src/main/res/values/strings_non_localized.xml
app/src/main/res/xml/app_restrictions.xml
app/src/test/java/com/x8bit/bitwarden/data/platform/manager/restriction/RestrictionManagerTest.kt

[BIT-2411](https://livefront.atlassian.net/browse/BIT-2411)
This PR adds logic for managed devices to obtain pre-configured URLs. …

BIT-2411: Add logic for managed device pre-configured URLs

---

app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/search/util/SearchTypeDataExtensions.kt
app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/search/util/SearchTypeDataExtensionsTest.kt

[BIT-2433](https://livefront.atlassian.net/browse/BIT-2433)
This PR filters any deleted items from the search unless you are explicitly searching the trash. …

BIT-2433: Filter trash from search results

---

app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/network/interceptor/BaseUrlInterceptors.kt
app/src/main/java/com/x8bit/bitwarden/data/platform/repository/util/EnvironmentUrlDataJsonExtensions.kt
app/src/test/java/com/x8bit/bitwarden/data/platform/repository/util/EnvironmentUrlsDataJsonExtensionsTest.kt

N/A
This PR cleans up the environment urls to create a more consistent way of retrieving the appropriate URLs.
Additionally, the urls are now sanitized for `/` to ensure that custom urls with trailing forward slashes work correctly. …

Clean up environment urls

---

app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModel.kt
app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/util/CipherViewExtensions.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModelTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/item/util/CipherViewExtensionsTest.kt

N/A
This PR updates `CipherViewExtensions` to use previous state to avoid clearing user set values like visibility and password re-prompt.
| --- | --- |
| <video src="https://github.com/bitwarden/android/assets/125928928/33800291-3bde-412f-9e22-187c64b2e017" width="300" /> | <video src="https://github.com/bitwarden/android/assets/125928928/1f3ae5c3-ba4c-4a9f-aff4-c15bc2486a87" width="300" /> | …

Update CipherViewExtensions to use previous state to avoid clearing user set values

---

app/build.gradle.kts
app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/util/TwoFactorAuthMethodExtensions.kt
app/src/main/res/values/strings.xml
app/src/main/res/values/strings_non_localized.xml
app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/util/TwoFactorAuthMethodExtensionTest.kt

https://livefront.atlassian.net/browse/BIT-2140
Move newly added strings related to feedback typeform and vault export to the primary strings resource file so they are tracked by Crowdin.
"MissingTranslation" lint check is disabled to allow source strings to be added without initial translations.
- 🤔 …

[BIT-2140] Add strings for typeform and export vault

---

app/src/main/java/com/x8bit/bitwarden/MainActivity.kt
app/src/main/java/com/x8bit/bitwarden/MainViewModel.kt
app/src/test/java/com/x8bit/bitwarden/MainViewModelTest.kt

N/A
This PR fixes a bug that clears the screen capture state on the activity whenever language changes (whenever it recomposes). …

Fix a screen capture bug that clears the setting when the app language changes

---

app/src/main/java/com/x8bit/bitwarden/data/auth/repository/util/RefreshTokenResponseExtensions.kt
app/src/test/java/com/x8bit/bitwarden/data/auth/repository/util/RefreshTokenResponseJsonTest.kt

N/A
This PR addresses an issue where the JWT `premium` status was returning false even when a user has premium. So we no longer use that value to update the premium status. The sync response is stilled used to update the premium state. …

Fix bug where JWT token clearing premium status

---

.github/ISSUE_TEMPLATE/bug.yml

https://bitwarden.atlassian.net/browse/PM-9340
Syntax error seems to be the `:` and not the links as previous PR indicated, added quotes to the whole string. …

[PM-9340] Fix bug template syntax error by adding quotes to label

---

app/src/main/java/com/x8bit/bitwarden/data/platform/manager/PushManagerImpl.kt
app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/NotificationPayload.kt

N/A
This PR resolves a crash found in Crashlytics:
```
Fatal Exception: kotlinx.serialization.MissingFieldException: Fields [Id, RevisionDate] are required for type with serial name 'com.x8bit.bitwarden.data.platform.manager.model.NotificationPayload.SyncCipherNotification', but they were missing at path: $
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:95)
at kotlinx.serialization.json.Json.decodeFromString(Json.kt:165)
at com.x8bit.bitwarden.data.platform.manager.PushManagerImpl.onMessageReceived(PushManagerImpl.kt:347)
at com.x8bit.bitwarden.data.platform.manager.PushManagerImpl.onMessageReceived(PushManagerImpl.kt:125)
at com.x8bit.bitwarden.data.push.BitwardenFirebaseMessagingService.onMessageReceived(BitwardenFirebaseMessag …
```

Update NotificationPayload to handle null values

---

app/src/main/java/com/x8bit/bitwarden/data/platform/manager/PushManagerImpl.kt
app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/NotificationPayload.kt

[BIT-2438](https://livefront.atlassian.net/browse/BIT-2438)
This PR updates the logic for processing notifications to parse the payloads assuming anything can be null. …

BIT-2438: Update push notification processing logic to be more lenient

---

app/src/main/java/com/x8bit/bitwarden/data/autofill/util/AutofillValueExtensions.kt
app/src/test/java/com/x8bit/bitwarden/data/autofill/util/AutofillValueExtensionsTest.kt

[BIT-2442](https://livefront.atlassian.net/browse/BIT-2442)
This PR adds a check to avoid an exception when attempting to parse autofill data as text.
- …

BIT-2442: check type before extracting autofill text

---

app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/util/AccountSummaryExtensions.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/vault/util/AccountSummaryExtensionsTest.kt

[BIT-2443](https://livefront.atlassian.net/browse/BIT-2443)
This PR fixes a crash when parsing initials that have extra blank spaces in them.
Stacktrace:
```
Fatal Exception: java.util.NoSuchElementException: Char sequence is empty.
at kotlin.text.StringsKt___StringsKt.first(_Strings.kt:76)
at com.x8bit.bitwarden.ui.vault.feature.vault.util.AccountSummaryExtensionsKt._get_initials_$lambda$0(AccountSummaryExtensions.kt:25)
at com.x8bit.bitwarden.ui.vault.feature.vault.util.AccountSummaryExtensionsKt.$r8$lambda$75K7JSwE63qgrtaNuTKqE1qCJyM()
at com.x8bit.bitwarden.ui.vault.feature.vault.util.AccountSummaryExtensionsKt$$ExternalSyntheticLambda0.invoke(D8$$SyntheticClass)
at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:84)
...
```
- All …

BIT-2443: Fix crash caused by extra blank spaces in name

---

app/src/main/java/com/x8bit/bitwarden/data/platform/manager/ciphermatching/CipherMatchingManagerImpl.kt
app/src/main/java/com/x8bit/bitwarden/data/platform/util/RegexUtils.kt
app/src/test/java/com/x8bit/bitwarden/data/platform/util/RegexUtilsTest.kt

[BIT-2439](https://livefront.atlassian.net/browse/BIT-2439)
This PR fixes a crash that can happen when a user enters a regular expression that is not a valid pattern.
```
Fatal Exception: java.util.regex.PatternSyntaxException: Unrecognized backslash escape sequence in pattern near index 4
.*\maj\-soul\.com.*
^
at com.android.icu.util.regex.PatternNative.compileImpl(PatternNative.java)
at com.android.icu.util.regex.PatternNative.<init>(PatternNative.java:53)
at com.android.icu.util.regex.PatternNative.create(PatternNative.java:49)
at java.util.regex.Pattern.compile(Pattern.java:3533)
at java.util.regex.Pattern.<init>(Pattern.java:1419)
at java.util.regex.Pattern.compile(Pattern.java:947)
at kotlin.text.Regex.<init>(Regex.kt:91)
at …
```

BIT-2439: Handle invalid patterns when processing regular expression matching

---

app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreen.kt

[BIT-2431](https://livefront.atlassian.net/browse/BIT-2431)
Fix bug where the password length field would shrink when the screen display size is zoomed all the way out. 
- able to repro original issue on Pixel 6 Pro (OS 14)
- unable to repro on Samsung device
https://github.com/bitwarden/android/assets/149429124/732a4de5-a8ce-4f4d-ab6d-d2b039f4bdc6
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes …

BIT-2431 add condition to only update labelTextWidth on initial layout

---

app/src/main/java/com/x8bit/bitwarden/data/autofill/util/AutofillIntentUtils.kt

[PM-9077](https://bitwarden.atlassian.net/browse/PM-9077)
This PR addresses a bug in inline autofill where having multiple options that can be used to fill the same field causes the PendingIntents to not function at all. The request codes for the pending intents are now based on random UUIDs ensuing unique request codes.
- ❓ …

PM-9077: Ensure each PendingIntent for inline autofill uses unique requestCode

---

app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingEmpty.kt
app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/util/VaultItemListingDataExtensions.kt
app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultNoItems.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingScreenTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/util/VaultItemListingDataExtensionsTest.kt

[PM-9443](https://bitwarden.atlassian.net/browse/PM-9443)
Updated message and button text for autofill empty state for passkeys.
Added an icon for the autofill search:
| --- | --- |
| <img src="https://github.com/bitwarden/android/assets/125921730/d49ef4df-c87d-4c73-961e-f8122ed53302" /> | <img src="https://github.com/bitwarden/android/assets/125921730/047778ef-490e-4fe9-9705-de0df82809b3" /> |
Updated the message and button for the autofill search for passkeys:
| --- | --- |
| <img src="https://github.com/bitwarden/android/assets/125921730/8ac37d9d-1e76-4715-874e-6b4ed3da8b7f" /> | <img src="https://github.com/bitwarden/android/assets/125921730/9a461eaa-4f56-48f5-8ecf-9a6d5d98b7b1" /> |
- All formatters and local …

PM-9443: Update empty search state

---

app/src/main/java/com/x8bit/bitwarden/data/autofill/builder/FilledDataBuilderImpl.kt
app/src/test/java/com/x8bit/bitwarden/data/autofill/builder/FilledDataBuilderTest.kt

[BIT-2446](https://livefront.atlassian.net/browse/BIT-2446)
This PR limits the number of inline autofill suggestions a user can see as well as the number of regular autofill suggestions a user can see. If the user has additional items, they can still view them by selecting the `My Vault` item.
The documentation for inline autofill suggests no more than 5 for performace reasons:
```
/**
* Max number of suggestions expected from the response. It must be a positive value.
* Defaults to {@code SUGGESTION_COUNT_UNLIMITED} if not set.
*
* <p>In practice, it is recommended that the max suggestion count does not exceed <b>5</b>
* for performance reasons.</p>
*/
```
We additionally want to avoid `TransactionTooLargeException`s that can occur when the fill response is too large. documentation can …

BIT-2446: Limit the number of inline autofill items that can be displayed

---

app/src/fdroid/java/com/x8bit/bitwarden/data/platform/manager/CrashLogsManagerImpl.kt
app/src/main/java/com/x8bit/bitwarden/data/platform/manager/CrashLogsManager.kt
app/src/standard/java/com/x8bit/bitwarden/data/platform/manager/CrashLogsManagerImpl.kt

N/A
Add functionality to allow us to track errors that do not result in a crash. This new functionality respects whether the user has opted out of crashing logging and does not function for FDroid users.
This errors will be displayed in Crashlytics but they will be listed as `Non-fatals` instead of the `Crashes` you normally see.
- …

Add ability to log non-fatal errors

---

app/src/main/java/com/x8bit/bitwarden/data/autofill/util/AutofillIntentUtils.kt
app/src/main/java/com/x8bit/bitwarden/data/autofill/util/FilledDataExtensions.kt
app/src/main/java/com/x8bit/bitwarden/ui/platform/manager/nfc/NfcManagerImpl.kt

N/A
This PR updates a bunch of pending intents to use a random request code in order to avoid collisions.
- …

Use random ints for request codes to ensure no overlap

---

app/src/main/java/com/x8bit/bitwarden/data/autofill/util/ViewNodeExtensions.kt
app/src/test/java/com/x8bit/bitwarden/data/autofill/util/ViewNodeExtensionsTest.kt

N/A
Update autofill to identify an `AutoCompleteTextView` as an input field. This allowed the username field to be found when logging in to the Linked In app. …

Add support for AutoCompleteTextView as an input field

---

app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt

Define a utility function for clearing the VaultAddEdit dialog state. …

Introduce utility function for clearing VaultAddEdit dialog state

---

app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt

Define a utility function for displaying VaultAddEdit error messages. …

Introduce utility function for displaying VaultAddEdit error message

---

app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/datasource/network/model/PublicKeyCredentialCreationOptions.kt

https://bitwarden.atlassian.net/browse/PM-8137
Refactor PublicKeyCredentialCreationOptions so that it reflects the WebAuth object spec.
- 🎨 (`:art:`) …

Refactor PublicKeyCredentialCreationOptions to match WebAuthn spec

---

app/src/main/java/com/x8bit/bitwarden/data/autofill/model/AutofillView.kt
app/src/main/java/com/x8bit/bitwarden/data/autofill/parser/AutofillParserImpl.kt
app/src/main/java/com/x8bit/bitwarden/data/autofill/util/ViewNodeExtensions.kt
app/src/test/java/com/x8bit/bitwarden/data/autofill/parser/AutofillParserTests.kt
app/src/test/java/com/x8bit/bitwarden/data/autofill/util/ViewNodeExtensionsTest.kt

N/A
This PR adds logic to find a username field for autofill by assuming any `Unused` field directly in front of the password field is the username field. …

Add logic to find missing username fields

---

app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/search/SearchViewModel.kt
app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/folders/FoldersViewModel.kt
app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/folders/addedit/FolderAddEditViewModel.kt
app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/SendViewModel.kt
app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendViewModel.kt
app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt
app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/attachments/AttachmentsViewModel.kt
app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/movetoorganization/VaultMoveToOrganizationViewModel.kt
app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/verificationcode/VerificationCodeViewModel.kt
app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/search/SearchViewModelTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/folders/FoldersViewModelTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/folders/addedit/FolderAddEditViewModelTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/send/SendViewModelTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/attachments/AttachmentsViewModelTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/movetoorganization/VaultMoveToOrganizationViewModelTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/verificationcode/VerificationCodeViewModelTest.kt

N/A
This PR updates the way we concatenate no network errors in the app. In many cases, we were not adding a space between the two strings which caused them to run into each other. Some spots used newline to separate the two strings and those have also been updated to maintain consistency throughout the app. …

Update no network errors to be consistent and have a space inbetween concatenated text

---

app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillScreen.kt
app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillViewModel.kt
app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillScreenTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillViewModelTest.kt

N/A
This PR hides the inline autofill option in the UI when the device OS does not support it.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/7de227c7-98e7-48e4-b191-f49593c75815" width="300" /> | <img src="https://github.com/user-attachments/assets/8824581e-c900-44c1-8ec7-8dbd8f1b94df" width="300" /> | …

Hide inline autofill option when not supported

---

app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/deleteaccount/DeleteAccountViewModel.kt
app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/deleteaccount/DeleteAccountViewModelTest.kt

https://bitwarden.atlassian.net/browse/PM-7495
Show the correct verbiage in the dialog if the user enters the wrong master password, we are doing this by using the existing client side check we have used elsewhere in the app, if that returns a result and password is *NOT* valid, we show the dialog saying so, otherwise use the same logic as before where we just use the server response and message.
https://github.com/bitwarden/android/assets/149429124/ca8c8ce1-6504-411f-bfb8-586392a98f59 …

PM-7495 perform client side check for invalid MP before account deletion

---

app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginViewModel.kt
app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginViewModelTest.kt

[PM-9017](https://bitwarden.atlassian.net/browse/PM-9017)
Update the continue button state when switching the AuthMethod state so it updates if there is a needed default state (i.e. with Duo)
issue and …

PM-9017 updated the continue button state when switching 2FA method

---

app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/manager/Fido2CredentialManager.kt
app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/manager/Fido2CredentialManagerImpl.kt

https://bitwarden.atlassian.net/browse/PM-8137
During FIDO 2 operations, Fido2CredentialManager will track whether the user has performed an action that explicitly verifies their identity.
`Fido2CredentialManager.isUserVerified` can be read to determine if the user is verified. It can also be modified any time a verification action completes. User verification actions include, but not limited to, biometric authentication, device credential entry, or vault unlock.
- Updated any necessary documentation or informed the …

[PM-8137] Introduce FIDO 2 user verification tracking

---

app/build.gradle.kts

I believe this is why there are cases of the builds passing on open PR jobs for `Detekt` but then failing on the merge job. I think cause this is triggered by the sonar `check` only in the dev builds it passes the check if all the files in the `main` source set pass, but ignores the tests.

[Build Issue] use full source set to match fastfile test task

---

app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dialog/BitwardenOverwritePasskeyConfirmationDialog.kt

PM-9407
Create a reusable dialog that prompts the user to confirm overwriting an existing passkey during FIDO 2 credential registration.
- 🎨 (`:art:`) …

[PM-9407] Create reusable overwrite passkey confirmation dialog

---

app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditCardItems.kt
app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditIdentityItems.kt
app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditLoginItems.kt
app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditSecureNotesItems.kt

https://bitwarden.atlassian.net/browse/PM-9838
Add height spacer to all list items for the `VaultAddEdit*Items` lists so the spacing matches the "view" versions of the VaultItem screens
| before | after |
| ![beforepm9838](https://github.com/user-attachments/assets/7634f2a4-9ae6-474f-bfed-0903d21ce580) | ![afterpm9838](https://github.com/user-attachments/assets/8b64a512-86e3-4299-bc01-84d7b972a499) | …

[PM-9838] Custom field spacing on Add/Edit item screen

---

app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/search/SearchViewModel.kt
app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/search/util/SearchTypeDataExtensions.kt
app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/util/VaultItemListingDataExtensions.kt
app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/util/CipherViewExtensions.kt
app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/util/VaultDataExtensions.kt
app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/search/SearchScreenTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/search/SearchViewModelTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/search/util/SearchTypeDataExtensionsTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingScreenTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/util/VaultItemListingDataExtensionsTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/util/CipherViewExtensionsTest.kt

https://bitwarden.atlassian.net/browse/PM-9844
Currently from any of the Vault item listing areas (VaultScreen, Collection, and Search) you can copy a TOTP code without meeting one of the required precondition (a premium account or legacy Org. uses TOTP rule). This PR adds condition check for adding the "copy TOTP" overflow action only if the the user has premium or the CipherView being converted has a `organizationUsesTotp` value which is `true`
- Updated any necessary documentation or informed the documentation …

[PM-9844] Android - Non-Premium Users Can Copy TOTP Code From Item Menu

---

app/src/main/java/com/x8bit/bitwarden/data/auth/manager/UserLogoutManagerImpl.kt
app/src/main/java/com/x8bit/bitwarden/data/autofill/util/CipherViewExtensions.kt
app/src/main/java/com/x8bit/bitwarden/data/vault/manager/VaultLockManagerImpl.kt
app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/landing/LandingViewModel.kt
app/src/test/java/com/x8bit/bitwarden/data/auth/manager/UserLogoutManagerTest.kt
app/src/test/java/com/x8bit/bitwarden/data/vault/manager/VaultLockManagerTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/landing/LandingViewModelTest.kt

https://bitwarden.atlassian.net/browse/PM-8534
If more than one accounts are available and one has `LOGOUT` as the session timeout action, the app should switch to the next active account. Additionally added pre-populating the email input if ending up on the Landing screen when switching to the "soft" logged out account.
https://github.com/user-attachments/assets/d1496bde-244e-4d63-ac49-9541c26d4df1
- 📝 …

PM-8534 update the active account after a "soft logout"

---

app/src/main/java/com/x8bit/bitwarden/data/autofill/processor/AutofillProcessorImpl.kt
app/src/test/java/com/x8bit/bitwarden/data/autofill/processor/AutofillProcessorTest.kt

N/A
This PR updates the Autofill Processor to do _all_ the parsing and processing of autofill data inside a single `Job`. This means that a cancellation will stop everything. …

All of the autofill processing happens in a job

---

app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultScreen.kt
app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModel.kt
app/src/test/java/com/x8bit/bitwarden/ui/platform/manager/permissions/FakePermissionManager.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultScreenTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModelTest.kt

[PM-9659](https://bitwarden.atlassian.net/browse/PM-9659)
This PR disables the push notifications permission request on FDroid since we do not use push notifications on FDroid. …

PM-9659: Do not show push notification permissions on FDroid

---

app/src/main/java/com/x8bit/bitwarden/data/autofill/di/AutofillModule.kt
app/src/main/java/com/x8bit/bitwarden/data/autofill/processor/AutofillProcessorImpl.kt
app/src/test/java/com/x8bit/bitwarden/data/autofill/processor/AutofillProcessorTest.kt

N/A
This PR adds a fallback to ensure that any `TransationToLargeException` in the AutofillService will be handled gracefully. …

Catch TransactionTooLargeExceptions in autofill

---

app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/manager/Fido2CredentialManager.kt
app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/manager/Fido2CredentialManagerImpl.kt
app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/model/PasskeyAttestationOptions.kt
app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt
app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/util/Fido2CredentialRequestExtensions.kt
app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
app/src/test/java/com/x8bit/bitwarden/data/autofill/fido2/manager/Fido2CredentialManagerTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/util/Fido2CredentialRequestExtensionsTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/util/PublicKeyCredentialCreationOptionsTestHelpers.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt

N/A
Rename PublicKeyCredentialCreationOptions to PasskeyAttestationOptions. Relocated it to the data model package since it is not a network model.
- 🎨 …

Refactor PublicKeyCredentialCreationOptions

---

app/src/test/java/com/x8bit/bitwarden/data/auth/datasource/sdk/AuthSdkSourceTest.kt

[BIT-877](https://livefront.atlassian.net/browse/BIT-877)
This PR re-enables a test that was blocked by a bug in Mockk. This bug has been resolved in the latest version and the test now works properly. …

BIT-877: Mockk update fixed a disabled test

---

app/src/main/java/com/x8bit/bitwarden/data/platform/manager/ciphermatching/CipherMatchingManagerImpl.kt
app/src/main/java/com/x8bit/bitwarden/data/platform/util/StringExtensions.kt
app/src/test/java/com/x8bit/bitwarden/data/platform/manager/ciphermatching/CipherMatchingManagerTest.kt

https://github.com/bitwarden/android/issues/3341
This PR updates the host URI matching logic to ignore the port. …

Update the HOST type cipher matching to ignore the port

---

app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/model/PasskeyAssertionOptions.kt
app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/model/PasskeyAttestationOptions.kt
app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/model/UserVerificationRequirement.kt
app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt
app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/util/PasskeyAssertionOptionsTestHelpers.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/util/PasskeyAttestationOptionsTestHelpers.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt

Reduce code duplication by extracting the FIDO 2 user verification constants to their own enum class since it is common across multiple FIDO 2 objects. …

Extract FIDO 2 user verification enum

---

app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/landing/LandingViewModel.kt
app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/landing/LandingScreenTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/landing/LandingViewModelTest.kt

[PM-9937](https://bitwarden.atlassian.net/browse/PM-9937)
If a user is trying to use the same email to sign in or create account using an existing email tied to another account but on a different host instance they should be able to.
https://github.com/user-attachments/assets/10132144-319a-4897-8080-b3c387e0e30d
- ❓ (`:question:`) …

PM-9937 an existing email should be able to add account from a different hosted instance.

---

app/src/main/java/com/x8bit/bitwarden/MainViewModel.kt
app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/model/Fido2CredentialAssertionRequest.kt
app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/util/Fido2IntentUtils.kt
app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/SpecialCircumstance.kt
app/src/main/java/com/x8bit/bitwarden/data/platform/manager/util/SpecialCircumstanceExtensions.kt
app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavScreen.kt
app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavViewModel.kt
app/src/test/java/com/x8bit/bitwarden/MainViewModelTest.kt
app/src/test/java/com/x8bit/bitwarden/data/autofill/fido2/model/Fido2CredentialAssertionRequestUtil.kt
app/src/test/java/com/x8bit/bitwarden/data/autofill/fido2/util/Fido2IntentUtilsTest.kt
app/src/test/java/com/x8bit/bitwarden/data/platform/manager/util/SpecialCircumstanceExtensionsTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavScreenTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavViewModelTest.kt

PM-9409
Introduce `Fido2Assertion` special circumstance to represent FIDO 2 credential authentication request intents.
When a Fido2Assertion circumstance is received the user will be navigated to the VaultItemListing screen after unlocking their vault, if needed. …

[PM-9409] Define FIDO 2 assertion Special Circumstance

---

app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/model/Fido2CredentialAssertionResult.kt
app/src/main/java/com/x8bit/bitwarden/ui/autofill/fido2/manager/Fido2CompletionManager.kt
app/src/main/java/com/x8bit/bitwarden/ui/autofill/fido2/manager/Fido2CompletionManagerImpl.kt
app/src/main/java/com/x8bit/bitwarden/ui/autofill/fido2/manager/Fido2CompletionManagerUnsupportedApiImpl.kt
app/src/main/java/com/x8bit/bitwarden/ui/platform/composition/LocalManagerProvider.kt
app/src/test/java/com/x8bit/bitwarden/ui/autofill/fido2/manager/Fido2CompletionManagerTest.kt

PM-9409
Update Fido2CompletionManager to handle FIDO 2 assertion results and respond to the system based on the assertion result. …

[PM-9409] Complete FIDO 2 assertion with appropriate response

---

app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/manager/Fido2CredentialManager.kt
app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/manager/Fido2CredentialManagerImpl.kt
app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/model/Fido2CredentialAssertionResult.kt
app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/model/Fido2PublicKeyCredential.kt
app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/sdk/util/PublicKeyCredentialAuthenticatorAssertionResponseExtensions.kt
app/src/main/java/com/x8bit/bitwarden/ui/autofill/fido2/manager/Fido2CompletionManagerImpl.kt
app/src/test/java/com/x8bit/bitwarden/data/autofill/fido2/manager/Fido2CredentialManagerTest.kt
app/src/test/java/com/x8bit/bitwarden/data/vault/datasource/sdk/util/PublicKeyCredentialAuthenticatorAssertionResponseExtensionsTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/autofill/fido2/manager/Fido2CompletionManagerTest.kt

PM-9409
Implement FIDO 2 credential assertion using the FIDO 2 credential manager. …

[PM-9409] Add FIDO 2 authentication to credential manager

---

app/src/main/java/com/x8bit/bitwarden/data/platform/manager/ciphermatching/CipherMatchingManagerImpl.kt
app/src/main/java/com/x8bit/bitwarden/data/platform/util/StringExtensions.kt
app/src/test/java/com/x8bit/bitwarden/data/platform/manager/ciphermatching/CipherMatchingManagerTest.kt

[PM-9135](https://bitwarden.atlassian.net/browse/PM-9135)
https://github.com/bitwarden/android/issues/3341
This PR adds back port matching to the Host matching logic, the main difference between this implementation and the original is that the port is now an optional property instead of a required property. …

PM-9135: Update host matching to include optional port value

---

app/src/main/java/com/x8bit/bitwarden/data/autofill/provider/AutofillCipherProviderImpl.kt
app/src/main/java/com/x8bit/bitwarden/data/platform/manager/ResourceCacheManager.kt
app/src/main/java/com/x8bit/bitwarden/data/platform/manager/ResourceCacheManagerImpl.kt
app/src/main/java/com/x8bit/bitwarden/data/platform/manager/ciphermatching/CipherMatchingManagerImpl.kt
app/src/main/java/com/x8bit/bitwarden/data/platform/manager/di/PlatformManagerModule.kt
app/src/main/java/com/x8bit/bitwarden/data/platform/util/StringExtensions.kt
app/src/main/java/com/x8bit/bitwarden/data/platform/util/URIExtensions.kt
app/src/test/java/com/x8bit/bitwarden/data/autofill/processor/AutofillCipherProviderTest.kt
app/src/test/java/com/x8bit/bitwarden/data/platform/manager/ResourceCacheManagerTest.kt
app/src/test/java/com/x8bit/bitwarden/data/platform/manager/ciphermatching/CipherMatchingManagerTest.kt
app/src/test/java/com/x8bit/bitwarden/data/util/StringExtensionsTest.kt
app/src/test/java/com/x8bit/bitwarden/data/util/UriExtensionsTest.kt

[PM-10140](https://bitwarden.atlassian.net/browse/PM-10140)
This PR addresses some issues we have seen with autofill on accounts with extremely large amounts of ciphers (3000+). The OS is timing out the autofill operation because we are taking [longer than 5 seconds](https://android.googlesource.com/platform/frameworks/base/+/master/services/autofill/java/com/android/server/autofill/RemoteFillService.java#328). To address this issue we have added some caching to the process of retrieving the suffix resources which is currently queried once for each cipher and can be a fairly expensive operation. In addition to this, we have also lowered our internal timeout for retrieving ciphers from 5 seconds to 2 seconds.
- All formatters and local linters executed and …

PM-10140: Add caching for large string resources to avoid delays and reduce timeout when retrieving ciphers

---

app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/model/Fido2GetCredentialsRequest.kt
app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/SpecialCircumstance.kt
app/src/main/java/com/x8bit/bitwarden/data/platform/manager/util/SpecialCircumstanceExtensions.kt
app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavScreen.kt
app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavViewModel.kt
app/src/test/java/com/x8bit/bitwarden/data/autofill/fido2/model/Fido2GetCredentialsRequestUtil.kt
app/src/test/java/com/x8bit/bitwarden/data/platform/manager/util/SpecialCircumstanceExtensionsTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavScreenTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavViewModelTest.kt

PM-9410
Define a SpecialCircumstance that represents a request to unlock the user's vault and retrieve any saved FIDO 2 credentials associated with the relying party that initiated the request.
issue and …

[PM-9410] Introduce FIDO 2 Get Credentials Request special circumstance

---

app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/sdk/VaultSdkSourceImpl.kt
app/src/test/java/com/x8bit/bitwarden/data/vault/datasource/sdk/VaultSdkSourceTest.kt

[PM-10140](https://bitwarden.atlassian.net/browse/PM-10140)
This PR makes a minor performance improvement to the `VaultSdkSource` when it loops through multiple items by ensuring that it only uses a single instance of the client. …

PM-10140: Update looping SDK calls to use single instance of client

---

app/src/main/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryImpl.kt

[PM-10140](https://bitwarden.atlassian.net/browse/PM-10140)
This PR updates the vault repository to no longer clear the data from the various `mutableStateFlows` when a user is first subscribing. This allows us to better utilize the cache data, which is especially useful in Autofill scenarios.
Note that the `mutableStateFlows` are still cleared when the the user changes or a lock event occurs.
- 📝 …

PM-10140: Allow for the vault data to have a pending state by default when data is already present

---

app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/disk/VaultDiskSourceImpl.kt
app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/sdk/VaultSdkSourceImpl.kt
app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/sdk/di/VaultSdkModule.kt
app/src/test/java/com/x8bit/bitwarden/data/vault/datasource/sdk/VaultSdkSourceTest.kt

PM-10140
This PR updates the `VaultSdkSource` and `VaultDiskSource` to parallelize the heavy loads when possible.
Currently we are doing this when decrypting ciphers or sends and when deserializing ciphers and sends. …

PM-10140: Update the VaultSdkSource and VaultDiskSource to use parallelization when processing heavier loads

---

app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarScreen.kt
app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarViewModel.kt
app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/model/VaultFilterType.kt
app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarScreenTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarViewModelTest.kt

[PM-8522](https://bitwarden.atlassian.net/browse/PM-8522)
The label of the tab bar for the vault tab should be "My vault" when the user doesn't have organizations and "Vaults" when they do.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/188a6030-5062-4b0b-bc61-7b4ac8211d65" /> | <img src="https://github.com/user-attachments/assets/cc8804d7-be83-4b58-b0b7-0b29f9d3ffec" /> | …

PM-8522: Vault tab bar title for organization users

---

app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/model/Fido2GetCredentialResult.kt
app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/processor/Fido2ProviderProcessorImpl.kt
app/src/main/java/com/x8bit/bitwarden/ui/autofill/fido2/manager/Fido2CompletionManager.kt
app/src/main/java/com/x8bit/bitwarden/ui/autofill/fido2/manager/Fido2CompletionManagerImpl.kt
app/src/main/java/com/x8bit/bitwarden/ui/autofill/fido2/manager/Fido2CompletionManagerUnsupportedApiImpl.kt
app/src/main/java/com/x8bit/bitwarden/ui/platform/composition/LocalManagerProvider.kt
app/src/test/java/com/x8bit/bitwarden/ui/autofill/fido2/manager/Fido2CompletionManagerTest.kt

PM-9410
Implement the completion process for FIDO 2 Get Credentials operation. This process packages any matching credentials into PublicKeyCredentialEntry objects and delivers them to the OS before finishing the activity. …

[PM-9410] Implement FIDO 2 Get Credentials completion

---

app/src/main/java/com/x8bit/bitwarden/ui/platform/components/row/BitwardenExternalLinkRow.kt
app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillScreen.kt
app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillViewModel.kt
app/src/main/java/com/x8bit/bitwarden/ui/platform/manager/intent/IntentManager.kt
app/src/main/java/com/x8bit/bitwarden/ui/platform/manager/intent/IntentManagerImpl.kt
app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillScreenTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillViewModelTest.kt

[PM-9406](https://bitwarden.atlassian.net/browse/PM-9406)
Add the manage passkey row to the autofill settings for Android 14+ devices.
<video width="400px" src="https://github.com/bitwarden/android/assets/125921730/9745f6cf-ba88-4383-a73e-c5b432fa663b" /> …

PM-9406: Add passkey management to autofill settings

---

app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/disk/AuthDiskSource.kt
app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/disk/AuthDiskSourceImpl.kt
app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepository.kt
app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
app/src/main/java/com/x8bit/bitwarden/data/vault/manager/VaultLockManagerImpl.kt
app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavScreen.kt
app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavViewModel.kt
app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarScreen.kt
app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarViewModel.kt
app/src/test/java/com/x8bit/bitwarden/data/auth/datasource/disk/AuthDiskSourceTest.kt
app/src/test/java/com/x8bit/bitwarden/data/auth/datasource/disk/util/FakeAuthDiskSource.kt
app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
app/src/test/java/com/x8bit/bitwarden/data/vault/manager/VaultLockManagerTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavViewModelTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarViewModelTest.kt

[PM-10379](https://bitwarden.atlassian.net/browse/PM-10379)
This PR enforces that the timeout action occurs as early as possible and not just when the app is foregrounded. This was causing a bug where the vault would be left unlocked after the user used the Autofill feature until either the background process was manually killed or the app was manually foregrounded.
This is a pretty big shift compared to the previous implementation since the app would store a `LastActiveTimeMillis` on disk and reference that value when foregrounding the app.
The new mechanism is based entirely on when the app is backgrounded, the user becoming inactive (change user), or on app startup. At those times we either enforce the timeout or set a timer for when the timeout should be enforced.
This …

PM-10379: Update the timeout action logic to occur immediately after requirements are met

---

app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/model/PasskeyAssertionOptions.kt
app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/model/PasskeyAttestationOptions.kt
app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt
app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/util/PasskeyAssertionOptionsTestHelpers.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/util/PasskeyAttestationOptionsTestHelpers.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt

PM-10428
Per the WebAuthn spec, when an unknown user verification requirement value is encountered the value is ignored and defaults to `PREFERRED`.
- 🎨 …

[PM-10428] Default UserVerificationRequirement to PREFERRED

---

gradle.properties

PM-10441
This change allocates more resources and enables parallel GC to avoid out of memory exceptions during workflow exectuion. …

[PM-10441] Fix memory exception during CI builds

---

app/src/main/java/com/x8bit/bitwarden/MainViewModel.kt

[PM-10528](https://bitwarden.atlassian.net/browse/PM-10528)
This PR fixes a bug in which switching from a user with a lock type of "immediate" to an unlocked account from the Vault screen doesn't actually update the Vault screen. The issue is that the fallback logic we have in place for restarting `MainActivity` whenever a vault locking event occurs (in order to clear out all vault data from memory) is happening too soon and this is interfering with the logic that destroys the current `VaultScreen`/`VaultViewModel` and creates a new set. This is a very similar reason why we added a delay of 500 milliseconds before restarting `MainActivity` whenever a user switch event occurs. This PR just adds the same delay for the locking events. This does not seem to have any visual downsides as far as …

PM-10528: Fix user switching issue due to rapid Activity recreation when locking

---

app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/manager/Fido2CredentialManagerImpl.kt
app/src/test/java/com/x8bit/bitwarden/data/autofill/fido2/manager/Fido2CredentialManagerTest.kt
app/src/test/java/com/x8bit/bitwarden/data/vault/datasource/sdk/model/PublicKeyAuthenticatorAssertionResponseUtil.kt

PM-10373
This pull request fixes incorrect arguments passed to Bitwarden SDK when handling passkey registration and authentication requests from unprivileged applications.
When registering a passkey from an unprivileged application, Bitwarden SDK expects `ClientData.DefaultWithExtraData.androidPackageName` to be the calling application package name. However, during authentication `ClientData.DefaultWithExtraData.androidPackageName` is the apk-key-hash.
Bitwarden SDK requires `origin` to be a valid HTTP URL, including the protocol preamble, when performing registration and authentication.
- Used internationalization (i18n) for all UI …

[PM-10373] Fix FIDO 2 credential creation from unprivileged apps

---

app/src/debug/AndroidManifest.xml
app/src/main/AndroidManifest.xml

PM-10556
Move FIDO 2 intent filter to the primary manifest. …

[PM-10556] Move FIDO 2 intent filter to main manifest

---

app/src/main/java/com/x8bit/bitwarden/ui/platform/components/scaffold/BitwardenScaffold.kt

https://bitwarden.atlassian.net/browse/PM-10645
Add padding for navigation bars to FAB in the bitwarden scaffold
| ![10645before](https://github.com/user-attachments/assets/9e2bde24-29f1-4b1c-973e-590d99b8633a) | ![10645after](https://github.com/user-attachments/assets/fb206f3d-699b-4f8e-9e87-03e606bcaffa) | 
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes …

[PM-10645] add nav bar padding in bw scaffold for FAB

---

app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingScreen.kt
app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/util/VaultItemListingDataExtensions.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/util/VaultItemListingDataExtensionsTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/util/VaultItemListingDataUtil.kt

https://bitwarden.atlassian.net/browse/PM-10066
If a user if authenticated w/o a MP as they would be in the instance of SSO via TDE flow, and there is a vault item that has a masterpassword, we should not prompt the user for adding one when they go through the autofill flow. …

PM-10066 don't prompt for MP if the user does not have one

---

app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/network/core/ResultCall.kt

N/A
This PR updates the `ResultCall` class to allow for 204 responses that are nullable classes instead of `Unit`.
Ideally we could determine if the `successType` is a nullable value and allow null based on that but unfortunately the information is not available to us. …

Allow null network responses for 204s

---

app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt

PM-10644
Re-prompt for master password entry when authenticating a protected passkey.
[protected-passkey-mp-reprompt.webm](https://github.com/user-attachments/assets/2b177add-7adb-4a16-a73c-fa3b2552061a) …

[PM-10644] Re-prompt master password for protected passkeys

---

app/src/main/java/com/x8bit/bitwarden/data/auth/manager/UserLogoutManager.kt
app/src/main/java/com/x8bit/bitwarden/data/auth/manager/UserLogoutManagerImpl.kt
app/src/main/java/com/x8bit/bitwarden/data/auth/manager/model/LogoutEvent.kt
app/src/main/java/com/x8bit/bitwarden/data/auth/manager/model/LogoutResult.kt
app/src/main/java/com/x8bit/bitwarden/data/vault/manager/VaultLockManagerImpl.kt
app/src/test/java/com/x8bit/bitwarden/data/vault/manager/VaultLockManagerTest.kt

https://bitwarden.atlassian.net/browse/PM-10058
If a user, using SSO TDE  logouts out and attempts to log back in during an active app session (app has not been destroyed) they will get stuck in a state where they are unable to fully authenticate with Admin approval or other device. 
The root cause found was in debugging
```
val updatedRootNavState = when {
userState?.activeAccount?.trustedDevice?.isDeviceTrusted == false &&
!userState.activeAccount.isVaultUnlocked &&
!userState.activeAccount.hasManualUnlockMechanism -> RootNavState.TrustedDevice
```
once the vault was unlocked for the user if it was never set to locked and they logged it, it would always return true.
- Written new unit and / or …

[PM-10058] Non-remembered device TDE issue in same session

---

app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
app/src/main/java/com/x8bit/bitwarden/data/auth/repository/model/LoginResultExtensions.kt
app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/sdk/VaultSdkSourceImpl.kt
app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/sdk/model/InitializeCryptoResult.kt
app/src/main/java/com/x8bit/bitwarden/data/vault/repository/model/VaultUnlockResult.kt
app/src/main/java/com/x8bit/bitwarden/data/vault/repository/util/VaultUnlockResultExtensions.kt
app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/trusteddevice/TrustedDeviceScreen.kt
app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockViewModel.kt
app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
app/src/test/java/com/x8bit/bitwarden/data/auth/repository/model/LoginResultExtensionsTest.kt
app/src/test/java/com/x8bit/bitwarden/data/vault/datasource/sdk/VaultSdkSourceTest.kt
app/src/test/java/com/x8bit/bitwarden/data/vault/manager/VaultLockManagerTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockViewModelTest.kt

[PM-9532](https://bitwarden.atlassian.net/browse/PM-9532)
If a user is able to authenticate successfully with the server but there is an issue in the SDK when unlocking the vault (or related SDK operation like initializing crypto) they will be in a sort of limbo state where they will immediately be take to the unlock screen but unable to proceed. To prevent this and match iOS behavior we want to propagate any error from the SDK that occurs in the vault unlock process to the `LoginResult` and prevent a "successful" login, if they are unable to access the vault due to the issue stated above. 
The repro step which originally highlighted this issue has been fixed in the SDK according to the info on the ticket. To recreate you can force the result of `VaultSdkSourceImpl.initializeCrypto` to …

PM-9532: pt2. separate vault unlock logic and fail out on error during login.

---

app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/login/LoginScreen.kt

[PM-10122](https://bitwarden.atlassian.net/browse/PM-10122)
Auto focus on the PIN or password entry fields when unlocking the vault or logging in.
Logging in:
| --- | --- |
| <video src="https://github.com/user-attachments/assets/84207a9a-350c-4fd6-b73d-fe30ab0b8d9d" /> | <video src="https://github.com/user-attachments/assets/c0fc252a-e33a-4aad-9950-5a3ca87563a0" /> |
Unlocking the vault:
| --- | --- |
| <video src="https://github.com/user-attachments/assets/dab78f9a-4a64-4871-bd21-e1f502bc6e01" /> | <video src="https://github.com/user-attachments/assets/3b398fe2-fb9b-446d-a302-e45ee626cb71" /> |
- …

PM-10122: Autofocus on PIN or password field

---

app/src/main/java/com/x8bit/bitwarden/data/platform/manager/FeatureFlagManager.kt
app/src/main/java/com/x8bit/bitwarden/data/platform/manager/FeatureFlagManagerImpl.kt
app/src/test/java/com/x8bit/bitwarden/data/platform/manager/FeatureFlagManagerTest.kt

N/A
This PR adds a function for getting a feature flag synchronously using the cache. …

Add option to retrieve feature flag synchronously

---

app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockScreen.kt
app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockViewModel.kt
app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockScreenTest.kt

[issues/3383](https://github.com/bitwarden/android/issues/3383)
Request autofocus on input field to show keyboard on Unlock Vault screen if biometric unlock is disabled or unavailable.
Also extent input field to support keyboard actions and and bind Unlick action to keyboard Done event too.
Add tests to cover cases with empty PIN\Password and ingnore Unlock action  and focus related tests too.
- 📝 …

[PM-10024] Force focus on Master Password or Pin input field.

---

app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
app/src/main/java/com/x8bit/bitwarden/data/vault/repository/VaultRepository.kt
app/src/main/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryImpl.kt
app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
app/src/test/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt

N/A
This PR cleans up the logic around unlocking the vault from the `AuthRepository` placing everything into a single helper method. …

Consolidate unlock vault functionality for auth into a single helper method

---

app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/di/PreferenceModule.kt
app/src/main/res/xml/backup_rules.xml
app/src/main/res/xml/data_extraction_rules.xml

[BIT-2437](https://livefront.atlassian.net/browse/BIT-2437)
This PR attempt to mitigate a crash that occurs when trying to instantiate encrypted shared preferences.
This problem cannot be reproduced easily but has been tracked [here](https://issuetracker.google.com/issues/176215143).
The logic in this PR _mitigates_ the issue but does not _solve_ it. …

BIT-2437: Add mitigation logic for bad encryption key

---

app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt

PM-10670
Prompt for PIN creation when performing FIDO 2 user verification if the user is using TDE, does not have a master password, and has not previously setup a PIN.  
How does this change fix the issue?
During FIDO 2 user verification flows, we only need to know if a PIN has been setup. We don't technically care what the vault unlock method is because we're performing user verification, not unlocking the vault.
[passkey-uv-pin-setup.webm](https://github.com/user-attachments/assets/1f0f4f99-9a38-4777-b223-5a2211c9df67) …

[PM-10670] Prompt for PIN creation during passkey user verification

---

app/src/main/java/com/x8bit/bitwarden/ui/platform/components/toggle/BitwardenUnlockWithBiometricsSwitch.kt
app/src/main/java/com/x8bit/bitwarden/ui/platform/components/toggle/BitwardenUnlockWithPinSwitch.kt
app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityScreen.kt
app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityViewModel.kt
app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityScreenTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityViewModelTest.kt

[PM-10621](https://bitwarden.atlassian.net/browse/PM-10621) Part 1
This PR extracts the biometrics and pin switches from the `AccountSecurityScreen` in order to make reusable components out of them. These new components will get additional use in a future PR. …

PM-10621: Create common biometrics and pin unlock UI elements

---

app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/welcome/WelcomeScreen.kt
app/src/main/java/com/x8bit/bitwarden/ui/platform/util/ConfigurationExtensions.kt
app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/qrcodescan/QrCodeScanScreen.kt

[PM-10729](https://bitwarden.atlassian.net/browse/PM-10729)
This PR adds a helper method for determining if the app is in portrait orientation. This function defaults to portrait mode when the orientation is unknown. …

PM-10729: Add a helper method for determining if the app is in portrait orientation

---

app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/welcome/WelcomeViewModel.kt

N/A
This PR addresses a minor warning on the `WelcomeCard` parcelable. …

Fix a minor parcelable warning

---

app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendViewModel.kt

[PM-10725](https://bitwarden.atlassian.net/browse/PM-10725)
This PR updates the `AddSendEvent.ShowShareSheet` to allow it to be consumed in the background (when the screen is paused). This allows us to display the share sheet as the UI is being dismissed.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/f94e0fe3-a63e-4d9f-8ace-9d994da74a58" width="300" /> | <video src="https://github.com/user-attachments/assets/4ee9589f-8657-41f3-8dcb-a4262a7a2d10" width="300" /> |
- Updated …

Allow the ShowShareSheet event to be launched after the screen is paused

---

app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupUnlockViewModel.kt
app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupUnlockViewModelTest.kt

[PM-10628](https://bitwarden.atlassian.net/browse/PM-10628)
This PR adds pin unlock logic to the `SetupUnlockViewModel`. …

PM-10628: Add pin unlock to SetupUnlockViewModel

---

app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenTextField.kt
app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/PinInputDialog.kt
app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityScreenTest.kt

PM-10697
Auto-focus on the PIN field within the PIN dialog.
| <video src="https://github.com/user-attachments/assets/196e1b7b-0968-4ee6-975f-cdf36933160b" />  | <video src="https://github.com/user-attachments/assets/1cf2a33a-a19e-44b1-919f-6746cb401e99" />| 
- 🤔 …

[PM-10697] Auto-focus on PIN Dialog field

---

app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockScreen.kt

PM-10696
Dismiss the vault unlock keyboard when a tap gesture occurs outside of the input field.
Coming soon! …

[PM-10696] Dismiss vault unlock keyboard

---

app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarViewModel.kt
app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarViewModelTest.kt

[PM-8522](https://bitwarden.atlassian.net/browse/PM-8522)
Fix the nav bar vault title of an account just logging in with organizations.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/9a0992b7-a4ad-4e7c-add9-3bd0ea69bbcb" /> | <video src="https://github.com/user-attachments/assets/02fdccee-6157-4d5b-9ca4-c1eb78c02bc8" /> | …

PM-8522: Fix vault tab nav bar title when logging in

---

app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/auth/AuthNavigation.kt
app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/masterpasswordgenerator/MasterPasswordGeneratorNavigation.kt
app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/masterpasswordgenerator/MasterPasswordGeneratorScreen.kt
app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/masterpasswordgenerator/MasterPasswordGeneratorViewModel.kt
app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/util/PolicyInformationMasterPasswordExtensions.kt
app/src/main/res/values/strings.xml
app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/masterpasswordgenerator/MasterPasswordGeneratorScreenTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/masterpasswordgenerator/MasterPasswordGeneratorViewModelTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/generator/util/PolicyInformationMasterPasswordExtensionsTest.kt

https://bitwarden.atlassian.net/browse/PM-10619
Screen for onboarding flow allowing users to generate a passphrase to use as their master password.
**Forced the navigation to screen on opening the `LogInScreen`**
https://github.com/user-attachments/assets/5fcb0348-17d1-48dd-8402-b93008897cd8
- 🤔 …

PM-10619 screen to generate master password

---

app/src/main/java/com/x8bit/bitwarden/data/platform/util/IntentExtensions.kt

[PM-10878](https://bitwarden.atlassian.net/browse/PM-10878)
This PR addresses a crash caused by a bug in Android 13, using the `IntentCompat` and `BundleCompat` methods resolve this crash for us.
issue …

PM-10878: Access parcelable data in a safe manor across SDK versions

---

app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginScreen.kt
app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginViewModel.kt
app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginViewModelTest.kt

PM-10664
Display server error message during 2FA login.
Coming soon! …

[PM-10664] Display server error message during 2FA login

---

app/src/main/java/com/x8bit/bitwarden/ui/platform/components/appbar/BitwardenTopAppBar.kt

https://bitwarden.atlassian.net/browse/PM-10851
The goal is to make it so the title drops to the second row (MediumTopAppBar layout) in the event it overflows the title space.
**juiced the navigation to go the screen where we have a longer title**
https://github.com/user-attachments/assets/05a9f85c-7d10-469d-8bb1-bc257af6840e
- ❓ …

PM-10851 make the default top app bar reactive 

---

app/src/main/java/com/x8bit/bitwarden/data/platform/manager/FeatureFlagManagerImpl.kt
app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/FlagKey.kt
app/src/test/java/com/x8bit/bitwarden/data/platform/manager/FeatureFlagManagerTest.kt
app/src/test/java/com/x8bit/bitwarden/data/platform/repository/util/FakeServerConfigRepository.kt

[PM-10894](https://bitwarden.atlassian.net/browse/PM-10894)
Add logic to allow feature flags to ignore the network configured value. …

PM-10894: Add flag for disabling remote feature flag configuration

---

app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/disk/AuthDiskSource.kt
app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/disk/AuthDiskSourceImpl.kt
app/src/main/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryImpl.kt
app/src/test/java/com/x8bit/bitwarden/data/auth/datasource/disk/AuthDiskSourceTest.kt
app/src/test/java/com/x8bit/bitwarden/data/auth/datasource/disk/util/FakeAuthDiskSource.kt
app/src/test/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt

[PM-10909](https://bitwarden.atlassian.net/browse/PM-10909)
This PR adds the persistance layer for the `usersKeyConnector` boolean that is received from the sync API. …

PM-10909: Add persistance layer for usersKeyConnector

---

app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/disk/AuthDiskSource.kt
app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/disk/AuthDiskSourceImpl.kt
app/src/main/java/com/x8bit/bitwarden/data/auth/manager/TrustedDeviceManagerImpl.kt
app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/BaseDiskSource.kt
app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/PushDiskSourceImpl.kt
app/src/test/java/com/x8bit/bitwarden/data/auth/datasource/disk/AuthDiskSourceTest.kt

N/A
This PR updates the way data is stored in the various DiskSources by forcing them to be nullable (null meaning not present).
This change only affects one boolean and makes the disk source more consistent. …

All booleans stored are nullable for consistency

---

app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/api/AuthenticatedAccountsApi.kt
app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/model/KeyConnectorKeyRequestJson.kt
app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/service/AccountsService.kt
app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/service/AccountsServiceImpl.kt
app/src/test/java/com/x8bit/bitwarden/data/auth/datasource/network/service/AccountsServiceTest.kt

[PM-10936](https://bitwarden.atlassian.net/browse/PM-10936)
This PR adds two new APIs using the account domain that will be used to support key connectors. …

PM-10936: Add account apis for key connectors

---

app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/di/AuthNetworkModule.kt
app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/datasource/network/di/Fido2NetworkModule.kt
app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/network/retrofit/Retrofits.kt
app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/network/retrofit/RetrofitsImpl.kt
app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/di/VaultNetworkModule.kt
app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/network/retrofit/RetrofitsTest.kt

N/A
This PR updates the way we manage instances of Retrofit with static base urls. This is just a small bit of clean up that will be nice as I add another static retrofit instance for Key Connectors. …

Add helper function for static retrofit instances

---

app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/api/AuthenticatedOrganizationApi.kt
app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/service/OrganizationService.kt
app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/service/OrganizationServiceImpl.kt
app/src/test/java/com/x8bit/bitwarden/data/auth/datasource/network/service/OrganizationServiceTest.kt

[PM-10956](https://bitwarden.atlassian.net/browse/PM-10956)
This PR adds support for the leave organization network API that will be used for key connectors. …

PM-10956: Add support for leave organization API

---

app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockViewModel.kt
app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockViewModelTest.kt

[PM-10874](https://bitwarden.atlassian.net/browse/PM-10874)
Fix an additional bug to automatically prompt the user for biometrics if they switch to an account that has it enabled.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/f3f0feab-315b-48b5-abda-c02a0873517e" /> | <video src="https://github.com/user-attachments/assets/4bd36f81-a9f4-432c-8b7c-db77aefef7a6" /> | …

PM-10874: Prompt for biometrics after switching accounts

---

app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/model/RegisterResponseJson.kt
app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/model/SendVerificationEmailResponseJson.kt
app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/service/IdentityServiceImpl.kt
app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
app/src/test/java/com/x8bit/bitwarden/data/auth/datasource/network/service/IdentityServiceTest.kt
app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt

N/A
This PR addresses a testing inconsistency with our network APIs.
The `Json` instance used in some tests did not match the instance used in production code. Once I addressed this, certain tests began to fail because production code does not require `explicitNulls`. This means that the `Error` case of many network responses will never be used, so I have removed those. …

Simplify error responses

---

app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/di/Fido2ProviderModule.kt
app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/processor/Fido2ProviderProcessorImpl.kt
app/src/test/java/com/x8bit/bitwarden/data/autofill/fido2/processor/Fido2ProviderProcessorTest.kt

https://bitwarden.atlassian.net/browse/PM-10753
When creating a passkey, the last active account should be the initial default option.
| <video src="https://github.com/user-attachments/assets/86c7801c-5e2b-4cc8-9007-a9d571a85aa6" /> | <video src="https://github.com/user-attachments/assets/588e92b0-1138-4db7-9596-6ca5c048d040" /> | …

[PM-10282] Default to last active account for passkey creation

---

app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/model/GetTokenResponseJson.kt
app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/model/KeyConnectorMasterKeyResponseJson.kt
app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/service/AccountsServiceImpl.kt
app/src/test/java/com/x8bit/bitwarden/data/auth/datasource/network/service/AccountsServiceTest.kt
app/src/test/java/com/x8bit/bitwarden/data/auth/datasource/network/service/IdentityServiceTest.kt
app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
app/src/test/java/com/x8bit/bitwarden/data/auth/repository/util/GetTokenResponseExtensionsTest.kt

[PM-10954](https://bitwarden.atlassian.net/browse/PM-10954)
This PR updates the key-connector APIs with a few minor changes:
* custom url APIs have the `/user-keys` appended to them.
* The sync API includes the `KeyConnectorUrl` property.
* The `KeyConnectorMasterKeyResponseJson` uses a lowercase `k` in the variable name.
- ❓ …

PM-10954: Update the key connector APIs to use the correct url and responses

---

app/src/main/java/com/x8bit/bitwarden/data/auth/repository/model/Organization.kt
app/src/main/java/com/x8bit/bitwarden/data/auth/repository/util/SyncResponseJsonExtensions.kt
app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/model/SyncResponseJson.kt
app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/removepassword/RemovePasswordNavigation.kt
app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/removepassword/RemovePasswordScreen.kt
app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/removepassword/RemovePasswordViewModel.kt
app/src/main/res/values/strings.xml
app/src/test/java/com/x8bit/bitwarden/data/auth/repository/util/AuthDiskSourceExtensionsTest.kt
app/src/test/java/com/x8bit/bitwarden/data/auth/repository/util/SyncResponseJsonExtensionsTest.kt
app/src/test/java/com/x8bit/bitwarden/data/auth/repository/util/UserStateJsonExtensionsTest.kt
app/src/test/java/com/x8bit/bitwarden/data/vault/datasource/network/model/SyncResponseProfileUtil.kt
app/src/test/java/com/x8bit/bitwarden/data/vault/datasource/network/service/SyncServiceTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/removepassword/RemovePasswordScreenTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/removepassword/RemovePasswordViewModelTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/util/CipherViewExtensionsTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/movetoorganization/VaultMoveToOrganizationViewModelTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/movetoorganization/util/VaultMoveToOrganizationExtensionsTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModelTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/vault/util/UserStateExtensionsTest.kt

[PM-11154](https://bitwarden.atlassian.net/browse/PM-11154)
[PM-11196](https://bitwarden.atlassian.net/browse/PM-11196)
This PR adds the basic UI for the Remove Password screen. …

PM-11154: Create basic Remove Master Password UI

---

app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/api/AuthenticatedAccountsApi.kt
app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/api/AuthenticatedKeyConnectorApi.kt
app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/api/UnauthenticatedAccountsApi.kt
app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/api/UnauthenticatedKeyConnectorApi.kt
app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/di/AuthNetworkModule.kt
app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/service/AccountsService.kt
app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/service/AccountsServiceImpl.kt
app/src/main/java/com/x8bit/bitwarden/data/auth/manager/KeyConnectorManager.kt
app/src/main/java/com/x8bit/bitwarden/data/auth/manager/KeyConnectorManagerImpl.kt
app/src/main/java/com/x8bit/bitwarden/data/auth/manager/di/AuthManagerModule.kt
app/src/test/java/com/x8bit/bitwarden/data/auth/datasource/network/service/AccountsServiceTest.kt
app/src/test/java/com/x8bit/bitwarden/data/auth/manager/KeyConnectorManagerTest.kt

[PM-11226](https://bitwarden.atlassian.net/browse/PM-11226)
This PR updates multiple key connector APIs to function with or without the access token based on where they will be needed. These APIs are then wrapped by the `KeyConnectorManager` which manages more of the complex data flows.
- 🤔 …

PM-11226: Wrap Key Connector APIs

---

app/src/test/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt

N/A
This PR fixes an `IllegalArgumentException` that occurs when running a `VaultRepository` test caused by trying to mock a `Result`. Looks like the `turbineScope` was eating the exception allowing the test to pass.
The Warning:
```
WARNING: Failed to transform class kotlin/Result
java.lang.IllegalArgumentException: Cannot resolve T from private static final ? kotlin.Result.getOrNull-impl(?)
```
- 📝 …

Fix IllegalArgumentException in test

---

app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepository.kt
app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
app/src/main/java/com/x8bit/bitwarden/data/auth/repository/di/AuthRepositoryModule.kt
app/src/main/java/com/x8bit/bitwarden/data/auth/repository/model/RemovePasswordResult.kt
app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/removepassword/RemovePasswordScreen.kt
app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/removepassword/RemovePasswordViewModel.kt
app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/removepassword/RemovePasswordScreenTest.kt
app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/removepassword/RemovePasswordViewModelTest.kt

[PM-11155](https://bitwarden.atlassian.net/browse/PM-11155)
This PR adds the Logic for processing a request to remove a users password.
- 🎨 (`:art:`) …

PM-11155: Add logic for handling remove password flow
