bitwarden/android

src/Android/Services/GoogleAnalyticsService.cs, src/App/Abstractions/Services/IGoogleAnalyticsService.cs, src/App/App.cs, src/App/Constants.cs, src/App/Pages/Settings/SettingsPage.cs, src/App/Resources/AppResources.Designer.cs, src/App/Resources/AppResources.resx, src/iOS.Core/Services/GoogleAnalyticsService.cs
=> Fixes #8 Disable Google Analytics

src/App/Resources/AppResources.sv.resx
Additional translated strings for search, auto-fill and organisations.
=> Additional swedish strings

src/App/Controls/ExtendedButton.cs, src/App/Controls/PinControl.cs, src/App/Controls/StepperCell.cs, src/App/Pages/Lock/LockPasswordPage.cs, src/App/Pages/LoginTwoFactorPage.cs, src/App/Pages/PasswordHintPage.cs, src/App/Pages/RegisterPage.cs, src/App/Pages/Settings/SettingsCreditsPage.cs, src/App/Pages/Settings/SettingsPage.cs, src/App/Pages/Tools/ToolsPasswordGeneratorPage.cs, src/App/Pages/Vault/VaultAddCipherPage.cs, src/App/Pages/Vault/VaultCustomFieldsPage.cs, src/App/Pages/Vault/VaultEditCipherPage.cs, src/App/Pages/Vault/VaultViewCipherPage.cs
=> App: Use Windows helper instead of WinPhone

src/UWP/App.xaml.cs
=> UWP: Enable Collection Services

README.md
Same as all other ones just with two images:
This makes the image fetch from https://github.com/bitwarden/brand instead of using imgur, this means that you just need to update the screenshot there and this updates automatically.
=> fetch image from bitwarden/brand

src/App/Models/Page/PasswordGeneratorPageModel.cs, src/App/Models/Page/VaultViewCipherPageModel.cs, src/App/Pages/Tools/ToolsPasswordGeneratorPage.cs, src/App/Pages/Vault/VaultViewCipherPage.cs, src/App/Utilities/PasswordFormatter.cs
Same pattern as the jslib/desktop implementation.
Since I didn't see any theming (so far), I just used "default" colors.
=> Colorized passwords

src/Android/Accessibility/AccessibilityHelpers.cs, src/Android/Autofill/AutofillHelpers.cs, src/Android/Resources/xml/autofillservice.xml
Mozilla is now releasing new nightly versions of fenix with a new package name here https://tools.taskcluster.net/index/project.mobile.fenix.v2.nightly
=> add support for org.mozilla.fenix.nightly

src/Android/Accessibility/AccessibilityHelpers.cs
Added SupportedBrowsers  entries to support Sleipnir Mobile Browser.
=> Added support for Sleipnir Mobile.

src/Core/Models/View/CardView.cs
Issue is fixed No 361
Now tested on android device extra comma is not appended anymore
Screenshot attached
=> Updated Incorrect Check Condition

src/Android/Accessibility/AccessibilityHelpers.cs, src/Android/Accessibility/AccessibilityService.cs, src/Android/Resources/xml/accessibilityservice.xml
Fixes to accessibility overlay anchor view tracking and node tree parsing.  Restricted calls to 'RootInActiveWindow' until absolutely necessary as it can be expensive (this was the culprit behind chromium based browser performance with view tracking).
=> Accessibility fixes

src/Android/Accessibility/AccessibilityHelpers.cs, src/Android/Accessibility/AccessibilityService.cs, src/Android/Accessibility/NodeList.cs
Made node recycling approach a bit more surgical to appease older versions of Android, and adjusted anchor position offset for older versions of Android
=> Fixes for older versions of Android

src/Android/Accessibility/AccessibilityHelpers.cs
Support for multiple browser UriViewIds when extracting a uri
=> Support for multiple browser UriViewIds when extracting a uri

src/Android/Accessibility/AccessibilityHelpers.cs, src/Android/Accessibility/AccessibilityService.cs
Align accessibility overlay to bottom or top of anchor view depending on available space (bottom by default on initial focus).  This prevents blocking system prompts when long-pressing EditTexts (copy, paste, etc.). Also establishing visible app height now works much better on Android 5.0+.
=> Accessibility Overlay Enhancements

src/Android/Android.csproj, src/Android/MainActivity.cs, src/Android/Properties/AndroidManifest.xml, src/Android/Receivers/RestrictionsChangedReceiver.cs, src/Android/Resources/Resource.designer.cs, src/Android/Resources/values/strings.xml, src/Android/Resources/xml/app_restrictions.xml, src/Android/Utilities/AndroidHelpers.cs, src/App/Utilities/AppHelpers.cs, src/iOS.Core/Utilities/iOSCoreHelpers.cs, src/iOS/AppDelegate.cs
Support setting environment base URL for AppConfig EMM provider. See https://www.appconfig.org/www/appconfig-content/uploads/2015/08/ImplementingAppConfigwithXamarin.pdf
=> support for appconfig settings

src/Android/Accessibility/AccessibilityService.cs
Check the blacklist before showing the overlay. resolves issues like #728
=> Check blacklist before showing overlay

src/Core/Abstractions/IPolicyService.cs, src/Core/Enums/PolicyType.cs, src/Core/Models/Data/PolicyData.cs, src/Core/Models/Domain/Policy.cs, src/Core/Models/Response/PolicyResponse.cs, src/Core/Models/Response/SyncResponse.cs, src/Core/Services/PolicyService.cs, src/Core/Services/SyncService.cs, src/Core/Utilities/ServiceContainer.cs
Added models & service layer to support policies
=> Beginning of policy support

src/App/Pages/Generator/GeneratorPage.xaml, src/App/Pages/Generator/GeneratorPageViewModel.cs, src/App/Resources/AppResources.Designer.cs, src/App/Resources/AppResources.resx, src/Core/Abstractions/IPasswordGenerationService.cs, src/Core/Models/Domain/PasswordGeneratorPolicyOptions.cs, src/Core/Services/PasswordGenerationService.cs, src/Core/Utilities/ServiceContainer.cs, src/iOS.Core/Controllers/PasswordGeneratorViewController.cs
Enforcement of password generator policies.  Handling of UI widgets on generator screen could use some polish but I'd like a review for this so far.  (I don't see a way to comment on a review request, just a PR)
=> Password generator policy enforcement

src/App/Pages/Generator/GeneratorPage.xaml, src/App/Pages/Generator/GeneratorPageViewModel.cs
Change switch binding back to using EnforcedPolicyOptions directly
=> Change switch binding back to using EnforcedPolicyOptions directly

src/Core/Services/PolicyService.cs
Added null check for loading non-existent policies
=> Added null check for loading non-existent policies

src/App/Pages/Settings/ExportVaultPageViewModel.cs, src/Core/Core.csproj
- Added handled exception tracking for vault export (unable to reproduce failed CSV export on iOS)
- Bumped CsvHelper to latest
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1169444489336079/1169599833491800) by [Unito](https://www.unito.io/learn-more)
=> Added handled exception tracking for vault export and bumped CsvHelper to latest

src/Android/Accessibility/AccessibilityHelpers.cs
We're no longer parsing for total app vs non-app window dimensions as it apparently can't be trusted across ROMs (Repro'd a condition on a non-Pixel phone where a 4th "mystery" system window would appear and disappear (logically, not visibly) at regular intervals while sitting on a login page, throwing off the measurements and causing the overlay to fly off-screen (i.e. disappear shortly after appearing)
We're now explicitly checking for a single InputMethod window for measuring software keyboards, and ignoring the rest.  This seems to have stabilized the overlay behavior, though it really needs more testing (Need more examples of websites with issues, not just browsers)
Also made improvements to measurements used when automatically flipping from bottom to top-aligned overlay, which helps …
=> Tweaks to accessibility autofill overlay

src/Android/Android.csproj, src/App/App.csproj, src/iOS/iOS.csproj, store/google/Publisher/Publisher.csproj
Updated dependencies (thanks to Xamarin team for fixing the transitive issue with Forms .495)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1169444489336079/1169867809469152) by [Unito](https://www.unito.io/learn-more)
=> Updated dependencies

src/App/Pages/Vault/AutofillCiphersPage.xaml.cs
Remove unnecessary info message when clicking search during the autofill flow. Fixes #807
=> Remove Unnecessary Toast Message

src/Android/Autofill/AutofillService.cs, src/Android/Receivers/LockAlarmReceiver.cs, src/App/App.xaml.cs, src/App/Pages/Accounts/LockPageViewModel.cs, src/App/Pages/Settings/SettingsPage/SettingsPageViewModel.cs, src/App/Pages/Vault/GroupingsPage/GroupingsPage.xaml.cs, src/App/Pages/Vault/GroupingsPage/GroupingsPageViewModel.cs, src/Core/Abstractions/IVaultTimeoutService.cs, src/Core/Services/AuthService.cs, src/Core/Services/VaultTimeoutService.cs, src/Core/Utilities/ServiceContainer.cs, src/iOS.Autofill/CredentialProviderViewController.cs, src/iOS.Core/Controllers/LockPasswordViewController.cs, src/iOS.Core/Utilities/ASHelpers.cs, src/iOS.Extension/LoadingViewController.cs, src/iOS/AppDelegate.cs
> Begin name refactor of `LockService` to `VaultTimeoutService`. No logic changes are present.
- Variable name refactor from `lockService` to `vaultTimeoutService`. 
- Updated interface reference from `ILockService` to `IVaultTimeoutService`.
- Updated service calls to use name refactor.
=> [Auto-Logout] Lock Service name refactor

src/Android/MainActivity.cs, src/App/App.xaml.cs, src/iOS/AppDelegate.cs
> Change existing `lockOption` variables, method names, and message commands to use the `...vaultTimeout...` pattern.
- **MainActivity.cs**: Updated intent variable name, command message conditional, and local variable names
- **App.xaml.cs**: Updated method name, command message sent, and updated logic within timeout method to properly lock/log out when necessary
- **AppDelegate.cs**: Updated variable names, command messages received, updated method names and local variable names.
=> [Auto-Logout] LockOption refactor - application layer (part 1)

src/Android/Accessibility/AccessibilityHelpers.cs, src/Android/Autofill/AutofillHelpers.cs, src/Android/Resources/xml/autofillservice.xml
This adds compatibility for Brave Beta browser (https://play.google.com/store/apps/details?id=com.brave.browser_beta).
=> Add support for Brave Beta browser

appveyor.yml
Restrict publishing Google Play artifacts to builds from master branch
=> Only publish to Google Play if master branch

src/Android/Accessibility/AccessibilityHelpers.cs
It looks like there are a few bugs across a few versions of Android where the right conditions would return `false` when querying `Settings.CanDrawOverlays(..)`.  In addition to that we're now querying the `AppOpsManager` for a state that describes our `system_alert_window` access (the `Ignored` state is apparently based on timing and means we actually _can_ draw, but `CanDrawOverlay` still returned `false` in this case.  Finally if both of those conditions are still `false` we attempt to just draw an invisible overlay and catch the failure as proof that we actually don't have the permission, which will then show the toast.  (Thankfully this whole thing only happens on the initial focus of a view that we've already established requires an overlay)
=> Added additional smarts for establishing permission to draw over other apps

src/App/Resources/AppResources.resx
- **AppResources.cs**: Fixed `OneMinute` dupe string resource.
=> [Auto-Logout] Bug: Fixed dupe string resource

src/Android/Accessibility/AccessibilityHelpers.cs, src/Core/Utilities/CoreHelpers.cs
Changed URI detection to utilize framework.  This fixes parsing failures on some (possibly a lot of) urls.
=> Fixes to uri parsing

src/Android/Accessibility/AccessibilityHelpers.cs, src/Core/Utilities/CoreHelpers.cs
Additional uri parsing intelligence to sync with updated jslib logic
=> Additional uri parsing intelligence

src/Android/Accessibility/AccessibilityHelpers.cs, src/Android/Autofill/AutofillHelpers.cs, src/Android/Resources/xml/autofillservice.xml
This adds some clarifications to the browser lists.
=> [Browser lists] Global clarification

src/Android/Accessibility/AccessibilityHelpers.cs
=> Fixed spacing on known username field list

src/Android/Android.csproj, src/App/App.csproj, src/Core/Core.csproj, src/iOS.Autofill/iOS.Autofill.csproj, src/iOS.Extension/iOS.Extension.csproj, src/iOS/iOS.csproj, store/google/Publisher/Publisher.csproj
Another round of lib updates for the latest bug fixes
=> Lib updates

src/App/Utilities/AppHelpers.cs
> Update legacy uses of `LockService`
- **AppHelper.cs**: Updated code to use `VaultTimeoutService`. Renamed variables to follow service pattern.
=> [Auto Logout] AppHelper - legacy service update

src/App/Pages/Settings/SettingsPage/SettingsPageViewModel.cs
=> Send vaultTimeoutActionChanged event after save

src/iOS.Autofill/CredentialProviderViewController.cs
Try to catch the null ref crash we are seeing in crash logs.
=> null check all the things

src/App/Pages/Vault/AddEditPage.xaml, src/App/Pages/Vault/AddEditPageViewModel.cs, src/App/Pages/Vault/ViewPage.xaml, src/App/Pages/Vault/ViewPageViewModel.cs, src/App/Utilities/AppHelpers.cs, src/Core/Models/Data/CipherData.cs, src/Core/Models/Domain/Cipher.cs, src/Core/Models/Response/CipherResponse.cs, src/Core/Models/View/CipherView.cs, src/Core/Models/View/FieldView.cs
Adds support for the hidden password functionality, companion PR to https://github.com/bitwarden/server/pull/743.
This PR has only been tested using the Android emulator.
=> Add support for hidden passwords

src/Android/Accessibility/AccessibilityHelpers.cs, src/Android/Autofill/AutofillHelpers.cs, src/Android/Resources/xml/autofillservice.xml
=> Add autofill/a11y support for ungoogled.chromium browser

src/Core/Models/View/LoginUriView.cs
Resolves https://github.com/bitwarden/browser/issues/1296
=> Do not process hostname for regex matching URIs

src/Core/Models/Data/CipherData.cs
as explained in issue https://github.com/bitwarden/mobile/issues/1006
=> Don't break when CipherType data is null

src/Core/Services/TokenService.cs, src/Core/Utilities/CoreHelpers.cs
These helpers are needed for SSO work.
=> base64 url encode/decode helpers

src/Android/Properties/AndroidManifest.xml, src/iOS.Autofill/Info.plist, src/iOS.Extension/Info.plist, src/iOS/Info.plist
Bump versions to 2.6.1 for continued testing
=> version bumps to 2.6.1

src/Android/Properties/AndroidManifest.xml, src/iOS.Autofill/Info.plist, src/iOS.Extension/Info.plist, src/iOS/Info.plist
=> bump version to 2.6.2

src/App/Pages/Accounts/LockPageViewModel.cs
Visibility should default to false unless all biometric checks pass
=> fix issue with bio unlock button visibility

src/Core/Enums/PolicyType.cs
> Synchronize all `PolicyType` enum values across server, jslib, and mobile repos.
- **PolicyType**: Added enum values for `OnlyOrg` and `RequireSso` to match the `server` and `jslib` repos
=> [Require SSO] Added new Policy Types

.github/workflows/build.yml
change msbuild reference to v1 to fix github warnings
=> change msbuild reference to v1

.github/workflows/build.yml
removed setup-nuget from script as nuget is pulled in via msbuild without using the deprecated actions
=> removal of setup-nuget

store/apple/en/copy.resx, store/fdroid/metadata/com.x8bit.bitwarden.yml, store/google/en/copy.resx
@kspearrin @go12 updates for app store copy
=> updated english copy for the app stores

src/Android/Properties/AndroidManifest.xml, src/iOS.Autofill/Info.plist, src/iOS.Extension/Info.plist, src/iOS/Info.plist
=> bump version to 2.7.0

src/Android/Properties/AndroidManifest.xml, src/iOS.Autofill/Info.plist, src/iOS.Extension/Info.plist, src/iOS/Info.plist
required to get testflight moving again
=> bump version to 2.7.1

src/Android/Properties/AndroidManifest.xml, src/iOS.Autofill/Info.plist, src/iOS.Extension/Info.plist, src/iOS/Info.plist
Required for TestFlight publishing
=> bump version to 2.7.3

store/google/Publisher/Publisher.csproj
https://github.com/googleapis/google-api-dotnet-client/releases
=> bump google publisher dep

src/App/Pages/Send/SendAddEditPage.xaml.cs, src/App/Pages/Send/SendAddEditPageViewModel.cs
Fixed some formatting. My real motivation is to trigger a rebuild to poke TestFlight.
=> Fixed formatting

src/Android/Accessibility/AccessibilityHelpers.cs, src/Android/Autofill/AutofillHelpers.cs, src/Android/Resources/xml/autofillservice.xml
Add Alook browser (https://play.google.com/store/apps/details?id=alook.browser) and update Via browser's URL bar.
=> [SupportedBrowsers] Update browsers

src/App/Pages/Send/SendAddEditPageViewModel.cs
Resolves https://app.asana.com/0/1199659118818122/1199987076477970/f
Sibling to https://github.com/bitwarden/jslib/pull/287
=> clear Send password if whitespace

src/Android/Properties/AndroidManifest.xml, src/iOS.Autofill/Info.plist, src/iOS.Extension/Info.plist, src/iOS/Info.plist
=> version bump to 2.9.1

src/Android/Properties/AndroidManifest.xml, src/iOS.Autofill/Info.plist, src/iOS.Extension/Info.plist, src/iOS/Info.plist
Version bump to 2.9.2 for TestFlight
=> bump to 2.9.2

src/Android/Accessibility/AccessibilityHelpers.cs, src/Android/Autofill/AutofillHelpers.cs, src/Android/Resources/xml/autofillservice.xml
https://github.com/jamal2362/Styx
=> Add support for Styx browser.

src/Android/Accessibility/AccessibilityHelpers.cs, src/Android/Autofill/AutofillHelpers.cs, src/Android/Resources/xml/autofillservice.xml
Supports when address bar is above.
=> Add support for Soul browser

src/App/Pages/Send/SendAddEditPageViewModel.cs, src/App/Resources/AppResources.Designer.cs, src/App/Resources/AppResources.resx
Mobile implementation of https://github.com/bitwarden/web/pull/915
=> Require user to verify email to use file Send

src/Core/Services/ApiService.cs
Related to bitwarden/server#1266. Fixes overlapping api endpoint
=> Fix overlapping ciphers api endpoints

src/App/Pages/Send/SendAddEditPageViewModel.cs, src/Core/Abstractions/IUserService.cs, src/Core/Services/SyncService.cs, src/Core/Services/UserService.cs
Refactor to match the logic here, so that we're consistent across clients: https://github.com/bitwarden/jslib/pull/344
=> Use UserService to manage emailVerified

src/App/App.xaml.cs
=> clear cache on logout

src/Android/Properties/AndroidManifest.xml, src/iOS.Autofill/Info.plist, src/iOS.Extension/Info.plist, src/iOS/Info.plist
> Bump mobile versions from 2.9.2 -> 2.10.0 in preparation of general release
- **AndroidManifest.xml**: Bump from 2.9.2 -> 2.10.0
- **iOS.Autofill / iOS.Extension / iOS / Info.plist**: Bump from 2.9.2 -> 2.10.0
=> [Version] Bump to 2.10.0

src/Android/Properties/AndroidManifest.xml, src/Core/Core.csproj, src/iOS.Autofill/Info.plist, src/iOS.Extension/Info.plist, src/iOS/Info.plist, store/google/Publisher/Publisher.csproj
- app version bump to `2.10.1` for TestFlight
- catch-up some lib versions
=> version bumps

src/App/Pages/Vault/ViewPageViewModel.cs
Resolves downloading attachments not reprompting.
=> More Autofill fixes

src/App/Pages/Accounts/LockPageViewModel.cs, src/App/Pages/Accounts/SetPasswordPageViewModel.cs, src/App/Pages/Settings/ExportVaultPageViewModel.cs, src/App/Services/MobilePasswordRepromptService.cs, src/Core/Abstractions/ICryptoService.cs, src/Core/Enums/HashPurpose.cs, src/Core/Services/AuthService.cs, src/Core/Services/CryptoService.cs, src/iOS.Core/Controllers/LockPasswordViewController.cs
Implement https://github.com/bitwarden/jslib/pull/404 and https://github.com/bitwarden/jslib/pull/407 for mobile.
=> Use 2 iterations for local password hashing

src/iOS.Autofill/CredentialProviderViewController.cs
Add a sleep in an attempt to resolve keyboard not showing up somtimes.
=> Add a 250ms sleep before prompting for password

store/apple/en/copy.resx, store/google/en/copy.resx
Change follows exactly what it sounds like it should :grin:
=> Fix encoding of & in resx XML

src/Android/Properties/AndroidManifest.xml, src/iOS.Autofill/Info.plist, src/iOS.Extension/Info.plist, src/iOS/Info.plist
=> bump version to 2.11.0

src/Android/Properties/AndroidManifest.xml, src/iOS.Autofill/Info.plist, src/iOS.Extension/Info.plist, src/iOS/Info.plist
bump version to 2.11.1 for testflight
=> bump version to 2.11.1

src/App/Pages/Settings/SettingsPage/SettingsPageViewModel.cs
Added the ability to conditionally exclude links to pages containing subscription/pricing info from the Settings screen
=> Add toggle for removing links to pages containing subscription info

src/Android/Properties/AndroidManifest.xml, src/iOS.Autofill/Info.plist, src/iOS.Extension/Info.plist, src/iOS/Info.plist
Bump app version to 2.11.2 for release
=> bump version to 2.11.2

src/Core/Services/AuthService.cs
add missing parameter in call to LogInHelperAsync
fixes #1474
=> bugfix in AuthService.LogInSsoAsync (#1474)

src/Android/Properties/AndroidManifest.xml, src/iOS.Autofill/Info.plist, src/iOS.Extension/Info.plist, src/iOS/Info.plist
Bump app version to 2.11.3 for release
=> bump app version to 2.11.3 for release

src/App/Pages/Accounts/EnvironmentPage.xaml, src/App/Pages/Accounts/HintPage.xaml, src/App/Pages/Accounts/LoginSsoPage.xaml, src/App/Pages/Accounts/RegisterPage.xaml, src/App/Pages/Generator/GeneratorPage.xaml, src/App/Pages/Send/SendAddEditPage.xaml, src/App/Pages/Settings/ExportVaultPage.xaml, src/App/Pages/Settings/FolderAddEditPage.xaml, src/App/Pages/Vault/AddEditPage.xaml, src/App/Pages/Vault/CollectionsPage.xaml, src/App/Pages/Vault/ScanPage.xaml, src/App/Pages/Vault/SharePage.xaml
https://community.bitwarden.com/t/change-close-text-to-cancel-on-creation-editing-generation-forms/31965
=> Change Close to Cancel in editing prompts.

src/Core/Models/Request/TokenRequest.cs
Companion to bitwarden/jslib#450
@eliykat sorry to step on your toes, I just want to make sure we're able to cut `rc`s soon
=> Encode auth email for unicode email support

.github/workflows/crowdin-sync.yml
Adding in the Crowdin Sync workflow that we spiked for Web. This allows for easy one-click opening of a PR with any new Crowdin changes.
=> Crowdin sync workflow

src/iOS.Extension/Info.plist, src/iOS/Info.plist
bump MinimumOSVersion to 12.0 (Autofill extension is already at 12.0)
=> bump MinimumOSVersion to 12.0

src/iOS/iOS.csproj
=> enable LLVM in iOS builds

src/iOS.Autofill/iOS.Autofill.csproj, src/iOS.Extension/iOS.Extension.csproj
=> enable LLVM in iOS extensions

.github/workflows/build.yml, .github/workflows/crowdin-sync.yml, .github/workflows/release.yml
These changes were based off the linter output.
=> Update workflows with linter suggestions

src/iOS/Info.plist
Fixes issue from hackerone ticket 1330577
=> Bugfix typerole

src/Android/Properties/AndroidManifest.xml, src/iOS.Autofill/Info.plist, src/iOS.Extension/Info.plist, src/iOS/Info.plist
=> Bump version to 2.12.1

src/App/Pages/Accounts/SetPasswordPageViewModel.cs, src/Core/Models/Response/OrganizationAutoEnrollStatusResponse.cs
> Fix typo in response object for auto enroll status API
- **SetPasswordPageViewModel**: Updated reference to boolean in response object
- **OrganizationAutoEnrollStatusResponse**: Updated boolean reference to match API
=> [SSO/Auto Enroll] Fixed response object typo

src/Android/Properties/AndroidManifest.xml, src/iOS.Autofill/Info.plist, src/iOS.Extension/Info.plist, src/iOS/Info.plist
=> Version bump to 2.13.0

src/App/Pages/Settings/ExportVaultPage.xaml, src/App/Pages/Settings/ExportVaultPageViewModel.cs, src/App/Resources/AppResources.Designer.cs, src/App/Resources/AppResources.resx, src/Core/Enums/PolicyType.cs
Adds support for the new policy which disables personal vault export.
=> Disable Private Vault Export Policy

src/Android/Properties/AndroidManifest.xml, src/iOS.Autofill/Info.plist, src/iOS.Extension/Info.plist, src/iOS/Info.plist
bump to 2.13.1 for testflight publishing
=> bump version for testflight

.github/workflows/build.yml
- Fixes pipeline so Android and iOS jobs can deploy properly.
=> Pipeline fixes

src/iOS.Core/Views/ExtensionTableSource.cs
=> filter Ciphers to exclude deleted items

src/Core/Models/Data/Permissions.cs, src/Core/Models/Domain/Organization.cs
Asana: https://app.asana.com/0/0/1201116867140797/f
Splits collections permissions. These permissions are currently unused, but keeps the models in line with bitwarden/jslib#504
=> Split collections permissions

src/Android/Properties/AndroidManifest.xml, src/iOS.Autofill/Info.plist, src/iOS.Extension/Info.plist, src/iOS/Info.plist
Bumping version to 2.14.2 for Android hotfix
=> Version bump 2.14.2

package-lock.json, package.json
Upgrading the `gh-pages` version.
* **package.json:** bump of `gh-pages` version as it was a bit out of date.
* **package-lock.json:** Updated with newest `npm install`
This will need to be manually after next release as this is only used in the release process.
=> Updating gh-pages

.github/workflows/build.yml, .github/workflows/crowdin-pull.yml, crowdin.yml
Update Crowdin sync process to push sources on every build of `master` and to pull weekly at midnight on Friday. 
* **.github/workflows/build.yml:** Added a Crowdin push after all of the build jobs on the `master` branch
* **.github/workflows/crowdin-pull.yml:** Renamed and added a schedule trigger to the Crowdin Pull
* **crowdin.yml:** Updated the Crowdin config file to the the outcome of the Action to match the outcome of the Crowdin GitHub App integration
=> Updating the crowdin sync process

crowdin.yml
Fix the new Crowdin Push
* **crowdin.yml:** fix the typo
=> fixing a typo

src/App/Pages/Accounts/LoginSsoPageViewModel.cs, src/Core/Abstractions/IAuthService.cs, src/Core/Services/AuthService.cs
Pass org id to authorization service for onboarding new CME accounts
Asana Task: https://app.asana.com/0/1201363553288890/1201367638175947/f
* **src/Core/Services/AuthService.cs: **Pass Org id to LogInHelper from SSO login 
* **src/Core/Abstractions/IAuthService.cs: **Add Org id to method parameters
* **src/App/Pages/Accounts/LoginSsoPageViewModel.cs: **Pass Org id to AuthService
- Onboarding for new SSO accounts using CME
=> pass OrgId to SSO login while using CME

src/App/Pages/Settings/ExportVaultPage.xaml, src/App/Pages/Settings/ExportVaultPageViewModel.cs, src/App/Resources/AppResources.Designer.cs, src/App/Resources/AppResources.resx
Update Export Vault screen for those using key connector with OTP
* **src/App/Pages/Settings/ExportVaultPage.xaml:** Update vault ui
* **src/App/Pages/Settings/ExportVaultPageViewModel.cs:** Add success toast to code send and exception handling
* **src/App/Resources/AppResources.resx:** Add resource strings
- Vault export functionality
=> ui changes export vault screen for key connector

src/App/Pages/Accounts/LockPage.xaml, src/App/Pages/Accounts/LockPage.xaml.cs, src/App/Pages/Accounts/LockPageViewModel.cs, src/App/Resources/AppResources.Designer.cs, src/App/Resources/AppResources.resx
If a key connector user has biometrics set up on the lock screen, we want to hide the master password prompt. This change will impact both the lock screen authentication, and autofill authentication on Android. 
If the user is using a PIN with biometrics, the screen should remain the same and prompt for PIN input.
* **src/App/Pages/Accounts/LockPage.xaml:** Altered padding to look decent if MP prompt is missing. Added a name to unlock button for hiding.
* **src/App/Pages/Accounts/LockPage.xaml.cs:** Hide MP field and Unlock button if key connector is being used, moved biometric prompt to this codebehind so we can make UI changes faster.
* **src/App/Pages/Accounts/LockPageViewModel.cs:** Created `UsingKeyConnector` property, additional ui changes if `true`
* …
=> ui changes for lock screen if using key connector with biometrics

src/Core/Services/AuditService.cs, src/Core/Services/AuthService.cs, src/Core/Services/CipherService.cs, src/Core/Services/SendService.cs
remove `throw e` from project as it hides stack trace
https://app.asana.com/0/1153292148278596/1201459506316842/f
=> remove re-throws of exceptions, hiding stack trace

.github/workflows/release.yml
Adds workflow input with logic to skip the version check if the pipeline run is a redeployment. 
- **.github/workflows/release.yml** - Added workflow inputs and logic to version check step.
=> Added logic for version check step

.github/workflows/version-bump.yml
This PR updates the Version Bump action to the latest version which includes formatting fixes for Android manifest files.
* **.github/workflows/version-bump.yml:** Changed hash to match latest version of Version Bump action.
=> Update Version Bump action

README.md, src/Android/Accessibility/AccessibilityHelpers.cs, src/Android/Autofill/AutofillHelpers.cs, src/Android/Resources/xml/autofillservice.xml
- Adding Browser compatibility
"com.kiwibrowser.browser.dev" package added which is official kiwi browser package publish on github regularly.
=> Adding kiwi Browser "Dev" package name for autofill support

src/Android/MainApplication.cs, src/App/App.csproj, src/App/Pages/Accounts/DeleteAccountViewModel.cs, src/App/Pages/Accounts/VerificationCodePage.xaml, src/App/Pages/Accounts/VerificationCodePage.xaml.cs, src/App/Pages/Accounts/VerificationCodeViewModel.cs, src/App/Resources/AppResources.Designer.cs, src/App/Resources/AppResources.resx, src/App/Utilities/VerificationActionsFlowHelper.cs, src/Core/Abstractions/IApiService.cs, src/Core/Services/ApiService.cs, src/iOS.Core/Utilities/iOSCoreHelpers.cs
Added possibility to delete an account that was logging on SSO with CME. Also, added a `VerificationCodePage` that can be reused when we need action code verification.
* **VerificationActionsFlowHelper.cs:** Added this helper that interacts with the different verifications (master password/verification code) and the actions to perform (like delete account)
* **DeleteAccountViewModel.cs:** Modified to adapt it to the `VerificationActionsFlowHelper`
* **VerificationCodePage.xaml/ViewModel.cs:** Added this view to reuse it when we need verification code with actions
* **ApiService:** Added possibility of avoid logging out when `HttpStatusCode.Unauthorized`
* Perform same tests as in #1621 
* Test that an account logged in on SSO with CME can also be deleted with the Verification Code
=> Account Deletion on SSO with CME

src/App/Pages/Accounts/VerificationCodePage.xaml, src/App/Pages/Accounts/VerificationCodeViewModel.cs
Fix master build fail because control not existing anymore to show icons.
* **VerificationCodePage.xaml:** Changed to new control to show icons
* **VerificationCodeViiewModel.cs:** Updated code to show the correct icon with the new way
Same as #1721
=> Fix icon update on Verify code view

src/App/Pages/Accounts/VerificationCodeViewModel.cs
Fix loading freeze on Verification Code view after sending the OTP
* **VerificationCodeViewModel.cs:** Added the hide loading call after sending the OTP so that the loading dialog gets hidden.
Same as #1721
=> Fix loading freeze on Verification Code view

src/iOS.Core/Controllers/LockPasswordViewController.cs
Resolves a missed icon conversion from #1541.
=> Update FA icons on LockPasswordViewController

src/App/Services/PushNotificationListenerService.cs, src/iOS/AppDelegate.cs, src/iOS/Services/iOSPushNotificationHandler.cs, src/iOS/Services/iOSPushNotificationService.cs
Clear the logs added previously to debug iOS push notifications
* Clear logs changing them to `Debug.WriteLine(...)`
No logs regarding "## PUSH NOTIFICATIONS" should be output on the Console
=> Clear Console.WriteLine logs on iOS push notifications

src/App/Pages/Settings/SettingsPage/SettingsPageViewModel.cs, src/App/Services/PushNotificationListenerService.cs
Cleared About alert info about the Push notifications registration
* Changed to only display on DEBUG mode the push notifications registration info on the Settings about alert
Push notifications registration info should only be displayed in DEBUG mode.
=> Cleared About alert info about Push Notifications registration

src/iOS.Core/Controllers/LockPasswordViewController.cs
The biometric cell of the Autofill screen was not being updated to the current theme. This fix is fixin to fix it.
* **src/iOS.Core/Controllers/LockPasswordViewController.cs:** Set theme background on bio cell init
Before:
After:
=> set background of biometricCell from theme

src/App/Pages/Vault/AddEditPage.xaml, src/App/Pages/Vault/GroupingsPage/GroupingsPageListItem.cs
> Make any requested icon changes. Merge to both `master` and `rc` once approved.
- **AddEditPage.xaml**: Icon update - `refresh` - > `generate`
- **GroupingsPageListItem.cs**: Icon update - all folders -> `folder`
-  Make sure the classes listed above are working/looking as expected
=> [Icons] FF requested icon changes

src/App/Pages/Accounts/LoginSsoPageViewModel.cs, src/App/Services/MobilePlatformUtilsService.cs, src/Core/Abstractions/IPlatformUtilsService.cs, src/Core/Enums/ClientType.cs, src/Core/Services/ApiService.cs
Adds two new headers included in each request. I decided to not re-use the `DeviceType`, since it's more granular.
`Bitwarden-Client-Name`: `[web, browser, desktop, cli, connector, mobile]`
`Bitwarden-Client-Version`: `1.41.0`
This will allow us to get an insight into which versions are currently in use.
- **platformUtils.service.ts:** Added new method, `getClientType`.
- **clientType.ts:** New enum with the client types.
Should be covered in general regression testing.
=> Client & Version headers

src/App/Pages/Accounts/TwoFactorPageViewModel.cs, src/App/Pages/Settings/SettingsPage/SettingsPageViewModel.cs, src/App/Pages/Vault/AddEditPageViewModel.cs, src/App/Pages/Vault/AttachmentsPageViewModel.cs
> Update all `help.bitwarden.com` and `bitwarden.com/help/article/*` to the new `bitwarden.com/help/*` URL pattern
- Make sure URL links don't 404 and take you to the correct page
=> [Help] Update links to new pattern

src/App/Pages/Vault/ScanPage.xaml.cs
Fix the crash on TOTP Scan Autofocus and improve the code for better cancellation and exception handling.
* **ScanPage.xaml.cs:** Improved the code for better cancellation and exception handling.
I'm not sure how to reproduce the issue because it seems to be a race condition, but the Scan view shouldn't crash when scanning the QR. Also the Scan should keep working as before.
=> Fix crash Autofocus on TOTP Scan

.github/workflows/version-bump.yml
Add new ShareExtension to the version bump Action
* **.github/workflows/version-bump.yml:** Add new iOS Extension to the version bump
=> Add iOS Share Extension to our version bump automation

src/App/Pages/Vault/ScanPage.xaml.cs
Improve the code to remove the DeviceTimer and use Task instead that are less likely to run into race conditions.
* **ScanPage.xaml.cs:** Improve the code by changing the `DeviceTimer` for `Task` and cancellation token source for handling the cancellation and the 3min failsafe.
The app shouldn't crash and should work as before when scanning.
=> Improve Scan autofocus timer to task code

src/App/Pages/Accounts/LockPageViewModel.cs
If our UserService failed to return an email from storage, we would continue with the authentication process on the LockPage. This crashed the project when it got down to our CryptoService. 
This change checks if the email is null, and logs out if so.
* **src/App/Pages/Accounts/LockPageViewModel.cs:** Log out if email is null
Regression testing needed for authenticating on Lock Page
- Password
- Pin
- Biometric
=> check email for null before authenticating

src/App/Resources/AppResources.resx
Asana: https://app.asana.com/0/1169444489336079/1200083053512725/f
Remove text indicating we fill credit cards and identities with autofill service
Check autofill description in settings
=> remove erroneous autofill description

.github/workflows/enforce-labels.yml
Adds Hold label enforcement as done in bitwarden/cli#456
=> Enforce Hold label

.github/workflows/workflow-linter.yml
To automate our linting by using the Bitwarden linter action, so that workflows will be tested for styling and programmatic errors on a pull request.
* **.github/workflows/workflow-linter.yml:** NEW: A workflow to use the Bitwarden Github workflow linter against any workflows in the `.github/workflows/*` folder.
Example: https://github.com/bitwarden/mobile/actions/runs/1854819678
~~- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)~~
~~- [ ] This change requires a **documentation update** (notify the documentation team)~~
=> Created initial workflow for workflow linting

src/App/Utilities/AppHelpers.cs
Missed the Send service cache reset when switching users, making the Sends appear to be identical across multiple accounts.
* **AppHelpers.cs:** Resolve SendService and call `ClearCache` when switching accounts
https://app.asana.com/0/1201803072708593/1201862267238033
=> Clear send service cache on account switch

src/Android/Accessibility/AccessibilityHelpers.cs, src/Android/Autofill/AutofillHelpers.cs, src/Android/Resources/xml/autofillservice.xml
Adding Alook browser again as per https://github.com/bitwarden/mobile/pull/1625#issuecomment-1054033319. @LiuDeng
=> [SupportedBrowsers] add Alook

.github/workflows/build.yml, .github/workflows/release.yml
Rename `hotfix` release branch name to `hotfix-rc` to avoid branch name collisions with branches like `hotfix/this-feature`.
- **.github/workflows/release.yml** rename `hotfix` to `hotfix-rc`
- **.github/workflows/build.yml** rename `hotfix` to `hotfix-rc`
=> Update hotfix release branch name to hotfix-rc

.github/workflows/release.yml
Updates the input name for "dry run" so that it's consistent with the other workflows.
* **.github/workflows/release.yml:** Updates input name.
=> Update input name to be consistent with other workflows

src/App/Pages/Send/SendGroupingsPage/ISendGroupingsPageListItem.cs, src/App/Pages/Send/SendGroupingsPage/SendGroupingsPage.xaml, src/App/Pages/Send/SendGroupingsPage/SendGroupingsPageHeaderListItem.cs, src/App/Pages/Send/SendGroupingsPage/SendGroupingsPageListItem.cs, src/App/Pages/Send/SendGroupingsPage/SendGroupingsPageListItemSelector.cs, src/App/Pages/Send/SendGroupingsPage/SendGroupingsPageViewModel.cs, src/App/Pages/Settings/SettingsPage/SettingsPageViewModel.cs, src/App/Pages/Vault/AutofillCiphersPage.xaml, src/App/Pages/Vault/AutofillCiphersPageViewModel.cs, src/App/Pages/Vault/GroupingsPage/GroupingsPage.xaml, src/App/Pages/Vault/GroupingsPage/GroupingsPageHeaderListItem.cs, src/App/Pages/Vault/GroupingsPage/GroupingsPageListItem.cs, src/App/Pages/Vault/GroupingsPage/GroupingsPageListItemSelector.cs, src/App/Pages/Vault/GroupingsPage/GroupingsPageViewModel.cs, src/App/Pages/Vault/GroupingsPage/IGroupingsPageListItem.cs, src/iOS/AppDelegate.cs
Fix crash produced on iOS 15.4 when adding an item on an empty list: Vault, Send mainly. Also applied the fix on Settings and Autofill Ciphers.
This has a drawback that it takes a bit longer to load the collection and there is an animation when loading the items, but it's something much better than the app crashing. It's because adding a delay between item adding, the crash is related to https://github.com/xamarin/Xamarin.Forms/issues/13323
Also fixed crash when calling base on `OpenUrl` on `AppDelegate`
* **AppDelegate:** Removed call to base on `OpenUrl` given that that throws an exception for optional iOS method
* **...xaml:** Added common item header template, removed grouping and `GroupHeaderTemplate`
* **...Selector:** Added the `HeaderTemplate` and logic to return it depending on …
=> Fix iOS 15.4 crash on adding first item on collection

src/App/Pages/Send/SendGroupingsPage/SendGroupingsPageViewModel.cs, src/App/Pages/Settings/SettingsPage/SettingsPageViewModel.cs, src/App/Pages/Vault/AutofillCiphersPageViewModel.cs, src/App/Pages/Vault/GroupingsPage/GroupingsPageViewModel.cs
Hotfix of flickering on iOS while loading collections due to collections crash hotfix #1850 
* **...ViewModel:** Changed the code to only make special loading of the list if it's coming from an empty state. If so, first the list is replaced with the header and the all the items are loaded. If it's not empty, then the whole list is replaced at once.
Test that Vault items, Send items, Settings and Autofill ciphers list are loading correctly even if you remove all items so that the list gets empty and also when the list is empty add a new item and test that the app behaves as expected without crashing.
=> Fixed flickering on iOS while loading collections

src/Core/Services/StateService.cs
Cleanup: Removed extra debug logging since it's no longer necessary (and potentially expensive)
* **StateService.cs:** Removed extra logging around state & value storage R/W
N/A
=> Remove verbose state & value storage debug logging

src/Android/Services/BiometricService.cs, src/Android/Services/DeviceActionService.cs, src/App/Abstractions/IDeviceActionService.cs, src/App/Pages/Settings/AutofillServicesPageViewModel.cs, src/App/Pages/Vault/AutofillCiphersPageViewModel.cs, src/Core/Services/TokenService.cs, src/iOS.Core/Services/DeviceActionService.cs
Fixes for several crashes reported in AppCenter
* **BiometricService.cs:** Extended `try` scope around keystore calls (`_keyStore.GetKey(..)` was throwing `UnrecoverableKeyException` which we catch, but only when calling `cipher.Init(..)`)
* **DeviceActionService.cs:** Null check `cipher` in addition to `cipher.Login`
* **AutofillServicesPageViewModel.cs** Platform check Android before calling `deviceActionService.AutofillServiceEnabled()` which throws unsupported on iOS
* **AutofillCiphersPageViewModel.cs** null check `appOptions` before getting `appOptions.Uri`
* **TokenService.cs** move second `_accessTokenForDecoding` null check inside initial null check block as recommended in #1861 
N/A as these crashes haven't been reproduced in house
=> Crash fixes

src/App/Pages/Send/SendGroupingsPage/SendGroupingsPage.xaml.cs, src/App/Pages/Send/SendsPage.xaml.cs, src/App/Pages/Vault/CiphersPage.xaml.cs, src/App/Pages/Vault/GroupingsPage/GroupingsPage.xaml.cs, src/App/Resources/AppResources.Designer.cs, src/App/Resources/AppResources.resx
Currently, search screens in our clients use generic titles such as “Search collection” or “Search folder”. In desktop and browser the folder name is shown but in mobile there is no clue as to which folder, collection, or item type you are searching for.
This PR adds the name of the collection/folder/type to the title of the page in mobile. For Sends, it also adds whether its a Text or File Send.
* **src/App/Pages/Vault/GroupingsPage/GroupingsPage.xaml.cs:** Pass the page title to search screen
* **src/App/Pages/Vault/CiphersPage.xaml.cs:** Removes previous titles and uses page title instead
* **src/App/Pages/Send/SendGroupingsPage/SendGroupingsPage.xaml.cs:** Passes the type of Send to the search screen
* **src/App/Pages/Send/SendsPage.xaml.cs:** Uses type of Send as search screen title …
=> [BEEEP] add context to search titles

.github/workflows/build.yml
- Switching to app center org
**- build.yml:** Changed from old org to proper one.
**- N/A**
=> Switched org

src/iOS.Core/Renderers/CustomLabelRenderer.cs
Removed workaround of null reference on `LabelRenderer` given that [Xamarin.Forms package has been updated](https://github.com/xamarin/Xamarin.Forms/releases/tag/release-5.0.0-sr9) and already includes the fix. 
* **CustomLabelRenderer.cs:** Removed try...catch that was the workaround for the issue.
The app should not crash on the same tests as #1690
=> TDL-13 Removed workaround of null reference on LabelRenderer

src/App/Pages/Generator/GeneratorHistoryPageViewModel.cs
Fix Password History to load correctly by updating on the main thread.
* **GeneratorHistoryPageViewModel:** Updated the properties in `InitAsync` on the main thread.
When entering to the Password History, the view should load correctlly.
=> PS-291 Fix Password History load correctly

.git-blame-ignore-revs, .github/workflows/build.yml, README.md
Add `.git-blame-ignore-revs`, enable linting in CI. Update Readme
=> [TI-8] Add .git-blame-ignore-revs

.gitattributes
Should resolve the linting issues
=> Update .gitattributes to fix build issue

.github/PULL_REQUEST_TEMPLATE.md
Testing requirements / QA notes are now in the Jira ticket templates, and can be removed from the Github PR templates.
The reviewer of any community PR is responsible for completing the testing notes in Jira.
=> Remove testing requirements from pr template

src/App/Pages/Vault/PasswordHistoryPageViewModel.cs
Fix password history page on iOS devices.
**PasswordHistoryPageViewModel.cs**: Invoked view model properties changes on main thread.
=> PS-593 -  View model properties are now updated on main thread

.github/PULL_REQUEST_TEMPLATE.md
Updated Pull request template to include formatting check.
=> Update PULL_REQUEST_TEMPLATE to include formatting check

src/App/Pages/Vault/ScanPage.xaml.cs
Fix crash when scanning TOTP in Android. Improves previous PR: #1759 
* **ScanPage.xaml.cs:** Changed `Device.BeginInvokeOnMainThread(...)` for `await Device.InvokeOnMainThreadAsync` so that exceptions are bubble up and caught by the try...catch. Also added null check just in case on `OnDisappearing` for the awaiting task.
=> [EC-255] Fix crash when scanning TOTP in Android

src/App/Pages/Vault/CiphersPageViewModel.cs, src/App/Pages/Vault/GroupingsPage/GroupingsPageViewModel.cs
Alphabetize the list of organizations in the vault filter list
* **GroupingsPageViewModel/CiphersPageViewModel.cs:** Added `OrderBy` to org list linq statement
=> [SG-79] Alphabetize organization list in vault filter

.github/workflows/release.yml
Update the way we check the release version to use our new action
=> Updating the release version check to use the new action

.github/workflows/build.yml
GitHub decided to break our builds by updating NuGet. This pins the version to that last working version.
* **.github/workflows/build.yml:** Pin the NuGet versions
=> Pin NuGet version

src/App/Pages/Accounts/LockPageViewModel.cs
Fix formatting so that `master` doesn't break
* **LockPageViewModel:** Fix formatting
=> Fix formatting

README.md
Fixes #1977
Fixing a link
Just updated the link with a working one
=> [EC-304] Replace link to mobile section of contributing documentation

src/App/Resources/AppResources.resx
Update the wording on the modal warning when deleting the account.
* **src/App/Resources/AppResources.resx:** Updated the text for the modal warning
=> [EC-305] Updated the wording on the modal warning when deleting the account

src/iOS.Core/Renderers/CollectionView/CollectionException.cs, src/iOS.Core/Renderers/CollectionView/ExtendedGroupableItemsViewController.cs, src/iOS.Core/Renderers/CollectionView/ExtendedGroupableItemsViewDelegator.cs, src/iOS.Core/iOS.Core.csproj
Add more logging information to see where the AppCenter list crash is happening
* **CollectionException.cs:** Added this exception to easily spot it on the reports
* **ExtendedGroupableItemsViewController.cs:** Improved the logging add creates the delegator
* **ExtendedGroupableItemsViewDelegator.cs:** Added this delegator that is a point where we can add helpful logging of the crash
=> [EC-324] Added more logging for information on list crash

src/App/Pages/Vault/GroupingsPage/GroupingsPageViewModel.cs
=> [EC-325] Fix format

src/App/Resources/AppResources.resx
Changes additional strings to sentence case
- Only changed translations
-------------------------------------------------
---------------------------------------
=> [EC-353] Fix sentence cases

src/App/Pages/Settings/OptionsPage.xaml, src/App/Pages/Settings/OptionsPage.xaml.cs, src/App/Pages/Settings/OptionsPageViewModel.cs, src/App/Resources/AppResources.Designer.cs, src/App/Resources/AppResources.resx
=> [EC-348] change blacklisted to blocked URIs

src/Android/Properties/AndroidManifest.xml
Updated AndroidManifest format as to what Visual Studio for Mac auto-formats to avoid merge conflicts/ resetting the file on commits.
* **AndroidManifest.xml:** Updated format of the file to what is automatically done by Visual Studio for Mac when the solution opens.
=> [EC-366] Updated AndroidManifest format

.github/workflows/version-auto-bump.yml
Add stub to test autobump workflow done in another PR: https://github.com/bitwarden/mobile/pull/2013
* **.github/workflows/version-auto-bump.yml:** Add stub to test autobump workflow done in another PR: https://github.com/bitwarden/mobile/pull/2013
=> Add autobump workflow stub

.github/workflows/crowdin-pull.yml
This PR updates the action hash of the Crowdin action.  The new version of the action has been updated to match the GitHub spec which fixes the error when running the workflow.
* **.github/workflows/crowdin-pull.yml:** Update the Crowdin action hash
=> Update Crowdin Sync action hash

.github/workflows/build.yml
Fix Android sign job during build. 
* **.github/workflows/build.yml:** Update worker to windows server 2022 which contains VS 2022.
=> Fix Android build

.github/workflows/release.yml
In order to track which Jira issues are included in each deployment, we need to tie the release pipeline to Github deployments, which the Github for Jira integration will then tie to Jira deployments.
* **[release.yml](https://github.com/bitwarden/mobile/compare/ENG-71-add-deployment?expand=1#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34)** Added workflow steps to create a Github deployment and update the status to success or failure based on the job success or failure.
=> [ENG-71] Add Github deployment to release pipeline.

src/App/Pages/Accounts/HintPage.xaml, src/App/Pages/Accounts/HintPage.xaml.cs, src/App/Pages/Accounts/HintPageViewModel.cs, src/App/Pages/Accounts/LoginPage.xaml, src/App/Pages/Accounts/LoginPage.xaml.cs, src/App/Pages/Accounts/LoginPageViewModel.cs, src/App/Utilities/ThemeManager.cs, src/iOS.Autofill/CredentialProviderViewController.cs, src/iOS.Core/Controllers/BaseLockPasswordViewController.cs, src/iOS.Core/Controllers/LockPasswordViewController.cs, src/iOS.Core/Services/DeviceActionService.cs, src/iOS.Extension/LoadingViewController.cs, src/iOS.ShareExtension/LoadingViewController.cs
The three dots more menu on iOS extensions' login view was not working. This fixes it and also fixes the style on HintPage and some things over there that weren't working because of being on an extension.
* **HintPage.xaml:** Changed event to command on more menu item
* **HintPage.xaml.cs:** Removed Submit_Clicked
* **HintPageViewModel.cs:** Added logging and to SubmitCommand and fixed alert display to call the one in `IDeviceActionService` instead of `Page` so it works on the extensions as well
* **LoginPage.xaml:** Added binding for enabled on email
* **LoginPage.xaml.cs:** Changed a bit the More_Clicked to call the VM command for the logic and just left the behavior with the overlay in there. Also added some logging and changed a bit some flags.
* **LoginPageViewModel.cs:** Added …
=> [EC-371] Fix iOS extensions login more menu

src/App/Utilities/EnumHelper.cs, src/App/Utilities/LocalizableEnumConverter.cs, src/Core/Attributes/LocalizableEnumAttribute.cs, src/Core/Core.csproj
Add some helpers to ease enum value localization
* **EnumHelper.cs:** Helper to localize enums by using the type as a parameter or as a generic parameter
* **LocalizableEnumConverter.cs:** Converter to be used in xaml that used the EnumHelper for the localization
* **LocalizableEnumAttribute.cs:** Attribute to be used in enum values to set the key that is used for localization
=> EC-487 Add helpers to localize enum values

src/App/Pages/Accounts/LoginPasswordlessPage.xaml.cs, src/App/Pages/Accounts/LoginPasswordlessViewModel.cs, src/App/Resources/AppResources.resx, src/Core/Abstractions/IApiService.cs, src/Core/Abstractions/IAuthService.cs, src/Core/Enums/NotificationType.cs, src/Core/Models/Request/PasswordlessLoginRequest.cs, src/Core/Models/Response/PasswordlessLoginResponse.cs, src/Core/Services/ApiService.cs, src/Core/Services/AuthService.cs
Added two method to connect to api service, one to get the details from a passwordless request and another to accept/reject a pending request.
=> [SG-408] Implement passwordless api methods

src/App/Resources/AppResources.resx
Fix AppResources encoding to be UTF-8 with BOM
* **AppResources.resx:** Fix encoding to be UTF-8 with BOM
=> [EC-540] Fix AppResources encoding to be UTF-8 with BOM

src/App/Pages/Vault/CipherDetailsPageViewModel.cs, src/App/Pages/Vault/GroupingsPage/GroupingsPageViewModel.cs
Fixed bug where free users with classic organizations plans were not able to see TOTP codes.
Added org validation besides premium.
=> [SG-659] Fixed TOTP not showing for free user with classic plans.

src/App/App.xaml.cs, src/App/Services/PushNotificationListenerService.cs, src/Core/Services/ApiService.cs, src/Core/Services/AuthService.cs
Some bugs were found after performing end-to-end testing, requiring some code changes.
=> [SG-169] End-to-end test fixes

src/App/Pages/Vault/AttachmentsPage.xaml, src/App/Pages/Vault/AttachmentsPage.xaml.cs, src/App/Pages/Vault/AttachmentsPageViewModel.cs, src/Core/Services/FileUploadService.cs
Prevent application from crashing when uploading a file.
* **AttachmentPageViewModel.cs:** Improved error handling and catching when saving an attachment
=> PS-1404 Improved exception handling when saving an attachment

src/Android/Services/AndroidPushNotificationService.cs, src/App/App.xaml.cs, src/App/Pages/Accounts/LoginPasswordlessPage.xaml, src/App/Pages/Accounts/LoginPasswordlessViewModel.cs, src/App/Resources/AppResources.resx, src/App/Services/PushNotificationListenerService.cs, src/App/Styles/Black.xaml, src/App/Styles/Dark.xaml, src/App/Styles/Light.xaml, src/App/Styles/Nord.xaml, src/Core/Constants.cs, src/Core/Models/Response/PasswordlessLoginResponse.cs, src/Core/Services/ApiService.cs, src/Core/Services/AuthService.cs
Change requests from async demo of passwordless feature.
Forced modal to appear after app came into foreground. Android was having erratic behaviour when the user had the app in background and clicked the received notification.
=> [SG-169] Passwordless demo change requests

src/Android/Android.csproj, src/App/App.csproj, src/Core/Core.csproj, src/iOS.Autofill/iOS.Autofill.csproj, src/iOS.Extension/iOS.Extension.csproj, src/iOS.ShareExtension/iOS.ShareExtension.csproj, test/Common/Common.csproj, test/Core.Test/Core.Test.csproj, test/Playground/Playground.csproj
Updated all third-party dependencies to latest stable.  In addition to getting back on track, this helps reduce the IDE thrashing/violence when switching between `master` and MAUI dev branches.  We were several revisions behind on some of these due to them shifting to requiring Android 12 as a build target, and we hadn't yet handled the updated requirements to target past 11.  With #2063 in place (thanks @aj-rosado !) we can finally bump these up.
* ***.csproj:** Misc version bumps to all projects with a few exceptions:
- `Publisher`: Holding off on this to avoid breaking our automated publishing process
- `xunit`: Issue in `2.4.2` crashing the test: https://github.com/xunit/xunit/issues/2572
- Please …
=> Updated libs to latest stable

src/App/App.csproj
Removed a duplicate dependency
* **App.csproj:** Removed duplicate (and older) `Xamarin.CommunityToolkit` dependency
=> Remove duplicate Xamarin community toolkit dependency

src/App/App.xaml.cs, src/App/Pages/Accounts/LoginPasswordlessViewModel.cs
Fixed date time object that was not being converted to universal time.
=> [SG-690] DateTime to Utc fix

.github/workflows/version-auto-bump.yml
I couldn't suggest everything easily in GitHub's review process, so I created a PR with changes.
=> DEVOPS-1014 - Review

.github/workflows/version-auto-bump.yml
Fix version auto bump workflow. https://bitwarden.atlassian.net/browse/DEVOPS-1014
* **.github/workflows/version-auto-bump.yml:** Fix obtaining version tag. Fix regex matching major and minor portions of the released version.
=> [DEVOPS-1014] Fix version auto bump workflow

src/Android/Android.csproj, src/Android/Constants.cs
Added droid constants file with the package name constant to be used across the app
* **Constants.cs:** This was added to have the `PACKAGE_NAME` constant to be used across the app and help ease scripts.
=> [EC-602] Added droid constants

src/App/App.xaml.cs, src/App/Pages/Accounts/LoginPasswordlessViewModel.cs
1. Open login request once it’s received,
2. Wait 15 minutes with app backgrounded
3. Open app once expired
Expected: Displays alert that it’s expired, dismisses login request, redirects to vault
Actual: Displays alert that it’s expired, hangs on Bitwarden logo screen. Have to close and re-open app
Datetime values were not matching.
=> [SG-690] Passwordless Timeout fix

src/App/Resources/AppResources.resx
Currently the use of Title and Sentence case is inconsistent throughout the product. To improve the UI consistency, readability, and localization, this change updates strings to use sentence case.
src/App/Resources/AppResources.resx
=> [PS-1543]Sentence case mobile

src/iOS.ShareExtension/iOS.ShareExtension.csproj
This was originally an attempt to get the package size down in iOS but had no effect.  It is however an unnecessary dependency now, so let's remove it anyway.
* **iOS.ShareExtension.csproj:** Remove `Xamarin.Forms` dependency
=> Removal of Xamarin.Forms dependency from iOS.ShareExtension

.github/workflows/version-auto-bump.yml
Fix mobile autobump workflow.
.github/workflows/version-auto-bump.yml: Change trigger to tag push and fix increase of patch part of the version.
=> Fix autobump workflow

src/App/Pages/Settings/OptionsPageViewModel.cs, src/App/Resources/AppResources.Designer.cs, src/App/Resources/AppResources.resx, src/App/Styles/SolarizedDark.xaml, src/App/Styles/SolarizedDark.xaml.cs, src/App/Utilities/ThemeManager.cs
Added a new Solarized Dark theme for the mobile apps.
* **OptionsPageViewModel.cs:** Added new KeyValuePair on the theme options
* **AppResources.resx:** Added string title of the new Solarized Dark theme
* **SolarizedDark.xaml:** The new theme colors scheme
* **ThemeManager.cs:** Added the new theme
iOS:
hone SE (3rd generation) - 2022-10-14 at 17 45 39](https://user-images.githubusercontent.com/109146700/196489692-3a72fd76-915e-49b0-9b69-c6759d7214cb.png)
Android:
- If this change has particular **deployment requirements** - notify …
=> [PS-1188] Add new Solarized Dark Theme

src/App/Pages/Accounts/LoginPasswordlessPage.xaml.cs
Add a  cancel button to the login request modal on Android. 
=> [SG-765] Add cancel button to passwordless login modal on android

src/App/Pages/Accounts/LoginPageViewModel.cs
Fix bug. When the user is saving new environment endpoints and if one of them is wrong, the app will crash.
Add try catch to `LoginViewModel -> InitAsync` method.
=> [SG-806] Mobile wrong environment endpoints crash

.github/workflows/release.yml
This PR updates the release workflow runs to include `workflow_dispatch` name in each run, this separates dry run releases runs from the actual releases runs.
=> add run-name for release to include workflow trigger

.github/workflows/release.yml
=> Devops 1039 update release flow dry run step names

src/App/Resources/AppResources.resx
SG-807 Sentence case fixes for mobile
=> [SG-807] Sentence case fixes

.github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/version-auto-bump.yml, .github/workflows/version-bump.yml
This PR is updating the set output command to the latest method, the previous is deprecated.
Change the ::set-output command to Github's environment variable $GITHUB_OUTPUT
* .github/workflows/*.yaml files
=> update ::set-output to the latest method

src/watchOS/bitwarden/bitwarden WatchKit App/Assets.xcassets/AccentColor.colorset/Contents.json, src/watchOS/bitwarden/bitwarden WatchKit Extension/Assets.xcassets/AvatarItemBackground.colorset/Contents.json, src/watchOS/bitwarden/bitwarden WatchKit Extension/Utilities/ColorUtils.swift, src/watchOS/bitwarden/bitwarden WatchKit Extension/Views/CipherListView.swift
Improve UI/UX on Apple Watch
* **CipherListView:** UI/UX improvements like padding and background and added "Bitwarden" on the navigation bar
=> [EC-834] Apple Watch UI/UX improvements

src/watchOS/bitwarden/bitwarden WatchKit Extension/Views/CipherListView.swift
Fix Watch cipher fetch that was accidentally changed on the last PR
* **CipherListView.ext:** Fixed cipher list fetch and added flag to prevent this from happening again
=> [EC-841] Fix Watch fetch cipher and added condition for previews

src/App/Pages/Accounts/LoginPageViewModel.cs, src/App/Pages/Accounts/LoginPasswordlessViewModel.cs, src/App/Pages/BaseViewModel.cs
We currently do not have generic error handling code in the mobile repo to handle errors and present them to the user in a consistent manner.
Add method in BaseViewModel to handle exceptions this will show the user a dialog with a generic or custom message.
=> [SG-872] Create generic exception handler for mobile

src/watchOS/bitwarden/bitwarden.xcodeproj/project.pbxproj
Bump Apple Watch version to 2022.12.0
* **project.pbxproj:** Bumped `MARKETING_VERSION` to 2022.12.0
=> [EC-785] Bumped Apple Watch version to 2022.12.0

.github/workflows/build.yml
Revert ignore Android build added while developing Apple Watch app. Introduced in #2228 
* **build.yml:** Removed condition to run Android that prevented it from running
=> [EC-846] Revert ignore Android build on the CI

src/watchOS/bitwarden/bitwarden WatchKit Extension/Views/CipherListView.swift
Improve the Apple Watch cipher list performance where the scrolling was not smooth.
* **CipherListView:** Removed animations of the Search box and also moved back to the simple `List` instead of the `TrackableWithHeaderListView`
=> [EC-847] Improve Watch list UI performance

src/App/Pages/Accounts/LoginPageViewModel.cs
Remove login with device feature from master.
Button visibility is bound to IsKnownDevice property of the viewmodel. This property will always be false.
=> [SG-174] Remove login with device button

src/Android/Services/LocalizeService.cs, src/iOS.Core/Services/LocalizeService.cs, src/iOS.Core/Views/Toast.cs, src/watchOS/bitwarden/bitwarden WatchKit Extension/Services/CryptoService.swift
Clear console logging to be only shown in debug
* **...:** Changed all console logging to be only shown in debug
=> [EC-868] Clear console logging

src/Core/Exceptions/ApiException.cs, src/Core/Models/Response/ErrorResponse.cs
Improve `ApiException` so that we can log an enhanced message with the errors provided by the Server instead of just "An API error has occurred"
**With `ValidationErrors`:**
{Http status code number} {Http status code string}. [{key1}]:{validation11}; {validation12}; {validation13} ...
[{key2}]: {validation21}; {validation22}; {validation23} ...
[{key3}]:{validation31}; {validation32}; {validation33} ...
...
**Without `ValidationErrors`:**
{Http status code number} {Http status code string}. {Message}
**Examples:**
404 Bad Request. []: Premium status is required
404 Bad Request. [Token]: Invalid token
404 Bad Request. []: User verification failed
["MasterPassword"]: Invalid password
and if no `ValidationErrors` are there but there is a `Message` we should get something like:
403 …
=> [EC-469] Improve ApiException message

src/App/Pages/Vault/CipherAddEditPageViewModel.cs, src/App/Resources/AppResources.Designer.cs, src/App/Resources/AppResources.resx
Add the honorific title "Mx" as an option in the identity title.
* **src/App/Resources/AppResources.resx:** Define "Mx" as a string resource
* **src/App/Resources/AppResources.Designer.cs:** Declare method to return string from AppResources.resx
* **src/App/Pages/Vault/CipherAddEditPageViewModel.cs:** Add "Mx" as an option in the identity title selection
Android:
iOS:
=> [PS-2324] Add honorific title "Mx"

src/App/Pages/Accounts/RegisterPageViewModel.cs
Make "Check known data breaches" switch ON by default.
https://user-images.githubusercontent.com/4648522/217916961-e50ccab8-787d-489b-8064-df90661107de.mov
=> [SG-1057] "Check known data breaches" switch is OFF by default

src/App/Resources/AppResources.resx
The ‘Log in with device’ button option currently reads ‘Log In with device’
- The 'i' should not be capitalized 
- it should be displayed as, ‘Log in with device’
=> [SG-1052] [Defect] - Log in with device button case incorrect

src/Android/Properties/AndroidManifest.xml, src/App/Abstractions/IDeepLinkContext.cs, src/App/Services/DeepLinkContext.cs, src/App/Utilities/AppSetup.cs, src/Core/Constants.cs, src/iOS/AppDelegate.cs, src/iOS/Info.plist
Add otpauth scheme handling on iOS so that the app can handle TOTPs uris and can be selected in "Password options" -> "Set up verification codes using".
* **Info.plist:** Added otpauth scheme to be handled
* **AppDelegate:** Added handling of Uris on `OpenUrl`
* **IDeepLinkContext, DeepLinkContext:** Added this class to handle deep links, more logic here in the upcoming PRs for the feature
* **AppSetup:** Registered `IDeepLinkContext`
=> [EC-980] Added iOS otpauth handler

README.md
Remove the old dotnet format instructions since everything should be updated by now.
=> Remove dotnet format note

src/App/Pages/Settings/SettingsPage/SettingsPageViewModel.cs, src/App/Resources/AppResources.Designer.cs, src/App/Resources/AppResources.resx, src/Core/Abstractions/IPolicyService.cs, src/Core/Services/PolicyService.cs, src/Core/Services/VaultTimeoutService.cs
=> Revert "[EC-1045] add vault timeout action to policy"

src/App/Pages/Accounts/LoginPageViewModel.cs
Do not clear Master password  if login is ongoing.
Added control variable to check if the app is currently performing a login.
=> [PM-1431] [Defect] [Android] New accounts are not able to log in

src/Core/Services/StateService.cs
This fixes the issue where the vault timeout option `Never` would not persist.  Originally `null` represented this option but a [recent change](https://github.com/bitwarden/mobile/pull/2366) returned defaults in the `StateService` getters, breaking the null handling.  This restores the null support in the getters, and sets the defaults on first login in `ScaffoldNewAccountAsync` to restore this functionality without breaking the recent change to retain settings on logout.
* **StateService.cs:** Remove null fallback values from `GetVaultTimeoutAsync` and `GetVaultTimeoutActionAsync`, and set initial defaults in `ScaffoldNewAccountAsync`
- Please add **unit tests** where it makes sense to do so (encouraged …
=> [PM-1567] Fix for vault timeout 'never' not persisting

.github/workflows/release.yml
Fix upload the SHA256 hashes to the GitHub release.
* **.github/workflows/release.yml:** Fix path for the SHA256 hashes
=> Fix Mobile Release workflow to properly upload SHA256 hashes

.github/workflows/build.yml, .github/workflows/crowdin-pull.yml, .github/workflows/version-bump.yml
- Few edits for the CI-only SP KV
=> [DEVOPS-1259] changing CI-only SP KV job names

src/Core/Services/StateService.cs
On making a `login with device` request, the device that was making the request was receiving a push notification and showing it.
Remove ApprovePasswordlessLogins value on logout
=> [PM-1946] remove ApprovePasswordlessLogins value on logout

.github/labeler.yml, .github/workflows/pr-labeler.yml
This new workflow will add platform labels based on the PR file path changes.
=> Adding a Pull Request Labeler workflow

.github/labeler.yml
Adds src/App to PR Labeler, missed in #2503 
=> Adds src/App folder to PR Labeler

src/iOS.Core/Controllers/LoginAddViewController.cs, src/iOS.Core/Views/FormEntryTableViewCell.cs
🐛 Fix VoiceOver on buttons when adding new item on iOS extension.
* **LoginAddViewController:** Added the accessibility label to the button so VoiceOver can read it.
* **FormEntryTableViewCell:** Added the accessibility label and hint to the button so VoiceOver can read it.
=> [PM-1798] [BEEEP] Fix VoiceOver on buttons when adding new item on iOS extension

.github/labeler.yml, src/iOS.Core/iOS.Core.csproj
Added '' to paths with dots in. This should fix the matching of paths with dots.
=> PR Labeler: fix for paths with dots

.github/workflows/automatic-issue-responses.yml, .github/workflows/build.yml, .github/workflows/crowdin-pull.yml, .github/workflows/enforce-labels.yml, .github/workflows/release.yml, .github/workflows/version-auto-bump.yml, .github/workflows/version-bump.yml, .github/workflows/workflow-linter.yml
```
```
- Update all workflows actions with their version pinned
- .github/worflows/*
=> update all actions for version pin

src/App/Pages/Settings/SettingsPage/SettingsPageViewModel.cs
Fix settings vault timeout action policy check that was changed during a merge on #2443 
* **SettingsPageViewModel:** Fix the key to check on the policy on Vault timeout action.
=> [PM-2249] Fix vault timeout action policy check

src/Core/Services/ApiService.cs
Fix response check where in some kind of responses the `ContentType` property of `Headers` is not being filled properly. So add an additional check against the headers enumeration directly.
* **ApiService:** Added new check to see if the content of a response is media type is Json looking into the headers enumeration directly.
=> [PM-2232] Fix Json response check

.github/workflows/build.yml, .github/workflows/crowdin-pull.yml, .github/workflows/enforce-labels.yml, .github/workflows/release.yml
- Some workflows are corrected to include the correct versions existing
- .github/workflows/build.yml
- .github/workflows/crowdin-pull.yml
- .github/workflows/enforce-labels.yml
- .github/workflows/release.yml
=> [DEVOPS-1392] add more comment to missing actions

store/fdroid/metadata/com.x8bit.bitwarden.yml
Update F-Droid listing author name to `Bitwarden Inc`
Change `8bit Solutions LLC` to `Bitwarden Inc` in the F-Droid listing
=> Update F-Droid listing author name

src/App/Pages/Accounts/LoginPasswordlessPage.xaml, src/App/Pages/Accounts/LoginPasswordlessRequestPage.xaml
* **LoginPasswordlessPage.xaml:** Adding IDs for fingerprint/IP/device labels + action buttons
* **LoginPasswordlessRequestPage.xaml:** Adding IDs for fingerprint label + action buttons
=> [PM-2612] Adding AutomationIDs for LoginPasswordlessPage elements

src/App/Pages/Settings/FolderAddEditPage.xaml
Updating a wrong locator added on FolderAddEditPage
* ** FolderAddEditPage.xaml:** Updating locators
=> [PM-2798] Fixing Toolbar locators in FolderAddEditPage

src/Core/Services/AuthService.cs
On the approving device, we should only be sending the encrypted Symmetric Key since we have already authenticated through SSO.
if mp is not present ignore it and send null.
=> [PM-2583] Add logic to only send Symmetric Key for TDE Approval Auth Request

.github/workflows/build.yml
This PR adds the `actions/setup-dotnet` action to install the .NET 3.1.x framework in order for the Android build jobs to complete successfully.
* **.github/workflows/build.yml:** Add `actions/setup-dotnet` action to Android build jobs
=> Fix Build Workflow

.github/workflows/version-auto-bump.yml
This PR fixes a syntax error in the `Version Auto Bump` workflow to make it valid.
* **.github/workflows/version-auto-bump.yml:** Fix the `trigger_version_bump job` syntax.
=> Fix syntax in Version Auto Bump workflow

src/App/Resources/AppResources.resx
Remove resource duplication introduced by https://github.com/bitwarden/mobile/pull/2616
* **AppResources:** Removed duplicated string
=> [PM-2320] Fix duplicated resource

README.md
Fix a minor text error in README.
* **README.md:** Change "Google Play" to "F-Droid"
=> [PM-3153] fix image alt text error

src/App/Pages/Settings/BlockAutofillUrisPage.xaml
Removed back button from block autofill uris to be aligned to other Android views.
* **BlockAutofillUrlsPage:** Removed back button from navigation.
=> [PM-3249] Removed back button from block autofill uris

src/App/Pages/Settings/SettingsPage/SettingsPageViewModel.cs, src/Core/Services/StateService.cs
Android SSO Login wasn't working because of null auth pending request and access to secure storage.
Handle null argument exception thrown
=> [PM-3313] Fix Android SSO Login

src/App/Pages/Accounts/LoginApproveDeviceViewModel.cs, src/App/Pages/Accounts/LoginPasswordlessRequestPage.xaml, src/App/Pages/Accounts/LoginPasswordlessRequestViewModel.cs, src/App/Resources/AppResources.Designer.cs, src/App/Resources/AppResources.resx
Change labels and _Log in with device page_ UI tweaks.
=> [PM-3320][PM-3321] Fix labels and UI tweaks

src/App/Pages/Accounts/LoginApproveDevicePage.xaml, src/App/Pages/Accounts/LoginApproveDevicePage.xaml.cs, src/App/Pages/Accounts/LoginApproveDeviceViewModel.cs, src/iOS.Autofill/CredentialProviderViewController.cs, src/iOS.Extension/LoadingViewController.cs, src/iOS.ShareExtension/LoadingViewController.cs
Android: Tapping "Not you?" From the `decryption-options` screen sends user into a loop.
Instead of Popping the modal and go back, just call logout and send the user to the homepage.
=> [PM-3342] Not you button not working

src/App/Pages/Accounts/LockPage.xaml.cs, src/App/Pages/Accounts/LockPageViewModel.cs, src/App/Pages/Accounts/LoginApproveDevicePage.xaml.cs, src/App/Resources/AppResources.resx
After requesting approval from admin or other device, trying to approve device with Master Password will not work.
Add parameter to ignore pending requests check in `LockPage`
=> [PM-3319] Check for admin request in Lock page

src/App/Pages/Accounts/LoginPasswordlessRequestPage.xaml, src/App/Pages/Accounts/LoginPasswordlessRequestPage.xaml.cs, src/App/Pages/Accounts/LoginPasswordlessRequestViewModel.cs, src/App/Resources/AppResources.Designer.cs, src/App/Resources/AppResources.resx
Change header title based on auth request type.
PageTitle is set after AuthRequestType so the label changes accordingly. 
=> [PM-2289] Change header title based on auth request type

src/App/Pages/Accounts/LoginSsoPageViewModel.cs, src/Core/Services/AuthService.cs
When an admin auth request gets purged, ignore it and continue to Device Approval Options page.
Check for 404 api exceptions and return null.
=> [PM-3333] Check for purged admin auth requests

src/App/Resources/AppResources.Designer.cs, src/App/Resources/AppResources.resx
Fix copy for "_Login initiated_"
=> [PM-3357] Fix "Login initiated" copy

src/Core/Exceptions/UserAndMasterKeyNullException.cs, src/Core/Models/Request/PasswordlessLoginRequest.cs, src/Core/Services/AuthService.cs, src/Core/Services/CryptoService.cs
If the approval device had login without a password, it wouldn't be able to respond to auth requests.
There was some code missing for the auth requests response when the user didn't have a Master Password set.
https://github.com/bitwarden/mobile/assets/4648522/24353027-a147-4be0-a005-462d3a914151
=> [PM-3362] Fix auth request approval

.github/CODEOWNERS
Set up CODEOWNERS file for this repository with some initial assignees on some folders that can be easily set up without moving files.
* **CODEOWNERS:** File to set up code owners.
=> [PM-1768] Set up CODEOWNERS file

src/Core/Services/AuthService.cs
Fix bug where app fresh install would crash when a new user was login in with master password. 
=> Fix app fresh install login

src/App/Pages/Accounts/LockPageViewModel.cs, src/App/Services/BaseBiometricService.cs
Fix login with biometric after key migration.
Wrong validation was causing `BiometricEnabled` property never setting as true.
=> [PM-3303] Fix biometric login after key migration

src/App/Pages/Accounts/LockPageViewModel.cs, src/App/Pages/Accounts/TwoFactorPage.xaml.cs, src/App/Pages/Accounts/TwoFactorPageViewModel.cs
Fix SSO TDE login flow when the user has 2FA enabled.
Check for vault lock before navigating to the Lock Page on the 2FA Page.
=> [PM-3381] Fix TDE login 2FA flow

src/App/Pages/Accounts/TwoFactorPage.xaml.cs, src/App/Pages/Accounts/TwoFactorPageViewModel.cs
Fix TDE SSO login flows for users without a master password. 
Update code to match the logic in SSO Login Page
=> [PM-3381] Update login flows

src/Core/Services/UserVerificationService.cs
Fix MP reprompt vs OTP has master password hash check
* **UserVerificationService:** Fix has master password with master key hash check
=> [PM-3450] Fix MP reprompt vs OTP has master password hash check

.github/CODEOWNERS
Move files related to CrowdIn sync into a separate section.
=> CODEOWNERS: Create section for crowdin sync

src/iOS.Autofill/iOS.Autofill.csproj, src/iOS.Extension/iOS.Extension.csproj, src/iOS.ShareExtension/iOS.ShareExtension.csproj, src/iOS/iOS.csproj
Fix csproj configurations for "Release iPhoneSimulator" on iOS / Extensions
* **iOS.csproj:** Removed Watch app from "Release iPhoneSimulator" configuration
* **Extensions:** Fixed bundle signing
=> [PM-3508] Fix Release iPhoneSimulator configuration for iOS / Extensions

src/Core/Services/StateService.cs
encrypted pin wasn't being cleared on logout, resulting in pins persisting through logins.
=> [Pm-3523] pin not cleared

src/iOS.Core/Controllers/BaseLockPasswordViewController.cs
Extension code was not updated for the user to be able to unlock with biometrics using new UserKey model.
Set user key after biometric is valid.
https://github.com/bitwarden/mobile/assets/4648522/264e2619-da43-4e13-afa9-9b8ff16060e7
=> [PM-3545] Fix biometric unlock for autofill

src/Core/Services/VaultTimeoutService.cs
Fix account status in the account switcher.
Move condition to be evaluated and condition the set of the userkey. 
=> [PM-3547] Lock/unlock statuses are not displayed correctly on Mobile in the account switcher

src/Android/MainApplication.cs, src/App/Services/MobilePasswordRepromptService.cs, src/Core/Abstractions/ICryptoService.cs, src/Core/Services/CryptoService.cs, src/iOS.Core/Utilities/iOSCoreHelpers.cs
Fix 2 bugs on password re-prompt. On autofill and editing a cipher, the app would crash.
Update code to use userkey.
=> [PM-3543] [PM-3607] Fix password re-prompt when editing and on autofill.

src/App/Pages/Settings/AppearanceSettingsPage.xaml, src/App/Resources/AppResources.Designer.cs, src/App/Resources/AppResources.resx
Fix default dark theme verbiage
* **AppearancePage:** Fix default dark theme verbiage
=> [PM-3845] Fix default dark theme verbiage

.github/CODEOWNERS
Make `dept-development-mobile` the default code owner.
=> Make dept mobile default CODEOWNER

src/App/Pages/Settings/VaultSettingsPageViewModel.cs, src/Core/ExternalLinksConstants.cs
Fix import link
* Updated import items link
=> [PM-3834] Fix import items link

src/Core/Abstractions/IApiService.cs, src/Core/Services/ApiService.cs
Currently mobile is using deprecated API endpoints, PreLogin and Register. Change these to use Identity.
Change send method to have the option to use Identity has base url.
=> [PM-3893] Migrate to identity for prelogin & register

src/App/Resources/AppResources.Designer.cs, src/App/Resources/AppResources.resx
Remove hyphen from clip-board string resource
=> [PM-4138] Remove hyphen from clip-board string resource

src/Core/Services/ConfigService.cs
Fix `ConfigService` exception bug when StatusCode is null.
Add null check
=> [PM-2915] Fix config service null error bug

src/App/Resources/AppResources.Designer.cs, src/App/Resources/AppResources.resx
Removed strings resources marked as DEPRECATED
=> [PM-2658] Removed deprecated strings resources.

src/Core/Enums/DeviceType.cs
Remove unused DeviceTypeExtensions
=> [PM-3532] Remove unused DeviceTypeExtensions

src/App/Pages/Settings/OtherSettingsPage.xaml
This PR adds some missing IDs for the new Other Settings view
* **OtherSettingsPage.xaml:** Adding missing AutomationIDs
=> Adding missing ids

.github/workflows/crowdin-pull.yml, .github/workflows/release.yml, .github/workflows/version-bump.yml, .github/workflows/workflow-linter.yml
```
```
This PR updates all of our action versions to reference `main` instead of `master`.
=> All workflows - Update 'master' to 'main' for any actions in the gh-actions repository

.github/workflows/build.yml, .github/workflows/crowdin-pull.yml, .github/workflows/release.yml, .github/workflows/stale-bot.yml, .github/workflows/version-bump.yml
```
```
Update workflows to point to `main`
- **.github/workflows/*:** Change all relevant references of internal `master` branches to `main`
=> Point workflows to `main`

src/Core/Services/ApiService.cs
To match server changes (pm-1247), we need to update the SSO url on mobile.
Replace "account" with "sso"
=> [PM-5542] Update SSO endpoint

src/iOS.Core/Renderers/CollectionView/ExtendedGroupableItemsViewController.cs
Fix app crash on iOS due to an iOS CollectionView bug. Ignoring exception to collect more data, as of now it is very hard to  reproduce.
This will help reducing errors from: https://github.com/bitwarden/mobile/issues/2478 
Ignore ArgumentOutOfRangeException and let the app continue execution. Since this is at startup, the bug must be happening on an empty state or a transition state and recover after the error. 
=> [PM-5633] iOS app crashing on startup

.github/CODEOWNERS
=> Fix code ownership

src/App/Pages/Settings/AboutSettingsPage.xaml, src/App/Pages/Settings/AboutSettingsPageViewModel.cs, src/App/Resources/AppResources.Designer.cs, src/App/Resources/AppResources.resx, src/Core/ExternalLinksConstants.cs
Added link to privacy policy on About screen, and removed support contact
=> [PM-5863] Add privacy policy link to about screen

.github/CODEOWNERS
This PR updates the `CODEOWNERS` file so that our Version Bump automation can automatically approve and merge PRs related to new versions.
* **.github/CODEOWNERS:** Add lines for the files that are modified while using the Version Bump automation
=> Add files to CODEOWNERS for Version Bump automation

src/App/Pages/Settings/LoginPasswordlessRequestsListPage.xaml
In pending login requests the "No pending requests" is visible even when there are requests available.
Bind label visibility to vm property
=> [PM-5856] No pending requests is visible

.github/workflows/build.yml
```
```
This PR adds the build number as a GitHub step summary for the Build workflow.
- **.github/workflows/build.yml:** Add build number to GitHub step summary.
=> Add Build Number as Step Summary for Build workflow

src/Core/Pages/Accounts/EnvironmentPage.xaml, src/Core/Pages/Settings/AboutSettingsPageViewModel.cs
Removed MAUI label from environment and about pages
=> [PM-6209] Removed MAUI label from environment and about pages

.github/workflows/version-auto-bump.yml
```
```
This PR should fix the Version Auto Bump workflow for automatically bumping the Mobile version after release.
- **.github/workflows/version-auto-bump.yml:** Switch to calling the `Version Bump` workflow from the `gh` cli tool.
=> Fix auto version bump workflow

src/Core/Utilities/ThemeManager.cs
Fix Android build UT Failing because of precompiler directives.
=> Fix Android build UT Failing because of precompiler directives.

.github/CODEOWNERS
This PR updates the paths in `CODEOWNERS` to the files needed by the Version Bump automation.
* **.github/CODEOWNERS:** Update paths to where files were moved when the MAUI PR was merged in.
=> Update CODEOWNERS file for Version Bump automation

.github/workflows/version-bump.yml
This PR adds the missing `xmllint` install step.
* **.github/workflows/version-bump.yml:** Add `xmllint` install step.
=> Version Bump workflow - Add xmllint install step

crowdin.yml
Fix path for CrowdIn resources
* **crowdin.yml:** Change to new res path
=> Fix resource path for CrowdIn

.github/workflows/build-beta.yml
* **.github/workflows/build-beta.yml:** Adds Stub
=> Add stub for DEVOPS-1822

src/Core/Services/Fido2AuthenticatorService.cs, test/Core.Test/Services/Fido2AuthenticatorGetAssertionTests.cs
The server only needs to be updated if we have changed the counter. New passkeys that leave their counters at zero can therefore skip this step.
=> Optimize assertion network calls

store/google/Publisher/Publisher.csproj
Update Publisher.csproj to go back to net 3.1 to see if that fixes the build
* **Publisher.csproj:** Go back to net 3.1 to see if that fixes the build
=> Update Publisher.csproj to go back to net 3.1 to see if that fixes the build

.github/workflows/build.yml
Update build.yml to go back to net3.1 Publisher
* **build.yml:** Updated path to Net 3.1 Publisher
=> Update build.yml to go back to net3.1 Publisher

Directory.Build.props
Updates MAUI to the future SR2 MAUI release version. This was previously done in `feature/maui-migration-passkeys` but wasn't changed in `main`.
=> [PM-6480] Update MAUI to 8.0.7

.github/workflows/build.yml, store/google/Publisher/Publisher.csproj
This PR fixes the signing issue for Android builds.
* **.github/workflows/build.yml:** Formatting. Remove .NET 3.1. Comment out testing.
* **store/google/Publisher/Publisher.csproj:** Move project to .NET 8.
=> DEVOPS-1834 - Apply fix for signing issue

src/App/Platforms/Android/AndroidManifest.xml, src/App/Platforms/iOS/Info.plist, src/iOS.Autofill/Info.plist, src/iOS.Extension/Info.plist, src/iOS.ShareExtension/Info.plist
```
```
This PR updates the `Mobile` project to the proper version for the upcoming release.
=> Change version to proper value

.github/CODEOWNERS
The localization files got moved from `src/App/Resources` to `src/Core/Resources/Localization`a while ago and this updates the path to ownership for the Crowdin PRs.
=> [CODEOWNERS] Update ownership of translations

.github/workflows/build.yml
This PR fixes the download location of the `GoogleService-Info.plist` file.  It also has some formatting updates to the workflow.
* **.github/workflows/build.yml:** Download the `GoogleService-Info.plist` file to the `src/watchOS/bitwarden` directory.
=> DEVOPS-1848 - Fix GoogleService-Info.plist file location

src/iOS.Autofill/LoginListViewController.cs, src/iOS.Autofill/LoginListViewController.designer.cs, src/iOS.Autofill/MainInterface.storyboard
Remove header on Save passkey as new login
Remove header on Save passkey as new login
=> [PM-6474] Remove header on Save passkey as new login

.github/workflows/build.yml
This PR fixes the F-Droid signing process.
* **.github/workflows/build.yml:** Update steps so that the F-Droid APK is signed properly.
=> DEVOPS-1866 - Fix F-Droid Signing

src/iOS.Autofill/ListItems/HeaderItemView.cs, src/iOS.Autofill/LoginListViewController.cs, src/iOS.Autofill/LoginSearchViewController.cs, src/iOS.Core/Controllers/ExtendedUITableViewCell.cs, src/iOS.Core/Models/CipherViewModel.cs, src/iOS.Core/Views/CipherLoginTableViewCell.cs, src/iOS.Core/Views/ExtensionTableSource.cs, src/iOS.Extension/LoginListViewController.cs
Improved iOS extensions cipher cell UI to support passkeys
* **CipherLoginTableViewCell:** New Cell with the updated UI for cipher login / passkeys
* **ExtensionTableSource:** Updated it to use new cell and also to calculate the header and fill the cell correctly
* **Other:** Updated code to use new cells / table source
=> [PM-6496] Improved iOS extensions cipher cell UI

.github/workflows/build.yml
This PR adds logic to display the incremented versions in the GitHub Step Summary area of the workflow run.  This is very helpful for releasing the proper builds and not having to dive into the run to find the correct version code.
* **.github/workflows/build.yml:** Update logic to display incremented versions in the GitHub Step Summary.
=> Add version codes to GitHub step summary

src/Core/Services/UserVerification/UserVerificationMediatorService.cs
Fix attempts on passkeys User verification to be 5 instead of 6
* **UserVerificationMediatorService:** Changed how the addition is done so the attempts are maximum 5 instead of 6.
=> [PM-6706] Fix 5 attempts on passkeys User verification

src/Core/Pages/Settings/AutofillPage.xaml, src/Core/Resources/Localization/AppResources.Designer.cs, src/Core/Resources/Localization/AppResources.resx
Updated autofill settings copy
=> [PM-6793] Updated autofill settings copy

src/Core/Models/View/LoginView.cs, src/Core/Resources/Localization/AppResources.Designer.cs, src/Core/Resources/Localization/AppResources.resx, src/Core/Utilities/StringExtensions.cs, src/iOS.Core/Utilities/ASHelpers.cs
Add username empty fallback on passkey
Added the fallback value to the username and moved a bit the logic so it can be shared on Android as well.
=> [PM-6655] Add username empty fallback on passkey

src/Core/Services/Fido2ClientService.cs, src/Core/Utilities/Fido2/Extensions/Fido2CreateCredentialExtensionsParams.cs, src/Core/Utilities/Fido2/Extensions/Fido2CreateCredentialExtensionsResult.cs, src/Core/Utilities/Fido2/Extensions/Fido2CredPropsResult.cs, src/Core/Utilities/Fido2/Fido2AuthenticatorMakeCredentialParams.cs, src/Core/Utilities/Fido2/Fido2ClientCreateCredentialParams.cs, src/Core/Utilities/Fido2/Fido2ClientCreateCredentialResult.cs, test/Core.Test/Services/Fido2ClientCreateCredentialTests.cs
Add support for `credProps.rk`
=> [PM-7257] Add support for `credProps.rk` extension

.github/CODEOWNERS
=> [PM-7309] Removed build.cake from Platform team ownership

src/App/Platforms/Android/Autofill/CredentialHelpers.cs
Fix incorrect passkey used when more than one passkey available for the same RP.
When "PasskeyA" and "PasskeyB" were being displayed for the same RP and the user selected "PasskeyA" it was being logged with "PasskeyB".
* **CredentialHelpers:** Change the `PendingIntent.GetActivity` to have a unique request code for each credential entry so the extras are not overridden by the last one.
=> [PM-7379] Fix incorrect passkey used because creating the PendingIntent wrongly

src/Core/Pages/Vault/GroupingsPage/GroupingsPageViewModel.cs, src/Core/Resources/Localization/AppResources.Designer.cs, src/Core/Resources/Localization/AppResources.resx
Self-hosted migration will be postponed, message updated with the new date.
=> [PM-7407] Updates the self-host release date in the unassigned items alert message

src/Core/Utilities/TaskExtensions.cs, src/iOS.Autofill/LoginListViewController.cs
Avoid logging Fido2AuthenticatorException so not to clutter the logging tool
=> [PM-5154] Avoid logging Fido2AuthenticatorException

src/App/Platforms/Android/Autofill/CredentialHelpers.cs, src/Core/App.xaml.cs
Fix UV not being performed on Fido2 credential creation Android
* **App.xaml.cs:** Update the flag on `Options` for successive `OnCreate` calls of `MainActivity`
=> [PM-7365] Fix UV not being performed on Fido2 credential creation Android

src/Core/Pages/Accounts/TwoFactorPage.xaml.cs
Fix app crashing after Master Password approval on TDE SSO login with MFA.
Add missing AppOptions to `LoginApproveDevicePage` navigation.
=> [PM-7869] App crashing after Master Password approval on SSO login with MFA

src/Core/Pages/Accounts/LockPage.xaml.cs, src/Core/Pages/Accounts/LoginApproveDevicePage.xaml.cs, src/Core/Pages/Accounts/LoginPage.xaml.cs, src/Core/Pages/Accounts/LoginPasswordlessRequestPage.xaml.cs, src/Core/Pages/Accounts/SetPasswordPage.xaml.cs, src/Core/Pages/Accounts/TwoFactorPage.xaml.cs
Fix null check to _appOptions to avoid NRE
* **all:** Added `_appOptions` null check before setting their properties
=> [PM-7855] Fix null check to AppOptions to avoid NRE

src/Core/Pages/Accounts/LockPageViewModel.cs
Add loading dialog when unlocking with PIN
* **LockPageViewModel:** Added loading dialog when unlocking with PIN and logging exceptions.
=> [PM-7877] Added loading dialog when unlocking with PIN

src/App/Platforms/Android/AndroidManifest.xml, src/App/Platforms/iOS/Info.plist, src/iOS.Autofill/Info.plist, src/iOS.Extension/Info.plist, src/iOS.ShareExtension/Info.plist
This reverts commit 1f966e6cbe771fa57aa3880bad8f7f942d4cf793.
Revert version bump to `2024.5.1`.
=> Revert "Bumped version to 2024.5.1 (#3217)"

.github/workflows/version-bump.yml
```
```
Add a new parameter to whether to send a notification for upcoming releases, which must be disabled by default.
Related PR: https://github.com/bitwarden/devops/pull/2329
* **.github/workflows/version-bump.yml:** Add new input
- If making database changes - make sure you also update Entity Framework queries and/or migrations
=> BRE-87 Add Slack notification enable feature and check in version-bump workflow

.github/workflows/release.yml
https://bitwarden.atlassian.net/browse/BRE-94
Replace `dawidd6/action-download-artifact` with `bitwarden/gh-actions/download-artifacts`.
* **.github/workflows/release.yml:** Replace `dawidd6/action-download-artifact` with `bitwarden/gh-actions/download-artifacts`.
=> [BRE-94] Replace `dawidd6/action-download-artifact` with `bitwarden/gh-actions/download-artifacts`

src/Core/Services/CipherService.cs
=> [PM-8392] Enables the Cipher Key Encryption preprocessor define

src/Core/Abstractions/IApiService.cs, src/Core/Abstractions/ICipherService.cs, src/Core/Abstractions/IStateService.cs, src/Core/Constants.cs, src/Core/Models/AppOptions.cs, src/Core/Pages/Accounts/LockPage.xaml.cs, src/Core/Pages/Accounts/LoginApproveDevicePage.xaml.cs, src/Core/Pages/Accounts/LoginPage.xaml.cs, src/Core/Pages/Accounts/LoginPasswordlessRequestPage.xaml.cs, src/Core/Pages/Accounts/SetPasswordPage.xaml.cs, src/Core/Pages/Accounts/TwoFactorPage.xaml.cs, src/Core/Pages/TabsPage.cs, src/Core/Pages/Vault/GroupingsPage/GroupingsPage.xaml.cs, src/Core/Pages/Vault/GroupingsPage/GroupingsPageViewModel.cs, src/Core/Resources/Localization/AppResources.Designer.cs, src/Core/Resources/Localization/AppResources.resx, src/Core/Services/ApiService.cs, src/Core/Services/CipherService.cs, src/Core/Services/StateService.cs
Remove unassigned items banner feature flag and related logic.
* Reverted changes related to Unassigned items banner feature flag + logic.
=> [AC-2788] Remove unassigned items feature flag and logic

src/Core/Resources/Localization/AppResources.Designer.cs, src/Core/Resources/Localization/AppResources.resx
Updates "Bitwarden Help Center" -> "Bitwarden help center" to match the sentence casing of the other options on the About screen.
* **AppResources.resx:** Change Bitwarden Help Center to sentence case.
=> [PM-9043] BIT-2356: Update casing of Bitwarden Help Center string

.github/workflows/scan.yml, app/build.gradle.kts, build.gradle.kts, gradle/libs.versions.toml
Internal change.
Sets up SARIF output for Checkmarx scans so we can see results in GitHub and adds SonarCloud. …
=> Additional scanning

app/build.gradle.kts
Internal change.
Adds better wildcarding of test paths as they'll live amongst the source files. …
=> Adjust Sonar scan paths

.github/workflows/test.yml
Internal change.
Reference the correct coverage report name. …
=> Use proper coverage report

app/src/test/java/com/x8bit/bitwarden/data/platform/manager/event/OrganizationEventManagerTest.kt, app/src/test/java/com/x8bit/bitwarden/data/vault/datasource/network/model/CipherJsonRequestUtil.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt
N/A
This PR cleans up a few detekt issues that slipped into the app. …
=> Clean up some detekt issues

.github/workflows/build.yml
https://bitwarden.atlassian.net/browse/PM-8985
Trigger the build workflow when commits are pushed to main branch. …
=> [PM-8985] Trigger build job on push events to main

.github/workflows/build.yml, fastlane/Fastfile
https://bitwarden.atlassian.net/browse/PM-8985
Fetch all tags during build job checkout so that they are available to calculate the correct version name. …
=> [PM-8985] Fetch all tags when checking out repo for build job

.github/ISSUE_TEMPLATE/bug.yml, README.md
https://bitwarden.atlassian.net/browse/PM-9340
Guides users to create Bitwarden prod (.NET MAUI) bugs in their respective repos. …
=> [PM-9340] Updates the bug template and readme to direct users to the right repos

fastlane/Fastfile
PM-8985
Automatic publishing will create drafts in the "internal" track. …
=> [PM-8985] Publish beta builds to internal track

.github/ISSUE_TEMPLATE/bug.yml
https://bitwarden.atlassian.net/browse/PM-9340
GitHub templates don't link links in labels, removing it!
- …
=> [PM-9340] Fix template syntax error

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/config.yml
https://bitwarden.atlassian.net/browse/PM-9340
Slight adjust to our bug template and adds a new link to the Issues list. …
=> [PM-9340] Improve Bug template and adds a config link

.github/workflows/build.yml
Builds will be distributed to Firebase automatically on push events to main.
- ❌ (`:x:`) or …
=> Distribute builds to Firebase on push events to main

app/src/main/java/com/x8bit/bitwarden/data/autofill/processor/AutofillProcessorImpl.kt, app/src/test/java/com/x8bit/bitwarden/data/autofill/processor/AutofillProcessorTest.kt
PM-9081
This PR addresses an issue where autofill would not display any options, this occurred because the `scope` used to process autofill requests would be cancelled and then no no requests could ever be processed. …
=> PM-9081: Should cancel the job not the scope when managing autofill requests

fastlane/Fastfile
Include Livefront tester group in Firebase disitrbutions. …
=> Include Livefront in Firebase distributions

app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/item/util/CipherViewExtensionsTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/verificationcode/VerificationCodeViewModelTest.kt
N/A
This PR cleans up some detekt issues in the app. …
=> Clean up some minor detekt issues

.github/workflows/build.yml
Upload F-Droid Beta artifacts to GitHub artifacts during build job. …
=> Upload F-Droid Beta artifacts to GitHub

app/build.gradle.kts
Internal change.
Excludes tests from Sonar as a recommended best practice. …
=> Exclude tests from Sonar

app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemScreenTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModelTest.kt
N/A
Fixes misc. detekt issues that were overlooked by build checks. …
=> Resolve detekt issues

fastlane/Fastfile
N/A
This PR replaces the `detektStandardDebug` command in fastlane to `detekt` in order to cover more of the app (other variants and tests).
- 🎨 …
=> Update the detekt command for fastlane to cover more of the app

app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/deleteaccount/DeleteAccountViewModelTest.kt
Fix detekt issues that were not detekted previously. …
=> Fix detekt issues

gradle/libs.versions.toml
N/A
This PR updates the app to use AGP 8.5.1 (current latest).
[Release notes!](https://developer.android.com/build/releases/gradle-plugin)
- 🎨 …
=> Update to AGP 8.5.1

app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/processor/Fido2ProviderProcessorImpl.kt
N/A
If a cancellation signal is reiceived while processing a FIDO 2 credential create request the Job will be cancelled, if active, instead of the coroutine scope. …
=> Cancel FIDO 2 registration job when cancellation occurs

app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/manager/Fido2CredentialManager.kt, app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/manager/Fido2CredentialManagerImpl.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/handlers/VaultItemListingUserVerificationHandlers.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingScreenTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
[PM-9684](https://bitwarden.atlassian.net/browse/PM-9684)
If the user's vault is unlocked, they have no lock screen on their device, and they have a master password but no PIN or biometrics, then prompt them to authenticate with their password.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/7ffb6e48-4724-440d-bcf7-751327f65464" /> | <video src="https://github.com/user-attachments/assets/281bcfa6-ecbc-4a8c-ad17-cb8cec3778e6" /> |
- Updated any necessary documentation or …
=> PM-9684: Verify with master password on item listing

app/src/debug/AndroidManifest.xml, app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/di/Fido2ProviderModule.kt, app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/manager/Fido2CredentialManager.kt, app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/manager/Fido2CredentialManagerImpl.kt, app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/model/PasskeyAssertionOptions.kt, app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/model/PasskeyAttestationOptions.kt, app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/model/PublicKeyCredentialDescriptor.kt, app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/model/PublicKeyCredentialRequestOptions.kt, app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/processor/Fido2ProviderProcessorImpl.kt, app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/sdk/VaultSdkSource.kt, app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/sdk/VaultSdkSourceImpl.kt, app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/sdk/model/Fido2CredentialSearchUserInterfaceImpl.kt, app/src/main/java/com/x8bit/bitwarden/data/vault/repository/VaultRepository.kt, app/src/main/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryImpl.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/manager/intent/IntentManager.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/manager/intent/IntentManagerImpl.kt, app/src/main/res/values/strings.xml, app/src/test/java/com/x8bit/bitwarden/data/autofill/fido2/manager/Fido2CredentialManagerTest.kt, app/src/test/java/com/x8bit/bitwarden/data/autofill/fido2/processor/Fido2ProviderProcessorTest.kt, app/src/test/java/com/x8bit/bitwarden/data/vault/datasource/sdk/VaultSdkSourceTest.kt, app/src/test/java/com/x8bit/bitwarden/data/vault/datasource/sdk/model/Fido2CredentialViewUtil.kt, app/src/test/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/util/PasskeyAssertionOptionsTestHelpers.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/util/PasskeyAttestationOptionsTestHelpers.kt
[PM-9408](https://bitwarden.atlassian.net/browse/PM-9408)
Display the bottom sheet with options to ether unlock the vault or select the correct passkey when attempting to authenticate with passkeys.
Unlock the vault if locked:
<video width="400px" src="https://github.com/bitwarden/android/assets/125921730/bbb7871e-3de0-4d3c-8b02-963b1fdcb271" />
Select a passkey from the vault if unlocked (note: selecting the item does not yet autofill the credentials as that will be a separate ticket):
<video width="400px" src="https://github.com/bitwarden/android/assets/125921730/ddd7b177-3baf-4db7-b86c-e3a2529f3e74" />
- Used internationalization (i18n) …
=> PM-9408: Show bottom sheet with passkey options

app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/manager/Fido2CredentialManager.kt, app/src/main/java/com/x8bit/bitwarden/data/autofill/fido2/manager/Fido2CredentialManagerImpl.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt, app/src/test/java/com/x8bit/bitwarden/data/autofill/fido2/manager/Fido2CredentialManagerTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditScreenTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
[PM-9684](https://bitwarden.atlassian.net/browse/PM-9684)
If the user's vault is unlocked, they have no lock screen on their device, and they have a master password but no PIN or biometrics, then prompt them to authenticate with their password.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/324cf40e-85d4-47ce-92cb-f25997759e47" /> | <video src="https://github.com/user-attachments/assets/0658cd32-cd69-48dd-ba4b-45313a08e0b8" /> |
- Updated any necessary documentation or …
=> PM-9684: Verify with master password on add edit view

app/src/main/java/com/x8bit/bitwarden/data/autofill/parser/AutofillParserImpl.kt, app/src/test/java/com/x8bit/bitwarden/data/autofill/parser/AutofillParserTests.kt
N/A
This PR updates the `AutofillParser` to return a fillable response if any field is fillable.
- ❌ …
=> Provide autofill response data even if focused field is not fillable

app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
This is a small refactor of some of the Login common code, the end goal of [PM-9532](https://bitwarden.atlassian.net/browse/PM-9532) will be to propagate any non API (read SDK) errors that can occur in the login flow (such as unlocking the vault). The change here moves all the unlock vault code to the top of the call stack in the `handleLoginCommonSuccess` function. 
The goal of this PR is to isolate this logic reordering to allow for regression testing without any other changes related to propagating the error message.
[PM-9532]: https://bitwarden.atlassian.net/browse/PM-9532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PM-9532 pt. 1 small refactor of login success steps

app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dialog/BitwardenPinDialog.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditScreenTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt
[PM-9682](https://bitwarden.atlassian.net/browse/PM-9682)
If the user's vault is unlocked, their device has no lock screen configured, and they have a Bitwarden PIN configured, allow them to authenticate with their PIN when saving a passkey on the vault add edit view.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/6af9ead6-e206-4833-8fba-b68685a2e9ef" /> | <video src="https://github.com/user-attachments/assets/5df5e553-8873-466b-a6c5-c14783a0c997" /> |
- Updated any …
=> PM-9682: Verify with PIN on add edit view

app/src/main/java/com/x8bit/bitwarden/data/platform/util/SpecialCharacterStringComparator.kt, app/src/main/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryImpl.kt, app/src/main/java/com/x8bit/bitwarden/data/vault/repository/util/VaultSdkCipherExtensions.kt, app/src/main/java/com/x8bit/bitwarden/data/vault/repository/util/VaultSdkCollectionExtensions.kt, app/src/main/java/com/x8bit/bitwarden/data/vault/repository/util/VaultSdkFolderExtensions.kt, app/src/main/java/com/x8bit/bitwarden/data/vault/repository/util/VaultSdkSendExtensions.kt, app/src/test/java/com/x8bit/bitwarden/data/vault/repository/util/VaultSdkCipherExtensionsTest.kt, app/src/test/java/com/x8bit/bitwarden/data/vault/repository/util/VaultSdkCollectionExtensionsTest.kt, app/src/test/java/com/x8bit/bitwarden/data/vault/repository/util/VaultSdkFolderExtensionsTest.kt, app/src/test/java/com/x8bit/bitwarden/data/vault/repository/util/VaultSdkSendExtensionsTest.kt
https://bitwarden.atlassian.net/browse/PM-9927
Items starting with special chars should be sorted to the top of the list for vault items, this is how it exists on iOS and other clients.
| before | after |
| ![9927before](https://github.com/user-attachments/assets/a5474e05-878a-45bf-a14f-723fac3528a6) | ![9927after](https://github.com/user-attachments/assets/08ed8bde-dfed-4288-86d3-82c572b08958) |  …
=> [PM-9927] Sort order update

app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/PinInputDialog.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingScreenTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
[PM-9681](https://bitwarden.atlassian.net/browse/PM-9681)
If the user is trying to save or select a passkey with their vault unlocked, a device with no lock screen, and no PIN or password, prompt them to set up a Bitwarden PIN before saving or selecting the passkey on the item listing view.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/8bfd3cfd-59e0-43bc-90be-8e8878aaf30c" /> | <video src="https://github.com/user-attachments/assets/76ef5363-07da-4a0b-a649-1302ece700b6" /> | …
=> PM-9681: Setup Bitwarden PIN

app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditScreenTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt
[PM-9681](https://bitwarden.atlassian.net/browse/PM-9681)
If the user is trying to save or select a passkey with their vault unlocked, a device with no lock screen, and no PIN or password, prompt them to set up a Bitwarden PIN before saving or selecting the passkey on the add edit view.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/6794bc0a-d681-4aec-9807-12af388410ed" /> | <video src="https://github.com/user-attachments/assets/ad15b488-7774-4478-8f28-abcdf2f2129c" /> |
- …
=> PM-9681: Setup Bitwarden PIN on add edit view

app/src/main/java/com/x8bit/bitwarden/data/autofill/di/AutofillModule.kt
[PM-10140](https://bitwarden.atlassian.net/browse/PM-10140)
This PR updates the various helper classes for autofill to be singletons. …
=> PM-10140: Update Autofill classes to be singletons

app/src/main/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryImpl.kt, app/src/main/java/com/x8bit/bitwarden/data/vault/repository/di/VaultRepositoryModule.kt, app/src/test/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt
N/A
This PR removes an unused `Json` class from the `VaultRepository`. …
=> Remove unused Json object from VaultRepository

app/build.gradle.kts
PM-10440
This pull requests fixes the size difference between beta and release variants by enabling minification on beta build variants.
- 🎨 (`:art:`) …
=> [PM-10440] Enable minification on beta build variants

.github/workflows/build.yml, fastlane/Fastfile
PM-9472
Update the format of generated release notes for artifacts distributed to Firebase.
The new format is as follows:
```
{commit_message}
{repository_name}/{branch_name} @ {commit-hash}
{github-action-url}
``` …
=> [PM-9472] Update release notes generated for Firebase

app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/util/SendDataExtensions.kt, app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/send/util/SendDataExtensionsTest.kt
PM-9927
Sort Sends alphabetically, and give special characters precedence so they are displayed at the top of lists. …
=> [PM-9927] Sort Sends alphabetically

app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/network/core/ResultCall.kt
N/A
This PR cleans up the `ResultCall` class with formatting and organizational improvements.
- ❌ (`:x:`) …
=> Minor formatting and clean up for ResultCall

app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/FlagKey.kt
[PM-10241](https://bitwarden.atlassian.net/browse/PM-10241)
This PR adds a feature flag for the Onboarding Carousel feature flag.
Note that the flag is not yet used in this PR. …
=> PM-10241: Add the onboarding carousel feature flag

gradle.properties
N/A
This PR removes a suppression form the `gradle.properties` file that is not longer needed.
- ❌ (`:x:`) …
=> Remove a suppression from gradle properties that is no longer needed

app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/sdk/VaultSdkSourceImpl.kt
N/A
This PR applies some minor formatting and clean up to the `VaultSdkSourceImpl`. …
=> Minor formating for the VaultSdkSource

app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/FlagKey.kt
N/A
This PR adds the feature flag for the forthcoming onboarding feature.
Note that the new flag is not yet used. …
=> Add onboarding feature flag

app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupUnlockScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/welcome/WelcomeScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/base/util/ModifierExtensions.kt
N/A
This PR adds a helper method to `Modifier` for maintaining a consistent margin throughout the app.
- ❌ …
=> Add helper method for standardizing margins

app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/auth/AuthNavigation.kt, app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/masterpasswordguidance/MasterPasswordGuidanceScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/preventaccountlockout/PreventAccountLockoutNavigation.kt, app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/preventaccountlockout/PreventAccountLockoutScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/preventaccountlockout/PreventAccountLockoutViewModel.kt, app/src/main/res/values/strings.xml, app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/preventaccountlockout/PreventAccountLockoutScreenTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/preventaccountlockout/PreventAccountLockoutViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-10620
Draw screen for the preventing account logout tips.
[figma link](https://www.figma.com/design/MSaj0DpjVEqCONBcV4WnKD/Bitwarden-Android-Mobile-App-Reskin---V2-(onboarding)?node-id=67412-73121&t=vfBs7OmnOjmoGGQg-4)
| Compose Preview |
|--------|
| ![image](https://github.com/user-attachments/assets/c7ebeb25-bf0e-492f-b3ac-b184def17578) | 
- 📝 (`:memo:`) or …
=> PM-10620 prevent account lockout tips screen

app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockViewModel.kt
[PM-10874](https://bitwarden.atlassian.net/browse/PM-10874)
Ensure the user is automatically prompted for biometrics on the vault unlock screen if it's enabled. Since the event is apparently sent before the screen is active, the event needs to be marked as a `BackgroundEvent`.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/95d8e034-88d6-4b36-ad8e-1123ca761cde" /> | <video src="https://github.com/user-attachments/assets/eac02872-dfb4-407e-b058-05f44692af2b" /> |
- Updated …
=> PM-10874: Fix biometrics auto-prompt

app/src/test/java/com/x8bit/bitwarden/AuthCallbackViewModelTest.kt
N/A
This PR addresses a failing test that was missed in CI initially. …
=> Fix a failing test

Dangerfile
N/A
This PR removes the dangerfile which is no longer used. The code that required this file was removed [here](https://github.com/bitwarden/android/pull/3363). …
=> Remove unused dangerfile

gradle/libs.versions.toml
N/A
This PR updates the AGP version from 8.5.1 to 8.5.2.
[Release notes!](https://developer.android.com/build/releases/gradle-plugin) …
=> Update to AGP 8.5.2

app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/sdk/AuthSdkSourceImpl.kt, app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/sdk/BaseSdkSource.kt, app/src/main/java/com/x8bit/bitwarden/data/tools/generator/datasource/sdk/GeneratorSdkSourceImpl.kt, app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/sdk/VaultSdkSourceImpl.kt
N/A
This PR adds logging to debug build for failing SDK interactions. The goal is to help us track bug when interacting with the SDK better.
- 🎨 …
=> Add logging for SDK functionality in debug only

.github/workflows/build.yml
https://bitwarden.atlassian.net/browse/PM-10282
Update build artifact names …
=> [PM-10282] Update build artifact names

app/src/main/res/values/public_suffix_list.xml, scripts/public_suffix_list.dat
https://bitwarden.atlassian.net/browse/PM-2126
Pulls the latest from the public suffix list for use.
- ❌ …
=> Update public suffix list

app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/FlagKey.kt
[PM-11223](https://bitwarden.atlassian.net/browse/PM-11223)
This PR enabled the remote configuration for the Email Verification feature.
- 🎨 (`:art:`) …
=> PM-11223: Enable remote confg for email verification feature

app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/network/util/HeaderUtils.kt, app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/network/interceptor/HeadersInterceptorTest.kt
[PM-11236](https://bitwarden.atlassian.net/browse/PM-11236)
This PR adds the build type and the build flavor to the user-agent. …
=> PM-11236: Add build type and flavor to the user agent

app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt, app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt
[PM-11254](https://bitwarden.atlassian.net/browse/PM-11254)
This PR adds the logic for logging in with Key Connector.
<video src="https://github.com/user-attachments/assets/5ec49636-95bc-4fd0-b1c0-32afbe9f2a06" width="300" /> …
=> PM-11254: Add logic for logging in with Key Connector

app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
N/A
This PR applies some minor clean up to the login common helper methods by providing a specific profile to those methods. …
=> Simplify common login helper methods

app/src/main/AndroidManifest.xml, app/src/main/java/com/x8bit/bitwarden/data/auth/util/CompleteRegistrationDataUtils.kt
https://bitwarden.atlassian.net/browse/PM-6702
Change email verification AppLink handling to a new redirect-connector path.
https://github.com/user-attachments/assets/ad0557e2-dde7-4e3d-bac4-e4f5f766eb9d …
=> [PM-6702] AppLink new redirect path

app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt, app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/landing/LandingViewModel.kt, app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/startregistration/StartRegistrationScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/startregistration/StartRegistrationViewModel.kt, app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/completeregistration/CompleteRegistrationScreenTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/startregistration/StartRegistrationViewModelTest.kt
N/A
This PR cleans up the code by applying the formatting and addressing a weird import. …
=> Minor formatting an import cleanup

app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockViewModel.kt
N/A
This PR simplifies the check for a manual unlock mechanism in the `VaultUnlockViewModel` by using the helper method. …
=> Simplify manual unlock check

app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/welcome/WelcomeScreen.kt
N/A
This PR fixes a minor UI bug where the login button should be full width.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/51889f0d-e8f1-42c0-ab94-2d39ec7e7182" width="300" /> | <img src="https://github.com/user-attachments/assets/b875456c-dbc3-4f03-ab03-3328ab6a3a1a" width="300" /> |
- ❓ …
=> Carousel buttons should be full width

app/src/main/java/com/x8bit/bitwarden/data/auth/util/CompleteRegistrationDataUtils.kt
https://bitwarden.atlassian.net/browse/PM-11394
- allow the app to sanitize the `redirect-connector` links as intended.
- May unblock email verification. …
=> PM-11394 String parse issue with app link

app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/di/AccessibilityModule.kt, app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/manager/AccessibilityAutofillManager.kt, app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/manager/AccessibilityAutofillManagerImpl.kt, app/src/main/java/com/x8bit/bitwarden/data/tiles/BitwardenAutofillTileService.kt, app/src/test/java/com/x8bit/bitwarden/data/autofill/manager/AccessibilityAutofillManagerTest.kt
N/A
This PR contain no functional changes and simply moves the `accessibility` package into the `autofill` package for better organization moving forward. …
=> Relocate the accessibility package into the autofill package

app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/auth/AuthNavigation.kt, app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/expiredregistrationlink/ExpiredRegistrationLinkNavigation.kt, app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/expiredregistrationlink/ExpiredRegistrationLinkScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/expiredregistrationlink/ExpiredRegistrationLinkViewModel.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavViewModel.kt, app/src/main/res/values/strings.xml, app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/expiredregistrationlink/ExpiredRegistrationLinkScreenTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/expiredregistrationlink/ExpiredRegistrationLinkViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavScreenTest.kt
https://bitwarden.atlassian.net/browse/PM-11479
- Build UI layer for the expired registration email link screen. …
=> PM-11479 Expired link UI

gradle/libs.versions.toml
N/A
This PR updates the Kotlin Immutable collections library to the latest version (v0.3.8).
[Release Notes!](https://github.com/Kotlin/kotlinx.collections.immutable/releases) …
=> Update immutable collection to v0.3.8

bridge/README.md, bridge/build.gradle.kts
https://livefront.atlassian.net/browse/BITAU-165
Add kotlinx serialization as a dependency and update README. 
N/A …
=> BITAU-165 add kotlinx serialization dependency to bridge

app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuViewModel.kt
N/A
This PR simplifies the way we add feature flags to the debug menu. The only thing required now, is to add the flag to the `activeFlags` list.
- 🎨 …
=> Simplify adding flags to debug menu

gradle/libs.versions.toml
N/A
This PR updates the app to use the latest version of AGP (v8.6.0).
- 🎨 …
=> Update to AGP 8.6.0

bridge/README.md, bridge/build.gradle.kts
https://livefront.atlassian.net/browse/BITAU-168
Setup test dependencies for the Bridge SDK.
N/A
- ❌ …
=> BITAU-168 Add Bridge SDK test dependencies

app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupAutofillScreen.kt
https://bitwarden.atlassian.net/browse/PM-10845
- implement the landscape design when device is in in landscape orientation …
=> PM-10845 add landscape layout for setup auto-fill

app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/parser/AccessibilityParserImpl.kt, app/src/main/java/com/x8bit/bitwarden/data/platform/util/StringExtensions.kt, app/src/test/java/com/x8bit/bitwarden/data/autofill/accessibility/parser/AccessibilityParserTest.kt, app/src/test/java/com/x8bit/bitwarden/data/util/StringExtensionsTest.kt
N/A
This PR updates the Url parsing logic to inject a valid protocol if none is present. …
=> Add logic to ensure url has a valid https protocol

app/build.gradle.kts
N/A
This PR bumps the version name `2024.09.00`. …
=> Bump version name to 2024.09.00

gradle/libs.versions.toml
N/A
Update to app to use the latest AGP (v8.6.1).
This update requires Android Studio Koala Feature Drop | 2024.1.2 Patch 1 or higher …
=> Update APG to 8.6.1

app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/auth/AuthNavigation.kt, app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/login/LoginScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/login/LoginViewModel.kt, app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/trusteddevice/TrustedDeviceEncryptionNavigation.kt, app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginNavigation.kt, app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginViewModel.kt, app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/login/LoginViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginViewModelTest.kt
N/A
Moves the process of encoding and decoding a password (required for navigation) to the `TwoFactorLoginNavigation` file. …
=> Password encoding and decoding handing in TwoFactorLoginNavigation

app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/startregistration/StartRegistrationScreen.kt, app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/startregistration/StartRegistrationScreenTest.kt
https://bitwarden.atlassian.net/browse/PM-10616
- change the copy back to the value thats in the design
- ❌ …
=> PM-10616 update copy to match design

gradle/libs.versions.toml
N/A
This PR updates the app to use the latest version of Junit (5.11.1).
[Release Notes!](https://junit.org/junit5/docs/5.11.1/release-notes/#release-notes-5.11.1) …
=> Update to Junit 5.11.1

app/src/main/java/com/x8bit/bitwarden/ui/platform/theme/BitwardenTheme.kt
[PM-12322](https://bitwarden.atlassian.net/browse/PM-12322)
This PR exposes the `BitwardenColorScheme` to the app via the `BitwardenTheme`.
No functional changes were made in this PR. …
=> PM-12322: Add bitwarden color scheme to BitwardenTheme

gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties
N/A
This PR updates the Android Gradle Plugin (v8.7.0) and the Gradle Wrapper (v8.10.2) to their latest versions.
Release Notes:
* [AGP](https://developer.android.com/build/releases/gradle-plugin#android-gradle-plugin-8.7.0)
* [Gradle](https://docs.gradle.org/8.10.2/release-notes.html)
- 🤔 …
=> Update the Android Gradle Plugin and the Gradle Wrapper

app/src/main/res/values/strings.xml, app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupAutofillScreenTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillScreenTest.kt
https://bitwarden.atlassian.net/browse/PM-10630 
&
https://bitwarden.atlassian.net/browse/PM-10632
- Update copy to be more general on completion page.
- Update copy to remove "-" from Autofill.
issue and …
=> PM-10632 update the copy on setup complete

gradle/libs.versions.toml
N/A
This PR update Junit to the latest version (5.11.2).
[Release Notes!](https://junit.org/junit5/docs/current/release-notes/index.html#release-notes-5.11.2) …
=> Update to Junit 5.11.2

app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/masterpasswordgenerator/MasterPasswordGeneratorScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/snackbar/BitwardenSnackbarHost.kt, app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreen.kt
N/A
This PR creates a custom wrapper around the `SnackbarHost` for easier styling. …
=> Add a bitwarden styles snackbar

app/src/main/java/com/x8bit/bitwarden/ui/platform/components/appbar/action/BitwardenOverflowActionItem.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/card/BitwardenActionCard.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/card/BitwardenActionCardSmall.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/card/BitwardenInfoCalloutCard.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dialog/BitwardenBasicDialog.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dialog/BitwardenDateSelectButton.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dialog/BitwardenLoadingDialog.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dialog/BitwardenMasterPasswordDialog.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dialog/BitwardenPinDialog.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dialog/BitwardenSelectionDialog.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dialog/BitwardenTextEntryDialog.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dialog/BitwardenTimePickerDialog.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dialog/BitwardenTwoButtonDialog.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/snackbar/BitwardenSnackbarHost.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/theme/BitwardenTheme.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/theme/shape/BitwardenShapes.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/theme/shape/Shapes.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/util/CipherViewExtensions.kt
N/A
This PR adds shapes to the BitwardenTheme this will help maintain consistency in the UI.
- ❌ (`:x:`) or …
=> Add shapes to the BitwardenTheme

gradle/libs.versions.toml
N/A
This PR updates the Android Gradle Plugin to the latest version (8.7.1).
Release Notes!
- ❌ (`:x:`) or …
=> AGP update v8.7.1

gradle/libs.versions.toml
N/A
This PR updates Turbine to the latest version (1.2.0).
[Release Notes!](https://github.com/cashapp/turbine/releases/tag/1.2.0) …
=> Update Turbine to 1.2.0

.github/workflows/crowdin-pull.yml
- [Card](https://bitwarden.atlassian.net/browse/BRE-372) …
=> [BRE-372] - Clean up document start

app/src/test/java/com/x8bit/bitwarden/MainViewModelTest.kt
N/A
This PR cleans up the `MainViewModelTest` making it easier to maintain going forward. …
=> Create single helper method to clean up the MainViewModelTest

authenticatorbridge/src/test/java/com/bitwarden/authenticatorbridge/util/EncryptionUtilTest.kt
N/A
This PR fixes a failing test in the authenticator bridge module. …
=> Fix authenticator test

app/src/main/java/com/x8bit/bitwarden/data/auth/repository/util/UserStateJsonExtensions.kt, app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/checkemail/CheckEmailScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/content/ObscuredContent.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/toggle/BitwardenUnlockWithBiometricsSwitch.kt, app/src/test/java/com/x8bit/bitwarden/data/auth/repository/util/UserStateJsonExtensionsTest.kt, app/src/test/java/com/x8bit/bitwarden/data/autofill/fido2/processor/Fido2ProviderProcessorTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/accountsetup/SetupUnlockViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/landing/LandingViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/login/LoginViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/removepassword/RemovePasswordViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/trusteddevice/TrustedDeviceViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/welcome/WelcomeViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/deleteaccount/DeleteAccountViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/exportvault/ExportVaultViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/util/CipherViewExtensionsTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/attachments/AttachmentsViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/importlogins/ImportLoginsScreenTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/importlogins/ImportLoginsViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/movetoorganization/VaultMoveToOrganizationViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/movetoorganization/util/VaultMoveToOrganizationExtensionsTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/vault/util/UserStateExtensionsTest.kt
N/A
This PR applies the formatter to the entire app. …
=> Apply the formatter to the entire app

gradle/libs.versions.toml
N/A
This PR updates the Junit 5 library to the latest version (5.11.3).
[Release Notes!](https://junit.org/junit5/docs/5.11.3/release-notes/#release-notes-5.11.3) …
=> Update Junit 5 (5.11.3)

gradle/libs.versions.toml
N/A
This PR updates the Compose BOM and the AndroidX Activity library to their latest versions.
Release Notes:
* [Compose BOM (2024.10.0)](https://developer.android.com/develop/ui/compose/bom/bom-mapping)
* [Androidx Activity (1.9.3)](https://developer.android.com/jetpack/androidx/releases/activity#1.9.3) …
=> Update Compose BOM and Androidx activity libs

app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/masterpasswordgenerator/MasterPasswordGeneratorScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/button/BitwardenOutlinedButton.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/button/BitwardenOutlinedButtonWithIcon.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/button/color/BitwardenButtonColors.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/snackbar/BitwardenSnackbar.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/snackbar/BitwardenSnackbarHost.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/snackbar/BitwardenSnackbarHostState.kt, app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreen.kt
https://bitwarden.atlassian.net/browse/PM-13943
- Support custom snackbar UI to match the most extreme of the new snackbar designs. …
=> PM-13943 : PT1 Custom snackbar UI

app/src/main/java/com/x8bit/bitwarden/ui/platform/components/fab/BitwardenFloatingActionButton.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/theme/shape/BitwardenShapes.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/theme/shape/Shapes.kt
N/A
This PR updates the FAB to match v3 designs.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/734a3f4b-ff47-4fc5-b49a-280472fb829b" width="300" /> | <img src="https://github.com/user-attachments/assets/0f5fc3e5-8779-4990-91b8-9f732365aa35" width="300" /> |
- …
=> Update fab design

app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/movetoorganization/VaultMoveToOrganizationContent.kt
=> QA-957: Adding missing testTag for collection list container

.github/workflows/build.yml, fastlane/Fastfile
https://bitwarden.atlassian.net/browse/PM-14224
Starts publishing the production build variant to Play Store.  …
=> [PM-14224] Automate Play Store prod variant publishing

app/src/standard/java/com/x8bit/bitwarden/data/platform/manager/LogsManagerImpl.kt
https://bitwarden.atlassian.net/browse/PM-14241
Merge the hotfix branch containing the crash logs fix into the main branch …
=> [PM-14241] Backport Timber hotfix

app/src/beta/res/xml/shortcuts.xml
https://bitwarden.atlassian.net/browse/PM-13155
- Fix shortcuts not working for beta build by adding /beta/.../shortcuts.xml with beta version app ID
- …
=> PM-13155 add shortcuts file to beta source set for beta app id

gradle/libs.versions.toml
N/A
This PR updates the app to the latest version of AGP (8.7.2)
- 🎨 …
=> Update to AGP 8.7.2

app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/disk/VaultDiskSourceImpl.kt, app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/disk/dao/DomainsDao.kt
see #4227 
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 …
=> PM-14433 update flow type to nullable so we can handle gracefully and avoid crash.

app/src/main/java/com/x8bit/bitwarden/ui/platform/manager/intent/IntentManagerImpl.kt
[PM-14480](https://bitwarden.atlassian.net/browse/PM-14480)
This PR updates the `IntentManager` to check for the `androidapp` scheme and attempt to launch the app if possible.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/0973c77f-1d88-4159-a884-776a23447921" width="300" /> | <video src="https://github.com/user-attachments/assets/77daec24-41bb-4274-9c0f-5870ac3a989b" width="300" /> | …
=> PM-14480: Update IntentManager to be able to launch apps

app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/importlogins/ImportLoginsScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/importlogins/components/ImportLoginsInstructionStep.kt, app/src/main/res/values/strings.xml, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/importlogins/ImportLoginsScreenTest.kt
https://bitwarden.atlassian.net/browse/PM-14621
- Update copy per design updates …
=> PM-14621 update the copy for step three instruction and cta button

app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorViewModel.kt, app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/handlers/PasswordHandlers.kt, app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreenTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorViewModelTest.kt
Fixing a couple of small typos
=> Fix typos in generator actions

app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/welcome/WelcomeScreen.kt, app/src/main/res/values/strings.xml
https://bitwarden.atlassian.net/browse/PM-12761
- The focus/touch targets for the visual page indicator rows were misaligned. This was due to the their size + spacing being smaller than the minimum touch target implicitly applied.
- After talking with design the conclusion was to remove the touch target from accessibility as it is meant to be a visual indicator and not a primary navigation component for the pager content.
- Improve the existing accessibility on the pager content so its more indicative what page the user with a screen reader is on.
- Communicated to …
=> PM-12761 Talkback UI Focus misalignment bug.

app/src/main/java/com/x8bit/bitwarden/data/platform/util/JsonExtensions.kt, app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/disk/VaultDiskSourceImpl.kt
N/A
This PR adds non-fatal logging to deserialization errors that occur when pulling data from the vault database. …
=> Log vault deserialization errors

app/src/main/java/com/x8bit/bitwarden/data/platform/repository/EnvironmentRepositoryImpl.kt
N/A
This PR updates the environment flow to be a shared flow to avoid delays in initialization and also provide an accurate default value.
- 🎨 (`:art:`) …
=> Share the environment flow and provide better default

app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/startregistration/StartRegistrationScreen.kt
N/A
This PR removes an unused constant from the app. …
=> Remove unused constant

app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginViewModel.kt, app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-15022
- After the user either taps the key to the device or presses the button while attached via USB, attempt login.
Required for any UI changes; delete if not applicable. Use fixed width images for better display. --> …
=> PM-15022 Auto login when user completes a YubiKey login trigger.

app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/SendViewModel.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModel.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/verificationcode/VerificationCodeViewModel.kt, app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/send/SendViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/verificationcode/VerificationCodeViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-15412
- Don't force sync on PTR invokations …
=> PM-15412 🍒 Pull-to-refresh operations should not invoke a forced sync.

.github/workflows/crowdin-push.yml, .github/workflows/github-release.yml, .github/workflows/release-branch.yml
- https://bitwarden.atlassian.net/browse/BRE-443
- Updating worklfows to pass `bwwl lint` before deployment …
=> [BRE-443] - Fix bwwl Linting pre Deployment

gradle/libs.versions.toml
N/A
This PR updates AGP to the latest version (v8.7.3).
[Release Notes!](https://developer.android.com/build/releases/gradle-plugin#android-gradle-plugin-8.7.0) …
=> Update to latest AGP

gradle/libs.versions.toml
N/A
This PR update the Dagger Hilt library to the latest version (v2.53).
[Release Notes!](https://github.com/google/dagger/releases/tag/dagger-2.53)
- …
=> Update Dagger Hilt library

.github/ISSUE_TEMPLATE/config.yml
https://bitwarden.atlassian.net/browse/PM-15583
Adds Autofill failure report form to GitHub issues menu
- ❌ …
=> [PM-15583] chore: Adds Autofill failure report form to GitHub issues menu

app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/other/OtherScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/other/OtherViewModel.kt, app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/SendViewModel.kt, app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendViewModel.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModel.kt, app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/other/OtherViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/send/SendViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModelTest.kt
(cherry picked from commit 7b7c2da67c1a0edb4636223737266128bff7ed3d)
https://bitwarden.atlassian.net/browse/PM-15624
- Cherry pick into hotfix branch
- …
=> PM-15624 🍒 Align handling of no network states with iOS app. (#4431)

app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/importlogins/ImportLoginsScreen.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/importlogins/ImportLoginsScreenTest.kt
PM-15037
- Use correct resource to match figma. …
=> PM-15037 Correct the text for the confirm error dialog on import logins screen

app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt, app/src/main/java/com/x8bit/bitwarden/data/auth/repository/model/LoginResult.kt, app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/network/util/NetworkUtils.kt, app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/enterprisesignon/EnterpriseSignOnViewModel.kt, app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/login/LoginViewModel.kt, app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/loginwithdevice/LoginWithDeviceViewModel.kt, app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginViewModel.kt, app/src/main/res/values/strings.xml, app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt, app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/network/util/NetworkUtilsTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/enterprisesignon/EnterpriseSignOnViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/login/LoginViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/loginwithdevice/LoginWithDeviceViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-15890
- When there is an SSL related network error inform the user. …
=> PM-15890  TLS related error propagation

.github/CODEOWNERS
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 …
=> Add Phil to CODEOWNERS

app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt, app/src/main/java/com/x8bit/bitwarden/data/auth/repository/model/LoginResult.kt, app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/network/util/NetworkUtils.kt, app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/enterprisesignon/EnterpriseSignOnViewModel.kt, app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/login/LoginViewModel.kt, app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/loginwithdevice/LoginWithDeviceViewModel.kt, app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginViewModel.kt, app/src/main/res/values/strings.xml, app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt, app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/network/util/NetworkUtilsTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/enterprisesignon/EnterpriseSignOnViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/login/LoginViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/loginwithdevice/LoginWithDeviceViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginViewModelTest.kt
(cherry picked from commit e565a5a118de0a43d22b5743bf31de35150d376b)
[PM-15890 ](https://bitwarden.atlassian.net/browse/PM-15890)
- Propagate the CertPath error and display and informative dialog to user. …
=> PM-15890 🍒  TLS related error propagation

app/src/main/assets/fido2_privileged_community.json
Fix the alphabetical order originally proposed in the FIDO2 community list …
=> [PM-15912] Fix alphabetical order in FIDO2 privileged browser community list

README.md, app/build.gradle.kts, app/src/fdroid/java/com/x8bit/bitwarden/ui/platform/manager/review/AppReviewManagerImpl.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/composition/LocalManagerProvider.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/manager/review/AppReviewManager.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/manager/review/AppReviewManagerImpl.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModel.kt, app/src/main/res/values/strings.xml, app/src/standard/java/com/x8bit/bitwarden/ui/platform/manager/review/AppReviewManagerImpl.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultScreenTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultViewModelTest.kt, gradle/libs.versions.toml
https://bitwarden.atlassian.net/browse/PM-15381
https://bitwarden.atlassian.net/browse/PM-15383
- When the user is on the vault screen and has met the criteria for prompting for review (3 qualifying actions, auto fill/accessibility on) and the flag is on after 3 seconds prmpt for review
- shows a toast in debug mode for ease of testing.
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general …
=> PM-15383 PM-15381 - Show the google play review prompt

.github/workflows/build.yml, scripts/update_app_ci_build_info.sh
PM-15176
Update the script path for updating the app CI build info to the correct location.
- ❌ (`:x:`) or …
=> [PM-15176] Update script path for CI build info

.github/workflows/test.yml
[PM-16827](https://bitwarden.atlassian.net/browse/PM-16827)
1. Fixes sdk package retrieval by bringing back the github token env var removed in https://github.com/bitwarden/android/pull/4488
2. Split test job to reduce the GitHub Token permissions surface in each job, scoping it to packages access only for gradle
3. Adds a comment to the PR when code coverage report upload fails. [Example](https://github.com/bitwarden/android/pull/4538#issuecomment-2580778503)
> [!IMPORTANT]
> About 3., while testing the initial changes I noticed that when the codecov action fails, it's a silent error by design and won't fail the workflow job. This is the case if the coverage report can't be found for instance. Discussing it with @SaintPatrck we agreed that uploading code coverage reports shouldn't block …
=> [PM-16827] Fix test.yml sdk package access and refactor test jobs

app/src/main/res/values/strings.xml
`Backport:` https://github.com/bitwarden/android/pull/4544 …
=> [PM-16808] Add question mark to copy (#4544)

gradle/libs.versions.toml
N/A
This PR updates the AGP plugin to the latest version (v8.8.0).
- 🎨 …
=> Update AGP to v8.8.0

app/src/main/res/xml/network_security_config.xml
PM-17119
Adds Bitwarden domains to network config HTTPS rules. Migrates https://github.com/bitwarden/mobile/pull/2738, thanks @AChep! …
=> [PM-17119] Add domains to network config

app/src/main/java/com/x8bit/bitwarden/ui/platform/composition/LocalManagerProvider.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavScreen.kt, gradle/libs.versions.toml
N/A
this PR updates the AndroidX Activity library to the latest version (v1.10.0).
[Release Notes!](https://developer.android.com/jetpack/androidx/releases/activity#1.10.0) …
=> Update the AndroidX Activity library to 1.10.0

app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/login/LoginScreen.kt
N/A
This PR fixes one last test tag for the automation team. …
=> Fix the login test tag

app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/completeregistration/CompleteRegistrationScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/createaccount/CreateAccountScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/removepassword/RemovePasswordScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/resetpassword/ResetPasswordScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/setpassword/SetPasswordScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dialog/BitwardenMasterPasswordDialog.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dialog/BitwardenPinDialog.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenHiddenPasswordField.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenPasswordField.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenPasswordFieldWithActions.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenTextField.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/exportvault/ExportVaultScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendContent.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditCardItems.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditLoginItems.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditSshKeyItems.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemLoginContent.kt
N/A
This PR is a cherry-pick from main to fix some of the automation tests.
Original PR: https://github.com/bitwarden/android/pull/4621
- 🎨 (`:art:`) …
=> Update BitwardenPasswordField TestTags

authenticatorbridge/README.md
N/A
This PR fixes some minor formatting issues in the Authenticator Bridge Readme file. …
=> Fix minor formatting issues in Authenticator Bridge Readme

app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/base/util/ModifierExtensions.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dialog/BitwardenDateSelectButton.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dialog/BitwardenTimeSelectButton.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dropdown/BitwardenMultiSelectButton.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenHiddenPasswordField.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenPasswordField.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenTextField.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/listitem/BitwardenGroupItem.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/listitem/BitwardenListItem.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/row/BitwardenTextRow.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/segment/BitwardenSegmentedButton.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/slider/BitwardenSlider.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/toggle/BitwardenSwitch.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/SettingsScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/pendingrequests/PendingRequestsScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/passwordhistory/PasswordHistoryListItem.kt, app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendContent.kt, app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendDeletionDateChooser.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditCustomField.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/attachments/AttachmentsContent.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemAttachmentContent.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/verificationcode/VerificationCodeItem.kt
N/A
This PR updates the app to use simpler modifier extensions to make the code more readable.
- ❌ (`:x:`) …
=> Simplify modifier extensions

app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/appearance/AppearanceScreen.kt, app/src/main/res/values/strings.xml, app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/appearance/AppearanceScreenTest.kt
[PM-17958](https://bitwarden.atlassian.net/browse/PM-17958)
This PR updates the copy on the appearance screen.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/49d8c76d-df49-4128-96e4-f16727e8367a" width="300" /> | <img src="https://github.com/user-attachments/assets/a516635f-9ad1-41d7-a515-ff8a5cfcbff6" width="300" /> | …
=> PM-17958: Update appearance text

.github/workflows/scan-ci.yml, .github/workflows/scan.yml
https://bitwarden.atlassian.net/browse/VULN-193
This is to enable SonarQube scanning in PRs, and not just the main/master branches. …
=> Enabled SonarQube scanning for PRs

app/src/main/assets/fido2_privileged_community.json, app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/util/BrowserUtil.kt, app/src/main/res/xml/autofill_service_configuration.xml
The DivestOS project ended. Its browsers are not maintained anymore.
https://divestos.org/pages/news#end
Disable these browsers as trusted browsers for security, they're not updated anymore and therefore insecure …
=> [PM-16862] FIDO2 Community: Remove DivestOS-developed browsers

app/src/main/java/com/x8bit/bitwarden/ui/platform/components/account/BitwardenAccountSwitcher.kt
[PM-17847](https://bitwarden.atlassian.net/browse/PM-17847)
- Update text style as designed.
- ❌ (`:x:`) or …
=> PM-17847 update text style for add account label

app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/welcome/WelcomeScreen.kt
=> QA-1061: Adding testTags for new WelcomePage

app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorViewModel.kt, app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreenTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorViewModelTest.kt
[PM-17848](https://bitwarden.atlassian.net/browse/PM-17848)
- Change copy on action button from "Select" to "Save" on generator modal. …
=> PM-17848 update copy on generator modal

app/src/main/java/com/x8bit/bitwarden/ui/platform/base/util/StringResExtensions.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/text/BitwardenHyperTextLink.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/theme/type/BitwardenTypography.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/theme/type/Typography.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/util/SpanStyleUtil.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemCardContent.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemIdentityContent.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemLoginContent.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemSecureNoteContent.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemSshKeyContent.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModel.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/component/ItemNameField.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/component/VaultItemCustomField.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/component/VaultItemUpdateText.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/util/CipherViewExtensions.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/manualcodeentry/ManualCodeEntryScreen.kt, app/src/main/res/values/strings.xml, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemScreenTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/item/util/VaultItemTestUtil.kt
[PM-18013](https://bitwarden.atlassian.net/browse/PM-18013)
This PR updates the contents of the View Item Screen to reflect the V3 designs
| --- | --- |
| <img src="https://github.com/user-attachments/assets/ea9947f8-7bae-4fab-bd48-f7ad821b18bb" width="300" /> | <img src="https://github.com/user-attachments/assets/7aaef76a-a6f6-4866-90a4-9b995aac0f74" width="300" /> |
- 📝 (`:memo:`) …
=> PM-18013: Update the View Item screens

fastlane/Fastfile
[PM-16534](https://bitwarden.atlassian.net/browse/PM-16534)
Monorepo prep, will prevent tasks in unrelated modules from executing. …
=> [PM-16534] Update gradle invocations to specify app module

app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepository.kt, app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt, app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/removepassword/RemovePasswordScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/resetpassword/ResetPasswordNavigation.kt, app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/resetpassword/ResetPasswordScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/resetpassword/ResetPasswordViewModel.kt, app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/vaultunlock/VaultUnlockScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/appbar/action/BitwardenOverflowActionItem.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dialog/BitwardenClientCertificateInfoDialog.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dialog/BitwardenMasterPasswordDialog.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/dialog/BitwardenPinDialog.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/field/BitwardenPasswordField.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/exportvault/ExportVaultScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/exportvault/ExportVaultViewModel.kt, app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendContent.kt, app/src/main/res/values/strings.xml, app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/resetPassword/ResetPasswordScreenTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/resetPassword/ResetPasswordViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/exportvault/ExportVaultScreenTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/exportvault/ExportVaultViewModelTest.kt
[PM-18123](https://bitwarden.atlassian.net/browse/PM-18123)
- Update the UI and actions to match new design and functionality
https://github.com/user-attachments/assets/8acc7bb9-5184-457b-8902-04a2b5d9ebb5 …
=> PM-18123 Update the reset password screen.

app/src/main/java/com/x8bit/bitwarden/ui/platform/components/appbar/BitwardenTopAppBar.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/bottomsheet/BitwardenModalBottomSheet.kt
N/A
This PR fixes a minor typo in the `BitwardenTopAppBar`. …
=> Fix minor typo

.github/workflows/build-authenticator.yml, .github/workflows/crowdin-pull-authenticator.yml, .github/workflows/crowdin-push-authenticator.yml, .github/workflows/scan-authenticator.yml, .github/workflows/test-authenticator.yml
PM-18384
Adds empty GitHub Workflows so we can test the Authenticator files ahead of time.
- ❌ (`:x:`) or …
=> [PM-18384] Add placeholder workflows for the Authenticator

gradle/libs.versions.toml
N/A
This PR updates the Android Gradle Plugin to the latest version (8.8.1). …
=> Update to gradle plugin 8.8.1

app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingScreenTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
[PM-18370](https://bitwarden.atlassian.net/browse/PM-18370)
This PR allows users to select the type of cipher to add from the collection list screen.
- …
=> PM-18370: Allow selecting type of cipher to add from collection list

app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingScreenTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
[PM-18421](https://bitwarden.atlassian.net/browse/PM-18421)
- Exclude the "Folder" option from the selection list within the folder view when adding a new item. …
=> PM-18421 Remove adding a folder option from within folder view.

gradle/libs.versions.toml
N/A
This PR updates the Compose BOM to the latest version (2025.02.00).
[Release Notes!](https://developer.android.com/develop/ui/compose/bom/bom-mapping) …
=> Update Compose BOM to 2025.02.00

gradle/libs.versions.toml
N/A
This PR updates hilt to the latest version (v2.55).
[Release Notes!](https://github.com/google/dagger/releases/tag/dagger-2.55) …
=> Update hilt v2.55

gradle/libs.versions.toml
N/A
This PR updates Kotlin and ksp to the latest versions.
Release Notes:
* [Kotlin 2.1.10](https://github.com/JetBrains/kotlin/releases/tag/v2.1.10)
* [ksp 2.1.10-1.0.30](https://github.com/google/ksp/releases/tag/2.1.10-1.0.30) …
=> Update Kotlin and ksp to latest versions

.github/ISSUE_TEMPLATE/bug-bwa.yml
PM-18651
Add an issue template for Bitwarden Authenticator issues ahead of the mono repo transition. 
- ❌ …
=> [PM-18651] Add Bitwarden Authenticator issue template and update existing bug template

.checkmarx/config.yml, .github/renovate.json, .gitignore
PM-16534
Updates remaining files ahead of moving the authenticator app.  …
=> [PM-16534] Monorepo prep - Update checkmarx, renovate and gitignore

.github/ISSUE_TEMPLATE/config.yml, .github/PULL_REQUEST_TEMPLATE.md, SECURITY.md
PM-18655
Update common files to the latest version in our template. …
=> [PM-18655] sync with bitwarden/template 

app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginViewModel.kt, app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-8223
PR to RC of https://github.com/bitwarden/android/pull/4772
- …
=> [PM-8223]  new device verification ux improvements RC

.editorconfig
This commit updates the `.editorconfig` file to streamline its focus.
It removes C# specific settings and configurations for project/config files.
It now includes configurations for Kotlin and common file types like JSON and YML.
Adds Kotlin-specific rules to enforce trailing commas on declaration and call sites for improved readability and maintainability. …
=> Refactor .editorconfig to focus on Kotlin and common file types

gradle/libs.versions.toml
N/A
This PR updates AGP to the latest version (8.8.2). …
=> Update AGP to 8.8.2

gradle/libs.versions.toml
N/A
Update junit5 from 5.11.3 to 5.11.4
[Release notes!](https://junit.org/junit5/docs/5.11.4/release-notes/) …
=> [deps] Update junit5 to 5.11.4

app/build.gradle.kts, authenticator/build.gradle.kts, gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties
N/A
This PR updates AGP and gradle to the latest versions (8.9.0 and 8.13). …
=> Update to AGP 8.9.0

gradle/libs.versions.toml
N/A
This PR updates the AndroidX Activity library to the latest version (1.10.1). …
=> Update AndroidX Activity to 1.10.1

app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavScreenTest.kt
N/A
This PR updates the `RootNavScreenTest` to be simpler and using standard practices. …
=> Simplify RootNavScreenTest

app/src/main/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryImpl.kt, app/src/main/java/com/x8bit/bitwarden/data/vault/repository/model/CreateSendResult.kt, app/src/main/java/com/x8bit/bitwarden/data/vault/repository/model/DeleteSendResult.kt, app/src/main/java/com/x8bit/bitwarden/data/vault/repository/model/RemovePasswordSendResult.kt, app/src/main/java/com/x8bit/bitwarden/data/vault/repository/model/UpdateSendResult.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/search/SearchScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/search/SearchViewModel.kt, app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/SendScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/SendViewModel.kt, app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendViewModel.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt, app/src/test/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/search/SearchViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/send/SendViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-19243
- Propagate send related result errors to the UI. …
=> PM-19243 send result errors propagated to UI

app/src/main/java/com/x8bit/bitwarden/data/tools/generator/repository/GeneratorRepositoryImpl.kt, app/src/main/java/com/x8bit/bitwarden/data/tools/generator/repository/model/GeneratedCatchAllUsernameResult.kt, app/src/main/java/com/x8bit/bitwarden/data/tools/generator/repository/model/GeneratedForwardedServiceUsernameResult.kt, app/src/main/java/com/x8bit/bitwarden/data/tools/generator/repository/model/GeneratedPassphraseResult.kt, app/src/main/java/com/x8bit/bitwarden/data/tools/generator/repository/model/GeneratedPasswordResult.kt, app/src/main/java/com/x8bit/bitwarden/data/tools/generator/repository/model/GeneratedPlusAddressedUsernameResult.kt, app/src/main/java/com/x8bit/bitwarden/data/tools/generator/repository/model/GeneratedRandomWordUsernameResult.kt, app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/masterpasswordgenerator/MasterPasswordGeneratorViewModel.kt, app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorViewModel.kt, app/src/test/java/com/x8bit/bitwarden/data/tools/generator/repository/GeneratorRepositoryTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/masterpasswordgenerator/MasterPasswordGeneratorViewModelTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-19335
- Add caught throwables to the generator results to be in line with other result error types. …
=> PM-19335 add throwable val to generator error results

app/src/main/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryImpl.kt, app/src/test/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt
[PM-19389](https://bitwarden.atlassian.net/browse/PM-19389)
This PR updates the Biometric Key migration encoding logic to occur before attempting to login. This ensures that we know the user is in a position to be migrated to a more secure biometric configuration before unlocking the vault.
- 📝 (`:memo:`) or …
=> PM-19389: Handle encoding error when migrating biometric key

.github/workflows/scan-authenticator.yml, .github/workflows/scan-ci.yml, .github/workflows/scan.yml
https://bitwarden.atlassian.net/browse/VULN-226
Add correct ref/sha reference for main and PR branches, since codeql/upload-sarif doesn't handle pull_request_target properly. …
=> Fix SARIF upload branch ref/sha

app/build.gradle.kts, authenticator/build.gradle.kts, authenticatorbridge/build.gradle.kts, gradle/libs.versions.toml
N/A
This PR updates JUnit to the latest version (5.12.1).
In addition to the update, I also migrated the app to use the JUnit BOM and added the platform launcher dependency, which is required for continued usage.
[Release Notes!](https://junit.org/junit5/docs/snapshot/release-notes/#release-notes-5.12.1)
- 📝 …
=> Update to Junit 5.12.1

app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/FlagKey.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/components/FeatureFlagListItems.kt, app/src/main/res/values/strings_non_localized.xml, app/src/test/java/com/x8bit/bitwarden/data/platform/manager/FlagKeyTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuViewModelTest.kt
[PM-19543](https://bitwarden.atlassian.net/browse/PM-19543)
This PR adds the feature flag for controlling the flight recorder. …
=> PM-19543: Add flight recorder feature flag

authenticatorbridge/src/main/java/com/bitwarden/authenticatorbridge/manager/AuthenticatorBridgeManager.kt, authenticatorbridge/src/main/java/com/bitwarden/authenticatorbridge/manager/AuthenticatorBridgeManagerImpl.kt, authenticatorbridge/src/main/java/com/bitwarden/authenticatorbridge/manager/model/AccountSyncState.kt, authenticatorbridge/src/main/java/com/bitwarden/authenticatorbridge/model/SharedAccountData.kt, authenticatorbridge/src/main/java/com/bitwarden/authenticatorbridge/model/SharedAccountDataJson.kt, authenticatorbridge/src/main/java/com/bitwarden/authenticatorbridge/util/EncryptionUtils.kt, authenticatorbridge/src/test/java/com/bitwarden/authenticatorbridge/manager/AuthenticatorBridgeManagerTest.kt, authenticatorbridge/src/test/java/com/bitwarden/authenticatorbridge/manager/util/AuthenticatorBridgeConnectionTypeExtensionsTest.kt, authenticatorbridge/src/test/java/com/bitwarden/authenticatorbridge/util/EncryptionUtilTest.kt
N/A
Fix formatting issues identified by detekt in the `authenticatorbridge` module. …
=> Run detekt on `authenticatorbridge` module

authenticatorbridge/src/test/java/com/bitwarden/authenticatorbridge/util/EncryptionUtilTest.kt, authenticatorbridge/src/test/java/com/bitwarden/authenticatorbridge/util/TestAuthenticatorBridgeCallbackProvider.kt
N/A
Fix detekt issues in the `authenticator` test suite. …
=> Fix detekt issues in `authenticator` tests

gradle/libs.versions.toml
N/A
This PR update the app to use the latest version of AGP (8.9.1). …
=> Update to AGP 8.9.1

app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/network/service/PushService.kt, app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/network/service/PushServiceImpl.kt, app/src/main/java/com/x8bit/bitwarden/data/platform/manager/PushManagerImpl.kt, app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/network/service/PushServiceTest.kt, app/src/test/java/com/x8bit/bitwarden/data/platform/manager/PushManagerTest.kt, network/src/main/kotlin/com/bitwarden/network/api/PushApi.kt, network/src/main/kotlin/com/bitwarden/network/model/PushTokenRequest.kt
PM-19849
Move PushApi to the `network` module and update all references to use the new location. …
=> [PM-19849] Move PushApi and PushTokenRequest to network module

app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/service/DevicesService.kt, app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/service/DevicesServiceImpl.kt, app/src/test/java/com/x8bit/bitwarden/data/auth/datasource/network/service/DevicesServiceTest.kt, app/src/test/java/com/x8bit/bitwarden/data/auth/manager/TrustedDeviceManagerTests.kt, network/src/main/kotlin/com/bitwarden/network/api/AuthenticatedDevicesApi.kt, network/src/main/kotlin/com/bitwarden/network/model/TrustedDeviceKeysRequestJson.kt, network/src/main/kotlin/com/bitwarden/network/model/TrustedDeviceKeysResponseJson.kt
M-19855
Migrate AuthenticatedDevicesApi and models to network module
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit …
=> [PM-19855] Migrate AuthenticatedDevicesApi and models to network module

app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/service/HaveIBeenPwnedServiceImpl.kt, app/src/test/java/com/x8bit/bitwarden/data/auth/datasource/network/service/HaveIBeenPwnedServiceTest.kt, network/src/main/kotlin/com/bitwarden/network/api/HaveIBeenPwnedApi.kt
PM-19858
Move HaveIBeenPwnedApi to the `network` module …
=> [PM-19858] Migrate HaveIBeenPwnedApi to network module

app/build.gradle.kts
N/A
This PR bumps the internal version name to `2025.4.0` in order to ensure current debug builds interact with the server in an expected manner. …
=> Bump internal version name

app/src/main/java/com/x8bit/bitwarden/data/platform/repository/model/FlightRecorderDuration.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/text/BitwardenHyperTextLink.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/FlightRecorderScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/FlightRecorderViewModel.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/util/FlightRecorderDurationExtensions.kt, app/src/main/res/values/strings.xml, app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/FlightRecorderScreenTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/FlightRecorderViewModelTest.kt
PM-19978
This PR adds the UI for enabling the flight recorder.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from …
=> PM-19978: Build out flight recorder UI

app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/service/OrganizationService.kt, app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/service/OrganizationServiceImpl.kt, app/src/main/java/com/x8bit/bitwarden/data/auth/repository/model/VerifiedOrganizationDomainSsoDetailsResult.kt, app/src/test/java/com/x8bit/bitwarden/data/auth/datasource/network/service/OrganizationServiceTest.kt, app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/auth/feature/enterprisesignon/EnterpriseSignOnViewModelTest.kt, network/src/main/kotlin/com/bitwarden/network/api/UnauthenticatedOrganizationApi.kt, network/src/main/kotlin/com/bitwarden/network/model/OrganizationDomainSsoDetailsRequestJson.kt, network/src/main/kotlin/com/bitwarden/network/model/OrganizationDomainSsoDetailsResponseJson.kt, network/src/main/kotlin/com/bitwarden/network/model/VerifiedOrganizationDomainSsoDetailsRequest.kt, network/src/main/kotlin/com/bitwarden/network/model/VerifiedOrganizationDomainSsoDetailsResponse.kt
PM-19864
Moved organization single sign-on (SSO) related components from the `app` module to the `network` module. This includes API definitions, request/response, and models. …
=> [PM-19864] Migrate UnauthenticatedOrganizationApi to `network` module

app/src/main/java/com/x8bit/bitwarden/data/platform/manager/di/PlatformManagerModule.kt, app/src/main/java/com/x8bit/bitwarden/data/platform/manager/flightrecorder/FlightRecorderManager.kt, app/src/main/java/com/x8bit/bitwarden/data/platform/manager/flightrecorder/FlightRecorderManagerImpl.kt, app/src/main/java/com/x8bit/bitwarden/data/platform/manager/flightrecorder/FlightRecorderWriter.kt, app/src/main/java/com/x8bit/bitwarden/data/platform/manager/flightrecorder/FlightRecorderWriterImpl.kt, app/src/main/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepository.kt, app/src/main/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepositoryImpl.kt, app/src/main/java/com/x8bit/bitwarden/data/platform/repository/di/PlatformRepositoryModule.kt, app/src/main/java/com/x8bit/bitwarden/data/vault/manager/FileManager.kt, app/src/main/java/com/x8bit/bitwarden/data/vault/manager/FileManagerImpl.kt, app/src/test/java/com/x8bit/bitwarden/data/platform/datasource/disk/util/FakeSettingsDiskSource.kt, app/src/test/java/com/x8bit/bitwarden/data/platform/manager/flightrecorder/FlightRecorderManagerTest.kt, app/src/test/java/com/x8bit/bitwarden/data/platform/repository/SettingsRepositoryTest.kt
[PM-20133](https://bitwarden.atlassian.net/browse/PM-20133)
This PR implements the underlying logic for creating and writing to a file on disk for the flight recorder feature. …
=> PM-20133: Add initial logging logic

app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/network/di/PlatformNetworkModule.kt, app/src/main/java/com/x8bit/bitwarden/data/platform/manager/PushManagerImpl.kt, app/src/main/java/com/x8bit/bitwarden/data/platform/manager/di/PlatformManagerModule.kt, app/src/test/java/com/x8bit/bitwarden/data/platform/manager/PushManagerTest.kt, network/src/main/kotlin/com/bitwarden/network/service/PushService.kt, network/src/main/kotlin/com/bitwarden/network/service/PushServiceImpl.kt, network/src/test/kotlin/com/bitwarden/network/service/PushServiceTest.kt
PM-20067
Moved `PushService` and `PushServiceImpl` from the `app` module to the `network` module. Removed the old implementations and interfaces from the `app` module. Updated all usages of `PushService` to use the new implementation in `network`. Added a service module to `network` that provides `PushServiceImpl`. …
=> [PM-20067] Migrate PushService to the network module

app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/network/di/PlatformNetworkModule.kt, app/src/main/java/com/x8bit/bitwarden/data/platform/manager/di/PlatformManagerModule.kt, app/src/main/java/com/x8bit/bitwarden/data/platform/manager/event/OrganizationEventManagerImpl.kt, app/src/test/java/com/x8bit/bitwarden/data/platform/manager/event/OrganizationEventManagerTest.kt, network/src/main/kotlin/com/bitwarden/network/service/EventService.kt, network/src/main/kotlin/com/bitwarden/network/service/EventServiceImpl.kt, network/src/test/kotlin/com/bitwarden/network/service/EventServiceTest.kt
PM-20066
Moved `EventService` and `EventServiceImpl` from the `app` module to the `network` module.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue …
=> [PM-20066] Migrate EventService and EventServiceImpl to network module

app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/di/AuthNetworkModule.kt, app/src/main/java/com/x8bit/bitwarden/data/auth/manager/TrustedDeviceManagerImpl.kt, app/src/main/java/com/x8bit/bitwarden/data/auth/manager/di/AuthManagerModule.kt, app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt, app/src/main/java/com/x8bit/bitwarden/data/auth/repository/di/AuthRepositoryModule.kt, app/src/test/java/com/x8bit/bitwarden/data/auth/manager/TrustedDeviceManagerTests.kt, app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt, network/src/main/kotlin/com/bitwarden/network/service/DevicesService.kt, network/src/main/kotlin/com/bitwarden/network/service/DevicesServiceImpl.kt, network/src/test/kotlin/com/bitwarden/network/service/DevicesServiceTest.kt
PM-20187
Migrated `DevicesService` and `DevicesServiceImpl` from the `app` module to the `network` module.
Removed duplicate implementations and interfaces from the `app` module.
Updated all usages of `DevicesService` to use the new implementation in `network`.
Added `DevicesServiceTest` to `network` module. …
=> [PM-20187] Migrate DevicesService to the network module

app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/di/VaultNetworkModule.kt, app/src/main/java/com/x8bit/bitwarden/data/vault/manager/CipherManagerImpl.kt, app/src/main/java/com/x8bit/bitwarden/data/vault/manager/di/VaultManagerModule.kt, app/src/main/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryImpl.kt, app/src/main/java/com/x8bit/bitwarden/data/vault/repository/di/VaultRepositoryModule.kt, app/src/test/java/com/x8bit/bitwarden/data/vault/manager/CipherManagerTest.kt, app/src/test/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt, network/src/main/kotlin/com/bitwarden/network/model/AttachmentInfo.kt, network/src/main/kotlin/com/bitwarden/network/model/ImportCiphersResponseJson.kt, network/src/main/kotlin/com/bitwarden/network/model/UpdateCipherResponseJson.kt, network/src/main/kotlin/com/bitwarden/network/service/CiphersService.kt, network/src/main/kotlin/com/bitwarden/network/service/CiphersServiceImpl.kt, network/src/test/kotlin/com/bitwarden/network/model/AttachmentInfoUtil.kt, network/src/test/kotlin/com/bitwarden/network/service/CiphersServiceTest.kt
PM-20192
Move the `CiphersService`, along with its implementation and related models (`ImportCiphersResponseJson`, `UpdateCipherResponseJson`) from the `app` module to the `network` module. Also move `CiphersServiceTest` to the `network` module.
-   **CiphersService and implementation**: Moved `CiphersService` and `CiphersServiceImpl` from the `app` module to the `network` module.
-   **Models**: Moved `ImportCiphersResponseJson` and `UpdateCipherResponseJson` to the `network` module.
- **`CiphersServiceTest`:** Move this class to the `network` module.
-   **Dependencies:** Updated all dependencies on `CiphersService`, `ImportCiphersResponseJson` and `UpdateCipherResponseJson` to point to the new locations in the `network` module.
-   **Add AttachmentInfo:** Add this class to describe …
=> [PM-20192] Migrate CiphersService to network module

app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/network/di/VaultNetworkModule.kt, app/src/main/java/com/x8bit/bitwarden/data/vault/manager/FileManagerImpl.kt, app/src/main/java/com/x8bit/bitwarden/data/vault/manager/di/VaultManagerModule.kt, network/src/main/kotlin/com/bitwarden/network/service/DownloadService.kt, network/src/main/kotlin/com/bitwarden/network/service/DownloadServiceImpl.kt, network/src/test/kotlin/com/bitwarden/network/service/DownloadServiceTest.kt
PM-20193
Moved `DownloadService` and `DownloadServiceImpl` from the `app` module to the `network` module. Removed duplicate implementations and interfaces from the `app` module. Updated all usages of `DownloadService` to use the new implementation in `network`. Added a new test for `DownloadService` to `network` module. Removed old `DownloadServiceTest`.
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation …
=> [PM-20193] Migrate DownloadService to `network` module

app/src/main/java/com/x8bit/bitwarden/data/platform/manager/flightrecorder/FlightRecorderManagerImpl.kt, app/src/test/java/com/x8bit/bitwarden/data/platform/manager/flightrecorder/FlightRecorderManagerTest.kt
[PM-19620](https://bitwarden.atlassian.net/browse/PM-19620)
The log files should auto-delete themselves after the expiration date (30 days after logging completes). …
=> PM-19620: Auto-delete flight recorder logs after 30 days

app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/blockautofill/BlockAutoFillScreen.kt
[PM-20426](https://bitwarden.atlassian.net/browse/PM-20426)
This PR updates the Block Autofill UI to display the illustration properly (size and spacing). I also cleaned up the dialogs a little bit 😄.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/6095153a-262f-4c4e-bd23-b299d9af5a3b" width="300" /> | <img src="https://github.com/user-attachments/assets/d44bb76e-52d3-4d20-ad6c-ac0415e75c79" width="300" /> |
- …
=> PM-20426: Update Block Autofill UI

app/src/main/java/com/x8bit/bitwarden/data/platform/datasource/disk/di/PlatformDiskModule.kt, app/src/main/java/com/x8bit/bitwarden/data/vault/datasource/disk/di/VaultDiskModule.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/theme/BitwardenTheme.kt
N/A
This PR fixes a handful of minor lint warnings, no functionality has changed in this PR. …
=> Cleanup minor lint warnings

app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/about/AboutScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/FlightRecorderScreen.kt, app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/about/AboutScreenTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/flightrecorder/FlightRecorderScreenTest.kt
[PM-19809](https://bitwarden.atlassian.net/browse/PM-19809)
This PR updates the Flight Recorder help link. …
=> PM-19809: Update flight recorder tooltip url

app/src/main/java/com/x8bit/bitwarden/MainActivity.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/util/RememberBitwardenNavController.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/rootnav/RootNavScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarScreen.kt
[PM-20510](https://bitwarden.atlassian.net/browse/PM-20510)
This PR adds logging whenever the screen destination changes. …
=> PM-20510: Log whenever the screen changes

gradle/libs.versions.toml
N/A
Update to the latest version of JUnit (v5.12.2).
[Release Notes!](https://junit.org/junit5/docs/current/release-notes/index.html#release-notes-5.12.2) …
=> Update to Junit 5.12.2

app/src/main/java/com/x8bit/bitwarden/data/platform/manager/flightrecorder/FlightRecorderManagerImpl.kt, app/src/main/java/com/x8bit/bitwarden/data/vault/manager/VaultLockManagerImpl.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/coachmark/CoachMarkState.kt, core/src/main/kotlin/com/bitwarden/core/data/util/MapUtil.kt
N/A
This PR adds a helper function for creating a Concurrent Map.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from …
=> Add helper for concurrent map

gradle/libs.versions.toml
N/A
This PR updates the app to use the latest version of AGP (v8.9.2).
[Release Notes!](https://developer.android.com/build/releases/gradle-plugin#android-gradle-plugin-8.9.2) …
=> Update to AGP 8.9.2

app/src/main/java/com/x8bit/bitwarden/BitwardenApplication.kt, app/src/main/java/com/x8bit/bitwarden/data/auth/manager/UserLogoutManagerImpl.kt, app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/manager/AccessibilityNodeInfoManagerImpl.kt, app/src/main/java/com/x8bit/bitwarden/data/platform/manager/AppStateManagerImpl.kt, app/src/main/java/com/x8bit/bitwarden/data/platform/manager/network/NetworkConnectionManagerImpl.kt, app/src/main/java/com/x8bit/bitwarden/data/platform/repository/EnvironmentRepositoryImpl.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/components/util/RememberBitwardenNavController.kt, app/src/test/java/com/x8bit/bitwarden/data/platform/repository/EnvironmentRepositoryTest.kt
[
PM-20966](https://bitwarden.atlassian.net/browse/PM-20966)
This PR adds some general logging to the app.  …
=> PM-20966: Log app state changes

app/src/main/java/com/x8bit/bitwarden/data/autofill/accessibility/processor/BitwardenAccessibilityProcessorImpl.kt, app/src/test/java/com/x8bit/bitwarden/data/autofill/accessibility/processor/BitwardenAccessibilityProcessorTest.kt
PM-17222
Relates to #4586 
Enhance the autofill accessibility processor by only processing events when the Quick Tile is clicked.
Additionally, logs are added to record when an event node is skipped due to one of declared restrictions. 
- …
=> [PM-17222] Enhance autofill accessibility processor

gradle/libs.versions.toml
N/A
This PR updates the Dagger Hilt library to the latest version (v2.56.2).
[Release Notes!](https://github.com/google/dagger/releases/tag/dagger-2.56.2) …
=> Update Dagger Hilt to v2.56.2

gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties
N/A
This PR updates the Android Gradle Plugin to the latest version (v8.10.0).
* [Release Notes!](https://developer.android.com/build/releases/gradle-plugin#android-gradle-plugin-8.10.0)
- 🤔 (`:thinking:`) …
=> Update AGP to 8.10.0

app/src/main/java/com/x8bit/bitwarden/data/platform/manager/util/AppResumeStateManager.kt, app/src/main/java/com/x8bit/bitwarden/ui/auth/feature/twofactorlogin/TwoFactorLoginScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/pendingrequests/PendingRequestsScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorScreen.kt, app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/vault/VaultScreen.kt, ui/src/main/java/com/bitwarden/ui/platform/base/util/LifecycleEventEffect.kt
PM-21355
The `LivecycleEventEffect` has been moved from the `app` module to a `ui` common module.
Also, renamed LivecycleEventEffect to LifecycleEventEffect to correct a typo. …
=> [PM-21355] Migrate LifecycleEventEffect to ui module

app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/send/addsend/AddSendContent.kt
[PM-21445](https://bitwarden.atlassian.net/browse/PM-21445)
This PR updates the Add/Edit Sends UI to match the latest comps, this change is being done ahead of the View Sends UI.
No tests changed because the everything functions the same, I just moved things around.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/73348251-564c-4dec-99cd-ba422735d03b" width="300" /> | <img src="https://github.com/user-attachments/assets/01ec0ba3-e58b-4d0b-bef0-023fbf80bb71" width="300" /> |
| <img src="https://github.com/user-attachments/assets/dd307abb-ae00-4513-961d-e1d8cffbf9e4" width="300" /> | <img src="https://github.com/user-attachments/assets/07cb4aa2-d39a-4c14-bdc4-bb914f2c7f14" width="300" /> |
| <img …
=> PM-21445: Update Add Edit Sends UI

.github/workflows/scan.yml
[BRE-609](https://bitwarden.atlassian.net/browse/BRE-609) 
edit workflow to ensure pull_request_target event triggers only target main, and that pull_request event triggers target main, rc, hotfix-* so things continue to work as expected …
=> BRE-609/android-pr-target-change

app/src/test/java/com/x8bit/bitwarden/ui/platform/feature/settings/other/OtherScreenTest.kt, app/src/test/java/com/x8bit/bitwarden/ui/vault/feature/movetoorganization/VaultMoveToOrganizationScreenTest.kt, authenticator/src/test/java/com/bitwarden/authenticator/ui/platform/feature/debugmenu/DebugMenuScreenTest.kt
N/A
This PR removes some logs from tests.
- 🎨 (`:art:`) …
=> Remove logging from tests

app/src/main/java/com/x8bit/bitwarden/ui/platform/base/util/ModifierExtensions.kt, ui/build.gradle.kts, ui/src/main/java/com/bitwarden/ui/platform/base/util/TopAppBarScrollBehaviorExtensions.kt, ui/src/test/kotlin/com/bitwarden/ui/platform/base/util/TopAppBarScrollBehaviorExtensionsTest.kt
PM-21361
Move TopAppBarScrollBehaviorExtensions to the shared `ui` module. …
=> [PM-21361] Migrate TopAppBarScrollBehaviorExtensions to `ui` module

app/src/main/java/com/x8bit/bitwarden/ui/platform/theme/BitwardenTheme.kt, ui/src/main/java/com/bitwarden/ui/platform/theme/shape/BitwardenShapes.kt, ui/src/main/java/com/bitwarden/ui/platform/theme/shape/Shapes.kt
PM-21655
PM-21656
Move the shapes package from the app module to the ui module. …
=> [PM-21655] Migrate BitwardenShapes to `ui` module

app/src/test/java/com/x8bit/bitwarden/data/auth/repository/util/SyncResponseJsonExtensionsTest.kt, app/src/test/java/com/x8bit/bitwarden/data/vault/manager/CipherManagerTest.kt, app/src/test/java/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt, app/src/test/java/com/x8bit/bitwarden/data/vault/repository/util/VaultSdkCipherExtensionsTest.kt, network/src/test/kotlin/com/bitwarden/network/service/CiphersServiceTest.kt, network/src/testFixtures/kotlin/com/bitwarden/network/model/AttachmentJsonRequestUtil.kt, network/src/testFixtures/kotlin/com/bitwarden/network/model/AttachmentJsonResponseUtil.kt, network/src/testFixtures/kotlin/com/bitwarden/network/model/CipherJsonRequestUtil.kt, network/src/testFixtures/kotlin/com/bitwarden/network/model/SendJsonRequestUtil.kt, network/src/testFixtures/kotlin/com/bitwarden/network/model/SyncResponseCipherUtil.kt, network/src/testFixtures/kotlin/com/bitwarden/network/model/SyncResponseCollectionUtil.kt, network/src/testFixtures/kotlin/com/bitwarden/network/model/SyncResponseDomainsUtil.kt, network/src/testFixtures/kotlin/com/bitwarden/network/model/SyncResponseFolderUtil.kt, network/src/testFixtures/kotlin/com/bitwarden/network/model/SyncResponsePolicyUtil.kt, network/src/testFixtures/kotlin/com/bitwarden/network/model/SyncResponseProfileUtil.kt, network/src/testFixtures/kotlin/com/bitwarden/network/model/SyncResponseSendUtil.kt, network/src/testFixtures/kotlin/com/bitwarden/network/model/SyncResponseUtil.kt
N/A
This PR updates the test fixtures in the `network` module to allow for easier customization.
This does not change any functional code and these changes only apply to tests. …
=> Update test fixtures to allow for easier customization

.github/workflows/build.yml, .github/workflows/test.yml
- [BRE-552](https://bitwarden.atlassian.net/browse/BRE-552?atlOrigin=eyJpIjoiZDI5NjZjMDY0YjIzNGViNTkwYmJkZmNkMTNjZGViNjAiLCJwIjoiaiJ9)
This PR fixes findings found by `Actionlint` to prepare for flipping the `Actionlint` rule for the workflow linter to `error`.
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) …
=> [BRE-552] Fix Actionlint findings

.github/workflows/build-authenticator.yml, .github/workflows/build.yml, .github/workflows/crowdin-pull-authenticator.yml, .github/workflows/crowdin-pull.yml, .github/workflows/crowdin-push-authenticator.yml, .github/workflows/crowdin-push.yml, .github/workflows/github-release.yml, .github/workflows/scan.yml
https://bitwarden.atlassian.net/browse/PM-21825
Updating workflows missing permissions.
Test runs:
* github-release.yml - https://github.com/bitwarden/android/actions/runs/15148111568/job/42588593310
* build.yml - https://github.com/bitwarden/android/actions/runs/15148830802
* build-authenticator.yml - https://github.com/bitwarden/android/actions/runs/15148837122
* crowdin-pull.yml - https://github.com/bitwarden/android/actions/runs/15148860858
* crowdin-push.yml - https://github.com/bitwarden/android/actions/runs/15148844776
* scan.yml - https://github.com/bitwarden/android/actions/runs/15148926433
crowdin-push-authenticator.yml and crowdin-pull-authenticator.yml were broken (unrelated to these permissions change) and will be fixed in a future PR.
Linter output:
```
➜  android …
```
=> [PM-21825] Set missing workflow permissions

app/src/main/AndroidManifest.xml, authenticator/src/main/AndroidManifest.xml, gradle/libs.versions.toml
N/A
This commit updates the target and compile SDK versions to 36 (Android VanillaIceCream).
Additionally, `android:intentMatchingFlags="enforceIntentFilter"` has been added to the `AndroidManifest.xml` for both the main app and authenticator modules. This flag, introduced in Android 15 (upside-down cake) and enforced in Android 16 (vanilla ice cream), ensures that intents are only delivered to components that have explicitly declared matching intent filters. This enhances app security by preventing unintended component invocation.
[Release notes](https://developer.android.com/about/versions/16)
- Protected functional changes with …
=> Update target and compile SDK to 36

app/src/test/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryTest.kt, network/src/main/kotlin/com/bitwarden/network/model/DeleteAccountResponseJson.kt
https://bitwarden.atlassian.net/browse/PM-21405
Display delete account server error messages.
<p align="center">
</p> …
=> [PM-21405] Delete account error message

authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/ItemListingScreen.kt, authenticator/src/test/java/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/ItemListingScreenTest.kt
PM-21386
Cherry picking #5220 (commit 183584f67838fa3d01ab3a59d06f5a786a7506c7)
This is a cherry-pick from #5220 to the 2025.5 release candidate branch. …
=> 🍒[PM-21386] Fix typo in sync with Bitwarden message

app/src/main/AndroidManifest.xml, app/src/main/kotlin/com/x8bit/bitwarden/MainActivity.kt, app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/item/util/CipherViewExtensions.kt, app/src/main/res/values/styles.xml, authenticator/src/main/AndroidManifest.xml, authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/platform/theme/AuthenticatorTheme.kt
N/A
This PR should not change any functionality but cleans up some minor lint warnings. …
=> Clean up lint errors and suppressions

.github/workflows/test-device.yml
[QA-1126](https://bitwarden.atlassian.net/browse/QA-1126)
Add placeholder workflow for device farm testing. …
=> [QA-1126] Add placeholder workflow for device farm testing

.github/scripts/jira-get-release-notes/README.md, .github/scripts/jira-get-release-notes/jira_release_notes.py, .github/scripts/jira-get-release-notes/main.py, .github/scripts/jira-get-release-notes/pyproject.toml, .github/scripts/jira-get-release-notes/uv.lock, .github/workflows/github-release.yml
https://bitwarden.atlassian.net/browse/PM-22437
Automate adding product release notes to GitHub Releases.  …
=> [PM-22437] Add product release notes to GitHub Releases

data/src/test/kotlin/com/bitwarden/data/repository/util/DataStateExtensionsTest.kt
PM-19625
The file `DataStateExtensionsTest.kt` was moved from the `app` module to the `data` module.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue …
=> [PM-19625] Move DataStateExtensionsTest to data module

network/src/main/kotlin/com/bitwarden/network/BitwardenServiceClientImpl.kt
[PM-22874](https://bitwarden.atlassian.net/browse/PM-22874)
[PM-22846](https://bitwarden.atlassian.net/browse/PM-22846)
This PR fixes the base domain for the events API by instantiating it with the correct Retrofit instance.
- ❓ …
=> PM-22874: Fix Events service domain

app/build.gradle.kts, authenticator/build.gradle.kts, build.gradle.kts, gradle/libs.versions.toml
N/A
This PR adds the Room Gradle plugin to the app in order to streamline Room configuration and remove some minor warnings. …
=> Add Room Gradle plugin

app/src/main/kotlin/com/x8bit/bitwarden/data/autofill/model/AutofillAppInfo.kt, app/src/main/kotlin/com/x8bit/bitwarden/data/autofill/util/FillRequestExtensions.kt, app/src/main/kotlin/com/x8bit/bitwarden/data/autofill/util/FilledDataExtensions.kt, app/src/main/kotlin/com/x8bit/bitwarden/data/autofill/util/FilledPartitionExtensions.kt, app/src/test/kotlin/com/x8bit/bitwarden/data/autofill/util/FillRequestExtensionsTest.kt
N/A
This PR improves our version checking inside the Autofill feature to avoid unnecessary APIs suppression's.
No functionality has changed in this PR. …
=> Improve autofill version checking

gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties
N/A
This PR updates AGP to the latest version (v8.11.0)
[Release Notes!](https://developer.android.com/build/releases/gradle-plugin#android-gradle-plugin-8.11.0) …
=> Update to AGP v8.11.0

app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/search/SearchViewModel.kt, app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/search/SearchScreenTest.kt, app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/search/SearchViewModelTest.kt
https://bitwarden.atlassian.net/browse/PM-19309
Apply restrict item policy when searching items.
https://github.com/user-attachments/assets/35a9cef2-e414-4473-a5d8-8ca45f796711 …
=> [PM-19309] Fix search when restrict item policy is enabled

app/src/main/kotlin/com/x8bit/bitwarden/data/platform/repository/AuthenticatorBridgeRepositoryImpl.kt, app/src/main/kotlin/com/x8bit/bitwarden/data/platform/repository/di/PlatformRepositoryModule.kt, app/src/test/kotlin/com/x8bit/bitwarden/data/platform/repository/AuthenticatorBridgeRepositoryTest.kt
[PM-23774](https://bitwarden.atlassian.net/browse/PM-23774)
This PR simplifies the dependencies of the `AuthenticatorBridgeRepositoryImpl` …
=> PM-23774: Simplify AuthenticatorBridgeRepositoryImpl

app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/manager/intent/IntentManagerImpl.kt
[VULN-261](https://bitwarden.atlassian.net/browse/VULN-261)
This PR filters out all Send intents that utilize our own content provider. This prevents a malicious user from sending out own private data out as a Send. …
=> VULN-261: Filter out send intents that use our own content provider

app/build.gradle.kts, authenticator/build.gradle.kts
N/A
This PR updates the version name for debug builds.
- …
=> Update the version name to 2025.7.0

.github/workflows/build-authenticator.yml, .github/workflows/build.yml, .github/workflows/crowdin-pull.yml, .github/workflows/crowdin-push.yml, .github/workflows/github-release.yml, .github/workflows/scan-ci.yml, .github/workflows/scan.yml
[BRE-831](https://bitwarden.atlassian.net/browse/BRE-831)
Updating to use Azure Key Vault Secrets in place of GitHub secrets.
All GitHub secrets have been migrated to the repository's respective Key Vault.
Azure Service Principals have been updated to use Managed Identities with OIDC. …
=> 🍒 [BRE-831] migrate secrets akv (#5347)

app/src/main/kotlin/com/x8bit/bitwarden/data/auth/util/PasswordlessRequestDataUtils.kt, app/src/main/kotlin/com/x8bit/bitwarden/data/autofill/util/AutofillIntentUtils.kt, app/src/main/kotlin/com/x8bit/bitwarden/ui/credentials/manager/CredentialProviderCompletionManager.kt, app/src/main/kotlin/com/x8bit/bitwarden/ui/credentials/manager/CredentialProviderCompletionManagerImpl.kt, app/src/main/kotlin/com/x8bit/bitwarden/ui/credentials/manager/CredentialProviderCompletionManagerUnsupportedApiImpl.kt, app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/SettingsViewModel.kt, app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/vaultunlockednavbar/VaultUnlockedNavBarViewModel.kt, app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/manager/nfc/NfcManagerImpl.kt, app/src/main/kotlin/com/x8bit/bitwarden/ui/tools/feature/send/SendViewModel.kt, app/src/main/kotlin/com/x8bit/bitwarden/ui/tools/feature/send/model/SendStatusIcon.kt, app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/components/model/CreateVaultItemType.kt, app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/model/VaultTrailingIcon.kt, authenticator/src/main/kotlin/com/bitwarden/authenticator/data/authenticator/datasource/disk/entity/AuthenticatorItemAlgorithm.kt, authenticator/src/main/kotlin/com/bitwarden/authenticator/data/authenticator/datasource/disk/entity/AuthenticatorItemType.kt, authenticator/src/main/kotlin/com/bitwarden/authenticator/data/authenticator/repository/AuthenticatorRepository.kt, authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/model/ItemListingExpandableFabAction.kt, authenticator/src/main/kotlin/com/bitwarden/authenticator/ui/platform/components/dialog/BitwardenLoadingDialog.kt, ui/src/main/kotlin/com/bitwarden/ui/platform/components/content/model/ContentBlockData.kt, ui/src/main/kotlin/com/bitwarden/ui/platform/components/icon/model/IconData.kt, ui/src/main/kotlin/com/bitwarden/ui/util/Text.kt
N/A
This PR cleans up some lint warnings and imports.
- …
=> Fix lint warnings and imports

gradle/libs.versions.toml
N/A
This PR updates Junit to the latest version (v5.13.4)
[Release notes!](https://docs.junit.org/5.13.3/release-notes/#release-notes-5.13.4) …
=> Update Junit to v5.13.4

app/build.gradle.kts, authenticator/build.gradle.kts, authenticatorbridge/build.gradle.kts, gradle/wrapper/gradle-wrapper.properties, settings.gradle.kts
N/A
This PR updates Gradle to v9.0.0.
[Release Notes!](https://docs.gradle.org/9.0.0/release-notes.html) …
=> Update to Gradle v9.0.0

app/src/main/kotlin/com/x8bit/bitwarden/data/vault/datasource/sdk/VaultSdkSource.kt, app/src/main/kotlin/com/x8bit/bitwarden/data/vault/datasource/sdk/VaultSdkSourceImpl.kt, app/src/main/kotlin/com/x8bit/bitwarden/data/vault/repository/VaultRepository.kt, app/src/main/kotlin/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryImpl.kt, app/src/main/kotlin/com/x8bit/bitwarden/data/vault/repository/model/VaultData.kt, app/src/main/kotlin/com/x8bit/bitwarden/data/vault/repository/util/VaultSdkCollectionExtensions.kt, app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/search/util/SearchTypeDataExtensions.kt, app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/addedit/util/CipherViewExtensions.kt, app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/itemlisting/util/VaultItemListingDataExtensions.kt, app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/movetoorganization/VaultMoveToOrganizationViewModel.kt, app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/movetoorganization/util/VaultMoveToOrganizationViewExtensions.kt, app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/util/CollectionViewExtensions.kt, app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/vault/util/VaultDataExtensions.kt, app/src/test/kotlin/com/x8bit/bitwarden/data/vault/datasource/sdk/VaultSdkSourceTest.kt, app/src/test/kotlin/com/x8bit/bitwarden/data/vault/datasource/sdk/model/CollectionViewUtil.kt, app/src/test/kotlin/com/x8bit/bitwarden/data/vault/datasource/sdk/model/VaultSdkCollectionUtil.kt, app/src/test/kotlin/com/x8bit/bitwarden/data/vault/repository/VaultRepositoryTest.kt, app/src/test/kotlin/com/x8bit/bitwarden/data/vault/repository/util/VaultSdkCollectionExtensionsTest.kt, app/src/test/kotlin/com/x8bit/bitwarden/ui/platform/feature/search/util/SearchTypeDataExtensionsTest.kt, app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModelTest.kt, app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/item/VaultItemViewModelTest.kt, app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/movetoorganization/VaultMoveToOrganizationViewModelTest.kt, app/src/test/kotlin/com/x8bit/bitwarden/ui/vault/feature/util/CollectionViewExtensionsTest.kt, gradle/libs.versions.toml
[PM-24456](https://bitwarden.atlassian.net/browse/PM-24456)
Update bitwarden sdk to 1.0.0-2450-9fe3aeda. …
=> [PM-24456] Update bitwarden sdk to 1.0.0-2450-9fe3aeda

app/build.gradle.kts, authenticator/build.gradle.kts
N/A
Fix publishing errors in the build workflows. Failures are due to removal of a deprecated gradle property. The property is now set using the replacement API. …
=> Set base.archivesName for app and authenticator modules

app/src/main/kotlin/com/x8bit/bitwarden/BitwardenApplication.kt, app/src/main/kotlin/com/x8bit/bitwarden/data/platform/manager/di/PlatformManagerModule.kt, app/src/main/kotlin/com/x8bit/bitwarden/data/platform/manager/restriction/RestrictionManager.kt, app/src/main/kotlin/com/x8bit/bitwarden/data/platform/manager/restriction/RestrictionManagerImpl.kt, app/src/main/kotlin/com/x8bit/bitwarden/data/platform/repository/EnvironmentRepository.kt, app/src/main/kotlin/com/x8bit/bitwarden/data/platform/repository/EnvironmentRepositoryImpl.kt, app/src/test/kotlin/com/x8bit/bitwarden/data/platform/manager/restriction/RestrictionManagerTest.kt, app/src/test/kotlin/com/x8bit/bitwarden/data/platform/repository/EnvironmentRepositoryTest.kt, app/src/test/kotlin/com/x8bit/bitwarden/data/platform/repository/util/FakeEnvironmentRepository.kt
[PM-24726](https://bitwarden.atlassian.net/browse/PM-24726)
This PR updates the MDM functionality.
- The MDM data is only applied at startup and is applied before the `EnvironmentRepository` applies any of it's changes.
- It is no longer applied on foreground.
- It is no longer applied when the value is changed in realtime.
- When applying the MDM server URL, we completely overwrite the previous values. …
=> PM-24726: Update MDM functionality

app/src/main/kotlin/com/x8bit/bitwarden/AutofillTotpCopyViewModel.kt, app/src/main/kotlin/com/x8bit/bitwarden/data/autofill/builder/FillResponseBuilderImpl.kt, app/src/main/kotlin/com/x8bit/bitwarden/data/autofill/manager/AutofillCompletionManagerImpl.kt, app/src/main/kotlin/com/x8bit/bitwarden/data/autofill/parser/AutofillParserImpl.kt, app/src/main/kotlin/com/x8bit/bitwarden/data/platform/manager/flightrecorder/FlightRecorderManagerImpl.kt
N/A
This PR improves the logs for autofill to better track issues.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from …
=> Update Autofill logging

app/src/main/kotlin/com/x8bit/bitwarden/ui/auth/feature/landing/LandingViewModel.kt, ui/src/main/kotlin/com/bitwarden/ui/platform/base/util/StringExtensions.kt, ui/src/test/kotlin/com/bitwarden/ui/platform/base/util/StringExtensionsTest.kt
PM-24700
Resolves #5687
The email validation in `LandingViewModel` was updated to use non-strict validation. The `isValidEmail` extension function was also updated to include a `useStrictValidation` parameter to control the validation behavior.
https://github.com/user-attachments/assets/4ad569fc-bb48-4feb-b7ef-9fc808a4b5ce …
=> [PM-24700] Update email validation in LandingViewModel

app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/SettingsScreen.kt, app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/about/AboutScreen.kt, app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/accountsecurity/AccountSecurityScreen.kt, app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/AutoFillScreen.kt, app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/autofill/privilegedapps/list/PrivilegedAppsListScreen.kt, app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/folders/FoldersScreen.kt, app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/settings/vault/VaultSettingsScreen.kt, ui/src/main/kotlin/com/bitwarden/ui/platform/components/row/BitwardenExternalLinkRow.kt, ui/src/main/kotlin/com/bitwarden/ui/platform/components/row/BitwardenPushRow.kt, ui/src/main/kotlin/com/bitwarden/ui/platform/components/row/BitwardenTextRow.kt
[PM-25006](https://bitwarden.atlassian.net/browse/PM-25006)
This PR migrates the row package to the `ui` module. …
=> PM-25006: Migrate row components to the UI module

gradle/libs.versions.toml
N/A
This PR updates AGP to the latest version (v8.12.2).
[Release Notes!](https://developer.android.com/build/releases/gradle-plugin#android-gradle-plugin-8.12.2) …
=> Update AGP to v8.12.2

gradle/libs.versions.toml
N/A
This PR bumps the `update-app-version-name` to `2025.9.1` to keep it up-to-date with current releases. …
=> Update appVersionName to 2025.9.1

app/src/main/kotlin/com/x8bit/bitwarden/ui/platform/feature/debugmenu/DebugMenuScreen.kt, ui/src/main/kotlin/com/bitwarden/ui/platform/components/debug/FeatureFlagListItems.kt
[PM-26445](https://bitwarden.atlassian.net/browse/PM-26445)
This PR moves the debug menu components to the UI module. …
=> PM-26445: Common Debug menu components

.github/renovate.json
n/a
We can't update Glide for the time being, excluding it from group so we're able to merge other dependencies. 
* https://bumptech.github.io/glide/int/compose.html#status
* https://github.com/bumptech/glide/issues/5512
- ❓ …
=> Update renovate.json to exclude com.github.bumptech.glide from gradle-minor group
